### ISSUE TITLE
How to show/hide markers after an initialization with onPressed: ()?

### ISSUE THREAD

**Issue by PaulKsi** [fleaflet/flutter_map#1005]
Hello, 
let`s say you initialize marker array
```
List<Marker> marker_array = [];
```
then add a marker somewhere
```
Marker mark1= Marker(
      width: 30,
      height: 30,
      point: LatLng(54.268741, 23.330198),
      builder: (ctx) => Container(
          child: GestureDetector(
        onTap: () {
          setState(() {
            showMarkerPopUp = true;
            popUpTxt = "MARKER1";
          });
        },
        child: Icon(
          Icons.circle,
          size: 30,
          color: Colors.green, //
        ),
      )),
    );
    marker_array.add(mark1);
```
how to show/hide markers after an initialization, with a button press -  onPressed: ()?  Thank you!

**Comment by ibrierley** [comment]
Just remove it from the list (assuming you are doing a setState or similar somewhere to update the screen) when button pressed ? Or I guess your builder could return just a container or something (can't remember if null is allowed). You can also use a MarkerLayerWidget and a widgetlayer if thats more useful for some reason.

**Comment by PaulKsi** [comment]
thanks
