### ISSUE TITLE
Zoom centers regarding center of map instead of gesture

### ISSUE THREAD

**Issue by pawelsa** [fleaflet/flutter_map#1006]
I have an issue while zooming where the center of my gesture is not zoomed in. It seems as it is biased by the map center when zooming, the closer the gesture is done to the center the more accurate the zooming is. It may be caused by my configuration. You can see what I mean in the video:

https://user-images.githubusercontent.com/23721547/131499288-9aaff920-2360-4679-a0b8-503e965ce131.mp4

Code used in the video:

```dart
Widget build(BuildContext context) {
    return Scaffold(
      body: FlutterMap(
        mapController: _mapController,
        options: MapOptions(
          center: LatLng(51.5, -0.09),
          zoom: 3,
          maxZoom: 5,
          minZoom: 1.5,
          interactiveFlags: InteractiveFlag.drag |
              InteractiveFlag.pinchZoom,
        ),
        layers: [
          TileLayerOptions(
            urlTemplate: "assets/map/{z}/{x}/{y}.png",
            tileProvider: AssetTileProvider(),
          ),
        ],
      ),
    );
  }
```

**Comment by jasonJamEther** [comment]
I have the same issue. Is there are current parameter to zoom from gesture center instead of map center?

**Comment by pawelsa** [comment]
This is still an issue

**Comment by Zzerr0r** [comment]
Still an issue

**Comment by Zzerr0r** [comment]
Hey guys i fixed this and made a pull request for it ( #1081)(i hope this links to the pull request and not an issue, if it doesn't just check the pull requests page) . if you want to, you can fork the repo yourself and integrate the changes i made in the pull request as i don't think this repo is maintained anymore so i dont expect the pull request to be merged into master. 
hope i can help anyone who has this problem as well with this

**Comment by SlowBroshka** [comment]
I have same problem ...
>>i made in the pull request as i don't think this repo is maintained anymore so i dont expect the pull request to be merged into master.
Why it not maintained?

**Comment by Zzerr0r** [comment]
@SlowBroshka I don't know why, it just seems that way because the devs dont respond in any issues or solve any pull requests. but as I've said, you can just copy my fork into your repo
