### ISSUE TITLE
Auto resize of markers and circles not found

### ISSUE THREAD

**Issue by arslankaleem7229** [fleaflet/flutter_map#1013]
I a working with flutter_maps. It worked perfectly but I have not found the way to resize or autosize the markers as it should be like on zoom in marker size increase and non zoom out marker size should decrease. Is these any way to do that or not ?

**Comment by ibrierley** [comment]
Zoom shouldn't change the size of the markers, or am I misunderstanding what you want....?

**Comment by arslankaleem7229** [comment]
Like you can see on Google maps. The circle radius auto increases with zoom in and decreases with zoom out. Also is there any function like Google maps where on a button click user can animateto its current location?

**Comment by JaffaKetchup** [comment]
> Also is there any function like Google maps where on a button click user can animate to its current location?

If you can get the user's location coordinates yourself or through a community-maintained plugin on the README, then you can make a button that, when pressed, moves the map to the user's location.

**Comment by arslankaleem7229** [comment]
Ok. and is there any way to increase or decrease the circle size on zoom in and zoom out

**Comment by JaffaKetchup** [comment]
I'm still not quite sure what you mean, but you can get the current zoom level through the `MapController()`, which would allow you to perform your own sizing maths.

**Comment by ibrierley** [comment]
> Like you can see on Google maps. The circle radius auto increases with zoom in and decreases with zoom out. Also is there any function like Google maps where on a button click user can animateto its current location?

With my google maps, the size stays exactly the same (it has the illusion of getting bigger due to markers possibly getting closer together). But maybe it depends on each app or whatever. Just wondering if we're talking about different things.

**Comment by Swepilot** [comment]
I'm using the mapcontroller.zoom in the marker build method to change the size of the marker. Perhaps not the most efficient way but only way I found. For circles I'm using Circle Marker from the package that enables you to set a radius in meters that will resize the circle as you zoom in/out.
