### ISSUE TITLE
using https://github.com/danwild/leaflet-velocity

### ISSUE THREAD

**Issue by marilantagliari** [fleaflet/flutter_map#1015]
Is it possible to use this lib with flutter_map? suggestions??

**Comment by kengu** [comment]
No, there is currently not a meaningful way to include js-libs for general use other than for web-applications. You could look into [packages:js](https://pub.dev/packages/js) what will allow you to call javascript from dart, but only for dart:js and Flutter:web runtimes. This is not something I think the community will look into. Closing.
