### ISSUE TITLE
calculateEndingGlobalCoordinates

### ISSUE THREAD

**Issue by Zzerr0r** [fleaflet/flutter_map#1016]
Dear flutter_map dev team, i was just wondering where you got the algorithm from for calculating a new latlong point given an old one, bearing and distance. I've been searching all around the internet and tried different formulas but none seemed to be even remotely as accurate as the one youre using. I'm talking about the function used here : https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/scalebar_utils.dart
If you could tell me, where I can find this formula/algorithm I'd be very grateful!

**Comment by Zzerr0r** [comment]
nevermind i found it.
for anyone else searching: https://www.movable-type.co.uk/scripts/latlong-vincenty.html

**Comment by JaffaKetchup** [comment]
I've been using `latlong2`'s `Distance()` object, does the job for me.
