### ISSUE TITLE
Zoom in WEB with MOUSE

### ISSUE THREAD

**Issue by Pizzacorn** [fleaflet/flutter_map#1019]
I'm have been working on these few days but I didn`t find any solution here. I need to Zooming when scrolling in web just like Google Maps and others.

When you move the mouse wheel, the zoom level need o change, are there any solution?

**Comment by JaffaKetchup** [comment]
Please see #914

**Comment by klaasdannen** [comment]
works with the newest commit (tested on Web only, so far)

**Comment by FRANIAZA** [comment]
Please upload this latest version to pub.dev

**Comment by kengu** [comment]
Closing, release of 0.14.0 can be tracked her: #1021
