### ISSUE TITLE
GeoJson with Hole Point polygon color

### ISSUE THREAD

**Issue by hauphidao** [fleaflet/flutter_map#1020]
i have GeoJson with Hole Point https://sharetext.me/rjjdgkx1, i used [http://geojson.io/](url) to parse ok this json
![image](https://user-images.githubusercontent.com/37209567/132608916-a92d3be9-07df-41f9-ab35-a905f9b6cac4.png)
but in my app the Hole Point is black color how to set transparent 
![z2746878073391_90d7bb16d9e479f098b6db87e45b5a89](https://user-images.githubusercontent.com/37209567/132609187-55408381-edd0-4551-a21f-948346c9d707.jpg)

here my code 
```dart
        final poly = Polygon(
          points: _geoPolygon.toLatLng(ignoreErrors: true),
          color: Proj4Convert.instance.fromHex(_feature.properties!['color']),
          borderColor: Colors.grey,
          borderStrokeWidth: 3,
          holePointsList: _lstPoints.isNotEmpty ? _lstPoints : null,
        );
```

**Comment by adnanefouam** [comment]
i have the same issue for some polygones
