### ISSUE TITLE
How to dynamic update marker ?

### ISSUE THREAD

**Issue by zozeei** [fleaflet/flutter_map#1023]

**Comment by tinvujasinovic** [comment]
If you are talking about changing marker color or something similar, you are going to need to use StatefulMarkers. (https://pub.dev/documentation/map_controller/latest/map_controller/StatefulMarker-class.html)

 You should be creating markers with some kind of _state_ like this:
![image](https://user-images.githubusercontent.com/37039349/133383993-88f42dc3-ad9c-41ab-b08c-e9330a4414c2.png)

and finally you can change their _state_ using a StatefulMapController like this:
![image](https://user-images.githubusercontent.com/37039349/133384150-0e145bad-cac3-463c-9d52-b1d9e4c6d781.png)

Hope this helps :)

**Comment by ibrierley** [comment]
Or you can simply call setState on the widget flutter_map is in, it will update the marker. Depends if it's an issue to refresh the whole map (which typically isn't an issue), rather than an individual marker.

**Comment by darkwolf66** [comment]
> If you are talking about changing marker color or something similar, you are going to need to use StatefulMarkers. (https://pub.dev/documentation/map_controller/latest/map_controller/StatefulMarker-class.html)
> 
> You should be creating markers with some kind of _state_ like this: ![image](https://user-images.githubusercontent.com/37039349/133383993-88f42dc3-ad9c-41ab-b08c-e9330a4414c2.png) _Hint_: were using marker hash code to be able to identify markers to mutate
> 
> and finally you can change their _state_ using a StatefulMapController like this: ![image](https://user-images.githubusercontent.com/37039349/133384150-0e145bad-cac3-463c-9d52-b1d9e4c6d781.png)
> 
> Hope this helps :)

This solution is outdated and does not work with version 0.14.0 only 0.11.0
