### ISSUE TITLE
Crash app when panning

### ISSUE THREAD

**Issue by caocuongajax** [fleaflet/flutter_map#1026]
Hello everyone,
I have a problem with panning map. Could you help me, please?
My layers load wmts service from my server, but when I pan map, it is slow so much and my app is crashed.
This is my code:
```
FlutterMap(
...
layers:[
TileLayerOptions(
  urlTemplate: <OSM_service_url>,
  tileProvider: const CacheNetworkImage()
),
TileLayerOptions(
  urlTrmplate: <my_wmts_server_url_with_xyz>,
  tileProvider: const CacheNetworkImage()
)
]
...
)
```
Thank you!

P/S: in debug mode, I saw "Flutter Performance" dialog which show red bar all time. 6 or 12 frame/sec

**Comment by JaffaKetchup** [comment]
Can you show what's inside `CacheNetworkImage()`?

**Comment by caocuongajax** [comment]
CacheNetworkImage(), I followed READ ME of flutter_map plugin.

**Comment by caocuongajax** [comment]
import 'package:cached_network_image/cached_network_image.dart';
class CachedTileProvider extends TileProvider {
  const CachedTileProvider();
  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return CachedNetworkImageProvider(
      getTileUrl(coords, options),
      //Now you can set options that determine how the image gets cached via whichever plugin you use.
    );
  }
}

**Comment by JaffaKetchup** [comment]
Can you post a video or a log? What device are you on?

You may want to try my plugin: https://pub.dev/packages/flutter_map_tile_caching and see if it matches your needs without performance impact. If you try it, use the latest prerelease so you don't have to migrate to the new release soon.

**Comment by caocuongajax** [comment]
Hi @JaffaKetchup 
This is my screen recording: https://drive.google.com/file/d/1PUsNYxgMOqvm8IvGgxAJ9hNZ0QjZA-6P/view?usp=sharing
And this is my app in Android https://drive.google.com/file/d/1MSk0LLShdzRI-xNbSxNivq76OGMl1JIR/view?usp=sharing
In Android app, you zoom in 2-3 times and pan map a lot, it will crash.
Could you help me, please?
Thank you.

**Comment by Swepilot** [comment]
I see you are using opacity. I had the same issue and it stopped happening when I removed opacity. Can you see if that helps?

**Comment by JaffaKetchup** [comment]
If @Swepilot 's suggestion doesn't work, the only other thing I can think of it the caching blocking the thread. If this is the case, use my plugin as I mentioned above (use prereleases).

**Comment by caocuongajax** [comment]
Thanks for your help.
