### ISSUE TITLE
LateInitializationError with polygonCulling in PolygonLayerOptions - with example

### ISSUE THREAD

**Issue by spatialbits** [fleaflet/flutter_map#1037]
Same as #974 and #931 but opening as a new issue since those were closed. 

Upgrading FlutterMap from very old version I am encountering  `LateInitializationError: Field 'boundingBox' has already been initialized` when `polygonCulling=true`.

The problem crops up when I hold reference to `polygonOpts` in a stateful widget. This seems reasonable to me as rebuilding polygonOpts would be unnecessary.

##### Example

```
import 'package:flutter/material.dart';
import 'package:flutter_map/plugin_api.dart';
import 'package:latlong2/latlong.dart' hide Path; // conflict with Path from UI

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MapPage(),
    );
  }
}

class MapPage extends StatefulWidget {
  const MapPage({Key? key}) : super(key: key);

  @override
  State<MapPage> createState() => _MapPageState();
}

class _MapPageState extends State<MapPage> {
  final MapController _mapController = MapController();

  final poly = Polygon(
    points: [
      LatLng(50, -120),
      LatLng(50, -119),
      LatLng(49, -119),
      LatLng(49, -120),
    ],
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FlutterMap(
        options: MapOptions(
          center: LatLng(49.4, -119.5),
          zoom: 8,
          onTap: (_, __) => setState(() {}),
          controller: _mapController,
        ),
        nonRotatedChildren: [
          TileLayerWidget(
            options: TileLayerOptions(
                minZoom: 2,
                maxZoom: 19,
                urlTemplate:
                    "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                subdomains: ['a', 'b', 'c']),
          ),
          PolygonLayerWidget(
            options: PolygonLayerOptions(
              polygonCulling: true,
              polygons: [poly],
              // polygons: [
              //   Polygon(
              //     points: [
              //       LatLng(50, -120),
              //       LatLng(50, -119),
              //       LatLng(49, -119),
              //       LatLng(49, -120),
              //     ],
              //   )
              // ],
            ),
          )
        ],
      ),
    );
  }
}
```

- Tap in the map to trigger setState and exception will be thrown.
- Swap `polygons: [poly],` for the inline Polygon instance and exceptions won't be thrown.

**Comment by moovida** [comment]
Same issue here. 

```
class PolylineLayerOptions extends LayerOptions {
[...]
    if (polylineCulling) {
      for (var polyline in polylines) {
        polyline.boundingBox = LatLngBounds.fromPoints(polyline.points);
[...]
```

Can't it be assumed that if the bbox is already calculated, it probably didn't change?

**Comment by ibrierley** [comment]
Any difference if poly or polylines isn't final ?

**Comment by moovida** [comment]
Not sure I understand your comment. 
Since the bbox is final:
```
late final LatLngBounds boundingBox;
```
There is no way to reset it.

**Comment by moovida** [comment]
The interesting thing is that there isn't even a way to check if it is initialized or not? Can that be?
If I try to check:
```
if (polyLine.boundingBox != null) {
```
It throws me an exception: LateInitializationError: Field 'boundingBox' has not been initialized.

**Comment by spatialbits** [comment]
> Any difference if poly or polylines isn't final ?

Yeah it does make a difference.

This is my fix: 
https://github.com/Kwusen/flutter_map/commit/f07fd48a4e1d107cd7814d5ed0c460d89f5b11e2

Also, since my bboxes are calculated elsewhere I parameterized it to avoid the extra overhead.

**Comment by mohammedX6** [comment]
This is working for me without using late 
try to set boundingBox to this in the Polygon Class
LatLngBounds boundingBox = LatLngBounds();

**Comment by Vafin84** [comment]
I want to inform you that the problem is still relevant with polylines

**Comment by jithware** [comment]
Here's an example that reproduces the error and a proposed fix: https://github.com/jithware/flutter_map/commit/dd418f89b88903faa8b92e945cb8cf15bba08408

**Comment by beeekey** [comment]
This Bug still exists?

**Comment by ibrierley** [comment]
What exact error and what exact version of flutter_map are you using ?
