### ISSUE TITLE
Can you have tileBuilder without urlTemplate?

### ISSUE THREAD

**Issue by benboughton1** [fleaflet/flutter_map#1038]
I want to have a fully custom TileLayer built from widget in tileBuilder - no external source.

In TileLayerOptions Can you have tileBuilder without urlTemplate?

If I leave out urlTemplate I get a null error:
The following TypeErrorImpl was thrown building RawGestureDetector(state: RawGestureDetectorState#9e289(gestures: [scale, vertical drag, horizontal drag])):
Unexpected null value.

The relevant error-causing widget was: 
  RawGestureDetector RawGestureDetector:file:///C:/Work/flutter/flutter_windows_2.2.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.14.0/lib/src/map/flutter_map_state.dart:88:11
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/flutter_map/src/layer/tile_provider/tile_provider.dart 35:48                                                          getTileUrl
packages/flutter_map/src/layer/tile_provider/tile_provider.dart 72:25                                                          getImage
packages/flutter_map/src/layer/tile_layer.dart 1068:32                                                                         [_addTile]
....
....

If I set to empty string tileBuilder works but I get error:
ImageCodecException: Failed to decode image data.

Thanks

**Comment by ibrierley** [comment]
It's not very clear what you are trying to do....

**Comment by benboughton1** [comment]
Sorry, maybe this is more clear: Can you take the tile_builder_example.dart example from this repo and remove OSM map and have the built tile remain showing the zoom and coordinates? 

If that still does not make sense ill copy paste the tilebuilder example in with showing the lines that I took out.

**Comment by benboughton1** [comment]
It's OK - I will extend the TileProvider class to make custom tile instead.

**Comment by pedromolesp** [comment]
Now you have the option of leave '' as empty string the urlTemplate
