### ISSUE TITLE
Attribution is affected by map rotation

### ISSUE THREAD

**Issue by Robbendebiene** [fleaflet/flutter_map#1040]
The attribution widget introduced by @ondbyte (https://github.com/fleaflet/flutter_map/pull/1012) gets rotated whenever the map is rotated.
Maybe `attributionBuilder` is supposed to be used in the `nonRotatedLayers` layer, but this means that the tiles of the `TileLayerOptions` won't be rotated as well.

I feel like the `attributionBuilder` in the `TileLayerOptions` is obsolete, since one can add any number of widgets over the map using `children` and `nonRotatedChildren` which is way more powerful.

**Comment by JaffaKetchup** [comment]
I was a little confused looking at the implementation of the `attributionBuilder`, but I haven't used it yet so I can't say much about it.

**Comment by JaffaKetchup** [comment]
Can confirm this is an issue! @Robbendebiene Would be great if you could re-open it?

**Comment by Robbendebiene** [comment]
@JaffaKetchup I don't think that I can reopen it since the bot closed the issue. At least I don't see any button.

**Comment by Robbendebiene** [comment]
I would recommend removing this option, since this can easily be achieved with an Align widget inside the `nonRotatedChildren`, which is much more flexible.

**Comment by JaffaKetchup** [comment]
Not sure what's the best option here.
Most mapping packages have a built-in 'attributor', to make it less easy for the developer to forget to credit and therefore as a courtesy to map servers.
You could also just use a `Stack` for a homemade solution.
@ibrierley Any opinions?

**Comment by melis-m** [comment]
You could deprecate `attributionBuilder`, with a message explaining just that, if you don't want to get rid of it yet

**Comment by ibrierley** [comment]
I have no problem with it getting deprecated (I think), but I also think there should be something in place first to replace it. I suspect this will have to be a separate layer as suggested, as whole layers get rotated, and there's no real easy way for a tile layer to do this itself. It's a shame as it is intuitive to have the option as part of the tiles.

**Comment by JaffaKetchup** [comment]
Yeah I agree. I don't want to deprecate this without a replacement as it's quite a useful feature.

**Comment by ibrierley** [comment]
Theoretically in flutter_map_state.dart we could have a method..
```dart
List<Widget> getAttributionLayers() {

    final List<Widget> attributionLayers = [];
    final layers = [...widget.layers, ...widget.children];
    for (final object in layers) {

      TileLayerOptions? tileOption;
      if (object is TileLayerOptions) {
        tileOption = object;
      } else if (object is TileLayerWidget) {
        tileOption = object.options;
      }

      if (tileOption != null && tileOption.attributionBuilder != null) {
        attributionLayers.add(
            Align(
                alignment: tileOption.attributionAlignment,
                child: tileOption.attributionBuilder!.call(context)
            )
        );
      }
    }
    return attributionLayers;
  }
```
then in _buildmap
```dart
final List<Widget> attributionLayers = getAttributionLayers();
```
and in the nonRotatedChildren area have..
```dart
if(attributionLayers.isNotEmpty)
                ...attributionLayers,
```
Remove the bit of code from TileLayer.

I think this would work...
pros: It fixes the original problem and doesn't break or deprecate anything.
cons: it feels a bit clunky and is probably cluttering the map_state code, and not sure it's the most intuitive location.

**Comment by ibrierley** [comment]
I don't think there's any nice way to do it without introducing a separate normal Widget layer. Another alternative then....

attribution_layer.dart
```dart
import 'package:flutter/widgets.dart';

class AttributionWidget extends StatelessWidget {
  final WidgetBuilder attributionBuilder;
  final Alignment alignment;

  const AttributionWidget({Key? key, required this.attributionBuilder, this.alignment =  Alignment.bottomRight})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Align(
        alignment: alignment,
        child: attributionBuilder.call(context)
    );
  }
}
```
flutter_map.dart
```dart
export 'package:flutter_map/src/layer/attribution_layer.dart';
```

Where you end up including flutter_map

```dart
nonRotatedChildren: [
                  AttributionWidget(
                    attributionBuilder: (_) {
                      return Text("© OpenStreetMap2 contributors");
                    }
                )],
```

Leave the original in and mark to be removed in future.

**Comment by ibrierley** [comment]
I'm out now until tomorrow, so feel free.
