### ISSUE TITLE
Bounds not changed when rotating

### ISSUE THREAD

**Issue by ankiimation** [fleaflet/flutter_map#1041]
map's bounds seem not be changed when I rotate the map. Any suggestion?

**Comment by Zverik** [comment]
Came here to add this issue. When specifying both `bounds` and `rotation` options for a map, bounds are calculated for a zero rotation, and then the map is rotated. This almost never looks right.

A solution would be to improve `LatLngBounds.fromPath` constructor to get a parameter for rotation.

**Comment by b-cancel** [comment]
any solution to this @ankiimation or @Zverik?
