### ISSUE TITLE
Address Xennis' flutter_map_location in plugin list

### ISSUE THREAD

**Issue by geisterfurz007** [fleaflet/flutter_map#1045]
`flutter_map_location` has been [discontinued](https://github.com/Xennis/flutter_map_location/commit/367d33ac22adc40d4f89fd6ce1c80cf09fe7dc96) a few weeks ago. This should be addressed in the [list of plugins](https://flutter-map.vercel.app/plugins/list) by either marking it as such or removing it from the list entirely.

![grafik](https://user-images.githubusercontent.com/26303198/135458422-93657331-f664-4c4e-8485-5a0d1c2c721f.png)

*I am aware that page is still WIP but wanted to note this since Xennis refers to that list in his discontinuation notice.*

**Comment by JaffaKetchup** [comment]
As an author of this new docs, I will remove the link (unless @Xennis contacts me (or other maintainers) prior).

Out of interest, how did you come across the link to these docs? I'm assuming you just found it in a comment of mine or on the New Docs thread. Thanks.
