### ISSUE TITLE
Offline Maps, {y} part of path not matching my tilemill png files

### ISSUE THREAD

**Issue by Alextbush-gg** [fleaflet/flutter_map#1050]
I have hundreds of a pre-build tiles used in an old cordova based application that used leaflet js to load in offline tiles.

I am attempting to use this project to create a new flutter version however when loading the offline tiles in, the {y} part of the path seems to be completed different. The x and z directories seem fine based on the console logs.

Is there an option I am missing to correct this? The coordinates I am using are correct, and work fine with online providers.

**Comment by ibrierley** [comment]
Hmm neither seem to match for me, which online providers are you checking against ?
