### ISSUE TITLE
calculate the center of points

### ISSUE THREAD

**Issue by resfandiari** [fleaflet/flutter_map#1052]
Hi,
Thanks for the great package.
Could you please explain how to determine the center of points?

**Comment by JaffaKetchup** [comment]
Hi there,
If you have a `LatLngBounds` object, you should be able to use `.center` on it.
Hope that helps!

**Comment by resfandiari** [comment]
> Hi there, If you have a `LatLngBounds` object, you should be able to use `.center` on it. Hope that helps!

I really appreciate it, you saved me a lot of time.
