### ISSUE TITLE
arcgis tile layer is not in place

### ISSUE THREAD

**Issue by seiif1** [fleaflet/flutter_map#1053]
I am trying to put an arcgis WMTS tile layer on top of openstreetmaps WMTS layer in flutter using the flutter_map plugin. Here is my code :

  ```
Widget build(BuildContext context) {
return MaterialApp(
  home: FlutterMap(
    options: new MapOptions(
      center: LatLng(33.8, 9.5),
      zoom: 6.0,
      pinchZoomWinGestures: MultiFingerGesture.pinchZoom,
    ),
    layers: [
      //layer 1 - leaflet tiles
      TileLayerOptions(
        urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        subdomains: ['a', 'b', 'c'],
        tileProvider: NonCachingNetworkTileProvider(),
        backgroundColor: Colors.black,
      ),

      //Layer 2 - leaflet tiles
      TileLayerOptions(
        urlTemplate:
            "https://tiles.arcgis.com/tiles/C8EMgrsFcRFL6LrL/arcgis/rest/services/GEBCO_contours/MapServer/tile/{z}/{x}/{y}",
        subdomains: ['a', 'b', 'c'],
        tileProvider: NonCachingNetworkTileProvider(),
        backgroundColor: Colors.transparent,
      ),
    ],
  ),
);
```
but the ArcGIS map does not align correctly with the OpenStreetMap.

https://i.stack.imgur.com/4rDOo.jpg

I hope you can help me rectify my code and have a great day

**Comment by seiif1** [comment]
i am sorry for my simple question but how can I know the CRS of this tile ??

**Comment by ibrierley** [comment]
Hmm actually it seems like they may both be EPSG:4326 (WGS84) (I think you
can request the crs to use in arcgis, but I may be wrong). So I may be
talking rubbish, however I don't know much about the different CRSs so
maybe someone else has some ideas. Just trying to help lead in the
direction of things I would try and dig into, as some of that stuff isn't
clear in the respective docs.
