### ISSUE TITLE
Zoom to a specific bounds of a screen

### ISSUE THREAD

**Issue by X-SLAYER** [fleaflet/flutter_map#1054]
is there a way to zoom on the map marker to a specific place on the screen
like I want whenever I click on the marker it will be zoomed in to one-third of the screen height something like in the picture

<img src="https://user-images.githubusercontent.com/22800380/136676641-a333950b-b573-45ed-ab18-c62ea7505825.png" width=250>

**Comment by tprebs** [comment]
Something like the below method will allow you to zoom to a point where that point becomes the center. If you need to zoom to a point which is not the center of the map you will have to calculate the offset centre point yourself. You can do this using the latlng2 library by calculating the distance between min and max latitude (available from the mapcontroller) and calculating the required offset to move the center point to 2/3rds height

```dart
 /// Animates the movement between the previous point and new point/zoom level
  _animatedMapMove(LatLng destination, double zoom) {
    final _latTween = Tween<double>(
        begin: _mapController.center.latitude, end: destination.latitude);
    final _longTween = Tween<double>(
        begin: _mapController.center.longitude, end: destination.longitude);
    final _zoomTween = Tween<double>(begin: _mapController.zoom, end: zoom);

    var animationController =
        AnimationController(duration: Duration(milliseconds: 500), vsync: this);

    Animation<double> animation = CurvedAnimation(
        parent: animationController, curve: Curves.fastOutSlowIn);

    animationController.addListener(() {
      _mapController.move(
          LatLng(_latTween.evaluate(animation), _longTween.evaluate(animation)),
          _zoomTween.evaluate(animation));
    });

    animationController.addStatusListener((status) {
      if (status == AnimationStatus.completed ||
          status == AnimationStatus.dismissed) {
        animationController.dispose();
      }
    });

    animationController.forward();
  }
```
