### ISSUE TITLE
"Unable to load asset" when using offLine map with TileMill

### ISSUE THREAD

**Issue by nalnir** [fleaflet/flutter_map#1056]
I don't know where I'm making the mistake. In my `pubspec.yaml` I tried this:
```
assets:
    - assets/offlineIceland/map/
```
and also this
```
assets:
    - assets/offlineIceland/map/{z}/{x}/{y}.png
```

The first one results with `Unable to load asset`
The second results with: `No file or variants found for asset: assets/offlineIceland/map/%7Bz%7D/%7Bx%7D/%7By%7D.png.`
and also the comment in pubspec.yaml assets: `The asset file 'assets/offlineIceland/map/{z}/{x}/{y}.png' doesn't exist.
Try creating the file or fixing the path to the file.`

My TileLayerOption in `main.dart` looks like this:
```
TileLayerOptions(
            tms: true,
            tileProvider: const AssetTileProvider(),
            urlTemplate: "assets/offlineIceland/map/{z}/{x}/{y}.png",
)
```

I tried without tms but doesn't work. I saw similar 2 issues here but none of them were answered.

**Comment by ibrierley** [comment]
Maybe screenshot your android studio (or whatever) file structure (including the outer folders) could be useful to someone to spot something ?

**Comment by ibrierley** [comment]
It also looks like your indentation is too far over for your - assets/offlineIceland/map/ but that may just be the git paste.

**Comment by nalnir** [comment]
Yeah indentation is alright. I tried random images and I had to explicitly import it like this:
```
assets:
    - assets/images/download.png
```
It will work. If I would import like this:
```
assets:
    - assets/images/
```
Then the same error is going happen. I think I have to import every single .png image separately otherwise it won't load at all. Unless there is a way to import it with entire folders.

**Comment by ibrierley** [comment]
Only other thing I can do is show a screeny with one of the png files expanded to highlight its there and the png filename is correct that you are trying to reference eg can you expand  6/30/ so it shows 20.png

**Comment by nalnir** [comment]
Alright I think I figured it out. There are plenty of .png images missing. I imported some .png files manually and when I checked the error point at specific image that image didn't exist at all.
