### ISSUE TITLE
Can Google Maps be used as a map/tile provider?

### ISSUE THREAD

**Issue by aytunch** [fleaflet/flutter_map#1058]
I haven't seen Google maps example as a provider in the documentation. Has anyone tried using flutter_map with google maps?

**Comment by JaffaKetchup** [comment]
Ok, so here is the base URL:
`https://mt0.google.com/vt/lyrs=m@221097413,traffic,transit,bike&x={x}&y={y}&z={z}`

To change overlays, remove 'traffic', 'transit' or 'bike'.

To change style, replace 'm' with any of the following:
- h: Roads only
- m: Standard roadmap
- p: Terrain
- r: Different roadmap
- s: Satellite only
- t: Terrain only
- y: Hybrid

It may be possible to mix and match these but I'm not 100% sure. You may also be interested in groups.google.com/forum/#!topic/google-maps-api/3RvxRebArfg for language variations.

**Comment by mohamadkenway** [comment]
> Ok, so here is the base URL: `https://mt0.google.com/vt/lyrs=m@221097413,traffic,transit,bike&x={x}&y={y}&z={z}`
> 
> To change overlays, remove 'traffic', 'transit' or 'bike'.
> 
> To change style, replace 'm' with any of the following:
> 
> * h: Roads only
> * m: Standard roadmap
> * p: Terrain
> * r: Different roadmap
> * s: Satellite only
> * t: Terrain only
> * y: Hybrid
> 
> It may be possible to mix and match these but I'm not 100% sure.
> 
> Use at your own risk and responsibility.

Hi
this url doesn't need Google API Key ?

**Comment by JaffaKetchup** [comment]
Hi,
This URL doesn't need an API key. I'm not sure if it's breaking their terms of service, however, so use at your own risk.

**Comment by mohamadkenway** [comment]
> Hi, This URL doesn't need an API key. I'm not sure if it's breaking their terms of service, however, so use at your own risk.

Hi again
no i have api key but i don't want use Google map package in flutter , i want have a base url that i pass it my API Key in flutter map package

**Comment by JaffaKetchup** [comment]
Oh sorry, I didn't quite understand.
Unfortunately I can't help much with that as I haven't used Google Maps like that before. The best suggestion I can give is find a Raster URL from their docs and remove the 'apiKey' (or similar) from the URL query and pass it through the additional options map in `FlutterMap()`.

**Comment by mohamadkenway** [comment]
> 

Hello
i could not find Raster URL like you said
do u can help me more ?

**Comment by mohamadkenway** [comment]
> Oh sorry, I didn't quite understand. Unfortunately I can't help much with that as I haven't used Google Maps like that before. The best suggestion I can give is find a Raster URL from their docs and remove the 'apiKey' (or similar) from the URL query and pass it through the additional options map in `FlutterMap()`.

Hello
i could not find Raster URL like you said
do u can help me more ?

**Comment by JaffaKetchup** [comment]
Did you find any URL? It may not be specially Raster.

**Comment by mohamadkenway** [comment]
> Did you find any URL? It may not be specially Raster.

No i couldn't

**Comment by mohamadkenway** [comment]
> https://mt0.google.com/vt/lyrs=m@221097413,traffic,transit,bike&x={x}&y={y}&z

this url can set language (Not English)?

**Comment by JaffaKetchup** [comment]
So after doing research, Google Maps doesn't provide static tiles. Therefore you won't be able to use Google Maps officially with flutter_map.

Don't know how to change the language of the URL. It may not be possible. The URL I provided was a trial and error based on multiple sources online.

**Comment by naiiu** [comment]
> Ok, so here is the base URL: `https://mt0.google.com/vt/lyrs=m@221097413,traffic,transit,bike&x={x}&y={y}&z={z}`
> 
> To change overlays, remove 'traffic', 'transit' or 'bike'.
> 
> To change style, replace 'm' with any of the following:
> 
> * h: Roads only
> * m: Standard roadmap
> * p: Terrain
> * r: Different roadmap
> * s: Satellite only
> * t: Terrain only
> * y: Hybrid
> 
> It may be possible to mix and match these but I'm not 100% sure.
> 
> Use at your own risk and responsibility.

Is it possible to access the typical traffic layer (and specify the weekday and hours) in Google Maps?

**Comment by JaffaKetchup** [comment]
Hi there.
I'm not quite sure what you mean, sorry. Please explain more?

**Comment by naiiu** [comment]
![image](https://user-images.githubusercontent.com/24749905/162748072-02a98b82-c405-4868-b8a6-b87080512e67.png)
For example, I would like to get traffic information for Monday morning at 9 am.
Is that possible

**Comment by JaffaKetchup** [comment]
Unfortunately I have no idea. I am not the original source of the URL, I just did trial and error to find some remaining properties. I wouldn't even know where to start.

**Comment by ibrierley** [comment]
That URL just gives a 400 error for me, not sure if I'm missing something ?

Typically it's not possible without paying Google or Mapbox or whoever. If you can get past that stage and what you want to do is within their t&C, it's likely possible, but then a case of how much work you want to put in.

Normally those are the stumbling blocks, so people will just use the native google or mapbox plugins etc.

**Comment by JaffaKetchup** [comment]
@ibrierley That URL still seems to work for me: https://mt0.google.com/vt/lyrs=m@221097413,traffic,transit,bike&x=1&y=1&z=1

It's an undocumented endpoint in Google, and I couldn't find any specific clauses about it in their TOS. However, it's probably against their rules (in some catch-all clause) so use at your own risk.

Native Google Maps plugin would be a better option wherever possible, but this is free and if you need 'flutter_map', it'll work.

**Comment by ibrierley** [comment]
Ah thanks. Sorry, I was thinking it was the data was being sought, rather than the raster tiles iyswim. I'm not sure that would provide the typical traffic usage though, but it looks very useful for some who just want live display.

**Comment by hamsaco** [comment]
> Ok, so here is the base URL: `https://mt0.google.com/vt/lyrs=m@221097413,traffic,transit,bike&x={x}&y={y}&z={z}`
> 
> To change overlays, remove 'traffic', 'transit' or 'bike'.
> 
> To change style, replace 'm' with any of the following:
> 
> * h: Roads only
> * m: Standard roadmap
> * p: Terrain
> * r: Different roadmap
> * s: Satellite only
> * t: Terrain only
> * y: Hybrid
> 
> It may be possible to mix and match these but I'm not 100% sure.
> 
> Use at your own risk and responsibility.

Hey. Is there any other link for a dark map? (google map)

**Comment by JaffaKetchup** [comment]
Sorry @hamsaco, I don't know. I found some properties from a mixture of digging online and trial and error, but I wouldn't even know where to start to find that sort of thing.
