### ISSUE TITLE
Irritating scrolling

### ISSUE THREAD

**Issue by arslankaleem7229** [fleaflet/flutter_map#1059]
I am working with flutter maps in which I am using mapbox as `TileLayerOption` but it is very irritating when swiping to some other location. Sometimes it became inverted like behaving in opposite direction i.e when I swap left map moves towards right. Also it is not fixed with the size of screen if I continue to zoom it it will zoom out and add grey portion where there is no map There are so many problems I am facing with this map. Here are the previews of that problems
![original](https://user-images.githubusercontent.com/49631685/137464256-33bcde87-936d-42e7-8cf2-734732db6b08.jpg)

https://user-images.githubusercontent.com/49631685/137464871-9b7accce-bf09-4c46-840a-e3ba579550e1.mp4

**Comment by B4eva** [comment]
Ohh i also experience these issues. I am using  flutter maps in which I am using Mapbox as TileLayerOption

**Comment by Swepilot** [comment]
The irritating scrolling is due to the fact that you have a nonRotatingLayer or nonRotatingChildren but the gesture detection has rotated. Change the layers/children to rotating ones and you will see what mean.

You can disable this behaviour with some of the option parameters, but not at my computer at the moment and don't remember exactly what I did...

**Comment by B4eva** [comment]
Ohh cool but  I may be misunderstanding something basic in the rotation because i can't still figure out the options parameter to fix this.

**Comment by arslankaleem7229** [comment]
> The irritating scrolling is due to the fact that you have a nonRotatingLayer or nonRotatingChildren but the gesture detection has rotated. Change the layers/children to rotating ones and you will see what mean.
> 
> You can disable this behaviour with some of the option parameters, but not at my computer at the moment and don't remember exactly what I did...

but what if i want to make layers non rotateable ??? then you are saying I have to bear this irritating scroll ???

**Comment by Swepilot** [comment]
> > The irritating scrolling is due to the fact that you have a nonRotatingLayer or nonRotatingChildren but the gesture detection has rotated. Change the layers/children to rotating ones and you will see what mean.
> > You can disable this behaviour with some of the option parameters, but not at my computer at the moment and don't remember exactly what I did...
> 
> but what if i want to make layers non rotateable ??? then you are saying I have to bear this irritating scroll ???

I have perfectly behaving non rotating layers. I will provide my solution a bit later today, don't worry 😊

**Comment by arslankaleem7229** [comment]
> > > The irritating scrolling is due to the fact that you have a nonRotatingLayer or nonRotatingChildren but the gesture detection has rotated. Change the layers/children to rotating ones and you will see what mean.
> > > You can disable this behaviour with some of the option parameters, but not at my computer at the moment and don't remember exactly what I did...
> > 
> > 
> > but what if i want to make layers non rotateable ??? then you are saying I have to bear this irritating scroll ???
> 
> I have perfectly behaving non rotating layers. I will provide my solution a bit later today, don't worry 😊

Oh ... OK that would be great. Thank you soo much

**Comment by Swepilot** [comment]
So, this is what I have added as one parameter in mapOptions: 
`interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate`

As I recall it, this was what fixed the issue

**Comment by B4eva** [comment]
This works. Thanks a lot for this ..

**Comment by arslankaleem7229** [comment]
> So, this is what I have added as one parameter in mapOptions: `interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate`
> 
> As I recall it, this was what fixed the issue


No it didn't helped me as you can see the swipe direction and direction of map

https://user-images.githubusercontent.com/49631685/142905048-a2a87c40-7926-4b74-a603-8e0631f026d9.mp4

**Comment by Hellomik2002** [comment]
The Issue still exist

**Comment by JaffaKetchup** [comment]
@Hellomik2002 Please open a new issue with a new minimal reproducible example.
