### ISSUE TITLE
I Am trying to make an onTap on a marker and its not registering any tap actions 

### ISSUE THREAD

**Issue by liamsammut97** [fleaflet/flutter_map#1061]
`class _Map extends StatelessWidget {
  final RouteController routeController;
  final CaminoController caminoController;

  _Map({
    required this.routeController,
    required this.caminoController,
  });

  @override
  Widget build(BuildContext context) {
    var trailPoints = routeController.currentRouteData().trailPoints ?? [];
    trailPoints.sort(
      (a, b) => a.orderNumber.compareTo(b.orderNumber),
    );
    final points = [
      for (var trail in trailPoints) LatLng(trail.latitude, trail.longitude)
    ];

    return Obx(
      () => FlutterMap(
        options: MapOptions(
          center: LatLng(35.9375, 14.3754),
          zoom: 11.0,
        ),
        layers: [
          TileLayerOptions(
              urlTemplate:
                  'https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png',
              subdomains: ['a', 'b', 'c'],
              tileProvider: const CachedTileProvider()),
          MarkerLayerOptions(
            markers: [
              for (var poi in routeController
                  .currentRouteData()
                  .poi
                  .where((poi) => poi.type?.id != 5))
                Marker(
                  point: LatLng(poi.latitude, poi.longitude),
                  builder: (context) => InkWell(
                    onTap: () {
                      print("Tap");
                    },
                    child: Icon(
                      Icons.location_on,
                      size: 35,
                      color: Colors.red,
                    ),
                  ),
                ),
            ],
          ),
          PolylineLayerOptions(
            polylines: [
              Polyline(points: points, strokeWidth: 4, color: Colors.red),
            ],
          ),
        ],
      ),
    );
  }
}`

**Comment by TrungJamin** [comment]
![image](https://user-images.githubusercontent.com/68997072/137622047-1f58b1bc-1a83-4d64-8127-0564fa723636.png)

Hey bro, I fixed the problem, you can check at issue #324

**Comment by liamsammut97** [comment]
You are a true life saver ! Thanks for the fix ❤️
