### ISSUE TITLE
how to add zoom control position to map option

### ISSUE THREAD

**Issue by majidpourdavood** [fleaflet/flutter_map#1069]
how to add zoom control position to map option?

**Comment by fvisticot** [comment]
Did you mean to add a control/widget to allow zooming/unzooming with + - buttons ?

**Comment by majidpourdavood** [comment]
> Did you mean to add a control/widget to allow zooming/unzooming with + - buttons ?

yes

**Comment by CarSanoja** [comment]
any news about this?

**Comment by ibrierley** [comment]
There's a zoomplugin widget in the test directory, does that not do what you are after ?
