### ISSUE TITLE
Marker position shifts while zooming

### ISSUE THREAD

**Issue by manoj036** [fleaflet/flutter_map#1070]
On zooming in or out, the marker position seems to shift by a lot.
I checked the points mentioned in #88. But they don't seem to fix my problem.

![ezgif-6-ac6f48c5c2ae](https://user-images.githubusercontent.com/9340848/139424478-31b65fa2-e3fb-400b-8042-1a19d0695719.gif)

This is the code I was using.
```
AspectRatio(
      aspectRatio: 1,
      child: FlutterMap(
        options: MapOptions(
          center: LatLng(location.latitude, location.longitude),
          zoom: 15.0,
        ),
        layers: [
          TileLayerOptions(
            urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            subdomains: ['a', 'b', 'c'],
            attributionBuilder: (_) {
              return const Text("© OpenStreetMap contributors");
            },
          ),
          MarkerLayerOptions(
            markers: [
              Marker(
                width: 80.0,
                height: 80.0,
                point: LatLng(location.latitude, location.longitude),
                anchorPos: AnchorPos.align(AnchorAlign.bottom),
                builder: (ctx) => const DSIconButton(
                      type: IconType.pin,
                      color: TextColorType.primary,
                    ),
                rotate: true,
              ),
            ],
          ),
        ],
      ),
    )
```
Can you please let me know if I am doing something wrong?

**Comment by WieFel** [comment]
> > What happens if you just have a normal Marker added in there as well, which is just a Icons.circle in the builder and no anchorPos etc.
> 
> With a simple circle icon, the position seems to be fixed in place and everything works correctly. I tried Icons.pin_drop as well. It seems to work correctly with `AnchorPos.align(AnchorAlign.center)` with icon center as the point center. But once I change anchorPos to `AnchorPos.align(AnchorAlign.bottom)`, the issue seems to happen.

@manoj036 have you tried with `AnchorPos.align(AnchorAlign.top)`? That solved it for me, together with setting the rotate origin to the bottom center. For me this was `rotateOrigin: const Offset(16, 32),`, as I use a marker icon of size 32...

**Comment by manoj036** [comment]
> @manoj036 have you tried with `AnchorPos.align(AnchorAlign.top)`? That solved it for me, together with setting the rotate origin to the bottom center. For me this was `rotateOrigin: const Offset(16, 32),`, as I use a marker icon of size 32...

@WieFel, thanks.
I will try it when I get time later. 
I decided to use circular icons for my project because of this issue. 😂

But I remember that placing the `IconButton` in a `Center` widget seems to have fixed this problem for me at one point of time. Can you try doing it if you have a chance?
