### ISSUE TITLE
Support for Arcgis basemap tile url

### ISSUE THREAD

**Issue by elobeparfait** [fleaflet/flutter_map#1071]
Please is like fluttermap does not support .pbf files and throws error of invalide image data.
baseUrl looks like : "https://basemaps-api.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer/tile/{z}/{y}/{x}.pbf"

**Comment by JaffaKetchup** [comment]
This looks like a vector tile source.
Unfortunately, flutter_map does not have built in support for this type as it requires more complicated code to draw to screen.
However, you may be able to use this source through a 3rd party plugin for flutter_map, such as https://github.com/greensopinion/flutter-vector-map-tiles.

Hope this works for you!
