### ISSUE TITLE
Issue with flutter_map_popup_marker

### ISSUE THREAD

**Issue by Swepilot** [fleaflet/flutter_map#1072]
Hi!

Been using flutter_map 1.5 years by now, and finally took the plunge to update to the latest version, 0.14.0. This of course involved switching to LatLong2 and a lot of other repos needed updates too, including flutter_map_popup_marker which is now added as a widget instead of a plugin.

Some addons like lat_long_grid_plugin are still added to `List<LayerOptions>` instead of `List<Widgets>`. My problem now is that as soon as I add lat_long_grid_plugin (or anything else) in `nonRotatedLayers` the popup marker functionality stops. Nothing is popping!

It seems the `nonRotatedLayers` is preventing the taps from hitting the widget in `nonRotatedChildren`. If I remember correctly, layers are always rendered on top of children, regardless of the order in `mapOptions`

Any clever ideas/solutions?

Thanks!

PS. Also commented here https://github.com/rorystephenson/flutter_map_marker_popup/issues/23 DS.

**Comment by Swepilot** [comment]
Working example to reproduce. 
From pubspec.yaml
 flutter_map: ^0.14.0
 flutter_map_marker_popup: ^2.0.0
 lat_lon_grid_plugin:
 latlong2:

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map_marker_popup/flutter_map_marker_popup.dart';
import 'package:latlong2/latlong.dart';
import 'package:lat_lon_grid_plugin/lat_lon_grid_plugin.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Map Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Map Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(

          title: Text(widget.title),
        ),
        body: Center(
          child: Container(
            height: MediaQuery.of(context).size.height,
            child: FlutterMap(
              options: MapOptions(
                center: LatLng(0, 0),
                plugins: [
                  MapPluginLatLonGrid(),
                ],
              ),
              nonRotatedLayers: [
                // Comment/uncomment MapPluginLatLongGridOption below to hide/show 
                // the latlong grids and notice how popup of the marker is 
                //not working the the grids showing
                
                // MapPluginLatLonGridOptions(
                //   lineColor: Colors.grey,
                //   textColor: Colors.white,
                //   lineWidth: 1,
                //   textBackgroundColor: Colors.grey,
                //   showCardinalDirections: true,
                //   showCardinalDirectionsAsPrefix: true,
                //   textSize: 12.0,
                //   showLabels: true,
                //   rotateLonLabels: true,
                //   placeLabelsOnLines: true,
                //   offsetLonTextBottom: 20.0,
                //   offsetLatTextLeft: 20.0,
                // ),
              ],
              nonRotatedChildren: [
                PopupMarkerLayerWidget(
                    options: PopupMarkerLayerOptions(
                        popupBuilder: (BuildContext context, Marker marker) {
                          return Text("Test popupmarker");
                        },
                        markers: [
                      Marker(
                          point: LatLng(0, 0),
                          builder: (BuildContext context) {
                            return Icon(Icons.location_on);
                          })
                    ]))
              ],
            ),
          ),
        ));
  }
}

```

**Comment by rorystephenson** [comment]
I can confirm after some debugging that this is happening because there is [no way to put children plugins on top of layer plugins](https://github.com/fleaflet/flutter_map/blob/95a8d26b353fc3cc62f29f210c2a91be8a5a2d5f/lib/src/map/flutter_map_state.dart#L168-L186).

Potential solutions:

1. Plugins which don't support being added as a child/non-rotated child should have add support for it, then you can order the plugins as you wish.
2. Modify the lat lon grid plugin to stop if from capturing tap events, this can be achieved by wrapping it with a `IgnorePointer` [here](https://github.com/matthiasdittmer/lat_lon_grid_plugin/blob/d8e8e9c9b0a63ee8ca58107804926d2873c1d7cf/lib/lat_lon_grid_plugin.dart#L97).
3. Change flutter_map so that it's possible to order children/layers as you wish.

I think the first solution is the best as [it seems](https://github.com/fleaflet/flutter_map/pull/619#issuecomment-655655772) that the intention is to eventually remove the options/layers method for including plugins and to just add plugins as children/non-rotated children.

**Comment by neimproove** [comment]
Thanks a lot for taking your time to look into this. It looks like I'll have to chase up some plugin developers and/or doing some forking 😅

**Comment by Swepilot** [comment]
Thanks a lot for taking your time to look into this. It looks like I'll have to chase up some plugin developers and/or doing some forking 😅
