### ISSUE TITLE
scaling the whole application

### ISSUE THREAD

**Issue by mohammedX6** [fleaflet/flutter_map#1073]
I am trying to scale my whole application because everything looks small, so I find [this libary](https://github.com/Codelessly/ResponsiveFramework), it's working correctly with some minor issues, but callbacks like "onTap", "onLongPress" returns wrong coordinates.

**Comment by alexandrim0** [comment]
Same problem is actual for me.
Did you solve it?

**Comment by ibrierley** [comment]
Can you clarify the small thing. Screenshot may be useful.

**Comment by alexandrim0** [comment]
body: isMobile
          ? LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) =>
                  OverflowBox(
                maxHeight: constraints.maxHeight * 2,
                maxWidth: constraints.maxWidth * 2,
                child: Transform.scale(
                  scale: 0.5,
                  child: const MapWidget(),
                ),
              ),
            )
          : const MapWidget(),

I would be nice to have some parameter to do that.
Also it could affect some calculations, for example tap of coordinates and etc.

**Comment by mohammedX6** [comment]
@alexandrim0 I ended up not using scaling in my app.
