### ISSUE TITLE
 jsonEncode/jsonDecode not work

### ISSUE THREAD

**Issue by wzhou-grid** [fleaflet/flutter_map#1078]
It seems like jsonDecode/jsonEncode with Polygon objects not work. Is there any implement to resolve this? thanks.

**Comment by ibrierley** [comment]
What have you tried ?

**Comment by wzhou-grid** [comment]
> What have you tried ?

`try {
    var _str = jsonEncode(_polygon);
}
catch(e){
  print(e.toString());
}`
The result is _Converting object to an encodable object failed: Instance of 'Polygon'_

**Comment by Swepilot** [comment]
I would assume the Polygon object is not serializable

**Comment by ibrierley** [comment]
I assume you could probably do something like traverse the polygon, create a Map from it, then that would convert ?

**Comment by wzhou-grid** [comment]
> I assume you could probably do something like traverse the polygon, create a Map from it, then that would convert ?

yeah. that works. thank you.
