### ISSUE TITLE
Unnecessary log on zoom level changed

### ISSUE THREAD

**Issue by pseusys** [fleaflet/flutter_map#1079]
Every time map is resized in flutter WEB zoom level and some boolean is logged into console. How can I disable it?  
Log example:
```
false
zoom: 9.25
false
zoom: 9.5
false
zoom: 9.75
false
zoom: 10
false
zoom: 10.25
false
zoom: 10.5
false
zoom: 10.75
false
zoom: 11
false
zoom: 11.25
false
zoom: 11.5
false
zoom: 11.75
false
zoom: 12
false
zoom: 12.25
false
zoom: 12.5
false
zoom: 12.75
false
zoom: 12.5
false
zoom: 12.25
false
zoom: 12
false
zoom: 11.75
false
zoom: 11.5
false
zoom: 11.25
false
zoom: 11
false
zoom: 10.75
false
zoom: 10.5
false
zoom: 10.25
false
zoom: 10
```

**Comment by kengu** [comment]
There are some print commands left in the code from debugging it seams.

**Comment by pseusys** [comment]
Just as I thought! There is one more issue I/d like to report, it's not very important (for me), however may require attention in future releases.
In flutter WEB `interactiveFlags` do not always work as expected, for example `pinchZoom` can not be disabled (in case of laptop with a touchpad), and `pinchMove`, in contrary, can not be enabled.

**Comment by danielmahon** [comment]
PING

**Comment by pseusys** [comment]
Thank you! I'll try it later.
