### ISSUE TITLE
Animation on MapController.move()

### ISSUE THREAD

**Issue by liamsammut97** [fleaflet/flutter_map#1084]
is it possibile to have an animation on MapController.move() so moving the map is smoother ? Thanks in advance !

**Comment by Vafin84** [comment]
I support, I also encountered this problem.

**Comment by theArtechnology** [comment]
There is a lot of maths going there, tweening and interpolation, maybe this can be helpful to add this to the plugin:

https://github.com/gauris26/flutter_animarker/tree/master/lib/animation

**Comment by JaffaKetchup** [comment]
Hi there,
You might want to take a look at https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart?

**Comment by liamsammut97** [comment]
I found a Great fix take a look at this https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart
hope it can help !!

**Comment by Vafin84** [comment]
Thank you. Indeed, this seems to be what I need.

**Comment by theArtechnology** [comment]
Nice, it is good, is there a way to make the marker move smooth, not just the zoom
