### ISSUE TITLE
How to dynamically update markers and polylines without redrawing entire Map  (with setState) ?

### ISSUE THREAD

**Issue by fvisticot** [fleaflet/flutter_map#1089]
I'm using this plugin to dynamically display multiple markers and polylines on the map in real time.
More than 200 makers and up to 200 polylines.

Using the setState to update the full FlutterMap seems not a good idea for performance reasons.

It seems a solution has been started but I'm not sure it'is maintained anymore (and not null safety)

[map_controller plugin](https://github.com/synw/map_controller/issues/25)

Is there any solution / roadmap / external plugin providing a dedicated controller for "real time" modifications on markers and polylines ?

**Comment by akeblom** [comment]
This is highly requested from me as well.

**Comment by ibrierley** [comment]
I feel like updating the marker contents may be possible without a full setState, but not sure about moving the position of it without a full setState. I may be wrong though, so someone else may have some ideas.

Do you have a minimal testing example that folks could look at ? 

Just as an aside...

I suspect using setState on individual polylines may not be as optimial as one would think, but I may well be very wrong on that. So its worth testing out. But ultimately if you move a single polyline for example, behind the scenes, one way or another I imagine the Canvas has to recalculate it all anyway (i.e lets suppose you move a poly that was in front of another one to behind it, it still has to figure out what are the correct Strokes to show). However, there may be some caching and api reduced calls or something that helps...just thinking out loud.

There seems to be quite a few issues that pop up regarding markers/polys/labels/tapping them and performance, that maybe suggests a new plugin would be warranted. I have some ideas on it all, but not quite the time atm, but would be happy to contribute thoughts if someone wanted a stab at it.

**Comment by RickyvdBerg** [comment]
> I feel like updating the marker contents may be possible without a full setState, but not sure about moving the position of it without a full setState. I may be wrong though, so someone else may have some ideas. 

Have there since the creation of this issue been any updates to this? I need to update polygonline's life. Imagine it like a flight tracker where a lone follows the plane.
