### ISSUE TITLE
How to attach videos from API inside markers on onTap events? 

### ISSUE THREAD

**Issue by aedthuill** [fleaflet/flutter_map#1090]
Hello. Thanks you for such great plugin, but I have the quite complicated issue, so I decided to ask here. So I want to create the map where user can tap on markers and it opens with the video stream from the API. 

So, my question is: is there any flutter map plugin that can do this?

Thanks you.

**Comment by ibrierley** [comment]
I'm probably misunderstanding...wouldn't you just add a VideoPlayer() Widget or similar  on click or something ? Not quite sure what it has to do with flutter_map.
