### ISSUE TITLE
The latLng obtained through onTap of MapOptions is inaccurate

### ISSUE THREAD

**Issue by antu58** [fleaflet/flutter_map#1091]
MapOptions mapOptions() {
    return MapOptions(
      center:  LatLng(39.9091, 116.3941,),
      minZoom: 2.0,
      maxZoom: 18,
      zoom: 16.0,
      onTap: (LatLng latLng) {
        //It looks different from the position touched by the hand
      }
    );
  }

**Comment by ibrierley** [comment]
How far out is it ? What happens if you place a marker at the latlng ?

**Comment by Zzerr0r** [comment]
you probably didnt center your marker correctly on the latlng, the position is accurate from what i experienced

**Comment by cyrilhl** [comment]
No, this issue can simulate if you tap the map after zoom. If you did not zoom the map before tap,  the latLng obtained is correct, but not after zoom. I think this is a bug on calculate the tap location without getting the latest zoom value.

**Comment by Zzerr0r** [comment]
@cyrilhl why do you think its inaccurate? how do you come to the conclusion?

**Comment by cyrilhl** [comment]
Please review the screen record that can reproduce the issue, my device is one plus 3T with lineage os 
https://drive.google.com/file/d/15jmcGQD-IQ5VdpebQTA9o-LOue_qLb_e/view?usp=sharing

I am on Flutter 2.5.3 with getx 4.6.1, and attached with the widget for your reference. 
[flutter-map-on-tap-issue.zip](https://github.com/fleaflet/flutter_map/files/7922372/flutter-map-on-tap-issue.zip)

**Comment by JaffaKetchup** [comment]
This screen recording shows that the marker moves to the correct location, after another location has been pressed: ie. it is accurate, but delayed.

This may be something to do with your state management solution, or it may be a bug in flutter_map. It just seems the widget doesn't get rebuilt correctly.

**Comment by cyrilhl** [comment]
The marker is totally not on the location where I tap at the last 10 sec in my video, I know don't why you can say that is still accurate. I suggested you to download the whole video onto you computer to see instead of directly on google drive, since that is compressed on preview and the timing is really different after you download.

I agree that state management solution can be one of the cause, but this cannot explain the different between the tap location before and after zoom.

**Comment by JaffaKetchup** [comment]
Sorry, my mistake. Wasn't showing me the whole video for some reason. Now I can see that it does get less accurate the more zooming is done.

**Comment by cyrilhl** [comment]
If state management cause the issue, most likely the location is always incorrect, but inside my code I use the lat lng directly to create the marker, so I don't think this is the root cause. 

And I use Getx in all of my projects, it can compatible will all packages on pub.dev, I think flutter map can compatible with it without any special handling

**Comment by ibrierley** [comment]
I note you are using nonrotatedchildren and layers....is it possible you are rotating the map when zooming, and you can't see that or something. To isolate, try adding     interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate  to your mapoptions and see if the behaviour is the same.

**Comment by cyrilhl** [comment]
Thank you so much, since my client required to disable the rotation on map, so that the reason I using nonrotated children and layers.
And after setting the "interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate", the tap location is correct no matter zoom in or out. Thank you so much !!

**Comment by tk2232** [comment]
I have the same issue. 

```dart
class MapsBaseWidget extends StatefulWidget {
  const MapsBaseWidget({
    Key? key,
  }) : super(key: key);

  @override
  State<MapsBaseWidget> createState() => _MapsBaseWidgetState();
}

class _MapsBaseWidgetState extends State<MapsBaseWidget> {
  final List<Marker> markers = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FlutterMap(
        options: MapOptions(
            center: LatLng(51.5, 9.05),
            zoom: 13.0,
            onLongPress: (_, LatLng latLng) {
              setState(() {
                markers.add(Marker(
                  width: 80.0,
                  height: 80.0,
                  point: latLng,
                  builder: (ctx) => const Icon(Icons.location_on),
                ));
              });
            }),
        layers: [
          TileLayerOptions(
            urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            subdomains: ['a', 'b', 'c'],
            attributionBuilder: (_) {
              return Text("© OpenStreetMap contributors");
            },
          ),
          MarkerLayerOptions(
            markers: markers,
          ),
        ],
      ),
    );
  }
}
```

here is an image with tap position and marker on wrong place.
Fresh card not rotated or zoomed

![image](https://user-images.githubusercontent.com/33070559/151420965-9fa2a9a4-f46f-43e5-926c-89219a3deb10.png)

**Comment by ibrierley** [comment]
Your example works fine for me.

**Comment by tk2232** [comment]
Ok I found the bug. I'm using the responsive_framework as a result, the positions do not match.
Thank you for your help

**Comment by Fraganya** [comment]
If anyone is still having this issue here is something you might want to check out.

I was having the same issue, what i noticed was that the marker widget size can significantly skew the placement on the map. 

So check that.
