### ISSUE TITLE
reset, as shown in the example app, does not seem to clear the cache

### ISSUE THREAD

**Issue by juri117** [fleaflet/flutter_map#1096]
I tried to implement a reset button to force a reload of my tiles.
I followed the example:
https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/reset_tile_layer.dart
where it says in the description: "TileLayers can be progromatically reset, disposing of cached files".
What I expected was, that all currently displayed (and cached) tiles will be disposed and a full reload of all tiles is performed.

However, when running the example (current master, windows-desktop), it is visible that the cache is not cleared, since the whole map is there at once when pressing "Reset" multiple times. While on app startup, when the cache is actually empty, the tiles visibly are being loaded and displayed successive.

I could confirm this when using my own tile server. After the initial load, there are no additional requests when trying the reset with `resetController.add(null);`.

Please let me know if I got something wrong or if you need more information.
Thank you for your awesome work :)

**Comment by ibrierley** [comment]
I suspect there's some confusion as to "which" cache.

The Flutter_map reset probably deletes all the tiles from the flutter_map "cache" (I feel this is probably the wrong terminology for what it is here, but it is a type of cache).
There is probably a filesystem type of url caching, that flutter_map doesn't really touch too much (the http get type packages/plugins may do).

So I suspect what's happening is that you are in fact resetting the flutter_map "cache", it's just the images are still cached on the filesystem, so no http call is needed ?

**Comment by juri117** [comment]
wow, thank you @ibrierley, exactly the hint in the right direction, that I needed :D

If anybody else wants to **reload all map tiles** from the server:
Add `imageCache?.clear();` to your reset routine.
In the reset example ([reset_tile_layer.dart](https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/reset_tile_layer.dart#L29)), it could look like this:
```
  void _resetTiles() {
    setState(() {
      layerToggle = !layerToggle;
    });
    imageCache?.clear();
    resetController.add(null);
  }
```

note: this clears all images, also the non map tile ones, to change that, I guess you could overwrite the clear cache method like shown [here](https://stackoverflow.com/questions/47209606/how-do-i-clear-flutters-image-cache)
