### ISSUE TITLE
I found a fatal mistake，Keep repeating zoom in and out，Will cause the app to collapse

### ISSUE THREAD

**Issue by zjyhll** [fleaflet/flutter_map#1097]
I found a fatal mistake
Keep repeating zoom in and out，Will cause the app to collapse

**Comment by ljmatan** [comment]
@zjyhll which OS and device model?

**Comment by JaffaKetchup** [comment]
Can you provide any information, such as logs?

**Comment by JaffaKetchup** [comment]
@zjyhll Please provide some more information: does your crash match #1134? It would be extremely useful to have your input.

**Comment by magnuswikhog** [comment]
We're getting customer reports of this as well. The app crashes hard on two separate Galaxy Tab A (SM-T510, Android 11) after zooming out and then zooming in quickly again. Strange thing is I can't find any crash reports in Crashlytics, and we're unable to reproduce it on any test devices. The affected version of our app is using Flutter Map version `0.12.0`.

**Comment by ibrierley** [comment]
Areyou using any plugins at all ?
