### ISSUE TITLE
How should I check if the MapController is ready?

### ISSUE THREAD

**Issue by magnuswikhog** [fleaflet/flutter_map#1101]
There used to be a property called `ready` on the `MapController`, but for some reason it has been removed in an update. 

Any particular reason this was removed? How should I check if the controller is ready now? I know there is a `onReady` future, but what if I don't want to wait for the controller to be ready? 

What if I just want to check wether or not it's ready right now, in a synchronous method?

**Comment by Heknon** [comment]
You can use "onMapCreated" parameter in "FlutterMap" along with a "[Completer](https://api.flutter.dev/flutter/dart-async/Completer-class.html)".

This is how I did it:
```dart
late Completer<MapController> controllerCompleter = Completer();

void _onMapCreated(MapController controller) async {
    controllerCompleter.complete(controller);
  }
```

You can then access the controller as if it is a future using "controllerCompleter.future"

Hope this helps!

**Comment by JaffaKetchup** [comment]
Hi @magnuswikhog,
Do you still require support? Happy to try to help!

**Comment by magnuswikhog** [comment]
@JaffaKetchup I'm using the workaround I posted in another issue (https://github.com/fleaflet/flutter_map/issues/926#issuecomment-994954459), which takes care of this as well. 

Thanks for the follow up!
