### ISSUE TITLE
Remove grey margins above and below

### ISSUE THREAD

**Issue by KirschbaumP** [fleaflet/flutter_map#1103]
When I zoom out I can see grey margins above and below the map. Are there ans solutions how to solve this issue?

**Comment by KirschbaumP** [comment]
That is the same problem like #831, but the solution doesn't work.

**Comment by Aristidios** [comment]
Also looking to remove grey edges on Flutter Map

**Comment by KirschbaumP** [comment]
Can someone help us with this problem? Or do you need additional information?

**Comment by ibrierley** [comment]
So, just to clarify the problem...you have set
swPanBoundary: LatLng(56.6877, 11.5089),
nePanBoundary: LatLng(56.7378, 11.6644),

or whatever it is, to restrict the pan, does "bounds" do anything if restricted to that ?

Is it just the manual zooming that leads to the problem ?
