### ISSUE TITLE
OnTap arguments within MapOptions

### ISSUE THREAD

**Issue by W2NJL** [fleaflet/flutter_map#1104]
Hi all,
    I am trying to use a basic FlutterMap implementation so that a user can select a location on a map by tapping that location.  Once they tap, a marker will appear over it, and then they can hit a submit button below the FlutterMaps widget on my app, which will send the LatLng of the location they chose to another part of my application.  

I feel like the best way to do this would be to make use of the onTap option right out of MapOptions?  However, can anyone possibly guide me as how to ascertain the formatting for the arguments the MapOptions onTap requires?  

It appears to require a function that includes a TapPosition and a LatLng.  I can't seem to find anything referencing how a TapPosition should be formatted.  Might anyone have an example or documentation?  

Thank you for any help in advance!

**Comment by JaffaKetchup** [comment]
Hello there,
You are indeed correct that `onTap` is the correct way to do this. `onTap` takes a void function that takes a `TapPosition` and `LatLng` as it's arguments.

`TapPosition` contains information related to where you tapped on the screen (`global` for 'out of whole screen'; `relative` for 'within the parent widget'), which is primarily used internally to calculate the `LatLng`.
`LatLng` is the more useful argument to most people and will contain the coordinates at which the user tapped on the map, not on the screen.

Therefore, for your use case, you would likely 'drop' the `TapPosition` and just use `LatLng`, as shown in this example:
``` dart
options: MapOptions(
    onTap: (_, point) {
        // 'point' will be the map location tapped
    },
),
```

Hope this answered your question!

**Comment by W2NJL** [comment]
> Hello there, You are indeed correct that `onTap` is the correct way to do this. `onTap` takes a void function that takes a `TapPosition` and `LatLng` as it's arguments.
> 
> `TapPosition` contains information related to where you tapped on the screen (`global` for 'out of whole screen'; `relative` for 'within the parent widget'), which is primarily used internally to calculate the `LatLng`. `LatLng` is the more useful argument to most people and will contain the coordinates at which the user tapped on the map, not on the screen.
> 
> Therefore, for your use case, you would likely 'drop' the `TapPosition` and just use `LatLng`, as shown in this example:
> 
> ```dart
> options: MapOptions(
>     onTap: (_, point) {
>         // 'point' will be the map location tapped
>     },
> ),
> ```
> 
> Hope this answered your question!

I will try this...thank you so much for your lightning fast response - happy holidays!

**Comment by W2NJL** [comment]
Solved my issue - thank you!
