### ISSUE TITLE
Map image is not rendering in web it is coming as white page wgen i am running my project in chrome

### ISSUE THREAD

**Issue by Abhishek8-198** [fleaflet/flutter_map#1106]

**Comment by Abhishek8-198** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart' as latlong;
            

class MapBoxWeb extends StatefulWidget {
  @override
  _MapBoxWebState createState() => _MapBoxWebState();
}

class _MapBoxWebState extends State<MapBoxWeb> {
  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      options: new MapOptions(
        center: latlong.LatLng(28.479462047712307, 77.51447532422465),
        zoom: 13.0,
      ),
      layers: [
        new TileLayerOptions(
          urlTemplate:
              "https://api.mapbox.com/styles/v1/abhi-8198/ckxfstd77h3jp15s9zwkzz5em/wmts?access_token=pk.eyJ1IjoiYWJoaS04MTk4IiwiYSI6ImNreGVxY2R4aDFiNWcyb3Bka2l0aXQwdXAifQ.40GzI4Y_AaCPrHLGMtEYnA",
          additionalOptions: {
            'accessToken':
                'pk.eyJ1IjoiYWJoaS04MTk4IiwiYSI6ImNreGVxY2R4aDFiNWcyb3Bka2l0aXQwdXAifQ.40GzI4Y_AaCPrHLGMtEYnA',
            'id': 'mapbox.mapbox-streets-v8',
          },
        ),
        new MarkerLayerOptions(
          markers: [
            new Marker(
              width: 80.0,
              height: 80.0,
              point: latlong.LatLng(28.479462047712307, 77.51447532422465),
              builder: (ctx) => new Container(
                  child: IconButton(
                      icon: Icon(Icons.location_on),
                      color: Colors.red,
                      iconSize: 45.0,
                      onPressed: () {
                        print('Marker tapped');
                      })),
            ),
          ],
        ),
      ],
    );
  }
}

**Comment by JaffaKetchup** [comment]
Hi there,
It appears you are setting up Mapbox with WMTS mode incorrectly. Please visit the beta documentation to hopefully fix your issue: https://flutter-map.vercel.app/servers/using-mapbox.
Hope it works!
