### ISSUE TITLE
disable onTap event

### ISSUE THREAD

**Issue by mohammedX6** [fleaflet/flutter_map#1111]
I want to disable map events like onTap because i want to wrap the whole map with InkWell

**Comment by FallenRiteMonk** [comment]
It would also be great to be able to disable longpress. If a user longpresses and then drags, I would like him to move the map. Currently this does not do anything as the onLongPress event fires.

**Comment by FallenRiteMonk** [comment]
Still a issue for me

**Comment by mohammedX6** [comment]
No please my dear bot

**Comment by JaffaKetchup** [comment]
Hi @mohammedX6, sorry for the long wait.
I'll have a look into this soon.

**Comment by TesteurManiak** [comment]
@mohammedX6 why not just wrap the map with the `AbsorbPointer` widget then wrap the entire thing with your `InkWell`

```dart
class Issue1111View extends StatelessWidget {
  static const routeName = '/issue_1111';

  const Issue1111View({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Issue 1111')),
      body: InkWell(
        onTap: () => print('Tapped on the map'),
        child: AbsorbPointer(
          child: FlutterMap(
            options: MapOptions(),
            layers: [
              TileLayerOptions(
                urlTemplate:
                    "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                subdomains: ['a', 'b', 'c'],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by JaffaKetchup** [comment]
Hi there,
I apologize for the long wait time. I'll try to remember to have a look at it ASAP.
Thanks for your patience.

**Comment by JaffaKetchup** [comment]
Since the v3 gesture implementation is very different, it may now be possible to do this easily and reliably. I'll have a look into it - sorry for the delay.

**Comment by mohammedX6** [comment]
Good work guys !

**Comment by JaffaKetchup** [comment]
I haven't had a chance to look into this yet, I've been really busy. If anyone else wants to take a look, please do! As I said, it may be easier now with v3.

**Comment by JaffaKetchup** [comment]
Closing this for now. I think there are suitable workarounds (such as `IgnorePointer`), and this is a fairly niche use case I would imagine.
