### ISSUE TITLE
Marker issue

### ISSUE THREAD

**Issue by Lawati97** [fleaflet/flutter_map#1112]
Whenever i try to set a column for the marker builder (to have the icon button and the name of the user) I get the bottom overflow no matter how I increase the size of the marker 

using flutter_map: ^0.14.0

**Comment by ibrierley** [comment]
Might be useful to include the code for others to look at.

**Comment by mohammedX6** [comment]
Use `Stack` insted of `Column`

**Comment by JaffaKetchup** [comment]
Hi @Lawati97,
Do you still require support? Happy to try to help, if you can provide some more details?
Thanks.

**Comment by ibrierley** [comment]
Closing, feel free to open if still a problem and you can include some code to reproduce
