### ISSUE TITLE
LateInitializationError: Field 'boundingBox' has already been initialized

### ISSUE THREAD

**Issue by jithware** [fleaflet/flutter_map#1119]
Similar to Issue #1037, this issue occurs with polylines when polylineCulling is set to true

```
PolylineLayerWidget(
  options: PolylineLayerOptions(
    polylines: polylines,
    polylineCulling: true,
  ),
),
```

Here is code to reproduce bug and fix:

Pull request https://github.com/fleaflet/flutter_map/pull/1110

**Comment by jithware** [comment]
Anyone willing to review https://github.com/fleaflet/flutter_map/pull/1110?

**Comment by JaffaKetchup** [comment]
@jithware Please see the Discussion on the future of flutter_map. TLDR: At the moment, the maintainers don't seem to be around, so nothing can get merged to the master branch.

**Comment by jithware** [comment]
> @jithware Please see the Discussion on the future of flutter_map. TLDR: At the moment, the maintainers don't seem to be around, so nothing can get merged to the master branch.

@JaffaKetchup thanks for update. For those interested see https://github.com/fleaflet/flutter_map/discussions/1117

**Comment by jithware** [comment]
Yeah should be all set. I'll go ahead and close.
