### ISSUE TITLE
3D buildings

### ISSUE THREAD

**Issue by adnanefouam** [fleaflet/flutter_map#1121]
Is it possible to add pitch degrees with 3D feature to flutter_map ?
<img width="826" alt="Screenshot 2022-01-10 at 11 40 11" src="https://user-images.githubusercontent.com/59290932/148752741-04c1933f-a2d5-4e25-bc78-83f6b3481367.png">

**Comment by ibrierley** [comment]
Realistically, I'd say not in the short term. There's sometimes some clever things that can be done, but I'm assuming you mean full 3d that can be rotated etc as well. Things like pitch/perspective on a flat plane aren't impossible with a lot of work, but there's some issues probably when it comes to rotating etc with them.

If there's a general solution that needs pitch, it may be worth elaborating more, but I think if it's pure 3d, you may be better off looking at some of the other solutions (I'm not sure there are any 3d working in Leaflet.js either, I'd be interested if you knew some).

**Comment by adnanefouam** [comment]
Many thanks for the prompt reply, i thought of applying Widget Layers and add mapboxGL widget instead of TileLayerWidget(),
and when i activate the 3D on the mapbox widget i'll also transform my polygon layers the same degrees and i'll disable the rotation feature something like this ,

`map.MapboxMap(
            styleString: map.MapboxStyles.LIGHT,
            accessToken:
                "TOKEN",
            initialCameraPosition: const map.CameraPosition(
              target: map.LatLng(0.0, 0.0),
            ),
          ),
 PolygonLayerWidget(
            options: PolygonLayerOptions(
              polygonCulling: true,
              polygons: widget.selectedParcelle!,
            ),
          ),

`

**Comment by JaffaKetchup** [comment]
Will close now as this likely won't be added. Please feel free to ask to reopen if you would like!

**Comment by vaibhavinsuide** [comment]
Why dont you support tilt & bearing in flutter map. for 3D Maps

**Comment by ibrierley** [comment]
How would you be drawing the 3d maps ?

**Comment by vaibhavinsuide** [comment]
with the help of Flutter Map Package & used style URL which is already 3D but there is no option of bearing & tilt in Flutter Map

**Comment by ibrierley** [comment]
Which provider for the 3d maps are you looking at, can you give an example of the url you would be using to retrieve the tiles ? I'm trying to understand how you would be rendering the 3d buildings etc....

**Comment by ibrierley** [comment]
I'm guessing for this you are using the mapbox-gl layer (if so, what happens if you provide a pitch yourself...what do you need flutter_map to do...)?

**Comment by vaibhavinsuide** [comment]
I am using MapBox Street Style URL  3D  in Flutter Map Package. but without tilt & bearing option in Flutter Map. doesn't look a 3D.

**Comment by ibrierley** [comment]
Can you give a minimal example (without your mapbox keys). I think the main thing that's not clear here...is if mapbox is drawing these in vector tiles which can adapt on the fly (and the view will change if you do provide a bearing), or raster tiles, which couldn't.

**Comment by vaibhavinsuide** [comment]
return FlutterMap(
        mapController: mapController,
        options: new MapOptions(
            plugins: [
              MarkerClusterPlugin(),
            ],
            center: new LatLng(41.259555383140835, 28.741587357328253),
            minZoom: 18,
            maxZoom: 40,
            zoom: 20,
            pinchMoveThreshold: 10,
            enableMultiFingerGestureRace: false,
            rotationThreshold: 40.0,
            rotationWinGestures: 20,
            pinchMoveWinGestures: 50),
        layers: [
          TileLayerOptions(
              urlTemplate: Constant.MAP_STYLE_URL,
              additionalOptions: {
                'accesstoken':
                    Constant.MAP_ACCESS_TOKEN,
                'id': 'mapbox.mapbox-streets-v8'
              },
              maxNativeZoom: 20,
              maxZoom: 40),
          MarkerClusterLayerOptions(
              spiderfyCircleRadius: 80,
              spiderfySpiralDistanceMultiplier: 4,
              circleSpiralSwitchover: 16,
              maxClusterRadius: 120,
              rotate: true,
              size: Size(40, 40),
              anchor: AnchorPos.align(AnchorAlign.center),
              fitBoundsOptions: FitBoundsOptions(
                padding: EdgeInsets.all(50),
                maxZoom: 10,
              ),
              markers: isMapRead ? showFilterMarker : showMarker,
              builder: (context, marker) {
                return Container();
              }),

        ]);
see I shared the code only I want to show the MAP in 3D way.

**Comment by vaibhavinsuide** [comment]
I am not using Mapbox gl I am using Flutter Map

**Comment by ibrierley** [comment]
ok, then I don't see how this could even ever work if wanted to (if using normal raster tiles and not something like mapbox-gl).
