### ISSUE TITLE
Bounding box of List<Polygon>

### ISSUE THREAD

**Issue by adnanefouam** [fleaflet/flutter_map#1122]
Can i get the bounding box of a group of polygons List<Polygon> ?

**Comment by ibrierley** [comment]
I _think_ the Polygon class has a boundingBox property, so see if you can access that.

**Comment by ibrierley** [comment]
Actually, not sure that would really help if you need it for a list of polys....so it may just be as quick to roll your own method anyway as its just a min/max type loop isn't it ?

**Comment by JaffaKetchup** [comment]
Hi there @adnanefouam.
Do you still require support? Happy to try to help!

**Comment by adnanefouam** [comment]
@JaffaKetchup Yes!  thank you, in my case i need the bounding box of a group of polygons,
Like => (List<Polygon> myPolygons) not just one item from  my list

**Comment by JaffaKetchup** [comment]
Ok, no problem. I'm assuming that we're dealing with rectangles here, would need to think some more for any polygon.

The way I'd approach this is take out all of the corners of each bounding box into separate lists: ie. 4 lists for each corner of the overall rectangle, containing `LatLng`s.

Then, create a method to find the furthest coordinate in each corner, by evaluating the main/max of each part of each coordinate. For example, you'd want the minimum longitude and maximum latitude for the northwest point.

Hope this helps!
