### ISSUE TITLE
Screenshot feature (aka convert map into an image)

### ISSUE THREAD

**Issue by gcsaba2** [fleaflet/flutter_map#1123]
We're drawing routes (polygons) on the map and would like to enable users share these maps as pictures. Is there any way to take a snapshot of the current map and convert it into png?

**Comment by JaffaKetchup** [comment]
Does this do what you require: https://pub.dev/packages/screenshot?

**Comment by gcsaba2** [comment]
Perfect, thanks!

**Comment by Flokart** [comment]
Hi guys, I'm using the same package but there's a small thing I could use help with if you've had the same problem. My specific use case requires an automatic zoomOut to fit the user created markers inside the screenshot. The problem with that is that the screenshot is usually taken before the map is completely loaded on the sides after zooming out. I was thinking if there's any way to pre-load a larger portion of the map beforehand. Thank you!

https://user-images.githubusercontent.com/25905620/150745735-24f13466-fcc7-418b-9ea3-6e29f98bdb95.mp4

**Comment by mohammedX6** [comment]
@Flokart to to wait for example 3 seconds before doing the screenshot
