### ISSUE TITLE
Tile boundaries visible at certain zoom levels

### ISSUE THREAD

**Issue by pmjobin** [fleaflet/flutter_map#1126]
I built the demo app using Flutter 2.8.1 (desktop linux target) and I noticed that tile boundaries pop out as white lines at certain zoom levels while they are seamless at others.

![Screenshot from 2022-01-12 15-35-32](https://user-images.githubusercontent.com/1387411/149209616-a19bc571-f627-46cc-beaf-5a9ea51015a2.png)

**Comment by jiazeh** [comment]
Same issue, and this issue only happens on Flutter 2.8.x and above..

**Comment by mohammedX6** [comment]
+1

**Comment by DrNorton** [comment]
+1

**Comment by ibrierley** [comment]
Does this happen on mobile too, or just on desktop ?

**Comment by DrNorton** [comment]
> Does this happen on mobile too, or just on desktop ?

On mobile too, but only with disabled rotation

**Comment by JaffaKetchup** [comment]
This seems strange, and would be probably Flutter 2.8's fault, because I haven't seen this before.
Maybe the changelog will hold the answers?

**Comment by DrNorton** [comment]
I think that located problem, if I delete Opacity widget in _AnimatedTileState

**Before**:

`   return Opacity(
      opacity: widget.tile.opacity,
      child: widget.tileBuilder == null
          ? tileWidget
          : widget.tileBuilder!(context, tileWidget, widget.tile),
    );`

**After**:

` return widget.tileBuilder == null
        ? tileWidget
        : widget.tileBuilder!(context, tileWidget, widget.tile);`

The problem is gone. There are no white lines.

And there are many opacity issues that were merged in [release notes](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-2.8.

**Comment by ibrierley** [comment]
Good find, this url should work if anyone has problems with above url https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-2.8.0

**Comment by JaffaKetchup** [comment]
Duplicate of #1156

**Comment by mostafaac30** [comment]
same
