### ISSUE TITLE
print() statements in release builds

### ISSUE THREAD

**Issue by jithware** [fleaflet/flutter_map#1130]
When scrolling mouse wheel ```print(...)``` statements show up in release builds:
```
false
zoom: 13.170738050712146
false
zoom: 12.920738050712146
false
zoom: 12.670738050712146
false
zoom: 12.420738050712146

``` 

https://github.com/fleaflet/flutter_map/blob/95a8d26b353fc3cc62f29f210c2a91be8a5a2d5f/lib/src/gestures/gestures.dart#L36
https://github.com/fleaflet/flutter_map/blob/95a8d26b353fc3cc62f29f210c2a91be8a5a2d5f/lib/src/gestures/gestures.dart#L40

Proposed fix: remove all ```print(...)```

See https://dart-lang.github.io/linter/lints/avoid_print.html

**Comment by NaincyKumariKnoldus** [comment]
Hey @jithware I would like to do this. Can I please?

**Comment by JaffaKetchup** [comment]
This may be duplicate of #1079?

**Comment by NaincyKumariKnoldus** [comment]
Okay @JaffaKetchup no issues.

**Comment by jithware** [comment]
Duplicate of #1079
