### ISSUE TITLE
How to rotate and move map with animation?

### ISSUE THREAD

**Issue by Farrukh1198** [fleaflet/flutter_map#1148]
I would like to move and rotate map view according to users current location. For this purpose I use mapController.moveAndRotate(usercoords, zoom, heading);
But this function does it with no animation. Is there any way to move and rotate map view with smooth animation with linear easing?

**Comment by JosefWN** [comment]
You can do it using the `moveAndRotate` function with `Tween`s: https://api.flutter.dev/flutter/animation/Tween-class.html

```dart
mapController.moveAndRotate(
  centerTween.evaluate(animation),
  zoomTween.evaluate(animation),
  rotationTween.evaluate(animation),
);
```

**Comment by Farrukh1198** [comment]
Thank you

**Comment by Pepslee** [comment]
> You can do it using the `moveAndRotate` function with `Tween`s: https://api.flutter.dev/flutter/animation/Tween-class.html
> 
> ```dart
> mapController.moveAndRotate(
>   centerTween.evaluate(animation),
>   zoomTween.evaluate(animation),
>   rotationTween.evaluate(animation),
> );
> ```

Can you explain more details please ?
