### ISSUE TITLE
how to add draggable marker in flutter_map? I have used flutter_map_dragmarker: but it is not working. 

### ISSUE THREAD

**Issue by UsamaAndroid** [fleaflet/flutter_map#1149]
i have used flutter_map package and displayed mapbox map and Geoserver map using layers. Now i have to add draggable marker to proceed in my work and i do not find a way to add draggable marker. Actually i have added markers on onTap and onLongPress method but it does not give me drag action.

**Comment by JaffaKetchup** [comment]
Can you post some code, and potentially a video. We don't have very much information to help you with at the moment. Also note that, this may be an issue in an external plugin, which we may not be able to provide much support for.

**Comment by UsamaAndroid** [comment]
> Can you post some code, and potentially a video. We don't have very much information to help you with at the moment. Also note that, this may be an issue in an external plugin, which we may not be able to provide much support for.

After a lot of research of days I concluded that flutter_map package does not supports marker drag feature and I have done it by centering the marker and moving the map only. Ah and if you want code then I can share in the tomorrow morning. Ok thanks a lot.

**Comment by ibrierley** [comment]
I look after the dragmarker plugin, so feel free to raise an issue on there if something doesn't work. It's not really clear on this, what isn't working.

**Comment by Ahmed-gubara** [comment]
This is a code i'm using to move points on map.

 ```dart
  var _controller = MapController();
  final _points = <LatLng>[];

  @override
  Widget build(BuildContext context) {
    List<Marker> markers = List.generate(
      _points.length,
      (index) => Marker(
        width: 20,
        height: 20,
        point: _points[index],
        builder: (context) => GestureDetector(
          onPanUpdate: (DragUpdateDetails details) {
            CustomPoint<num> position = Epsg3857().latLngToPoint(_points[index], _controller.zoom);
            Offset delta = details.delta;
            LatLng? pointToLatLng = Epsg3857().pointToLatLng(position + CustomPoint(delta.dx, delta.dy), _controller.zoom);

            _points[index] = pointToLatLng!;

            setState(() {});
          },
          child: Container(...),
        ),
      ),
    );
  ......
  }
```

If it didn't move, then set MapOptions like this

```dart
MapOptions(
  allowPanningOnScrollingParent: false,
  ...
)
```

**Comment by ibrierley** [comment]
I think I'm going to close this, as there is code included and a possible plugin. Feel free to reopen if I've closed prematurely,
