### ISSUE TITLE
HTTP request failed, statusCode: 204

### ISSUE THREAD

**Issue by TweeM4N** [fleaflet/flutter_map#1150]
I want to get image from TileLayerOptions(), but I had Exception "HTTP request failed, statusCode: 204"

**Comment by ibrierley** [comment]
What zoom level and tileurl are you using ?

**Comment by TweeM4N** [comment]
> 

zoom: 7,
tileurl from API

**Comment by TweeM4N** [comment]
> What zoom level and tileurl are you using ?

zoom: 7,
tileurl from API
https://vtms.gptl.ru/tiles/{z}/{x}/{y}?url=s3://webdata/geoportal/RP1/GTNL1/2021/ETRIS.RP1.GTNL1.5569.5.0.2021-08-04.L2B1.MCHS_MUR.NTSOMZ_MSK.2021-10-12T084019Z.tiff

**Comment by ibrierley** [comment]
If I try that url with valid z,x,y it returns "NO CONTENT", so maybe there's something amiss there

**Comment by ibrierley** [comment]
Double check all works correctly with the normal example URLs eg urlTemplate: TileLayerOptions(
        urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        subdomains: ['a', 'b', 'c'],
        attributionBuilder: (_) {
          return Text("© OpenStreetMap contributors");
        },

Then if that works ok, I think there's something wrong with the understanding of that tile provider.
