### ISSUE TITLE
onRotation callback?

### ISSUE THREAD

**Issue by zegkljan** [fleaflet/flutter_map#1153]
There is a callback when the map position changes, but I didn't notice any such thing for map rotation. Is there any way to hook a callback on map rotation? If there is none, I think it would be nice to have. I wanted to show an indicator whether the map is rotated or not, but I don't have a way to detect that a rotation took place.

**Comment by JaffaKetchup** [comment]
I think map position always changes when rotation changes, but I'm not 100% sure. You can also use the `MapController`'s stream (I forget what it's called now) to listen for all changes.

**Comment by JaffaKetchup** [comment]
Hi @zegkljan,
Do you still require support? Happy to help!

**Comment by zegkljan** [comment]
@JaffaKetchup No need, I can manage with `MapController`'s stream. However, the rotation (when only a rotation takes place - the map rotates around its center) really does not trigger the position change callback. It often does trigger in practice (the user often changes the position as they don't remove their fingers at the same time and slide them a bit), but not always.

**Comment by JaffaKetchup** [comment]
Good to hear!
