### ISSUE TITLE
How to always center the marker on the polygon, regardless of zoom level 

### ISSUE THREAD

**Issue by raycastsant** [fleaflet/flutter_map#1160]
Hi, I'm using **flutter_maps** to display the polygons of a building plan.
Each polygon is a department. I have added a layer of polygons and 1 layer of **Markers** with the names of the polygons.
The problem is that I need the department names to **always be centered**. In the initial zoom each name looks good, like in this image:
![1](https://user-images.githubusercontent.com/54291127/153949560-4e7a9479-bf27-451c-9a91-93ad883bf2bb.JPG)

Since I have calculated the center of each polygon and that is the position that I have assigned to the corresponding Marker. But **when zooming in/out**, the name scrolls:
![2](https://user-images.githubusercontent.com/54291127/153949609-77b3cb62-322a-4ba7-b1e9-b9719cdd5515.JPG)
![3](https://user-images.githubusercontent.com/54291127/153949630-1477b979-364c-467c-85b7-b71cb78c5c69.JPG)

Is there any way to recalculate the position of the marker so that it is always in the center?

Thanks in advance for any assistance!

**Comment by JaffaKetchup** [comment]
Hi there,
Thanks for your question. I'm a bit busy at the moment, so I can't help you much, but #880 may be of interest to you in the future. I hope to merge this soon!
If you still want help, I can try, but probably not for a couple of days.
Thanks.

**Comment by raycastsant** [comment]
Hello, thanks for the answer. Good idea that you implemented. Now I´m trying to adapt it to my project through **MapPlugin**. 
I also need to make some changes for it to become **NullSafety**. I'll let you know later if I made any progress.
Thanks!
