### ISSUE TITLE
[FEATURE]  Google Map platform native as layerwidget

### ISSUE THREAD

**Issue by pmg1991** [fleaflet/flutter_map#1164]
**Describe The Problem**
 I'm always frustrated when have to write new layer for google_maps_flutter .

**Describe Your Solution**
To use Google map sdk on Android on IOS as those maps are free on platforms and map contains more information than any other maps. Instead of TileLayerWidget we could have GoogleLayerWidget, GoogleLayerWidget will use native platform maps  for example google_maps_flutter package. It is very difficult to add new layers to google_maps_flutter package. 

**Alternatives/Workarounds**
using google_maps_flutter but adding/writing new plugins is not easy. 
---

**Additional Information**
Google maps sdk is free on Android.

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

 - [ ] All/any
 - [x] Android
 - [x] iOS
 - [ ] Web
 - [ ] Windows
 - [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
Hi there @pmg1991,
Please include some more details so we can try to help you better. Consider making use of the template instead of just getting rid of it.
Thanks!

**Comment by pmg1991** [comment]
@JaffaKetchup updated. 
Thanks,

**Comment by JaffaKetchup** [comment]
@pmg1991 Hello,
Thanks for this feature request, however we are unlikely to be adding features to this package at the moment. This is due to a backlog of bug reports, which must take priority.
If you feel you can write it yourself, consider creating a plugin.
I hope you understand this, but please feel free to engage more with the 'flutter_map' project - it's always nice to see activity!
Thanks once again.

**Comment by ibrierley** [comment]
Just wondering, what type of layers are you wanting to add that you can't in google_maps_flutter...just may give some ideas, as I haven't used it in the last few years (and then not much at all). I'm interested in what different people find good/bad in google_maps_flutter, mapbox etc, and the pros/cons.
