### ISSUE TITLE
[BUG] When I run the example project I get Neither user 10353 nor current process has android.permission.ACCESS_FINE_LOCATION.

### ISSUE THREAD

**Issue by basvdijk** [fleaflet/flutter_map#1166]
**Describe The Bug**
`java.lang.SecurityException: Neither user 10353 nor current process has android.permission.ACCESS_FINE_LOCATION.`

Is thrown when opening the live location page in the example app

**Expected Behavior**
See my location on the map

**Screenshots & Recordings**
```
E/AndroidRuntime(23425): FATAL EXCEPTION: main
E/AndroidRuntime(23425): Process: me.jpryan.flutter_map_example, PID: 23425
E/AndroidRuntime(23425): java.lang.SecurityException: Neither user 10353 nor current process has android.permission.ACCESS_FINE_LOCATION.
```

**Additional Information**
Add any other context about the problem here, or remove this section.

---

**Doctors Report**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.3 20G415 darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.0-insider)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**To Reproduce**
- Checkout the repo
- Open the example folder in Android studio
- Fix all the compiler warnings like targetSDK to 31, minSDK tot 23
- Run the app and go to the realtime location page.
- There is no permission prompt and you'll get a `E/AndroidRuntime(23425): java.lang.SecurityException: Neither user 10353 nor current process has android.permission.ACCESS_FINE_LOCATION.` error

---

**Severity**
Select two (one from fatality, one from frequency). This will help us to label the issue quicker and decide what needs attention first.
 - [X] Non-fatal
 - [ ] Fatal
 - [ ] Uncommon
 - [x] Common

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.
 - [X] Android
 - [ ] iOS
 - [ ] Web
 - [ ] Windows
 - [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
Hi there.
Thanks for the report. Will try to verify tomorrow.

**Comment by ibrierley** [comment]
Ops, updated previous reply...

**Comment by ibrierley** [comment]
Actually, that's probably one that should be included in flutter_maps example/android/app/src/main if it fixes it...(can't test right now)

**Comment by basvdijk** [comment]
Hi, yes I have `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> ` in all the manifests since there are 3 of them. It looks like a race condition is going on. So the map already loads while the permission is not yet given.

**Comment by ibrierley** [comment]
I think you're right, it works fine on my old tablet, but get that error on phone (not sure if thats speed or version related).

This SO thread seems to have a bit of info on it... https://stackoverflow.com/questions/26312733/neither-user-nor-current-process-has-android-permission-access-coarse-location so may be dependant on Android versions...looking through Git, I don't think the flutter_map AndroidManifest.xml has it in there actually (or am I going mad :D). 

Has anyone else come across this recently in their code ?

**Comment by basvdijk** [comment]
Maybe it has something to do with Android 12?

**Comment by JaffaKetchup** [comment]
There have been some breaking changes to permissions in Android 12, so that could be the issue.

**Comment by ibrierley** [comment]
I suppose the question for this one, is if the problem is related to flutter_map or if its the location package ? Not quite sure we want to get bogged down with errors from a different package that isn't a requirement for flutter_map ?

**Comment by c0deslinger** [comment]
I encounter same problem, and now already fixed by moving these code

```
 await _locationService.changeSettings(
            accuracy: LocationAccuracy.high,
            interval: 1000,
          );
```
          
 to 
          
```    
if (serviceEnabled) {
        final permission = await _locationService.requestPermission();
        _permission = permission == PermissionStatus.granted;

       if (_permission) {
       // move here
       await _locationService.changeSettings(
            accuracy: LocationAccuracy.high,
            interval: 1000,
          );
      }
}
```

**Comment by opsquid** [comment]
> I encounter same problem, and now already fixed by moving these code
> 
> ```
>  await _locationService.changeSettings(
>             accuracy: LocationAccuracy.high,
>             interval: 1000,
>           );
> ```
> 
> to
> 
> ```
> if (serviceEnabled) {
>         final permission = await _locationService.requestPermission();
>         _permission = permission == PermissionStatus.granted;
> 
>        if (_permission) {
>        // move here
>        await _locationService.changeSettings(
>             accuracy: LocationAccuracy.high,
>             interval: 1000,
>           );
>       }
> }
> ```

Thank you. This solution works for me.
