### ISSUE TITLE
[BUG] Error is thrown when adding marker then centering map

### ISSUE THREAD

**Issue by mbasa** [fleaflet/flutter_map#1171]
I get the error below whenever I add a marker on a given position then center the map to the marker position. This error appears with versions `0.13.0` and `0.14.0`, but not in `0.12.0`. 

The problem seems to be here: (package:flutter_map/src/layer/marker_layer.dart:217:21)

The source code of my project can be found here: https://github.com/mbasa/pgrServerDemo.

Thanks and regards,

Mario. 

```
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building StreamBuilder<int?>(dirty, state: _StreamBuilderBaseState<int?, AsyncSnapshot<int?>>#2220d):
RangeError (index): Invalid value: Only valid value is 0: 1

The relevant error-causing widget was: 
  FlutterMap FlutterMap:file:///Users/mbasa/Development/AndroidStudioProjects/pgrServerDemo/lib/main.dart:432:17
When the exception was thrown, this was the stack: 
#0      List._setIndexed (dart:core-patch/growable_array.dart:269:49)
#1      List.[]= (dart:core-patch/growable_array.dart:264:5)
#2      _MarkerLayerState.build.<anonymous closure> (package:flutter_map/src/layer/marker_layer.dart:217:21)
#3      StreamBuilder.build (package:flutter/src/widgets/async.dart:442:81)
#4      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#18     _invoke (dart:ui/hooks.dart:150:10)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#20     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)

```

**Comment by ibrierley** [comment]
There's a pull request at https://github.com/fleaflet/flutter_map/pull/1147 I did for a similar issue that may be related. Would you be able to test this at all, to see if it fixes your problem ? If so, I'll try and get it merged quicker.

**Comment by mbasa** [comment]
Unfortunately, the error still persists. I did this: 

```
flutter_map:
    git:
      url: https://github.com/ibrierley/flutter_map
      branch: markerlayer_crash_fix
```      

but still get this: 

<img width="912" alt="Screen Shot 2022-02-23 at 16 57 35" src="https://user-images.githubusercontent.com/462884/155280507-7102ce66-d1d8-4bf2-b87c-850e5ae997f8.png">

**Comment by ibrierley** [comment]
Yes, sorry I didn't spot your earlier comment, I don't think my fix is related to this issue.

I've tried running the app, how does one recreate the problem (does it need to be connected to the server?), as it all runs fine, but I'm probably doing something you're not adding the marker or whatever.

Can you try and create smaller test case for people to run.

**Comment by ibrierley** [comment]
oh I get the pgServer is unavailable...so can't really test properly here. See if you can create a test that can run standalone without any connections etc for people to test.

**Comment by ibrierley** [comment]
Actually, it could still be related....if you can, in flutter_maps marker_layer, around line 218, print out widget.markerLayerOptions.markers.length and _pxCache.length...are they different ?

**Comment by mbasa** [comment]
Will test if the values are different. 

But if you are running my app, once the map appears just click anywhere since that will add a marker on the clicked position and then center the map to that position.  Thanks.

**Comment by ibrierley** [comment]
Hi, I did, the centering doesn't work as it pops up an error about the pgrServer not being reachable, so I don't think any tests I've done are valid.

**Comment by mbasa** [comment]
Can you please click on the icon on the AppBar and change the url to: 

http://cld06.georepublic.net/pgrServer

then press the Zoom Bnd floating button in the map to recenter. 

Thanks thanks.

**Comment by ibrierley** [comment]
Actually, your pubspec is using 0.11.0 which may be why it doesn't for me....

**Comment by ibrierley** [comment]
Ok, I think I managed to reproduce it, changing flutter_map to 0.14 in pubspec, dio: any, latlong2: ^0.8.1

Then it crashes when adding/recentering, but it doesnt crash if I use my PR 

```
flutter_map:
    git:
      url: git://github.com/ibrierley/flutter_map
      ref: markerlayer_crash_fix
```

Make sure you do a new pub get etc after changing that...see if it helps.

**Comment by ibrierley** [comment]
Possibly make sure you use ref: and not branch: in the pubspec as above, I'm not sure if there's any difference or what.

**Comment by tantzygames** [comment]
I am also encountering this after upgrading from 0.12.0 to 0.14.0

I'll do a pull request when I get a chance. Until then in the file lib/src/layers/marker_layer.dart replace the line at 217 with:
```
if (_pxCache.length > i) {
    _pxCache[i] = pxPoint;
  }
  else {
    _pxCache = generatePxCache();
  }
```

**Comment by JaffaKetchup** [comment]
@tantzygames, I think your suggestion already appears in @ibrierley's #1147?

**Comment by tantzygames** [comment]
I see, so it does. Thanks for that

**Comment by mbasa** [comment]
@ibrierley apologies for not replying much sooner, but your branch referenced as: 

```
flutter_map:
      git:
        url: https://github.com/ibrierley/flutter_map
        ref: markerlayer_crash_fix
```

does fix the problem. I have been testing for over an hour now and have yet to experience a crash like before. 

**Thanks**.

**Comment by ibrierley** [comment]
No problem, this fix has been merged now.

**Comment by ibrierley** [comment]
I'm going to close this, as I'm assuming the PR sorts this on the whole (at least prevents crashing and one can turn off caching). Feel free to reopen if still a problem.
