### ISSUE TITLE
[GENERAL] ... Polygon operations libary

### ISSUE THREAD

**Issue by mohammedX6** [fleaflet/flutter_map#1173]
I have ported a very useful library that is capable of doing boolean operations on polygons (union, intersection, difference, xor),
if you want to put it into the readme so it can reach out to more people.
More info: https://github.com/mohammedX6/poly_bool_dart

**Comment by mohammedX6** [comment]
Yes sure, I have added it now

**Comment by JaffaKetchup** [comment]
@mohammedX6 That's great. I'd be happy to add it to the new documentation, but it would be good if you could publish it to pub.dev to make it easier to depend on? Let me know.

**Comment by mohammedX6** [comment]
@JaffaKetchup I have already publish it 
https://pub.dev/packages/poly_bool_dart

**Comment by JaffaKetchup** [comment]
Great, will see what I can do.

**Comment by JaffaKetchup** [comment]
I have added it to the new documentation, however the deployment chain seems to be broken, so it's not visible right now. It's usually at https://flutter-map.vercel.app/plugins/list. Thanks for this plugin!
