### ISSUE TITLE
Name in the map have no animation while zooming

### ISSUE THREAD

**Issue by carlodenardin** [fleaflet/flutter_map#1175]
**Describe The Bug**
When I zoom in my map the name of the city, for example, have no animations. They change only when the zoom is over. I had this problem on the openstreetmap server but also on my own private tile server. So I think that I'm missing some options or we need to improve this.

**Expected Behavior**
In my mind, like others map, I expect that the name have an animation.

**Screenshots & Recordings**
https://imgur.com/a/kl3LCKB

---

**To Reproduce**
I've just use the plugin with the OpenStreetMap server.
---

**Severity**
Select two (one from fatality, one from frequency). This will help us to label the issue quicker and decide what needs attention first.
 - [x] Non-fatal
 - [ ] Fatal
 - [ ] Uncommon
 - [ ] Common

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.
 - [ ] Android
 - [x] iOS
 - [ ] Web
 - [ ] Windows
 - [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
As far as I understand, you're saying POIs don't animate between zooms.

If you're talking about the animation as seen on openstreetmap.org, they just apply a slight animate between tiles when they load in.
At the moment, we are unlikely to add this in, as there is a backlog of higher priority issues, but it may appear in the future.

However, if you are talking about more advanced animations, like on Google Maps, this is impossible for static raster tiles and way beyond the scope of this library (at the moment) to support more advanced maps.

Thanks for your report!

**Comment by carlodenardin** [comment]
This answer serves to be more clearer since I did not post an example of the solved problem.

I have a tile server in which if I open it from a browser I have an animation for the city names while zooming. Instead when I'm using the flutter map package the city names change according to the zoom without any animations.

This is the animation of the city names that I obtain from my tile server on a web page:
[Example](https://imgur.com/qYglfD0)

**Comment by JaffaKetchup** [comment]
Can I ask what library or SDK you are using on your website? Many thanks.

**Comment by carlodenardin** [comment]
Tileserver-gl from the OpenMapTiles.

**Comment by ibrierley** [comment]
What you're looking at are vector tiles, not raster tiles. By default flutter_map doesn't support it, but you may have luck with a Flutter_map Vector tile plugin like [ ](https://github.com/greensopinion/flutter-vector-map-tiles), otherwise you may need to look at something like mapbox-gl for flutter

**Comment by ibrierley** [comment]
Sorry, that url didn't come though, see if this works! https://github.com/greensopinion/flutter-vector-map-tiles

**Comment by ibrierley** [comment]
I'm going to close this, as its really not a raster tile issue, but happy for anyone to reopen if they think its still relevant (and I can see the issue raised on David vector plugin).
