### ISSUE TITLE
I'm trying to use your library, however, I'm getting the following error:

### ISSUE THREAD

**Issue by AlysonTrizotto** [fleaflet/flutter_map#1178]
Hello how are you?
I'm trying to use your library, however, I'm getting the following error:
Because find_favorites depends on flutter_osrm any which doesn't exist (could not find package flutter_osrm at https://pub.dartlang.org), version solving failed.
pub finished with exit code 65
exit code 65

Did the library lose support?

**Comment by JaffaKetchup** [comment]
I own flutter_osrm. At the moment it, is sitting on the backburners, not to be used for any serious projects.
I plan to greatly expand it in the future, as it should be quite a high demand library.

**Comment by AlysonTrizotto** [comment]
So I'm working on a project for which it requires navigation. I thought about using the library because of the ease I saw in some tutorials. However, when I do the import 'package:flutter_osrm/flutter_osrm.dart'; dart returns the error. As it is stopped, I believe it will be better for me to use the orm api, right?!

**Comment by AlysonTrizotto** [comment]
I had even seen this one: https://github.com/liodali/OSM-Routing-Client-Dart
however, from what I could observe it is still under construction. And I haven't found a way to use it. it returns me errors

**Comment by JaffaKetchup** [comment]
For now, I'd use OSRM directly. Maybe in the future my library will be released, it will just take a while.
As this is unrelated to flutter_map (as far as I can tell), I will close this now. Many thanks!

**Comment by AlysonTrizotto** [comment]
Yes, that's what I'm doing. Thank you very much for your attention! Great day!
