### ISSUE TITLE
 Map update for polyline rendering

### ISSUE THREAD

**Issue by AlysonTrizotto** [fleaflet/flutter_map#1179]
Hello, I'm having trouble finding a way to display the route obtained through a library on the map. I already decoded and got the coordinate points. However, when I loop inside a polyline list it doesn't update, it doesn't show the drawn line on the map. However, when I leave it pre-defined it appears normal... Which is to say, by clicking on the button it doesn't show it to me... Can anyone help me? I didn't find any material online or in the questions that are already here on github...

```

//Global

`
  late List<LatLng> polyPoints = [];
  late List<Polyline> polyLines = [];`


//Map
` MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Navegação'),
          backgroundColor: Color(0xFF101427),
        ),
        body: Center(
          child: Stack(children: [
            FlutterMap(
                mapController: mapController,
                options: MapOptions(
                    maxZoom: 18,
                    minZoom: 4,
                    center: currentCenter,
                    zoom: zoomAtual,
                    plugins: []),
                layers: [
                  TileLayerOptions(
                      urlTemplate:
                          "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                      //   "https://api.openrouteservice.org/v2/directions/driving-car?api_key=${chave}&start=${lat_init},${lng_init}&end=${lat_final},${lng_final}",
                      subdomains: ['a', 'b', 'c']),
                  PolylineLayerOptions(
                    polylines: [for (int i = 0; i < polyLines.length; i++) polyLines[i]],
                    
                    ),
                  MarkerLayerOptions(markers: [
                    for (int i = 0; i < markersInit.length; i++) markersInit[i]
                  ]),
                  MarkerLayerOptions(markers: [
                    for (int i = 0; i < markersFinal.length; i++)
                      markersFinal[i]
                  ]),
                  MarkerLayerOptions(markers: [
                    for (int i = 0; i < markersTracker.length; i++)
                      markersTracker[i],
                  ]),
                ]),`



//Coleta de coordenadas e decodificação, criação de List<Polyline>

`
  Future<void> routeHelper() async {
    polyPoints.clear();
    double latPoint = 0.0;
    double longPoint = 0.0;

    List<LngLat> waypoints = [
      LngLat(lat: latLng.latitude, lng: latLng.longitude),
      LngLat(lat: currentCenter.latitude, lng: currentCenter.longitude),
    ];
    final manager = OSRMManager();
    final road = await manager.getTrip(
      waypoints: waypoints,
      roundTrip: true,
      destination: DestinationGeoPointOption.last,
      source: SourceGeoPointOption.first,
      geometry: Geometries.polyline,
      steps: true,
      languageCode: "en",
    );

    List resultado = decodePolyline(road.polylineEncoded.toString());
    
    for (int x = 0; x < resultado.length; x++) {
      List passagem = resultado[x];
      if (passagem.length > 0) {
        latPoint = passagem[0];
        longPoint = passagem[1];

        polyPoints.add(LatLng(latPoint, longPoint));
        polyLines.add(Polyline(
          points: polyPoints,
          strokeWidth: 4.0,
          color: Colors.amber,
        ));
      }
      setState(() {});
    }
    print(polyPoints);
  }
`

```

full code 
[https://github.com/AlysonTrizotto/LocalizaCliente/blob/main/lib/componentes/rota.dart](url)

**Comment by ibrierley** [comment]
It's difficult to tell, as in your code you link, you don't have a setState, but you do in your code referenced here...
I'm also not sure why you don't just do PolylineLayerOptions( polylines: polyLines ), rather than looping. I doubt that's the problem, but you could try doing that and double checking your setState is still there, and print out the polyLine list in your build, just to make sure it is what you think it is and updating when you think.

**Comment by AlysonTrizotto** [comment]
So, now I managed to make the line appear, however, it only adds when it already has a pre-established point. Then he adds one more point. I don't understand why he doesn't add more than one point, since I'm telling him to add them all...


`
  Future<void> routeHelper() async {
    double latPoint = 0.0;
    double longPoint = 0.0;

    List<LngLat> waypoints = [
      LngLat(lat: latLng.latitude, lng: latLng.longitude),
      LngLat(lat: currentCenter.latitude, lng: currentCenter.longitude),
    ];
    final manager = OSRMManager();
    final road = await manager.getTrip(
      waypoints: waypoints,
      roundTrip: true,
      destination: DestinationGeoPointOption.last,
      source: SourceGeoPointOption.first,
      geometry: Geometries.polyline,
      steps: true,
      languageCode: "en",
    );

    List resultado = decodePolyline(road.polylineEncoded.toString());
    await Future.delayed(Duration(seconds: 3));
    for (int x = 0; x < resultado.length; x++) {
      List passagem = resultado[x];
      for (int i = 0; i < passagem.length; i++) {
        latPoint = passagem[0];
        longPoint = passagem[1];
        points.add(LatLng(latPoint, longPoint));
      }
    }
    setState(() {});
    print(points);
    print('FIm Future');
  }`

`Positioned(
              bottom: 130.0,
              left: 20.0,
              child: FloatingActionButton(
                  heroTag: 'rota',
                  elevation: 50,
                  child: Text(
                    'IR',
                    style: TextStyle(fontSize: 25),
                  ),
                  onPressed: () {
                    setState(() {
                      points.clear();
                      print(points);
                      routeHelper();
                      print(points);
                    });
                  }),
            ),`


`PolylineLayerOptions(
                    polylines: [
                      Polyline(
                          points: points,
                          strokeWidth: 4.0,
                          color: Colors.purple),
                    ],
                  ),`


`points = <LatLng>[
      LatLng(51.5, -0.09),
      LatLng(53.3498, -6.2603),
      LatLng(48.8566, 2.3522),
    ];`


`late List<LatLng> points = [];`


full code
[https://github.com/AlysonTrizotto/LocalizaCliente/blob/main/lib/componentes/rota.dart](url)

**Comment by ibrierley** [comment]
You need to print out 'points' at the start of your build method. See if it is what you think. For example, this code doesn't quite look right...

```
for (int i = 0; i < passagem.length; i++) {
    latPoint = passagem[0];
    longPoint = passagem[1];
    points.add(LatLng(latPoint, longPoint));
  }
```

Normally it would be something like latPoint = passagem[i][0]; rather than latPoint = passagem[0]; (otherwise why are you looping, you never use 'i' ? But I don't really know what your original data is, so it may work, but a bit unnecessarily code wise.

**Comment by AlysonTrizotto** [comment]
So, the 'for' used that you pointed out I did to test, see if it would change anything. However, it didn't help... Now, when I use another "local" list to feed the global one it works. Only it doesn't add the polyline... It doesn't recognize it. Even though I use setState((){})

**Comment by ibrierley** [comment]
It's really difficult to follow with some phrasing i.e "it works, only it doesn't add the polyline"....so I guess it isn't working, or what isn't working etc...
So I think you need to add some debug and include here, so its clearer as we don't know what the data is. Maybe add a print statement in your build method, to output what is in the 'points' variable, and then add whether it displayed the line or not.

**Comment by AlysonTrizotto** [comment]
Sorry, it's cultural customs.

I managed to get him to add the points to the List<LatLng> points. However, it doesn't add the polylines. For some reason that I still don't know which one, it only adds the polyline when it has a pre-established point

**Comment by AlysonTrizotto** [comment]
I will collect the debug output.

**Comment by AlysonTrizotto** [comment]
This is output

`I/flutter (31741): [LatLng(latitude:51.5, longitude:-0.09), LatLng(latitude:53.3498, longitude:-6.2603), LatLng(latitude:48.8566, longitude:2.3522), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439)]
Reloaded 9 of 1022 libraries in 3.985ms.
I/flutter (31741): [LatLng(latitude:51.5, longitude:-0.09), LatLng(latitude:53.3498, longitude:-6.2603), LatLng(latitude:48.8566, longitude:2.3522), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439)]
I/flutter (31741): WAYPOINTS
I/flutter (31741): [-49.1645689,-25.5120383, -49.1645689,-25.5120383]
I/flutter (31741): [[-25.51185, -49.16439], [-25.51185, -49.16439]]
2
I/flutter (31741): [-25.51185, -49.16439]
I/flutter (31741): points
I/flutter (31741): [LatLng(latitude:51.5, longitude:-0.09), LatLng(latitude:53.3498, longitude:-6.2603), LatLng(latitude:48.8566, longitude:2.3522), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439)]
Reloaded 9 of 1022 libraries in 3.792ms.
Reloaded 0 libraries in 906ms.
I/flutter (31741): [LatLng(latitude:51.5, longitude:-0.09), LatLng(latitude:53.3498, longitude:-6.2603), LatLng(latitude:48.8566, longitude:2.3522), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439)]
I/flutter (31741): WAYPOINTS
I/flutter (31741): [-49.1645689,-25.5120383, -49.1645689,-25.5120383]
I/flutter (31741): [[-25.51185, -49.16439], [-25.51185, -49.16439]]
2
I/flutter (31741): [-25.51185, -49.16439]
I/flutter (31741): points
I/flutter (31741): [LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439)]
Reloaded 9 of 1022 libraries in 3.733ms.
I/flutter (31741): [LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439)]
I/flutter (31741): WAYPOINTS
I/flutter (31741): [-49.1645689,-25.5120383, -49.1645689,-25.5120383]
I/flutter (31741): [[-25.51185, -49.16439], [-25.51185, -49.16439], [-25.51185, -49.16439]]
I/flutter (31741): [-25.51185, -49.16439]
I/chatty  (31741): uid=10289(alysontrizotto.github.io.localiza_favoritos) 1.ui identical 1 line
I/flutter (31741): [-25.51185, -49.16439]
I/flutter (31741): points
I/flutter (31741): [LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439), LatLng(latitude:-25.51185, longitude:-49.16439)]
`

**Comment by AlysonTrizotto** [comment]
So I believe the source of the problem is the return from the library I'm using to create the route. It's only giving me 3 coordinates, and both 3 are the same. That is, the polyline created from them is just a point

**Comment by AlysonTrizotto** [comment]
I believe this is the source of the problem.
