### ISSUE TITLE
Markers not updated when map is moved with same zoom level

### ISSUE THREAD

**Issue by mbasa** [fleaflet/flutter_map#1180]
My app will delete all markers and then add a marker and center the map using the same zoom level on a user selected position every time a user will click on the map. 

What is happening now is that map is centered, but the previous marker which should have been deleted is still displayed, while the newly added marker isn't displayed. But when the zoom level is changed, the markers are correctly updated, with the marker that should be deleted is not displayed and the newly added marker is shown on the correct position. 

I am using @ibrierley 's markerlayer_crash_fix branch.

**Comment by ibrierley** [comment]
Try setting usePxCache = false on your MarkerLayerOptions.

**Comment by ibrierley** [comment]
Btw the crash_fix should be merged already now, so shouldn't need to use that.

Alternatively if you want to use the cache as performance then drops too much, you somehow would need to make the marker layers didUpdateWidget get called, which would force a cache reload. Not quite sure how you would do that though (it would prob depend on your other code)

**Comment by mbasa** [comment]
Hi, I just tried the 
```
          MarkerLayerOptions(
                      markers: _markers,
                      usePxCache: true,
          ),
```

and it doesn't seem to fix the problem. Should I be using the flutter_map's `master` branch now? Thanks.

**Comment by ibrierley** [comment]
Yes, you can try the master branch, and set usePxCache to false, not true.

**Comment by mbasa** [comment]
Oh, sorry. I just used `master` and set usePxCache to **false**. Works fine now. Will close this issue. 

Thanks, thanks.
