### ISSUE TITLE
using a local WMS generated with qgis server

### ISSUE THREAD

**Issue by seiif1** [fleaflet/flutter_map#1184]
**What do you need support with?**
i created a map using qgis and i publidshed it using qgis server
and in my browser it works fine ,i was wondering if i can use it directly from my local server without the need to host it .
![Screenshot_20220311_141032](https://user-images.githubusercontent.com/62269578/157872887-1adbe1c2-fdfa-42a3-b461-3508794544c7.png)
![Screenshot_20220311_141053](https://user-images.githubusercontent.com/62269578/157872899-bc0de144-2324-483e-a06a-a066fcdae9a4.png)
when i try to use this link in flutter map i get this error
`I/flutter ( 5624): SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = myhost, port = 40804
`

![Screenshot_20220311_142009](https://user-images.githubusercontent.com/62269578/157874131-09e613ff-2dc4-4309-9300-93f8dfdd7837.png)

**Comment by ibrierley** [comment]
What exactly is "your local server", what is the client and what is the server ? I assume baseUrl must be something that exists you can query, rather than http://myhost/cgi-bin etc.

**Comment by seiif1** [comment]
my local server is 127.0.0.1:80 i am using apashe2 in kubuntu.
i am sorry if i didn't provide the necessary informations .

**Comment by ibrierley** [comment]
And what is trying to access it (and where is it) ? Something on the same machine ? If not, it needs an internet address/name, rather than 127.0.0.1

**Comment by seiif1** [comment]
yes it in my root directory /etc/apashe2/cgi-bin

**Comment by ibrierley** [comment]
I think you are misunderstanding what I'm asking maybe. Are you trying to draw the map on your mobile or a desktop. If it's on a desktop is it on the same physical machine as the server ? If its on the same physical machine as the server, is Apache running ? (go to http://127.0.0.1:80 in your browser and see if it displays any normal apache basic page or something)

**Comment by seiif1** [comment]
the map is in my desktop and i want to show it in my android emulator


![Screenshot_20220311_151323](https://user-images.githubusercontent.com/62269578/157884251-fc8578af-2540-4b2c-aeba-80e8f1d7ee3e.png)

**Comment by ibrierley** [comment]
I think you may need to try http://10.0.2.2:<hostport> then...see  https://stackoverflow.com/questions/6760585/accessing-localhostport-from-android-emulator see also some of the other answers on there for more details and config options.

**Comment by seiif1** [comment]
i tried that approach but i got an other error

![Screenshot_20220311_151724](https://user-images.githubusercontent.com/62269578/157884918-db878e46-9204-4675-a840-a5939cdc60b7.png)

**Comment by ibrierley** [comment]
That looks like the network side is all working, but Apache isn't serving up the images in that location. So you need to get Apache serving up images before anything else will work.

**Comment by seiif1** [comment]
how can i do that if i may ask  ??

**Comment by seiif1** [comment]
i found this but the baseurl property needs a string 
https://stackoverflow.com/questions/68594142/http-request-failed-statuscode-404-in-flutter-when-load-from-local-image

**Comment by seiif1** [comment]
ok thanks for helping me and have a great day
i will continue my digging (struggle)

**Comment by ibrierley** [comment]
Before even bothering with Flutter...load the URL it's trying into your browser (the one in blue at the bottom of the screen with bbox type parameters) and see if it returns anything.

**Comment by seiif1** [comment]
the bbox is different but when i add it in otherparameters it just writes it 2 times
it's working pperfect in my browser


![Screenshot_20220311_155401](https://user-images.githubusercontent.com/62269578/157891501-36a287b3-8983-4ff2-9211-b967a248c5b0.png)

**Comment by ibrierley** [comment]
Only other thing I can think of, is to check your Apache logs, and compare whats in the log when you access in Flutter vs when you access in Browser. See if you can spot any difference as to why its serving up a 404.

**Comment by seiif1** [comment]
nothing is showing in apashe error log

**Comment by seiif1** [comment]
![Screenshot_20220311_161328](https://user-images.githubusercontent.com/62269578/157894920-38709d78-bb43-4512-9046-0956d82a4ce8.png)

two bbox

**Comment by ibrierley** [comment]
I'm pondering starting a discord server for flutter_map could reduce some clutter for others who get notifications... https://discord.gg/AAsH3D2t   see if others think its a good idea.

**Comment by JaffaKetchup** [comment]
@seiif1 Please [join the Discord server](https://discord.gg/egEGeByf4q) and start a thread for this discussion if you want to continue further. Thanks for using 'flutter_map'!

**Comment by seiif1** [comment]
just for future reference and to help people that need to do this.
first of all you need to create a suitable environmment for you qgis server by :
`    sudo mkdir /var/log/qgis/      //needs to be created
    sudo chown www-data:www-data /var/log/qgis/         //give permission
    sudo mkdir /home/qgis/qgisserverdb/      //needs to be created
    sudo chown www-data:www-data /home/qgis/qgisserverdb/
    a2enmod fcgid
    a2ensite "your site"  // remove " " and put your site's .conf title  `
then make sure your phone and pc are in the same connection and pair and connect your phone through adb for wireless debugging.
then you have to change the ServerName in the .conf file to match this pc's own ip that i got from ipconfig 'wlp2s0:' in 'inet'.
then restart apache2 with cmd 'service apache2 restart '.
then put your url in flutter map and it should work
e.g: `FlutterMap(
             options: new MapOptions(
               zoom: 0.0,
               interactiveFlags: InteractiveFlag.pinchZoom | InteractiveFlag.drag,
             ),
            layers: [
           TileLayerOptions(
                urlTemplate:
                     'http://192.168.1.152/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMTS&REQUEST=GetTile&map=/home/qgis/projects/world.qgs&LAYER=yert&FORMAT=image/png&TILEMATRIXSET=EPSG:4326&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&.png',
                  subdomains: ['a', 'b', 'c'],
                )
                 //subdomains: ['a', 'b', 'c'],
               ],
            )`
