### ISSUE TITLE
Custom Map （WMS） cannot be displayed

### ISSUE THREAD

**Issue by SanSanNiang** [fleaflet/flutter_map#1189]
I need display a custom map by flutter_map.  
The map is displayed normally in HTML, but, cannot be displayed in flutter，why？
###################################################################################################
HTML code:
var untiled = new ol.layer.Image({
        source: new ol.source.ImageWMS({
          ratio: 1,
          url: 'http://XXXXXX/geoserver/dandongport/wms',
          params: {'FORMAT': format,
                   'VERSION': '1.1.1',  
                "LAYERS": 'dandongport:dandongport_tile',
                "exceptions": 'application/vnd.ogc.se_inimage',
          }
        })
      });
      var tiled = new ol.layer.Tile({
        visible: false,
        source: new ol.source.TileWMS({
          url: 'http://XXXXXX/geoserver/dandongport/wms',
          params: {'FORMAT': format, 
                   'VERSION': '1.1.1',
                   tiled: true,
                "LAYERS": 'dandongport:dandongport_tile',
                "exceptions": 'application/vnd.ogc.se_inimage',
             tilesOrigin: 13814005.499810196 + "," + 4828679.950831153
          }
        })
      });
###################################################################################################
Flutter Code：
 FlutterMap(
                      options: MapOptions(
                        zoom: 0
                      ),
                      layers: [
                        TileLayerOptions(

                          wmsOptions: WMSTileLayerOptions(
                              baseUrl:
                                  'http://XXXXXX/geoserver/dandongport/wms?',
                              layers: ['dandongport:dandongport_tile'],
                              version: '1.1.1',
                              otherParameters: {
                                "exceptions": 'application/vnd.ogc.se_inimage'
                              }
                              ),
                        )
                      ],
                    )
###################################################################################################

Please， help me~

**Comment by ibrierley** [comment]
Do you get any errors, or what actually happens ?

**Comment by SanSanNiang** [comment]
There’re no errors.The display in Flutter is shown below
![微信图片_20220317143715](https://user-images.githubusercontent.com/58019634/158751216-52a29314-f03e-4785-9d54-c081f6f51b7d.png)

**Comment by SanSanNiang** [comment]
> Can you change the server URL, but nothing else, and see if that works? Thanks.

The full server URL is："http://124.93.251.50:8085/geoserver/dandongport/wms?"

when changed to 
        baseUrl: 'https://{s}.s2maps-tiles.eu/wms/?',
        layers: ['s2cloudless-2018_3857'],
        subdomains: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
it works！

**Comment by JaffaKetchup** [comment]
Ok then. Now that I have the full URL, it loads an error ERR_SSL_PROTOCOL_ERROR. That would indicate the server isn't working for some reason unrelated to flutter_map. That also would explain why the other URL works.

Is there anything 'special' or different about the server, or the way you set it up with Leaflet?

**Comment by JaffaKetchup** [comment]
Just noticed your `zoom` argument in your options is 0. Can you change this to 1 or 10 and see if that makes a difference?

**Comment by SanSanNiang** [comment]
> Just noticed your `zoom` argument in your options is 0. Can you change this to 1 or 10 and see if that makes a difference?

I tried to change  the zoom，but nothing changed.

**Comment by SanSanNiang** [comment]
> Ok then. Now that I have the full URL, it loads an error ERR_SSL_PROTOCOL_ERROR. That would indicate the server isn't working for some reason unrelated to flutter_map. That also would explain why the other URL works.
> 
> Is there anything 'special' or different about the server, or the way you set it up with Leaflet?

I opened the map in PNG format from geoserver and got the url:  
http://124.93.251.50:8085/geoserver/dandongport/wms?service=WMS&version=1.1.0&request=GetMap&layers=dandongport%3Adandongport_tile&bbox=1.3814005499810196E7%2C4828679.950831153%2C1.3825623928109542E7%2C4845801.845167033&width=521&height=768&srs=EPSG%3A3857&format=image%2Fpng

but  in flutter ( zoom : 0) , break the getUrl method in tile_layer.dart ，and get the URL:
http://124.93.251.50:8085/geoserver/dandongport/wms?&service=WMS&request=GetMap&layers=dandongport%3Adandongport_tile&styles=&format=image%2Fpng&srs=EPSG%3A3857&version=1.1.1&transparent=true&exceptions=application%2Fvnd.ogc.se_inimage&width=256&height=256&bbox=-20037508.342789244,-20037508.34278071,20037508.342789244,20037508.34278071

**Comment by ibrierley** [comment]
I think its the bbox param that's the problem...

**Comment by SanSanNiang** [comment]
> 

how to change the bbox param?
and I haven't found where to call the getUrl method and how is the coords param obtained
![微信图片_20220317165055](https://user-images.githubusercontent.com/58019634/158772430-188bf41c-f380-4c24-9ce7-5fc7726386d8.png)

**Comment by ibrierley** [comment]
What happens if you provide a center to flutter_map eg 
center: LatLng(65.05166470332148, -19.171744826394896),

**Comment by SanSanNiang** [comment]
> What happens if you provide a center to flutter_map eg center: LatLng(65.05166470332148, -19.171744826394896),

I provided a center，but nothing changed.

**Comment by SanSanNiang** [comment]
> What happens if you provide a center to flutter_map eg center: LatLng(65.05166470332148, -19.171744826394896),

This is a very effective solution. Thank you.
