### ISSUE TITLE
How to set the display boundary

### ISSUE THREAD

**Issue by SanSanNiang** [fleaflet/flutter_map#1190]
How to set the display boundary ?
Only the set area is displayed, and beyond the boundary can not be dragged

**Comment by JaffaKetchup** [comment]
@SanSanNiang Hi there,
Sorry, I don't quite understand your request? Can you explain more information. Many thanks.

**Comment by SanSanNiang** [comment]
> @SanSanNiang Hi there, Sorry, I don't quite understand your request? Can you explain more information. Many thanks.

I tested a map, based on Epsg3857,which displays part of the map. 
Now, the map shows the exceeding part, and the exceeding part is gray. What should I do not display the exceeding part?
![Uploading image.png…]()

**Comment by JaffaKetchup** [comment]
Ok, related to #1103 perhaps?

**Comment by JaffaKetchup** [comment]
I can't help fully, as I've never dealt with it before, but you should be able to set bounds in `MapOptions`? Please try that or look at the issue linked above, and let me know if it works.

**Comment by SanSanNiang** [comment]
> I can't help fully, as I've never dealt with it before, but you should be able to set bounds in `MapOptions`? Please try that or look at the issue linked above, and let me know if it works.

With the sw and ne coordinates of the map as the boundary, although there are restrictions on dragging,  there are still excess parts displayed.
![微信图片_20220322161401](https://user-images.githubusercontent.com/58019634/159436605-fa2852c4-23a6-4532-a839-4380e1363fd2.png)
![微信图片_20220322161418](https://user-images.githubusercontent.com/58019634/159436630-7b216dd2-892b-4967-ae9b-b8cd0fe533d2.png)

**Comment by sam-parks** [comment]
I'm
![Screen Shot 2022-03-22 at 9 08 44 AM](https://user-images.githubusercontent.com/44235716/159489063-e6981ce1-f5c9-4cdc-8f2a-8038aca9f9bc.png)
 also experiencing this issue

**Comment by sam-parks** [comment]
@JaffaKetchup 

I did just start using the package so its version 0.14.0

```
FlutterMap(
                options: MapOptions(
                  zoom: 2,
                  maxZoom: 7,
                  minZoom: 2,
                  center: LatLng(15.96, 45.81),
                ),
                children: <Widget>[
                  TileLayerWidget(
                    options: TileLayerOptions(
                      urlTemplate:
                          'https://api.maptiler.com/maps/bright/{z}/{x}/{y}.png?key=FHzUbZwstZKBiAQE7D4V',
                    ),
                  ),
```

**Comment by SanSanNiang** [comment]
> FlutterMap(
>                 options: MapOptions(
>                   zoom: 2,
>                   maxZoom: 7,
>                   minZoom: 2,
>                   center: LatLng(15.96, 45.81),
>                 ),
>                 children: <Widget>[
>                   TileLayerWidget(
>                     options: TileLayerOptions(
>                       urlTemplate:
>                           'https://api.maptiler.com/maps/bright/{z}/{x}/{y}.png?key=FHzUbZwstZKBiAQE7D4V',
>                     ),
>                   ),

**Comment by SanSanNiang** [comment]
> Can you both please write a minimal reproducible example for me to test and experiment with? Many thanks.

the package version：0.11.0
   FlutterMap(
                          mapController: this._mapController,
                          options: MapOptions(
                            center: LatLng(39.813363,124.143537),
                            interactiveFlags: InteractiveFlag.all &
                                ~InteractiveFlag.rotate, // Disable map rotation
                            slideOnBoundaries: true,
                            swPanBoundary:LatLng(39.743098,124.093323),
                            nePanBoundary: LatLng(39.861238,124.197371),
                            minZoom: 12.0,
                            maxZoom: 14.0,
                            zoom: 13,
                         
                          ),
                          layers: [
                            TileLayerOptions(
                              maxZoom: 14.0,
                              wmsOptions: WMSTileLayerOptions(
                                  baseUrl:
                                      'http://124.93.251.50:8085/geoserver/dandongport/wms?',
                                  layers: ['dandongport:dandongport_tile'],
                                  version: '1.1.1',
                                  ),
                            ),
                          
                          ],
                        ),

> Can you both please write a minimal reproducible example for me to test and experiment with? Many thanks.


the package version：0.11.0
   FlutterMap(
                          mapController: this._mapController,
                          options: MapOptions(
                            center: LatLng(39.813363,124.143537),
                            interactiveFlags: InteractiveFlag.all &
                                ~InteractiveFlag.rotate, // Disable map rotation
                            slideOnBoundaries: true,
                            swPanBoundary:LatLng(39.743098,124.093323),
                            nePanBoundary: LatLng(39.861238,124.197371),
                            minZoom: 12.0,
                            maxZoom: 14.0,
                            zoom: 13,
                         
                          ),
                          layers: [
                            TileLayerOptions(
                              maxZoom: 14.0,
                              wmsOptions: WMSTileLayerOptions(
                                  baseUrl:
                                      'http://124.93.251.50:8085/geoserver/dandongport/wms?',
                                  layers: ['dandongport:dandongport_tile'],
                                  version: '1.1.1',
                                  ),
                            ),
                          
                          ],
                        ),

**Comment by SanSanNiang** [comment]
> Can you both please write a minimal reproducible example for me to test and experiment with? Many thanks.

the package version：0.11.0
   FlutterMap(
                          mapController: this._mapController,
                          options: MapOptions(
                            center: LatLng(39.813363,124.143537),
                            interactiveFlags: InteractiveFlag.all &
                                ~InteractiveFlag.rotate, // Disable map rotation
                            slideOnBoundaries: true,
                            swPanBoundary:LatLng(39.743098,124.093323),
                            nePanBoundary: LatLng(39.861238,124.197371),
                            minZoom: 12.0,
                            maxZoom: 14.0,
                            zoom: 13,
                         
                          ),
                          layers: [
                            TileLayerOptions(
                              maxZoom: 14.0,
                              wmsOptions: WMSTileLayerOptions(
                                  baseUrl:
                                      'http://124.93.251.50:8085/geoserver/dandongport/wms?',
                                  layers: ['dandongport:dandongport_tile'],
                                  version: '1.1.1',
                                  ),
                            ),
                          
                          ],
                        ),

**Comment by JaffaKetchup** [comment]
Please update to the latest version 0.14.0 if you can. If not use [advanced installation](https://docs.flutter.dev/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages) to use the latest commits from this package on branch 'master'. Support is limited for older versions, due to high maintenance pressures at the moment.

I'm not familiar with these options, but the `bounds` and `boundsOptions` parameters (in `MapOptions()`) might work better for you? Please try and get back to me.

**Comment by sam-parks** [comment]
@JaffaKetchup I tried messing around with `bounds` and `boundsOptions` but that only seems to change the bounds of the initial position. I can still scroll to the grey areas.

**Comment by JaffaKetchup** [comment]
In that case I will need to investigate further. Many thanks for your help!

**Comment by stx** [comment]
Same issue here using Mapbox tiles (not sure it matters though.)

Setting panBoundaries didn't seem to affect it - at least vertically.

**Comment by stx** [comment]
Created a $100 bounty for a nice and timely fix for this. [Source](https://app.bountysource.com/issues/106601553-how-to-set-the-display-boundary)

Looking for the map to be displayed perfectly by default with no out of bounds panning.

**Comment by stx** [comment]
This looks fixed by PR https://github.com/fleaflet/flutter_map/pull/1211. Thank you!
