### ISSUE TITLE
Adaptive Marker Size

### ISSUE THREAD

**Issue by furkan-celik** [fleaflet/flutter_map#1192]
Hi, I am using some markers from a dataset and having a bit of trouble right now with the sizing. The issue I believe is width and height of markers are defined inside the screen space and not in map space. This create the issue of if I zoom out, markers continue taking 30x30 pixels of the screen and ends up being really meaningless. Whereas in google maps, if I zoom out the icons continue take the same cm2 in the real world and keeps getting smaller on the user screen and disappear at some point.

I tried to use mapEventStream but I couldn't update marker sizes without a setState call and when I do that, it builds map entirely from ground up which resets the position and zoom etc. I also tried to implement some custom Markers but I am not sure whether map calls markers on events like zoom/move. 

If you can show me a way out of this I would be very happy. Maybe there is a callback that I miss or some way to trigger rebuilding markers. I wouldn't like to go down the path of rebuilding marker pool for every change but better than having a bunch of black patches when I zoom out (my marker icons are black and on zooms like 10, they almost cover all of the germany as a black patch).

**Comment by ibrierley** [comment]
Couple of thoughts. This sounds a bit like it may benefit from clustering markers, so you may want to look into that plugin. Regarding the markers themselves, I think you can set the width/height, so couldn't you adjust those as necessary ? Just a note, for me, markers on google always stay the same size (and you'd probably want that, as you need to be able to interact with them with your fingers, cursor etc), but maybe we are talking about different things there.

For a callback, I think you would be able to do that via a mapController callback ?

**Comment by furkan-celik** [comment]
I am changing marker's height and width values but I believe the app doesn't care about updates on those. And since they are passed as values, not reference I believe there is no way to update them without redrawing flutter_map or at least I couldn't see one.
I am using mapController callback and tried to manipulate state to adjust marker sizes but I couldn't reach there. I have found that it has mapEventStream but I cannot update icons from there without redrawing the screen. Redrawing the entire map widget creates infinite loop with  mapEventStream.

**Comment by furkan-celik** [comment]
clustering may solve the issue to some degree, I can try that at least better than current version. I believe the "illusion" gmaps has that it dynamicly draws markers as their importance. Which is I believe pretty hard even with cluster plugin. I am having a bit trouble understanding marker code so I don't know where I can enhance to achieve dynamic cluster pooling or survival algorithm

**Comment by ibrierley** [comment]
If you are getting some infinite loop, it sounds like there is a bug in your code. Redrawing the map should on the whole be pretty efficient, so it could be worth sharing the relevant code.

**Comment by furkan-celik** [comment]
what I done whas using 
`void updateIconSize(MapEvent newEvent) {
    setState(() {
      iconSize = newEvent.zoom >= 15.0 ? 30 : 30 * (mapController.zoom / 30.0);
      print(iconSize);
      currZoom = newEvent.zoom;
    });
  }`
and hook it up with mapController.mapEventStream.listen(updateIconSize). However, I believe that this causes updateIconSize triggering a new change and calling itself again and again. Removing `currZoom = newEvent.zoom;` causes no change in the map result. This version does not create infinite loop but the issue is when I release my fingers, map goes back to initial state of which zooming started. I tried to use mapController.move() to prevent not goint to initial state but that created infinite loop.

Clustering marker plugin is good but it seems like it is only a temporary solution for me. In the final product we can easily have around 5-10k markers which is impossible to manage without dynamic elimination or resizing. I also seen some concerns about performance of cluster plugin and all marker computations.

**Comment by ibrierley** [comment]
You shouldn't have a setState call from something like a map stream or in or related to a build method, as it should have already called setState previously iyswim.So your marker size should have already been decided and passed in the marker options (I assume via something like your mapcontroller zoom calculation you have...I'm a bit unclear why mapEvent zoom would be different to mapController.zoom and why you use both though...)

There are some caching performance improvements for makers, and there's an example in the examples directory using 5k markers.

**Comment by ibrierley** [comment]
Just wondering if you had managed to fix your loop ?

**Comment by furkan-celik** [comment]
Hi, yeah I managed to work it out at the end. But there were some other caveats and we decided to migrate project to the official mapbox plugin instead mostly due to budget plannıng. Thank you again though for your enormous helps.
