### ISSUE TITLE
Map is getting Grey on zoom

### ISSUE THREAD

**Issue by ch-muhammad-adil** [fleaflet/flutter_map#1193]
Hello All! Map is getting greyed for me even at 17 zoom level, I am mostly testing at iOS simulator and real device. I have applied many solutions [here](https://github.com/fleaflet/flutter_map/issues/1085) and [here](https://github.com/fleaflet/flutter_map/issues/670) but no luck. 

`flutter_map: ^0.14.0`

Here is my implementation
     
                       MapOptions? options = MapOptions(
                            center: position,
                            zoom: cameraZoom,
                            maxZoom: 17,
                            controller: mapController,
                            allowPanning: true,                       
                          );
                       
                       FlutterMap(
                                mapController: mapController,
                                options: options,
                                children: <Widget>[
                                  TileLayerWidget(
                                    options: TileLayerOptions(
                                      urlTemplate:
                                          'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
                                      subdomains: ['a', 'b', 'c'],
                                      fastReplace: true,
                                      retinaMode: true,
                                      maxNativeZoom: 17,
                                      maxZoom: 17,
                                      tileProvider: CachedTileProvider(),
                                      overrideTilesWhenUrlChanges: true,
                                    ),
                                  ),
                               )

Here is the video 
                               
https://user-images.githubusercontent.com/8264639/159454048-2bc4a5d4-eb6a-469c-b04e-7f836e27b820.mov

**Comment by ibrierley** [comment]
First thought...(I posted some bits on https://github.com/fleaflet/flutter_map/issues/670 but here is a better place, and I wasn't checking somethings correct, so this is more updated)...
We have 
```
maxZoom = 18.0,
and
maxZoom =
            wmsOptions == null && retinaMode && maxZoom > 0.0 && !zoomReverse
                ? maxZoom - 1.0
                : maxZoom,
```
in TileLayerOptions.

So I "think", maxZoom passed in will get totally ignored....unless we set this.maxZoom = 18.0 and scratch the wmsOptions code completely....

I note, if we remove that code and set this.maxZoom = 18.0 in the constructor, the grey tiles problem goes away, but obviously it's broken other stuff :).

Then we can use the MapOptions maxZoom ok as well which will keep the zoom from moving further if we want.

So I think is may just be a bug in the TileLayerOptions constructor....

**Comment by ibrierley** [comment]
Doh, actually, I think part of this issue is not so much the constructor, but that retinaMode is set to true and gets checked in the constructor...so as a temp workaround you could possibly disable that. But naturally that may not be ideal and needs a better solution.

**Comment by ibrierley** [comment]
There's a few places in tile_layer that maxZoom is used for checking...so I suspect in some places it needs thinking whether the original passed maxZoom should be used, or a modified maxZoom (maybe a sep method) that sees if retinaMode is true, and adjusts ?

**Comment by ch-muhammad-adil** [comment]
I think it should be straight forward and zoom level should be applied without any check? It should be developer's preference.

**Comment by ch-muhammad-adil** [comment]
I got it working finally for `FlutterMap` `options` parameter we need to pass `maxZoom` like this 

                   MapOptions(
                   ..........
                        maxZoom: 17,
                   ..........
                    )              
                    
and inside `TileLayerOptions` it should be 
```
                             TileLayerOptions(
                                      urlTemplate:
                                          'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
                                      subdomains: ['a', 'b', 'c'],
                                      fastReplace: true,
                                      retinaMode: true, /// I am not disabling this I have just read it's documentation which helped me to understand actual problem 
                                      maxZoom: 18, //// This zoom level should be mapOptions zoom level + 1
                                      ................
                                    ),
```


Please read `ratinaMode`'s documentation 
<img width="677" alt="Screenshot 2022-03-22 at 9 56 14 PM" src="https://user-images.githubusercontent.com/8264639/159533867-5e6a763a-18c4-4f97-8fd8-4c9bccb481d0.png">

**Comment by ch-muhammad-adil** [comment]
I am keeping retinaMode as well, HAPPY TO CLOSE THIS NOW!!!

**Comment by ShokhrukhbekYuldoshev** [comment]
options: MapOptions(
          zoom: 13.0,
          bounds: LatLngBounds(
            LatLng(51.74920, -0.56741),
            LatLng(51.25709, 0.34018),
          ),
          maxBounds: LatLngBounds(
            LatLng(-90, -180.0),
            LatLng(90.0, 180.0),
          ),
        ),

**Comment by ShokhrukhbekYuldoshev** [comment]
![image](https://user-images.githubusercontent.com/72590392/236712764-7cfb5cbe-45b1-4dea-bdaf-bbad56dcfcd2.png)
bounds: LatLngBounds(
            LatLng(51.74920, -0.56741),
            LatLng(51.25709, 0.34018),
          ),
maxBounds: LatLngBounds(
            LatLng(-90, -180.0),
            LatLng(90.0, 180.0),
          ),
