### ISSUE TITLE
 Crash when testing in airplane mode

### ISSUE THREAD

**Issue by AlysonTrizotto** [fleaflet/flutter_map#1195]
Hello, I'm using your api, and at the moment, I'm trying to use cache, however, whenever I activate the airplane mode to test it, it throws me this error

`SocketException (SocketException: Failed host lookup: 'c.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7))`

My code is like this:

` var _needLoadingError = true;

    return Scaffold(
      appBar: AppBar(
        title: Text('Mapa'),
      ),
      body: Center(
        child: Stack(children: [
          FlutterMap(
              mapController: mapController,
              options: MapOptions(
                maxZoom: 18,
                minZoom: 4,
                center: currentCenter,
                zoom: zoomAtual,
                onTap: (k, latlng) {
                  removeMarker();
                  setState(() {
                    addMarker(latlng);
                  });
                },
                plugins: [],
                slideOnBoundaries: true,
                screenSize: MediaQuery.of(context).size,
                
              ),
              layers: [
                TileLayerOptions(
                    tileProvider: MyTileProvider(onError: _onTileError),
                    urlTemplate:
                        "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                    subdomains: ['a', 'b', 'c'],
                    //tileProvider: NonCachingNetworkTileProvider(),
                    //tileProvider: const CachedTileProvider(),
                    updateInterval: 1,
                    errorTileCallback: (Tile tile, error) {
                      if (_needLoadingError) {
                        WidgetsBinding.instance!.addPostFrameCallback((_) {
                          ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                            duration: Duration(seconds: 1),
                            content: Text(
                              error.toString(),
                              style: TextStyle(color: Colors.black),
                            ),
                            backgroundColor: Colors.deepOrange,
                          ));
                        });

                        _needLoadingError = false;
                      }
                      throw Exception('Unknown error, description: $error');
                    }),
                MarkerLayerOptions(markers: [
                  for (int i = 0; i < markers.length; i++) markers[i]
                ]),
                MarkerLayerOptions(markers: [
                  for (int i = 0; i < markerDb.length; i++) markerDb[i]
                ]),
                MarkerLayerOptions(markers: [
                  for (int i = 0; i < markersTracker.length; i++)
                    markersTracker[i],
                ]),
              ]),`

`import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_map/flutter_map.dart';

class CachedTileProvider extends TileProvider {
  const CachedTileProvider();
  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    //print(getImage(coords, options));
    return CachedNetworkImageProvider(
      getTileUrl(coords, options),
    );
  }
}

typedef ErrorResponseHandler = Future<http.Response> Function(Object error,
    [StackTrace stack]);

class MyTileProvider extends TileProvider {
  MyTileProvider({ required this.onError });

  final VoidCallback onError;

  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    final url = getTileUrl(coords, options);
    return CachedNetworkImageProvider(url, errorListener: onError);
  }
}
`

**Comment by JaffaKetchup** [comment]
For more complete caching, consider using my 3rd party solution.
This error is not from `flutter_map`, and exists because there is no Internet to fetch tiles with.

**Comment by AlysonTrizotto** [comment]
I'm tending to this a lot

**Comment by JaffaKetchup** [comment]
Closing, as https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/48 is for the same reason. This issue is out-of-scope here.
