### ISSUE TITLE
[FEATURE] Example for bing map usage?

### ISSUE THREAD

**Issue by xyzbilal** [fleaflet/flutter_map#1197]
**Describe The Problem**
Trying to implement bing maps in tile layer options but white screen only

**Describe Your Solution**

Provide an example for usage for it.

**Alternatives/Workarounds**

no workaround

---

**Additional Information**
I m trying to implement a map without titles, roads etc. bing maps gives me this opportunity but I m getting white screen instead

**my FlutterMap implementation**

```
 FutureBuilder(
        future: getBingUrlTemplate(
            'http://dev.virtualearth.net/REST/V1/Imagery/Metadata/RoadOnDemand?output=json&include=ImageryProviders&key=$bingMapKey'),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
          String url = snapshot.data! as String;
          print(url);
          url = url.replaceAll("en-US", "tr-TR");
          url = url.replaceAll("it=G,L&shading=hill","it=A,G,RL&shading=t");
          print(url);
   
        return FlutterMap(
                  mapController: c.mapController,
                  options: MapOptions(
                      zoom: 11.0,
                      onTap: (tap, points) {
                        // my Logic
                      }),
                  layers: [
                    TileLayerOptions(
                      urlTemplate:snapshot.data as String,
                      attributionBuilder: (_) {
                        return SizedBox(); //Material(child:Text("© OpenStreetMap contributors"));
                      },
                    ),
                    PolygonLayerOptions(polygons:polies),


                  ],
                );
          }else{
            return SizedBox();
          }
          })

```

**function to get link**
```
Future<String?> getBingUrlTemplate(String url) async {
  final Response response = await GetConnect().get(url);
  assert(response.statusCode == 200, 'Invalid key');

  if (response.statusCode == 200) {
    final Map<String, dynamic> decodedJson = response.body ;
    late String imageUrl;
    late String imageUrlSubDomains;
    if (decodedJson['authenticationResultCode'] == 'ValidCredentials') {
      for (final String key in decodedJson.keys) {

  

        if (key == 'resourceSets') {
          // ignore: avoid_as
          final List<dynamic> resourceSets = decodedJson[key] as List<dynamic>;
          for (final dynamic key in resourceSets[0].keys) {
            if (key == 'resources') {
              final List<dynamic> resources =
                  // ignore: avoid_as
                  (resourceSets[0])[key] as List<dynamic>;
              final Map<String, dynamic> resourcesMap =
                  // ignore: avoid_as
                  resources[0] as Map<String, dynamic>;
              imageUrl = resourcesMap['imageUrl'].toString();
              final List<dynamic> subDomains =
                  // ignore: avoid_as
                  resourcesMap['imageUrlSubdomains'] as List<dynamic>;
              imageUrlSubDomains = subDomains[0].toString();
              break;
            }
          }
          break;
        }
      }

      final List<String> splitUrl = imageUrl.split('{subdomain}');
      return splitUrl[0] + imageUrlSubDomains + splitUrl[1];
    }
  }
  return null;
}

```

**Applicable Platforms**
Select platforms that this request applies to.

- [ ] All/any
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
Thanks for your report. Can you check the following things, which may lead to a similar error:

 - Is Bing Maps (or whatever tile server you're using) serving static raster tiles, as opposed to vector tiles? You'll likely find this in the documentation.
 - Do the network calls actually get made to the correct URL? You can use the DevTools Network tab for this purpose.
 - If you change the URL to the OpenStreetMaps one used in the examples, does the map work then? If not, this would indicate something not obvious wrong.

Many thanks!

**Comment by xyzbilal** [comment]
Is Bing Maps (or whatever tile server you're using) serving static raster tiles, as opposed to vector tiles? You'll likely find this in the documentation.
*** Yes. it works. I tried bingmaps service  syncfusion_flutter_maps package and everything works fine.** 
Do the network calls actually get made to the correct URL? You can use the DevTools Network tab for this purpose.
*** Yes. I tried syncfusion_flutter_maps with same urls and on web my urls provide me correct data I need.** 

If you change the URL to the OpenStreetMaps one used in the examples, does the map work then? If not, this would indicate something not obvious wrong.
*** OpenStreet map works fine as you can see in picture below**
I  get reference  to from this link to implement bing maps to my project.

[Link](https://help.syncfusion.com/flutter/maps/tile-layer)


![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-03-25 at 09 44 49](https://user-images.githubusercontent.com/18241412/160068685-c0e14537-ffe5-4467-92b9-6934b9ca4890.png)

**Comment by ibrierley** [comment]
Can you paste what snapshot.data contains.

**Comment by xyzbilal** [comment]
Hi Thanks for interest, Now I received an error after cleaning and rebuilding app
 says that `Exception: No value provided for variable quadkey`  when I search for it  in syncfusion_maps there is getTileUrl and _getQuadKey functions to replace quadKey comes  with url .  my snapshot.data is `http://ak.dynamic.t0.tiles.virtualearth.net/comp/ch/{quadkey}?mkt=en-US&it=G,L&shading=hill&og=1790&n=z`

I thing there would be a solution in the link below but I am not that professional to solve and contribute to project. Plase check the link for the purpos. thanks. [Link ](https://github.com/syncfusion/flutter-widgets/blob/194afe6f24944c0d998bf2edc92e1a70e851e036/packages/syncfusion_flutter_maps/lib/src/layer/tile_layer.dart)

**Comment by ibrierley** [comment]
Quadkeys are shown here https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system on how to calculate.

**Comment by ibrierley** [comment]
Just wondering if you managed to solve this ?

**Comment by xyzbilal** [comment]
unfortunately I couldn't solve it by myself then I start to work on syncfusion maps.

**Comment by JaffaKetchup** [comment]
OK, no problem. Feel free to ask for more help if you start using flutter_map again :)

**Comment by victor0402** [comment]
@luka-glusica Thanks for sharing your solution, it also worked for me

**Comment by TROJANALE** [comment]
@luka-glusica Your solution worked perfectly. Thank you.
PS: In the BingTileProvider class, replace the method:
 @override
  String getTileUrl(Coords<num> coords, TileLayer options) {
    String url = options.urlTemplate ?? '';

    return url.replaceAll('{subdomain}', 't0').replaceAll('{quadkey}',
            _getQuadKey(coords.x.toInt(), coords.y.toInt(), coords.z.toInt()))
        .replaceAll('{culture}', 'en-US');
  }

with the one below. I changed 'Coords' to 'TitleCoordinates'.


@override
  String getTileUrl(TileCoordinates coordinates, TileLayer options) {
    String url = options.urlTemplate ?? '';

    return url.replaceAll('{subdomain}', 't0').replaceAll('{quadkey}',
        getQuadKey(coordinates.x.toInt(), coordinates.y.toInt(), coordinates.z.toInt()))
        .replaceAll('{culture}', 'en-US');
  }

**Comment by TROJANALE** [comment]
@luka-glusica Your solution worked perfectly. Thank you.

PS: In the BingTileProvider class, replace the method:


```
 @override
  String getTileUrl(Coords<num> coords, TileLayer options) {
    String url = options.urlTemplate ?? '';
 return url.replaceAll('{subdomain}', 't0').replaceAll('{quadkey}',
            _getQuadKey(coords.x.toInt(), coords.y.toInt(), coords.z.toInt()))
        .replaceAll('{culture}', 'en-US');
  }
```

with the one below. I changed 'Coords' to 'TitleCoordinates'.

```

@override
  String getTileUrl(TileCoordinates coordinates, TileLayer options) {
    String url = options.urlTemplate ?? `'';`
    return url.replaceAll('{subdomain}', 't0').replaceAll('{quadkey}',
        getQuadKey(coordinates.x.toInt(), coordinates.y.toInt(), coordinates.z.toInt()))
        .replaceAll('{culture}', 'en-US');
  }
```

**Comment by JaffaKetchup** [comment]
As this seems to be working, I'll add it to the docs. Thanks @luka-glusica :)
