### ISSUE TITLE
drag marker Issue #758

### ISSUE THREAD

**Issue by Mike-3** [fleaflet/flutter_map#1199]
Issue: #758

Unfortunately, this code no longer works in version flutter_map 0.14.0. Up to version 0.13.1 it worked fine. From version 0.14.0 onPanUpdate is no longer called to move the markers.
Is there an approach to solve the problem?

**Comment by ibrierley** [comment]
you could try the dragmarker plugin https://github.com/ibrierley/flutter_map_dragmarker if still stuck

**Comment by Mike-3** [comment]
Thanks.
`allowPanningOnScrollingParent: false` fixed the problem.
