### ISSUE TITLE
 Use OSM Bright with TileMill in flutter_map

### ISSUE THREAD

**Issue by AlysonTrizotto** [fleaflet/flutter_map#1202]
I'm trying to use flutter_map with offline map with TileMill which is one of the options of flutter_map, but I'm having difficulties installing osm bright to be able to use TileMill and make the map to work with flutter_map... I know this question is not here, but I saw that osm bright support stopped a while ago (I didn't see any updates), so I decided to see if anyone can help me here
[configure.txt](https://github.com/fleaflet/flutter_map/files/8378597/configure.txt)

Can anyone give me a light on how to install OSM-Bright? I'm trying to do the configuration but without success so far. I've been having the same return for a long time, I checked the installations, read the read.me, but I still couldn't install. This is the payback I have:

C:\Users\PESSOAL\Downloads\mapbox-osm-bright-f1c8780>make.py Traceback (most recent call last): File "C:\Users\PESSOAL\Downloads\mapbox-osm-bright-f1c8780\make.py", line 129, in install() File "C:\Users\PESSOAL\Downloads\mapbox-osm-bright-f1c8780\make.py", line 67, in install assert isdir(config["path"]), "Config.path does not point to your mapbox projects directory; please fix and re-run" AssertionError: Config.path does not point to your mapbox projects directory; please fix and re-run

This is my configure.py
[configure.txt](https://github.com/fleaflet/flutter_map/files/8378601/configure.txt)

this is my dependencies 
![Capturar](https://user-images.githubusercontent.com/79091765/160786832-7bcd8aed-9d39-4d3b-8485-3c1c2e8c72cd.PNG)

**Comment by ibrierley** [comment]
I don't know tilemill, but, start with the basics of the error...

does    config["path"] = path.expanduser("~/Documents/MapBox/project") correspond to where your projects directory is ? If not, change that to the correct place and try again ?
