### ISSUE TITLE
How to display the map of EPSG:404000

### ISSUE THREAD

**Issue by SanSanNiang** [fleaflet/flutter_map#1205]
I don't konw how to display the map of epsg:404000, please, help !

**Comment by ibrierley** [comment]
I don't think 404000 is real system ? Doesn't it kinda mean its not found, a bit like a 404 on a webpage ?

**Comment by SanSanNiang** [comment]
> I don't think 404000 is real system ? Doesn't it kinda mean its not found, a bit like a 404 on a webpage ?

The map can be displayed in GeoServer.
url: http://124.93.251.50:8085/geoserver/patrol/wms?service=WMS&version=1.1.0&request=GetMap&layers=patrol%3Aworkroom4&bbox=-0.5%2C-0.5%2C895.5%2C671.5&width=768&height=576&srs=EPSG%3A404000&format=image%2Fpng

I don't know how to display the map in FlutterMap

**Comment by ibrierley** [comment]
Have you tried the WMS example in the readme and the wms_tile_layer example in the examples folder ? What happens ?

**Comment by SanSanNiang** [comment]
> Have you tried the WMS example in the readme and the wms_tile_layer example in the examples folder ? What happens ?

code：
           FlutterMap(
                          mapController: this._mapController,
                          options: MapOptions(
                              center: LatLng(7.00744829826634,175.6270586294484),                           
                          
                              ),
                          layers: [
                            TileLayerOptions(
                              maxZoom: 14.0,
                              wmsOptions: WMSTileLayerOptions(
                                  baseUrl:
                                      'http://124.93.251.50:8085/geoserver/patrol/wms?', 
                                  layers: ['patrol:workroom4'],
                                  version: '1.1.1',
                                  otherParameters: {
                                  }
                                  ),
                            ),
                          ],
                        ),
There‘s no display. And, the crs is EPSG3857. I don't konw how to change crs to EPSG：404000 
![微信图片_20220401171425](https://user-images.githubusercontent.com/58019634/161234595-c9162fe8-1b46-4daf-bd72-fa584a996928.png)

**Comment by ibrierley** [comment]
Best thing I can think of is to debug the tile_layer.dart and see what _encodedBaseUrl = _buildEncodedBaseUrl();  displays (line 377) if you print it out...see if the args are the same as your example earier.

**Comment by JaffaKetchup** [comment]
Interestingly, <http://91.250.242.35/web/wicket/bookmarkable/org.geoserver.web.demo.SRSDescriptionPage?1&code=EPSG:404000> also shows the map empty (I'm assuming they are using Leaflet).

**Comment by JosefWN** [comment]
That EPSG code is not valid:
> Each entity is assigned an EPSG code between 1024-32767

https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset

**Comment by JaffaKetchup** [comment]
In that case, I'm going to close this as invalid. Please feel free to ask for more help!
