### ISSUE TITLE
LatLng isn't defined 

### ISSUE THREAD

**Issue by aravind-b-dev** [fleaflet/flutter_map#1208]
Error: The method 'LatLng' isn't defined for the class '_FeedbackPageState'.

 - '_FeedbackPageState' is from 'package:nrithya/screens/feedback.dart' ('lib/screens/feedback.dart').
Try correcting the name to the name of an existing method, or defining a method named 'LatLng'.
                    center: LatLng(56.704173, 11.543808),

**Comment by ibrierley** [comment]
Sounds like you don't have LatLng included. Typically you would do something like 

import 'package:latlong2/latlong.dart';

and have latlong2: ^0.8.0 in your pubspec.yaml

**Comment by aravind-b-dev** [comment]
Okay
