### ISSUE TITLE
[BUG] When you zoom in/out on the map, the markers move

### ISSUE THREAD

**Issue by Elidor00** [fleaflet/flutter_map#1209]
**Describe The Bug**
Once the markers are positioned on the map, when you zoom in/out they move slightly higher or lower, moving from their original position. Obviously, the greater is the zoom in/out, the greater is the shift of the markers.

**Expected Behavior**
When zooming I would expect the markers to keep pointing to their original coordinates.

**Screenshots & Recordings**
The marker is initially positioned at the coordinates (Broadwick Street) `(51.513722299986334, -0.13553618031213494)` as can be seen from the following image:
![start](https://user-images.githubusercontent.com/39164350/162297181-df73a9dc-c874-44db-b033-231300ecf59e.jpeg)

After a little zoom out, the marker seems to have moved from its original coordinates going to point the wrong coordinates (Hopkins Street) as can be seen from the following image:
![stop](https://user-images.githubusercontent.com/39164350/162298536-c7722ce0-da17-4682-9608-14edc46d023d.jpeg)

**Additional Information**
-
My `pubspec.yaml`:
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^0.14.0
  flutter_native_splash: ^2.0.4
  flutter_map_marker_popup: ^2.1.1+1
  flutter_map_location_marker: ^3.0.2
  geolocator: ^8.2.0
```
---

**Doctors Report**

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.4 LTS 5.4.0-107-generic, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] VS Code (version 1.66.1)
[✓] Connected device (2 available)

• No issues found!

```

**To Reproduce**

1. Take any example present in the example [folder of the library](https://github.com/fleaflet/flutter_map/tree/master/example/lib/pages)
2. Replace the `build()` function with the following:
```dart
final List<LatLng> _markerPositions = [
    LatLng(51.513722299986334, -0.13553618031213494)
  ];

  final PopupController _popupLayerController = PopupController();

  List<Marker> get _markers => _markerPositions
      .map(
        (markerPosition) => Marker(
            point: markerPosition,
            width: 81.0,
            height: 81.0,
            builder: (_) => const Icon(Icons.location_on, size: 40),
            rotate: true,
            rotateOrigin: const Offset(0.5, 0.5),
        ),
      )
      .toList();

@override
Widget build(BuildContext context) {
    return FlutterMap(
      options: MapOptions(
        center: userPosition,
        zoom: 5.0,
        onTap: (_, __) => _popupLayerController.hideAllPopups(),
      ),
      children: <Widget>[
        TileLayerWidget(
            options: TileLayerOptions(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
          attributionBuilder: (_) {
            return const Text("© OpenStreetMap contributors",
                style: TextStyle(fontSize: 5.0));
          },
        )),
        LocationMarkerLayerWidget(),
        MarkerLayerWidget(options: MarkerLayerOptions(
          markers: _markers,
        ))
      ],
    );
  }

```
4. Try to zoom in/out
5. Watch the marker move

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [x] Non-Fatal
- [ ] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by ibrierley** [comment]
Initial guess would be something like your marker rotation origin/alignment...if you turn off marker rotation, does it stay correct (albeit rotated with the map) ?

**Comment by Elidor00** [comment]
I had already tried to comment these lines of code
```
rotate: true,
rotateOrigin: const Offset(0.1, 0.1),
```
 but the situation does not change

**Comment by ibrierley** [comment]
I think it looks ok to me, it just looks like the center of the marker isn't the "point" of the icon, it's closer to the hole in the icon, so you would want to adjust it so that the bottom point of the icon is at the center.

**Comment by ibrierley** [comment]
You can see this a bit clearer if you use a centralised icon, for example try it with    Icons.add_circle_outline

**Comment by JaffaKetchup** [comment]
I also think @ibrierley might be right. Try making the point of the marker shape the center of the graphic (or choose a centralised design like he suggested).

**Comment by Elidor00** [comment]
Right! Looking more closely while zooming, it appears that the center is the "empty circle/hole of the icon" and not its "point".
Then I test with Icons.add_circle_outline.

In any case, just to understand, if I wanted to use the current icon what parameter should I change to make the center of the icon be the "point" and not the central hole? Is it a problem with the widget or with the icon?

**Comment by JaffaKetchup** [comment]
There might be a way to do it in the code, maybe using anchors and origins in the `Marker` widget - but I have no experience with that.

**Comment by Elidor00** [comment]
Ok I'll try to investigate, thanks

**Comment by JaffaKetchup** [comment]
No problem, always happy to help more if needed.

**Comment by ibrierley** [comment]
Yes, have a look at the anchor code intiially see if it helps. There's an anchor examples page you can run, and look at eg

https://github.com/fleaflet/flutter_map/blob/368e3b71f73ef415997aa1b8f39a0363d140b879/example/lib/pages/marker_anchor.dart

**Comment by AliEasy** [comment]
having the same issue

**Comment by ibrierley** [comment]
Try the same "fix" and check if the center of your icon is where you think it is, and anchor if necessary.

**Comment by AliEasy** [comment]
@ibrierley Thank you
I had to use `AnchorPos.exactly` finally
