### ISSUE TITLE
[BUG] Overlay image using excessive amounts of memory?

### ISSUE THREAD

**Issue by JosefWN** [fleaflet/flutter_map#1210]
**Describe The Bug**
Loading a 61 MB PNG as an overlay image, the memory consumption of the application jumped from ~350 MB to ~1.5 GB.

**Expected Behavior**
I didn't expect a 61 MB PNG to consume 1150 MB of memory.

**Additional Information**
I'm running an M1 ARM on both iOS and macOS, and an Intel Core i3 on Windows.

---

**Doctors Report**

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.12.0-4.2.pre, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.66.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**To Reproduce**

Under the examples, try switching to a larger PNG image on the overlay image page. Unsure if PNG is the only affected file format or if it applies generally.

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [ ] Non-Fatal
- [x] Fatal / App Crashes

Could be argued, but the app is killed at times because of OOM on iOS with images that are just large, not enormous.

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [ ] Android
- [x] iOS 15 / macOS 12
- [ ] Web
- [x] Windows 11
- [ ] Others (beta platforms)

**Comment by JosefWN** [comment]
Ugh, was a bit fast to jump the trigger, seems to be an issue with Flutter itself. Even a simple example-app will consume insane amounts of memory with a large, but not huge, image:

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
            '...'),
      ),
    );
  }
}
```

**Comment by JaffaKetchup** [comment]
Thanks for the report (great use of the template!). I'll leave this open for now, but mark as invalid until we can confirm it's this library's issue.

**Comment by ibrierley** [comment]
Try adding a cacheWidth to your Image.network, see if that helps...

https://api.flutter.dev/flutter/widgets/Image/Image.network.html

```
If cacheWidth or cacheHeight are provided, it indicates to the engine that the image should be decoded at the specified size. The image will be rendered to the constraints of the layout or [width](https://api.flutter.dev/flutter/widgets/Image/width.html) and [height](https://api.flutter.dev/flutter/widgets/Image/height.html) regardless of these parameters. These parameters are primarily intended to reduce the memory usage of [ImageCache](https://api.flutter.dev/flutter/painting/ImageCache-class.html).

In the case where the network image is on the Web platform, the cacheWidth and cacheHeight parameters are ignored as the web engine delegates image decoding to the web which does not support custom decode sizes.
```

**Comment by JosefWN** [comment]
The image is intentionally large because it contains details I need to see when I'm zoomed in, that's the tricky part. I could tile it, but that would make adding the layer (which is done by the end user) a bit slow. I guess I'll just have to eat the cost...

I think the reason I expected the image to be smaller in RAM is because I initially compared my apps memory consumption to Preview on macOS. It seems to stream the visible pixels from disk (including downsampling), keeping the memory consumption reasonably low.

**Comment by JosefWN** [comment]
I will close this issue, as I was a bit quick to jump the gun...
