### ISSUE TITLE
[FEATURE] Rainfall Layer

### ISSUE THREAD

**Issue by paintingStyle** [fleaflet/flutter_map#1218]
**Describe The Problem**
Is it possible to increase the rainfall layer example, the relevant information is too little, I don't know how to draw this kind of layer

**Describe Your Solution**

The following is the data source format:
```
[
    {
        "longitude":-122,
        "latitude":45,
        "rainfall_amount":200,
        "time":1649728404000
    },
    {
        "longitude":-123,
        "latitude":46,
        "rainfall_amount":700,
        "time":1649728404000
    },
    {
        "longitude":-125,
        "latitude":48,
        "rainfall_amount":1200,
        "time":1649728404000
    }
]
....
```

I want to reflect the change in rainfall in the last 12 hours

**Alternatives/Workarounds**
No alternatives found

**Additional Information**

https://user-images.githubusercontent.com/22866404/163738644-e559404d-4821-4c1c-9e9f-1173fac0b1ce.mov

**Applicable Platforms**

- Android

**Comment by JaffaKetchup** [comment]
Hi @paintingStyle,

I'm not quite sure what you mean. Can you elaborate?

Note that flutter_map can only display information it's given from a tile source, if that's what you're asking .

**Comment by ibrierley** [comment]
I'm guessing the idea is maybe more like a heatmap layer (unless somehow someone is providing raster tiles updated every so often).

If so, I think there's probably 3 main components...
1) the data source,
2) getting some visualisation technique (often they look like filters, that vary depending on the input value)
3) drawing them on a canvas
(maybe 4, optimising, as I'm guessing some are resource heavy).

I don't see any reason why it's not possible, it's just that probably no one else is likely to work much on it, unless they have a vested interested in that specific area.  

If you can sort out 2), then the rest should be easier.

It could be nice to have some sort of a plugin, which takes a value and the user provides a visual path/circle/filter/whatever they choose, and the plugin draws it (eg weather layer, heatmap layer etc) I guess.

**Comment by ibrierley** [comment]
I'm going to close this for the moment, as it's outside of the scope of normal flutter_map (currently). It looks similar to a heatmap type problem though, so maybe keep an eye out for if someone develops a solution along those lines.

Feel free to reopen any time though, if there's some news.
