### ISSUE TITLE
[BUG] Map images not getting displayed on web

### ISSUE THREAD

**Issue by minusium** [fleaflet/flutter_map#1221]
**Describe The Bug**
I can see map images are loaded but they're not getting displayed.

**Screenshots & Recordings**
![image](https://user-images.githubusercontent.com/21140798/164186939-fb28dd33-6d1b-4716-932e-34f53f898e81.png)

---

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by ibrierley** [comment]
Probably need more info, like the code thats being run, which tileProvider and url, or is it one of the examples ? I note quite a few of the filenames shown on the right are the same, which looks a bit odd, but hard to tell without seeing more detail.

**Comment by minusium** [comment]
I'm using this, that uses flutter_map under the hood, your examples work well?

https://github.com/mo-ah-dawood/open_location_picker

**Comment by ibrierley** [comment]
I think if all the examples work fine, you're going to have to try and isolate debugging that code...try removing all of the things like ColorFilters, add some debugging to check the full url of each tile being called for, and check if its available (I assume it is, as I couldn't see any errors in the first screenshot, but it's a case of probably proving each step).

**Comment by minusium** [comment]
example seems to work fine, thanks for help

![image](https://user-images.githubusercontent.com/21140798/164226931-a99d59e4-f90a-41c2-830d-505c31558a5f.png)
