### ISSUE TITLE
LateInitializationError: Field'_pixelOrigin has not been initialized.

### ISSUE THREAD

**Issue by stx** [fleaflet/flutter_map#1224]
Seen on iOS 15 devices using production error tracking, Flutter 2.10.4 and flutter_map master. Seems rare. Not sure of the trigger.

```
LateError: LateInitializationError: Field '_pixelOrigin@1049051772' has not been initialized.
  File "map.dart", in MapState.getPixelOrigin
  File "tile_layer.dart", line 701, in _TileLayerState._updateLevels
  File "tile_layer.dart", line 852, in _TileLayerState._setView
  File "tile_layer.dart", line 827, in _TileLayerState._resetView
  File "tile_layer.dart", line 477, in _TileLayerState.initState

#0      MapState._updateSizeByOriginalSizeAndRotation (package:flutter_map/src/map/map.dart:164)
#1      MapState.setOriginalSize (package:flutter_map/src/map/map.dart:128)
#2      FlutterMapState.build.<anonymous closure> (package:flutter_map/src/map/flutter_map_state.dart:81)
```

**Comment by ibrierley** [comment]
Do you know how long this has been happening (and if you are using a version from Git which is later than PR 1216), and is there any way to revert to before PR 1216 to test if so ? (guessing tricky if infrequent)...and do you use fitBounds at all ?

There was some odd things happening previously with fitBounds which I "fixed" where some devices couldn't be initialised with a screen size (maybe on slower devices...), but don't have an ios device to test properly.

Couple of places to explore if so (and maybe even if not) to replicate would be around slow devices, resizing screens and fitBounds...

**Comment by ibrierley** [comment]
Actually, you may have to go before PR 1211 to check...(so checking fitBounds and maxBounds if either of those are used).

Just digging through the code for some other possibilities. There's a few bits of code (inside map.dart move() method), which would all lead to no center being set (so no pixelOrigin I think), i.e if some bounds are invalid that are set...so that would be worth trying to figure out if the code could do that.

**Comment by stx** [comment]
fitBounds, yes! This error was from flutter_map master around PR 1212.

**Comment by JaffaKetchup** [comment]
Hi @stx,
Just cleaning up the issue tracker. Do you have any news? Happy to try to offer more help if we can.
Note that for the time being, it is recommended to always use this library as a dependency from Git(Hub), as new features and fixes are currently not being published to pub.dev.
Thanks!

**Comment by JaffaKetchup** [comment]
Closing for now due to inactivity. @stx, please feel free to ping either of us to re-open this!
