### ISSUE TITLE
[BUG] Azure map

### ISSUE THREAD

**Issue by thomtomdup** [fleaflet/flutter_map#1226]
**Describe The Bug**
Try to use the example of azure map giving in readme file but i have an error with starting page test_app.dart for main start.

**Expected Behavior**
I have an debug error.

**Screenshots & Recordings**
why : to resolve the 'alignment' argument; hint : The default value for 'alignment' is AlignmentDirectional.topStart, which requires a text direction. Alternative : Instead of providing a Directionality widget, another solution would be passing a non-directional 'alignment', or an explicit 'textDirection', to the Stack.

**Additional Information**

---

**Doctors Report**

```shell
Paste your report from `flutter doctor` inside here
```

**To Reproduce**
Just use the example code giving in readme file

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [ ] Non-Fatal
- [x] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [x] Others (beta platforms)

**Comment by ibrierley** [comment]
What's the debug error that you get ?

**Comment by thomtomdup** [comment]
Hello.
I have write the message details in Screenshots & Recordings.

file debug.dart 
function bool debugCheckHasDirectionality

why : to resolve the 'alignment' argument; hint : The default value for 'alignment' is AlignmentDirectional.topStart, which requires a text direction. Alternative : Instead of providing a Directionality widget, another solution would be passing a non-directional 'alignment', or an explicit 'textDirection', to the Stack.

**Comment by thomtomdup** [comment]
Ho ok. Excuse me i didn't see it was missing. Sorry.

Now the problem is that i have a issue with the network image : 
NetworkImage("https://atlas.microsoft.com/map/tile/png?api-version=1&layer=basic&style=main&tileSize=256&view=Auto&zoom=13&x=409 
HttpException: Failed to parse header value

**Comment by ibrierley** [comment]
No problem :).

Have you added <uses-permission android:name="android.permission.INTERNET"/> to your AndroidManifest.xml if using Android. It all works fine for me otherwise.

**Comment by ibrierley** [comment]
Hmm it's probably not that actually...the URL pasted looks like it has some info cut off...

Is that just your paste in here which has cut some off, or is there some info like the y parameter and key (don't include that, but it should mention it in the response I think) ?

**Comment by thomtomdup** [comment]
No the link was not cut.
The url requested is this :
https://atlas.microsoft.com/map/tile/png?api-version=1&layer=basic&style=main&tileSize=256&view=Auto&zoom=13&x=4094&y=2722&subscription-key=----------
