### ISSUE TITLE
How to calculate minZoom from scale

### ISSUE THREAD

**Issue by 1Map** [fleaflet/flutter_map#1233]
I have a minScale (Note: Not minZoom), like for example 6000.  How would I implement that as minZoom in flutter_map for a certain layer?

**Comment by JaffaKetchup** [comment]
Hi there @1Map,
Can you please explain how a minimum scale works, as I'm not aware of this.
Thanks!

**Comment by mohammedX6** [comment]
Try this : 
 ```
  var scale = 6000;
    var minZoom =
        (math.log(591657550.500000 / (scale / 2)) / math.log(2)).round();
```

**Comment by JaffaKetchup** [comment]
@1Map Has @mohammedX6's solution answered your question?
