### ISSUE TITLE
[FEATURE] Ability to ignore long-presses and allow dragging

### ISSUE THREAD

**Issue by victor0726** [fleaflet/flutter_map#1235]
hi,
Generally, there is no problem in dragging the map, but after long-pressing the screen, dragging the map cannot move.
 Is there any attribute that needs to be set? Thank you.

**Comment by JaffaKetchup** [comment]
Hi there,
I've personally never experienced this issue before. Can you please provide a minimal reproducible example to help us debug the issue?
Thanks :)

**Comment by JaffaKetchup** [comment]
Is this what you're experiencing: https://github.com/fleaflet/flutter_map/issues/1111#issuecomment-1002622973?

**Comment by victor0726** [comment]
> Is this what you're experiencing: [#1111 (comment)](https://github.com/fleaflet/flutter_map/issues/1111#issuecomment-1002622973)?

The sample program provided by flutter_map also has the same problem. thanks.

**Comment by victor0726** [comment]
> 
hi,
Drag directly after long-pressing on the map, the map cannot be moved。

thank you.

**Comment by JaffaKetchup** [comment]
Ah I see. This isn't a bug, but also not intended functionality. This is a very rare use case: can I ask what you need this for, if you don't mind?

**Comment by victor0726** [comment]
> Ah I see. This isn't a bug, but also not intended functionality. This is a very rare use case: can I ask what you need this for, if you don't mind?

hi
I know this is not a bug, but it is a bit inconvenient for users to use. I have tested other map apps and there is no such problem. I don't need the long-press function, so long-press-drag and click-drag must be treated as the same action.

Thanks for your reply

**Comment by JaffaKetchup** [comment]
In this case, this will have to be converted to a feature request. Note that waiting times on feature requests are currently indefinite at this time - unless a PR can be supplied - as we (maintainers) are quite stretched at the moment.
Thanks for your interest in 'flutter_map', and we are happy to answer any more questions! My apologies for the late reply.

**Comment by victor0726** [comment]
hi,  
I'm sorry I can't understand your explanation. How to modify the program? Is there a way to do it? Thank you~

**Comment by JaffaKetchup** [comment]
Hi @victor0726,
Unfortunately, there is no way to do it right now. I've converted to a feature request so it may be implemented in the future.

**Comment by JaffaKetchup** [comment]
@ibrierley Should I make a PR for this?

**Comment by ibrierley** [comment]
Yes, sorry I haven't had a lot of time of late. Feel free to have a bash!

**Comment by JaffaKetchup** [comment]
Actually, after looking around a bit, not sure I like the look of that in there. We need to sort out the gestures and events system instead of putting quick fixes like this in.

**Comment by JaffaKetchup** [comment]
@victor0726 Can you try the new v3 betas, and see if they fix your problem?

**Comment by JaffaKetchup** [comment]
@victor0726 Any luck with v3?
