### ISSUE TITLE
Is there onmapclick(event) function in this package 

### ISSUE THREAD

**Issue by halhwadi** [fleaflet/flutter_map#1239]
Sorry, I know this is not a bug, but I didn't know where to post my question...
My question is about onclickmap event function which is used in leaflet to create marker upon clicking on the map and whether its available in this package,  if yes, can you share 1 example please?

Best Regards

**Comment by JaffaKetchup** [comment]
Hi there,
There is indeed! Have a look at the `MapOptions` object, which contains an `onTap` callback with the location of the click as the arguments.
Always happy to help more! Consider using the Discord for questions like this, if you can. There's a join link at the top of the README on GitHub.

**Comment by halhwadi** [comment]
Thank you so much

Sent from Yahoo Mail on Android 
 
  On Mon, 16 May 2022 at 12:50 am, Luka ***@***.***> wrote:   


Hi there,
There is indeed! Have a look at the MapOptions object, which contains an onTap callback with the location of the click as the arguments.
Always happy to help more! Consider using the Discord for questions like this, if you can. There's a join link at the top of the README on GitHub.
