### ISSUE TITLE
Is there an `onMove` event?

### ISSUE THREAD

**Issue by Farrukh1198** [fleaflet/flutter_map#1240]
**Describe The Problem**
Perhaps I did not understand so much or searched badly, but I could not find the onMove event in this package

**Describe Your Solution**
After listening to this event, I would like to add an animation for the marker while the map is moving. It would also be useful for picking up the user's location.

**Alternatives/Workarounds**
onCameraMove event listener in google maps flutter package

---

**Applicable Platforms**
Select platforms that this request applies to.

- [x] All/any

**Comment by JaffaKetchup** [comment]
Hi there,

I think there is an event available that should do what you want.

Just look at `onPositionChanged` in `MapOptions`. It should fire the assigned function if the map pans, rotates, or zooms.

Hope this helps!

**Comment by Farrukh1198** [comment]
> Hi there,
> 
> I think there is an event available that should do what you want.
> 
> Just look at `onPositionChanged` in `MapOptions`. It should fire the assigned function if the map pans, rotates, or zooms.
> 
> Hope this helps!

onPositionChanged doesn't fully cover the desired functionality. Since the event occurs when the user has already released his finger, and I need some function and marker animation to work while dragging the map (moving).
An example is the package https://pub.dev/packages/map_picker . However, I would like to do without this package.

**Comment by ibrierley** [comment]
try listening to your mapController...eg

```
@override
  void initState() {
    super.initState();
    mapController = MapController();
    mapController.mapEventStream.listen((event) {print("EVENT IS $event");});

... etc
in build...

child: FlutterMap(
                mapController: mapController,
                options: MapOptions(
... etc
```

You should see events like the following that you can handle.

```
I/flutter (26001): EVENT IS Instance of 'MapEventMoveStart'
I/flutter (26001): EVENT IS Instance of 'MapEventMove'
I/flutter (26001): EVENT IS Instance of 'MapEventMove'
I/flutter (26001): EVENT IS Instance of 'MapEventMove'
I/flutter (26001): EVENT IS Instance of 'MapEventMove'
I/flutter (26001): EVENT IS Instance of 'MapEventMove'
I/flutter (26001): EVENT IS Instance of 'MapEventMove'
I/flutter (26001): EVENT IS Instance of 'MapEventMoveEnd'
```

**Comment by JaffaKetchup** [comment]
Hi @Farrukh1198, has either of our answers answered your question? Happy to help more if necessary!

**Comment by Farrukh1198** [comment]
> 

Thank you! That's what I need.

**Comment by Farrukh1198** [comment]
And one more question. How can I check if MapEventMoveStart triggered because when I try to check it I get "The switch case expression type 'Type' must be a subtype of the switch expression type 'MapEvent'." and typing MapEvent I don't get any type of event.

**Comment by JaffaKetchup** [comment]
Can you post some code so we can see your current setup? Thanks.

**Comment by Farrukh1198** [comment]
> Can you post some code so we can see your current setup? Thanks.

Currently My code is 
`mapController.mapEventStream.listen((event) { 
      String eventString = event.toString();
      if(eventString == "Instance of 'MapEventMoveStart'") {
        sheetController.snapToExtent(0.1);
        textController.text = 'Checking...';
      } else if(eventString == "Instance of 'MapEventMoveEnd'") {
        sheetController.snapToExtent(0.4);
        textController.text = 'Your address';
      }
    });`

But I know that it's not proper way to get triggered event
`if(event == MapEventMoveStart) {
        // some code
      }`
When I try something like this I get type dismatch error

**Comment by JaffaKetchup** [comment]
Try something like:

```dart
if (event is MapEventMoveStart) {}
```

...instead of using the equality operator?

**Comment by Farrukh1198** [comment]
> Try something like:
> 
> ```dart
> if (event is MapEventMoveStart) {}
> ```
> 
> ...instead of using the equality operator?

This event is not triggering when I move map.
I also tried bellow code to achieve what I wanted 
```
    var eventType = event.source.name;
      if(eventType == "onDrag") {
        sheetController.snapToExtent(0.1);
        textController.text = 'Checking...';
      } else if(eventType == "dragEnd") {
        sheetController.snapToExtent(0.4);
        textController.text = 'Your address';
      }
```
But there is not dragStart source.

**Comment by Farrukh1198** [comment]
I've achieved my goal by bellow code 
```
      var eventType = event.runtimeType;
      if(eventType == MapEventMoveStart) {
        sheetController.snapToExtent(0.05);
        textController.text = 'Checking...';
      } else if(eventType == MapEventMoveEnd) {
        sheetController.snapToExtent(0.4);
        textController.text = 'Your address';
      }
```

But I don't know if it is a proper way to get triggered event.

**Comment by JaffaKetchup** [comment]
If it works, it works, but note that `runtimeType` is expensive. The docs say to prefer using the `is` operator, so I'm not sure why my example didn't work.

**Comment by Farrukh1198** [comment]
> If it works, it works, but note that `runtimeType` is expensive. The docs say to prefer using the `is` operator, so I'm not sure why my example didn't work.

Why runtimeType is expensive? I also tried is operator with runtimeType but didn't get anything. Can you try to compile your code pls?

**Comment by JaffaKetchup** [comment]
Sorry, I meant `runtimeType` is dangerous and doesn't always return the result you expect. See, for example: https://stackoverflow.com/a/66456143/11846040 or https://stackoverflow.com/questions/7715948/how-to-perform-runtime-type-checking-in-dart#comment59556899_35950312

---

Copy and paste the following code into https://dartpad.dev:

```dart
typedef Fut<T> = Future<T>;

void main() async {
  final String str = 'This is a string';
  final num number = 1;
  final Fut<String> future = Fut<String>.delayed(const Duration(seconds: 1), () => 'This is a future');
  
  if (str is String) print(str);
  if (number is num) print(number);
  if (future is Fut) print(await future);
  if (future is Future) print(await future);
}
```

I can't prove it will work with this scenario, but types are types, and if this works (which it does) then using `is` here should work too.

**Comment by Farrukh1198** [comment]
> Sorry, I meant `runtimeType` is dangerous and doesn't always return the result you expect. See, for example: https://stackoverflow.com/a/66456143/11846040 or https://stackoverflow.com/questions/7715948/how-to-perform-runtime-type-checking-in-dart#comment59556899_35950312
> 
> Copy and paste the following code into https://dartpad.dev:
> 
> ```dart
> typedef Fut<T> = Future<T>;
> 
> void main() async {
>   final String str = 'This is a string';
>   final num number = 1;
>   final Fut<String> future = Fut<String>.delayed(const Duration(seconds: 1), () => 'This is a future');
>   
>   if (str is String) print(str);
>   if (number is num) print(number);
>   if (future is Fut) print(await future);
>   if (future is Future) print(await future);
> }
> ```
> 
> I can't prove it will work with this scenario, but types are types, and if this works (which it does) then using `is` here should work too.

Ok. Thank you so much!

**Comment by JaffaKetchup** [comment]
No problem. Will close now, feel free to ping if you need more help!
