### ISSUE TITLE
Bug on non rotated widget

### ISSUE THREAD

**Issue by glennmichaelmejias** [fleaflet/flutter_map#1257]
When I try to rotate and then pan it, the motion did not match my pan gestures. its like the rotation gesture is still accepted.

**Comment by glennmichaelmejias** [comment]
fix it with 
enableMultiFingerGestureRace: true on MapOptions.

this should be enabled by default.

**Comment by JaffaKetchup** [comment]
Hi there @glennmichaelmejias,
Glad to hear you've fixed it. For now we'll leave the option disabled by default to reduce the number of breaking changes.
Thanks for your report!
