### ISSUE TITLE
[FEATURE] Restrict tiles loaded with bound radius

### ISSUE THREAD

**Issue by nhtlquan** [fleaflet/flutter_map#1260]
I want create WMS layer with radius.
Example: Draw only layer in circle.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/20571358/172134058-0facd530-c924-4790-8a63-3b6677c7ba02.png">

My code:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/20571358/172134214-71ab5aa1-97b7-4f11-bf31-0d0b400d7223.png">

Current view:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/20571358/172134303-84d75c4c-1659-4313-bb3e-cf34434fc6aa.png">

**Comment by ibrierley** [comment]
One useful thing you can try, is using Widgets instead of Layers, so you could combine ClipRRect or ClipOval....so you could try (on the top layer) something like...

```
children: <Widget>[
<lower widget tile layer>,
ClipOval(
    child: <upper widget tile layer>
)]
```

You may need something like a custom clipper if using ClipOval I guess, as I think it defaults to circle of the whole area, but it may set you on a path that gives you an idea.

**Comment by nhtlquan** [comment]
> One useful thing you can try, is using Widgets instead of Layers, so you could combine ClipRRect or ClipOval....so you could try (on the top layer) something like...
> 
> ```
> children: <Widget>[
> <lower widget tile layer>,
> ClipOval(
>     child: <upper widget tile layer>
> )]
> ```
> 
> You may need something like a custom clipper if using ClipOval I guess, as I think it defaults to circle of the whole area, but it may set you on a path that gives you an idea.

Thanks for answering.
Not what I wanted.
I have 2 map layers, google map layer and WMS layer.
The google map layer remains the same. But when clicking on 1 point. Will limit the display of the WMS layer to a circle with a radius of 500m. I can still move the map but the shape layer in WMS doesn't change.

**Comment by nhtlquan** [comment]
I using code in this: https://github.com/hpoul/flutter_map_tilebounds_example
And result:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/20571358/172146110-364cb823-3e31-4a40-967c-4e13dc0b9d4c.png">

But, how to limit with circle. 
Code in branch:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/20571358/172146333-538e5f2b-c5ca-4e53-aa5f-39c93f474d2f.png">

**Comment by nhtlquan** [comment]
> One useful thing you can try, is using Widgets instead of Layers, so you could combine ClipRRect or ClipOval....so you could try (on the top layer) something like...
> 
> ```
> children: <Widget>[
> <lower widget tile layer>,
> ClipOval(
>     child: <upper widget tile layer>
> )]
> ```
> 
> You may need something like a custom clipper if using ClipOval I guess, as I think it defaults to circle of the whole area, but it may set you on a path that gives you an idea.

Can you help me?

**Comment by ibrierley** [comment]
It's not clear to me what you are trying to achieve (as you said the suggestion above wasn't what you wanted). The first image seems to show a clip, but the later comments seem to contradict this.

**Comment by nhtlquan** [comment]
> 

Currently I have limited Layer to square, but I want to limit layer to circle.

**Comment by nhtlquan** [comment]
I using code: https://github.com/fleaflet/flutter_map/pull/1212

**Comment by ibrierley** [comment]
So, have you tried a clip, to clip the widget visually to a circle ?

**Comment by ibrierley** [comment]
So, here's an example, with 2 tile layers...it's probably not what you specifically need...but it's all I can think of with the initial desired effect screenshot...I've left the example so it can position the circle anywhere clicked, but in your case, you may want to always have the position width/2,height/2 and move to the center of the click.
![localhost_44873_](https://user-images.githubusercontent.com/3901173/172327478-f56c1c71-e35f-4792-b809-bb25ed9bc1bb.png)

Full code (I just edited the widgets example, so it can be placed there)...

```
import 'package:flutter/material.dart';
import 'package:flutter_map/plugin_api.dart';
import 'package:latlong2/latlong.dart';
import '../widgets/drawer.dart';

import 'dart:ui' as ui;

class WidgetsPage extends StatefulWidget {
  static const String route = 'widgets';

  const WidgetsPage({Key? key}) : super(key: key);

  @override
  WidgetsPageState createState() {
    return WidgetsPageState();
  }
}

class WidgetsPageState extends State<WidgetsPage> {

  static const String route = 'widgets';
  late final MapController mapController;
  Offset circlePosition = const Offset(50.0,50.0);
  double radius = 20.0;
  CustomClipper<ui.Path>? circleClipper = CircleClipper(const Offset(0.0,0.0),0.0);

  @override
  void initState() async {
    super.initState();
    mapController = MapController();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Widgets')),
      drawer: buildDrawer(context, WidgetsPage.route),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [
            Flexible(
              child: FlutterMap(
                mapController: mapController,
                options: MapOptions(
                  onTap: (tapPosition, latlng) {
                      setState(() {
                        final RenderBox referenceBox = context.findRenderObject() as RenderBox;
                        circlePosition = referenceBox.globalToLocal(tapPosition.relative!);
                        circleClipper = CircleClipper(tapPosition.relative!, radius);
                      });
                    },
                  center: LatLng(51.5, -0.09),
                  zoom: 5.0,
                ),
                nonRotatedChildren: const <Widget>[
                  Text(
                    'Testing a circle clip',
                    style: TextStyle(
                        fontSize: 22,
                        color: Colors.red,
                        fontWeight: FontWeight.bold,
                        backgroundColor: Colors.yellow),
                  )
                ],
                children: <Widget>[

                  Opacity(
                      opacity: 0.25,
                      child: TileLayerWidget(
                        options: TileLayerOptions(
                          urlTemplate:
                          'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',
                          subdomains: ['a', 'b', 'c'],
                        ),
                    )
                  ),
                  ClipPath(
                    clipper: circleClipper,
                    child: TileLayerWidget(
                    options: TileLayerOptions(
                      urlTemplate:
                          'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                      subdomains: ['a', 'b', 'c'],
                    ),
                  )),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class CircleClipper extends CustomClipper<ui.Path> {

  final double radius;
  final Offset positionOffset;

  CircleClipper(this.positionOffset, this.radius);

  @override
  ui.Path getClip(Size size) {
    return ui.Path()
      ..addOval(Rect.fromCircle(
        center: positionOffset,
          radius: size.width * 0.1));
  }

  @override
  bool shouldReclip(CustomClipper<ui.Path> oldClipper) => true;
}
```

**Comment by JaffaKetchup** [comment]
As there is a workaround for this, and this is quite a niche feature request, I'm going to close this now. Feel free to make a plugin for this!
