### ISSUE TITLE
[BUG] Zoom issue on double click

### ISSUE THREAD

**Issue by JosefWN** [fleaflet/flutter_map#1265]
**Describe The Bug**
If I place the cursor on my home (or any other specific geographical location) and double click, the position of my cursor is moved geographically as the viewport zooms (this does not happen on scroll, or on Google Maps double click).

**Expected Behavior**
If I place the cursor on my home and scroll rather than double click, the position of my cursor remains on my home. It should be the same for double click.

**Additional Information**
`flutter_map` v1.0.0

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [x] Non-Fatal
- [ ] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [ ] Android
- [ ] iOS
- [x] Web
- [x] Windows
- [x] Mac <- not a beta platform?
- [ ] Others (beta platforms)

**Comment by ibrierley** [comment]
I think I see what you mean..it moves on a double click, but kind of moves too far past the point where the event occured ?

**Comment by JosefWN** [comment]
Yeah, I would expect the mouse pointer to remain stationary both geographically and on the screen. It works "correctly" for scroll, so if you try scroll vs double click I think you will see the difference right away.

**Comment by ibrierley** [comment]
Can you test https://github.com/fleaflet/flutter_map/pull/1271 and see if it helps this (without breaking other stuff!)
