### ISSUE TITLE
[FEATURE] support for Geographic projection (EPSG:4326) WMTS？

### ISSUE THREAD

**Issue by sotex** [fleaflet/flutter_map#1266]
**Describe The Problem**
flutter_map only directly supports tiles with the Web Mercator (EPSG:3857) projection and tiling scheme. This projection is extremely common on the web, so this is usually not a problem. However, some servers do not support Web Mercator, notably this Northern Territory WMS server, which only supports the Geographic (EPSG:4326) projection:
http://wms1.ntlis.nt.gov.au/ilismap

**Describe Your Solution**
Sorry, I don't have a good solution.I want can consider the same dishes as OpenLayers.
https://openlayers.org/en/latest/examples/xyz-esri-4326-512.html

**Alternatives/Workarounds**

---

**Additional Information**

**Applicable Platforms**
Select platforms that this request applies to.

- [x] All/any
- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment]
Closing for now, happy to reopen if it doesn't work for you :)
