### ISSUE TITLE
[FEATURE] tilt/pitch (map perspective)

### ISSUE THREAD

**Issue by greensopinion** [fleaflet/flutter_map#1268]
It would be great to be able to render the map with pitch/tilt to give perspective.

I've been experimenting with tilt/pich and have created a prototype: https://github.com/greensopinion/flutter_map/tree/pitch

Prototype supports:
* rendering with pitch
* set the initial pitch via options
* update the map pitch using the controller
* two-finger gesture (push up/down) to change pitch

There's more to do before this could be included as a feature. Some things are top of mind:
* hit testing
* marker positioning
* support rendering layers without perspective (e.g. pop-up info bubbles on markers)

The prototype has a new example page which you can find in the menu named "Pitch". A two-finger push/pull gesture will tilt the map.

**Comment by greensopinion** [comment]
similar to #220

**Comment by greensopinion** [comment]
pushed my commit as a pull request - but it's not intended to be merged as-is

**Comment by ibrierley** [comment]
Interesting, I had look at this with my vector tiles last time. Go as far drawing the perspective fine, but never got around looking at adapting the guestures, so it would wobble when rotating.

I'll try and take a peek later and give some feedback.

**Comment by greensopinion** [comment]
Here's a screenshot of what I've done so far. 

The image on the left has a 60 degree pitch, the one on the right has 0 degree pitch.
There are two pin markers. The red one is rendered flat to the viewport, the grey one is flat to the map, creating a shadow effect.

<img width="1378" alt="pitch-example" src="https://user-images.githubusercontent.com/18102398/173201011-22300138-9d1d-4907-82a9-9aa355616018.png">

**Comment by greensopinion** [comment]
To reallly make this look like it has depth, we need more distant things to get smaller. Eg. roads that go north/south should appear to converge as they get more distant.

**Comment by ibrierley** [comment]
It should be possible to do that I think. I had a dabble some time ago with the vector stuff...here was an example https://www.youtube.com/shorts/RBU3xjVPCmY this is on canvas, so not really applicable here and drag with rotation was always a pain (I have a few matrix bits if you get stuck), but I think some of the concepts are probably the same, maybe with a Transform widget (I think I asked a question on similar on SO, will see if I can dig it out).

**Comment by ibrierley** [comment]
I dug this out from my old emails...not sure if this is useful at all for the perspective on a Widget.
```dart
Transform(
  transform: Matrix4(
    1,0,0,0,
    0,1,0,0,
    0,0,1,0,
    0,0,0,1,
  )..setEntry(3, 2, 0.001)..rotateX(x)..rotateY(y)..rotateZ(z),
  alignment: FractionalOffset.center,
```

**Comment by greensopinion** [comment]
Thanks Ian that's great

**Comment by JaffaKetchup** [comment]
Ok, I'm going to close this for now, as it's out of scope. Happy to reopen if anyone can work on it!

**Comment by aytunch** [comment]
Just writing to see if @greensopinion is still working on this?
And @JaffaKetchup @ibrierley what are the blockers for this? From the screenshots and videos in the above comments, I see there are working prototypes. Is the main problem perspective? or gesture handling? or tile loading with non square tiles? If I know the blockers, maybe I can try to look in to this.

**Comment by ibrierley** [comment]
The initial blockers iirc (not had chance to dig through the issue again), was the gestures either way. I did post some matrix stuff I think there, and maybe the inverse of that could be used or something, but iirc that can get a bit hairy :).

Many moons ago, I did get as far as https://www.youtube.com/shorts/RBU3xjVPCmY (but the gesture feeling on a full rotation was never there..I think, there may also be a couple of relevant example vids at https://studio.youtube.com/channel/UCovGudVp04tyZONMUN4RGjQ/videos/upload?filter=%5B%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D )

There's probably other issues which people may not care about (bounds/fitbounds etc)

**Comment by aytunch** [comment]
@ibrierley the YT video link is private I guess. Can't access it.

**Comment by ibrierley** [comment]
Sorry :D, have edited, see if that works!
