### ISSUE TITLE
[FEATURE] ... Union polygons / Intersect polygons

### ISSUE THREAD

**Issue by adnanefouam** [fleaflet/flutter_map#1270]
This library is amazing but for an app that use polygons and geometry it's important to use some operations like
Polygons union or intersection for the polygon class, ive tried to paint new points as a groupe of multipoints that contains all the groupe of polygons but the holes makes the process difficult 

**Wanted solution**
 Using a methode like  Union(Poly1,Poly2) / Intesect(Poly1,Poly2) and get the result as a new polygon class with all the features holes .....

**Applicable Platforms**
- [x] All/any

**Comment by ibrierley** [comment]
Maybe this is of use ?

https://pub.dev/packages/poly_bool_dart

**Comment by adnanefouam** [comment]
i've used it, it gives a format with segments that have (x,y,z) and it works with a class (RegionPolygon) , in fact i've modify it and i managed to achieve the intersection by creating a method that converts Polygon to RegionPolygonafter that i eliminated the (z) dimension from the result and convert it back to the Polygon class, but i found some issue in the union part.


` RegionPolygon _transformFlutterMapPolyToPolyRegion(Fmap.Polygon polygon) {
    RegionPolygon poly1 = RegionPolygon(regions: []);

    poly1.regions = [
      List.generate(
          polygon.points.length,
          (i) => Coordinate(
              polygon.points[i].latitude, polygon.points[i].longitude)),
      if (polygon.holePointsList != null)
        for (int index = 0; index < polygon.holePointsList!.length; index++)
          List.generate(
              polygon.holePointsList![index].length,
              (i) => Coordinate(polygon.holePointsList![index][i].latitude,
                  polygon.holePointsList![index][i].longitude))
    ];

    return poly1;
  }`

**Comment by mohammedX6** [comment]
Hi,
 you can try [polybool js](https://github.com/velipso/polybooljs) port to dart https://github.com/mohammedX6/poly_bool_dart

**Comment by ibrierley** [comment]
Going to close this, as I think there's a solution there, but feel free to reopen.
