### ISSUE TITLE
[FEATURE] Ability to change the language of map features

### ISSUE THREAD

**Issue by shashanka777** [fleaflet/flutter_map#1277]
_Reporter did not use issue template and did not add any useful information_

**Comment by ibrierley** [comment]
It's not clear to me, what part exactly do you need a different language for ?

**Comment by shashanka777** [comment]
Hi Greetings,
In map it was like example in taiwan it showing different language is that posssible to change the lanaguage to english?
________________________________

**Comment by ibrierley** [comment]
The language of the locations etc on the maps, are purely dependant on the URL of the tile provider you choose, so you need to find a tile provider (or select their option) for whichever you want. I'm not sure the default openstreetmap supports that, but others do (but you may have to pay, depending on what options you need).

**Comment by shashanka777** [comment]
Okay thanks for your replay,
________________________________

**Comment by JaffaKetchup** [comment]
@shashanka777 Hope your issue is resolved! In future, please make better use of the issue template.
