### ISSUE TITLE
[BUG] ...  After max zoom it was showing empty map.

### ISSUE THREAD

**Issue by shashanka777** [fleaflet/flutter_map#1280]
**Describe The Bug**
1. In Map after the zoom position reaches to more than 19.5 it showing empty map , check the below attached recordings video.
2. Other Bug is if the two or more  markers have same  latitude and Longitude value then it showing only one marker, for that bug have any solution ?.

**Expected Behavior**
1. In map it need to show the map upto max zoom position.
2. if markers have same  latitude and Longitude value then need to show all markers.

**Screenshots & Recordings**
If possible, add screenshots or recordings to help explain your problem. This can quickly improve diagnosis of the issue.

https://user-images.githubusercontent.com/107545028/174049756-33e28cbc-ea25-4402-831e-d40789c67a47.mp4

**Additional Information**
Add any other context about the problem here, or remove this section.

---

**Doctors Report**

```shell
Paste your report from `flutter doctor` inside here
```

**To Reproduce**

3. Click on '....'
4. Scroll down to '....'
5. See error

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [ ] Non-Fatal
- [ ] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [ ] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by shashanka777** [comment]
1.Max zoom in on the map is at zoom position 19.0 , in map not showing anything if the  zoom in position reaches above 19.0 . it only show marker it will not show any map image or location details.

 2. Is there any possible to display two markers side by side if the markers have same latlng values.
________________________________

**Comment by shashanka777** [comment]
> 1. What maxzoom on the map and tileLayers are you using ?
> 2. If 2 markers have the same latLng, I would assume one is hidden behind the other...not sure exactly what you would want to happen there.

**Comment by ibrierley** [comment]
Try using maxZoom 19 on the TileLayerOptions.

For the markers, the problem then is that the marker is at the wrong LatLng, which is even worse, all manner of strange things could happen (especially at low zoom levels). This one is really down to whoever to create a clean data source for any particular zoom level. One could probably write a plugin with some collision detection and either hide or adjust a marker, but I don't really think thats for flutter_map itself to decide that.

**Comment by JaffaKetchup** [comment]
@shashanka777
Is this OK to close? Have you resolved your problems?

**Comment by shashanka777** [comment]
Thanks for your reply.
________________________________
