### ISSUE TITLE
Can't set transparency to wms layer

### ISSUE THREAD

**Issue by kttary** [fleaflet/flutter_map#1281]
I'm trying to overlay wms layer on top of openstreet map with following code:

```
return FlutterMap(
      options: MapOptions(
        center: LatLng(35.7062591,-96.7874228,),
        zoom: 4.0,
      ),
      layers: [
        TileLayerOptions(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
        ),
        TileLayerOptions(
                    TileLayerOptions(
                    wmsOptions: WMSTileLayerOptions(
                     baseUrl: 'https://ahocevar.com/geoserver/wms?',
                      layers: ['topp:states'],
                      transparent: true,
                    ),
                  ),
      ],
      nonRotatedChildren: [
        AttributionWidget.defaultWidget(
          source: 'OpenStreetMap contributors',
          onSourceTapped: () {},
        ),
      ],
    );
```

However, the wms layer is not transparent so it hiding osm basemap. flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on Pop!_OS 22.04 LTS 5.17.5-76051705-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by ibrierley** [comment]
What happens if you set backgroundColor on the TileLayerOptions to transparent ?

**Comment by kttary** [comment]
That is.
