### ISSUE TITLE
LatLng is not defined OOTB, consider exporting latlong2/latlong.dart

### ISSUE THREAD

**Issue by ko16a46** [fleaflet/flutter_map#1285]
Hello,

When I just started out using this package, I was confused why `LatLng` wasn't defined, and the autocomplete wasn't helping me out. Turns out this was the same problem described in #1208 and I just needed to add `latlong2` as a dependency.

**Suggested improvement**
Perhaps consider adding `export 'package:latlong2/latlong.dart'` to the exports in the main barrel file, so that new users aren't confused when `LatLng` doesn't work.

Thank you!

**Comment by ko16a46** [comment]
Ok, thanks for the quick reply! Also I suppose an alternative to exporting would just be documenting the need to add the dependency yourself somewhere, maybe in the readme. Thanks for the context

**Comment by JaffaKetchup** [comment]
Funny you should mention the docs, there will be some improvements coming soon!
