### ISSUE TITLE
Accomodate for MapBox iOS & Android SDK as well as Web

### ISSUE THREAD

**Issue by IttaiBarkai** [fleaflet/flutter_map#1287]
Hopefully someone can correct me, but it seems the only way to integrate a custom MapBox style at the moment is by making use of an integration url? Like in the readme, for example:

<img width="495" alt="Screenshot 2022-06-22 at 21 36 25" src="https://user-images.githubusercontent.com/53575993/175131254-0d15a52e-3421-4a55-a0c2-35248d2e1f76.png">

ideally I would prefer to use the web, iOS and Android style URLs. For example: 

<img width="419" alt="Screenshot 2022-06-22 at 21 37 39" src="https://user-images.githubusercontent.com/53575993/175132045-148aecc8-3e87-4ffd-93a1-020a1acfb029.png">

*screenshots taken from mapbox studio

Any advice regarding the matter would be greatly appreciated :) 

**Applicable Platforms**

-  Android
-  iOS
-  web

**Comment by JaffaKetchup** [comment]
Hi there,

You are correct about this being the correct integration method.

Unfortunately it is beyond the scope of this project to implement external SDKs like this - especially as maintainer efforts are somewhat stretched currently.
If you can create a plugin to do this, it would be much appreciated and I'd be happy to add it to the upcoming docs, and I'm sure plenty of people (myself included) would thank you!

Thanks for your interest in flutter_map, and please feel free to leave feedback in future :)

**Comment by JaffaKetchup** [comment]
Ah no problem, hope that this method works well for you for now :)
