### ISSUE TITLE
[BUG] Labels rotating with the map making it difficult to read

### ISSUE THREAD

**Issue by saugatshakya** [fleaflet/flutter_map#1298]
**Describe The Bug**
I was trying to implement mapbox in flutter_map, the labels in the map are not rotating like they rotate normally in mapbox, making it harder for the users to understand the labels.

**Expected Behavior**
In mapbox and other similar map services, the labels rotate counter to the rotation of the map, making it easier for the user to read the labels at all time.

![image](https://user-images.githubusercontent.com/65102753/177917659-8ad6875e-fe80-420e-8afe-88660d952950.png)

**Comment by JaffaKetchup** [comment]
Hi there,

This is a drawback with raster tiles, the type used by this library. Please see https://docs.fleaflet.dev/tile-servers/raster-vs-vector-tiles, and do some research of your own.

There is no plan to implement vector tiles, as it is out of scope. However, there is a plugin available, linked on the page above.

Thanks for your interest!
