### ISSUE TITLE
[BUG] Adding array of Markers to Flutter_Map only show after moving the map

### ISSUE THREAD

**Issue by sonjeux** [fleaflet/flutter_map#1300]
**Describe The Bug**
Adding array of Markers to Flutter_Map only show after moving the map, when the zoom is 10 if it shows all the markers

**Expected Behavior**
Markers only show after moving the map

**Screenshots & Recordings**
https://youtube.com/shorts/IjS5e_Av7u8?feature=share

when the zoom is 10 if it shows all the markers
https://youtu.be/O52I-TPxedQ

**Additional Information**
```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  List<double> coordenadas(String coordenada) {
    List<double> datos = [];
    datos.add(
        double.parse(coordenada.substring(0, coordenada.indexOf(',')).trim()));
    datos.add(
        double.parse(coordenada.substring(coordenada.indexOf(',') + 1).trim()));
    return datos;
  }

  List<Marker> lugares() {
    List<String> puntos = [];
    puntos.add("-21.537095, -64.755728");
    puntos.add("-21.526250, -64.729663");
    puntos.add("-21.546215, -64.703554");
    puntos.add("-21.536175, -64.720484");
    puntos.add("-21.518357, -64.740251");

    List<Marker> datos = [];
    for (var punto in puntos) {
      datos.add(Marker(
          height: 45,
          width: 45,
          point: LatLng(coordenadas(punto)[0], coordenadas(punto)[1]),
          builder: (context) {
            return IconButton(
              onPressed: () {
                showModalBottomSheet(
                    context: context,
                    builder: (context) {
                      return Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisSize: MainAxisSize.min,
                          children: const [
                            ListTile(
                              leading: Icon(Icons.warehouse),
                              title: Text('SETAR - OFICINA BARRIO ABAROA'),
                            ),
                            ListTile(
                              leading: Icon(Icons.place),
                              title: Text(
                                  'CALLE ORURO ESQ. ESPAÑA (LADO MERCADO BOLIVAR)'),
                            ),
                          ],
                        ),
                      );
                    });
              },
              icon: const Icon(
                Icons.room,
                size: 45,
                color: Colors.red,
              ),
            );
          }));
    }
    return datos;
  }

  MaterialColor colorApp = Colors.red;
  String coordenadasCentro = "-21.53549, -64.72956";

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: colorApp,
        primaryColor: colorApp,
      ),
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Mapas'),
        ),
        body: Center(
          child: FlutterMap(
            options: MapOptions(
              interactiveFlags:
                  InteractiveFlag.pinchZoom | InteractiveFlag.drag,
              center: LatLng(coordenadas(coordenadasCentro)[0],
                  coordenadas(coordenadasCentro)[1]),
              zoom: 12.5,
            ),
            layers: [
              TileLayerOptions(
                urlTemplate:
                    "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                subdomains: ['a', 'b', 'c'],
              ),
              MarkerLayerOptions(markers: lugares())
            ],
          ),
        ),
      ),
    );
  }
}```

---

**Doctors Report**

```shell
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Versi¢n 10.0.19044.1766], locale es-ES)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.2)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.69.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**To Reproduce**

1. Open App

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [x] Non-Fatal
- [ ] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by ibrierley** [comment]
I assume it's down to the markers not being ready when FlutterMap is put in the widget tree...

Out of interest, what happens if you use a Widget layer, instead of LayerOptions... so something like...

```dart
FlutterMap(
            options: MapOptions(
              interactiveFlags:
              InteractiveFlag.pinchZoom | InteractiveFlag.drag,
              center: LatLng(coordenadas(coordenadasCentro)[0],
                  coordenadas(coordenadasCentro)[1]),
              zoom: 12.5,
            ),
            children: [
              TileLayerWidget(options:
                TileLayerOptions(
                  urlTemplate:
                  "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  subdomains: ['a', 'b', 'c'],
                )
              ),
              MarkerLayerWidget(options: MarkerLayerOptions(markers: lugares()))
            ],
          ),
```

**Comment by paul-gdy** [comment]
I try your code on android, ios and web but I can not reproduce this issue. Do you have a repository ?

**Comment by sonjeux** [comment]
> I try your code on android, ios and web but I can not reproduce this issue. Do you have a repository ?

in emulator it works without problems

**Comment by sonjeux** [comment]
> I couldn't either, but I'm suspecting it may be a timing issue that only happens on slow devices, but could be wrong...(I'm also assuming its not an old version of FlutterMap, but again could be wrong!)

tried on several cell phones, I use the latest version

**Comment by ibrierley** [comment]
Have you tried the suggested code above and it still has the same problem on cell phones ?

**Comment by sonjeux** [comment]
> Have you tried the suggested code above and it still has the same problem on cell phones ?

yes, it didn't work, i still have the same problem

**Comment by sonjeux** [comment]
> I try your code on android, ios and web but I can not reproduce this issue. Do you have a repository ?

I don't have a repository, but that's all the code

just add in pubspec.yaml
flutter_map: ^1.1.1
latlong2: ^0.8.1

**Comment by ibrierley** [comment]
Wondering if you'd be better with a stateful widget here, rather than stateless...I don't see that it would, but it may be worth a quick go.

**Comment by paul-gdy** [comment]
Maybe use a stateful widget and add the following code in the `initState()`.
```
WidgetsBinding.instance.addPostFrameCallback((_) {
    setState(() {});
});
```

**Comment by sonjeux** [comment]
> Maybe use a stateful widget and add the following code in the `initState()`.
> 
> ```
> WidgetsBinding.instance.addPostFrameCallback((_) {
>     setState(() {});
> });
> ```

it didn't work I think it's a bug because when the zoom is 10 the markers are shown and in the emulator they are shown with any zoom

**Comment by ibrierley** [comment]
Start with the examples....does the home example work ?

eg https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/home.dart

if not, let us know. If it does work, slowly add bits of your code back until it breaks, then let us know which bit caused it.

**Comment by JaffaKetchup** [comment]
@sonjeux Any news?

**Comment by JaffaKetchup** [comment]
Hi there, I'm going to have to close this now due to inactivity. Please feel free to ask to reopen or make a new issue if this still is an issue for you!

**Comment by sernocturno** [comment]
hi everyone, i have the same problem here, im working with flutter but im debugging on windows with chrome, mi pc is an i5 12500, windows 10, so is not a performance problem, after add a marker the, have to move the map to show the marker, im using a statelesswidget and after add the marker i call notifylistener()

**Comment by JaffaKetchup** [comment]
Hi @sernocturno,
Please open a new issue with a reproducible example (and checking the example app first) if you still experience this with the latest FM version 6.1.0.

**Comment by fabilei** [comment]
I had the same problem, I managed to solve it, I using a Future type function inside the .then it added the command 

setState((){});

and solved the problem of markers only appearing after some action on the map, zoom, move, etc.
no need to add to inistate

Future<List<Marker>> _buildPins(BuildContext context) async {
  await fetchDados.call().then((dados) {
    for (var item in dados) 
    {      
      double latitude = double.parse(item.latitude.toString());
      double longitude = double.parse(item.longitude.toString());
      var marcador = buildPin(context, LatLng(latitude, longitude), item);
      customMarkers.add(marcador);
    }
    setState((){});
    })
    .catchError(
      (onError){
      print('erro $onError');
    }
    );
    return customMarkers;
}


the customMarkers variable used in this function must be the same as the one set in 'markers:' so they will be updated correctly
