### ISSUE TITLE
Can you tell me how to load the FeatureLayer layer？

### ISSUE THREAD

**Issue by yinxh2016** [fleaflet/flutter_map#1305]
how to load the FeatureLayer layer？

**Comment by ibrierley** [comment]
What is he featureLayer ? Geojson ? If so, you need to use one of the geojson packages out there to decode, and then take its geometry and create a polyline/polygon/marker layer or whatever from it.

**Comment by JaffaKetchup** [comment]
Please use the appropriate issue template - and include some more information, so that we know exactly what you are talking about - in future, or use the Discord server.

If you still need more help, we're happy to offer it on a new issue or on the Discord server :)
