### ISSUE TITLE
[FEATURE] Add option to hide flutter_map text in attribute layer

### ISSUE THREAD

**Issue by Husnain-Asharf** [fleaflet/flutter_map#1310]
### What do you want implemented?

- There should be option to hide flutter_map text in attribute layer.

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
Can't you just create your own attribution layer, eg   https://github.com/fleaflet/flutter_map/blob/master/lib/src/layer/attribution_layer.dart ?

**Comment by Husnain-Asharf** [comment]
Ooh my mistake I did not saw attributionBuilder. It's fixed.

**Comment by JaffaKetchup** [comment]
Hi @Husnain-Asharf,
As a project/community, we don't impose mandatory attribution - unlike some commercial mapping libraries.
However, please consider keeping the 'flutter_map' attribution if you can! It helps to make people aware of our presence, just like leaflet.js.
In any case, thanks for using 'flutter_map'!
