### ISSUE TITLE
[FEATURE] Handle setParams in WMS options to Refresh a Single Layer

### ISSUE THREAD

**Issue by 1Map** [fleaflet/flutter_map#1313]
### What do you want implemented?

https://leafletjs.com/reference.html#tilelayer-wms-setparams:~:text=Description-,setParams,-(%3CObject%3E

How can I implement setParams (Used in leaflet) on my WMS Layer to update the layer parameters and force a redraw on a single wms layer? - See link to Method above

### Platforms Affected

Android

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
Would reset on the TileLayerOptions do what you need ?

**Comment by 1Map** [comment]
What I need is to modify a WMS URL parameter to prevent client-side caching.  For example:  

https://sampleserver.com/wms?param1=value1&param2=value2&....

To prevent client-side caching of tiles, I then can call a url as follow:

https://sampleserver.com/wms?param1=value1&param2=value2&RANDOM=randomnumber....

Where randomnumber is changed to a random number, and then a redraw on that layer, **everytime** the layer changes and I need to force a fetch from server.

setParams in leaflet works perfectly, but not sure how to handle this in fluttermap?

**Comment by ibrierley** [comment]
As I said, reset on the TileLayerOptions.

If Flutter is doing internal caching as well, you may want to do imageCache?.clear();

**Comment by 1Map** [comment]
How would one do that (reset on TileLayerOptions)?  I am new to Flutter Map.  Will appreciate a sample.

**Comment by ibrierley** [comment]
Can't you just change the urlTemplate to include the relevant changed params ?

**Comment by ibrierley** [comment]
or the WMSTIleLayerOptions....

**Comment by ibrierley** [comment]
If not, maybe just paste an example, as its often hard to grasp it without seeing the actual code

**Comment by 1Map** [comment]
```
    var mapLayer = TileLayerOptions(
      minZoom: minZoom.toDouble(),
      maxZoom: maxZoom.toDouble(),
      backgroundColor: Colors.transparent,
      wmsOptions: WMSTileLayerOptions(
        baseUrl: baseUrl,
        format: imageFormat,
        version: '1.3.0',
        transparent: isTransparent,
        otherParameters: {
          'type': baseOrOverlay,
          'isbase': isBaseLayer.toString(),
          'isbaselayer': isBaseLayer.toString(),
          'drawcache': drawCache.toString(),
          'serial': _serial,
          'token': _token,
          'layerid': layerId.toString(),
          'filterid': filterId.toString(),
          'srs': 'EPSG:3857',
          'tileloadingdelay': '0',
          'format_options': formatOptions,
          'tiled': 'true',
          'opacity': opacity.toString(),
          'style': style,
          'attribution': attribution
        },
      ),
    );
```

What I want is to add an extra parameter in `wmsOptions.otherParameters`, but not during initial setup.  Only if I need to refresh the layer and force it to draw from server, something like: 
`'random': myrandomnumber`

**Comment by ibrierley** [comment]
So what does happen if you do add 'random': myrandomnumber to the otherParameters map when you need to and resetController.add(null) when you need to ? (I can't remember if reset reloads all the tile options, if not and the tile layer doesn't do anything, you may need to call setState on fluttermap or pass a stream to the rebuild param in the tile layer to force it to the rebuild, depending on the rest of your code or something)

**Comment by JaffaKetchup** [comment]
Hi @1Map, any news on this? If you need more help with the resetting, please see https://docs.fleaflet.dev/usage/layers/tile-layer/other-options#reset-stream-reset, which was added to the documentation recently.

**Comment by JaffaKetchup** [comment]
I'm going to have to close this issue now due to inactivity. Please let me know if you need it reopened!
