### ISSUE TITLE
[BUG] `Marker` With `IconButton` Calls `onPressed` Unexpectedly

### ISSUE THREAD

**Issue by rick2909** [fleaflet/flutter_map#1316]
### What is the bug?

Since the icon is a container with an IconButton in it, it should be that the OnPressed is only called when the icon is pressed. Now this doesn't happen, It is only called when dragging the map around, and every bit that is dragged it is called.
The OnPressed from the IconButton is also called when loading in (building) before the FlutterMap is fully initialised, so this causes a crash when using an `ScaffoldMessenger` for example.

### What is the expected behaviour?

When the icon is pressed execute the function `tapMarker()` once.

### How can we reproduce this issue?

```dart
List<Marker> markers = [];

  @override
  void initState() {
    super.initState();
    loadMarkes();
  }

Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FlutterMap(
          options: MapOptions(
            center: LatLng(52.28, 5.3),
            zoom: 7.1,
            maxZoom: 18,
          ),
          layers: [
            TileLayerOptions(
              urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
              subdomains: ['a', 'b', 'c'],
              tileProvider: NetworkTileProvider(),
            ),
            MarkerLayerOptions(
              markers: markers,
            ),
          ],
        ),
      ),
    );
  }

void loadMarkes() {
      markers.add(
        Marker(
          point: LatLng(52.067211, 4.323950),,
          builder: (ctx) => markerIcon(p),
        )
      );
  }

Widget markerIcon(Widget w) {
    return Container(
      child: IconButton(
        icon: Icon(Icons.place),
        onPressed: tapMarker('place'),
      ),
    );
  }

  tapMarker(String m) {
    print('Tapped on ${m}');
  }
```

### Platforms Affected

Android, Web

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi there @rick2909,

Can you try replacing:

> ```dart
> onPressed: tapMarker('place'),
> ```

...with this instead:

> ```dart
> onPressed: () => tapMarker('place'),
> ```

I think this should resolve the issue, and if it does work, this is not a 'flutter_map' issue, instead a misunderstanding of the way Dart calls functions?

Let us know if that works for you!

**Comment by rick2909** [comment]
> Hi there @rick2909,
> 
> Can you try replacing:
> 
> > ```dart
> > onPressed: tapMarker('place'),
> > ```
> 
> ...with this instead:
> 
> > ```dart
> > onPressed: () => tapMarker('place'),
> > ```
> 
> I think this should resolve the issue, and if it does work, this is not a 'flutter_map' issue, instead a misunderstanding of the way Dart calls functions?
> 
> Let us know if that works for you!

It worked thx.
Did this change in the BIG flutter upgrade?

**Comment by JaffaKetchup** [comment]
@rick2909 That's great to hear! I think this has been like this since the start of Dart, and many other languages (such as JavaScript where my origins are) follow a similar pattern.

It has something to do with the way anonymous functions are called, or something like that, but I can't really give much more info than that. For example, if that function didn't have any arguments, and you didn't put any () on it, it would work as expected. The () causes it to run immediately, whereas the anonymous
function is just a definition, not a call.
