### ISSUE TITLE
Call For Maintainers!

### ISSUE THREAD

**Issue by JaffaKetchup** [fleaflet/flutter_map#1326]
Hi all, and thanks for the great support that has been shown to us maintainers recently. We want to thank all of you contributors as well, you've helped bring this project back to life.

Unfortunately, @johnpryan has announced that he will be unable to spend any longer period of time working on this repository, so only essential work will be carried out by him. The other maintainers seem to have also departed from this project.

Therefore, we are asking for new maintainer applications! Don't worry, we are not going anywhere, but it would be great to have a helping hand. At the moment, we are unable to actually grant contribution permissions here on GitHub, but you can still help do many things (such as reviews, coding, and issue response), and @ibrierley or I will merge/do whatever on your behalf.

If you're interested, and you have a few spare minutes per day or whenever needed, please fill out this form: https://forms.gle/W78H942xc6PdVwf96.

We look forward to seeing your responses!

**Comment by pablojimpas** [comment]
I will keep an eye more frequently on the main repo and some plugins to help where I can, but right now I can't commit more to this.

**Comment by JaffaKetchup** [comment]
I'm closing this for now, as we've got a few more maintainers since this was posted. The form is still open, and we'd still love to have you on the team.

Please see above, or https://github.com/fleaflet/flutter_map/discussions/1366 for more information.
