### ISSUE TITLE
3D Map View

### ISSUE THREAD

**Issue by mohamadkenway** [fleaflet/flutter_map#1335]
### What do you want implemented?

I suggest implement 3d map view like Google Map 

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi there!

This appears to be a duplicate of https://github.com/fleaflet/flutter_map/issues/1268. Please check for similar feature requests in future, and also give a more detailed description of what you would like in future requests, when possible.

Thanks for your interest!
