### ISSUE TITLE
[FEATURE] Drag gesture on PageView

### ISSUE THREAD

**Issue by luunc** [fleaflet/flutter_map#1340]
### What do you want implemented?

When I use `FlutterMap` as a child of `PageView`, I cannot swipe among the pages.
Seem like the drag gesture is prioritized for the `FlutterMap` area, so the `PageView` does not behave as usual.
Is there any way to swipe the `PageView` with the `FlutterMap` inside, but still receive the tap gesture on the the map?
Thank you.

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi there @luunc,
Can you try setting `absorbPanEventsOnScrollables` to `false` inside `MapOptions`?
Many thanks :)

**Comment by luunc** [comment]
Hi @JaffaKetchup ,
I don't see that property (`absorbPanEventsOnScrollables `) in `MapOptions

<img width="866" alt="Screen Shot 2022-08-15 at 16 06 14" src="https://user-images.githubusercontent.com/46735778/184607847-326c1d86-18d0-4d48-aa3d-f23951cfa94d.png">
`

**Comment by JaffaKetchup** [comment]
Sorry, my mistake, that will be a property in v3. For now, try doing the same on `allowPanningOnScrollingParent`.

**Comment by ibrierley** [comment]
Thats on the new beta version, if using an older version could try ```allowPanningOnScrollingParent: true/false```

**Comment by sikandernoori** [comment]
> Hi there @luunc, Can you try setting `absorbPanEventsOnScrollables` to `false` inside `MapOptions`? Many thanks :)

Saved the day !!! 

Documentation would be great though.
