### ISSUE TITLE
[BUG]  don't draw map when using WMS options

### ISSUE THREAD

**Issue by drgo190** [fleaflet/flutter_map#1345]
### What is the bug?

When using the WMS option in TileLayerOptions, it does not draw the map that is sent to it in the urlTemplate variable

![evidencia_flutter_map](https://user-images.githubusercontent.com/82405805/186477225-24e34766-5abe-4f03-a6bc-0564f25bcd73.png)

### What is the expected behaviour?

The lines, in this case red and blue, are called through a WMS server

![otro](https://user-images.githubusercontent.com/82405805/186478347-93d44ade-38f6-4c6e-bae7-b984ca69b958.png)

### How can we reproduce this issue?

```dart
TileLayerOptions(
      subdomains: ['a', 'b', 'c'],
      urlTemplate:'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      userAgentPackageName: 'dev.fleaflet.flutter_map.example',
      wmsOptions: WMSTileLayerOptions(
          baseUrl: 'https://xxx.xxx.xxx/wms?',
          layers: ['xxxxxxxxxx'],
          transparent: true,
          crs:const Epsg3857(),
          version: '1.3.0',
          
      ), 
    ),
```

### Do you have a potential solution?

I was checking and possibly in the base_tile_provider.dart file in the getTileUrl function, in the urlTemplate condition, as the WMS option is being used, it will never take the value of the urlTemplate.

![fluter_ayuda](https://user-images.githubusercontent.com/82405805/186479244-3b9cd07e-b5b7-44d8-bbdc-ffe1172b4b94.png)

### Platforms Affected

Android, iOS, Web

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @drgo190,
If you are displaying two different maps (different URLs), you should use two tile layers. Can you try this please?
Many thanks for the report!

**Comment by drgo190** [comment]
Hi @JaffaKetchup 

i tried this

TileLayerOptions(
    subdomains: ['a', 'b', 'c'],
    urlTemplate:'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    userAgentPackageName: 'dev.fleaflet.flutter_map.example',
     
  ),
  TileLayerOptions(
    wmsOptions: WMSTileLayerOptions(
        baseUrl: 'https://xxxx.xxx.xxx/wms?',
        layers: ['xxxxxxx'],
        transparent: true,
        crs:const Epsg3857(),
        version: '1.3.0',
        
    ),
    
  ),

but it only shows what goes in the second order

**Comment by JaffaKetchup** [comment]
Try setting the `backgroundColor` of the WMS layer to be transparent. You may need to play around with the ordering to get it right as well, after this.

**Comment by drgo190** [comment]
thank you very much @JaffaKetchup , that solved the problem

**Comment by m-hamza-tanbits** [comment]
@drgo190 Can you share a source code of WMS layer.
I want to implement this layer in flutter_map. 
**https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015**
this is tile url. can you please guide on it.

<img width="1435" alt="Screenshot 2024-01-15 at 12 39 16 PM" src="https://github.com/fleaflet/flutter_map/assets/153491287/b805bde4-2bbe-4cfe-9688-ec8fdc996c84">
