### ISSUE TITLE
[FEATURE]  Markers don't have some unique id or anything by which we can search and perform action

### ISSUE THREAD

**Issue by arslankaleem7229** [fleaflet/flutter_map#1349]
### What do you want implemented?

I want to increase the marker size from List<Marker>. Now I know there is nothing by which I can search and perform an action on a marker

### Can you provide any other information?

I am using ListView of all locations now. When I scroll, I want the top location's marker to zoom in.

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
@arslankaleem7229 Hi there,

You should be able to do this fairly simply yourself. Use a `Map<LatLng, Size>`, then use `.map()` to generate a list of `Marker`s from it.
The location is the `LatLng`, and you can process the `Size` however you want.
To update a marker, just refer to its location, and change the size. Make sure to refresh the state!

Note that this may be expensive for large amounts of markers (more so <v3), but this is a good starting point for you to implement your own solution from.

Let me know if this works for you!

**Comment by JaffaKetchup** [comment]
Ok, I'm going to close this. I think the above should work for you :)
Happy to help you more if you need it!

**Comment by blablabla123-cell** [comment]
The same issue, I get a list of markers from the backend (each marker has its id) and I'd like to get a marker's id from the Popup builder for example:
popupBuilder: (context, marker) {
 Navigator.pushNamed('/event', args: marker.id);
}
and there is no way to attach an id, so I could obtain it in popup right away((

**Comment by JaffaKetchup** [comment]
@blablabla123-cell Please try https://github.com/fleaflet/flutter_map/issues/1349#issuecomment-1230216105

**Comment by blablabla123-cell** [comment]
> @blablabla123-cell Please try [#1349 (comment)](https://github.com/fleaflet/flutter_map/issues/1349#issuecomment-1230216105)

Can u please help in my case? I am new in flutter. 
I created a class that extends Marker and add's up an id and a point

**Comment by JaffaKetchup** [comment]
@blablabla123-cell I don't want to write code for you, that's not what we're here for.
Use a `Map<LatLng, String>` where `String` is the new page's route (for `pushNamed`). Then, build a `List<Marker>` from this by using `.entries.map((latlng, route) => Marker()).toList()` on the `Map`. There are likely more efficient ways to do this, but this should be OK for most use cases.

**Comment by blablabla123-cell** [comment]
Thank you for help, then!
