### ISSUE TITLE
[BUG] TileLayer Reset example broken on master

### ISSUE THREAD

**Issue by JosefWN** [fleaflet/flutter_map#1360]
### What is the bug?

The example breaks on reset.

### What is the expected behaviour?

The example works on reset.

### How can we reproduce this issue?

Press reset, screen goes blank. See logs:

```
ImageCodecException: Failed to load network image.
Image URL: http://.tile.openstreetmap.fr/hot/5/13/9.png
Trying to load an image from another domain? Find answers at:
https://flutter.dev/docs/development/platform-integration/web-images
```

### Platforms Affected

Web

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @JosefWN,
Can you clarify that this only occurs on the web, or is that just the only platform you tested on?
Thanks :)

**Comment by JaffaKetchup** [comment]
PS. If you are interested in becoming a maintainer, please do get in touch either on Discord (where I'll grant you the Awesome Person role if you join, purely because you've found so many issues), or fill out the form: see https://github.com/fleaflet/flutter_map/issues/1326.

**Comment by JosefWN** [comment]
I only tried it on web, tried on an iOS emulator now and it seems to be the same thing there:
```
flutter: SocketException: Failed host lookup: '.tile.openstreetmap.fr' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: SocketException: Failed host lookup: '.tile.openstreetmap.fr' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: SocketException: Failed host lookup: '.tile.openstreetmap.fr' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: SocketException: Failed host lookup: '.tile.openstreetmap.fr' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: SocketException: Failed host lookup: '.tile.openstreetmap.fr' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: SocketException: Failed host lookup: '.tile.openstreetmap.fr' (OS Error: nodename nor servname provided, or not known, errno = 8)
```

**Comment by JosefWN** [comment]
> If you are interested in becoming a maintainer, please do get in touch either on Discord (where I'll grant you the Awesome Person role if you join, purely because you've found so many issues), or fill out the form: see https://github.com/fleaflet/flutter_map/issues/1326.

Thanks a lot for the invitation! 😄 I'm really busy with work right now, but maybe in the future when things have settled down a bit!

**Comment by JaffaKetchup** [comment]
I'm assuming the subdomain processor has broken - it probably doesn't like that leading '.'.

**Comment by TesteurManiak** [comment]
I think you forgot to precise the `subdomains` to use, the following code has been working for me on MacOS, iOS & Web platforms:

```dart
TileLayer(
  urlTemplate: 'http://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png',
  userAgentPackageName: 'dev.fleaflet.flutter_map.example',
  subdomains: const ['a', 'b', 'c'],
),
```

**Comment by JaffaKetchup** [comment]
@JosefWN I know you're busy at the moment so don't worry to much, but can you try @TesteurManiak's suggestion when you get a moment. Thanks.
