### ISSUE TITLE
[BUG] Can't do any interaction on the map if I pass bounds param

### ISSUE THREAD

**Issue by tijee** [fleaflet/flutter_map#1362]
### What is the bug?

If I pass `bounds` to my FlutterMap, I cannot move or zoom anymore. If I remove the `bounds` (and pass a `center` for example) I can move, zoom, rotate, as normal.

### What is the expected behaviour?

I would expect to be able to move or zoom in the map even when passing an initial `bounds`.

### How can we reproduce this issue?

```dart
FlutterMap(
          options: MapOptions(
            bounds: LatLngBounds.fromPoints([......]),
            minZoom: 0,
            maxZoom: 18,
          ),
          children: [
            TileLayer(
              urlTemplate:
                  'https://api.maptiler.com/maps/basic-v2/{z}/{x}/{y}.png?key=......',
            ),
          ],
)
```

### Do you have a potential solution?

Pass a `center` instead of the `bounds` but I would also need to calculate the default `zoom` level matching the bounds I want.

### Platforms Affected

Android

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by muhammadSaqib7860** [comment]
I have facing the same issue , any solution.

**Comment by JaffaKetchup** [comment]
Thanks for the heads up! We'll look into this.

**Comment by muhammadSaqib7860** [comment]
Kindly resolve it asap, I have a deadline so need to finish it asap.

**Comment by ibrierley** [comment]
If you're desperate, revert to < 3.0.0 assuming thats ok

**Comment by JaffaKetchup** [comment]
@muhammadSaqib7860

Many of us maintainers have jobs as well or things to do other than this, so please be patient!

In the meantime, please send a minimal reproducible example and a screen recording of it. This will allow us to verify this issue and assign it high priority.

**Comment by muhammadSaqib7860** [comment]
Container(
              width: double.infinity,
              height: double.infinity,
              child: FlutterMap(
                mapController: mapController,
                options: MapOptions(
                  bounds: LatLngBounds(
                      latLng.LatLng(
                        52.874385,
                        5.773051,
                      ),
                      latLng.LatLng(
                        51.849942,
                        3.903331,
                      )),
                  boundsOptions: FitBoundsOptions(padding: EdgeInsets.all(100.0)),
                  interactiveFlags: InteractiveFlag.pinchZoom | InteractiveFlag.drag,
                  onTap: (_, __) => _popupLayerController.hideAllPopups(),
                ),
                children: [
                  TileLayer(
                    urlTemplate: "https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/"
                        "{z}/{x}/{y}?access_token=-----------",
                  ),
                  PopupMarkerLayerWidget(
                    options: PopupMarkerLayerOptions(
                      popupController: _popupLayerController,
                      markers: _provider.mMarkersList,
                      markerRotateAlignment: PopupMarkerLayerOptions.rotationAlignmentFor(AnchorAlign.top),
                      popupBuilder: (BuildContext context, Marker marker) {
                        int index = _provider.mMarkersList.indexOf(marker);
                        return ExamplePopup(
                          _provider.mEntrepreneurData.data![index],
                          closePopup: () {
                            _popupLayerController.hideAllPopups();
                          },
                        );
                      },
                    ),
                  ),
                ],
              ),
            )

**Comment by muhammadSaqib7860** [comment]
@JaffaKetchup if I move to the old version then Marker did not appear on the leaflet map. that's why I'm stuck.

**Comment by JaffaKetchup** [comment]
Sorry, but I didn't understand that last comment.

Can you try the example given by the author of this issue in the PR body and check whether that works for you? In future, that's a minimal reproducible example - it has no external dependencies and is short.

Please give us time to look into this, we appreciate you have a deadline to meet.

**Comment by tijee** [comment]
Edit: looks like it is because of the MarkerLayer, so the code to reproduce would be:

```
FlutterMap(
          options: MapOptions(
            bounds: LatLngBounds.fromPoints([LatLng(45.0, 2.0)]),
            minZoom: 0,
            maxZoom: 18,
          ),
          children: [
            TileLayer(
              urlTemplate:
                  'https://api.maptiler.com/maps/basic-v2/{z}/{x}/{y}.png?key=......',
            ),
            MarkerLayer(
              markers: [
                Marker(point: LatLng(45.0, 2.0), builder: (_) => FlutterLogo())
              ],
            ),
          ],
)
```

**Comment by stx** [comment]
Yeah, this bug was introduced as part of the 3.0.0 refactor. I reported it a few times in the Discord. Setting bounds removes interactivity.

Unfortunately calculating your own zoom and center (like through controller.getZoomCenter) isn't possible until the map loads, so there is an ugly frame flicker. Bounds needs to work the way it did previously; there's simply no other way to get the map to load on a certain view otherwise, as far as I can tell.

**Comment by ibrierley** [comment]
I suspect fitBounds or similar is run every build now, rather than initState (just loosely trying to guess how it runs). Need to double check, and it may be a case of removing this..Bounds has always been a bit annoying and probably should get renamed one day, to initialBounds or something.

**Comment by stx** [comment]
Yeah, initialBounds is good.

**Comment by JaffaKetchup** [comment]
Marked as high-priority.

**Comment by ibrierley** [comment]
It would be useful if anyone having the bounds limiting drag issue could test https://github.com/fleaflet/flutter_map/pull/1369

**Comment by stx** [comment]
@ibrierley @JaffaKetchup This fix makes the bounds function correctly but creates a visual issue. Filed at https://github.com/fleaflet/flutter_map/issues/1375.
