### ISSUE TITLE
Smooth Moving Marker 

### ISSUE THREAD

**Issue by J3thr0-6** [fleaflet/flutter_map#1371]
Hello guys,
Currently We are able to move the markers in the map with calling setState when required. Markers are moving fine from point to another and so on.
Timer interval is one second and then markers' position are updated with new position.
The movement is there but its not smooth (its kind of jerky) as we wanted.

Is there any way that we can smooth out the movement of marker from one point to another?
Thanks

**Comment by Zzerr0r** [comment]
You're trying to move a marker over the map smoothly by changings it's position once every second?

**Comment by JaffaKetchup** [comment]
Have a look into [`TweenAnimationBuilder`](https://api.flutter.dev/flutter/widgets/TweenAnimationBuilder-class.html). Then have two tweens, one for latitude, one for longitude. The video on the page I linked should help you figure it out.
This is probably out of scope for now, but thanks for the suggestion! If you need more help, please ask on the Discord server.

**Comment by J3thr0-6** [comment]
> You're trying to move a marker over the map smoothly by changings it's position once every second?
Yes,
Actually Multiple markers

**Comment by J3thr0-6** [comment]
> Have a look into [`TweenAnimationBuilder`](https://api.flutter.dev/flutter/widgets/TweenAnimationBuilder-class.html). Then have two tweens, one for latitude, one for longitude. The video on the page I linked should help you figure it out. This is probably out of scope for now, but thanks for the suggestion! If you need more help, please ask on the Discord server.

Okay thanks
