### ISSUE TITLE
[FEATURE] Improved attribution

### ISSUE THREAD

**Issue by ianthetechie** [fleaflet/flutter_map#1379]
### What do you want implemented?

I have a number of suggestions for how to improve attributions, and would be happy to contribute code.

* Allow multiple attribution sources. Right now it's just kinda one with a widget builder, but the helper functions could be a lot more interesting IMO.
* Make attribution collapse on small screens. This is a huge problem right now IMO. The next logical step once we have the above default builder is to allow it to collapse on small screens and pop up a list or something (need to do a bit of research the best way to do this in Flutter but I'm sure it's possible).
* Option to pass a URL rather than a tap handler. This is really what 99% of people want anyways. I'm not sure if you're OK with another dependency, but url_launcher is what I use. Just making this part of the builder helpers would make things SO much cleaner. As a bonus, attribution to flutter_map would be a hyperlink rather than just text ;)

Let me know if you have any thoughts/objections, but I have already implemented most of the first and last items locally.

### What other alternatives are available?

Yeah, just doing a bunch of boilerplate myself for some of them. There actually isn't a proper way to attribute multiple sources at this point correctly since you only have one tap handler (ok sure pop up a selection box but that's SUPER clunky).

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @ianthetechie.
I originally made the attribution system, and at the time, it was just a quick thing to replace some older APIs. It definitely needs changing.
I'll look into this, and attach a PR when it's ready.
Note that this will be breaking, so I'll have to merge into ['delayed-breaking-changes'](https://github.com/fleaflet/flutter_map/tree/delayed-breaking-changes) until we're ready to release a bigger version.

**Comment by JaffaKetchup** [comment]
This issue now has a discussion channel on the Discord server. To participate, please join via the link in the README: everyone is welcome :).
