### ISSUE TITLE
[BUG] WMS layer failed to load on flutter-map

### ISSUE THREAD

**Issue by sohagmahin** [fleaflet/flutter_map#1383]
### What is the bug?

Getting an error, When I was trying to load the WMS layer from GeoServer. It was work since `flutter_map: ^0.14.0` . 
Today, I update the flutter_map package to  `flutter_map: ^3.0.0` and it's broken. Thrown an error `Exception: Invalid image data` . And alongside I used Mapbox for styling the map, and Mapbox works great.

### What is the expected behaviour?

It should load the WMS layer.

### How can we reproduce this issue?

```dart
FlutterMap(
                      mapController: _mapController,
                      options: MapOptions(
                        center: LatLng(51.165691, 10.451526),
                        zoom: 6,
                        interactiveFlags: ~InteractiveFlag.rotate,
                      ),
                      children: [
                        //Mapbox URL that represents the map style for the radar screen
                        TileLayer(
                          urlTemplate:
                              "https://api.mapbox.com/styles/v1/spektergmbh/cl8ec8kg30****ijjpa6cq/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1Ijoic3Bla3Rlcmdt****J9.jpamQ8Yl4Wr-xisbkw1a1A",
                          additionalOptions: {
                            'accessToken':
                                'pk.eyJ1Ijoic3Bla3RlcmdtYmg***',
                            'id': 'mapbox.streets',
                          },
                        ),
                        TileLayer(
                            opacity: _opacity,
                            backgroundColor: new Color.fromRGBO(0, 0, 0, 0),
                            wmsOptions: WMSTileLayerOptions(
                              baseUrl:
                                  'https://***/geoserver/dwd/wms?time=' +
                                      _timeFrames[_count],
                              layers: ['dwd:WN-SKT'],
                              version: '1.1.1',
                              transparent: true,
                              format: 'image/png',
                            )),
                        MarkerLayer(
                          markers: _markers.length != 0 ? _markers : [],
                        ),
                      ]),
```

### Do you have a potential solution?

No.

### Can you provide any other information?

thrown error: 

```
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:5886:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5741:12)
#2      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2092:60)
#3      PaintingBinding.instantiateImageCodecFromBuffer (package:flutter/src/painting/binding.dart:153:15)
#4      FMNetworkNoRetryImageProvider._loadAsync (package:flutter_map/src/layer/tile_layer/tile_provider/network_no_retry_image_provider.dart:89:20)
<asynchronous suspension>
Image provider: FMNetworkNoRetryImageProvider()
Image key: FMNetworkNoRetryImageProvider()
====================================================================================================
```

### Platforms Affected

Android, iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
Is it possible to try and debug what the full URL is thats being called, and then see if you can actually retrieve that URL in your browser.

**Comment by sohagmahin** [comment]
Yes. the URL works fine in the browser. 
![Screenshot 2022-10-12 at 12 52 44 PM](https://user-images.githubusercontent.com/35423413/195271155-606db670-ca85-45cb-9ec6-c90cbdc0a5f3.png)

# flutter_dev tool (Network inspection)
![Screenshot 2022-10-12 at 12 51 09 PM](https://user-images.githubusercontent.com/35423413/195271272-5d65dd02-5202-455e-90c8-b0ec2f813eca.png)

**Comment by arsyadnimbly** [comment]
Same issue, any update?

![image](https://user-images.githubusercontent.com/109497576/197158225-24b9b66b-2957-4b08-8c84-4baf140992e1.png)

**Comment by JaffaKetchup** [comment]
Hi @sohagmahin & @arsyadnimbly.
Unfortunately, this will be a Flutter issue AFAIK, as images are handled by them in the end - we do have a custom image provider, but it all leads back to Flutter. I'm assuming that the image is a little corrupted/malformed/wrong format - see [this Flutter docs page](https://api.flutter.dev/flutter/widgets/Image-class.html#:~:text=The%20following%20image%20formats%20are,supported%20by%20the%20underlying%20platform).

**Comment by JaffaKetchup** [comment]
Just reread the original issue. It is a little strange that this worked previously: that would suggest an issue with our/my image provider implementation. I'm not sure why it would not support certain formats, but that might be it. I'll leave this open for now, and investigate when I get time. Thanks for the report!

**Comment by JaffaKetchup** [comment]
@sohagmahin @arsyadnimbly
As a temporary fix, can you please try following [this guide to make your own `TileProvider`](https://docs.fleaflet.dev/plugins/making-a-plugin/creating-new-tile-providers), and using a standard `NetworkImage` instead of a custom image provider. If you can do this, please let me know how it goes, it would be a great help :)

**Comment by sohagmahin** [comment]
Thanks for your temporary fix. I will try and let you know.
