### ISSUE TITLE
[FEATURE] Support different OSM layers

### ISSUE THREAD

**Issue by xyzbilal** [fleaflet/flutter_map#1384]
### What do you want implemented?

I want implement different layers like in website. 
is that possiple to send layer type parameter in url  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png' 

### What other alternatives are available?

in website we can add parameter like in  this link
https://www.openstreetmap.org/#map=16/41.0752/28.9340&layers=H 

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by TesteurManiak** [comment]
I don't understand your issue, nothing stops you from changing the url to adapt to your needs. As I see things you could use the following template for your url: `https://www.openstreetmap.org/#map={z}/{x}/{y}&layers=H` (Note that for the tile layer to work the url should return an image)

Could you please provide some pseudo code of what you want to do ?

**Comment by xyzbilal** [comment]
Thank you for quick answer.  sorry if I couldnt be clear.  I tried these url schemes but I get errors
such` flutter: HTTP request failed, statusCode: 400, https://b.tile.openstreetmap.org/8/150/97&layers=H ` or `flutter: Exception: Invalid image data` because of that I created this requests.

**Comment by ibrierley** [comment]
Yes, I think the layer you are after is a french "hot", one, so would be "https://b.tile.openstreetmap.fr/hot/8/150/97.png" as an example. Looks like you already have a handle on that now.
