### ISSUE TITLE
[FEATURE] new AttributionWidget without default text

### ISSUE THREAD

**Issue by Friendly-Banana** [fleaflet/flutter_map#1392]
### What do you want implemented?

I would like a new constructor for `AttributionWidget` where I can control all of the text. Adding 'flutter_map | © ' makes 1.) the attribution box quite big and 2.) the different styles of text don't match nicely.
Implementation: new named constructor like `AttributionWidget.customText` that doesn't add 'flutter_map | © '

### What other alternatives are available?

provide an `attributionBuilder` to `AttributionWidget`s normal constructor building the widget yourself

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Minimum: Not required for my use

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @Friendly-Banana,
You can construct a custom `AttributionWidget` by using it alone, without `AttributionWidget.defaultWidget`. See the screenshot:
![image](https://user-images.githubusercontent.com/58115698/198725849-5d93667f-9b18-40f3-b63a-360b002a9fa8.png)

Thanks for the issue!
