### ISSUE TITLE
[FEATURE] Prevent rotation alongside pinch zoom gestures

### ISSUE THREAD

**Issue by ARASHz4** [fleaflet/flutter_map#1396]
_Edit from maintainer: This was originally a bug report, but is more of a feature request/enhancement than a bug, as explained by https://github.com/fleaflet/flutter_map/issues/1396#issuecomment-1302687850._

### What is the bug?

When zooming in phone with two fingers rotate happening

### What is the expected behaviour?

When zooming don't rotate map 

### Platforms Affected

Android, iOS, Web

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
Try InteractiveFlag.all & ~InteractiveFlag.rotate in your mapoptions

**Comment by ARASHz4** [comment]
> Try InteractiveFlag.all & ~InteractiveFlag.rotate in your mapoptions

Its work but i can't rotate any more
i want disable rotate only when in pinch zooming

**Comment by JaffaKetchup** [comment]
The issue is differentiating between a zoom and a rotation. Pinch zooms almost always have a natural rotation factor (due to the tiny amount of movement of users' fingers), so this is quite difficult.

Maybe one of the 'threshold's or 'win factor's inside `MapOptions` could help you. See https://pub.dev/documentation/flutter_map/latest/flutter_map/MapOptions-class.html.

**Comment by rs-linhlc** [comment]
Same problem. At the moment I have to disable rotate completely. Hope team can implement this feature soon.

**Comment by rs-huypq** [comment]
@ARASHz4 
Try this, it might solve your problem
```
FlutterMap(
    options: MapOptions(
        enableMultiFingerGestureRace: true,
    )
)
```

**Comment by rs-anhnq2** [comment]
> @ARASHz4 Try this, it might solve your problem
> 
> ```
> FlutterMap(
>     options: MapOptions(
>         enableMultiFingerGestureRace: true,
>     )
> )
> ```

work like magic! =))

**Comment by JaffaKetchup** [comment]
Thanks @rs-huypq.
