### ISSUE TITLE
Map doesn't load when internet connection is setup at runtime.

### ISSUE THREAD

**Issue by Max053** [fleaflet/flutter_map#14]
The map doesn't load when an internet connection is setup at runtime. It only starts loading after you start zooming in or out.

Steps to reproduce:
1. Start the application without internet.
2. Enable wifi or mobile internet.
3. Observe
4. Zoom in or out.

**Comment by johnpryan** [comment]
I think the best solution here is to add a Controller widget (see https://github.com/apptreesoftware/flutter_map/issues/10) - that way, users can use a package like [connectivity](https://pub.dartlang.org/packages/connectivity) to detect when they are offline and call `forceRefresh` on the map controller

Let me know what you think, or if you have any other ideas!

**Comment by Max053** [comment]
The controller by itself is a good idea, but I think it would be better if the internet connectivity check is done within the plugin. We could add an option to disable this check. (for example, if you are serving local files)

**Comment by Max053** [comment]
I have thought about it last day, and I think it should be expected behaviour of the map to automatically (re)load the map when an internet connection is setup.

I have been working on an solution in an own branch. You can see the difference with the main branch here: https://github.com/apptreesoftware/flutter_map/compare/master...Max053:load_map_on_connectivity.

Basically, I've made sure the tile layers only get loaded when an internet connection is detected. It doesn't matter if there was already a connection when the app started, or if it was connected at runtime. We could maybe add a setting to only allow the map to load on wifi or mobile connection.

The only downside here, is that there will be a little extra configuration in gradle for now. You would have to change `gradle.properties` and `build.gradle` which can be seen in the diff.

I've tested this on android and it seems to work fine. I can't test this on iOS myself though.

Please let me know what you think!

**Comment by ruizalexandre** [comment]
Solution can be to rebuild only tile layer on demand !
