### ISSUE TITLE
[BUG] fluttermap, visibility, late initialization error 

### ISSUE THREAD

**Issue by tomquas** [fleaflet/flutter_map#1400]
### What is the bug?

if i put a Visibility child with access to the map controller in FlutterMap like this:

```
FlutterMap(
  mapController: mapController,
  options: MapOptions( ... )
  children: [
   TileLayer(...),
    Visibility(
      visible: mapController.zoom < 7, // !!!!!
      child: MarkerLayer(markers: populatedCitiesMarkers)
    ),
]
```

i get the following error:

```

The relevant error-causing widget was
MapView-[LabeledGlobalKey<MapViewState>#33e8d]
lib/…/map/population_map.dart:51
When the exception was thrown, this was the stack
#0      MapControllerImpl._state (package:flutter_map/src/map/map.dart)
package:flutter_map/…/map/map.dart:1
#1      MapControllerImpl.zoom
package:flutter_map/…/map/map.dart:67
#2      MapViewState.build
package:u2nite/widgets/map_view.dart:128
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4992
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4878
#5      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:5050
#6      Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#7      ComponentElement._firstBuild
package:flutter/…/widgets/framework.dart:4859
#8      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:5041
#9      ComponentElement.mount
```

### What is the expected behaviour?

i'd expect the mapController to be fully initialized when building the views.

### How can we reproduce this issue?

```dart
see above.
```

### Platforms Affected

Android

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by tomquas** [comment]
fwiw, while using existing Visibility would be my preferred solution, a working workaround seems to be to use the plugin api:
```
class PopulatedCitiesMarkerLayer extends StatelessWidget {
  const PopulatedCitiesMarkerLayer({
    this.minZoom = 0,
    this.maxZoom = 7,
    this.markers = const [],
    super.key,
  });

  final int minZoom;
  final int maxZoom;
  final List<Marker> markers;

  @override
  Widget build(BuildContext context) {
    final map = FlutterMapState.maybeOf(context)!;
    if (map.zoom <= minZoom || map.zoom > maxZoom) {
      return Container();
    }

    return MarkerLayer(markers: markers);
  }
}
```

**Comment by MooNag** [comment]
I think using the plug in API is the cleanest solution. You can also use visibility and backstage widgets there too.

If you dislike having an extra custom widget you can probably use a builder and grab the map state like in the plug in which should work too.

**Comment by JaffaKetchup** [comment]
As @MooNag suggested, I'm not surprised this doesn't work. As far as I know, the `MapController` is initialised after all children have built themselves, so it won't be available during build - although a bit of a weird exception if that was the case.
For now, we probably won't change this, as the method you already found is quite simple and makes sense. And as @MooNag also said, you may just be able to wrap the `MarkerLayer` in a `Builder`.

**Comment by tomquas** [comment]
thanks for the hints. my final take on this:
```
import 'package:flutter/widgets.dart';
import 'package:flutter_map/plugin_api.dart';

class MapZoomConstrainedBuilder extends StatelessWidget {
  const MapZoomConstrainedBuilder({
    required this.minZoom,
    required this.maxZoom,
    required this.child,
    super.key,
  });

  final int minZoom;
  final int maxZoom;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final map = FlutterMapState.maybeOf(context)!;
    return Visibility(
      visible: (minZoom <= map.zoom && map.zoom <= maxZoom),
      child: child
    );
  }
}
```

example:
```
MapZoomConstrainedBuilder(
  minZoom: 0,
  maxZoom: 7,
  child: MarkerLayer(markers: markers));
```
