### ISSUE TITLE
Set a Key for every Polygon

### ISSUE THREAD

**Issue by AliEasy** [fleaflet/flutter_map#1401]
### What do you want implemented?

Hi
I need to add a `Key` to each polygon to manage them, sth like `key: Key('p-$polygonId')` for `Marker`

Thanks in advance

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
I think this would make sense for those layers with lists (polyline, polygon etc). Pull requests welcome!
