### ISSUE TITLE
Is the max zoom just 18.0?

### ISSUE THREAD

**Issue by desmeit** [fleaflet/flutter_map#1406]
### What is the bug?

I cannot zoom more than 18.0. If I take 19.0 I get a grey page.

### What is the expected behaviour?

I want to zoom for example to 25.0

### Platforms Affected

Android, iOS

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
The problem is more likely that your tile provider doesn't provide tiles at that level. Which tile provider are you using ?

**Comment by desmeit** [comment]
I tried with Thunderforest.

**Comment by ibrierley** [comment]
Well, you can try setting maxZoom higher, Thunderforest can go higher (it may depend on your account, not sure). Have you set your maxZoom in your TileLayer ?

**Comment by TesteurManiak** [comment]
> Is MapTiler not working?
> 
> https://api.maptiler.com/maps/basic-v2/style.json?key=XXX
> 
> responds to
> 
> `Exception: Invalid image data`

It's because you are using a styling for a vectorial map, on MapTiler you need to use rasterized tiles.
