### ISSUE TITLE
[BUG] Transparency not applicable

### ISSUE THREAD

**Issue by RegalFenster** [fleaflet/flutter_map#1407]
### What is the bug?

Hi,
for some reason, I'm unable to set the transparency of the wms tile layer.
There is a similar issue: https://github.com/fleaflet/flutter_map/issues/1281
But changing the backgroundColor to transparent didn't resolve the problem.

### What is the expected behaviour?

Layer should be transparent

### How can we reproduce this issue?

```dart
FlutterMap(
        options: MapOptions(
          center: LatLng(51.5, -0.09),
          zoom: 13.0,
        ),
        nonRotatedChildren: [
          AttributionWidget.defaultWidget(
            source: 'OpenStreetMap contributors',
          ),
        ],
        children: [
          TileLayer(
            urlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
            userAgentPackageName: 'com.example.app',
          ),
          TileLayer(
            wmsOptions: WMSTileLayerOptions(
                baseUrl: "https://geo.weather.gc.ca/geomet?",
                layers: ["GDPS.ETA_TT"],
                version: '1.3.0',
                transparent: true),
            backgroundColor: Colors.transparent,
          ),
        ],
      )
```

### Can you provide any other information?

![image](https://user-images.githubusercontent.com/48275164/202856071-25d1662b-230d-4c3e-9e71-96ae5b85e49a.png)
![image](https://user-images.githubusercontent.com/48275164/202862264-ab219e57-05cd-4f0e-8e21-d8aee369f799.png)

### Platforms Affected

Windows

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
I guess the first obvious question is, what's the yellow stuff? :). Are you sure the WMS tile isn't just providing that from the server ?

**Comment by RegalFenster** [comment]
It looks like this, when zoomed out:
![image](https://user-images.githubusercontent.com/48275164/202862201-c35b1f35-7185-4602-b3a4-dac96c6bbfec.png)

**Comment by RegalFenster** [comment]
I updated the issue

**Comment by ibrierley** [comment]
So, I may be being dumb here, but as the whole weather world/layer is full of colour, why would transparent work, there's no transparency there ?

**Comment by JaffaKetchup** [comment]
Hi @RegalFenster, I think you might be getting confused. My mistake if I'm misunderstanding you!

`backgroundColor` sets the color behind any transparent areas of the map (of which there aren't any on this map). If you're trying to set the opacity of the entire layer, perhaps to overlay it on top of another layer, set the `opacity` property instead.

_(Not sure if you're trying to do this or not, but to toggle the layer, toggle the `TileLayer` itself: don't use 0 opacity)_

**Comment by RegalFenster** [comment]
I was confused indeed. Changing the opacity is what I actually wanted. Thanks a lot!
