### ISSUE TITLE
[BUG]  how to set selected color marker

### ISSUE THREAD

**Issue by MrLongg71** [fleaflet/flutter_map#1409]
### What is the bug?

I think it very stupid marker, it don't markerId?

i need to set marker selected with item Id.

<img width="681" alt="Screen Shot 2022-11-22 at 10 03 43 PM" src="https://user-images.githubusercontent.com/41661101/203348125-06300987-d8c0-495b-b3d3-d684e3a2a9da.png">

### What is the expected behaviour?

set color selected

### Platforms Affected

Android, iOS

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
It's not very clear what you are after here. I have some thoughts, you could probably use a closure for the marker or something like a cast, but needs a bit further info. I don't see it as a bug though, more a desired feature.

**Comment by ibrierley** [comment]
I'm going to close this, as it's not clear and not very constructive, and I suspect there are ways to make it work already. Happy to reopen if there's more info, or still having an issue.
