### ISSUE TITLE
[BUG] bounds set in MapOptions are sometimes ignored

### ISSUE THREAD

**Issue by felix-ht** [fleaflet/flutter_map#1412]
### What is the bug?

If i define bounds in MapOptions these are sometimes ignored - and the map shows the full world map. If i have any interaction with the map (even with disabled interactions) the zoom seems to fix itself.

```dart
options: MapOptions(
        bounds: bounds,
),
```

https://user-images.githubusercontent.com/24698503/205641417-77d82c62-b256-4711-b45e-54ac4e9ed602.mov

### What is the expected behaviour?

The map is zoomed to the bounds.

### How can we reproduce this issue?

```dart
import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter_map/plugin_api.dart';
import 'package:latlong2/latlong.dart';

class ExampleMap extends StatelessWidget {
  const ExampleMap({super.key});

  @override
  Widget build(BuildContext context) {
    final bounds = LatLngBounds(LatLng(51.6, 12.6), LatLng(53.4, 14.4));
    return FlutterMap(
      options: MapOptions(
        interactiveFlags: InteractiveFlag.none,
        bounds: bounds,
      ),
      nonRotatedChildren: [
        AttributionWidget.defaultWidget(
          source: 'OpenStreetMap contributors',
          onSourceTapped: null,
        ),
      ],
      children: [
        TileLayer(
          urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
          userAgentPackageName: 'com.example.app',
        ),
      ],
    );
  }
}
```

### Can you provide any other information?

Workaround is to set

```
   onMapReady: () {
          controller.fitBounds(bounds);
        },
```

### Platforms Affected

MacOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Once: Occurred on a single occasion

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
I can confirm this...I noticed this the other day with a report of bounds not working (preventing dragging), but sometimes would display zoom 0.

Discord:

> I thought there was a fix for this, just checking https://github.com/fleaflet/flutter_map/pull/1369/files#
> But there's something still buggy going on somewhere, I can't quickly see but firstly make sure you are using the latest version from Git,  that may help fix it...but then I think there's still something odd going on with fitbounds, but  haven't got time to debug atm
> it feels like now sometimes it doesnt fit to bounds at all, so I would raise an issue on Git, and also reference that change (out of interest, you could switch that PR exactly and test to see if your code works with it just to isolate)
> (my suspicion would be the main problem was fixed, but maybe the fitbounds gets called too early, although I think that was taken into account)

So, originally there was a addPostFrameCallback in there, to call fitBound() after it has a correct size calculated...maybe some other code introduced as meant that this is no longer good enough, and needs further to wait. I note in Web, this works fine, and I suspect that's because typically there are more tiles to display and its a bit slower.

**Comment by ibrierley** [comment]
It looks like it was the code from this https://github.com/fleaflet/flutter_map/commit/4276a91cf1c81e9ebc1a7bba86eae61a2b94cee7 which is weird, as I'm sure we tested this (but maybe we only tested it on web which does works?). So it looks like the original problem is still there or back. Cue trying to fix that, for flickering to return!

**Comment by ibrierley** [comment]
Possible fix at https://github.com/fleaflet/flutter_map/pull/1413 please test thoroughly everyone who uses bounds, as it can be hard to replicate this problem and the initial flashing problem, as it can depend on device :)

**Comment by felix-ht** [comment]
@ibrierley the PR seems to have fixed the issues 👍
