### ISSUE TITLE
Export map to png at certain scale

### ISSUE THREAD

**Issue by kttary** [fleaflet/flutter_map#1415]
### What do you want implemented?

Following a javascript mapping framework, it allow us to export or [compose map at certain scale](https://openlayers.org/en/latest/examples/print-to-scale.html). Does flutter map has this functionality or perhaps any chance to be considered as a feature?  

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Minimum: Not required for my use

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
No, it doesn't have this functionality, it feels pretty niche (but maybe I'm wrong), so I'm going to close this, but I'm happy to reopen if others would find it useful or someone wants to do a pull request for it.

**Comment by JaffaKetchup** [comment]
A few other people have used the '[screenshot](https://pub.dev/packages/screenshot)' package, with varying levels of success.
