### ISSUE TITLE
[BUG] Map is slow rendering when Polyline with many points is displayed

### ISSUE THREAD

**Issue by omerhertz** [fleaflet/flutter_map#1417]
### What is the bug?

When my Flutter app displays a "dense" Polyline, and the user is moving the map, the map suffers from delays and the user is facing "hiccups" in the map movements (i.e. some of the frames are skipped). 
This also affects the rest of the app. Clicking on the floating action button, for example, has a second / 1.5 second delay. This delay doesn't occur when less dense polygons appear on the map.
I tried both polylineCulling == true and polylineCulling == false. I didn't notice any change.

### What is the expected behaviour?

Smooth map movement

### How can we reproduce this issue?

```dart
Load a dense polyline to any map, and try to move it.
The problem almost doesn't occur in the Emulator. I see it on Android devices
```

### Do you have a potential solution?

I can reduce the number of points, but this will be reduce the app value.
In addition, I am adding points to the Polyline dynamically. Maybe loading them from a GeoJson might help?
I don't know enough about Flutter Map to suggest performance improvements

### Can you provide any other information?

I am also using the FlutterMapTileCaching package. I removed it and the problem still occurs.

### Platforms Affected

Android

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Often: Occurs more often than when it doesn't

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
Do you have a test example at all, would be handy to have something to look at and test to see if there's much to be done.

There are some known issues in general with flutter and a lot of lines that are over 1 pixel wide (could try reducing to less than that for the strokewidth just for extra purposes of isolating the problem.

**Comment by ibrierley** [comment]
It's also worth noting how many points overall there are in the polylines when its slow

**Comment by omerhertz** [comment]
@ibrierley I used 7 pixels strokewidth. Reducing it to 1 pixel did help. Actually it is a hugh difference. It runs almost fluent now. 
I can't really upload a working example, as it is just a part of my app.

**Comment by ibrierley** [comment]
There would be a reduction in processing anyway with less to paint I guess, but still useful to know. How many points in those polys ?

**Comment by omerhertz** [comment]
@ibrierley Added some counter to the loaded points. In this problematic area, there are 16.5K points in the Polyline. And 15K (almost all) are in the displayed area

**Comment by ibrierley** [comment]
Ah yeah, that's a lot of points :D I don't think you will achieve much with the normal flutter_map code with that many points. 

If you fancy experimenting and giving some feedback https://github.com/ibrierley/geojson_vector_slicer is a plugin I was playing with to get around that kind of problem. I'd be interested if it could cope.

It can do geojson if you have that, line simplification if its at a small zoom (as it would be too small to see anyway) and slices into tiles and stuff..it can also do polyline click detection.

You'd want to look at GeoJSONWidget() with lineStringFunc and lineStringStyle looking at the example on the readme and https://github.com/ibrierley/geojson_vector_slicer/blob/main/lib/main.dart (live example of an old version at https://fluttermap.dabbles.info/vector_outline/#/ )

**Comment by JaffaKetchup** [comment]
There's also a super fast clustering plugin listed on the docs - no animation, but says it can hold up to extreme numbers.

(If there was still any doubt if my plugin could be making it worse, it doesn't interfere at all with flutter_map rendering. In fact, it only really interfaces through one point, which just tells FM how to get the tiles.)

**Comment by JaffaKetchup** [comment]
Closing this for now, as we don't have a hope of achieving this, plus it's quite a niche number of markers.
