### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ivanzhadnov** [fleaflet/flutter_map#1426]
### What is the bug?

Line between -170 and +170 degrees longitude make longitude make line without crossing 180 longitude

### What is the expected behaviour?

Line must draw from -170 to -180 after from +180 and after to +170

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Duplicate of #1338.
