### ISSUE TITLE
[BUG] [REGRESSION] TileLayer's fastReplace flag prevents rendering

### ISSUE THREAD

**Issue by pento** [fleaflet/flutter_map#1435]
### What is the bug?

This bug was introduced in flutter_map v3.1.0, v3.0.0 works as expected.

When rendering a `TileLayer`, setting the `fastReplace` flag to true prevents the layer from rendering.

### What is the expected behaviour?

The layer should render.

### How can we reproduce this issue?

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FlutterMap(
        options: MapOptions(),
        children: <Widget>[
          TileLayer(
            urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
            fastReplace: true,
          ),
        ],
      ),
    );
  }
}
```

### Platforms Affected

Android, iOS

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
@pento Sorry for the really delayed response. v4 #1475 changes this behaviour, so it has likely been fixed. Please let us know if that works for you!
