### ISSUE TITLE
[BUG] `AssetTileProvider` loading slowly after Flutter 3.7 & FM v3.1.0

### ISSUE THREAD

**Issue by WorldpixelSoftware** [fleaflet/flutter_map#1436]
### What is the bug?

After upgrading to latest stable version of Flutter (3.7.0) as of today 25.1.2023 I noticed a massive lag within the loading of offline-maps. It is literally so slow, you can even see it in the example app.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2486], locale de-DE)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.15)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

The Windows version error is a known error in the latest flutter stable, please disregard.

### What is the expected behaviour?

Load offline image assets wihtin reasonable time.

### How can we reproduce this issue?

```dart
Run the example on https://zapp.run/pub/flutter_map or your device of choice. Choose the offline example. Watch how slow it takes to update the map while zooming in and out or panning.
```

### Do you have a potential solution?

Must have something to do with the AssetImage that gets created in AssetTileProvider. There seems to be a change on the Flutter side, that makes Asset Image teribly slow.

I constructed the following workaround class to use as a TileProvider that seems to improve performance, although I cannot find out how and why exactly, since Image.asset uses AssetImage under the hood aswell.
Also I'm using the path here directly, which is originally not intended but the easiest solution for my purpose here.

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';

class WorkaroundTileProvider extends TileProvider{
  @override
  ImageProvider getImage(Coords<num> coords, TileLayer options) {
    return Image.asset(
        "assets/offline_map/${coords.z.toInt()}/${coords.x.toInt()}/${coords.y.toInt()}.png",
      width: options.tileSize,
      height: options.tileSize,
    ).image;
  }
}
```

### Platforms Affected

Android, iOS, Web, Windows, MacOS

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by TesteurManiak** [comment]
I've tested the offline example with Flutter v3.7.5 and the tile provider seems to load the tiles correctly without lag. Could you confirm that this issue remains after upgrading Flutter to its latest version ?

<details>
  <summary>flutter doctor -v</summary>
 
```bash
$>flutter doctor -v
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [version 10.0.22621.1265], locale fr-FR)
    • Flutter version 3.7.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (21 hours ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Guillaume\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.35)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1500
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22621.1265]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.105
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

**Comment by KKStudios** [comment]
@TesteurManiak Yes I can. 
Still the same Issue after upgrading to v.3.7.5.

**Comment by mchlsndrn** [comment]
I have the same exact issue here.
The workaround improves the performance drastically by an order of magnitude.

I'm using flutter_map: ^3.1.0

```
Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

```
                  // slow, unusable
                  TileLayer(
                    tileProvider: AssetTileProvider(),
                    maxZoom: maxZoom,
                    urlTemplate:
                        'assets/data/maps/style-01/map/{z}/{x}/{y}.png',
                  ),
                  // OK
                  TileLayer(
                    tileProvider: CustomTileProvider(
                        path: "assets/data/maps/style-01/map/"),
                    maxZoom: maxZoom,
                    urlTemplate: '{z}/{x}/{y}.png',
                  ),
```

**Comment by mchlsndrn** [comment]
Minor improvement: this version still works fast and also supports the 'tms' option and probably other functionality.
I'm testing in iOS Simulator with a whole world map I've built in TileMill with zooms from 0 to 8.

A minor issue which might is probably unrelated:
- Fast zoom in poses apparently no problems.
- Fast zoom out and fast panning can show some redrawing / flickering, as if the tile provider was loading the required tiles on the fly.
Is there any workaround for this other than reducing the zoom / pan speed?

```
// ...
                  TileLayer(
                    tileProvider: CustomTileProvider(),
                    maxZoom: maxZoom,
                    tms: true,
                    urlTemplate:
                        'assets/data/maps/style-01/map/{z}/{x}/{y}.png',
                  ),

class CustomTileProvider extends TileProvider {
  @override
  ImageProvider getImage(Coords<num> coords, TileLayer options) {
    return Image.asset(
      getTileUrl(coords, options),
      width: options.tileSize,
      height: options.tileSize,
    ).image;
  }
}
```

**Comment by JaffaKetchup** [comment]
Hey there, apologies for the long delay.

Just having a look at the code and timeline, this may be because of changes we made to add fallback URL support to asset providers - we implemented a custom `CachingAssetBundle` in a56b2b3/#1348 for #1203.

https://github.com/fleaflet/flutter_map/blob/a56b2b32a1b0e8519dde147ad8744a3f465bda07/lib/src/layer/tile_layer/tile_provider/asset_tile_provider.dart#L22-L48

@TesteurManiak Do you think this could be a potential reason for this?

If @WorldpixelSoftware or @mchlsndrn are still interested, can you try updating to the 'master' branch with Flutter 3.10 and Dart 3 support? Things may have changed in the meantime.

Again, apologies for the extreme delay, this one just didn't jump out at me when scrolling the issue tracker.

**Comment by TesteurManiak** [comment]
> @TesteurManiak Do you think this could be a potential reason for this?

It might be, I'll have to do some benchmark to confirm this 🤔

**Comment by TesteurManiak** [comment]
I've done some first benchmarks and the `_FlutterMapAssetBundle` was in average ~23% slower than a basic `PlatformAssetBundle` even when no fallbackUrl is used (test made on a web browser).
An improvement could be to dynamically use the "fallback asset bundle" when the `fallbackUrl` property is used and otherwise the basic asset provider (and mention in the documentation that using a fallback url will make the loading slower)

**Comment by JaffaKetchup** [comment]
@TesteurManiak Thanks, that's interesting. I think that solution is acceptable, and I'll implement it into #1532.
