### ISSUE TITLE
[BUG] Map rotation should not rotate labels

### ISSUE THREAD

**Issue by giaur500** [fleaflet/flutter_map#1439]
### What is the bug?

While rotating the map, labels rotate as well.

### What is the expected behaviour?

Labels should not rotate. Behavior should be similar as official Google Maps. When rotated, map direction is changed, but labels are still readable (not rotating with map)

### How can we reproduce this issue?

Run included sample app and rotate map.

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @giaur500.

Please read our documentation before raising issues. See https://docs.fleaflet.dev/getting-started/explanation/raster-vs-vector-tiles.
Due to limitations of the technology, we cannot support this. We do not control the tiles, and the tile technlogies do not support this. I suggest looking into vector tiles.

**Comment by rithvikhashclude** [comment]
The website that you have provided is not available anymore.

**Comment by TesteurManiak** [comment]
@rithvikhashclude try this link instead https://docs.fleaflet.dev/explanation/raster-vs-vector-tiles

**Comment by rithvikhashclude** [comment]
Thank you, Does the mentioned plugin help in preventing the labels to rotate?

**Comment by JaffaKetchup** [comment]
(Followed up in https://github.com/greensopinion/flutter-vector-map-tiles/issues/160).
