### ISSUE TITLE
[HELP]  can any one make the Marker take arguments

### ISSUE THREAD

**Issue by Sillco** [fleaflet/flutter_map#1441]
### What is the bug?

is it possible to make the marker class take arguments like a dynamic type variable named data or even just a string  to represent a marker id.
Marker(
        markerId:'1',
        markerData:..,
        anchorPos: AnchorPos.align(AnchorAlign.center),
        height: 30,
        width: 30,
        point: LatLng(49.8566, 3.3522),
        builder: (ctx) => const Icon(Icons.pin_drop),
      )

### What is the expected behaviour?

 Marker(
        anchorPos: AnchorPos.align(AnchorAlign.center),
        height: 30,
        width: 30,
        point: LatLng(49.8566, 3.3522),
        builder: (ctx) => const Icon(Icons.pin_drop),
 )

### Platforms Affected

Android, iOS

### Severity

Fatal: Causes the application to crash

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
If you use a closure, you can include any info you want, example.
```
Marker createMarker(point, c) {
    return Marker(
      point: point,
      builder: (ctx) =>
          Container(
            child: IconButton(
              icon: Icon(Icons.location_on),
              color: Color.fromARGB(255, 3, 249, 32),
              onPressed: () {
                print("clicked $c");
              },
            ),
          )
    );
```
and read https://github.com/fleaflet/flutter_map/issues/293 there maybe a more preferable solution there as well

**Comment by JaffaKetchup** [comment]
You can't adjust/change/modify classes in Dart. Please try the solution listed above, or get in touch if you need more help.
