### ISSUE TITLE
[BUG] Live Location Force Close

### ISSUE THREAD

**Issue by dimaszulfa** [fleaflet/flutter_map#1443]
### What is the bug?

![image](https://user-images.githubusercontent.com/62337720/217138591-a2518e61-c5dc-49a3-bf52-fa5aeda713db.png)
D/AndroidRuntime( 5331): Shutting down VM
E/AndroidRuntime( 5331): FATAL EXCEPTION: main
E/AndroidRuntime( 5331): Process: me.jpryan.flutter_map_example, PID: 5331

### What is the expected behaviour?

location can update

### Platforms Affected

Android

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Without much more info, we cannot help. Please open a new issue and look at the guidance given to you.

**Comment by dimaszulfa** [comment]
yes sir, but it's just what happened. there is no message on console or something else. it's like suddenly force close when i opened live location navigation
