### ISSUE TITLE
[FEATURE] One-finger-pinch -> optional flag

### ISSUE THREAD

**Issue by unexus** [fleaflet/flutter_map#1445]
### What do you want implemented?

Hi, please add an additional flag to enable/disable the one-finger-zoom gesture.

`InteractiveFlag.oneFingerPinchZoom`

gestures.dart, Line 702:
`if (InteractiveFlag.hasFlag(flags, InteractiveFlag.oneFingerPinchZoom) ) {`

### Platforms Affected

Android, iOS

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Just to note, there seems to also be a potential bug - tiles aren't loaded until the gesture is finished, and zooming in too far appears as though it may cause errors.
