### ISSUE TITLE
Flutter_map + Mapbox doesn't work after I deployed the app on Firebase (gray screen)

### ISSUE THREAD

**Issue by najib-mrh** [fleaflet/flutter_map#1446]
### What is the bug?

Hi, 
I use Mapbox as a tile layer in Flutter map, everything works fine on the web emulator (chrome and edge). 
Unfortunately, after I deployed the app on Firebase, the screen became totally gray (no map or marker)

Here is my flutter doctor result : 
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [version 6.3.9600], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its
      default components
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] VS Code (version 1.73.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

### What is the expected behaviour?

The map should display with the marker 

### Platforms Affected

Web

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
Check you have internet permissions enabled in your androidmanifest.xml file for release directory.

**Comment by najib-mrh** [comment]
> Check you have internet permissions enabled in your androidmanifest.xml file for release directory.
Yes, I already add <uses-permission android:name="android.permission.INTERNET"/> in androidmanifest.xml file

**Comment by ibrierley** [comment]
I'd probably post up a minimal example of your code and your manifest file, someone may spot something amiss.

**Comment by najib-mrh** [comment]
> (@ibrierley androidmanifest.xml wouldn't help, as this is a web app)
> 
> @najib-mrh In addition to creating an MRE, please also try using Chrome's DevTools Console and Network tabs to check if there are any unexpected responses.

Thank you for Chrome's Devtools console 
Can you please explain me these errors ? https://imgur.com/a/X7Bv1BI 

`Mixed Content: The page at 'https://#########.web.app/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://########/networks'. This request has been blocked; the content must be served over HTTPS.` 

`Uncaught TypeError: Cannot read properties of null (reading 'toString')` 

Thank you !

**Comment by JaffaKetchup** [comment]
Is your tile URL HTTP instead of HTTPS?

**Comment by najib-mrh** [comment]
> Is your tile URL HTTP instead of HTTPS?

The Api endpoint link, yes

**Comment by JaffaKetchup** [comment]
That's why then. For security reasons, you can't load HTTP traffic over HTTPS in some cases. I recommend looking around more online about Mixed Content errors, but there's nothing else we can do AFAIK.

**Comment by najib-mrh** [comment]
Thank you for your help !
