### ISSUE TITLE
[FEATURE] Support dashed `Polyline`s (in addition to dotted)

### ISSUE THREAD

**Issue by WillyAdrianus** [fleaflet/flutter_map#1447]
### What do you want implemented?

if it is possible add dashed polyline with parameter isDashed: true and dashedWidth: {int}

### Platforms Affected

Other

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by MendleM** [comment]
I spent a little time today working on this. I'll get around to it in the coming weeks. If someone gets to it before me, if the lines could have miter joins like this design (from Figma if you want to play around with dashes), that'd be incredible:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/20160314/222955117-da617766-c16c-45f7-85fe-0adcc9aab6ef.png">

**Comment by JaffaKetchup** [comment]
Hey @MendleM, did you ever get around to this? No problem if not!

**Comment by JaffaKetchup** [comment]
Hey @monsieurtanuki, this looks excellent, we'd love to see it!

**Comment by JaffaKetchup** [comment]
Closed by #1855.
