### ISSUE TITLE
is there in flutter_map any similar feature to camera position in google_map_flutter

### ISSUE THREAD

**Issue by halhwadi** [fleaflet/flutter_map#1449]
### What do you want implemented?

I show user location as a marker in flutter_map in addition to other locations as markers, all markers are stored in one list, now my issue when user location change new marker is created in addition to the other markers for the previous locations , is there any parameters which I can use it to show the user location like camera position in google_map_flutter?

### Platforms Affected

Windows

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @halhwadi,
I'm not 100% sure what you're asking for.
If you're asking to move the view/map, FM has the [`MapController` concept](https://pub.dev/documentation/flutter_map/latest/flutter_map/MapController-class.html), which contains methods to control the map programatically. In your case, `.move()` should do what you you're looking for.
If you're asking how to create a dynamic user location marker, take a look at https://github.com/tlserver/flutter_map_location_marker.
Apologies if I'm misunderstanding!

**Comment by halhwadi** [comment]
Thanks fir your quick response 
I use move to change the user location and I have no issue at all in this..
My case is I keep tracking user location and use marker to show this location in map, the issue is when location changes then new marker is created so if user location location has changed ten times then ten different markers will be created and shown on the map!! I can't override the previous user location marker becuase I have other markers for other locations ( Rather than user locations marker) and all of them are stored in one list and there is no way to know which user location marker on that list..

Hopes this clear enough

**Comment by JaffaKetchup** [comment]
Probably best to use streams.
You can opt to have another independent `MarkerLayer` wrapped in a `StreamBuilder`, which rebuilds it's layer only (and the marker within it). This is probably best for performance.
Alternatively, you can just have a marker with a variable as the coordinate, and change the state of that. The marker later will rebuild.

**Comment by halhwadi** [comment]
Thank you, I already have markers as a variables inside the list, but I don't know which one for user location and which one for other landmarks  I will create separate list only for user location and update the location Coordinates when they change,  and add two lists before assigning them to markers parameter in flutter_map  if this not working I will try streambuilder as per your advice..

Thanks again for your assistance and prompt response
