### ISSUE TITLE
[FEATURE] Transparent tiles caching

### ISSUE THREAD

**Issue by giaur500** [fleaflet/flutter_map#1450]
### What do you want implemented?

Any tile that has been loaded once should be cached on disk (application internal cache). Next time map is used, tile should be loaded from disk cache (unless it's been changed).

**I don't mean offline maps.** Behavior should be the same as it's implemented currently, but cache should be persistent, with max cache size possible to set.

### Platforms Affected

Android, iOS

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @giaur500,
I'm not sure I understand your request.
By default, FMTC returns tiles from the cache if they already exist there. This behaviour can be changed: see https://fmtc.jaffaketchup.dev/usage/integration#cache-behavior.
If this doesn't help, please try to refine your explanation :)

**Comment by JaffaKetchup** [comment]
Hi @giaur500,
'flutter_map' doesn't support caching. Please see https://docs.fleaflet.dev/usage/layers/tile-layer/tile-providers#caching for more information.
Happy to help if you need more :)

**Comment by giaur500** [comment]
How to use cached network image to display tiles?

**Comment by giaur500** [comment]
Ok I think I need to create custom tile provider and use this: https://pub.dev/documentation/cached_network_image/latest/cached_network_image/CachedNetworkImageProvider-class.html
