### ISSUE TITLE
[FEATURE] Remove `absorbPanEventsOnScrollables` flag.

### ISSUE THREAD

**Issue by rorystephenson** [fleaflet/flutter_map#1454]
### What do you want implemented?

Remove the `absorbPanEventsOnScrollables` flag. If you have a FlutterMap inside a scrollable and you want dragging the map to cause the scrollable to scroll then you can just disable the `drag` interactive flag. It seems to me that [this has the same effect](https://github.com/fleaflet/flutter_map/blob/3e8368d85d45e1431ed78488f0df102cef81b925/lib/src/map/flutter_map_state.dart#L117-L118) and I can't see why you would need dragging enabled but for the map to not absorb pan events (which makes the dragging not work anyway)?

If you agree I am happy to open a PR including removing unnecessary commented code in `flutter_map_state.dart`.

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Minimum: Not required for my use

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
Not quite sure this is quite the same thing (but I lose track fast!)....For example with the dragmarker (& line_editor) plugin, it allows panning, but needs absorbPanEventsOnScrollables disabled to be able to drag icons iirc ?

**Comment by rorystephenson** [comment]
@ibrierley thanks for pointing that out! I did some further digging and realised that you are right that this would break some plugins. The good news is the fix in #1453 resolves this issues. I've decided to include removal of the flag in that PR (see the second part of the description in that PR for more info).

**Comment by JaffaKetchup** [comment]
Closed by #1455 AFAIK.
