### ISSUE TITLE
How to use Image.asset in marker

### ISSUE THREAD

**Issue by halhwadi** [fleaflet/flutter_map#1456]
### What is the bug?

I'm trying to use Image.asset to display image for marker, i don't have any error but image is not displayed, please find the block of code where i define the marker:
` if (response.statusCode == 200) {
      jsonDecode(response.body)['details'].forEach((carrier){
        markers_carriers_locations.add((new Marker(width: 50.0,
            height: 50.0,
            point: new latLng.LatLng(carrier[0],carrier[1]),
            builder: (ctx) => Image.asset("images/refeers.png",scale: 1.0),)));
        });`

### What is the expected behaviour?

displaying the image on flutter_map 

### Platforms Affected

Windows

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by halhwadi** [comment]
its solved

**Comment by JaffaKetchup** [comment]
Hi @halhwadi,
We're going to need more information.
The best way forward is to simplify your situation: try a `Text` instead of an `Image` widget. If `Text` doesn't work, you've probably got a state issue, or are misunderstanding something.

**Comment by halhwadi** [comment]
Thank you, it was state issue as you mentioned ...
