### ISSUE TITLE
[FEATURE] Rotate around arbitrary point

### ISSUE THREAD

**Issue by derolf** [fleaflet/flutter_map#1460]
### What do you want implemented?

Currently, when you rotate the map, it always rotates around the center.

If you have a nav app, your car icon is usually about 2/3 down and not at the map center. It would be great to rotate the map around a specific point, e.g. the car icon.

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
As a temp hack, it may be possible to reposition the main widget somehow, so the bottom third is off the physical screen, so when rotating it "looks" like its rotating around that object ? (obviously doesn't work for more unaligned situations).

**Comment by Soliardi-Chyngyz** [comment]
This topic remains relevant, there is an example in the MarkerAnchorPage class when markers lie inside MarkerLayer, but what if they lie inside MarkerClusterLayerOptions and it is inside MarkerClusterLayerWidget
in my case clusters are required
