### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by jwr3408** [fleaflet/flutter_map#1461]
### What do you want implemented?

It would be nice and convenient to have a MapEventScrollWheelZoomEnd event. I need to know if the zoom has ended when using a scroll wheel, so I can retrieve data from my api. Currently, it retrieves data at each zoom level, which causes multiple trips and causes the map to slow down.

### What other alternatives are available?

No known workarounds.

I have tried to check the map controller's zoom level and the MapEventScrollWheelZoom target zoom, but they always match,.

### Platforms Affected

Web

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
Maybe you can just register the time on each wheel event, and only call the API if x ms has passed since the last one ?

**Comment by JaffaKetchup** [comment]
This might be quite difficult to implement, as many mice wheels report one event per ratchet rotation. The best way to implement this is with a throttle or debounce mechanism.
