### ISSUE TITLE
LateInitializationError: Field '_state@743051772' has already been initialized.

### ISSUE THREAD

**Issue by halhwadi** [fleaflet/flutter_map#1463]
### What is the bug?

When I scroll down and up, I got this error:

the flutter_map is already initialized inside expanded tag and it keeps working properly till i move down and up in the page

flutter_map: ^0.14.0

```
`Expanded(
                                      child:FlutterMap(
                                        mapController: _mapControllerNextToMe,
                                        options: MapOptions(
                                            interactiveFlags: InteractiveFlag.pinchZoom | InteractiveFlag.drag,
                                            center: latLng.LatLng(lat!,lan!),
                                            zoom: currentZoom,
                                            onMapCreated: (c) {
                                              _mapControllerNextToMe = c;
                                            }
                                        ),
                                        layers: [
                                          new TileLayerOptions(
                                            urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                                            subdomains: ['a', 'b', 'c'],
                                            attributionBuilder: (_) {
                                              return Row(
                                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  FloatingActionButton.small(
                                                    backgroundColor: Colors.green,
                                                    foregroundColor: Colors.white,
                                                    heroTag: 'zoomOut',
                                                    onPressed: _zoomOut,
                                                    tooltip: 'Zoom',
                                                    child: Icon(Icons.zoom_out,size:30.0),
                                                  ),
                                                  FloatingActionButton.small(
                                                    backgroundColor: Colors.green,
                                                    foregroundColor: Colors.white,
                                                    heroTag: 'zoomIn',
                                                    onPressed: _zoomIn,
                                                    tooltip: 'Zoom',
                                                    //add_circle_outline_rounded
                                                    child: Icon(Icons.zoom_in,size:30.0),
                                                  ),
                                                ],
                                              );
                                            },
                                          ),
                                          new MarkerLayerOptions(
                                              markers: marker_shipper_location + markers_carriers_locations
                                          ),
                                        ],
                                      ),
                                    )`
```

### What is the expected behaviour?

dont give this error

### Platforms Affected

Android, Windows

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @halhwadi,
Please update your version. v0.14.0 is extremely old now.

**Comment by halhwadi** [comment]
i already have upgraded and the problem is still there....

**Comment by JaffaKetchup** [comment]
Can you post the code after upgrading.

**Comment by halhwadi** [comment]
I noticed that onMapCreated,layers,TileLayerOptions and MarkerLayerOptions are not been identified , have they been removed recently?

```
      Container(
                        margin: const EdgeInsets.only(left: 5.0, right: 5.0),
                        child: lat != null && lan != null ? Container(
                            height: 400.0,
                            child:Column(
                                mainAxisAlignment: MainAxisAlignment.spaceAround,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  if (lat != null && lan != null)
                                    // SizedBox(height:20),
                                  if (lat != null && lan != null)
                                    Expanded(
                                      child:FlutterMap(
                                        mapController: _mapControllerNextToMe,
                                        options: MapOptions(
                                            interactiveFlags: InteractiveFlag.pinchZoom | InteractiveFlag.drag,
                                            center: latLng.LatLng(lat!,lan!),
                                            zoom: currentZoom,
                                            onMapCreated: (c) {
                                              _mapControllerNextToMe = c;
                                            }
                                        ),
                                        layers: [
                                          new TileLayerOptions(
                                            urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                                            subdomains: ['a', 'b', 'c'],
                                            attributionBuilder: (_) {
                                              return Row(
                                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  FloatingActionButton.small(
                                                    backgroundColor: Colors.green,
                                                    foregroundColor: Colors.white,
                                                    heroTag: 'zoomOut',
                                                    onPressed: _zoomOut,
                                                    tooltip: 'Zoom',
                                                    child: Icon(Icons.zoom_out,size:30.0),
                                                  ),
                                                  FloatingActionButton.small(
                                                    backgroundColor: Colors.green,
                                                    foregroundColor: Colors.white,
                                                    heroTag: 'zoomIn',
                                                    onPressed: _zoomIn,
                                                    tooltip: 'Zoom',
                                                    //add_circle_outline_rounded
                                                    child: Icon(Icons.zoom_in,size:30.0),
                                                  ),
                                                ],
                                              );
                                            },
                                          ),
                                          new MarkerLayerOptions(
                                              markers: marker_shipper_location + markers_carriers_locations
                                          ),
                                        ],
                                      ),
                                    )
                                ]
                            )
                        ): Text(""),
                      ),
```

**Comment by JaffaKetchup** [comment]
This is why I asked to post code, to prove the version change.
There's migration info available on the docs site: you'll need to follow them sequentially from 0.14 through 3.1.0. Hopefully v3 contains the fixes you need.

**Comment by halhwadi** [comment]
now i have managed to upgrade the code as well, however the map itself is not showing, markers are placed on the map but the map itself is shown!!
moreover, is there any idea how i can add image,icon on top of map, i used before 'attributeoptions" and i have replaced them by "tilebuilder"?

`Expanded(
                                      child:FlutterMap(
                                        mapController: _mapControllerNextToMe,
                                        options: MapOptions(
                                            interactiveFlags: InteractiveFlag.pinchZoom | InteractiveFlag.drag,
                                            center: latLng.LatLng(lat!,lan!),
                                            zoom: currentZoom,
                                            onMapReady: () {
                                              setState((){_mapControllerNextToMe = MapController();});
                                            }
                                        ),
                                        children: [
                                          TileLayer(
                                            urlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                                            userAgentPackageName: 'dev.fleaflet.flutter_map.example',
                                            tileBuilder: (BuildContext, Widget,Tile){
                                              return Row(
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                            FloatingActionButton.small(
                                            backgroundColor: Colors.green,
                                            foregroundColor: Colors.white,
                                            heroTag: 'zoomOut',
                                            onPressed: _zoomOut,
                                            tooltip: 'Zoom',
                                            child: Icon(Icons.zoom_out,size:30.0),
                                            ),
                                            FloatingActionButton.small(
                                            backgroundColor: Colors.green,
                                            foregroundColor: Colors.white,
                                            heroTag: 'zoomIn',
                                            onPressed: _zoomIn,
                                            tooltip: 'Zoom',
                                            //add_circle_outline_rounded
                                            child: Icon(
                                            Icons.zoom_in,size:30.0),
                                                  ),
                                                ],
                                              );
                                               }
                                          ),
                                          new MarkerLayer(
                                              markers: marker_shipper_location + markers_carriers_locations
                                          ),
                                        ],
                                      ),
                                    )
                                ]`

**Comment by halhwadi** [comment]
the issue was the tilebuilder, however im keen to know how i can place image on map? i used before "attributeoptions" and i need to know the relevant method in V3.1.0 which provide the same functionalities,please?

**Comment by JaffaKetchup** [comment]
@halhwadi Try `OverlayImageLayer`.

**Comment by halhwadi** [comment]
@JaffaKetchup ..thank you for your support and prompt response
