### ISSUE TITLE
[BUG] `hasGesture` is `false` after double tap zoom in `onPositionChanged` callback

### ISSUE THREAD

**Issue by David-Prelinger** [fleaflet/flutter_map#1465]
### What is the bug?

The onPositionChanged callback delivers _false_ for `hasGesture` when zooming, especially double tapping to zoom. Normally, when the user zooms with two fingers, he also moves the map slightly, so hasGesture will eventually be true. But if you zoom with mouse and keyboard or zoom via double tap, `hasGesture` is just false. 

This makes it hard to disguish between zooms made by code and zooms made by human. 

### What is the expected behaviour?

hasGesture == true, when onPositionChanged callback is called from a zoom. 

### How can we reproduce this issue?

```dart
FlutterMap(
 mapController: _mapController,
 options: MapOptions(
 onPositionChanged: (
    MapPosition posChange,
    bool hasGesture,
 ) {
   print(hasGesture);
}
```

### Can you provide any other information?

I was just able to test it on Android, but I expect it to happen on all platforms.

### Platforms Affected

Android

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I have checked the FAQs section on the documentation website
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
Might be that line 71 of geatures/gestures.dart needs to include "hasGesture: true," if you wanted to test that.

**Comment by David-Prelinger** [comment]
I looked into the code and your suggestion seems reasonable.I tried to edit it in my .pub-cache folder to quickly try it out, though changes there didn't have an effect in my project. I am not familiar with flutter package development, so I would be happy if someone who knows about flutter package development and open source contribution could try it out.

**Comment by JaffaKetchup** [comment]
Hi @David-Prelinger,
You'll need to make a fork of this repository, then edit it via GitHub (or clone and work on it as normal), then depend on it direct from GitHub: https://docs.fleaflet.dev/getting-started/installation#from-github.com. After this, changes from GitHub should appear locally, after running `flutter pub upgrade`.
If the issue appears to be fixed, please do open a PR! There'll be buttons available at the top of your fork page once you make changes, or you can visit https://github.com/fleaflet/flutter_map/compare and use 'Compare across forks'.

**Comment by David-Prelinger** [comment]
Thanks I'll try it out!

**Comment by JaffaKetchup** [comment]
Hi @David-Prelinger, just checking up to see if you ever got around to this? No problem if not!
