### ISSUE TITLE
[FEATURE] start always rotated to the north

### ISSUE THREAD

**Issue by natandiasm** [fleaflet/flutter_map#1466]
### What do you want implemented?

I want the map to start always rotated to the north

### Platforms Affected

Android

### Severity

Minimum: Not required for my use

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Use https://docs.fleaflet.dev/usage/options/recommended-options#rotation-rotation. If that doesn't work, please let us know!
