### ISSUE TITLE
[BUG] MapEventSource.dragEnd gets called two times

### ISSUE THREAD

**Issue by fluttermoonger** [fleaflet/flutter_map#1467]
### What is the bug?

MapEventSource.dragEnd gets called two times even if the event happens one time.

### What is the expected behaviour?

The expected behaviour is that it only fires one time. 

### How can we reproduce this issue?

```dart
FlutterMap(
      mapController: _mapController,
      options: MapOptions(
        onMapEvent: (p0) {
          if (p0.source == MapEventSource.dragEnd) {
            print("DRAG END");
            _getMarkers();
          }
        },
        onPositionChanged: (position, hasGesture) {},
        boundsOptions: FitBoundsOptions(
          padding: EdgeInsets.all(50.0),
        ),
      ),
      children: [
        TileLayer(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
        ),
        MarkerLayer(
          markers: _markers,
        ),
      ],
    );
```

### Do you have a potential solution?

              if (p0.source == MapEventSource.dragEnd) {
                //_getMarkers();
                if (dragCount == 0) {
                  print("drag");
                  dragCount = 1;
                }
                dragCount = 1;
              }

              if (p0.source == MapEventSource.onDrag) {
                dragCount = 0;
              }

### Platforms Affected

Android, iOS

### Severity

Minimum: Allows normal functioning

### Frequency

Once: Occurred on a single occasion

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @fluttermoonger, apologies for the delay.

This is expected behaviour. More than one event can be emitted per source: in this case, there's one event for the drag end, and one event to signify that there was no fling animation started.

https://github.com/fleaflet/flutter_map/blob/64e3a8ec304b999f9ef6d0bece7874216ff76bed/lib/src/gestures/gestures.dart#L527-L554
