### ISSUE TITLE
[FEATURE] Draw Polyline with different gradient colors depending upon elevation 

### ISSUE THREAD

**Issue by J3thr0-6** [fleaflet/flutter_map#1469]
### What do you want implemented?

Hello all,
Is it possible to a draw a polyline on map using PolylineLayer, where we can apply different gradient colors to the line as per elevation.
eg. If we define two colors for red and green for high elevation and low elevation respectively. 
A polyline will drawn on map via defining point as per co-ordinates- lat and long (which is currently happening and working)
but is there any way to apply a gradient̉ to the path which will change it's color from red to green or green to red in a gradient fashion as per elevation 
Do note that, elevation values (altitude) will be user defined similar to  defining points for drawing a polyline on map 

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @J3thr0-6,
We support simple gradients on `Polyline`s, but be warned that they may not behave exactly as you expect - AFAIK the effect is applied to the line's bbox, meaning that if the line bends back towards it's start, the end will be the same color as the start.
