### ISSUE TITLE
[FEATURE] How to use the map rotation function on the web? Both Android and IOS can realize map rotation, but the web side cannot

### ISSUE THREAD

**Issue by BearnLee** [fleaflet/flutter_map#1473]
### What do you want implemented?

How to use the map rotation function on the web? Both Android and IOS can realize map rotation, but the web side cannot

### What other alternatives are available?

How to use the map rotation function on the web? Both Android and IOS can realize map rotation, but the web side cannot

### Can you provide any other information?

How to use the map rotation function on the web? Both Android and IOS can realize map rotation, but the web side cannot

### Platforms Affected

Web

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by TesteurManiak** [comment]
You can rotate the map programatically using the method [`rotate`](https://pub.dev/documentation/flutter_map/latest/flutter_map/MapController/rotate.html) from `MapController`. You can also check the [flutter_map_animations](https://pub.dev/packages/flutter_map_animations) package to get something smoother.

**Comment by BearnLee** [comment]
Thx,dear!
I know that map rotation can be controlled through mapController. I thought that right-clicking on the web side can control the rotation of the map, because other maps are like this, and I thought flutter_map is like this, which is different from what I thought. If I want to right-click to rotate the map, do I need to implement related functions myself?

**Comment by TesteurManiak** [comment]
Yes you'll have to implement this yourself but you might want to wait that this PR is merged first #1448 as it'll add a right click callback to the map.

**Comment by BearnLee** [comment]
Ok,thx!

**Comment by JaffaKetchup** [comment]
#1448 is now merged and available on `master`. Closing this as we are unlikely to implement this. PRs welcome!
