### ISSUE TITLE
[FEATURE] Release 3.1.0

### ISSUE THREAD

**Issue by eliabieri** [fleaflet/flutter_map#1474]
### What do you want implemented?

There's been quite some changes since the last release.
Is there any upcoming release planned?

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Minimum: Not required for my use

### Requirements

- [x] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @eliabieri,
We're working on it slowly behind the scenes! You'll notice that some PRs have been merged recently, and we're waiting on #1475 now, to hopefully make it v4.0.0.
If you aren't already there, consider joining the Discord server for update announcements :)
