### ISSUE TITLE
disable doubleTapToZoom with flags does not work [BUG] 

### ISSUE THREAD

**Issue by a1exhedb** [fleaflet/flutter_map#1477]
### What is the bug?

Whenever using the _InteractiveFlag.none_ or  _InteractiveFlag.all & ~InteractiveFlag.doubleTapZoom_
doubleTapToZoom is still active.

### What is the expected behaviour?

doubleTapToZoom should be inactive.

### How can we reproduce this issue?

```dart
FlutterMap(
    options: MapOptions(
      interactiveFlags: InteractiveFlag.none,
   ),
  children: [
    TileLayer(
      urlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
      userAgentPackageName: 'com.fluttermap.app',
    ),
  ]
)
```

### Do you have a potential solution?

Currently i'm surrounding my map with `AbsorbPointer` setting the absorbing property to `false` when i want the map not to be controlled.

### Platforms Affected

iOS

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi there, apologies for the late reply.
I'm unfortunately unable to reproduce this on latest 'master' (9a13031). If this issue still persists, please ask for this issue to be reopened.
