### ISSUE TITLE
[BUG] Using `tileBuilder: darkModeTileBuilder` prevents rendering tiles with html renderer

### ISSUE THREAD

**Issue by moneytoo** [fleaflet/flutter_map#1486]
### What is the bug?

I use `tileBuilder: darkModeTileBuilder`. When I open such map in a web app on mobile devices (Chrome on Android or Safari on iOS/iPadOS - both using the html renderer by default), then map tiles are not displayed at all. 

### What is the expected behaviour?

I would expect to see inverted tiles or at least unmodified tiles.

### How can we reproduce this issue?

```dart
1. In the official flutter_map example, open `pages/home.dart`
2. Add `tileBuilder: darkModeTileBuilder` to `TileLayer`
3. Run the app with html renderer: `flutter run -d chrome --web-renderer html`


TileLayer(
	urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
	userAgentPackageName: 'dev.fleaflet.flutter_map.example',
	tileBuilder: darkModeTileBuilder,
),
```

### Can you provide any other information?

Run with canvaskit:

![canvaskit](https://user-images.githubusercontent.com/1071643/231389756-602f424b-12b2-48f8-aca6-be58ac1a5b37.png)

Run with html:

![html](https://user-images.githubusercontent.com/1071643/231389841-93349e1a-f274-4905-9e07-7ce80d852fb2.png)

### Platforms Affected

Web

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Thanks for reporting @moneytoo. Unfortunately, this sounds more like a Flutter issue than ours. The builder in the example app is just an example: you can create your own that might work with HTML.

**Comment by JaffaKetchup** [comment]
Closing, as explained above.
