### ISSUE TITLE
Labels on Marker

### ISSUE THREAD

**Issue by arslanrazacrew** [fleaflet/flutter_map#1488]
### What do you want implemented?

Currently, there is no option to add labels on markers in the Flutter Map package. While the markers themselves are useful, being able to add labels to them would make them much more informative and intuitive for users. For example, users could label their markers with the names of locations, addresses, or other important information.

### What other alternatives are available?

Currently, there is no option to add labels on markers in the Flutter Map package. While the markers themselves are useful, being able to add labels to them would make them much more informative and intuitive for users. For example, users could label their markers with the names of locations, addresses, or other important information.

### Can you provide any other information?

Currently, there is no option to add labels on markers in the Flutter Map package. While the markers themselves are useful, being able to add labels to them would make them much more informative and intuitive for users. For example, users could label their markers with the names of locations, addresses, or other important information.

### Platforms Affected

Android

### Severity

Annoying: Currently have to use workarounds

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @arslanrazacrew,
Why can't you just use a `Text` widget?

**Comment by JaffaKetchup** [comment]
Closing, as I'm sure a `Text` widget in the custom builder will be able to perform any function we add.
