### ISSUE TITLE
I want to draw curved line from one point to another point in flutter map with Mapbox

### ISSUE THREAD

**Issue by tjsaini007** [fleaflet/flutter_map#1492]
### What do you want implemented?

I want to draw a curved/arc line from point 1 to point 2 on flutter_map with Mapbox.

### What other alternatives are available?

one option I found but it works with GoogleMap only.

### Platforms Affected

Other

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment]
Hard to know a bit, when you mention Mapbox, what you are using that for, just tiles or the whole system.

Either way, I suspect if you want to do curved lines within flutter_map, you will have to roll your own plugin, you could possibly use something like polyline.dart as a logic template (so see how it uses canvas etc, but just do curved lines instead, assuming you've passed in the relevant info to draw a curve), and checkout a plugin example for the basic plugin usage.

**Comment by tjsaini007** [comment]
@ibrierley Thanks for your quick response.

Like PolylineLayer I'm looking similar Layer for the curved lines. I found a plugin but it only works with GoogleMap and my requirement is to work with FlutterMap. My exact requirement is to draw a curved line from my current location to a specific location(you can check the image). 
Please help I'm stuck here and I need to deliver my project ASAP.

Plugin : [maps_curved_line: ^1.0.2](https://pub.dev/packages/maps_curved_line)

<img width="240" alt="Screenshot 2023-04-17 at 7 09 10 PM" src="https://user-images.githubusercontent.com/25338990/232502162-848124df-4d48-4710-ac30-75e36988fca0.png">

**Comment by JaffaKetchup** [comment]
@tjsaini007 As said by @ibrierley, you're probably best off writing your own layer. You may also be able to use something like 'vector_maths' to create curves, and get all the individual points - but this won't be great for performance.
