### ISSUE TITLE
Change the color of the marker when user is too far away

### ISSUE THREAD

**Issue by LamaAgent** [fleaflet/flutter_map#1494]
### What do you want implemented?

I would like to have a possibility to change the color or the icon of a marker afterwards. Here in my code, I would now like to change the color of the marker, is that possible?

`for (var value in markers) {
        if(Geolocator.distanceBetween(position.latitude, position.longitude, value.point.latitude, value.point.longitude) > 500) {
          setState(() {
            value.builder = (ctx) => const Icon(Icons.location_off, color: Colors.red,); //<-- Here I would like to change the Marker's color
          });
        } else {
          if(markerData.containsKey(value)) {
            markerData.remove(value);
          }
        }
      }`

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by LamaAgent** [comment]
Update: I have now made the `WidgetBuilder` non-final in the Marker class and now it seems to work. Is there another possibility?

**Comment by ibrierley** [comment]
Have you tried just changing whatever you want in the Markers builder method when creating it (i.e just return a different coloured icon or whatever)? You may need to create a separate widget outside the icon that can cause the state of the icon to change (eg a statefulwidget or whatever).

**Comment by LamaAgent** [comment]
Can you provide an example?

**Comment by LamaAgent** [comment]
I want that as soon as the user is too far away, all markers out of range get a certain icon with a certain color and are no longer clickable....

**Comment by LamaAgent** [comment]
That is my code: https://haste.l4zs.de/ecasexotek.typescript

**Comment by ibrierley** [comment]
Just change the color of the icon and call setState ? Not quite sure what the difficulty is you are having.

**Comment by LamaAgent** [comment]
How do I change the color of the icon?

**Comment by LamaAgent** [comment]
I'm really sorry, but I really don't know what you mean right now.

**Comment by ibrierley** [comment]
```
...
icon: Icon(
   Icons.location_on,
   color: myColorThatISetWhenTheDistanceWasReached,
),
```
or whatever I assume.

**Comment by JaffaKetchup** [comment]
See the stateful markers example in the app

**Comment by ibrierley** [comment]
JaffaKetchups suggestions is good and worth looking at that example mentioned. 

Also looking at your code, I would possibly be careful with this as it looks suboptimal..
```
Future<bool> isInRadius(LatLng latLng) async {
    Position currentLocation = await Geolocator.getCurrentPosition();
    if (Geolocator.distanceBetween(currentLocation.latitude,
            currentLocation.longitude, latLng.latitude, latLng.longitude) >
        500) {
      return false;
    }
    return true;
  }
```
This looks like you will end up calling async get gps position for every marker. It's unnecessary and will probably lag I would assume. Instead I would probably listen to a stream of location updates, update a variable once for your current position and have isInRadius use that instead.

**Comment by LamaAgent** [comment]
You just solved all my problems, thank you so much!!!

**Comment by LamaAgent** [comment]
@JaffaKetchup thank you too
