### ISSUE TITLE
[BUG] Markers with `rotate: true` do not adjust their anchor

### ISSUE THREAD

**Issue by AsturaPhoenix** [fleaflet/flutter_map#1500]
### What is the bug?

Markers (and info windows implemented as markers) with `rotate: true` to counter map rotation float around unexpectedly when the map is rotated. This seems to be because the rotation does not include the anchor offset, which is thus applied in the rotated space.

### What is the expected behaviour?

Marker geometry at the anchor position remains stationary in the map space when the map is rotated. That is, if the marker geometry is pointing at a particular map location and `rotate: true`, I expect the marker to continue pointing at that map location as the map is rotated.

### How can we reproduce this issue?

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: FlutterMap(
            options: MapOptions(center: LatLng(0, 0)),
            children: [
              MarkerLayer(
                rotate: true,
                markers: [
                  Marker(
                    point: LatLng(0, 0),
                    width: 256,
                    height: 256,
                    anchorPos: AnchorPos.align(AnchorAlign.left),
                    builder: (context) => const ColoredBox(
                      color: Colors.lightBlue,
                      child: Align(
                        alignment: Alignment.centerRight,
                        child: Text('-->'),
                      ),
                    ),
                  ),
                  Marker(
                    point: LatLng(0, 0),
                    width: 256,
                    height: 256,
                    anchorPos: AnchorPos.align(AnchorAlign.right),
                    builder: (context) => const ColoredBox(
                      color: Colors.pink,
                      child: Align(
                        alignment: Alignment.centerLeft,
                        child: Text('<--'),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
```

### Do you have a potential solution?

A workaround could be to pass the resolved `Anchor` as `rotateOrigin`.

Fixes might include applying the anchor offset as a `Transform`, or fully using `Transform`s instead of `Positioned` widgets.

### Can you provide any other information?

The effect is more pronounced as markers are larger. In the video below, it is particularly pronounced on the info window "markers", which are sized to a max size much larger than the info window itself.

https://user-images.githubusercontent.com/13222934/234441759-041071df-2ebb-48ff-b7a0-cd5fc75f7c44.mp4

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux, Other

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by AsturaPhoenix** [comment]
Here's what the minimum repro looks like with the `rotateOrigin` workaround, with two additional non-rotated markers in lieu of a tile layer for orientation.

https://user-images.githubusercontent.com/13222934/234447611-9a767489-12c8-411c-83d9-4cb6212ed353.mp4

The origin passed in here is the point opposite the anchor (width - left, height - top). The defaulting behavior of `rotateAlignment` slightly complicates this as well, as it needs to be set explicitly to `null` on the `MarkerLayer`.

<details><summary>Workaround code fragment, with the origins hardcoded for simplicity</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: FlutterMap(
            options: MapOptions(center: LatLng(0, 0)),
            children: [
              MarkerLayer(
                rotate: true,
                rotateAlignment: null,
                markers: [
                  Marker(
                    point: LatLng(-.05, 0),
                    rotate: false,
                    builder: (context) => const ColoredBox(color: Colors.black),
                  ),
                  Marker(
                    point: LatLng(.05, 0),
                    rotate: false,
                    builder: (context) => const ColoredBox(color: Colors.black),
                  ),
                  Marker(
                    point: LatLng(0, 0),
                    width: 256,
                    height: 256,
                    anchorPos: AnchorPos.align(AnchorAlign.left),
                    rotateOrigin: const Offset(256, 128),
                    builder: (context) => const ColoredBox(
                      color: Colors.lightBlue,
                      child: Align(
                        alignment: Alignment.centerRight,
                        child: Text('-->'),
                      ),
                    ),
                  ),
                  Marker(
                    point: LatLng(0, 0),
                    width: 256,
                    height: 256,
                    anchorPos: AnchorPos.align(AnchorAlign.right),
                    rotateOrigin: const Offset(0, 128),
                    builder: (context) => const ColoredBox(
                      color: Colors.pink,
                      child: Align(
                        alignment: Alignment.centerLeft,
                        child: Text('<--'),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
```
</details>

**Comment by JaffaKetchup** [comment]
Thanks for the report! We'll investigate.

**Comment by JaffaKetchup** [comment]
Hi @AsturaPhoenix,

Just to let you know, I did have a crack at implementing this for v5, but I couldn't get it to work correctly in all situations - I think I messed up with scaling/CRS translations somewhere, as the points vanished off to the other side of the world in some cases :D

Leaving this open.

**Comment by ElecSmurf** [comment]
Hi, is there any news on a solution for this fix?

**Comment by AsturaPhoenix** [comment]
@ElecSmurf In case you're blocked, you can work around this issue by specifying a `rotateOrigin` opposite the anchor and setting `rotateAlignment: null` on the `MarkerLayer`, as [above](#issuecomment-1522662937).

[Example in context.](https://github.com/AsturaPhoenix/trip_planner_aquamarine/blob/00db561084f972d4a5871a597da24658d780efe9/app/lib/widgets/map.dart#L148)

**Comment by mdmm13** [comment]
Not sure this is what you're looking for, but I recall we had a similar issue ages ago where markers would float around the map during rotation. Fix was to design a marker that matches one of the default `AlignmentDirectional` alignments, like so: `rotateAlignment: AlignmentDirectional.bottomCenter`.

Now you can rotate freely and it keeps the markers anchored where they're needed.

**Comment by JaffaKetchup** [comment]
I also just found out that just setting `rotateAlignment` to the inverse of the `anchor` also works. A fix may arrive in v6.
