### ISSUE TITLE
[FEATURE] Ruler

### ISSUE THREAD

**Issue by mohammedX6** [fleaflet/flutter_map#1501]
### What do you want implemented?

I love to see this helpful plugin ported to flutter_map https://github.com/gokertanrisever/leaflet-ruler 

### Platforms Affected

Android, iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment]
This is more suitable for a plugin. But you can DIY with the `Distance` tools from 'latlong2'.
