### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Abdo2021-a** [fleaflet/flutter_map#1502]
### What is the bug?

 can i make the current location is as live so if the user press on current the map moved scrolled auto as google map and show his current by  LatLng 
thank you so much for this package 

### What is the expected behaviour?

2- can i make the current location is as live so if the user press on current the map moved scrolled auto as google map and show his current by  LatLng 
thank you so much for this package 

### How can we reproduce this issue?

```dart

1- can i make the current location is as live so if the user press on current the map moved scrolled auto as google map and show his current by  LatLng 
thank you so much for this package
```

### Do you have a potential solution?

 can i make the current location is as live so if the user press on current the map moved scrolled auto as google map and show his current by  LatLng 
thank you so much for this package 

### Can you provide any other information?

i have 2 question please 
1- how i can show the street names on map because i just see the region names is this feature avalibale 
2- can i make the current location is as live so if the user press on current the map moved scrolled auto as google map and show his current by  LatLng 
thank you so much for this package 

### Platforms Affected

Android, iOS

### Severity

Minimum: Allows normal functioning

### Frequency

Once: Occurred on a single occasion

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Please see the FAQ and Plugins List.
In future, please follow the issue templates.
