### ISSUE TITLE
[BUG] White lines appears in between tiles on web build on a smartphone web browser

### ISSUE THREAD

**Issue by AlbaneseRemy** [fleaflet/flutter_map#1503]
### What is the bug?

When you use your own TileLayer to show an image on your map, depending on the device or the browser, sometimes you can see a thin white line between each tile. Depending on the zoom level, it sometimes appear, sometimes disappear, sometimes it is thinner or thicker.

### What is the expected behaviour?

The Layer should be shown as a single piece of image not separated

### How can we reproduce this issue?

```dart
https://github.com/AlbaneseRemy/flutter_map_issue

You can find here a simple reproduction of the bug

Otherwise, you can create your own map with your custom TileLayer. It can be with local Assets or with Network image, it doesn't matter.
Then, compile it for web, and host the application somewhere, then open it from a smartphone browser.


As of today, I only tried with Chrome and with a Samsung A51 phone, but it may happen with other browsers/devices? I couldn't try with Apple smartphones.
```

### Do you have a potential solution?

No

### Can you provide any other information?

No

### Platforms Affected

Android

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment]
Hi @AlbaneseRemy,
Can you try forcing the web renderer to use CanvasKit instead of HTML (which is used by default on mobile). See https://docs.flutter.dev/platform-integration/web/renderers.

**Comment by AlbaneseRemy** [comment]
It indeed worked, thanks!
