### ISSUE TITLE
[BUG]  The argument type 'List<dynamic>' can't be assigned to the parameter type 'List<Widget>

### ISSUE THREAD

**Issue by lcsvcn** [fleaflet/flutter_map#1506]
### What is the bug?
I am migrating from 0.14.0 to 3.1.0, follow the migration guide.
There is a run issue after migration. Works fine at 0.14.0.

Here is the fatal error:
../../../.pub-cache/hosted/pub.dev/flutter_map-3.1.0/lib/src/map/flutter_map_state.dart:216:30: Error: The argument type 'List<dynamic>' can't be assigned to the parameter type 'List<Widget>'.

- 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/opt/homebrew/Caskroom/flutter/3.3.7/flutter/packages/flutter/lib/src/widgets/framework.dart').
framework.dart:1
            children: widget.nonRotatedChildren,

### How can we reproduce it?

>   **Environment sdk:** ">=2.13.0 <3.0.0"
>   **Dart SDK:** 2.19.6 (Flutter)
>   **Flutter SDK:** 3.7.12
> 
>   **flutter_map:** 3.1.0

  
  
  Code:
  ```

  FlutterMap(
          options: MapOptions(
            zoom: 10,
            center: LatLng(_viewModel.latitude, _viewModel.longitude),
          ),
          children: [
            TileLayer(
              urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
              subdomains: ['a', 'b', 'c'],
            ),
            MarkerLayer(
              markers: [
                Marker(
                  width: 30.0,
                  height: 30.0,
                  point: LatLng(_viewModel.latitude, _viewModel.longitude),
                  builder: (_) => Icons.pin_drop,
                ),
              ],
            ),
          ],
        ),
```

### Do you have a potential solution?

Use List<Widget> instead of List<dynamic> on children or check why the cast is not correct.

### Platforms

iOS

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Hi @lcsvcn,
This is a little unusual. This is not a bug with FM, and so will be an issue with your configuration.
We recommend migrating between versions sequentially.
We'll be releasing v4 very soon.

**Comment by lcsvcn** [comment]
I still think it is some bug with the new version with Flutter Map. Seems to be happening when the optional field **nonRotatedChildren** is not set. I updated with Android error message.

My all my Flutter Map configuration is on the comment, so you can test it locally to check if it happens to you too.

I could not find the tutorial migration other than the migration from version previous than 3.0.0 to versions above 3.0.0, so I am unable to migrate it from versions, as you suggested.

**Comment by JaffaKetchup** [comment]
See the pages around https://docs.fleaflet.dev/v/v3/migration/older-versions for migrating from older versions.
Note that v4 is now available and should be used.

The example apps seem to be building.

There is no reason for a type error to appear at that location: the argument passed through is strongly specified as a `List<Widget>` with an `[]` default, which is all as expected.
It may be appearing because `nonRotatedChildren` did not take a list of `Widget`s in v0.14.0, but does now.

> Not sure if this may be of interest but:
>
> This line in your code appears to be wrong. Marker builders should return a `Widget` not an `Icon`, but it has always been this way AFAIK:
> ```dart
> builder: (_) => Icons.pin_drop,
> ```

Please try [clearing your pub cache](https://stackoverflow.com/a/59219256/11846040) and any other caches. If the issue still persists, please create an MRE for v4.

**Comment by lcsvcn** [comment]
Yes, I just copied wrong from my code. It should be:
`builder: (_) => Icon(Icons.pin_drop),`
instead of:
`builder: (_) => Icons.pin_drop,`

Now it is working with version 4.0.0. Maybe it was really cache or something...

I will close this issue, since it is not happening anymore. Thanks for the help.
