### ISSUE TITLE
[BUG] CustomPoint has potential cast exception at runtime

### ISSUE THREAD

**Issue by josxha** [fleaflet/flutter_map#1522]
### What is the bug?

While working on https://github.com/greensopinion/flutter-vector-map-tiles/pull/149 i discovered that the current CustomPoint implementation lead to a cast exception at runtime.

This behaviour is documented in the parent class math.Point but isn't mentioned in CustomPoint:
>   /// **Important Note**: This function accepts a `num` as its argument only so
  /// that you can scale `Point<double>` objects by an `int` factor. Because the
  /// `*` operator always returns the same type of `Point` as it is called on,
  /// passing in a double [factor] on a `Point<int>` _causes_ _a_
  /// _runtime_ _error_.

### How can we reproduce it?

```dart
final pDouble = CustomPoint<double>(1, 2);
final pInt = CustomPoint<int>(3,4);
var point;

point = pInt + pDouble; // runtime exception
point = pInt + pDouble; // runtime exception
point = pInt * pDouble; // runtime exception
point = pInt / pDouble; // runtime exception
```

Potentially this would throw an exception too:
```dart
point = CustomPoint<int, int>(5, 5) / CustomPoint<int, int>(2, 2); // runtime exception
```

### Do you have a potential solution?

The issue is that `other` may be a num or double and turns the result into a double while the function casts it to an int.

For example here:
```dart
  /// Create new [CustomPoint] where [x] and [y] values are added to [other]
  /// point [x] and [y] values
  @override
  CustomPoint<T> operator +(math.Point other) {
    return CustomPoint<T>((x + other.x) as T, (y + other.y) as T);
  }
```

Possible solutions:
- Add documentation to the dangerous functions like it's done in math.Point. This could lead to potential errors for users but might not be that problematic since CustomPoint is mostly used internally or by plugin developers.
- force `other` to be the same type as the CustomPoint instance. This requires transforming every working double/int compination to be converted to a double/double.
- Use named functions like: 
```dart
CustomPoint<T> multiplyWithInt(CustomPoint<int> other) {} // int/int, double/int
CustomPoint<double> multiplyWithDouble(CustomPoint<double> other) {} // double/double, int/double
```

### Platforms

tested on android but should 

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by josxha** [comment]
The flutter_map implementation had this issue at some point too and used a workaround:
```dart
final tileZoomDouble = tileZoom.toDouble();
final scale = mapState.getZoomScale(viewingZoom, tileZoomDouble);
final pixelCenter =
    mapState.project(center, tileZoomDouble).floor().toDoublePoint();
```
[Jump to code](https://github.com/fleaflet/flutter_map/blob/578bda0707df16bc5a22d2fc15a0851fca2a2d7a/lib/src/layer/tile_layer/tile_range_calculator.dart#L44-L45)

I don't think that this is the right solution. I can't see why `.floor()` is necessary in the first hand.

**Comment by ibrierley** [comment]
Looks like that was introduced as part of a larger rewrite on https://github.com/fleaflet/flutter_map/pull/572 and it's not clear (is it ever :D)

Just be aware, sometimes the floors and things like that are semi fudges where oddities get introduced like hairline white gaps between tiles and things like that, so double check all that kind of stuff if playing with it.

**Comment by josxha** [comment]
Thanks for the explaination of the floor() usage. (:
