### ISSUE TITLE
Globe View 

### ISSUE THREAD

**Issue by fodedoumbouya** [fleaflet/flutter_map#1524]
### What do you want implemented?

I'm using flutter_map plugin with a MapBox style and I'm trying to display a 3D globe view in app

https://i.stack.imgur.com/4650W.jpg

This is my current FlutterMap

```
FlutterMap(
                  mapController: controller,
                  options: MapOptions(
                    maxZoom: 19,
                    zoom: latestZoom,
                    center: userLocation ?? LatLng(lat, lon),
                  ),
                  children: [
                    TileLayer(
                      urlTemplate:   "https://api.mapbox.com/styles/v1/{username}/{mapStyleId}/tiles/256/{z}/{x}/{y}@2x?access_token={accessToken}",
                      additionalOptions: const {
                        'username': <username>,
                        'mapStyleId': <style.id>,
                        'accessToken': <access.token>,
                      },
                      maxZoom: 19,
                    ),

                      MarkerLayer(
                        markers: [
                          <markers>
                        ],
                      ),
                  ],
                ),
```
After some research I found out that the part responsible for the map view is the "crs" property in MapOptions and that the right projection and transform can give me the target result.

How can I find/create the right Crs class with the globe projection to be able to show a 3D globe view while maintaining the ability to display markers on it?

### Severity

Minimum: Not required for my use

**Comment by JaffaKetchup** [comment]
This has been discussed to great extents before, both here and on the Discord server.
This is currently out of scope for us to implement, and you'll likely need more than just changing CRS - you need to change the way that tiles are rendered, and add a 3D view.
Search for "3D"/"globe" here and on Discord for some previous attempts.
