### ISSUE TITLE
[DNS] fleaflet.dev does not resolve

### ISSUE THREAD

**Issue by solsticedhiver** [fleaflet/flutter_map#1526]
### What is the bug?

`fleaflet.dev` domain does not resolve to any IP.

Meaning, trying to reach fleaflet.dev is not possible;

This is the adress giben on https://pub.dev/packages/flutter_map for the publisher web site.
Either change it to docs.fleaflet.dev, or I don't know, add a static html page site on fleaflet.dev briefly explaining about fleaflet with links to docs, discord, etc ...

Or a permanent redirect to docs.fleaflet.dev, may be if it is possible?

### How can we reproduce it?

Try to browse to fleaflet.dev or try to resolve the domain name the way you like:

    host fleaflet.dev

for example

### Do you have a potential solution?

Not in my power

### Platforms

all 

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
I've updated the pub.dev link, the publisher name can't be changed.
We can't easily change the DNS settings, it's a long story.
Thanks for reporting!
