### ISSUE TITLE
[FEATURE] Add timeDimension to flutter_map options

### ISSUE THREAD

**Issue by billyz313** [fleaflet/flutter_map#1527]
### What do you want implemented?

I would like the map to have options for:

```
        timeDimension: true,
        timeDimensionControl: true,
        timeDimensionControlOptions: {
            autoPlay: false,
            loopButton: true,
            timeSteps: 1,
            playReverseButton: true,
            displayDate: true,
            timeSlider: true,
            limitSliders: true,
            limitMinimumRange: 5,
            timeZones: ['UTC'],
            playerOptions: {
                buffer: 10,
                loop: true,
            }
```

### What other alternatives are available?

I am currently trying to use a RangeSlider, but it doesn't have current value indicator, which I have worked on adding but have not been successful in keeping it confined to the slider width.

### Can you provide any other information?

There has also been requests to add this to the [RangeSlider](https://github.com/flutter/flutter/issues/34704) but since it was in the js leaflet I figured it might be able to be ported in.

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by JaffaKetchup** [comment]
Hi @billyz313, can you explain a little more what this is?

**Comment by billyz313** [comment]
Hi @JaffaKetchup , yes, basically what I am in need of is a flutter version of the Leaflet.TimeDimension as seen https://github.com/socib/Leaflet.TimeDimension .  I have a [current application](https://climateserv.servirglobal.net/) that uses this and I am trying to rewrite this app in flutter.  The lined app uses this on the [map page](https://climateserv.servirglobal.net/map).  When you load the page you will see that the control is visible, but has no attributes.  If you click the layer icon at the top right, then check one of the checkboxes to turn on a layer you will see the timeDimension control in action.  
There are sliders that can narrow the range at each end and there is a current value indicator which also can be dragged as needed.  There are also controls to "play/animate" the time dimension of the layer and even set the fps.  There is a control that displays the current range and can be clicked on to open a dialog that allows the user to set the range by date pickers, but that is not actually part of the timeDimension control so that can be ignored.  
If you need more info please let me know, I'd be happy to discuss/demo the use case more.

**Comment by JaffaKetchup** [comment]
Unfortunately, this is out of scope for FM core for now, as it's quite a niche feature. If anyone's willing to make a plugin for it (especially as it was originally a plugin for Leaflet), we'd be happy to add it to the docs.
