### ISSUE TITLE
[BUG] Update new http 1.0.0

### ISSUE THREAD

**Issue by thorizer** [fleaflet/flutter_map#1531]
### What is the bug?

Because google_fonts >=4.0.5 depends on http ^1.0.0 and flutter_map 4.0.0 depends on http ^0.13.5, google_fonts >=4.0.5 is incompatible with flutter_map 4.0.0.
And because no versions of flutter_map match >4.0.0 <5.0.0, google_fonts >=4.0.5 is incompatible with flutter_map ^4.0.0.
So, because ngi_gps depends on both flutter_map ^4.0.0 and google_fonts ^4.0.5, version solving failed.

### How can we reproduce it?

install any other plugin that now depends on dart 3 and http 1.0.0

### Do you have a potential solution?

most of my packages already use http 1.0.0, there are no breaking changes. they just use the new class modifiers internally

### Platforms

all

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by JaffaKetchup** [comment]
Hi @thorizer,
Please depend on 'master'.
