### ISSUE TITLE
[FEATURE] drawControl and edit tool

### ISSUE THREAD

**Issue by billyz313** [fleaflet/flutter_map#1537]
### What do you want implemented?

I am looking to have drawing tools similar to the js version of leaflet [docs](https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#l-draw-toolbar) so that we can add the drawControl to the flutter_map and the users can draw polygons, rectangles, points, etc... and if needed they can edit these as well.  

### What other alternatives are available?

Currently there is https://github.com/ibrierley/flutter_map_line_editor which enables polygon drawing but it would be much better to have the default leaflet draw controls which in javascript lets me do 

```
 drawToolbar = new L.Control.Draw({
        draw: {
            polyline: false,
            circle: false,
            circlemarker: false,
            polygon: {
                icon: new L.DivIcon({
                    iconSize: new L.Point(8, 8),
                    className: 'leaflet-div-icon leaflet-editing-icon'
                }),
                touchIcon: new L.DivIcon({
                    iconSize: new L.Point(20, 20),
                    className: 'leaflet-div-icon leaflet-editing-icon leaflet-touch-icon'
                }),
            }
        },
        edit: {
            featureGroup: drawnItems,
        },
    });
    map.addControl(drawToolbar);

```

and adds the circled controls:
![drawControls](https://github.com/fleaflet/flutter_map/assets/1868821/669cb164-7a8d-4ebd-b27f-9dda34b254b4)

### Severity

Annoying: Currently have to use workarounds

**Comment by JaffaKetchup** [comment]
Hi @billyz313,
This is unfortunately out of scope. Happy to add a plugin to the Plugins List though!

**Comment by billyz313** [comment]
Thanx @JaffaKetchup I don't understand why it would be out of scope since it was an included feature of the leaflet js version y'all are basing flutter_map on.  Do you know of any better work arounds that might handle this type of drawing on flutter_map?

**Comment by ibrierley** [comment]
This does feel like a good example for a plugin. Why not have a bash ? Folks will try and help if you get stuck.

**Comment by JaffaKetchup** [comment]
> leaflet js version y'all are basing flutter_map on

We are gradually moving away from ties with leaflet.js. It is true that the concepts of this library are similar, but our aim is not necessarily feature parity - we want to implement core features that there's high demand for, and don't really suit plugin architectures.
This is partially because FM is on a much smaller scale than leaflet.js, and there's only 4 maintainers, so we rely on the community for a lot of feature additions - hence, we prefer plugins, as it also reduces the maintenance cost for us.
