### ISSUE TITLE
[BUG] Linux "Invalid internet address tile.openstreetmap.org"

### ISSUE THREAD

**Issue by lewinpauli** [fleaflet/flutter_map#1539]
### What is the bug?

Exception will occur on Linux, Chrome works fine

 Flutter (Channel stable, 3.10.2, on Fedora Linux 38 (Workstation Edition) 6.2.15-300.fc38.x86_64, locale en_US.UTF-8)

message: "Invalid internet address tile.openstreetmap.org"
_errorExplanaition: ""
_errorName: "Invalid argument(s)"

### How can we reproduce it?

The code is almost the same as from the following example: https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/home.dart

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:url_launcher/url_launcher.dart';

class MapPage extends StatefulWidget {
  const MapPage({super.key});

  @override
  State<MapPage> createState() => _MapPageState();
}

class _MapPageState extends State<MapPage> {
  final List<LatLng> points = [
    LatLng(51.5, -0.09),
    LatLng(53.3498, -6.2603),
    LatLng(48.8566, 2.3522),
    LatLng(52.3702, 4.8952),
  ];
  @override
  Widget build(BuildContext context) {
    final markers = <Marker>[
      Marker(
        width: 80,
        height: 80,
        point: LatLng(51.5, -0.09),
        builder: (ctx) => const FlutterLogo(
          textColor: Colors.blue,
          key: ObjectKey(Colors.blue),
        ),
      ),
      Marker(
        width: 80,
        height: 80,
        point: LatLng(53.3498, -6.2603),
        builder: (ctx) => const FlutterLogo(
          textColor: Colors.green,
          key: ObjectKey(Colors.green),
        ),
      ),
      Marker(
        width: 80,
        height: 80,
        point: LatLng(48.8566, 2.3522),
        builder: (ctx) => const FlutterLogo(
          textColor: Colors.purple,
          key: ObjectKey(Colors.purple),
        ),
      ),
    ];

    return Flexible(
      child: FlutterMap(
        options: MapOptions(
          center: LatLng(51.5, -0.09),
          zoom: 5,
        ),
        nonRotatedChildren: [
          RichAttributionWidget(
            popupInitialDisplayDuration: const Duration(seconds: 5),
            animationConfig: const ScaleRAWA(),
            attributions: [
              TextSourceAttribution(
                'OpenStreetMap contributors',
                onTap: () => launchUrl(
                  Uri.parse('https://openstreetmap.org/copyright'),
                ),
              ),
              const TextSourceAttribution(
                'This attribution is the same throughout this app, except where otherwise specified',
                prependCopyright: false,
              ),
            ],
          ),
        ],
        children: [
          TileLayer(
            urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
            //userAgentPackageName: 'dev.fleaflet.flutter_map.example',
          ),
          MarkerLayer(markers: markers),
        ],
      ),
    );
  }
}
```

### Platforms

Linux Fedora 38

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by lewinpauli** [comment]
flutter_map: 4.0.0

And I am getting the exception in dart:io-patch/socket:patch.dart line 234

**Comment by ibrierley** [comment]
Can you ping tile.openstreetmap.org from the Linux console ?

**Comment by lewinpauli** [comment]
yes I get a ping

**Comment by JaffaKetchup** [comment]
@lewinpauli Strange question, but do the tiles load anyway?

**Comment by lewinpauli** [comment]
yes the tiles load

**Comment by lewinpauli** [comment]
@JaffaKetchup everything seems to work fine when I start the application without debugging

**Comment by lewinpauli** [comment]
The issue you are mentioning @JaffaKetchup (https://github.com/flutter/flutter/issues/83792)  is closed and fixed

For the parameter "urlTemplate" in the flutter_map package I can only provide a String, no Uri allowed...(which is mentioned as one of the fixes in the issue) 

Are you using the newest version of the http package inside of flutter_map?

Or do I have to write the address differently than: `urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',` ?

btw `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` does not work for me

**Comment by JaffaKetchup** [comment]
@lewinpauli 

> (https://github.com/flutter/flutter/issues/83792) is closed and fixed

It wouldn't be the first time something was 'fixed' :D

> Are you using the newest version of the http package inside of flutter_map?

If you depend on the 'master' branch, you'll be getting http 1.0.0, otherwise it's 0.13.5. AFAIK 0.13.5 should have the fix. But also, not sure how that interacts with the Flutter SDK version. From the issue, it looks like it was fixed in both.
Those are the constraints, so it's possible one of your packages is interfering with that - especially as 0.13.5 is supposedly compatible with all prior versions (they all share major v0). If one of your packages must have 0.10.0, flutter_map will also use 0.10.0.
You can check what version you're actually getting by running `flutter pub deps`. This could be the source of the issue.

>Or do I have to write the address differently than: `urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',` ?

Nope, that seems OK.

> `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` does not work for me

If using subdomains through the '{s}' placeholder, you also need to specify what subdomains to use through the `subdomains` parameter.

**Comment by JaffaKetchup** [comment]
@lewinpauli That might not mean you are using http 0.13.5, if another package demands something else.

Check your pubspec.lock file for a http entry. It should look something like this:
```yml
  http:
    dependency: transitive
    description:
      name: http
      sha256: "4c3f04bfb64d3efd508d06b41b825542f08122d30bda4933fb95c069d22a4fa3"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0" # Your version will be 0.13.5 or less - if less, that might be the cause of the issue
```

To use http 1.0.0, depend on the 'master' branch. See https://docs.fleaflet.dev/v/v5-beta/getting-started/installation#from-github.com for guidance.

**Comment by JaffaKetchup** [comment]
Well, there's not much else we can do I'm afraid. You'll just have to ignore those exceptions.
