### ISSUE TITLE
Map rotation with static labels orientation April 17, 2023

### ISSUE THREAD

**Issue by athiraHash** [fleaflet/flutter_map#1546]
### What is the bug?

I am using flutter_map with mapbox tiles. My problem is when I rotate the map, all building/poi/road labels also get rotated which affects their readability. When in Mapbox styles studio, labels stay horizontal when the map is rotated – is there any way to achieve the same behavior when integrating mapbox through the flutter_map?

### How can we reproduce it?

Try to rotate the flutter map

### Platforms

mobile

### Severity

Minimum: Allows normal functioning

**Comment by ibrierley** [comment]
I assume you are retrieving raster tiles with the lables on the actual raster tile itself. Your only option really is to use Vector tiles if you need that functionality. You could try something like https://github.com/greensopinion/flutter-vector-map-tiles for that. Feel free to reopen if I've misunderstood something there though.

**Comment by JaffaKetchup** [comment]
@athiraHash You've asked a series of very low quality questions here, on Discord, and on other repositories recently, all trying to achieve similar things. In order for maintainers to help you (here and elsewhere), please **include as much detail as you can**, and **ensure you've fully read the documentation before asking**. Also, look for other similar questions or an FAQ.
