### ISSUE TITLE
[BUG] Tile fallback called although with empty url (FlutterMapNetworkImageProvider)

### ISSUE THREAD

**Issue by envomer** [fleaflet/flutter_map#1554]
### What is the bug?

First thanks for the great library!

I upgraded to flutter_map 5.0.0 and now i am getting errors thrown if a tile image does not exist.
This error to be precise: `flutter: Invalid argument(s): No host specified in URI`

After taking a deeper look, this error is being generated from `FlutterMapNetworkImageProvider` provider.

When a tile does not exist on the remote server, the httpClient will throw an exception which will be caught and the `_loadAsync` will be called again with the `useFallback` argument. IT will try to use the fallback url, but when no fallback url is defined it will use an empty string. That however will throw a `No host specified in URI` error. Does it even make sense to retry if no fallback url is defined?

```dart
// tile_provider.dart:59
  Future<Codec> _loadAsync(
    FlutterMapNetworkImageProvider key,
    StreamController<ImageChunkEvent> chunkEvents,
    ImageDecoderCallback decode, {
    bool useFallback = false,
  }) async {
    final Uint8List bytes;
    try {
      bytes = await httpClient.readBytes(
        Uri.parse(useFallback ? fallbackUrl ?? '' : url),
        headers: headers,
      );
    } catch (_) {
      if (useFallback) rethrow;
      return _loadAsync(key, chunkEvents, decode, useFallback: true);
    }

    return decode(await ImmutableBuffer.fromUint8List(bytes));
  }
  
```

### How can we reproduce it?

- Load a map with missing tiles

Use the following tile provider:

```dart
TileLayer(
      urlTemplate: info.url,
      backgroundColor: Colors.black,
      additionalOptions: const {'noWrap': 'true'},
      reset: resetController.stream,
      panBuffer: 1,
    );
```

### Do you have a potential solution?

Maybe a retry should only be triggered if a fallback is set? What do you think?

### Platforms

MacOS

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @envomer,
I do believe this to be a bug. Thanks for reporting!
