### ISSUE TITLE
[BUG] Many `Polygon`s cause poor performance

### ISSUE THREAD

**Issue by george-brandidea** [fleaflet/flutter_map#1559]
### What is the bug?

When I load with many polygon list,  then the app gets lagging. It's not stable. Taking so longer time to load.

### How can we reproduce it?

Give me solution to resolve this problem.

### Platforms

Android all versions

### Severity

Fatal: Causes the application to crash

**Comment by ibrierley** [comment]
How many polygons are do you have, with how many points in each roughly ?

**Comment by george-brandidea** [comment]
There're 500+ polygons. Each 50+ points are there roughly. It works properly If there's less polygon.

**Comment by JaffaKetchup** [comment]
25000 points is quite a few! Try breaking them up into smaller polygons, then using the culling feature to try to remove some polygons that aren't on screen.

**Comment by george-brandidea** [comment]
Can you share me the code for reference? 

For me it's lagging too much. I need your support.

**Comment by george-brandidea** [comment]
I enabled the culling, still I'm facing the issue. It would be helpful if you share any sample code or project.

**Comment by ibrierley** [comment]
Realistically I think for very high poly/point counts, you may struggle with the default implementation (there's often a tradeoff between flexibility and performance by default), but it's possibly worth creating a test example (maybe that we can actually use for testing performance) that people can look at, and maybe come up with future ideas/plugins/implementations.

Fwiw I have a beta plugin at https://github.com/ibrierley/geojson_vector_slicer (not updated for flutter_map v4) which tries to help with geojson poly/marker performances, but it probably won't be kept up to date that much (unless someone wanted to help on it, simply due to time constraints)

**Comment by george-brandidea** [comment]
Can you review this code whether I've done in the right way? --> [](http://notepad.link/share/OUZbPpAuYL7IJ3jVdQvU)

**Comment by JaffaKetchup** [comment]
@george-brandidea Please create an MRE - that example is very complex and there's no way we can run that.
Please also be cautious of putting private access tokens in public places! I've removed the link as you included your Mapbox access token.

**Comment by george-brandidea** [comment]
Thanks @JaffaKetchup. That's not a original token. Can you tell me about the MRE

**Comment by JaffaKetchup** [comment]
https://en.wikipedia.org/wiki/Minimal_reproducible_example

**Comment by george-brandidea** [comment]
There's an issue in the package. When I use this "InteractiveFlag" in the MapOptions, the app started to lagging. Once I removed this option the map is working without any issue.

**Comment by JaffaKetchup** [comment]
You'll need to be a little more detailed than that. What flags did you change?

**Comment by george-brandidea** [comment]
I tried with these flags @ibrierley 

int interActiveFlags = InteractiveFlag.drag |
      InteractiveFlag.pinchMove |
      InteractiveFlag.doubleTapZoom |
      InteractiveFlag.doubleTapZoom |
      InteractiveFlag.flingAnimation |
      InteractiveFlag.pinchZoom;

**Comment by JaffaKetchup** [comment]
Can you make an MRE with a screen recording please, if you've got a moment?

**Comment by george-brandidea** [comment]
Here's the video link @JaffaKetchup --> https://drive.google.com/file/d/1S5HzBA07ZcqXlx0yfMGphxRcZuE9DdSA/view?usp=sharing

**Comment by george-brandidea** [comment]
@ibrierley you can clearly see that in this video. When the polygon thing is out side the screen the map is working great without any interruption. Only it gets lagging when it's inside the screen. Also there's not my points. I need more clarification whether I missed any code. I followed the documents only. I've also tried with 10 polygons, that time it's working fine without any lagging issue. 

Video link - https://drive.google.com/file/d/1AmgpXN4f442TJkuhNDIWsS8J1kPtQQ1g/view?usp=sharing

**Comment by ibrierley** [comment]
I suspect that's probably normal with current default implementation and no
plugins.

**Comment by george-brandidea** [comment]
I've not used any plugins in the current app related to flutter_map.

**Comment by george-brandidea** [comment]
This is the code I've used to load polygon @ibrierley 

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          FlutterMap(
            mapController: _mapController,
            options: MapOptions(
              center: polyLocation,
              zoom: menuType == "Home" ? 4.5 : 8,
              keepAlive: true,
            ),
            children: [
              TileLayer(
                urlTemplate: _mapUrl,
                backgroundColor: ColorFile.primaryColor,
              ),
              if (Utils.myGeoJson.polygons.isNotEmpty)
                PolygonLayer(
                  polygons: Utils.myGeoJson.polygons,
                  polygonCulling: true,
                ),
            ],
          ),
        ],
      ),
    );
  }
```

**Comment by ibrierley** [comment]
(I'm assuming you're using latest version of flutter_map?)

Like I said, if you have a large set of polys and geojson especially, you could try https://github.com/ibrierley/geojson_vector_slicer just to see if there's a big different, I'd like to know anyway if you get chance (you'd have to drop a version of flutter_map). If it's useful for someone I will look to update it to latest versions.

I'm not really sure what else to suggest for default flutter_map, its not that fast with a lot of polys historically, and I'm not really sure if anything has changed too much

**Comment by george-brandidea** [comment]
Yes. I'm using the latest version flutter_map: ^5.0.0 in my project.

**Comment by george-brandidea** [comment]
@ibrierley 

I tried with this - https://github.com/ibrierley/geojson_vector_slicer

It was working well upto 1500 poly. When I try with more than 3500 poly it really got stuck. It's lagging too much. It would be helpful if you provide a better solution.

**Comment by ibrierley** [comment]
I'd post on the plugins issue, rather than here, if it's specific to that...that's quite a lot of detailed polys...normally there are some tradeoffs to make. i.e drop some detail of some sort, or dropping some of the polys. Eg at low level zooms, you typically don't need all of those polys, and a different index may be more appropriate.

You can experiment with the "tolerance" option on the index, that will do some line simplification, but that gets tricky if some different polys have adjacent sides like in county boundaries (i.e one may be slightly simplified and not be quite adjacent any more, but maybe you want notice at most zoom levels). Also experiment with the buffer param.

**Comment by george-brandidea** [comment]
What you mean @ibrierley. Could you brief this with the code?

`You can experiment with the "tolerance" option on the index, that will do some line simplification, but that gets tricky if some different polys have adjacent sides like in county boundaries (i.e one may be slightly simplified and not be quite adjacent any more, but maybe you want notice at most zoom levels). Also experiment with the buffer param.`

**Comment by ibrierley** [comment]
The index options/params are listed near the top of https://github.com/ibrierley/geojson_vector_slicer

**Comment by ibrierley** [comment]
(there is also an example main.dart in the repo if you need it)

**Comment by george-brandidea** [comment]
Thanks. Let me check that.
