### ISSUE TITLE
[BUG] When I set interactive Flags in MapOptions: Interactive Flag.drag | Interactive Flag.rotate, and listen to onTap and onLongPress at the same time, when I double-click the map, the map will be enlarged

### ISSUE THREAD

**Issue by BearnLee** [fleaflet/flutter_map#1569]
### What is the bug?

When I set interactive Flags in MapOptions: Interactive Flag.drag | Interactive Flag.rotate, and listen to onTap and onLongPress at the same time, when I double-click the map, the map will be enlarged

### How can we reproduce it?

When I set interactive Flags in MapOptions: Interactive Flag.drag | Interactive Flag.rotate, and listen to onTap and onLongPress at the same time, when I double-click the map, the map will be enlarged

### Do you have a potential solution?

When I set interactive Flags in MapOptions: Interactive Flag.drag | Interactive Flag.rotate, and listen to onTap and onLongPress at the same time, when I double-click the map, the map will be enlarged

### Platforms

Web,Win11

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hey @BearnLee, a minimal reproducible example would be appreciated, just to help narrow down the issue!

**Comment by JaffaKetchup** [comment]
I could not reproduce this on the latest 'master', so it has either already been fixed or is an invalid bug.
If you find issues in future, please keep reporting them!
