### ISSUE TITLE
[BUG]  flutter_cache_manager

### ISSUE THREAD

**Issue by ghazalcomputer** [fleaflet/flutter_map#1570]
### What is the bug?

hi 
please help me
when i get pub get show this error

Because flutter_cache_manager 3.3.0 depends on http ^0.13.0 and no versions of flutter_cache_manager match
  >3.3.0 <4.0.0, flutter_cache_manager ^3.3.0 requires http ^0.13.0.
And because flutter_map >=5.0.0 depends on http ^1.0.0, flutter_map >=5.0.0 is incompatible with
  flutter_cache_manager ^3.3.0.
And because cached_network_image 3.2.3 depends on flutter_cache_manager ^3.3.0 and no versions of
  cached_network_image match >3.2.3 <4.0.0, flutter_map >=5.0.0 is incompatible with cached_network_image ^3.2.3. 
So, because metrohamkar depends on both cached_network_image ^3.2.3 and flutter_map ^5.0.0, version solving       
  failed.

### How can we reproduce it?

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.5
  path: ^1.8.0
  path_provider: ^2.0.13
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.11
  flutter_plugin_android_lifecycle: ^2.0.15
  latlong2: ^0.9.0
  flutter_map: ^5.0.0

### Platforms

android

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @ghazalcomputer,
Unless I'm missing something, there's nothing we can do about this? We're using the latest dependencies.

**Comment by george-brandidea** [comment]
@ghazalcomputer Try with these versions. It'll work.

```
flutter_map: ^4.0.0
flutter_cache_manager: ^3.3.0
http: ^0.13.6

```

**Comment by ghazalcomputer** [comment]
@george-brandidea  It is not possible because http ^1.0.0 is already installed

**Comment by JaffaKetchup** [comment]
This is not an issue with FM and is therefore out of scope.

**Comment by george-brandidea** [comment]
@ghazalcomputer Just remove it and add the http dependency. It'll work.
