### ISSUE TITLE
[FEATURE] in flutter web,brower is not allow set user-agent

### ISSUE THREAD

**Issue by duzechao** [fleaflet/flutter_map#1580]
### What do you want implemented?

`tileProvider = tileProvider == null
            ? NetworkTileProvider(
                headers: {'User-Agent': 'flutter_map ($userAgentPackageName)'},
              )
            : (tileProvider
              ..headers = <String, String>{
                ...tileProvider.headers,
                if (!tileProvider.headers.containsKey('User-Agent'))
                  'User-Agent': 'flutter_map ($userAgentPackageName)',
              })`
this code  add  user-agent,but in safari is not allowed

### Severity

Minimum: Not required for my use

**Comment by JaffaKetchup** [comment]
Hi @duzechao, thanks for reporting.
This is unfortunately a Flutter limitation and there's nothing we can do about it. You can verify this by observing all the (ignorable) errors in the debug console about 'Refused to set unsafe header'.
