### ISSUE TITLE
[FEATURE] Draggable Circle Layer Feature

### ISSUE THREAD

**Issue by MrShakila** [fleaflet/flutter_map#1588]
### What do you want implemented?

I need to implement a draggable circle layer  for my flutter project, currently, I have no solutions to do that, I'm getting user location and adding a 500-meter radius to that using the container ,(older documentation has `circularlayeroptions` but the latest version doesn't have that )

### What other alternatives are available?

I added a normal container  to that but it's hard to keep the 500m radius when the user zooms in or out on map

```
DragMarkers(
              markers: [
                DragMarker(
                  rotateMarker: false,
                  size: Size(circleRadius * 2, circleRadius * 2),
                  point: markedLatlnag ?? location,
                  offset: const Offset(0.0, -8.0),
                  builder: (context, demoMarkers, isdrag) => Container(
                      decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: const Color.fromARGB(55, 41, 120, 255),
                    border: Border.all(
                      color: circleBorderColor,
                      width: circleBorderWeight,
                    ),
                  )),
                  onDragUpdate: (details, latLng) => print(latLng),
                  onDragEnd: (details, latLng) {
                    // Update the marker's position

                    markedLatlnag = latLng;
                  },
                ),
              ],
            ),
```

### Severity

Annoying: Currently have to use workarounds

**Comment by JaffaKetchup** [comment]
Hi @MrShakila,
The circle layer is now called `CircleLayer`, with circles themselves being `CircleMarker`s. You may be able to adapt this to what you need.
Maybe the scale bar in the example app has something useful to keep the circle at 500m with `DragMarker`?

**Comment by JaffaKetchup** [comment]
For now, I think this is a little out of scope. We haven't supported any other draggable markers, as there's a plugin that does that. Closing for now.

**Comment by ibrierley** [comment]
Can't you use the dragmarker plugin with a circle icon and adjust the size when the user zooms (listening to the mapController) ?
