### ISSUE TITLE
[BUG] `FadeRAWA` allows invisible widgets to receive gesture events

### ISSUE THREAD

**Issue by ddshd** [fleaflet/flutter_map#1589]
### What is the bug?

On iOS (only tested on iOS) - Using the following code the "OpenStreetMap contributors" text is still tappable even through it does not show up on the screen. If a user is to tab in the general location of where the text would be the link opens

### How can we reproduce it?

Using the following on a FlutterMap
```
                nonRotatedChildren: [
                  RichAttributionWidget(
                    attributions: [
                      TextSourceAttribution(
                        'OpenStreetMap contributors',
                        onTap: () => launchUrl(
                          Uri.parse('https://openstreetmap.org/copyright'),
                        ),
                      ),
                    ],
                  ),
                ],
```

Tap the "info" button to see where the text would be, close the widget, and tab in the region where the text would be if the widget was open.. This will cause the link to be launched

### Do you have a potential solution?

Haven't looked deep into how the widget is shown/hidden but maybe it's done through opacity then the items would still interactive even though they are not seen

### Platforms

iOS 16

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @ddshd,

I can't reproduce this on Android, and I'm not sure why there would be platform specific behaviour here.

https://github.com/fleaflet/flutter_map/assets/58115698/31cfce2c-8e8c-4f7b-9976-2705b6d52b66

Can you reproduce on iOS with the example app?

**Comment by ddshd** [comment]
https://github.com/fleaflet/flutter_map/assets/17243132/6e425a02-1597-4a14-a0b8-969294512e3e

I should also note that we do not have the following set, we are just using the default value.. I commented the line out to reproduce it. Apologies.
https://github.com/fleaflet/flutter_map/blob/3f18982aeaae35622da689d5d88bcb4ed0fddb54/example/lib/pages/home.dart#L127

**Comment by JaffaKetchup** [comment]
Ok, thanks for that extra information. I can now reproduce it.
The fade animation uses `AnimatedOpacity`, which I should've realised won't stop gesture events at 0%. The scale animation is not a problem because the container becomes 0x0px.
