### ISSUE TITLE
onZoomChanged callback is needed

### ISSUE THREAD

**Issue by 244226077** [fleaflet/flutter_map#1595]
### What do you want implemented?

onZoomChanged callback is needed

### Severity

Minimum: Not required for my use

**Comment by TesteurManiak** [comment]
You can already implement this functionality with the callback [onMapEvent](https://pub.dev/documentation/flutter_map/latest/flutter_map.plugin_api/MapOptions/onMapEvent.html).

This is the second time you are opening an issue without checking the existing properties. Please remember to check the [documentation website](https://docs.fleaflet.dev/)  before opening an issue and if you're still unsure about the availability of a feature you can ask questions directly on the [discord server](https://discord.gg/BwpEsjqMAH) .
