### ISSUE TITLE
[FEATURE] Improve map zoom gesture with a threshold to lock onto it

### ISSUE THREAD

**Issue by androidseb** [fleaflet/flutter_map#1600]
### What do you want implemented?

When you use two fingers to pinch-zoom on the map, it is almost impossible to do this without accidentally causing the map to rotate a little bit. I personally find this is not ideal when you're trying to keep the map strictly oriented towards the north and did not intend to rotate the map with that gesture.

When you use two fingers to twist-rotate on the map, it is almost impossible to do so without accidentally causing the map zoom to change a little bit. I personally find that this is not much of a problem, because I feel like the map zoom is a thing you change often when using the map.

Ideally, there would be some kind of gesture threshold before which no change happens to the map rotation, and if a significant map zoom gesture is in progress, then the map rotation gesture is blocked from starting.

### What other alternatives are available?

To achieve this today in flutter_map, the user can still double-tap and hold to zoom in/out without accidentally rotating the map.

### Can you provide any other information?

**DISCLAIMER: this suggestion is based on an opinionated and subjective approach to the ideal map gestures UX.**

What I'm describing seems to be how the mobile apps of Google Maps and MAPS.ME behave today.

### Severity

Minimum: Not required for my use

**Comment by androidseb** [comment]
With the [V6 release](https://github.com/fleaflet/flutter_map/releases/tag/v6.0.0) just a few hours ago, I can see that this is now possible, I was able to obtain a behavior I wanted with the new `interactionOptions` param.

Here is a code sample for reference:

```dart
FlutterMap(
  options: MapOptions(
    //...
    interactionOptions: const InteractionOptions(
      enableMultiFingerGestureRace: true,
      flags: InteractiveFlag.doubleTapDragZoom |
          InteractiveFlag.doubleTapZoom |
          InteractiveFlag.drag |
          InteractiveFlag.flingAnimation |
          InteractiveFlag.pinchZoom |
          InteractiveFlag.rotate |
          InteractiveFlag.scrollWheelZoom,
    ),
    // ...
```

I hope this helps! Closing this issue since it has been resolved with the V6.

**Comment by JaffaKetchup** [comment]
Hi @androidseb,
As far as I'm aware, all those options existed in v5! Maybe I'm wrong though.
Thanks for closing anyway :)

**Comment by Hamza-Maa** [comment]
> With the [V6 release](https://github.com/fleaflet/flutter_map/releases/tag/v6.0.0) just a few hours ago, I can see that this is now possible, I was able to obtain a behavior I wanted with the new `interactionOptions` param.
> 
> Here is a code sample for reference:
> 
> ```dart
> FlutterMap(
>   options: MapOptions(
>     //...
>     interactionOptions: const InteractionOptions(
>       enableMultiFingerGestureRace: true,
>       flags: InteractiveFlag.doubleTapDragZoom |
>           InteractiveFlag.doubleTapZoom |
>           InteractiveFlag.drag |
>           InteractiveFlag.flingAnimation |
>           InteractiveFlag.pinchZoom |
>           InteractiveFlag.rotate |
>           InteractiveFlag.scrollWheelZoom,
>     ),
>     // ...
> ```
> 
> I hope this helps! Closing this issue since it has been resolved with the V6.

It worked thanks.
