### ISSUE TITLE
[BUG] tiles need some panning before being shown on 

### ISSUE THREAD

**Issue by sikandernoori** [fleaflet/flutter_map#1601]
### What is the bug?

After using `fitBounds` from `MapController` tiles needs some panning to display.

In example app Animated MapCofntroller (`example/lib/pages/animated_map_controller.dart`)

when you call `mapController.fitBounds(` line `164`.

Expected behaviour: 

Tile should load properly, new tiles should be rendered if necessary.

### How can we reproduce it?

Run example app go to Animated MapController page, zoom in a bit then click `Fit Bounds` button on screen.

https://github.com/fleaflet/flutter_map/assets/16399272/40704881-3c3b-4b7b-bea1-273b5863c613

### Do you have a potential solution?

No.

### Platforms

IOS 13

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
This looks similar to #1563, so that will be updated to include all platforms. Thanks for reporting!
