### ISSUE TITLE
[BUG] Double-tap-drag gesture doesn't cause new tiles to load after completion

### ISSUE THREAD

**Issue by JaffaKetchup** [fleaflet/flutter_map#1602]
### What is the bug?

Performing the double-tap-drag gesture (`MapEventSource.doubleTapHold`) does not cause new tiles to load after the gesture.

It's the correct behaviour for tiles not to load DURING the gesture, however - they should only load afterward.

### How can we reproduce it?

Perform the double-tap-drag gesture on any map to zoom in or out. The previously visible tiles will remain visible, and no new tiles will be loaded.

### Do you have a potential solution?

The example application's Interactive Flags test page does not appear to show this event after/during the gesture, meaning it is likely that none is properly emitted during zooming.

### Platforms

All

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by flodaniel** [comment]
I am on `flutter_map: 5.0.0` and the loading does also not occur once the gesture is completed. I use the gesture to zoom out and after completion the entire map is grey and no server calls to the tiles server are made. Once the user does a simple drag the load happens.

**Comment by JaffaKetchup** [comment]
Thanks @flodaniel, I've updated the original issue, as I can reproduce that now as well (I struggled to for some reason previously, but that was probably coincidence).

**Comment by josxha** [comment]
> I always thought this was more of a feature and not a bug.

That's a nice point of view. 😅 

> Of course after the gesture is finished the tiles should load, but surprisingly that always worked for me.

The problem is that another gesture input is needed until the tiles load after you zoomed with this gesture. I guess *most* users would do that intuitively if they see that the map doesn't load althrough not every user.

**Comment by JaffaKetchup** [comment]
Agreed, I think it makes sense for tiles to only load after completion with this gesture.

**Comment by josxha** [comment]
Some information on how to reproduce the bug:

1. open the interactive flags page of the demo app
2. deactivate all movement gestures, you can activate everything else but at least `+ drag`
3. perform a double tap + drag gesture

https://github.com/fleaflet/flutter_map/assets/34318751/ea048a3d-2876-4ea3-b93d-831e8ab3bc2a

**Comment by JaffaKetchup** [comment]
This appears to be fixed when performing it on the home page of the example application, but it does still occur in the conditions described by https://github.com/fleaflet/flutter_map/issues/1602#issuecomment-1837264417.

**Comment by JaffaKetchup** [comment]
I'm going to close this as a duplicate of #1813.
