### ISSUE TITLE
[BUG] Scalebar plugin feature cannot be implemented by default out of the box

### ISSUE THREAD

**Issue by blablabla123-cell** [fleaflet/flutter_map#1604]
### What is the bug?

In order to implement a scale bar as introduced in the example ('plugin_scalebar.dart' page), we need to have scale_layer_plugin_option.dart and scale_bar_utils.dart files included. But the first file has got methods which depend on other files which are not presented in the flutter_map package itself: 

  final map = MapCamera.of(context);
    final zoom = map.zoom;
    final distance = scale[max(0, min(20, zoom.round() + 2))].toDouble();
    final center = map.center;
    final start = map.project(center);
    final targetPoint =
        util.calculateEndingGlobalCoordinates(center, 90, distance);
    final end = map.project(targetPoint);
    

I myself could not figure out how to do this and It seems unclear to me. Also I googled all the issues and docs and couldn't find an answer. Please, help.

### How can we reproduce it?

Just install the package and include those two files and then you get an error of missing definitions and imports.

### Do you have a potential solution?

Include the 'MapCamera' object in the package or export it as I am guessing is the solution.

### Platforms

All

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @blablabla123-cell,
The `master` branch contains code for v6, which is incompatible with the current v5. The example app is migrated to v6, which is why it uses `MapCamera`. See https://github.com/fleaflet/flutter_map/tree/v5.0.0/example for the latest v5 compatible example.
