### ISSUE TITLE
[BUG] MacOS - Pinch to zoom behaviour

### ISSUE THREAD

**Issue by tobiasht** [fleaflet/flutter_map#1605]
### What is the bug?

When using pinch to zoom on a Mac, the maps zooms into the middle of the map instead of the position of the mouse pointer. Expected behaviour would be the same as Google Maps.

### How can we reproduce it?

Use pinch to zoom on a Mac

### Platforms

MacOS

### Severity

Minimum: Allows normal functioning

**Comment by JosefWN** [comment]
Are you using `v5.0.0`? Anything below should be suffering from this bug, which was fixed in this PR: https://github.com/fleaflet/flutter_map/pull/1543

**Comment by JaffaKetchup** [comment]
Closing as it is assumed that the author is using an outdated version. If this is not the case, please ping to reopen.

**Comment by tobiasht** [comment]
You are right. Thank you for pointing that out
