### ISSUE TITLE
[BUG] When intersection, polygon disappear

### ISSUE THREAD

**Issue by Velliane** [fleaflet/flutter_map#1608]
### What is the bug?

I have several polygons to display on the map. Individually, it's fine. But when I add them all, if they overlap, some disappear:

Single polygon
<img width="186" alt="Capture d’écran 2023-08-08 à 15 22 57" src="https://github.com/fleaflet/flutter_map/assets/44947503/5270e2b5-14d5-4419-bcd3-05748090b64c">

Multiple polygon (a part of the previous disapeared)
<img width="262" alt="Capture d’écran 2023-08-08 à 15 21 37" src="https://github.com/fleaflet/flutter_map/assets/44947503/1e40332d-f28c-4896-916b-2e984819b230">

  flutter_map: ^4.0.0
  latlong2: ^0.8.1

### How can we reproduce it?

I just create a list of Polygon and add it to FlutterMap using PolygonLayer.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/plugin_api.dart';
import 'package:latlong2/latlong.dart';

void main() {
  runApp(MapView());
}

class MapView extends StatelessWidget {
  const MapView({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: FlutterMap(
          mapController: MapController(),
          options: MapOptions(
            center: LatLng(43.678646, 7.053967),
            interactiveFlags:
                InteractiveFlag.drag | InteractiveFlag.pinchZoom | InteractiveFlag.doubleTapZoom,
            zoom: 7,
            onMapReady: () {},
          ),
          children: [
            TileLayer(
              urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
              subdomains: const ['a', 'b', 'c'],
            ),
            PolygonLayer(
              polygons: [
                Polygon(
                  color: Colors.blue,
                  isFilled: true,
                  points: [
                    LatLng(43.652371, 7.15313),
                    LatLng(43.627028, 7.132874),
                    LatLng(43.59521, 7.124977),
                    LatLng(43.573022, 7.117767),
                    LatLng(43.580982, 6.969452),
                    LatLng(43.773666, 7.047729),
                    LatLng(43.769699, 7.209778),
                    LatLng(43.69329, 7.183685),
                    LatLng(43.665481, 7.193298)
                  ],
                ),
                Polygon(
                  color: Colors.blue,
                  isFilled: true,
                  points: [
                    LatLng(43.702878, 7.20892),
                    LatLng(43.686991, 7.235527),
                    LatLng(43.697417, 7.265053),
                    LatLng(43.721986, 7.271233)
                  ],
                ),
                Polygon(
                  color: Colors.blue,
                  isFilled: true,
                  points: [
                    LatLng(43.702170146, 7.250461578),
                    LatLng(43.69692083, 7.250806409),
                    LatLng(43.692824997, 7.245657134),
                    LatLng(43.684706198, 7.232265472),
                    LatLng(43.674153609, 7.218875885),
                    LatLng(43.670254113, 7.209434509),
                    LatLng(43.67894518, 7.199134827),
                    LatLng(43.717170922, 7.186088562),
                    LatLng(43.726103295, 7.250976563)
                  ],
                )
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

### Platforms

Android/IOS

### Severity

Minimum: Allows normal functioning

**Comment by ibrierley** [comment]
Can you show us some code, and does it happen without the popup and cluster ?

**Comment by Velliane** [comment]
Thanks @ibrierley 
I edited my post. Yes, it happens also when I remove popup and cluster.

**Comment by JaffaKetchup** [comment]
Hi @Velliane,
A sample of the coordinates (both source, and what is eventually passed to FM) that cause the issue would be useful.
Just to note, if the coordinates in one polygon self-intersect, then you'd expect to see a gap like this. But it looks like you're generating multiple polygons: although I haven't tested the code.

**Comment by Velliane** [comment]
Hi @JaffaKetchup 
I added two of the coordinates

**Comment by ibrierley** [comment]
This is just kind of confusing. Get rid of all the extra stuff, no other plugins, no _buildPolygon, no viewModels, no json, hard fix the LatLngs you want into the Polygon layer and test.

If you still get an error, just amend the original post with the minimal code for others to test.

**Comment by Velliane** [comment]
Sorry about that. I updated my post.
I still have the error, the problem seems to be between the last 2 polygon when they are the same color. When i change the color of the last Polygon, it's seems ok:
![Screenshot_20230808_220130](https://github.com/fleaflet/flutter_map/assets/44947503/c7b93ddc-3fbd-43d8-bb7a-da84e60edcd0)

**Comment by JaffaKetchup** [comment]
Can you try updating to the latest 'master', if it's not too difficult? There's a lot of breaking changes, but they should be mostly self explanatory with deprecations. However, there's also some commits included that have fixed a couple of bugs with polygons.

**Comment by Velliane** [comment]
I update flutter_map to 5.0.0 and latlong2 to 0.9.0 (I can't in my project because of flutter_map_marker_cluster), but the result is the same when all polygon have the same color

<img width="262" alt="Capture d’écran 2023-08-09 à 09 23 54" src="https://github.com/fleaflet/flutter_map/assets/44947503/1e66eec6-e0e0-46a7-b0c6-a83edf81df40">

**Comment by JaffaKetchup** [comment]
Ah ok, I meant 'master' branch on GitHub.

**Comment by ibrierley** [comment]
I suspect this is a bug with batching polys for optimisation...

in lib/src/layer/polygon_layer.dart amend (maybe line 145)
```
if (lastHash != null && lastHash != hash) {
        drawPaths();
      }
```
to just
```
drawPaths();
```
I suspect it will work ok

**Comment by Velliane** [comment]
@ibrierley 

I try, and I worked yes 

<img width="240" alt="Capture d’écran 2023-08-09 à 10 17 54" src="https://github.com/fleaflet/flutter_map/assets/44947503/f9738442-230e-4d4c-abb0-486d70d6f434">

**Comment by JaffaKetchup** [comment]
It's probably fixed in the latest master then.

**Comment by ibrierley** [comment]
I'm not sure it is, as it basically has a similar codepath, or did some bug fix happen around this area ?

**Comment by JaffaKetchup** [comment]
It might not have been fixed, but @ignatz did 2 or 3 fixes to polygon batching.

**Comment by Velliane** [comment]
Thanks @ignatz 
It's the first time I have to work with Polygon, and I don't really understand what you mean by "align your normals". How can I do that ?

**Comment by ignatz** [comment]
Sorry, in this context normal is just a flexy way of referring to whether your polygon points are given in a clockwise or counter-clockwise order, e.g.  points (A, B, C) and (C, B, A) define the same polygon just with different surface orientation or opposing normals.

You can use https://github.com/fleaflet/flutter_map/blob/master/lib/src/layer/polygon_layer.dart#L15 to write something like:

```dart
  final polygons = <List<LatLng>>[];
  // ...
  final alignedPolygons = polygons.map((points) => isClockwise(points) ? points : points.reversed.toList());
```

**Comment by JaffaKetchup** [comment]
Closing this as resolved. Thanks for reporting!
