### ISSUE TITLE
[FEATURE] Semantics passthrough

### ISSUE THREAD

**Issue by edeetee** [fleaflet/flutter_map#1611]
### What do you want implemented?

My team is developing an app that presents information about accessibility features on a map:
[edt.nz/smart_access](https://edt.nz/smart_access)

I am currently using a custom painter to render the markers
In order to support people with different abilities, we need screen reader support (semantics).
I can implement this on a custom painter with [the semanticsBuilder override](https://api.flutter.dev/flutter/rendering/CustomPainter/semanticsBuilder.html).

However, flutter_map seems to override the semantics information with a big button, and any layers I use do not appear in the semantics debugger.

### What other alternatives are available?

I tried to wrap flutter map with custom semantics but it is very hacky and I couldn't figure out a way to access the FlutterMapState at a higher level without resorting to updating my markers on every second frame.

As mentioned above, making the semantics inside the layers did not work.

### Can you provide any other information?

I think I can figure out how to make this happen, I will work on a pull request so the accessibility improvements can be shared.

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by edeetee** [comment]
I made a fork and had a go at making the RawGestureDetectors excludeFromSemantics true, to no avail.
If anyone has ideas where the semantic tree might be getting absorbed please lemme know and I can try it out, do some testing and submit a pull req.

Cheers!

**Comment by edeetee** [comment]
My bad, was occurring due to my CustomPaint having zero size.
Fixed by Wrapping CustomPaint in a Stack(fit: StackFit.Expand)

**Comment by JaffaKetchup** [comment]
@edeetee Good to hear you fixed it yourself!
