### ISSUE TITLE
[BUG] 6.0.0-dev.2: Assertion false positive: "MapCamera is no longer within the cameraConstraint after an option change"

### ISSUE THREAD

**Issue by jjoelson** [fleaflet/flutter_map#1613]
### What is the bug?

Hi all! I'm testing out some code on the pre-release `6.0.0-dev.2` version. Whenever I include a camera constraint in my map options, I get an assertion failure from [lib/src/map/internal_controller.dart](https://github.com/fleaflet/flutter_map/blob/991f53c94386e31ab127bed97390f0046e2d96ef/lib/src/map/internal_controller.dart#L266):
```
    assert(
      newOptions.cameraConstraint.constrain(newCamera) == newCamera,
      'MapCamera is no longer within the cameraConstraint after an option change.',
    );
```

My constraint is a `CameraConstraint.containCenter` constraint, and I've confirmed that the map center is indeed within the given constraint.

### How can we reproduce it?

Create a map with map options that include a camera constraint, but ensure the map options change after the initial build such that `FlutterMap`s `didUpdateWidget` is called with the new set of map options.

### Do you have a potential solution?

I may have missed it, but it doesn't seem as though `MapCamera` implements `operator ==`, which may explain the issue (i.e. the assertion is essentially doing reference equality, which I think would always fail). If someone else is not already working on this then I could work on a PR to add it.

cc @rorystephenson @JaffaKetchup 

### Platforms

Android, iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by jjoelson** [comment]
Turns out to be a relatively simple fix; I just had to implement `operator ==`/`hashCode`: https://github.com/fleaflet/flutter_map/pull/1614

**Comment by DevTello** [comment]
@JaffaKetchup The same issue if I'm using CameraConstraint.contain(). No problems, if it's CameraConstraint.containCenter()

**Comment by JaffaKetchup** [comment]
@DevTello If you're still getting this issue in v6.1.0, please open a new issue!

**Comment by priyanshi-pandya** [comment]
I was getting the same exception, i had to adjust the initialCenter with respect to the cameraConstraints

Like,
  `initialZoom: 2.3,
    cameraConstraint: CameraConstraint.contain(
           bounds: LatLngBounds(
           const LatLng(-90, -180),
            const LatLng(90, 180),
                    ),
    ),`
                  
                  
For  this above bounds it works perfectly with  initialZoom of 2.3, if I go any less than this, its throws me again MapCamera, is not within cameraConstraint error.

Here is my full code

         FlutterMap(
                options: MapOptions(
                  minZoom: 1,
                  maxZoom: 19,
                  initialCenter: const LatLng(0, 0),
                  initialZoom: 2.3,
                  cameraConstraint: CameraConstraint.contain(
                    bounds: LatLngBounds(
                      const LatLng(-90, -180),
                      const LatLng(90, 180),
                    ),
                  ),
                  onTap: (tapPosition, point)  {
                    //Tap logic
                  },
                  onPointerHover: (event, point) {
                    //Hover logic                  },
                ),
                mapController: mapProvider.mapController,
                children: [
                  TileLayer(
                    urlTemplate:
                        'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                    userAgentPackageName: 'com.example.app',
                    tileProvider: CancellableNetworkTileProvider(),
                  ),
                  //other layers
                  
                ]
             ),
