### ISSUE TITLE
[FEATURE] Allow gesture handling on multiple layers

### ISSUE THREAD

**Issue by LRadocaj** [fleaflet/flutter_map#1616]
### What is the bug?

If I have more Marker/Polygon/Polyline layers only the top layer it tappable. 

### How can we reproduce it?

Place multiple layers, and check for tap callbacks on them, only the top one would be tappable.

### Do you have a potential solution?

The way I would workaround this is to either:

- Place all elements in 1 layer with custom painters
- Calculate whats being tapped on from MapOptions's onTap callback

Please let me know is there is an existing solution to this problem, thanks.

### Platforms

All platforms

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by LRadocaj** [comment]
TranslucentPointer from https://github.com/fleaflet/flutter_map/pull/1615 closes my issue.

**Comment by JaffaKetchup** [comment]
Hey @LRadocaj,

I'm going to leave this open for now, as it's not technically resolved yet. But thanks for confirming that it works!
