### ISSUE TITLE
[FEATURE] Induvidual line coloring within a PolyLine

### ISSUE THREAD

**Issue by digitalinnovationas** [fleaflet/flutter_map#1618]
### What do you want implemented?

I would like to see different colors on individual segments in a PolyLine. This would make it possible to use colors to indicate different states on individual lines (point to point) in the same polyline - like traffic coloring in google maps or different colors based of some other underlaying criteria.

### What other alternatives are available?

In leaflet this is possible

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by JaffaKetchup** [comment]
Hey @digitalinnovationas,
Is there a reason you can't use multiple `Polyline`s?

**Comment by digitalinnovationas** [comment]
> Hey @digitalinnovationas, Is there a reason you can't use multiple `Polyline`s?

The underlaying color states are not static but dynamic, although the polyline is static....e.g. a given geographic road is always the same, but the colored state can change within it. 

Well, I quess it would be possible to subclass PolyLine and PolyLayer myself, to obtain it adding a color a point to the previous...

**Comment by JaffaKetchup** [comment]
Well, even if you change the color, the entire line needs redrawing internally. So it's probably more performant to redraw only a part of the line (a single `Polyline`) than an entire long `Polyline` with dynamic/individual line coloring support.

**Comment by digitalinnovationas** [comment]
ok, it would be a kind of a segmentedMultiPolyLine then (type linked PolyLineOfPolylines)....well I guess it can work with some effort. If the polyLine is not ectremely long i quess the performance drop is not so huge in case of indvidual coloring - it may also be an option.
thanks
