### ISSUE TITLE
[BUG] Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by danishkhawaja98** [fleaflet/flutter_map#1621]
### What is the bug?

1. **What were you implementing when you found this issue?**
   - I was implementing the Mapbox map screen.
   - The issue occurred while I was zooming in and out on the map.

2. **What happens when the bug triggers?**
   - The app crashes with a fatal exception.
   - The error message indicates that an unsupported operation occurred: "Infinity or NaN toInt".
   - The error occurs while building a widget.

3. **Crash Analytics Report:**
   ```
   Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
   Unsupported operation: Infinity or NaN toInt. Error thrown building Widget.
   at double.floor(dart:core)
   at PointExtension.floor(point_extensions.dart:38)
   at MapCamera.pixelBoundsAtZoom(camera.dart:277)
   at MapCamera.pixelBounds(camera.dart:268)
   at MarkerLayer.build(marker_layer.dart:214)
   at StatelessElement.build(framework.dart:5156)
   ...
   ```

4. **What do you think should have happened instead?**
   - The app should not crash due to this error.
   - When zooming in and out on the map, the app should function smoothly without any issues.
   - The error related to "Infinity or NaN toInt" should be handled appropriately to prevent the crash.

### How can we reproduce it?

**How to Reproduce the Issue:**
   - Navigate to any map screen within the example app.
   - Zoom in on the map until it's fully zoomed in.
   - As the map is in the process of rendering, perform a zoom-out action using a two-finger gesture.
   - The app should encounter the "Unsupported operation: Infinity or NaN toInt" error and potentially crash.
   
**Example Code:**

```
FlutterMap(
                    mapController: _mapController,
                    options: 
                    MapOptions(
                        onMapReady: () => _onMapReady(context),
                        cameraConstraint: CameraConstraint.contain(
                          bounds: LatLngBounds(
                            const LatLng(-90, -180),
                            const LatLng(90, 180),
                          ),
                        ),
                        initialZoom: 5,
                        interactionOptions: InteractionOptions(enableMultiFingerGestureRace: true),
                        initialCenter: LatLng(
                            26.368557, -80.20081)
                    ),
                    children: [
                      TileLayer(
                        urlTemplate: 'https://api.mapbox.com........LrA',
                        additionalOptions: const {
                          'mapStyleId': 'clio........p74nq',
                          'accessToken': 'pk...........LrA',
                        },
                      ),
                      CircleLayer(
                        circles: _circleMarker,
                      ),
                      MarkerLayer(
                        markers: _listOfMarkers,
                      ),
                    ],
                  )
```

### Platforms

Android 12 (Galaxy A02s)

### Severity

Fatal: Causes the application to crash

**Comment by danishkhawaja98** [comment]
The same error occurs again but now with the different report

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unsupported operation: Infinity or NaN toInt. Error thrown building Widget.
       at double.round(dart:core)
       at PointExtension.round(point_extensions.dart:26)
       at MapCamera.pixelOrigin(camera.dart:93)
       at MapCamera.getOffsetFromOrigin(camera.dart:257)
       at CircleLayer.build.<fn>.<fn>(circle_layer.dart:41)
       at SetBase.toList(dart:collection)
       at CircleLayer.build.<fn>(circle_layer.dart:57)
       at _LayoutBuilderElement._layout.layoutCallback(layout_builder.dart:119)
       at BuildOwner.buildScope(framework.dart:2720)
       at _LayoutBuilderElement._layout(layout_builder.dart:153)
       at RenderObject.invokeLayoutCallback.<fn>(object.dart:2506)
       at PipelineOwner._enableMutationsToDirtySubtrees(object.dart:1062)
       at RenderObject.invokeLayoutCallback(object.dart:2506)
       at RenderConstrainedLayoutBuilder.rebuildIfNecessary(layout_builder.dart:228)
       at _RenderLayoutBuilder.performLayout(layout_builder.dart:313)
       at RenderObject.layout(object.dart:2395)
       at RenderBox.layout(box.dart:2386)
       at ChildLayoutHelper.layoutChild(layout_helper.dart:52)
       at RenderStack._computeSize(stack.dart:580)
       at RenderStack.performLayout(stack.dart:607)
       at RenderObject._layoutWithoutResize(object.dart:2234)
       at PipelineOwner.flushLayout(object.dart:1016)
       at RendererBinding.drawFrame(binding.dart:492)
       at WidgetsBinding.drawFrame(binding.dart:905)
       at RendererBinding._handlePersistentFrameCallback(binding.dart:358)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1284)
       at SchedulerBinding.handleDrawFrame(binding.dart:1214)
       at SchedulerBinding._handleDrawFrame(binding.dart:1072)    
```


I believe there is no proper error handling in your `point_extensions.dart` file

**Comment by JaffaKetchup** [comment]
Hey @danishkhawaja98,

Unfortunately, I cannot seem to reproduce this. Just to check, it appears as though you're already using v6, which is in beta?

However, from your second log, it appears as though the issue is within the `CircleMarker` layer instead of somewhere else, which you did not include in your example code. Can you post an MRE with the `CircleMarker`?

**Comment by danishkhawaja98** [comment]
> Hey @danishkhawaja98,
> 
> Unfortunately, I cannot seem to reproduce this. Just to check, it appears as though you're already using v6, which is in beta?
> 

Hi @JaffaKetchup 

Yes I have got the error on both stable and beta version (i.e v5 and v6).


> However, from your second log, it appears as though the issue is within the `CircleMarker` layer instead of somewhere else, which you did not include in your example code. Can you post an MRE with the `CircleMarker`?

Here is the code snippet of my `CircleMarkerLayer` and `MarkerLayer`

```
_circleMarker.add(CircleMarker(
              useRadiusInMeter: true,
              point: LatLng(_updatedAtmList.first['latitude'],
                  _updatedAtmList.first['longitude']),
              color: Colors.transparent,
              borderColor: HexColor('#1A8AE5'),
              borderStrokeWidth: 3,
              radius: double.parse(radiusInMeters.toString())));

          _updatedAtmList.forEach((element) {
            _listOfMarkers.add(Marker(
              height: 40,
              width: 40,
              point: LatLng(element['latitude'], element['longitude']),
              builder: (_) {
                return GestureDetector(
                  onTap: () => _onMarkerTapped(
                    {
                      'data': element,
                      'atm_locations': _updatedAtmList,
                    },
                  ),
                  child: Image.asset(
                    'assets/images/AppIcon.png',
                  ),
                );
              },
            ));
          });
```

**Comment by danishkhawaja98** [comment]
Hi @JaffaKetchup 

While I was going through the old PR, I found out that this issue was resolved in PR #1388, but in the latest code there was no such file available where the issue was resolved.

Can you please have a look into this?

Thanks

**Comment by JaffaKetchup** [comment]
I need a minimal set of `CircleMarker`s. Enough to reproduce the issue, but also not tied into your state system in any way. I cannot run the code above as is.

I think it's unlikely that #1388 resolved the same issue as this, especially if the issue does indeed turn out to be in the `CircleMarkerLayer`.

**Comment by danishkhawaja98** [comment]
> _circleMarker.add(CircleMarker(
>               useRadiusInMeter: true,
>               point: LatLng(_updatedAtmList.first['latitude'],
>                   _updatedAtmList.first['longitude']),
>               color: Colors.transparent,
>               borderColor: HexColor('#1A8AE5'),
>               borderStrokeWidth: 3,
>               radius: double.parse(radiusInMeters.toString())));

This is my only `CircleMarkerLayer` that I am using in my whole code

```
_circleMarker.add(CircleMarker(
              useRadiusInMeter: true,
              point: LatLng(_updatedAtmList.first['latitude'],
                  _updatedAtmList.first['longitude']),
              color: Colors.transparent,
              borderColor: HexColor('#1A8AE5'),
              borderStrokeWidth: 3,
              radius: double.parse(radiusInMeters.toString())));
```

**Comment by danishkhawaja98** [comment]
Closing this issue, as i haven't got this issue in the `master` branch.
