### ISSUE TITLE
[BUG] Network images should be cached by URL

### ISSUE THREAD

**Issue by Robbendebiene** [fleaflet/flutter_map#1628]
### What is the bug?

Flutter map doesn't cache network images by URL, wherefore it does not reliable cache images in memory.

The caching key is obtained [here](https://github.com/fleaflet/flutter_map/blob/master/lib/src/layer/tile_layer/tile_provider/network_image_provider.dart#L57) and is based on the identity of `FlutterMapNetworkImageProvider`. Since `FlutterMapNetworkImageProvider` doesn't implement an equality function a tile will be re-fetched for every new instance regardless of the requested tile.

If using the older tile provider that was based on Flutter's `NetworkImage` provider the caching works as expected:
```dart
class CachedNetworkTileProvider extends TileProvider {
  CachedNetworkTileProvider({
    super.headers,
  });

  @override
  ImageProvider getImage(Coords<num> coords, TileLayer options) {
    return NetworkImage(
      getTileUrl(coords, options),
      headers: headers,
    );
  }
}
```

While its [obtainKey function](https://github.com/flutter/flutter/blob/e1e47221e86272429674bec4f1bd36acc4fc7b77/packages/flutter/lib/src/painting/_network_image_io.dart#L34-L36) is also based on the `NetworkImage` instance, `NetworkImage` [implements an equality](https://github.com/flutter/flutter/blob/e1e47221e86272429674bec4f1bd36acc4fc7b77/packages/flutter/lib/src/painting/_network_image_io.dart#L174-L182) function based on the image's `url` and `scale`.

### How can we reproduce it?

Use e.g. the example app

- load some tiles
- disable the internet connection
- zoom in/out till the map is blank
- zoom back to the previous level where the tiles were loaded
- observe the whole map being blank

 This can also be seen/tested using: https://demo.fleaflet.dev/tile_loading_error_handle

### Do you have a potential solution?

If my hypothesis is true then implementing an equality function for `FlutterMapNetworkImageProvider`, or reusing Flutter's `NetworkImage` provider should solve this.

### Platforms

Android

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
Hey @Robbendebiene,

You're quite right, I noticed this the other day and intended to fix it, but forgot.

I'll add equality methods to the image provider. We're unable to use Flutter's `NetworkImage` provider, because it doesn't support `fallbackUrl`.

Just to note to readers, this caching refers to caching in memory, within a single sessions. Regardless of whether an equality method is implemented, it will not affect caching between sessions.
