### ISSUE TITLE
Encourage users away from *.tile.openstreetmap.org

### ISSUE THREAD

**Issue by pnorman** [fleaflet/flutter_map#1631]
### What is the bug?

flutter_map users are using {a,b,c}.tile.openstreetmap.org URLs instead of tile.openstreetmap.org. This is discouraged, and may be deprecated in the future.

Using the old URLs is slower with HTTP/2 and HTTP/3, and will cause apps to break if the old URLs become unsupported.

https://github.com/openstreetmap/operations/issues/737

### How can we reproduce it?

See logs attached to https://github.com/openstreetmap/operations/issues/737#issuecomment-1698279868

### Platforms

N/A

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Thanks for the heads up.

However, at the moment, this package does not support HTTP/2. We're looking into ways to solve this for the next release.
Yes, this also means our documentation is wrong in recommending users NOT to use subdomains.

We will ask people to move away from subdomains in our next release announcement, once we've implemented HTTP/2.
