### ISSUE TITLE
File provider in latest version

### ISSUE THREAD

**Issue by faizanmohdizi** [fleaflet/flutter_map#1635]
### What do you want implemented?

what we can u use if you removed file tile provider in latest version....i need to show map file on offline which is zxy png image file

### Severity

Minimum: Not required for my use

**Comment by JaffaKetchup** [comment]
Hi @faizanmohdizi,
Can you confirm what version you are talking about? It appears to be visible in the API docs in both v5 and v6-dev.3, which would suggest they are public.

**Comment by faizanmohdizi** [comment]
> Hi @faizanmohdizi, Can you confirm what version you are talking about? It appears to be visible in the API docs in both v5 and v6-dev.3, which would suggest they are public.

in version flutter_map: ^6.0.0-dev.3....have u removed file tile provider.


and one more thing how can i directly show mbtiles file in flutter map

**Comment by JaffaKetchup** [comment]
I'm not sure if that is a question or a statement. As far as I can see, we have not removed `FileTileProvider`, and I'm not sure what has led you to believe that we have?

For help with mbtiles, please ask in Discussions or on the Discord server. mbtiles are not supported by FM. If they are raster, they need to be [unpacked into XYZ](https://github.com/alfanhui/mbtilesToPngs). If they are vector, they need to be rendered, or you need to use a plugin, as described on the docs site.

**Comment by faizanmohdizi** [comment]
thanks! 

i saw in change log.

previously u have that feature showing mbtiles directly by flutter map ..why u have removed that ?? this was the good feature

**Comment by JaffaKetchup** [comment]
Ok, I'll double check the changelog.

Mbtiles support was removed many moons ago, before I was involved with this project, so I'm not sure why it was removed. Possibly to simplify the library and remove the dependencies it requires.

**Comment by faizanmohdizi** [comment]
ok thanks!...please dont removed those offline support file tile provider and asset tile provider these are very usefull!

**Comment by JaffaKetchup** [comment]
I couldn't see anything in the CHANGELOG for v6 that suggested the `FileTileProvider` would be removed.

**Comment by faizanmohdizi** [comment]
ok!
