### ISSUE TITLE
[BUG] Failed host lookup

### ISSUE THREAD

**Issue by cavator** [fleaflet/flutter_map#1637]
### What is the bug?

if i follow the example with OSM it works, when i try to use api.mapbox.com to use a custom tilelayer i got this error
SocketException: Failed host lookup: 'api.mapbox.com' (OS Error: No address associated with hostname, errno = 7)
yes i have the internet in androidmanifest

```flutter
    urlTemplate: 'https://api.mapbox.com/styles/v1/cavator/clm4cehht028001p964hvem2n/tiles/{z}/{x}/{y}?access_token={token}',
          additionalOptions: const {
            'accessToken': "{token}",
            'id': 'mapbox.mapbox-streets-v7'
          },
```

**Comment by TesteurManiak** [comment]
Are you sure that you are trying to use rasterized tiles, not vector tiles?

**Comment by cavator** [comment]
i have no idea, i was used to google_maps so it's my first time using this tile layer thing, i found some poor examples on internet but all lacking any useful info or real example, if u have something i would be glad

**Comment by TesteurManiak** [comment]
The package documentation already contains explanations to [use MapBox with flutter_map](https://docs.fleaflet.dev/tile-servers/using-mapbox). Seems like this is not an issue with the package so I'm closing it. If you need an example you should ask in the [discord server](https://discord.gg/BwpEsjqMAH).
