### ISSUE TITLE
[BUG] Add missing plugins to the docs

### ISSUE THREAD

**Issue by josxha** [fleaflet/flutter_map#1638]
### What is the bug?

I noticed that my plugin [flutter_map_cache](https://pub.dev/packages/flutter_map_cache) is missing in the [flutter_map plugin list](https://docs.fleaflet.dev/v/v6-preview/plugins/list).

### How can we reproduce it?

https://docs.fleaflet.dev/v/v6-preview/plugins/list

### Do you have a potential solution?

There might be some other plugins missing so it might be worth updating that list.

### Platforms

documentation

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hey @josxha, apologies for not adding your plugin in sooner.
I'll also adjust the offline mapping section. Whilst my plugin is very capable of caching, the main reason for using it is bulk downloading, so I can add your plugin as preferred for caching-only, if that sounds good to you?

**Comment by josxha** [comment]
Hi @JaffaKetchup, thanks for the quick reply (and sorry for my delayed reply 😓). 
I've just seen that you already updated the flutter_maps docs. Thanks a lot! 
...and for updating the page on offline tiles too (:
