### ISSUE TITLE
[BUG] camera member doesn't exsists

### ISSUE THREAD

**Issue by pishguy** [fleaflet/flutter_map#1639]
### What is the bug?

Which version of this library does the 'camera' parameter exist in? I have tested versions 4 and 5, and I did encounter any errors for these versions.

```dart
void updatePoint(MapEvent? event, BuildContext context) {
  latLng = mapController.camera.pointToLatLng(Point(pointX, pointY));
}
```

**Comment by JaffaKetchup** [comment]
Hi @pishguy,
This is for v6. The master branch and examples are all for v6.
