### ISSUE TITLE
[FEATURE] Specify Z value of markers and polygons

### ISSUE THREAD

**Issue by PvtPuddles** [fleaflet/flutter_map#1640]
### What do you want implemented?

I have a map that displays two types of equipment; controllers and gateways.  For our users, it is more important to see gateways than controllers.

I would like to be able to specify z-values in our controller and gateway markers to determine which markers should be displayed on top, similar to the google maps plugin. 

In the future, when our team implements polygons to mark locations of interest, I would like to make sure they draw on the bottom.  (I am aware that putting the polygonLayer under the markerLayer will have this effect, but I imagine it would be useful to specify polygon z values relative to each other, as well).

### What other alternatives are available?

The best work around I can think of is to make sure that all the markers I want to draw on top are at the bottom of our `Markers` list, but this doesn't seem intuitive.

### Severity

Minimum: Not required for my use

**Comment by ibrierley** [comment]
Just draw everything in order, including the layers ? You can have multiple layers if needed.

**Comment by JaffaKetchup** [comment]
Closing, as I'm not sure why the workaround you mentioned "doesn't seem intuitive": that's how many things in Flutter work (such as `Flex`s and `Stack`s).
Please ping if you would like this re-opened.
