### ISSUE TITLE
[BUG] getPixelBounds occasionally results in exception: Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by greensopinion** [fleaflet/flutter_map#1645]
### What is the bug?

Exception at runtime:

```
#0      double.floor (third_party/dart/sdk/lib/_internal/vm/lib/double.dart)
#1      CustomPoint.floor (~/.pub-cache/hosted/pub.dev/flutter_map-5.0.0/lib/src/misc/point.dart:58:31)
#2      FlutterMapState.getPixelBounds (~/.pub-cache/hosted/pub.dev/flutter_map-5.0.0/lib/src/map/state.dart:593:47)
#3      FlutterMapState.initState (~/.pub-cache/hosted/pub.dev/flutter_map-5.0.0/lib/src/map/state.dart:38:20)
#4      StatefulElement._firstBuild (~/development/flutter/packages/flutter/lib/src/widgets/framework.dart:5430:55)
```

### How can we reproduce it?

I haven't created a reproduction scenario yet

Is this the same issue as #1522 ?

### Platforms

all

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by JaffaKetchup** [comment]
Hey @greensopinion,
This is likely the same as #1522, which was fixed by #1585, released in v6.0.0-dev.2.
I'm going to close this, please reopen if you can still reproduce on the latest prerelease.

**Comment by greensopinion** [comment]
I have a reproduction scenario: 

```
final nan = 0.0/0.0; // <-- provides NaN

MapOptions(
                          zoom: nan,
...
)
```

The solution is to avoid passing in `NaN` for zoom

**Comment by JaffaKetchup** [comment]
@RicardoRB Please create a new issue with a full MRE if this still happens to you with the latest v6.1.0.
