### ISSUE TITLE
Crash on uncaught "Invalid image data" exception

### ISSUE THREAD

**Issue by s6o** [fleaflet/flutter_map#1649]
### What is the bug?

When running a custom tile server, in the case of a missing tile we can get back zero bytes. Resulting in the decode function failure in _loadAsync of FlutterMapNetworkImageProvider.

### How can we reproduce it?

Use a custom tile server that on a missing tile return zero bytes.

### Do you have a potential solution?

Looking at the _loadAsync implementation, the call to the decode function was left out of the try/catch block. Simply moving the decode function call inside the try block fixes the issue - the app no longer crashes on a missing tile.

### Platforms

MacOS Ventura 13.5.1 (M1)

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Thanks for reporting this! I'm not sure that this would cause a fatal error, but yes, it is still an issue.

**Comment by s6o** [comment]
> Thanks for reporting this! I'm not sure that this would cause a fatal error, but yes, it is still an issue.

Yes correct, in release mode it does not crash, but now less annoying in debug mode/development :-)

**Comment by JaffaKetchup** [comment]
Sure. This also means `fallbackUrl` will now be attempted where the exception is thrown from `decode` instead of during the network request.
