### ISSUE TITLE
[BUG] onTap is not working in Marker Widget on Map..

### ISSUE THREAD

**Issue by HeinKoZin** [fleaflet/flutter_map#1656]
### What is the bug?

onTap method is not working like I exptected.

### How can we reproduce it?

How can I make onTap method working well?

### Platforms

Android, iOS

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @HeinKoZin, please can you be a little more detailed?

**Comment by HeinKoZin** [comment]
Hi @JaffaKetchup,

Here is my code of Marker Widget.

`Marker(
                        width: 50,
                        height: 50,
                        point: LatLng(
                          double.parse(ambulances[index].location.lat),
                          double.parse(ambulances[index].location.lon),
                        ),
                        builder: (context) => GestureDetector(
                          onTap: () {
                            showAmbulance(index);
                          },
                          child: SvgPicture.asset(
                            "assets/svg/ambulance.svg",
                            height: 100,
                            width: 100,
                          ),
                        ),
                      )`

onTap of GestureDetector is not working when I click on this widget.

**Comment by JaffaKetchup** [comment]
Is the `MarkerLayer` last in the list of children?

**Comment by HeinKoZin** [comment]
> Is the `MarkerLayer` last in the list of children?

I forgot it bro. It's worked now.  Thank you.

**Comment by maxiggle** [comment]
I seem to have the same issue with Gesture detector for mapper

**Comment by maxiggle** [comment]
```
Marker buildPin(LatLng point, String customMarker, {String? title}) {
    return Marker(
      point: point,
      child: Stack(
        children: [
          Positioned(
            left: 35,
            top: 12,
            child: Container(
              width: 250.w,
              height: 50,
              decoration: BoxDecoration(
                color: bgsplashColor,
                borderRadius: BorderRadius.circular(100),
              ),
              child: Center(child: Text(title!)),
            ),
          ),
          Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(50),
              border: Border.all(
                  width: 5, color: bgsplashColor, style: BorderStyle.solid),
            ),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(100),
              child: GestureDetector(
                onTap: () {
                  log('message');
                  PopUpMarker(point);
                },
                child: Image.network(
                  customMarker,
                  fit: BoxFit.fitHeight,
                ),
              ),
            ),
          ),
        ],
      ),
      width: 250.w,
      height: 70.h,
    );
    
```
