### ISSUE TITLE
[FEATURE] Reintroduce keys on `Polygon`s

### ISSUE THREAD

**Issue by sirkalmi** [fleaflet/flutter_map#1657]
### What do you want implemented?

As a reminder, the 3.1.0 changelog:

[3.1.0] - 2022/12/21 
Contains the following additions/removals:

...
Added Keys to Polygons, Polylines, and CircleMarkers - #1402 & #1403
...

What can be used instead if I want to assign an arbitrary object? I want to read it as a result of the onTap event.

### Severity

Annoying: Currently have to use workarounds

**Comment by JaffaKetchup** [comment]
This appears to have been removed in 86a080c. Not sure why, will need to investigate.

**Comment by JaffaKetchup** [comment]
There should be methods that don't use keys. For example, I'm not sure how you're building the list of `Polygon`s, but you should be able to get a 'key' from a list, for example by `map`ping the list - but there might be more performant ways.

**Comment by josxha** [comment]
I don't think it makes sense to have a key property for polygons as long as they are not used by `flutter_map`.
@sirkalmi if you need custom properties, you can extend from `Polygon` and add all custom properties to the polygon that you need:
```dart
class MyPolygon extends Polygon {
  final Key key;

  MyPolygon({required this.key, required super.points});
}
```

Voting to close this issue as not planned.

**Comment by sirkalmi** [comment]
Thanks for the tip, that's how I solved the problem.

**Comment by sirkalmi** [comment]
> I don't think it makes sense to add a key property to the `Polygon` class as long as it isn't used by `flutter_map` internally.
> 
> @sirkalmi if you need custom properties, you can extend from `Polygon` and add all custom properties to the polygon that you need:
> 
> ```dart
> class MyPolygon extends Polygon {
>   final Key key;
> 
>   MyPolygon({required this.key, required super.points});
> }
> ```
> 
> Voting to close this issue as not planned.

Thanks for the tip, that's how I solved the problem.
