### ISSUE TITLE
[BUG] Impeller: `RotatedOverlayImage` is clipped incorrectly

### ISSUE THREAD

**Issue by adouglass** [fleaflet/flutter_map#1658]
### What is the bug?

When viewing a rotated overlay image on a map -- the image presents in full only at a zoom level that would allow the entire unrotated image to fit in the current camera/bounds.

Once you zoom into the map, the rotated image becomes clipped in what appears to be a pre-transformed camera/widget boundary.
![Simulator Screen Recording - iPhone 15 Pro Max - 2023-09-20 at 19 20 26](https://github.com/fleaflet/flutter_map/assets/2176621/93b3a175-f8a6-4816-baf1-5650f1a3d2ae)

### How can we reproduce it?

Open the v5.0.0 examples project and run in a simulator.
Navigate to the Overlay Image example, and pan/zoom around the rotated image.

### Platforms

iOS 17

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
Hi @adouglass,

I have a strange feeling this has to do with Impeller. Issues have been caused with `OverlayImage` in the past by Impeller.

Try using `--no-enable-impeller` to disable running with Impeller and see if that fixes your issue. If it does, this needs to be reported to the Flutter team.

**Comment by adouglass** [comment]
Thank you @JaffaKetchup! Running with `--no-enable-impeller` does indeed fix the issue.
I'll try writing it up for the Flutter team.

**Comment by JaffaKetchup** [comment]
Reported to the Flutter team in flutter/flutter#138687.
