### ISSUE TITLE
[FEATURE] Add `TileLayer` `urlTemplate` placeholder for `tileSize`

### ISSUE THREAD

**Issue by bramp** [fleaflet/flutter_map#1664]
### What do you want implemented?

`TileLayer` accepts a `tileSize` as well as a `urlTemplate`. Mapbox supports Static Tile URLs of the form `https://api.mapbox.com/styles/v1/{username}/{style_id}/tiles/{tilesize}/{z}/{x}/{y}{@2x}`

When using Mapbox you need to specify the tileSize twice, e.g

```dart
TileLayer(
   tileSize: 512,
   urlTemplate: 'https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/512/{z}/{x}/{y}{r}?access_token={accessToken}',
)
```

This can be error prone.

My proposal is a new placeholder, `{d}` (for dimension) that is replaced with the tile size, so I can now provide a url like `'https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/{d}/{z}/{x}/{y}{r}?access_token={accessToken}'` and not worry about ensuring I write 512 twice.

### What other alternatives are available?

A little bit of duplication

### Can you provide any other information?

Happy to send a very modest (one-line) patch.

### Severity

Annoying: Currently have to use workarounds

**Comment by JaffaKetchup** [comment]
This should be relatively easy. One interesting thing to note is that they don't actually have to match. Add to this retina mode, and it can all be quite confusing, with some combinations seemingly having no effect.
I should be able to get a PR for this done, but it will probably be more than one line!
