### ISSUE TITLE
Try using a constructor or factory that is 'const'.     LatLng initialCenter = const LatLng(50.5, 30.51)[BUG] <title>

### ISSUE THREAD

**Issue by hridoycse197** [fleaflet/flutter_map#1683]
### What is the bug?

when i update flutter map into latest version. then shows  Try using a constructor or factory that is 'const'.
    LatLng initialCenter = const LatLng(50.5, 30.51),

### How can we reproduce it?

 CameraConstraint get cameraConstraint =>
      _cameraConstraint ??
      (maxBounds != null
          ? CameraConstraint.contain(bounds: maxBounds!)
          : CameraConstraint.contain(
              bounds:
                  LatLngBounds(const LatLng(-90, -180), const LatLng(90, 180)),
            ));

### Platforms

Android

### Severity

Minimum: Allows normal functioning

**Comment by hridoycse197** [comment]
when i run code. it shows

**Comment by JaffaKetchup** [comment]
Where does it show? Can you provide an MRE?

**Comment by hridoycse197** [comment]
![IMG-20231010-WA0002.jpg](https://github.com/fleaflet/flutter_map/assets/47745174/36d37e6c-9b62-4c01-ba79-b44496d6268e)

**Comment by hridoycse197** [comment]
https://github.com/hridoycse197/Flutter-Map-check.git


you can check my repository

**Comment by JaffaKetchup** [comment]
Try updating your latlong2 version.

**Comment by JaffaKetchup** [comment]
With no further information, we're going to assume that this issue has been resolved.
