### ISSUE TITLE
[FEATURE] Tappable `Polyline`s

### ISSUE THREAD

**Issue by thomascoumau** [fleaflet/flutter_map#1685]
### What do you want implemented?

I wanted to implement an onTap for PolylineLayer. This tap could be specific for each polyline in the layer.

### What other alternatives are available?

There is a package TappablePolyline, however, the tap is not really functional and the layer take the size of the all map so the mapTap is inconsistently triggered

### Can you provide any other information?

I will propose a PR soon

### Severity

Annoying: Currently have to use workarounds

**Comment by thomascoumau** [comment]
I have made a draft PR for now [here](https://github.com/fleaflet/flutter_map/pull/1686)

**Comment by thomascoumau** [comment]
I have opened #1697 in order to prepare future PR's in both FM and FMTP repo in the future.

**Comment by JaffaKetchup** [comment]
I'm going to close this for now, as this won't be included in the core.
