### ISSUE TITLE
[FEATURE] Support reading pmtiles URLs

### ISSUE THREAD

**Issue by bramp** [fleaflet/flutter_map#1690]
### What do you want implemented?

[pmtiles](https://docs.protomaps.com/pmtiles/) are a way to host a entire tileset in a single file, that can be queried with issuing HTTP range-reads instead of multiple /z/x/y URL fetches.

This makes it very easy to host a single file, instead of 100,000s individual tiles (which in many cases are duplicates). This can reduce serving and hosting costs for self-hosted tilesets.

The proposal is most likely to create a new Tile Provider, that understands this format, and can work with the existing TileLayer.

### What other alternatives are available?

Use normal Slippy Map/CARTO/XYZ URLs.

### Can you provide any other information?

The spec is here: https://github.com/protomaps/PMTiles/blob/main/spec/v3/spec.md

Multiple other libraries, [maplibre](https://docs.protomaps.com/pmtiles/maplibre), [leaflet](https://docs.protomaps.com/pmtiles/leaflet) and [OpenLayers](https://docs.protomaps.com/pmtiles/openlayers) support this.

### Severity

Minimum: Not required for my use

**Comment by JaffaKetchup** [comment]
It may make sense to make this into a plugin.

**Comment by JaffaKetchup** [comment]
I'm going to close this for now, as I think a plugin is the best way to proceed with this.
Happy to add it to the docs should anyone want to have a go! Hadn't heard of pmtiles before, but the concept certainly seems interesting.

**Comment by bramp** [comment]
ack. I might implement this as I may have to host my own tiles, and this seems far more efficient protocol. I'll ping this bug if I create a plugin.

**Comment by coogle** [comment]
I'm also interested in this, and just to add to it there is already a dart library for working with these packages that just looks like it needs a `flutter_map` plugin wrapped around it?

https://pub.dev/packages/pmtiles

**Comment by bramp** [comment]
I'm the author of that package :-). But yes there needs to be a FlutterMaps plugin. I think that plugin would be hosted in a separate project. FYI I currently have no plans to write that plugin, but happy to support the pmtiles package.

**Comment by coogle** [comment]
I'll take a look-see at writing a plugin for it... it'll require me of course figuring out how to write plugins and specifically tile plugins :) Any pointers on the broad-strokes of that might get me up to speed on what actually needs to be written would be a welcome leg-up.

**Comment by JaffaKetchup** [comment]
I would imagine that it can just be put into a `TileProvider` backed by a custom `ImageProvider`, which relies on the package?
The basics are here: https://docs.fleaflet.dev/plugins/making-a-plugin/creating-new-tile-providers. And if you need more, have a look at the `TileProvider`s within FM's source code.

**Comment by josxha** [comment]
I haven't seen any packages for pmtiles support for flutter_map on pub.dev, so I wrote my own tile provider and can publish it once the following pr has been merged:
- https://github.com/bramp/pmtiles-dart/pull/1

**Comment by ethicnology** [comment]
Hi @josxha, Do you have an example to make `flutter_map` works with `protomaps` `https://api.protomaps.com/tiles/v3/{z}/{x}/{y}.mvt` ?

**Comment by josxha** [comment]
@ethicnology I don't have an example but as you're trying to use vector tiles I recommend to follow the flutter_map documentation on how to use vector tiles.

**Comment by ethicnology** [comment]
The file format seems not supported
