### ISSUE TITLE
[BUG] v6: New default constraints cause trapped zooms on different screen sizes

### ISSUE THREAD

**Issue by mattmyne** [fleaflet/flutter_map#1699]
### What is the bug?

In my `MapOptions` I include:

`initialZoom: 1.5,
minZoom: 1.5,`

In v5.0.0 this worked as expected.
In v6.0.0:

Seems to work as expected on Android emulator.
On Chrome, it allows further zoom in but cannot zoom out until zoom level is greater than 3 (and then only allows zoom down to 3, not 1.5 requested).
On Windows 11 (x64) zoom is frozen - cannot zoom in or out - if `initialZoom` set below 3.
I've not tested on macOS/iOS.

Setting `minZoom` to a value greater or equal to 3 works as expected (doesn't allow zoom less than whatever it's set to) on all platforms tested.

It seems like `minZoom` is internally limited to no less than 3?

I've tried changing `minNativeZoom` and `minZoom` on the `TileLayer` but this has no effect (given they both default to zero anyway this is unsurprising).

### How can we reproduce it?

Set `initialZoom` and/or `minZoom` to a value less than 3 in `MapOptions` and try and zoom on affected platforms.

### Platforms

Windows 11 (x64), Edge, Android Emulator

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by mattmyne** [comment]
Sorry, it seems it cannot be below 2 - not 3

**Comment by JaffaKetchup** [comment]
I'm assuming this is todo with display size, and therefore #1682.

**Comment by JaffaKetchup** [comment]
Yep, I've opened #1682 to revert this commit. I didn't release it would cause so many issues!
