### ISSUE TITLE
[FEATURE] Improve error handling of built-in image provider

### ISSUE THREAD

**Issue by JaffaKetchup** [fleaflet/flutter_map#1703]
### What do you want implemented?

As discussed in #1698.

* Reduce the number of errors that trigger breakpoints when debugging
* Achieve an effect similar to what is seen in Flutter's `NetworkImage`

### Can you provide any other information?

The behaviour has changed in v6 from v5 due to changed error handling. In combination with using `loadBytes` instead of lower-level IO, this triggers more errors, but allows us to keep our code simple and platform independent.

It is also worth saying that the current implementation may not be performant in comparison to a standard `NetworkImage`, but more testing is need to validate this. See #1698 for an issue designated for reporting/tracking the performance of the tile provider.

### Severity

Annoying: Currently have to use workarounds

**Comment by robiness** [comment]
Commenting on [manlyman29](https://github.com/manlyman29)

We also ran into this when migrating to V6.
Previously we had a `static TileLayer,` so only a single instant was used, leading into those `Client already closed` errors.
Making it a getter, or caching the `HttpClient` did solve the problem for us.

**Comment by manlyman29** [comment]
I did tried the solution @robiness mentioned on the other issue. While it seems the breakpoint happens less, it still happens sometimes.

The users comment:

> We also ran into this when migrating to V6.
> Previously we had a static TileLayer, so only a single instant was used, leading into those Client already closed errors.
> Making it a getter, or caching the HttpClient did solve the problem for us.

Another user mentioned this might be because of animated_map_controller. I can't test but worth mentioning maybe useful for someone else encoutering this.

**Comment by manlyman29** [comment]
This comment reduced encountering this:
https://github.com/fleaflet/flutter_map/issues/1698#issuecomment-1814640362

I have seen this being an issue in two cases:
1-Map moving immediately to another place while still loading.
2-In a responsive environment, we have a different instance of map for desktop and mobile. While resizing the screen, as soon as the breakpoint is reached, it goes into this error loop state.
This is from CancellableTileLayer, Same on NetworkTileLayer.
![Screenshot 2023-11-17 at 10 55 47](https://github.com/fleaflet/flutter_map/assets/63221039/2ee3e1c9-ef71-44dc-97ce-0bd11cbe01f0)

**Comment by JaffaKetchup** [comment]
Also see https://github.com/fleaflet/flutter_map/issues/1698#issuecomment-1834594893.

**Comment by JaffaKetchup** [comment]
Merging back into #1698, as the issues are closely related and the discussions are intertwined anyway.
