### ISSUE TITLE
[BUG] Circles not working

### ISSUE THREAD

**Issue by Navil** [fleaflet/flutter_map#1711]
### What is the bug?

The circles are not working anymore since version 6.0.0. The circle is just showing correct when it is in the bottom half of the screen.
<img width="353" alt="image" src="https://github.com/fleaflet/flutter_map/assets/3436399/dd6bae08-6520-4e45-8bb2-523e1eeffde5">

### How can we reproduce it?

This can be reproduced in the example you provided.

### Platforms

iOS 17.0 Simulator

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
Hi @Navil,
Have you tried the v6.0.1 version?

**Comment by Navil** [comment]
Yes. Same issue there

**Comment by JaffaKetchup** [comment]
Ok, can you try disabling Impeller?

**Comment by Navil** [comment]
Thank you. Disabling Impeller fixes the issue. So I am gonna keep it disabled until the fix lands on stable.

**Comment by JaffaKetchup** [comment]
Closing for now!
