### ISSUE TITLE
[FEATURE] Performance optimization for polygon rendering

### ISSUE THREAD

**Issue by QixianWu** [fleaflet/flutter_map#1719]
### What do you want implemented?

When I am drawing large polygons (such as national plates), the sliding is not smooth and the frame count drops severely. Preliminary investigation shows that 'MapCamera.getOffsetFromOrigin' requires a lot of time. It is unclear whether isolate can be used for optimization?

<img width="1002" alt="image" src="https://github.com/fleaflet/flutter_map/assets/28887269/330bdbbd-113d-48f7-9e8b-ed5ff4d16840">

<img width="1357" alt="image" src="https://github.com/fleaflet/flutter_map/assets/28887269/00552eb2-2bd2-46cf-b8f6-503a6918e929">

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by ibrierley** [comment]
How many points are there in the polys in total ?

**Comment by QixianWu** [comment]
> How many points are there in the polys in total ?

20659

**Comment by QixianWu** [comment]
<img width="260" alt="image" src="https://github.com/fleaflet/flutter_map/assets/28887269/e678048f-a773-466b-970d-e0c00f00adc1">

I want to achieve an effect similar to this, but the largest polygon has approximately 85000 points, which I find difficult to implement

**Comment by QixianWu** [comment]
[Simplify](https://github.com/bjartebore/simplify)

Simplifying collection points through this library can achieve perfect implementation.

<img width="369" alt="image" src="https://github.com/fleaflet/flutter_map/assets/28887269/c1998738-13fd-412b-be1e-2d94d621a713">

**Comment by JaffaKetchup** [comment]
@QixianWu This might be becoming to FM soon!
