### ISSUE TITLE
[BUG] TileLayer: tileBounds not working after upgrade from flutter_map 5 to 6

### ISSUE THREAD

**Issue by hpoul** [fleaflet/flutter_map#1720]
### What is the bug?

I tried upgrading from `flutter_map` 5.0 to 6.0 but the `tileBounds` in the `TileLayer` seem to no longer work. Map tiles aren't loaded at all. I used the same implementation which worked for me in 5.0

### How can we reproduce it?

Simply adding a `tileBounds` to the example app stops loading any tiles.
e.g. in `example/lib/pages/home.dart` line 81:

```
                  TileLayer(
                    tileBounds: LatLngBounds(
                      LatLng(49.260, -7.255),
                      LatLng(54.655, 2.429),
                    ),
                    urlTemplate:
                        'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                    userAgentPackageName: 'dev.fleaflet.flutter_map.example',
                  ),
```
imho this should load (parts of) the UK.

![](https://github.com/fleaflet/flutter_map/assets/313066/5f765a29-99a5-4150-869f-28823910ba4f)

### Do you have a potential solution?

Maybe this is related to #1689 ?

### Platforms

Tested on Android 13

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by josxha** [comment]
Hi @hpoul, this is a duplicate to https://github.com/fleaflet/flutter_map/issues/1710. It should be fixed in the master branch but hasn't been released to pub.dev yet.
If you want you can verify on your own and reopen this issue in case there is still a problem.
