### ISSUE TITLE
FlutterMapState doesn't support with the latest version 6.0.1

### ISSUE THREAD

**Issue by george-brandidea** [fleaflet/flutter_map#1722]
### What is the bug?

Recently I updated to the latest version which is 6.0.1. But this version doesn't have FlutterMapState. When I use this it doesn't accept and I am getting this error "Undefined name 'FlutterMapState'. Try correcting the name to one that is defined, or defining the name.". What is the alerternate for this?

### How can we reproduce it?

FlutterMapState has been removed from the latest version.

### Platforms

Android all versions

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by george-brandidea** [comment]
Like this 

![image](https://github.com/fleaflet/flutter_map/assets/137067736/7c0a3380-7f63-42ed-a82b-66dbf222ce9f)

**Comment by george-brandidea** [comment]
![image](https://github.com/fleaflet/flutter_map/assets/137067736/f3af80ec-718b-4b89-94ac-67e5604ec56e)

**Comment by TesteurManiak** [comment]
Please check the documentation to migrate to v6: https://docs.fleaflet.dev/getting-started/migrating-to-v6

**Comment by JaffaKetchup** [comment]
Apologies, this migration in particular wasn't the most obviously explained. I've refactored it a bit, hopefully https://docs.fleaflet.dev/getting-started/migrating-to-v6#fluttermapstate-has-been-removed will be what you need now.

**Comment by george-brandidea** [comment]
Sounds good. Now I got one more issue like the below one. After I updated I got the below issue too. "scaleBy()" not working.

![image](https://github.com/fleaflet/flutter_map/assets/137067736/61772fc1-3866-4738-87a7-b2869f3da175)

**Comment by JaffaKetchup** [comment]
Try using the multiply operator '*'.

**Comment by george-brandidea** [comment]
Can you give me a code for that @JaffaKetchup
