### ISSUE TITLE
[FEATURE] Compress images within documentation

### ISSUE THREAD

**Issue by Zverik** [fleaflet/flutter_map#1770]
### What is the bug?

There are png images in the documentation of sizes like 2000×3000 and sizes more than a megabyte. This leads to very slow loading and high network load.

### How can we reproduce it?

See https://docs.fleaflet.dev/usage/layers for an example: the map at the center weights 4.3 megabytes. I don't see any reason for this size.

### Do you have a potential solution?

Please compress those, maybe into jpegs.

### Platforms

Browsers

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
The image mentioned in the original report appears to be the only unnecessarily large image. The rest are measured in low KB.

**Comment by JaffaKetchup** [comment]
Fixed by f6352a739b2067881da5901c00ca4d1e64333abc.

**Comment by Zverik** [comment]
Thank you!

Just in case, I clicked through all pages and also found `Cover.png` of 2.11 MB on https://docs.fleaflet.dev/#demonstration . Every other image is below 400k, which is acceptable :)

**Comment by JaffaKetchup** [comment]
Yep, missed that! Compressed that one as well (thanks to @josxha).
