### ISSUE TITLE
[FEATURE] (Re-)Support absolute `Marker` alignment

### ISSUE THREAD

**Issue by JaffaKetchup** [fleaflet/flutter_map#1771]
### What do you want implemented?

Since v6, `Marker`s can only be aligned relatively (on a scale of 0-1) through `Alignment`. It would be good for there to be an alternative constructor that takes a number of pixels from each edge, and the size of the `Marker`, and calculates the relative `Alignment`.

### What other alternatives are available?

As an example, given the width (`w`) and number of pixels to offset from the left (`d`), the formula `1.0 - 2 * d / w` can be used, as suggested by @Zverik in https://github.com/fleaflet/flutter_map/pull/1659#issuecomment-1849013832.

### Severity

Annoying: Currently have to use workarounds

**Comment by monsieurtanuki** [comment]
@JaffaKetchup @josxha May I work on this issue?

**Comment by JaffaKetchup** [comment]
Hey @monsieurtanuki,
Sure, we appricate any help we can get :)
