### ISSUE TITLE
[BUG] TileLayer with WMTS not showing background transparent

### ISSUE THREAD

**Issue by Velliane** [fleaflet/flutter_map#1778]
### What is the bug?

I don't know if it's really bug, or if it's my fault, but I'm trying to add layer to my map. When using WMS, it works fine using `WMSTileLayerOptions`. But for WMTS, i use directly `urlTemplate` but can't add transparent background, there's always white background.

Did i miss something ? Is it about the url ?

<img width="263" alt="Capture d’écran 2023-12-15 à 15 40 53" src="https://github.com/fleaflet/flutter_map/assets/44947503/1a8f18db-826f-44e2-8626-1d858eea1834">

Thanks for your help

### How can we reproduce it?

```dart
class Map extends StatelessWidget {
  const Map({super.key});

  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      options: MapOptions(
        backgroundColor: Colors.transparent,
        initialZoom: 7,
      ),
      children: [
        TileLayer(
          urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
        ),
        TileLayer(
          urlTemplate:
              "https://wxs.ign.fr/pratique/geoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&TILEMATRIXSET=PM&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&STYLE=normal&FORMAT=image/png&TILECOL={x}&TILEROW={y}&TILEMATRIX={z}",
        ),
      ],
    );
  }
}
```

### Platforms

Android/IOS

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @Velliane,
Sorry for the long response time, I'm sure you've figured it out by now, but I think this is the tile server itself returning the while tiles? It bends and text overlaps into it, and there's no reason for FM to show white here, so I can only assume it is this.

![Screenshot demonstraing the above words](https://github.com/fleaflet/flutter_map/assets/58115698/94565942-376f-494c-81cd-62080ffaac7a)

Happy to help in future if needed, and again, apologies about the delay :)
