### ISSUE TITLE
[FEATURE] <Poligon Line>

### ISSUE THREAD

**Issue by ivanzhadnov** [fleaflet/flutter_map#1780]
### What do you want implemented?

Please advice if it is possible to draw a polygon contour line consisting of two colors.
<img width="377" alt="pic" src="https://github.com/fleaflet/flutter_map/assets/44845863/073a6e9c-5ab8-44ec-831b-83ad8c9cf7c7">
add labels at border of polygon
<img width="421" alt="pic2" src="https://github.com/fleaflet/flutter_map/assets/44845863/e40a1291-7478-4a69-881e-0e9a2c4d7d78">

please advice any idia
thanks!

### Severity

Annoying: Currently have to use workarounds

**Comment by josxha** [comment]
Please don't misuse a feature request to ask for help.

**Comment by JaffaKetchup** [comment]
This is out of scope for FM. Please use two polygons, and an overlaid widget for the label (there's a plugin which can help with that).
