### ISSUE TITLE
为什么flutter_map不支持windows?

### ISSUE THREAD

**Issue by yuanmaio** [fleaflet/flutter_map#1783]
### What is the bug?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/415b1d0b-2566-4e36-9ca9-3d1c28300b22)

### How can we reproduce it?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/1fb4d4f9-4209-4202-91ab-9c717df11e8d)

### Do you have a potential solution?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/26a21161-ee1b-454a-b934-4133335a6651)

### Platforms

windows 11

### Severity

Minimum: Allows normal functioning

**Comment by yuanmaio** [comment]
![image](https://github.com/fleaflet/flutter_map/assets/8166762/ef487e71-4bc2-4824-b178-1b5a227b7457)

**Comment by JaffaKetchup** [comment]
We support running on all platforms. It looks like something is incorrectly configured in your environment.
