### ISSUE TITLE
flutter map可以实现点击marker出现图层吗？可以的话，怎么实现？

### ISSUE THREAD

**Issue by yuanmaio** [fleaflet/flutter_map#1787]
### What do you want implemented?

flutter map可以实现点击marker出现图层吗？可以的话，怎么实现？

### What other alternatives are available?

flutter map可以实现点击marker出现图层吗？可以的话，怎么实现？

### Severity

Minimum: Not required for my use

**Comment by JaffaKetchup** [comment]
Hi @yuanmaio,
We're unable to offer support in languages other than English.
I've translated your question and it appears you're asking how to make tappable markers. You can use a `GestureDetector` inside the `Marker.child` as you would for any other widget.
If you need more help, please ask in English.

**Comment by yuanmaio** [comment]
![image](https://github.com/fleaflet/flutter_map/assets/8166762/a6bedd49-57ca-4e0c-bd7e-a42045ac46ae)
I use gesture，but no response
