### ISSUE TITLE
there add marker GestureDetector,but no response 

### ISSUE THREAD

**Issue by yuanmaio** [fleaflet/flutter_map#1788]
### What do you want implemented?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/0506f71d-4fb3-4a96-b253-2811a0fbd0e5)

### What other alternatives are available?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/1c53333a-4370-45d2-9e0c-04d4ccbbbb41)

### Can you provide any other information?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/d9fd7694-ccda-4753-a91b-0cde99b79152)

### Severity

Minimum: Not required for my use

**Comment by yuanmaio** [comment]
please tell me  to solve that clicking marker has a response

**Comment by josxha** [comment]
Please don't abuse a feature request to ask for help and don't spam the same picture in every input field.
I'm no native english speaker myself but that's no excuse for low effort in asking a question.

You need to put the `MarkerLayer` as the last child of the list.
