### ISSUE TITLE
[FEATURE] Apple MapKit Tile Server

### ISSUE THREAD

**Issue by Wallman** [fleaflet/flutter_map#1792]
### What do you want implemented?

Considering pricing, I would love to have [Apple MapKit](https://developer.apple.com/documentation/mapkitjs) (JS?) as a Tile Server. Is this possible?

I could not find anything about it [here](https://docs.fleaflet.dev/tile-servers/other-options)

### What other alternatives are available?

Other Tile Severs listed [here](https://docs.fleaflet.dev/tile-servers/using-mapbox)

### Severity

Annoying: Currently have to use workarounds

**Comment by TesteurManiak** [comment]
MapKit JS is a framework not a tile provider. It doesn't seem like the tiles are accessible to 3rd party services.
flutter_map supports tile providers with **raster tiles** (as explained in the doc you have linked).

Implementing support for MapKit is out of scope for this project.
