### ISSUE TITLE
ADD A WMS Source in Flutter_map

### ISSUE THREAD

**Issue by m-hamza-tanbits** [fleaflet/flutter_map#1797]
### What do you want implemented?

<img width="1435" alt="Screenshot 2024-01-15 at 12 39 16 PM" src="https://github.com/fleaflet/flutter_map/assets/153491287/89d8b2db-526a-4f42-84e2-7a9ba3399aee">
I want to add WMS Layer in flutter map, 
how i can add multiple layers in flutter map. 
**https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015**
This is tile url for WMS source, please share a demo code how i can use WMS layer in flutter_map.

### Severity

Minimum: Not required for my use

**Comment by josxha** [comment]
Please don't abuse a feature request to ask for help or implementation advice.

- There is an example implementation for WMS in the example app: https://github.com/fleaflet/flutter_map/blob/ec81782c50ebc9191885f48d886f2e9e0fdead80/example/lib/pages/wms_tile_layer.dart
- If you want to see how you can use the WMSTileLayerOptions, have a look at: https://pub.dev/documentation/flutter_map/latest/flutter_map/WMSTileLayerOptions-class.html
- You can use multiple tile layers by adding multiple layers to the `children` property of FlutterMap.
