### ISSUE TITLE
Offline Map

### ISSUE THREAD

**Issue by faizanmohdizi** [fleaflet/flutter_map#1811]
### What do you want implemented?

i want to show mbtiles file  into flutter_map. how i can i achieve this..is it possible to show direct mbtiles file to flutter map.

### Severity

Minimum: Not required for my use

**Comment by JaffaKetchup** [comment]
Hi @faizanmohdizi,
Before asking for help, please check the documentation, and ask in the Discord server if you still need to: it helps us help you quicker!
Please see https://docs.fleaflet.dev/tile-servers/offline-mapping#bundled-map-tiles.
