### ISSUE TITLE
[FEATURE]  CircleLayer with child

### ISSUE THREAD

**Issue by thorito** [fleaflet/flutter_map#1819]
### What do you want implemented?

I would like the CircleMarker to be able to add a widget.
For example, when the user taps, show a popup

### Severity

Minimum: Not required for my use

**Comment by josxha** [comment]
It won't be possible to have child widgets in the CircleLayer because a circle is not a widget itself.
If you need to display widgets please use the MarkerLayer instead with a round child widget.
