### ISSUE TITLE
[FEATURE] The quality of the map is very low

### ISSUE THREAD

**Issue by alireza-hnzpv** [fleaflet/flutter_map#1859]
### What do you want implemented?

hello,
The texture quality of the map is very low. The user feels that he is watching the image. For example, the Google map is very high quality. The way one feels is not an image but an object.

### Severity

Annoying: Currently have to use workarounds

**Comment by josxha** [comment]
flutter_map is vendor free, you might want to look into retina mode or vector tiles.
Closing since this is not a feature request.
