### ISSUE TITLE
[FEATURE] When rotating the map, it is hoped that the label of the map will remain upright and consistent with the mobile native platform experience

### ISSUE THREAD

**Issue by soulcure** [fleaflet/flutter_map#1863]
### What do you want implemented?

When rotating the map, it is hoped that the label of the map will remain upright and consistent with the mobile native platform experience.

now:
https://github.com/fleaflet/flutter_map/assets/7369232/bd58aba6-1f45-4a31-b9ce-0dd34144e16c

Looking forward to features:
https://github.com/fleaflet/flutter_map/assets/7369232/3172a0ea-9883-448c-89c2-df790dd45263

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by ibrierley** [comment]
This can only happen with vector maps/tiles rather than raster ones, so you could look at the vector tile plugin.

**Comment by JaffaKetchup** [comment]
Please see https://docs.fleaflet.dev/#how-can-i-use-a-custom-map-style-how-can-i-prevent-poi-labels-rotating-when-the-map-rotates-how-can for more info.
