### ISSUE TITLE
[BUG] Retina simulation not working on WMTS URL templates without {r} parameter in V7-beta

### ISSUE THREAD

**Issue by Henk-Keijzer** [fleaflet/flutter_map#1866]
### What is the bug?

As in the title: Retina simulation not working on WMTS URL templates without {r} parameter in V7-beta.
I set the retinaMode to RetinaMode.isHighDensity(context). During debugging I can see this is true on a high density screen and false on a low density screen, but the labels on the Open Street Map (url without {r} are virtaully unreadable.

Manually setting the retinaMode:
low density screen: true => text is small (unreadable)
                               false => text is readable
high density screen: true => text is small (unreadable)
                                 false => text is readable

### How can we reproduce it?

Should not be too difficult to reproduce...

### Platforms

windows, web an android (haven't tested on iOS)

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by Henk-Keijzer** [comment]
Hi Luka,

Here is an example main.dart. See comments in lines 145 etc
Select different maptile providers in lines 35/36

Met vriendelijke groet,
Stichting Zeilvaart Warmond
Henk Keijzer

**Comment by JaffaKetchup** [comment]
I think you may be misunderstanding the expected result. Some tile servers don't support retina natively (with the '{r}' param), so by setting `retinaMode` `true`, you are telling flutter_map to emulate it.
As stated in the [documentation](https://docs.fleaflet.dev/layers/tile-layer#retina-mode), this emulation can cause results like this, where text and POIs get smaller.
It's up to you/users whether you prefer higher quality 'tiles' at the expense of smaller details or not.
You can restore larger text and POIs by disabling the parameter, or finding a tile server which does support retina tiles natively.

Please also take note of https://operations.osmfoundation.org/policies/tiles/. Please don't use OSM tiles directly in any production environment.

If you need any more help, please ping me!

**Comment by Henk-Keijzer** [comment]
Hu Luka,

The documentation says:

If it is not present, but retinaMode is enabled, then flutter_map will simulate retina behaviour by requesting four tiles at a larger zoom level and combining them together in place of one.

Just above that it says:

It is recommended to enable retina mode on high density displays (especially where the server natively supports retina tiles). This can be done by calling RetinaMode.isHighDensity with the current BuildContext, and passing the result to TileLayer.retinaMode.

So, my interpretation was: always set retineMode to RetinaMode.isHighDensity, and you are always safe. But that does not seem to be correct..... I think the documentation can be improved a bit... Or we have to find a real solution to the problem, that takes into account both the true pixelsize of the screen and the DigitalPixelRatio.

On my windows laptop the DPR is the same as the scaling factor, set in the Windows display settings (scale 100% -> dpr 1.0, scale 150% -> dpr 1.5). The MediaQuery screensize (actually windowsize) already takes this into account because on a 3456x2160 screen, with a window covering about 2/3rds of the screen it shows as something like 1200 x 800 pixels. So, you need to find the real physical number of pixels to make a good calculation...

Best regards,
Henk Keijzer

**Comment by JaffaKetchup** [comment]
Ah, I can see how the documentation could be confusing. I've updated it: https://docs.fleaflet.dev/v/v7-beta/layers/tile-layer#retina-mode!

I think the current solution is fine, it just needs to be a bit better understood, which hopefully this update should help with.
