### ISSUE TITLE
Add privacy manifest file for iOS

### ISSUE THREAD

**Issue by FaiazRahman100** [fleaflet/flutter_map#1872]
### What do you want implemented?

# Feature Request

You need to add PrivacyInfo.xcprivacy file following the new apple policy.

Describe the feature
Refer link: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Platforms affected (mark all that apply)

✅📱 iOS

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by JaffaKetchup** [comment]
Hi @FaiazRahman100,
As far as I am aware, we are not required to do this. We are a package, not a plugin, therefore we cannot create build config files.
Additionally, there's no restrictions on what 3rd party APIs can be used through flutter_map, so we couldn't write an explanation for all of them.
I may have misunderstood something though, I'm not great with iOS, so please let me know if I have.

**Comment by josxha** [comment]
flutter_map indeed does not use any iOS SDKs. You're mixing up flutter packages with XCFrameworks, Swift packages or Xcode projects that are mentioned in the article. Only those iOS SDKs need to add the manifest.
