### ISSUE TITLE
Dragging polygon/polyline

### ISSUE THREAD

**Issue by glin94** [fleaflet/flutter_map#1873]
### What do you want implemented?

Add a dragging feature to polygons and polylines 

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by JaffaKetchup** [comment]
Hi @glin94,
This is out of scope for flutter_map. However, there is a plugin available: https://github.com/ibrierley/flutter_map_line_editor! Alternatively, you can try creating your own.
