### ISSUE TITLE
[BUG] v7-beta: polygon becomes distorted & invisible (but remains interactive) when zoomed far in

### ISSUE THREAD

**Issue by RuoLiDevelop** [fleaflet/flutter_map#1877]
### What is the bug?

this question is the same as issues #1864,polygon becomes distorted & invisible (but remains interactive) when zoomed far in.

### How can we reproduce it?

[screen-capture.webm](https://github.com/fleaflet/flutter_map/assets/47424927/1fbe25f4-d20f-4f04-8958-c7960390a33f)

### Platforms

macos chrome 

### Severity

Minimum: Allows normal functioning

**Comment by monsieurtanuki** [comment]
Hi @RuoLiDevelop!

In the latest code the lines are supposed to be always correct (I tested up to zoom 32 in https://github.com/fleaflet/flutter_map/issues/1864#issuecomment-2088204503). There's still an issue with the areas, in high zoom levels (e.g. 25+) (cf. https://github.com/fleaflet/flutter_map/issues/1864#issuecomment-2088672940).

I'm very surprised you're still experiencing display issues _regarding lines_: are you using the latest code - the one that included https://github.com/fleaflet/flutter_map/pull/1871?

**Comment by RuoLiDevelop** [comment]
> Hi @RuoLiDevelop!
> 
> In the latest code the lines are supposed to be always correct (I tested up to zoom 32 in [#1864 (comment)](https://github.com/fleaflet/flutter_map/issues/1864#issuecomment-2088204503)). There's still an issue with the areas, in high zoom levels (e.g. 25+) (cf. [#1864 (comment)](https://github.com/fleaflet/flutter_map/issues/1864#issuecomment-2088672940)).
> 
> I'm very surprised you're still experiencing display issues _regarding lines_: are you using the latest code - the one that included #1871?

thank you for your reply,
In the latest code, the problem still exists

**Comment by monsieurtanuki** [comment]
@RuoLiDevelop Please provide a code example, not a video. I managed to go up to zoom level 32 without distortions. Your issue may be related to the zoom gesture not zooming to the right place when the zoom level is too high.

**Comment by RuoLiDevelop** [comment]
> @RuoLiDevelop Please provide a code example, not a video. I managed to go up to zoom level 32 without distortions. Your issue may be related to the zoom gesture not zooming to the right place when the zoom level is too high.

I am using an example demo,It may not be related to gestures, as high zoom polygons may shake.

**Comment by JaffaKetchup** [comment]
I would prefer to just ignore the issue, put it down to precision, and add a note to the documentation. But also fine with limiting the max zoom if you prefer. No real usecase should need to use zoom level 32 (except maybe non-geographical maps, like games/floor plans?).

**Comment by josxha** [comment]
I ask myself if double percision limitations have an effect on those zoom levels. 🤔 But I agree, zoom level above 32 (and probably way before) are out of scope.
