### ISSUE TITLE
[BUG] map rotation is always possible on web even with InteractiveFlag set to InteractiveFlag.none

### ISSUE THREAD

**Issue by okoumea** [fleaflet/flutter_map#1878]
### What is the bug?

When all interactions are disabled, user can still rotate the map on web.

### How can we reproduce it?

setting interactionOptions to `InteractionOptions(flags: InteractiveFlag.none)`
```
FlutterMap(
                  options: MapOptions(InteractionOptions(flags: InteractiveFlag.none)
),
```
Rotate the map on web using ctrl + mouse click & drag

### Platforms

web

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by josxha** [comment]
Thanks for the bug report. See the answer here https://github.com/fleaflet/flutter_map/issues/811#issuecomment-2096064622

**Comment by okoumea** [comment]
Ok know its working, I didn't notice that there were 2 ways to disable rotation thank you !

```
  interactionOptions: InteractionOptions(
    cursorKeyboardRotationOptions: CursorKeyboardRotationOptions.disabled(),
    flags: InteractiveFlag.all & ~InteractiveFlag.rotate
  )

```
