### ISSUE TITLE
Load data from an external GeoJSON file

### ISSUE THREAD

**Issue by m-hamza-tanbits** [fleaflet/flutter_map#1881]
### What do you want implemented?

<img width="610" alt="image" src="https://github.com/fleaflet/flutter_map/assets/153491287/14bed4cf-a8c2-4798-945e-1e6b43c7bc8e">

in map box we can extract from data from file due to large amount of data .
Example code
```dart
    mapController!.addSource(
      'multiPolygons', // Unique ID for the source
      GeojsonSourceProperties(
        data: 'https://s3.ap-southeast-1.amazonaws.com/isn-landscape/isn/public/1/original/map%20(18)_1715585465413072.geojson'
        // 'https://s3.ap-southeast-1.amazonaws.com/isn-landscape/isn/public/1/original/map (19)_1715664018556365.geojson',
      ),
    );
```
Is there any way we can achieve this
while i am using http and get data from url and show in map, the map goes stuck.
    

### What other alternatives are available?

```dart
    mapController!.addSource(
      'multiPolygons', // Unique ID for the source
      GeojsonSourceProperties(
        data: 'https://s3.ap-southeast-1.amazonaws.com/isn-landscape/isn/public/1/original/map%20(18)_1715585465413072.geojson'
        // 'https://s3.ap-southeast-1.amazonaws.com/isn-landscape/isn/public/1/original/map (19)_1715664018556365.geojson',
      ),
    );
```

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by JaffaKetchup** [comment]
Please read the documentation and check for previous issues. GeoJSON support is outside of our scope. However, there is a plugin available: https://github.com/jozes/flutter_map_geojson.

**Comment by josxha** [comment]
There are actually two plugins that add geojson support, both are up-to-date and seem valid options:
- https://pub.dev/packages/power_geojson
- https://pub.dev/packages/flutter_map_geojson
