### ISSUE TITLE
[BUG] Cannot use the package on flutter 3.22

### ISSUE THREAD

**Issue by SoroushBeigi** [fleaflet/flutter_map#1889]
### What is the bug?

The latest flutter update has totally  replaced some theme-related objects which were deprecated before and the package cannot be used on the latest flutter version. I'm willing to solve this issue and create a PR.

### How can we reproduce it?

deprecated and removed codes must be replaced.

### Do you have a potential solution?

I can migrate the plugin to the latest flutter and dart version

### Platforms

All

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Hi @SoroushBeigi,
This has been fixed in #1883. Please use the master branch if using Flutter 2.22 is a requirement. We hope to release a new prerelease or version in the coming days.
