### ISSUE TITLE
[BUG] `Polygon`s and `Polyline`s don't update when `points` modified

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [fleaflet/flutter_map#1894]
### What is the bug?

After adding new points to polygon, it's not updating automatically. You should explicitly add UniqueKey to Polygon widget. 

### How can we reproduce it?

To reproduce you can view min sample in [github](https://github.com/tologonkudaiberdiuulu/map_draw). To solve you can uncomment "// key: UniqueKey()," part in map_page.dart file

### Do you have a potential solution?

No

### Platforms

All

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
This issue is occuring because the equality checking for elements is not working correctly.
A temporary workaround is shown in the invalid issue https://github.com/flutter/flutter/issues/106743: use `List.from` to create a new list instance.

**Comment by tologonkudaiberdiuulu** [comment]
Then maybe when overriding "=" operator, you should check manually? Not using listEquals function?

**Comment by JaffaKetchup** [comment]
It's not due to that. Its because the list instance is shared, so the list on the `oldWidget` and new`widget` are always the same.

**Comment by tologonkudaiberdiuulu** [comment]
I already tried to make like this 
<img width="362" alt="image" src="https://github.com/fleaflet/flutter_map/assets/47391827/b772a5a8-2293-4699-98b4-3e479cf12c69">

It's also not working. Only way to work is creating "mapsPolygons" variable also from new instance of List.
Like this:
<img width="306" alt="image" src="https://github.com/fleaflet/flutter_map/assets/47391827/a7297c71-83c5-4ad6-9071-33989aef6d18">

**Comment by JaffaKetchup** [comment]
I generally wouldn't recommend doing what you're doing. Instead, use `List<List<LatLng>>.map((coords) {}).toList()` on the `coordinates` list, in the `build` method. This may also resolve the issue as well.

```dart
final coordinates = <List<LatLng>>[...];

// inside `build`
PolygonLayer(
	polygons: coordinates.map((c) => Polygon(points: c)).toList(),
),
```
