### ISSUE TITLE
Drawing interactive polygons in real time [FEATURE] <title>

### ISSUE THREAD

**Issue by masoudafrakhteh** [fleaflet/flutter_map#1900]
### What do you want implemented?

1. Drawing filled up or dashed polygons in real time using mouse clicks for windows
2. User can make a left click to start drawing 
3. User will only hover mouse to continue drawing ( no need to press and hold)
4. User will make a 2nd left click indicating that drawing is finalized
5. User should decide on whether to save or discard the drawn polygon:

- To save , make a right click
- To discard , a long left click  press 

### Can you provide any other information?

I have implemented this to some extent BUT only the last polygon is showed , they are all saved though
Here is the modified version of the page from fluttermap package :
[polygon_draw.txt](https://github.com/user-attachments/files/15520557/polygon_draw.txt)

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by ibrierley** [comment]
You could always take a look at https://github.com/ibrierley/flutter_map_line_editor if any use.

**Comment by masoudafrakhteh** [comment]
Well, I just used it and thanks for the recommendation; however, this example also overwrites the only one polygon which is drawn. I am trying to see more than one polygon on the map drawn and kept showing.

**Comment by JaffaKetchup** [comment]
I believe the Every Door app does this for `Polyline`s: https://discord.com/channels/951867686378409984/989576405580918804/1229341271072575509 & https://github.com/Zverik/every_door/blob/main/lib/screens/modes/notes.dart#L130. Maybe you can adapt this for `Polygon`s.
The FMTC example app also supports drawing of polygons in two modes: either move the map, and the point is added at the center crosshairs on tap, or tap and the point is added at tap location. The code is at https://github.com/JaffaKetchup/flutter_map_tile_caching/tree/main/example/lib/screens/main/pages/region_selection, but it will need some decomposing as it does quite a lot more. (It's also GPL licensed).

However, this is out of scope for the core.
