### ISSUE TITLE
[BUG] FlutterFlow dependencies issue on meta 1.12.0

### ISSUE THREAD

**Issue by madi-rachidi** [fleaflet/flutter_map#1910]
### What is the bug?

using **FlutterFlow** i have this issue : Because every version of flutter_test from sdk depends on meta 1.11.0 and flutter_map >=7.0.0 depends on meta ^1.12.0, flutter_test from sdk is incompatible with flutter_map >=7.0.0.
So, because your app depends on both flutter_map ^7.0.0 and flutter_test from sdk, version solving failed.

### How can we reproduce it?

Use flutterFlow

### Do you have a potential solution?

Using **FlutterFlow**, I am unable to modify my pubspec.yaml and overriding the version. It would be very helpful to publish a new version

### Platforms

FlutterFlow

### Severity

Fatal: Causes the application to crash

**Comment by mootw** [comment]
I believe you can solve this issue by upgrading the flutter SDK in flutter flow to a newer version.

flutter_map depends on: ^1.12.0
your flutterflow SDK depends on: 1.11.0

**Comment by JaffaKetchup** [comment]
Fixed by #1897, very similar to #1896.
