### ISSUE TITLE
[FEATURE] Remove logger dependencies

### ISSUE THREAD

**Issue by perelman7** [fleaflet/flutter_map#1916]
### What do you want implemented?

Please remove logger dependencies, because it is not importent for implementation, but stop using some other dependencies which use 'logger' too, I asked them for help too. 

Thanks for you lib a lot

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by perelman7** [comment]
or change logger version to any (<= >=)

**Comment by josxha** [comment]
Similar issue as https://github.com/fleaflet/flutter_map/issues/1896.

**Comment by josxha** [comment]
What other dependency are you using that uses an incompatible logger version to the version used in flutter_map?
flutter_map supports the latest version of the logger package.
