### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by raghadAL-Nehlawi** [fleaflet/flutter_map#1919]
### What do you want implemented?

Why is this feature needed?
User Experience: Providing localized names for countries and cities ensures that users from different linguistic backgrounds can use the app more comfortably and intuitively.
Accessibility: Localization improves accessibility by catering to users who may not be proficient in the application's default language.
Global Reach: Supporting multiple languages can help reach a broader audience, making the app more inclusive and user-friendly.

### Severity

Annoying: Currently have to use workarounds

**Comment by JaffaKetchup** [comment]
It is not possible for us to change the language of the map tiles. This is entirely under the control of the tile server.
