### ISSUE TITLE
[WASM] Make WASM available in flutter web

### ISSUE THREAD

**Issue by Trung15010802** [fleaflet/flutter_map#1923]
### What do you want implemented?

Make WASM available in flutter web

### Severity

Annoying: Currently have to use workarounds

**Comment by josxha** [comment]
Could you provide further details why you are not able to use flutter_map with WASM please?

**Comment by Trung15010802** [comment]
> Could you provide further details why you are not able to use flutter_map with WASM please?

I have some mistakes

**Comment by JaffaKetchup** [comment]
Hi @Trung15010802,
Could you explain what you mean by this? FM should support WASM (although the example and CTP plugin do not yet, since they require Dio).

**Comment by Trung15010802** [comment]
> Hi @Trung15010802, Could you explain what you mean by this? FM should support WASM (although the example and CTP plugin do not yet, since they require Dio).

Sorry for my mistake. I have some problem with ffi imported  NOT FM
