### ISSUE TITLE
[FEATURE] Support for 3D globe view

### ISSUE THREAD

**Issue by Espade** [fleaflet/flutter_map#1927]
### What do you want implemented?

Hi, this is cool project! Just wonder that do you have a plan for supporting a 3D globe view? 
![Screenshot 2024-06-30 at 21 13 03](https://github.com/fleaflet/flutter_map/assets/38678091/3679513f-05d3-4001-aecb-2ed775b22fe7)

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by JaffaKetchup** [comment]
Hi @Espade,
This is unfortunately currently out of scope - although some discussions have occurred previously on the topic, so I suggest you check for other issues!
