### ISSUE TITLE
[BUG] updating map children doesn't render changes

### ISSUE THREAD

**Issue by mjt-tt** [fleaflet/flutter_map#1937]
### What is the bug?

It feels like I'm missing something here, and perhaps this is just a behaviour change, but after upgrading flutter maps the way that a change to a maps children gets handled is different.

For context, we've been using flutter_map v6.2.1 and what we are doing in there is updating a polyline as location updates take place by updating the PolylineLayer child of the map with new versions of a polyline. This has worked fine in the version we were using, but when we upgraded the library to 7.0.1 it stopped working and those polyline updates did not have any effect.

If fact, making changes to any child layers within the map in this way didn't seem to be reflected in what is being rendered in the map. We are also using the flutter_map_location_marker and interestingly that seems to work fine so I think there is something happening with how the map is handling layers and changes being made to them (as in adding/removing/changing data within the layer).

So not sure if this is a bug and just a behaviour change that means we should be doing something different/additional when making changes to (Polyline) layers, any ideas/assistance would be appreciated.

### How can we reproduce it?

This is the function that creates the map:

  Widget _setupFlutterMap(
      BuildContext context,
      TourNavigationState state,
      String apiKey,
      MarkerLayer tourMarkers,
      double startLat,
      double startLong) {
    const styleUrl =
        "https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png";

    dio = Dio();
    cacheOptions = CacheOptions(
      store: retrieveMapCacheStore(),
      hitCacheOnErrorExcept: [], // for offline behaviour
    );
    dio.interceptors.add(
      DioCacheInterceptor(options: cacheOptions),
    );

    _routeMap = FlutterMap(
      options: MapOptions(
        initialCenter: ll.LatLng(startLat, startLong),
        // onPointerDown: _onPointerDown,
        // onPointerUp: _onPointerUp,
        initialZoom: 18,
      ),
      children: [
        const SimpleAttributionWidget(
          alignment: Alignment.bottomLeft,
          source:
              Text('Stadia Maps © OpenMapTiles © OpenStreetMap contributors'),
        ),
        TileLayer(
            urlTemplate: "$styleUrl?api_key={api_key}",
            additionalOptions: {"api_key": apiKey},
            maxZoom: 20,
            maxNativeZoom: 20,
            retinaMode: true,
            tileProvider: CachedTileProvider(
                dio: dio,
                // maxStale keeps the tile cached for the given Duration and
                // tries to revalidate the next time it gets requested
                maxStale: const Duration(days: 999),
                store: context
                    retrieveMapCacheStore())),
        PolylineLayer(
            polylines: [getRoute()]),
        //PolylineLayer(polylines: <Polyline>[]),
        CurrentLocationLayer(
          focalPoint: FocalPoint(
              ratio: (_deviceType == DeviceScreenType.tablet
                  ? Point<double>(0.0, 1.0)
                  : Point<double>(0.0, 1.4)),
              offset: Point<double>(0.0, -60.0)),
          alignDirectionStream: _followCurrentLocationStreamController.stream,
          alignPositionOnUpdate: _followOnLocationUpdate,
          alignDirectionOnUpdate: AlignOnUpdate.always,
          positionStream: _positionStreamController.stream,
          headingStream: _headingStreamController.stream,
          style: const LocationMarkerStyle(
            marker: DefaultLocationMarker(
              child: Icon(
                Icons.navigation,
                color: Colors.white,
              ),
            ),
            markerSize: Size(40, 40),
            markerDirection: MarkerDirection.heading,
          ),
        ),
        tourMarkers,
      ],
    );
    return _routeMap;
  }

when a location changes is received a function calls and makes updates to the map including (amongst other things) these calls:
    if ((_routeMap.children[2] as PolylineLayer).polylines.length == 1) {
      (_routeMap.children[2] as PolylineLayer).polylines.add(context
          getLineToStart(
              ll.LatLng(currentLocation.lat, currentLocation.long)));
    } else {
      (_routeMap.children[2] as PolylineLayer).polylines[1] =
          _getNavLine(currentLocation, currentRouteIdx);
    }

    _positionStreamController.add(LocationMarkerPosition(
        latitude: currentLocation.lat,
        longitude: currentLocation.long,
        accuracy: (currentLocation.locationAccuracy ?? 0)));

It is the logic around _routeMap above that seems to not have any affect on what is rendered in the map

### Do you have a potential solution?

Sorry, tried lots of things in the new version, disabling culling and other attempted workarounds, but nothing seems to work

### Platforms

Pixel 6a running Android 12

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
Hi @mjt-tt,
There's been some difficulties in this area recently, particularly with `PolylineLayer` and `PolygonLayer`, although I believe they are mostly fixed with the latest version.
Does this issue still occur with the latest version?

**Comment by JaffaKetchup** [comment]
Additionally, changing the children of widgets in this way shouldn't necessarily be expected to work.
I don't believe this behaviour would work with native Flutter widgets such as Row and Column for example: widgets aren't added to the children list, the children list is built from widgets.

For example, try having a list of coordinates, then `map`ping this to the desired elements (eg. `Polyline`s) at build time.
Alternatively (and possibly more expensively depending on specific implementation details), create a copy of the list of children every time before passing it to the widget/layer, by using `List.from(yourList)` in the layer arguments and maintaining the list yourself (the copy may not even be necessary here if you maintain the list yourself).

**Comment by JaffaKetchup** [comment]
I'm going to close this for now. I'll try to remember to explain this in the documentation, as we've had a few questions about this behaviour change recently. We'll also discuss internally.

If you want this re-opened, please let me know!

**Comment by mjt-tt** [comment]
ok, thanks @JaffaKetchup, that gives me some things to try and a nice description of what is going on, thanks for the explanation.
