### ISSUE TITLE
[BUG] onTap returns wrong LatLng when map rotated

### ISSUE THREAD

**Issue by eidolonFIRE** [fleaflet/flutter_map#1938]
### What is the bug?

`onTap` and `onLongPress` do not give correct `latlng` when map is rotated.

### How can we reproduce it?

flutter_map: 6.2.1

I am printing the latlng from the callbacks, they are not shifting correctly. I suspect something wrong with the new map_camera code.

### Platforms

android

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by eidolonFIRE** [comment]
Further investigation:

- When map is rotated 180* , the latlng points returned become correct again.
- The error in offset peaks at +90deg and -90deg map rotation, at which point the error can be high enough to put the points off the screen.
- The amount of error tracks with zoom level. IE, the amount error seems to be coming from something relative to screen position. It does not matter if you are at a high or low zoom level, the offset will appear the same pixel distance on the screen.
- The trendline orientation is maintained, only offset is added. IE, if you select a serious of points moving WEST, rotation will not angle the points trending in a different direction. The map rotation only adds offset to the series of points.

**Comment by eidolonFIRE** [comment]
I have further narrowed the issue down to `tapPosition.relative` which is very, very wrong. (so, `camera.offsetToCrs` doesn't seem like the culprit)

**Comment by JaffaKetchup** [comment]
Thanks for the report and investigation so far! This looks similar to #1934.

I wonder if the code was changed to always assume non-rotation? I'll try to have a look at the git diffs when I get a moment. We should ideally have one method to handle this.

**Comment by eidolonFIRE** [comment]
I have figured out a work-around for now! 🎉 

```
  onTap: (tapPosition, point) {
    // WORKAROUND - calculate relative offset ourselves
    final widgetBox = mapKey.currentContext?.findRenderObject()! as RenderBox?;
    if (widgetBox != null) {
      final relativeTapPos = tapPosition.global - widgetBox.localToGlobal(Offset.zero);
      final correctedLatLng = mapController.camera.offsetToCrs(relativeTapPos);
      // outgoing call...
      onMapTap(context, correctedLatLng);
    }
  },
 ```

**Comment by JaffaKetchup** [comment]
Thanks for the help, we'll look into it :) I just wonder what exactly changed and when.

**Comment by JaffaKetchup** [comment]
Hey @eidolonFIRE, do you know what version you were on previously?

**Comment by eidolonFIRE** [comment]
AH! I too couldn't reproduce in a clean project... So, I kept looking and discovered the real source of the broken relative position.
I was using plugin which put `MobileLayerTransformer` somewhere deep in my `FlutterMap(children: ...)` which was screwing things up.

https://github.com/eidolonFIRE/flutter_map_tappable_polyline/blob/master/lib/flutter_map_tappable_polyline.dart#L100

Sorry for the distraction!

**Comment by JaffaKetchup** [comment]
No worries :D. Although I'd be interested to know how MobileLayerTransformer breaks this alone, it could be an issue. But if they were being stacked or used improperly, then that would explain it.
