### ISSUE TITLE
[FEATURE] Update marker size / design on mouse onHover event

### ISSUE THREAD

**Issue by fvisticot** [fleaflet/flutter_map#1946]
### What do you want implemented?

I need to display detailed information when the mouse is hover a marker.
Regarding the "hover" property, the marker do not have the same size.

### What other alternatives are available?

I have tried to implement the isHover detection in the marker child widget BUT the size of the marker is FIXED for a marker and can not be updated from the isHover property. 
I need to set the marker size with the maximum size of the 2 markers configuration (normal or detailed)
It means that with this implementation, the hover detection is not detected on the child widget region but on the FIXED marker region

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by josxha** [comment]
The basic Marker widgets in flutter_map don't have toggleable states. If you want to change the size when the mouse hovers over a marker, you can add this logic yourself similar to how it is showcased in the example app for Polylines. In your case, use something like a [MouseRegion](https://api.flutter.dev/flutter/widgets/MouseRegion-class.html) to detect the hover event.
- hosted example app: https://demo.fleaflet.dev/polyline
- example code: https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/polyline.dart
