### ISSUE TITLE
[BUG] TileLayer deadlocks File IO with no internet

### ISSUE THREAD

**Issue by djnugent** [fleaflet/flutter_map#1947]
### What is the bug?

When testing my app in high packet loss environments (large conferences/events) the tile layer deadlocks the file system.

This happens in my app because it has an offline mode. So it loads cached data from the file system and then updates when it get internet again. I was testing this feature by setting my connection to 100% packet loss using network conditioner and noticed cached loads were locked for 10ish seconds. Upon further investigation I tracked it down to the tilelayer hitting a socket timeout. Once the socket timeout triggered the cache would load. Note: I cache json for other parts of the app, I DONT NOT CACHE THE MAP.

I found this incredibly odd since my cache uses filesystem I/O and the map uses network I/O. My suspicion is that tile layer is using the filesystem in some way and starting file I/O before the network call, holding the resource, while the network call is stalled by lack of internet. 

I tried setting keepBuffer to zero to see if that helped. I thought it did, but results were inconsistent (appeared to work on my main app but had no effect on the code below 🤷) Update: might help. See new comment

### How can we reproduce it?
You must use network conditioner to simulate packet loss (100% for best effect). Turning off wifi & cellular does not work! I believe this is because the flutter network stack is aware of interface operability. So the network degradation must be emulated on the transport layer. 

For more consistent reproducibility, make the start up time longer i.e. 3 seconds. That way the cache load is guaranteed to land in the middle of the tile load operation.

__pubspec.yaml__
```yaml
name: map_bug
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^7.0.2
  provider: ^6.1.2
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```
__main.dart__
```dart
import 'dart:io';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:provider/provider.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: ChangeNotifierProvider(
        create: (_) => CacheLoader()..init(),
        child: const MyHomePage(),
        lazy: false,
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FlutterMap(
          mapController: MapController(),
          children: [
            TileLayer(
              urlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
              keepBuffer: 1,
            ),
          ],
        ),
      ),
    );
  }
}

class CacheLoader with ChangeNotifier {
  String generateRandomString(int length) {
    var random = Random();

    const chars =
        'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    return List.generate(length, (index) => chars[random.nextInt(chars.length)])
        .join();
  }

  CacheLoader() {
    print("CacheLoader created");
  }

  Future<void> init() async {
    print("Simulate startup delay 1 second");
    await Future.delayed(Duration(seconds: 1));
    print("Delay complete");

    print("init started");

    var dir = await getApplicationDocumentsDirectory();
    print("Checking for cache existence");
    print("WE USUALLY GET STUCK HERE IF PACKET LOSS IS 100%");

    // Load from cache if it exists
    if (await File(dir.path + 'cache1.txt').exists()) {
      print("Loading from cache");
      await Future.wait([
        File(dir.path + 'cache1.txt').readAsString(),
        File(dir.path + 'cache2.txt').readAsString(),
        File(dir.path + 'cache3.txt').readAsString(),
        File(dir.path + 'cache4.txt').readAsString(),
        File(dir.path + 'cache5.txt').readAsString(),
        File(dir.path + 'cache6.txt').readAsString(),
      ]);
      print("Load from cache complete");
    } else {
      // Generate a bunch of random data in the cache files (5mb each)
      print("Generating random data in cache");
      await Future.wait([
        File(dir.path + 'cache1.txt')
            .writeAsString(generateRandomString(5 * 1024 * 1024)),
        File(dir.path + 'cache2.txt')
            .writeAsString(generateRandomString(5 * 1024 * 1024)),
        File(dir.path + 'cache3.txt')
            .writeAsString(generateRandomString(5 * 1024 * 1024)),
        File(dir.path + 'cache4.txt')
            .writeAsString(generateRandomString(5 * 1024 * 1024)),
        File(dir.path + 'cache5.txt')
            .writeAsString(generateRandomString(5 * 1024 * 1024)),
        File(dir.path + 'cache6.txt')
            .writeAsString(generateRandomString(5 * 1024 * 1024)),
      ]);
      print(
          "Generating random data in cache complete. Please restart application");
    }
    notifyListeners();
  }
}
```

### Do you have a potential solution?

If there is a file I/O used in tilelayer, use it after the network call.

### Platforms

All

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by djnugent** [comment]
Update: I think setting both `panBuffer` and `keepBuffer` to zero solves the issue. Not the proper solution, but a hit at the problem source.

**Comment by djnugent** [comment]
I tried looking at the tile layer src. I didnt see anything that would indicate the use of filesystem I/O. The only thing I can suspect is too many I/O operations of any kind cause a scheduler lock up. Maybe they are all on the same thread? So when increasing the load panBuffer and keepBuffer, more socket connections are being established. Im really shooting in the dark here. More experimentation is required but I'm pretty lost.

**Comment by JaffaKetchup** [comment]
Hi @djnugent,

Interestingly, this similar to something I've experienced recently, but not investigated and not linked back to FM. My FMTC plugin's example app new version was loading the cache database very slowly on initial load, and loaded immediately after the map loaded (but the map load also took longer than normal) - I wonder whether it's the same thing.

> So when increasing the load panBuffer and keepBuffer, more socket connections are being established

I would guess this is correct. `keepBuffer` is probably irrelevant, but reducing `panBuffer` reduces the number of network requests, and so reduces the issue.

I'm not sure what's best to investigate from here either.

I wonder whether it's also related to some slow map loading of bigger maps and apps with multiple maps.

**Comment by djnugent** [comment]
I tried digging some more into the event loop to understand if that's being blocked, but I dont think that's the case. According all sources I can find, flutter uses a single event loop, so if it locked up, so would the UI. And that's not happening in this case. 

However, it does sound like the network stack runs in either it's own isolate or own OS thread. If it runs an isolate and that isolate also runs the file io then maybe there could be contention would a bunch of network requests???? Maybe but that feels like a stupid design given how unreliable network connections are. Also the number of simultaneous connections isnt even that high.

Idk. i dont know enough about flutter or flutter map, to really understand whats happening here. 

The work around I listed works but it haunts me not knowing the real source of the bug.

**Comment by JaffaKetchup** [comment]
I'm not sure there is an issue with flutter_map here, I think it's just how Flutter/Dart works behind the scenes unfortunately.

If I have time at some point I might try to reproduce without flutter_map to see if I can file an issue to Flutter, but I don't have time right now unfortunately.
