### ISSUE TITLE
[BUG] On web - Hit Testing on any markers not work

### ISSUE THREAD

**Issue by codebombi** [fleaflet/flutter_map#1952]
### What is the bug?

On web - When the mouse button is pressed, Hit Testing on any markers not work

### How can we reproduce it?

Hold down the mouse left button and hover over the Polyline

### Platforms

WEB

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Please clarify this bug report by adding more detailed information, and a minimal reproducible example, and screen recording if possible. It is currently unclear what the issue is.

**Comment by codebombi** [comment]
> Please clarify this bug report by adding more detailed information, and a minimal reproducible example, and screen recording if possible. It is currently unclear what the issue is.

Thank you for the great flutter package and quick response, I have already solved the problem!
