### ISSUE TITLE
[BUG] WMS layer example no longer working

### ISSUE THREAD

**Issue by d01101010m** [fleaflet/flutter_map#1955]
### What is the bug?

It just shows a blank screen. It seems the baseUrl no longer works. In my app I'm getting the following error:

DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
I/flutter ( 3249): The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
I/flutter ( 3249): Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
I/flutter ( 3249): In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

### How can we reproduce it?

https://demo.fleaflet.dev/wms_layer

### Platforms

Android 15.0, PWA

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by monsieurtanuki** [comment]
From what I read in https://s2maps.eu/, it looks like the URL has to be changed
from
https://f.s2maps-tiles.eu/wms/?&service=WMS&request=GetMap&layers=s2cloudless-2021_3857&styles=&format=image%2Fpng&srs=EPSG%3A3857&version=1.1.1&transparent=true&width=256&height=256&bbox=0.0,6261721.357121641,626172.1357121639,6887893.492833804
to
https://tiles.maps.eox.at/wms?service=WMS&request=GetMap&layers=s2cloudless-2021_3857&styles=&format=image%2Fpng&srs=EPSG%3A3857&version=1.1.1&transparent=true&width=256&height=256&bbox=0.0,6261721.357121641,626172.1357121639,6887893.492833804

**Comment by monsieurtanuki** [comment]
I've just changed `baseUrl: 'https://{s}.s2maps-tiles.eu/wms/?',` into `baseUrl: 'https://tiles.maps.eox.at/wms?',` in `wms_tile_layer.dart`, et voilà:
![Screenshot_1726141645](https://github.com/user-attachments/assets/8eb878a9-b508-43ed-80f7-ac0f921f79c3)

I haven't taken the time to read potential licence issues.
If needed, ready to PR.
