### ISSUE TITLE
[FEATURE] disable caching for TileLayer

### ISSUE THREAD

**Issue by timur-harin** [fleaflet/flutter_map#1974]
### What do you want implemented?

I did not find how to disable caching or specify age of cache for TileLayer

### Can you provide any other information?

I already tried something like, but it does not work 

```
tileProvider: NetworkTileProvider(
                silenceExceptions: true,
                headers: {
                  'Cache-Control': 'max-age=1',
                },
              ),
```

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by timur-harin** [comment]
@JaffaKetchup
Please help with this problem

**Comment by JaffaKetchup** [comment]
The only caching included by default is session caching: see the note at the top of https://docs.fleaflet.dev/tile-servers/offline-mapping#caching. Please provide some additional detail if you need more help.
