### ISSUE TITLE
[FEATURE] loadingTileDisplay for TileLayer

### ISSUE THREAD

**Issue by edeetee** [fleaflet/flutter_map#1980]
### What do you want implemented?

Fallback to show a custom tile while tile is loading.

For my use case, I have a tile server serving transparent tiles. The tiles are mostly content:
<img width="400" alt="Screenshot 2024-10-19 at 6 11 42 PM" src="https://github.com/user-attachments/assets/00cded2d-734e-41e6-83dd-61f06d69fa8f">

When I load new tiles, the map doesn't render anything where it hasn't yet loaded:
<img width="400" alt="Screenshot 2024-10-19 at 6 12 33 PM" src="https://github.com/user-attachments/assets/4f85c5e2-0af6-4ef4-892c-65679d19461f">

It would be ideal if I had some way to provide a custom tile that can render content in the loading area. I would render with the transparent red I am using elsewhere.

For context, here is my layer code, containing an Opacity widget:
```
class NavigationAvailabilityOverlay extends ConsumerWidget {
  const NavigationAvailabilityOverlay({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Opacity(
      opacity: 0.5,
      child: TileLayer(
        tileProvider: CancellableNetworkTileProvider(),
        tileUpdateTransformer: TileUpdateTransformers.throttle(
          const Duration(milliseconds: 500),
        ),
        urlTemplate:
            "$devOrigin/routing/availability_tile.png?z={z}&y={y}&x={x}",
        tileDisplay: const TileDisplay.instantaneous(),
        maxNativeZoom: 22,
      ),
    );
  }
}
```

### What other alternatives are available?

I could add a background layer but this wouldn't work with the transparent tiles.

### Can you provide any other information?

I could be interested in implementing a pr if someone can give me some guidance to where I should start in the TileLayer code.

### Severity

Annoying: Currently have to use workarounds

**Comment by josxha** [comment]
Hi @edeetee, this functionality is already possible using the `tileBuilder`.
Return your loading widget when `tile.loadFinishedAt` is null.

- https://demo.fleaflet.dev/tile_builder
- https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/tile_builder.dart
