### ISSUE TITLE
[BUG] `Marker` child not appearing correctly

### ISSUE THREAD

**Issue by rizalahmaddd** [fleaflet/flutter_map#1995]
### What is the bug?

I encountered an issue while using the PulseIcon widget as a child of a Marker in a MarkerLayer. The widget does not behave as expected. The PulseIcon widget should display with a pulsing effect at the marker's location.
Could you please help me on this? 
Thank you!

<img width="339" alt="Screenshot 2024-11-27 at 22 52 07" src="https://github.com/user-attachments/assets/432b829a-a497-40c3-9a0b-1f09a4a17115">

### How can we reproduce it?

`MarkerLayer(
  markers: [
    Marker(
      point: LatLng(51.509364, -0.128928),
      child: PulseIcon(
        icon: Icons.location_on_rounded,
        pulseColor: App.primaryColor,
      ),
    ),
  ],
);`

### Platforms

Android

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment]
Hi @rizalahmaddd,
Please try changing the `height` and `width` parameters on the `Marker` itself. They are likely constraining the child.
