### ISSUE TITLE
'interactive' option doesn't block interaction

### ISSUE THREAD

**Issue by rafalbednarczuk** [fleaflet/flutter_map#20]
I want make flutter_map static, disable user input for it. I supposed setting interactive option to false would do this, but it doesn't change anything. How can it be solved?

**Comment by johnpryan** [comment]
Good find! the interactivity was recently moved into `MapGestureMixin`. 

If you want to take a crack at it, the fix would be to make `MapGestureMixin` check if `options.interactive` is false.

**Comment by johnpryan** [comment]
I think there's two places where gesture detection is happening, and only one is respecting the interaction parameter.

**Comment by raacker** [comment]
@johnpryan Does that mean custom GestureDetector on Marker should be disabled? https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/on_tap.dart#L30

I couldn't find any other gesture usages except on GestureMixin. Probably all fixed?
