### ISSUE TITLE
Add Documentation around Tile Layer ordering rules

### ISSUE THREAD

**Issue by Prototype1** [fleaflet/flutter_map#226]
Hi, 

this is probably an intended behavior but i would be nice to document it somewhere: Imagine having this code: 

```
var map = FlutterMap(
      options: new MapOptions(
          center: somePoint,
          zoom: 11.0,
      layers: [
        new TileLayerOptions(
          urlTemplate: 'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png',
          additionalOptions: {},
        ),
 new MarkerLayerOptions(
          markers: clickableMarker,
        ),
        CircleLayerOptions(circles: [
          CircleMarker(
              point: somePoint,
              radius: someRadius,
              color: Colors.black.withOpacity(0.5),
              )
        ]),
       
      ],
    );

```
The marker's child (Flatbutton) wont get informed onTap  because the circle marker is painted over it. Would be nice to document this somewhere, was quite a headache to figure out. It doesnt even depend on the position of the circle. As soon as there is another Layer after MarkerLayerOptions, onTap doesnt work on the child of the marker.

**Comment by johnpryan** [comment]
Yes, the order of the marker layers has caused headaches in the past. We should add documentation for tile layer ordering and how it works
