### ISSUE TITLE
hasGesture=false for user initiated map updates

### ISSUE THREAD

**Issue by avimak** [fleaflet/flutter_map#241]
version: 0.5.0

**scenario:** move the map using a touch-gesture (dragging)

**expected:** `onPositionChanged` will be called with `hasGesture=true`

**actual:** `onPositionChanged` is being called with `hasGesture=false`

meaning, the client can't differentiate between programmatic map-updates, and user-initiated map-updates

**Comment by AlexandreRoba** [comment]
Same issue

**Comment by johnpryan** [comment]
this is related to https://github.com/johnpryan/flutter_map/issues/280

**Comment by wmcshane** [comment]
This was fixed on the 20/07/19 - see commit efac99d3ad003d469d39ceb7b1356f718ef5c7c0
