### ISSUE TITLE
Cant disable moving map if bound is reached 

### ISSUE THREAD

**Issue by michael-k-taylor** [fleaflet/flutter_map#248]
For example I am showing a region with markers however I cant lock the map to just that region!

**Comment by supermuesli** [comment]
You can achieve that by setting the ```options``` parameter of your ```FlutterMap``` widget to something like 
```
MapOptions(
     swPanBoundary: LatLng(60, 4), // bottom left boundary
     nePanBoundary: LatLng(61, 5), // top right boundary
 )
 ```
