### ISSUE TITLE
Add TileProvider that stores images on disk

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#279]
Some users have asked for better image caching that can store tiles on disk https://github.com/johnpryan/flutter_map/issues/276

**Comment by josxha** [comment]
The policy of OpenStreetMap requires caching of tiles.

> Cache Tile downloads locally according to HTTP Expiry Header, alternatively a minimum of 7 days.

[https://wiki.openstreetmap.org/wiki/DE:Tile_usage_policy](https://wiki.openstreetmap.org/wiki/DE:Tile_usage_policy)

For this reason I'm really looking forward to this feature.

**Comment by Lootwig** [comment]
Would it make sense to use the same technology to also implement preloading of a specific section (like google's offline maps - so, all zoom levels for the section at once rather than on-demand)?

**Comment by MooNag** [comment]
@johnpryan This issue should be closed. Fixed by #841
