### ISSUE TITLE
move() has two gesture-parameters hasGesture and isUserGesture

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#280]
we should combine these

**Comment by johnpryan** [comment]
none, AFAICT. just bad API management :)

**Comment by wmcshane** [comment]
I'm going to remove isUserGesture and submit a pull request. I originally added it as hasGesture wasn't handle all scenarios as expected, however, it's since been fixed.

**Comment by johnpryan** [comment]
@wmcshane thanks!

**Comment by maRci002** [comment]
Solved, see #389
