### ISSUE TITLE
Add example showing current location

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#290]
use https://pub.dev/packages/location to display the user's current location as a Marker

**Comment by aytunch** [comment]
@johnpryan This would be perfect as to make the library more of a "whole" solution. Personally, I use [geolocator](https://pub.dev/packages/geolocator) and I am very glad with that.

**Comment by johnpryan** [comment]
I think this is something we can include as an example but not part of the library

**Comment by maRci002** [comment]
Solved, see #447
