### ISSUE TITLE
Grab current map image with all layers to image/file- enhancement ? 

### ISSUE THREAD

**Issue by MichalMisiaszek** [fleaflet/flutter_map#345]
Thanks for great plugin !

I am trying to save current map image with all overlays to the file. Unfortunately widget is not updated until I finish on pressed event. Inside onPressed function I move the map and then want to grab image. So the image I grab is current (old) map view before whole tree is refreshed.
I am looking for a way to get current map view (with all layers) before is it actually rendered. Any ideas ?

**Comment by johnpryan** [comment]
It sounds like you want a callback when the map is done loading tiles for the current viewport?

**Comment by MichalMisiaszek** [comment]
Loading and rendering, when I grab image sometimes tiles are not rendered yet. The idea is to create a snapshot of the map after it was updated.
