### ISSUE TITLE
The getter 'center' was called on null. using BottomNavigation.

### ISSUE THREAD

**Issue by MitchellQ** [fleaflet/flutter_map#346]
This might be a non issue but I had an issue with animatedMapMove method in conjunction with how I was using bottom navigation namely I had a Widget called currentPage that goes in the body and that renders differently depending on what tab you are on

when the currentPage returns FlutterMap the animatedMapMove method is unusable.

I have a public repo with an example if you want to have a look.

**Comment by johnpryan** [comment]
Yes please provide a link to help explain

**Comment by MitchellQ** [comment]
This is the url to the repo https://github.com/MitchellQ/map-example it should be set up to demonstrate this.
