### ISSUE TITLE
Rotated map jumps around when panning

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#361]
The MapController sample allows rotation, but panning a rotated map causes the map to jump. This may be due to the fling animation.

See https://github.com/johnpryan/flutter_map/pull/359 for details related to rotation

**Comment by paolorotolo** [comment]
I can still reproduce this on master, are you sure it's fixed?

**Comment by johnpryan** [comment]
I'm not sure, I'll reopen this.

**Comment by paolorotolo** [comment]
Woops, I already opened #387. If it's the same cause we can close it and continue here.

**Comment by paolorotolo** [comment]
So this is the behavior I recorded on a Pixel 3: https://youtu.be/wEW-7ZECZrw

As you can see, only when the map is rotated, the panning animation isn't smooth and the map jumps down.

**Comment by paolorotolo** [comment]
Any update on this?

**Comment by ibrierley** [comment]
Not sure I can see this in master, but it would be good to be fixed, is it because the CI tests failed ? (not that familiar with it yet!)

**Comment by RomanJos** [comment]
I also have this problem, setting the rotation to 180 and 0 have no problem though

**Comment by mat8854** [comment]
Yes, it seems to be worst for rotation values of 90 and 270 degrees. We tried it too.

**Comment by maRci002** [comment]
Hello, PR #719 fixes this problem.
