### ISSUE TITLE
Enable tap for layer "below"

### ISSUE THREAD

**Issue by moovida** [fleaflet/flutter_map#390]
I am not sure if there is a way to change this, but currently if I create two layers of clusters, then only the last added (or topmost) reacts to gestures. 
That happens also if they do not overlap. Is there a way to let the event sink through the layer if nothing was touched?

I am adding gesture like:

```
new Container(
              child: GestureDetector(
            onTap: () {
               .....
            },
            child: Icon(
              ......
            ),
          )),
```

Thank you

**Comment by petrenkolits** [comment]
hi! any suggestions on how to address that?

**Comment by johnpryan** [comment]
You might try looking at [the docs for gestures](https://flutter.dev/docs/development/ui/advanced/gestures) or reproducing this in a simple (non-flutter_map based) example to help pin down the issue.
