### ISSUE TITLE
Animate a point along route

### ISSUE THREAD

**Issue by boominadhaprakash** [fleaflet/flutter_map#411]
Hi,

Thanks for this nice library. I just want to know whether **animate a point along route** feature is available for flutter or not. That feature is available on the **Mapbox JS**. 
Please refer the below link.
https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/

Let me know is it possible on this library.

Regards,
Boominadha Prakash.

**Comment by osinakayah** [comment]
Please what plugin are you using on flutter to get the route between two markers?
