### ISSUE TITLE
Stop map.onTap propagation after marker.onTap

### ISSUE THREAD

**Issue by HugoHeneault** [fleaflet/flutter_map#420]
Hi there!

When I tap a marker, `onTap` events are triggered on marker and then on map. 
Would it be possible to stop propagation so the map don't trigger `onTap`?

I'm opening a popup when I tap the marker and closing it when I tap the map. As the events are fired for both marker and map... the popup opens and close instantly. 

Thanks!

**Comment by flogaribal** [comment]
Hi @HugoHeneault,

If you are still experiencing this problem, I might have a potential solution (in fact two).

I do not know how you are building your marker + popup and how do you handle the gesture on it but I did use this package to be able to play with popup easily and it is working as  well as expected and the problem you have is not present: https://github.com/rorystephenson/flutter_map_marker_popup

Anyway, I was having the same problem when I was trying to handle `PointerDownEvent` on a marker to make it change its color and display a floating text (elsewhere on the screen and not as popup). The `onTap` event was fired twice, one time for the marker and one time for the map and as you were experiencing my marker was showing something and right after showing nothing. 

My map options:

```
MapOptions(
      onTap: (_) => bloc.selectShop(null),
      plugins: <MapPlugin>[],
      center: center,
      zoom: _DEFAULT_ZOOM,
      interactive: true,
    );
```

In my case I was using the `Listener` class on my marker to handle `PointerDownEvent` (see below)

```
Widget build(BuildContext context) {
    final ShopMapBloc bloc = Provider.of<ShopMapBloc>(context);
    return StreamBuilder<Shop>(
      stream: bloc.selectedShop,
      builder: (BuildContext context, AsyncSnapshot<Shop> snapshot) {
        if (snapshot.hasData) {
          final Shop selectedShop = snapshot.data;
          if (selectedShop != null && selectedShop.id == widget.shop.id) {
            // Selected
            return Listener(
              onPointerDown: (PointerDownEvent _) {
                // Select the shop
                bloc.selectShop(null);
              },
              child: Container(
                child: _marker(selected: true),
              ),
            );
          } // not selected
        }
        return Listener(
          onPointerDown: (PointerDownEvent _) {
            // Undo select the shop
            bloc.selectShop(widget.shop);
          },
          child: _marker(selected: false),
        );
      },
    );
  }
```

When I changed this handling by `GestureDetector` and `onTap` handler, then the event was not fired twice anymore

```
  @override
  Widget build(BuildContext context) {
    final ShopMapBloc bloc = Provider.of<ShopMapBloc>(context);
    return StreamBuilder<Shop>(
      stream: bloc.selectedShop,
      builder: (BuildContext context, AsyncSnapshot<Shop> snapshot) {
        if (snapshot.hasData) {
          final Shop selectedShop = snapshot.data;
          if (selectedShop != null && selectedShop.id == widget.shop.id) {
            // Selected
            return GestureDetector(
              onTap: () {
                // Select the shop
                bloc.selectShop(null);
              },
              child: Container(
                child: _marker(selected: true),
              ),
            );
          } // not selected
        }
        return GestureDetector(
          onTap: () {
            // Undo select the shop
            bloc.selectShop(widget.shop);
          },
          child: _marker(selected: false),
        );
      },
    );
  }
```

I hope it helped
