### ISSUE TITLE
Reflecting changes on map requires interaction on the map to see the changes!

### ISSUE THREAD

**Issue by AzarouAmine** [fleaflet/flutter_map#421]
I'm using this package as my application MVP. Everything is working fine so far, but I've noticed one problem that I don't know how to solve. Technically I'm creating the map globally in an InhertiedWidget so I can reuse it in other screens. What I've managed to do with this is to add markers to the map, which works perfectly. However, when I try to modify these markers, by simply recreating them, the changes don't apply on the map unless I actually interact with it, meaning I need to zoom or slide it so I can see the changes on the map.

Anyone has an idea on why this is happening? And how can it be fixed?

N.B: I don't think seeing my code would be necessary, since this is a behavior of the map.

**Comment by eyecreate** [comment]
It seems this is programmed by default to have markers update on moving, but it is implemented that you can supply your own Stream to trigger rebuilds.
https://github.com/johnpryan/flutter_map/pull/144

**Comment by johnpryan** [comment]
> the changes don't apply on the map unless I actually interact with it

As far as I know, this is a bug. The [moving markers](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/moving_markers.dart) example seems to be working for me, which is adjusting the markers by calling setState() and re-assigning the list of markers to a list with new values.

If you can create a simple example I think it would help demonstrate the issue.

**Comment by AzarouAmine** [comment]
> > the changes don't apply on the map unless I actually interact with it
> 
> As far as I know, this is a bug. The [moving markers](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/moving_markers.dart) example seems to be working for me, which is adjusting the markers by calling setState() and re-assigning the list of markers to a list with new values.
> 
> If you can create a simple example I think it would help demonstrate the issue.

Hey, thank you for your reply. I haven't found a solution to this behavior so I'll explain what I'm doing.

Basically, I have a map and a carousel at the bottom of the screen. Each carousel item represents a marker on the map, meaning if I swipe the carousel, the map should move to and zoom on the marker corresponding and vice-versa for clicking on a marker.

To handle the interaction and the updates between the two widgets, I'm using the BLoC pattern so I have an InheritedWidget where I put my map (I have a custom class where I extend FlutterMap and is basically where I store my markers)  and the map controller (I've used the package [map_controller](https://pub.dev/packages/map_controller))

```
class GlobalInheritedWidgetState extends State<GlobalInheritedWidget> {

  MyMap _homeMap;
  StatefulMapController _statefulHomeMapController;

  TugiMap get homeMap => _homeMap;
  StatefulMapController get statefulHomeMapController => _statefulHomeMapController;

  @override
  void initState() {
    _homeMap = TugiMap(
      options: MapOptions(
        center: LatLng(51.5, -0.09),
        zoom: 13.0,
      ),
    );
    _statefulHomeMapController = StatefulMapController(mapController: _homeMap.mapController);
    super.initState();
  }

  @override
  Widget build(BuildContext context){
    return new GlobalInherited(
      data: this,
      child: widget.child,
    );
  }
}
```
So this class is just my state wrapper, in my main home widget, I have a method where I do my logic. Basically when the markers are first shown on the map, the closest one to the user's location is colored red, while others are blue. Once a marker is clicked, it becomes colored red and the map should move and zoom to it. The first part works partially, where the colors switch, but I need to interact with the map so I actually see the change, the second part doesn't work, which is moving to the marker clicked, it actually moves to the user's location (which I think might be an error from my part in my logic).

```
markerClicked(GlobalInheritedWidgetState state, rts.Route route) {
    /** In this piece of code I retrieve the data I need to move the carousel and
    * the current red colored route.
    */
    int index = state.routes.indexOf(route);
    List<rts.Route> r = state.routes.where((route) {
      return (route.dbId == int.parse(state.homeMap.currentMarker));
    }).toList();
    pois.Poi currentPoi = state.closestPoisToRoutesCenters[r[0]];
    pois.Poi poi = state.closestPoisToRoutesCenters[route];
    /*****************************************************************************/

    setState(() {

      // The addMarker is in my custom map class and I'm using it to update my markers list.
      state.homeMap.addMarker(r[0].dbId.toString(),
        Marker(
          width: 40.0,
          height: 40.0,
          point: new LatLng(currentPoi.latitude,currentPoi.longitude),
          builder: (ctx) =>
            GestureDetector(
                onTap: () => markerClicked(state, r[0]),
                child: Container(
                  child: Image.asset("imgs/blue.png"), //This marker was the current one, and now it isn't (was red, now blue)
                ),
            )
        ),
      );
      state.homeMap.addMarker(route.dbId.toString(),
        Marker(
          width: 40.0,
          height: 40.0,
          point: new LatLng(poi.latitude,poi.longitude),
          builder: (ctx) =>
            Container(
              child: Image.asset("imgs/red.png"), //This marker is now the current marker (red)
            ),
        ),
        isCurrent: true,
      );
    });

    //This for some reason I don't understand, moves the map to the user's location, and not the supplied marker.
    //state.homeMap.mapController.move(LatLng(route.latitude,route.longitude), state.homeMap.mapController.zoom);
    //This is just the controller to move the carousel, which works perfectly so far
    _swiperController.move(index);
  }
```

As I said, this code is working as intended, but the map needs to be interacted with to update the markers. And the commented before last instruction should move the map to the clicked marker, but actually moves it to the user's location.

**Comment by synw** [comment]
This is related to map_controller, author here. The `StatefulMapController` does not handle automatic map rebuilds, so in the widget where `FlutterMap` lives you have to watch for updates and manualy trigger `SetState` calls when something new happens by listenning to the changefeed:

```dart
   statefulMapController.changeFeed.listen((change) => setState(() {}));
```

This is the basic solution but you can do more advanced state management to trigger your updates, like with using Provider: [example](https://github.com/synw/fluxmap/blob/master/lib/src/fluxmap.dart#L69).

I am actually working on porting this package to a plugin precisely to avoid having to manage the map rebuilds manualy, but I did not find a proper way to do it yet #482 . I hope this can be solved and then we won't have to worry about map updates when an asset is changed.

**Comment by AzarouAmine** [comment]
> This is related to map_controller, author here. The `StatefulMapController` does not handle automatic map rebuilds, so in the widget where `FlutterMap` lives you have to watch for updates and manualy trigger `SetState` calls when something new happens by listenning to the changefeed:
> 
> ```dart
>    statefulMapController.changeFeed.listen((change) => setState(() {}));
> ```
> 
> This is the basic solution but you can do more advanced state management to trigger your updates, like with using Provider: [example](https://github.com/synw/fluxmap/blob/master/lib/src/fluxmap.dart#L69).
> 
> I am actually working on porting this package to a plugin precisely to avoid having to manage the map rebuilds manualy, but I did not find a proper way to do it yet #482 . I hope this can be solved and then we won't have to worry about map updates when an asset is changed.

Thanks for your explanation and proposition, I'm trying to find a simpler solution for the moment since I've done so much so far using the built-in BLoC pattern, switching to provider for example would require extra work and time which I can't afford at the moment, however it could still be done if it assures to fix the problem.

As for the problem, the way I see it (might be wrong about it) is that a marker is a child of the map, widget speaking; so it is logical that making changes to a marker wouldn't trigger a rebuild of the map (the parent) if it isn't implemented in the core of the package (or plugin if you wish). However, interacting with the map (finger gestures) does trigger a rebuild, which is why the markers are then updated. I believe this is what you explained in your answer. So what I'm basically saying, from how I understand how the plugin works and how Flutter works, wouldn't wrapping both the FlutterMap and the Markers in an InheritedWidget solve the problem? They clearly have different states, since they are implemented in two different StatefulWidget classes, putting them inside a single parent (an InhertiedWidget) would make both of them rebuild if one changes (pretty much what provider does but I'm trying to stay away from code complexity for the moment).
