### ISSUE TITLE
Bounds viscosity

### ISSUE THREAD

**Issue by quantosapplications** [fleaflet/flutter_map#423]
Hi @johnpryan, thanks for this amazing plugin!

On original Leaflet library there is a maxBoundsViscosity parameter that can be setted on map options, that prevents user from panning outside boundary making an animation that push view inside boundaries again.

It is a double between 0.0 and 1.0 that specify the speed used to push user inside boundaries again.

Do you think it can be implemented on this project too?

Thank you and sorry for bad English.

**Comment by johnpryan** [comment]
This isn't currently on the roadmap, thanks for filing an issue!
