### ISSUE TITLE
Compatibility with desktop apps

### ISSUE THREAD

**Issue by synw** [fleaflet/flutter_map#431]
I would like to integrate this package in a desktop app but there are some blocking dependencies. At least Sqflite and cached_network_image are not available for desktop.

Would it be possible to set some options to not use the incompatible packages when on desktop or is it too tight with the code and not an option?

**Comment by 11azars** [comment]
I don't have an answer for you, but I wanted to comment that I've been able to get a demo to compile on linux. It doesn't show a map, but instead draws a grey square with a flutter logo that can be dragged around. Not sure if I am doing something wrong, or if there is incompatibility here..

**Comment by 11azars** [comment]
I guess that flutter logo is a marker... so maybe it's just that the map isn't rendering.

**Comment by 11azars** [comment]
![maps](https://user-images.githubusercontent.com/54327825/65844530-acccfb80-e304-11e9-8dfa-f02f707294cc.png)

It's pretty clear to me now that there is something preventing this library from rendering on desktop... granted it silently fails (which I find to be very odd).

**Comment by 11azars** [comment]
What I am wondering is if the usage of Sqflite could be swapped for something like Sembast or ObjectDB. Sembast is pure dart, and supports desktop as well as both flutter mobile platforms. The only usage of Sqflite that I could find in the project (aside from the usage within cached_network_image) is in `lib/src/layer/tile_provider/mbtiles_image_provider.dart`.

It appears to be called for a SQL `select` query to get tile data. I'm having trouble finding how that database gets into the database in the first place. Either way, it would be a cakewalk to replace a single query like this with a Sembast query.

I _may_ submit a PR for these changes, so please let me know if you have any insight here that could help.

**Comment by 11azars** [comment]
Also, flutter_cache_manager is the cache provider used by cached_network_image, and it uses sqflite for storage.

**Comment by 11azars** [comment]
@synw I found a fix.

I realized that the only issues with this package arise from the cache mechanisms, and that you can choose a tile provider (documentation shows asset based provider for offline use)... I tried providing the a network provider instead of the default (cached network) and voila!

```dart
Container(
            width: 500,
            height: 500,
            child: FlutterMap(
              options: MapOptions(
                center: LatLng(51.5, -0.09),
                zoom: 13.0,
              ),
              layers: [
                TileLayerOptions(
                  tileProvider: NetworkTileProvider(), // <- add this line here and it should work!
                  urlTemplate: "https://api.mapbox.com/styles/v1/rucuriousyet/ck15ozlow33tj1cph5cpt2y79/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicnVjdXJpb3VzeWV0IiwiYSI6ImNpdm83MjFwYzAxMnQyeXFyaDR0ZmFxbjkifQ.Ak3DcaxXheiKmTW2TIKY9A",
                ),
                MarkerLayerOptions(
                  markers: [
                    Marker(
                      width: 80.0,
                      height: 80.0,
                      point: LatLng(51.5, -0.09),
                      builder: (ctx) =>
                      Container(
                        child: FlutterLogo(),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
```

![working map](https://user-images.githubusercontent.com/54327825/65846976-a727e380-e30d-11e9-9f86-f0014bf03607.png)

Obviously the long term solution would be to modify the caching to utilize a different database, or get support for sqflite on desktop... but that's not great for those wishing to play with desktop now.

**Comment by synw** [comment]
Thanks! Using `NetworkTileProvider` works. But we loose the caching ability. 

> Obviously the long term solution would be to modify the caching to utilize a different database, or get support for sqflite on desktop

I feel that Sqflite support for desktop is not for tomorrow: there is no up to date Dart module for Sqlite at the moment. We could use Sembast as you suggest or Hive to write a compatible tile provider that can cache

**Comment by 11azars** [comment]
I just saw hive yesterday... I think that's the way to go. We should just
fork cached network image. Ultimately since hive performs better the
community should probably use hive where possible instead of sqlite.

**Comment by GregorySech** [comment]
Instead of fully forking the package maybe a PR to inject a different cache strategy would be better. Then the hive cache might become a different strategy outside of the original package.

**Comment by JonasVautherin** [comment]
@cosmotek @synw: Does [this](https://github.com/tekartik/sqflite/blob/develop/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md) bring Desktop support for sqflite? Or am I misunderstanding it? Would that help?

**Comment by moovida** [comment]
@JonasVautherin  I changed from sqfile to use the sqlite3 package (former moor_ffi) and am happy with it. I am currently building for macos and linux and while sqfilte works on macos, it does not for linux. 

Since everything starts in the chache manager, I tried to open a discussion here: https://github.com/Baseflow/flutter_cache_manager/issues/222

Loosing cache management using the NetworkTileProvider is not a good option in my opinion, also because many free tile providers will blacklist you if you request too many images.

**Comment by cosmotek** [comment]
All good points. I haven't been in this discussion for a while, but I might try to write an alternative lib to replace NetworkTileProvider using Hive. I've used Hive for the last year in a mobile app (we used it in the same way you'd use LocalStorage in the browser) and have nothing but love for it. It's very fast, it provides an interface for custom object conversion (so no need to write SQL or convert to JSON)... overall a really nice utility for storing data in native dart.

**Comment by cosmotek** [comment]
I will always prefer using native language libraries as opposed to C/C++ bindings. C/C++ bindings will always be costly, and have cross-platform concerns. IMO that's a non-starter for Flutter, given the whole point is to be single framework for all UI platforms.

We should try to push this direction whenever practical as people writing Flutter libs that only work for a few devices will fragment the community.

**Comment by cosmotek** [comment]
(Sorry for the preaching, leaving my high-horse now).

**Comment by theinterestingstory** [comment]
Desktop seems to be working fine for me now on Ubuntu 20.10. I didn't do anything besides import this git project. I don't know if it was this project that changed something or maybe this: Baseflow/flutter_cache_manager/pull/226

![Screenshot from 2020-12-15 22-14-13](https://user-images.githubusercontent.com/10492556/102300858-9e8cee80-3f4d-11eb-85ff-a262c89eff56.png)

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final LatLng nycCords = new LatLng(40.7128, -74.0060);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: FlutterMap(
            options: MapOptions(
              center: nycCords,
              zoom: 13.0,
            ),
            layers: [
              TileLayerOptions(
                  urlTemplate:
                      "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  subdomains: ['a', 'b', 'c']),
              MarkerLayerOptions(
                markers: [
                  Marker(
                    width: 80.0,
                    height: 80.0,
                    point: nycCords,
                    builder: (ctx) => Container(
                      child: FlutterLogo(),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
