### ISSUE TITLE
[Question] How to move a marker throughout the map

### ISSUE THREAD

**Issue by angel1st** [fleaflet/flutter_map#458]
Hi there, I am trying this package along with geolocation one. Basically - I can have few markers, where each one can change its location over time. 
I can see a `Marker` class has `point` as final, which basically means, I have to remove and insert again the maker in case its position changes. Is that correct or am I missing something? I just feel, if you can simply update marker's point attribute this should be move efficient from performance perspective than removing and inserting the marker over and over...

**Comment by synw** [comment]
Actually the markers are not widgets and can not hold state, so I guess rebuilding them is the only option. This might change as this question is in the [0.8.0 planning](https://github.com/johnpryan/flutter_map/issues/405). 

Btw I made a stateful map controller package to reduce the boilerplate for [managing map assets](https://github.com/synw/map_controller#map-assets), if it can help

**Comment by angel1st** [comment]
Thanks, @synw, let's hope this might be added to 0.8.0 planning somehow. Your package seems very decent, I will give it a try later on.

**Comment by johnpryan** [comment]
Have you taken a look at [using Keys](https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d)?

**Comment by nishontan** [comment]
@johnpryan are you proposing to use the key in maker widget builder?


```dart
Marker(point: LatLng(_currentLocation.latitude, _currentLocation.longitude),
            builder: (context) {
              return Stack(
                key: UniqueKey(),
                alignment: AlignmentDirectional.center,
                children: <Widget>[
                .....
                ],
              );
            })
```

**Comment by darkwolf66** [comment]
Is already possible to update a marker without rebuilding the entire map?
