### ISSUE TITLE
Map padding

### ISSUE THREAD

**Issue by ZatacaSystems** [fleaflet/flutter_map#462]
Is there a way to set padding to the map's tiles layout? 

Example:

I have a card that is positioned on top of the map, and when I show the card, I want the map to put a padding for showing the markers in the remaining space area (total height - card height) is it possible?

**Comment by juanlabrador** [comment]
I need that too.

**Comment by maRci002** [comment]
`TileLayerOptions` has `tileBuilder` property, see #582
