### ISSUE TITLE
Add support for sending headers when fetching image tiles

### ISSUE THREAD

**Issue by rorystephenson** [fleaflet/flutter_map#464]
According to **Technical Usage Requirements** on OpenStreetMap's [Tile Policy Page](https://operations.osmfoundation.org/policies/tiles/) tile requests should use a valid HTTP User-Agent which identifies each application.

I stumbled upon this when trying to determine why the OpenStreetMaps tiles load so much slower on my device with `flutter_map` than on `Leaflet` in a browser. I think it's possible that OpenStreetMaps are throttling due to the lack of this header. Note I was testing on the same network and on a physical device with the app in release mode. Changing to another tile provider gave me expected speeds.

Even if it's not the reason for slow tile loading it is an expected parameter. I had a quick look and it seems like a pretty easy feature to add. I don't have the time to tackle it immediately (for the moment I'm just using a different tile provider whilst I develop my app) but I would like to eventually submit a PR for this.

Thanks for the amazing work on this plugin, I'm really impressed by the quality of it 👏.

**Comment by johnpryan** [comment]
The NetworkImage widget accepts headers, so you could extend TileProvider yourself, or add a `headers` option to the `NetworkTileProvider` class. Something like:

```dart
class NetworkTileProvider extends TileProvider {
  Map headers;
  NetworkTileProvider({this.headers = {}});
  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return NetworkImageWithRetry(getTileUrl(coords, options, headers: headers));
  }
}
```

**Comment by maRci002** [comment]
https://github.com/fleaflet/flutter_map/issues/464#issuecomment-570301974

**Comment by berkayoruc** [comment]
> The NetworkImage widget accepts headers, so you could extend TileProvider yourself, or add a `headers` option to the `NetworkTileProvider` class. Something like:
> 
> ```dart
> class NetworkTileProvider extends TileProvider {
>   Map headers;
>   NetworkTileProvider({this.headers = {}});
>   @override
>   ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
>     return NetworkImageWithRetry(getTileUrl(coords, options, headers: headers));
>   }
> }
> ```

Last version compatible with this code block

```
class NetworkTileProvider extends TileProvider {
  Map<String, String> headers;
  NetworkTileProvider({this.headers});
  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return NetworkImage(getTileUrl(coords, options), headers: headers);
  }
}
```
