### ISSUE TITLE
zooming buttons for web support

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#481]
Related to #383 and #440

**Comment by moovida** [comment]
What exactly are you looking for here? Creating zoom in/out buttons using the mapController is easy, so I am probably misunderstanding the need. Could you elaborate?

**Comment by johnpryan** [comment]
This would be a plugin that adds these buttons: 

<img width="162" alt="Screen Shot 2019-12-17 at 9 26 29 AM" src="https://user-images.githubusercontent.com/1145719/71019542-583d4f00-20af-11ea-96b8-2ab3ee4256e9.png">

**Comment by moovida** [comment]
Pull request #487 could be a starting point for the above.

**Comment by maRci002** [comment]
Solved, see #487

**Comment by daraul** [comment]
Sorry, but how do I actually use the plugin?
