### ISSUE TITLE
Choropleth Maps

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [fleaflet/flutter_map#483]
Is it possible to create Choropleth maps (similar to the one shown below)?

I know it can be done in Leaflet but I'm not sure whether this feature is available in your adaptation of it. 

![](https://datavizcatalogue.com/methods/images/top_images/choropleth.png)

**Comment by johnpryan** [comment]
Probably not right now, I haven't seen an example of this yet.

**Comment by waaeel** [comment]
any progress in this topic ? :)
