### ISSUE TITLE
set map rotation without triggering rebuild

### ISSUE THREAD

**Issue by moovida** [fleaflet/flutter_map#494]
I am trying to set map position and rotation from a plugin's build method.

From the mapState it is possible to do a .move without problems, but the rotate method is not implemented and if I call it on the mapcontroller I will suffer a re-build from within a build, which doesn't work.

Does anyone have an advice on how to handle this? Thank you.

**Comment by escamoteur** [comment]
Can you share some code? I'm nor 100% sure what you mean be you will suffer a rebuild from within a build. I use the rotation without problems.

**Comment by moovida** [comment]
Sure @escamoteur .

Inside a MapPlugin of the flutter_map project one has acces to the mapstate through the variable:
```
MapState mapState
```
this variable can be used to move the map to a given position with:
```
mapState.move(posLL, mapState.zoom);
```
which inside does a:
```
if (options.onPositionChanged != null) {
      options.onPositionChanged(
          MapPosition(
            center: center,
            bounds: bounds,
            zoom: zoom,
          ),
          hasGesture);
```
The cool part of this is that you can call it inside the build method of a plugin (mind, you are not allowed to set state during the build of a widget, but this works)


Instead setting the rotation on the mapstate is simply setting a variable, which doesn't trigger any change.

So the only option is to pass through the MapController. 

When a move is done in the mapcontroller, then this happens:
```
void move(LatLng center, double zoom, {bool hasGesture = false}) {
    _state.move(center, zoom, hasGesture: hasGesture);
  }
```
i.e. the MapState is used, which means it is the same as described in the first part here.

If rotation is set on the mapcontroller, then this happens:
```
  void rotate(double degree) {
    _state.rotation = degree;
    if (onRotationChanged != null) onRotationChanged(degree);
  }
```
The state's rotation is set and then with onRotationChanged a setState is triggered, issuing a rebuild. But this is not allowed during another widget build.

So I was wondering if there is a way to make rotation behave the same as the move method.
