### ISSUE TITLE
Convert point to latitude and longitude

### ISSUE THREAD

**Issue by HosseinBabriani** [fleaflet/flutter_map#496]
Hi i need latitude and longitude inside getTileUrl function but I can't usemap.unproject or crs.pointToLatLng but result isn't real result.
Is there any way to solve my problem ?

**Comment by moovida** [comment]
@hossein-hbb not sure I understand. You can't use the mapstate functions because you do not have access to it? And therefore you need a conversion between the TMS tileschema and lat/long?

**Comment by hossein-hbb** [comment]
I try to modify plugin and add my custom parameters in plugin like this:
'lat':lat.toString(),
'lng':lng.toString(),

**Comment by hossein-hbb** [comment]
But when I use pointToLatLng or usemap.unproject return wrong values for lat and lng...

**Comment by hossein-hbb** [comment]
I need change methode like this :
 String getTileUrl(Coords coords, TileLayerOptions options,LatLng latLng) {
    var data = <String, String>{
      'x': coords.x.round().toString(),
      'y': coords.y.round().toString(),
      'z': coords.z.round().toString(),
      'lat':latLng.latitude.toString(),
      'lng':latLng.longitude.toString(),
      's': getSubdomain(coords, options)
    };
    if (options.tms) {
      data['y'] = invertY(coords.y.round(), coords.z.round()).toString();
    }
    var allOpts = Map<String, String>.from(data)
      ..addAll(options.additionalOptions);
    return util.template(options.urlTemplate, allOpts);
  }

**Comment by moovida** [comment]
It might be you are missing some pieces in the conversion.
Here some code I use to convert a screen position to latlong. 
```
var p = e.localPosition;
var pixelBounds = map.getLastPixelBounds();

CustomPoint pixelOrigin = map.getPixelOrigin();
var ll = map.unproject(CustomPoint(pixelOrigin.x + p.dx, pixelOrigin.y + p.dy));
```
As you can see you need to consider the pixelOrigin also. Might that be your problem?

**Comment by hossein-hbb** [comment]
Can you explain e.localPosition .
how can I access or create e?

**Comment by moovida** [comment]
In my case I had an event from a GestureDetector. That part will not be of use for you, since you are converting tiles positions. I wanted to show you more the pixelOrigin part.

I am starting to have the feeling that you just need to convert the tile position index to lat/long?
If that is so, you can just use the following methods:

```
  static double tile2lon(int x, int z) {
    return x / pow(2.0, z) * 360.0 - 180.0;
  }

  static double tile2lat(int y, int z) {
    double n = pi - (2.0 * pi * y) / pow(2.0, z);
    return radianToDeg(atan(sinh(n)));
  }
```
Rationale behind it is found here: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

**Comment by hossein-hbb** [comment]
Its work but when _createTileWidget all tiles positions is wrong...
my code : 
```
![screenshot-1578915117768](https://user-images.githubusercontent.com/14945895/72253426-c75a8480-3616-11ea-9b6f-285acfcde16e.jpg)
  static double tile2lon(int x, int z) {
    return x / pow(2.0, z) * 360.0 - 180.0;
  }

  static double tile2lat(int y, int z) {
    var n = pi - (2.0 * pi * y) / pow(2.0, z);
    return radianToDeg(atan(numerics.sinh(n)));
  }

  String getTileUrl(Coords coords, TileLayerOptions options) {
    var data = <String, String>{
      'x': coords.x.round().toString(),
      'y': coords.y.round().toString(),
      'z': coords.z.round().toString(),
      'lat':tile2lat(coords.y.round(),coords.z.round()).toString(),
      'lng':tile2lon(coords.x.round(),coords.z.round()).toString(),
      's': getSubdomain(coords, options)
    };
    if (options.tms) {
      data['y'] = invertY(coords.y.round(), coords.z.round()).toString();
    }
    var allOpts = Map<String, String>.from(data)
      ..addAll(options.additionalOptions);
    return util.template(options.urlTemplate, allOpts);
  }
```
