### ISSUE TITLE
Two finger rotation gesture

### ISSUE THREAD

**Issue by Dharisd** [fleaflet/flutter_map#498]
How do i go about implementing two finger rotation gesture? #359 mentions that it should be possible with a GestureDetector but im not sure how to implement it

**Comment by ruizalexandre** [comment]
I'm on it ! It's already good but I need to clean code now

**Comment by mat8854** [comment]
@ruizalexandre Is there a PR for rotation gesture support? Thank you.

**Comment by maRci002** [comment]
#719 implements this feature.
