### ISSUE TITLE
Feature: PolylineDecorator?

### ISSUE THREAD

**Issue by HugoHeneault** [fleaflet/flutter_map#506]
Do you guys have any idea on how we could implement something like https://github.com/bbecquet/Leaflet.PolylineDecorator

![example of polyline decorator](https://camo.githubusercontent.com/db72a98578177ee530f827ce1ebb0c2de982ac50/68747470733a2f2f7261772e6769746875622e636f6d2f62626563717565742f4c6561666c65742e506f6c796c696e654465636f7261746f722f6d61737465722f73637265656e73686f742e706e67)

I might have some time for a PR (just not yet) if you have any idea on how you would do it it'll be faster!

**Comment by mat8854** [comment]
Hello, @HugoHeneault is there any progress? Also interested in more advanced polyline styling and options. Would like to contribute too.
