### ISSUE TITLE
 WMSTileLayer not working 

### ISSUE THREAD

**Issue by zozeei** [fleaflet/flutter_map#512]
![1580986593901](https://user-images.githubusercontent.com/49703843/73931008-2192f080-490a-11ea-898a-df10ae1868d3.jpg)
![1580986624458](https://user-images.githubusercontent.com/49703843/73931011-22c41d80-490a-11ea-944a-9aaf5361fcd8.jpg)

**Comment by porfirioribeiro** [comment]
It's not released yet!

I am using GIT version because of that :/

**Comment by maRci002** [comment]
Avaible since v0.9.0
