### ISSUE TITLE
[Request] Circle/ PolyLine onTap

### ISSUE THREAD

**Issue by Rossdex** [fleaflet/flutter_map#513]
Hi. 

I have an app that requires the user to select circles and lines on a map.

I have looked at another provider (mapbox_gl) however they do not support the polygon drawing and the performance isn't comparable to flutter_map.

Is there any way on tap of circles and lines can be implemented?

Or is there a direction you can point me in so I can implement this myself and submit a pull request?

Thanks
Ross

**Comment by porfirioribeiro** [comment]
[Polylines](https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/polyline_layer.dart#L80) and [Circles](https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/circle_layer.dart#L70) are rendered using a `CustomPaint` widget, there is no clickable area, might be possible using a GestureDetector like this: https://gist.github.com/sma/c6a9111d58c3deb83711106cec6152ee#file-example-dart-L44

**Comment by tuarrep** [comment]
About Polylines you could have a look to https://github.com/OwnWeb/flutter_map_tappable_polyline where we have implemented a clickable Polylines.
