### ISSUE TITLE
Problems to get dependences

### ISSUE THREAD

**Issue by alexst07** [fleaflet/flutter_map#521]
When I try get packages from pubspec.yaml I get this message "A package may not list itself as a dependency." In the line:

```
dependencies:
  flutter_map:
```

**Comment by ibrierley** [comment]
Have you called your own app futter_map my any change ? I think that may confuse it, but I may be wrong.

It may be worth posting your pubspec.yaml if still getting the problem.

**Comment by johnpryan** [comment]
Can you double check that your app/package name isn't also called `flutter_map`?
