### ISSUE TITLE
No google map support?

### ISSUE THREAD

**Issue by abhijithvijayan** [fleaflet/flutter_map#528]
So, this package doesn't support google maps at all?

Gradient polylines features is not available in flutter_google_maps package but it is available in this package.

Is there any way to get this done?

**Comment by X-SLAYER** [comment]
you can use Google streets

```
{
        url: 'http://mt{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
        subdomains: "0123",
        name: "Google Streets"
  },
```

**Comment by abhijithvijayan** [comment]
I need to draw gradient polylines on google maps.

Is that possible?

**Comment by X-SLAYER** [comment]
if u are using this package u can check the exemple here [polyline.dart](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/polyline.dart) but for google map package idk

**Comment by Krivtsov6grain** [comment]
> you can use Google streets
> 
> ```
> {
>         url: 'http://mt{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
>         subdomains: "0123",
>         name: "Google Streets"
>   },
> ```

Not you can't, accessing the tiles directly (without using the google maps API or one of google's apps) was against the terms of use.

> Can I access the Maps and Satellite images directly?
> You may not access the maps or satellite images through any mechanism besides the Google Maps Platform (such as the creation of your own mapping API or the use of a bulk tile download script). Your application's access to the tiles will be blocked if it accesses them outside of the Google Maps Platform. See the Google Maps Platform Terms of Service for more details.

https://developers.google.com/maps/faq#tos_tiles
