### ISSUE TITLE
Make geometries editable ?

### ISSUE THREAD

**Issue by X-SLAYER** [fleaflet/flutter_map#531]
is there any way to made the polylines and polygons editable like in leaflet [Leaflet.Editable](https://github.com/Leaflet/Leaflet.Editable)

**Comment by ibrierley** [comment]
Not aware of a way. I feel like it makes sense in desktop, but not really in mobile though (due to the precision needed)?

**Comment by X-SLAYER** [comment]
> Not aware of a way. I feel like it makes sense in desktop, but not really in mobile though (due to the precision needed)?

those options makes the control easier and i need it because i'm trying to make a GIS Mobile so these features are needed

**Comment by vitorfernandesuft** [comment]
hey man.... were you able to edit?

**Comment by X-SLAYER** [comment]
> hey man.... were you able to edit?

didn't understand ?

**Comment by fryette** [comment]
@X-SLAYER were you able to edit? Maybe you find a way?

**Comment by X-SLAYER** [comment]
> @X-SLAYER were you able to edit? Maybe you find a way?

nope i didn't find a way to edit i just made it a basic control edit like a panel to undo and redo the last point i draw thats what i did

**Comment by ibrierley** [comment]
I've just been hacking something together with the dragmarker plugin I did, only basic and maybe bugs, but I'll keep this thread posted as it may give some an idea.

**Comment by ibrierley** [comment]
Ok, I have this basic stuff working now..

![polyedit](https://user-images.githubusercontent.com/3901173/84055684-18e02300-a9ad-11ea-8ee6-cbcfbf361391.gif)

I'll get a separate repo sorted later so anyone can hack about with it and test or add stuff.

**Comment by ibrierley** [comment]
Git repo at https://github.com/ibrierley/flutter_map_line_editor if anyone wants a play
