### ISSUE TITLE
How can I apply style to the map?

### ISSUE THREAD

**Issue by JAICHANGPARK** [fleaflet/flutter_map#551]
Hi , I am using openstreetmap now.
https://openmaptiles.org/styles/ 

I would like to apply a style to the map like [the site,](https://openmaptiles.org/styles/) but I am wondering how to use it in this plugin.

Thank you

**Comment by ibrierley** [comment]
Have you tried adding a style to the part where the url is set, so you would add...

style: 'https://openmaptiles.github.io/osm-bright-gl-style/style-cdn.json'

I have no idea if this works! Just wondering, if the current code is set to pass those things.

**Comment by moovida** [comment]
I think there is some confusion here, Vector tiles, which could be styled, are not (yet) supported by this project to my knowledge. So right now tiles are png/jpg image that are downloaded and can't be styled.

**Comment by ibrierley** [comment]
Yes, thinking about it, you're likely right. I was thinking some create raster tiles with different themes, e.g https://www.maptiler.com/maps/#darkmatter//raster/2/-45.03/38.07

Howevever, I think those are pre-rendered and wouldn't be affected by the json styling etc.

**Comment by MooNag** [comment]
Someone is working on a post process tiles PR #582 which might let you partially style raster images, but vector support is the proper way to do it.

**Comment by JaffaKetchup** [comment]
@furkan-celik The PR has been merged (look into that for more details), but vector tiles - which is probably more like what you're looking for - are not supported by default. @ibrierley does have a plugin (look at his profile), but as far as I'm concerned it's still work in progress, and he's away at the moment.

**Comment by ibrierley** [comment]
There is also a much more complete package by Dave/greensopinion for vector
tiles, I think linked from site and in flutter dev.
