### ISSUE TITLE
Could not instantiate image codec.

### ISSUE THREAD

**Issue by ghost** [fleaflet/flutter_map#556]
Hello, i have this issue, i think that my configuration is good.

 
that's error log
```
> The following _Exception was thrown resolving an image codec:
> Exception: Could not instantiate image codec.
> 
> When the exception was thrown, this was the stack
> #0      _futurize  (dart:ui/painting.dart:4419:5)
> #1      instantiateImageCodec  (dart:ui/painting.dart:1722:10)
> #2      CachedNetworkImageProvider._loadAsyncFromFile 
> package:cached_network_image/src/cached_network_image_provider.dart:78
> <asynchronous suspension>
> #3      CachedNetworkImageProvider._loadAsync 
> package:cached_network_image/src/cached_network_image_provider.dart:64
> ...
> Image provider: CachedNetworkImageProvider("https://api.mapbox.com/styles/v1/salim96/ck7zo3mnj02m01iofnfltoh9p/wmts?access_token=pk.eyJ1Ijoic2FsaW05NiIsImEiOiJjazd6bndsYmUwN2hwM2xydWx5dWZieXJ1In0.wCZaiCZhLA2KEgHP8hYx7Q", scale: 1.0) 
>  Image key: CachedNetworkImageProvider("https://api.mapbox.com/styles/v1/salim96/ck7zo3mnj02m01iofnfltoh9p/wmts?access_token=pk.eyJ1Ijoic2FsaW05NiIsImEiOiJjazd6bndsYmUwN2hwM2xydWx5dWZieXJ1In0.wCZaiCZhLA2KEgHP8hYx7Q", scale: 1.0): CachedNetworkImageProvider("https://api.mapbox.com/styles/v1/salim96/ck7zo3mnj02m01iofnfltoh9p/wmts?access_token=pk.eyJ1Ijoic2FsaW05NiIsImEiOiJjazd6bndsYmUwN2hwM2xydWx5dWZieXJ1In0.wCZaiCZhLA2KEgHP8hYx7Q", scale: 1.0)
```

and that's my code: 

```
 @override
  Widget build(BuildContext context) {
    return Container(
      height: ScreenSize.heightPercent(100),
      width: ScreenSize.widthPercent(100),
      child: Stack(
        children: <Widget>[
          // GoogleMap(
          //   mapType: MapType.normal,
          //   initialCameraPosition: _poland,
          //   onMapCreated: (GoogleMapController controller) {
          //     controller.setMapStyle(_mapStyle);
          //     _controller.complete(controller);
          //   },
          // ),
          FlutterMap(
              mapController: _mapController,
              options: MapOptions(
                zoom: _zoom,
                center: _polandLatLng,
                interactive: true,
              ),
              layers: [
                TileLayerOptions(
                  urlTemplate:
                      "https://api.mapbox.com/styles/v1/salim96/ck7zo3mnj02m01iofnfltoh9p/wmts?access_token=pk.eyJ1Ijoic2FsaW05NiIsImEiOiJjazd6bwM2xydWx5dWZieXJ1In0.wCZaiCZhLA2KEgHP8hYx7Q",
                  additionalOptions: {
                    'accessToken':
                        'pk.eyJ1Ijoic2FsaW05NiIsImEiOiJjazd3Nqczg0czRxdGNjIn0.C75VkvTZJNiBA-Bpbjg2ww',
                    'id': 'dsalim96deq',
                  },
                ),
              ]),
```

and flutter doctor -v output aswell: 

```
PS C:\Users\omen\corona> flutter doctor -v
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18362.418], locale pl-PL)
    • Flutter version 1.15.17 at C:\flutter
    • Framework revision 2294d75bfa (2 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\omen\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\omen\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\omen\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.7019

[√] Connected device (3 available)
    • SM G930F   • ce0717173c06833005 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome     • chrome             • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server         • web-javascript • Flutter Tools

• No issues found!
```

**Comment by ibrierley** [comment]
Not sure your urlTemplate looks right, normally you would have something like the following...

'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',

With z,x,y so the tileprovider knows which actual tile you want ?

**Comment by ibrierley** [comment]
Oh, and you may want to edit out the token from this ticket if it's your own real one :).

**Comment by uzairahmed97** [comment]
Did you find the solution? 
I'm also facing this issue.

**Comment by eon46** [comment]
@uzairahmed97  i decided to use google maps.

**Comment by ibrierley** [comment]
If you get the same problem, you need to post your map API url, it looks like eon46 isn't using a valid one to me, but I may be wrong.

**Comment by uzairahmed97** [comment]
FlutterMap(
            options: new MapOptions(
                center: new LatLng(40.73, -74.00), zoom: 12.0),
            layers: [
              new TileLayerOptions(
                  urlTemplate:
                  "https://api.mapbox.com/styles/v1/testingapps/ck80eatu711r21iod8a874tj5/wmts?access_token=pk.eyJ1IjoidGVzdGluZ2FwcHMiLCJhIjoiY2s3ejg3em1hMDJpYzNkcXRnMXdsajZrbiJ9.0fdcRjYbDjhZwEpGiPKuVw",
                  additionalOptions: {
                    'accessToken':
                    'pk.eyJ1IjoidGVzdGluZ2FwcHMiLCJhIjoiY2s3ejg3em1hMDJpYzNkcXRnMXdsajZrbiJ9.0fdcRjYbDjhZwEpGiPKuVw',
                    'id': 'mapbox.mapbox-streets-v8'
                  }),
              new MarkerLayerOptions(markers: [
                new Marker(
                    width: 45.0,
                    height: 45.0,
                    point: new LatLng(40.73, -74.00),
                    builder: (context) => new Container(
                      child: IconButton(
                        icon: Icon(Icons.location_on),
                        color: Colors.blue,
                        iconSize: 45.0,
                        onPressed: () {
                          print('Marker tapped');
                        },
                      ),
                    ))
              ])
            ])

**Comment by uzairahmed97** [comment]
`FlutterMap(
            options: new MapOptions(
                center: new LatLng(40.73, -74.00), zoom: 12.0),
            layers: [
              new TileLayerOptions(
                  urlTemplate:
                  "https://api.mapbox.com/styles/v1/testingapps/ck80eatu711r21iod8a874tj5/wmts?access_token=pk.eyJ1IjoidGVzdGluZ2FwcHMiLCJhIjoiY2s3ejg3em1hMDJpYzNkcXRnMXdsajZrbiJ9.0fdcRjYbDjhZwEpGiPKuVw",
                  additionalOptions: {
                    'accessToken':
                    'pk.eyJ1IjoidGVzdGluZ2FwcHMiLCJhIjoiY2s3ejg3em1hMDJpYzNkcXRnMXdsajZrbiJ9.0fdcRjYbDjhZwEpGiPKuVw',
                    'id': 'mapbox.mapbox-streets-v8'
                  }),
              new MarkerLayerOptions(markers: [
                new Marker(
                    width: 45.0,
                    height: 45.0,
                    point: new LatLng(40.73, -74.00),
                    builder: (context) => new Container(
                      child: IconButton(
                        icon: Icon(Icons.location_on),
                        color: Colors.blue,
                        iconSize: 45.0,
                        onPressed: () {
                          print('Marker tapped');
                        },
                      ),
                    ))
              ])
            ])`

**Comment by ibrierley** [comment]
Looking at the tile url, it looks like it's for Vector tiles, which isn't supported atm.

**Comment by s3ppo** [comment]
any news on this? i also get the same error.. my shared url from mapbox also looks like this https://api.mapbox.com/styles/v1/...

**Comment by ibrierley** [comment]
Yes, that's probably not a valid url (probably for vector tiles), try first with one of the examples included.

**Comment by s3ppo** [comment]
hi @ibrierley,

i tried already with the default class mapbox.streets and its working but when i use the url provided from mapbox for my custom style it isnt working any more :(

**Comment by ibrierley** [comment]
I think the mapbox styles are all vector tiles, which aren't supported.

**Comment by s3ppo** [comment]
so is there something we can do ? :(

**Comment by ibrierley** [comment]
Best I can suggest is see if you can find the style you want as a png tile format somehow, or see if you can find support with another lib, eg you could try mapboxes https://github.com/mapbox/flutter-mapbox-gl I'm not sure how much support there is, and I don't think ios is supported tho.

**Comment by s3ppo** [comment]
thanks for your answer, i already use openstreetmaps now and its working, but doesnt look that beautiful than mapbox. :(

the other plugin https://github.com/mapbox/flutter-mapbox-gl is really great and i would prefer it, but as much as i understood this one isnt able to build markers or polgyons or something :(

**Comment by ibrierley** [comment]
No idea, but you may be able to get flutter_map without a tile layer (just with markers etc) with a Stack over mapbox-gl. Obviously it's not ideal and would need some extra fluff, but it could be one possibility.

**Comment by s3ppo** [comment]
well after some try and error i found the correct solution...
its quite easy, you just have to select in the dropdown of the share popup in mapbox studio the value 'CARTO'

**Comment by ibrierley** [comment]
Interesting, they don't make that clear. I can see some reference at https://docs.mapbox.com/api/maps/#raster-tiles but its not clear if you can make your own styles there, rather than the default ones. It may be worth posting the URL and any instructions you are using to help others who have the issue in future.

**Comment by SardorbekR** [comment]
**Solution: you need to make sure to select CARTO as the type under the Third Party option. This will generate a different URL which is the correct one.**

![image](https://user-images.githubusercontent.com/30071369/93848790-053e9b00-fcc4-11ea-93c7-d9c8f33ca4b9.png)

**Comment by faaqi** [comment]
> **Solution: you need to make sure to select CARTO as the type under the Third Party option. This will generate a different URL which is the correct one.**
> 
> ![image](https://user-images.githubusercontent.com/30071369/93848790-053e9b00-fcc4-11ea-93c7-d9c8f33ca4b9.png)

![map](https://user-images.githubusercontent.com/61233208/96390152-c1f52080-11cc-11eb-8839-0805a7f44a1b.png)

Where was that option? I guess mapbox is updated.
