### ISSUE TITLE
polyline onTap ?

### ISSUE THREAD

**Issue by tomaszgruzla** [fleaflet/flutter_map#559]
does polyline support onTap?

**Comment by HugoHeneault** [comment]
You should check https://github.com/OwnWeb/flutter_map_tappable_polyline plugin :)

**Comment by tomaszgruzla** [comment]
does not work as I would like
because I can only tap points of the line, but I can't tap lines between points of that line

**Comment by Mkohm** [comment]
> does not work as I would like
> because I can only tap points of the line, but I can't tap lines between points of that line

I have the same issue. Did you get it working? I am looking at generating new points in between the (data points) to support tapping. However, with lots of polylines to be drawn, I am concerned about the performance.. so looking for better solution.

**Comment by tuarrep** [comment]
@tomaszgruzla You be fixed now by https://github.com/OwnWeb/flutter_map_tappable_polyline/pull/8
