### ISSUE TITLE
TileLayer using basic auth

### ISSUE THREAD

**Issue by infinitespark** [fleaflet/flutter_map#573]
Hi, a newbie in flutter here but really interesting in learning. 
I was trying to overlay custom tiles from a private provider that requires BASIC auth.
Is there an easy way to implement this?

Thanks

**Comment by maRci002** [comment]
You can easily create a custom `TileProvider` see  #464 and you can pass it to `TileLayerOptions`.

add [authorization headers](https://flutter.dev/docs/cookbook/networking/authenticated-requests#add-authorization-headers)
`headers: {HttpHeaders.authorizationHeader: "Basic your_api_token_here"},`

**Comment by maRci002** [comment]
https://github.com/fleaflet/flutter_map/issues/464#issuecomment-570301974
