### ISSUE TITLE
Make move() animated

### ISSUE THREAD

**Issue by quetool** [fleaflet/flutter_map#587]
Hi! Is there a change to make the move() method in mapController animated?

**Comment by johnpryan** [comment]
We do have this example: https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart

**Comment by avioli** [comment]
Some time ago I needed to animate the `MapController`, so I wrote an external helper:
https://gist.github.com/avioli/a0b800d6a5ed053871ab4eec8f57c2da

Use it like so:

```dart
class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  MapController _mapCtrl;
  AnimatedMapController _animCtrl;

  @override
  void initState() {
    super.initState();
    _mapCtrl = MapController();
    _animCtrl = AnimatedMapController(
      mapController: _mapCtrl,
      tickerProvider: this,
    );
  }

  @override
  void dispose() {
    _animCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      mapController: _mapCtrl,
      options: MapOptions(
        center: LatLng(51.5, -0.09),
        zoom: 3.0,
        onTap: (coords) {
          // _animCtrl.move(coords, _animCtrl.zoom + 1);
          _animCtrl.move(coords);
        },
      ),
      layers: [...]
    });
  }
}
```

I haven't done `rotation`, since only a setter is exposed on the `MapController`, but it is trivial to add.

If you want to animate only the `zoom` level you can do:

```dart
_animCtrl.animate(() => _animCtrl.zoom = newZoom);
```

**Comment by quetool** [comment]
Will try! Thanks to both of you!

**Comment by TheLastGimbus** [comment]
Hey @avioli, just wanted to say thanks for this very much!

**Comment by maRci002** [comment]
https://github.com/fleaflet/flutter_map/issues/587#issuecomment-614302802
