### ISSUE TITLE
How to set language in the map?

### ISSUE THREAD

**Issue by firmlab** [fleaflet/flutter_map#592]
I'm wondering is there any way to set language that displayed in the map?
i tried the example on this repository, but it seems using not using English

**Comment by rorystephenson** [comment]
If you're talking about the labels that are on the map then that will depend on the map tile provider you use. Their API might allow you to specify the language.

**Comment by firmlab** [comment]
@rorystephenson I'm using open street map, is there any configuration that need to be set? 
I'm stuck with the map api, where should i start, do i need to create an account, if yes how to integrate it with this library?

**Comment by mat8854** [comment]
@firmlab This is working for the default OSM tile server (English labels):
```
              TileLayerOptions(
                  urlTemplate:
                      "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  subdomains: ['a', 'b', 'c']),
```
Also see here: https://wiki.openstreetmap.org/wiki/Tiles

**Comment by avioli** [comment]
Also check https://wiki.openstreetmap.org/wiki/Map_internationalization
