### ISSUE TITLE
Handle exception on move without internet connection

### ISSUE THREAD

**Issue by beerline** [fleaflet/flutter_map#593]
Hi flutter_map team! 

How I can handling exception while user move or zoom map but internet connect is lost?

Steps to do:
Open app with interne

1. t connection. As result we see the map
2. enable "Airplane mode"
3. tray to zoom the map
4. getting console errors

Code the same as in [this example](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/zoombuttons_plugin_option.dart) 

console errors
```
I/flutter (15443): SocketException: Failed host lookup: 'c.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'a.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'c.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'b.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'c.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'a.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'b.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'b.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15443): SocketException: Failed host lookup: 'a.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)
```

Thank you for your help!

**Comment by avioli** [comment]
The only way I can think of handling this is using a custom `TileProvider`, that keeps track of the current connectivity state and only loads tiles if connected to the internet or if a socket exception happened then await connectivity change to retry. It might have to use a custom `ImageProvider` since `getImage` is not async.

A plugin, paired with a tile provider might be a better fit, since it has access to the map state, thus will be able to invoke a reload on the visible tiles.

**Comment by maRci002** [comment]
User won't see console and as far as I know Leaflet will flood console too if there is no internet connection avaible (I tested it on browser). Anyway Flutter caches Network Images even if they loaded with error (forinstance no internet connection) so the Tiles gets stuck, take a look on #577 PR, I am goind to add connection detect strategy soon.

**Comment by beerline** [comment]
@maRci002, @avioli  thank you for your responses!

Main goal to catch this exception, is to notify user about internet connection lost. 

@maRci002 thank you for yuor PR. I will wait for it!

**Comment by avioli** [comment]
@beerline - this sounds like business logic, that’s not related to the plugin. I would say that this plugin is not supposed to handle the user facing connectivity notifications. It can handle it internally for a better user experience, but it is the developer’s job to handle connectivity state changes and notify the user accordingly in a way that makes sense for the final app.

**Comment by beerline** [comment]
@avioli totally agree with you, that this is business logic
I tried to wrap this move call by `try` `catch`
```dart
try{
  map.move(centerZoom.center, zoom);
} catch (e) {
  // handle error here
}
```
But since it useing strams under the hood `_onMoveSink.add(null);`, my `catch` can not catch this exception.

I also tried to subscribe to subscribe to this stream
```dart
map.onMoved(
  (_){}, 
  onError: (error) { // handle error here}
);
map.move(centerZoom.center, zoom);
```
But `onError` neve execute.

In theory, i can check internet connection before each call `map.move`, but i am afraid, this will be cause performance issue. And also this solution should by should be done befor each drag of map. So it seams to a lot of boilerplate code. 

may be you can suggest better solution how i can handle this exception, i will be grateful to you

**Comment by maRci002** [comment]
I think the easiest way to do this if you provide some callback method to `TileLayerOptions` and if options provided callback then fire the callback forinstace [here](https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/tile_layer.dart#L824).
```
if (options.errorTileCallback != null) {
    errorTileCallback(tile, error);
}
```

Note if you have multiple Tile Layers then you should pass your callback to every layer's `TileLayerOptions`.

**Comment by avioli** [comment]
If you are using the default tileProvider: `CachedNetworkTileProvider`, then you can recreate it with an added `errorListener`, which is invoked every time a tile cannot be loaded from the internet or the disk. This is only useful if you want to be notified though.

```dart
class MyTileProvider extends TileProvider {
  MyTileProvider({ this.onError });

  final VoidCallback onError;

  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    final url = getTileUrl(coords, options);
    return CachedNetworkImageProvider(url, errorListener: onError);
  }
}
```

Then in your Widget:

```dart
Widget build(BuildContext context) {
  return FlutterMap(
    ...
    layers: [
      TileLayerOptions(
        urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        subdomains: ['a', 'b', 'c'],
        tileProvider: MyTileProvider(onError: _onTileError),
      ),
    ],
  );
}

void _onTileError() {
  print("uh-oh - a tile couldn't load");
}
```

Unfortunately, given that `errorListener` doesn't pass the error you can only know an error has happened, but not what kind.

**Comment by avioli** [comment]
Then... if you want to go crazy you can try to get a grip of the cache manager that `CachedNetworkImageProvider` uses by default - `DefaultCacheManager`, but I would **STRONGLY SUGGEST NOT TO**...

```dart
typedef ErrorResponseHandler = Future<http.Response> Function(Object error,
    [StackTrace stack]);

class MyTileProvider extends TileProvider {
  MyTileProvider({this.errorHandler});

  final ErrorResponseHandler errorHandler;

  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    final url = getTileUrl(coords, options);
    final cacheManager = MyCacheManager()..errorHandler = errorHandler;
    return CachedNetworkImageProvider(
      url,
      cacheManager: cacheManager,
    );
  }
}

class MyCacheManager extends BaseCacheManager {
  factory MyCacheManager() => _instance ??= MyCacheManager._();

  static MyCacheManager _instance;

  MyCacheManager._()
      : super(DefaultCacheManager.key, fileFetcher: _staticFetch);

  ErrorResponseHandler errorHandler;

  @override
  Future<String> getFilePath() => DefaultCacheManager().getFilePath();

  // NOTE: need to relay the call to the instance's fetcher
  static Future<FileFetcherResponse> _staticFetch(String url,
          {Map<String, String> headers}) =>
      MyCacheManager()._fetch(url, headers: headers);

  Future<FileFetcherResponse> _fetch(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return new HttpFileFetcherResponse(response);
    } catch (e, stack) {
      if (errorHandler != null) {
        final response = await errorHandler(e, stack);
        return new HttpFileFetcherResponse(response);
      }
      rethrow;
    }
  }
}
```

Then use it like so:

```dart
Widget build(BuildContext context) {
  return FlutterMap(
    ...
    layers: [
      TileLayerOptions(
        urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        subdomains: ['a', 'b', 'c'],
        tileProvider: MyTileProvider(errorHandler: _onTileError), // <-- changed
      ),
    ],
  );
}

// This now gets an error object and a stack trace, but only for internet downloads,
// not for disk failures
Future<http.Response> _onTileError(Object err, [StackTrace stack]) {
  print("uh-oh - a tile couldn't load");
  print("error: $err");
  print(stack);
  return Future.error(err, stack);
}
```

**Comment by beerline** [comment]
@avioli thank you for your solution!
But unfortinaltly `SocketException` failed before checking `if (file == null) `  in `CachedNetworkImageProvider._loadAsync`.  I wrap whole body of method `_loadAsync` by `try` `catch` to show it.

[Please see screencast ](https://drive.google.com/file/d/1kPqST5_cI0AodyZnlODTHNphi39q_hff/view?usp=sharing)

**Comment by beerline** [comment]
Implementrd this solution https://github.com/johnpryan/flutter_map/issues/593#issuecomment-617223642

PR: https://github.com/johnpryan/flutter_map/pull/600

**Comment by tierecke** [comment]
Still not solved. Shouldn't it be added as an issue?

**Comment by ibrierley** [comment]
Didn't the PR #600 fix it ?
