### ISSUE TITLE
Adding Map Boundaries

### ISSUE THREAD

**Issue by GN-c** [fleaflet/flutter_map#604]
Hello,
I'm working on mobile version of my old project [T-map](http://www.t-map.gncorp.com.ge/).
I'm trying add country border boundaries but I think they are not supported in flutter_map yet

![Boundaries](https://user-images.githubusercontent.com/64430939/80401238-1037ff80-88cd-11ea-98ec-0eeac6bc0a26.png)

**Comment by moovida** [comment]
What do you mean by border boundaries? Border polygons? Or bounds to block pan?

**Comment by GN-c** [comment]
Map boundary that goes along the country border.
Leaflet does not load map blocks outside that boundary, that's main difference between polygon and boundary

**Comment by moovida** [comment]
Ah, ok, something like a mask, right? Didn't see that in the project. Nice to have though :-)

**Comment by GN-c** [comment]
Yes, exactly
