### ISSUE TITLE
Not all tiles are loading if i use Zoom Levels like 14.7

### ISSUE THREAD

**Issue by eazy2x** [fleaflet/flutter_map#605]
1st, forgive me if the problem is on my side, still new in programming/flutter.

I am trying to build a Map view, which whereever you are (Latitude - north/south) always displays the same distance (in meter) on the screen, with fixed zoom Level.  Seeing that Zoom Level ist a double, i thought, cool no big deal, but now if i set it to 14.7 as an example this happens:

![image](https://user-images.githubusercontent.com/63650733/80427527-3d45db80-88e8-11ea-8710-72dc55c5f665.png)

The tiles at the corners wont load until you move a bit closer to them in the map view, any way to trigger them loading a bit earlier or maybe fix that (if thats really an "issue")?

Oh and i use Mapbox, 'mapbox.dark', dont mind the Hexagons on top of the map they are markers.

**Comment by johnpryan** [comment]
This looks like a bug to me, do you have a lat/long and and size to reproduce the issue?

**Comment by ibrierley** [comment]
Reminds me a bit of this bug
https://github.com/johnpryan/flutter_map/pull/525 but I think the latest
version superceded, but that code is still in there if someone else is
using it.

**Comment by eazy2x** [comment]
This happens anywhere, anytime (if you havent cached the map arround) but just with 14.7  zoom set (zoom, maxzoom and minzoom) i noticed it. Some decimals like 15.2 work fine, seems only the last bit until you reach the next Level? This example anyway is at LatLng(64.137125, -21.902071); (island)

Might also be different depending on phone screen size/ratio? I am using Nexus 6 api 28 for the emulator.

**Comment by ibrierley** [comment]
I have a pull request in that link above, it's only one tiny change in a
file you could temp try and then restore to original. It would be
interesting to see if you can try it and see if it helps at all.

Ian

**Comment by eazy2x** [comment]
Sorry as i said i am really a newbie, have no clue how to quickly test another version of a package, i am happy that i got it running at all so far.

**Comment by eazy2x** [comment]
sorry accidently closed

**Comment by eazy2x** [comment]
i tested 0.8.2 now (changed yaml file/pub get) which should revert that (and other stuff) but same issue, using 14.7 zoom wont load tiles if they are at the edges of the screen.

**Comment by ibrierley** [comment]
any way for you to have a minimal example that breaks it that people could try ?

**Comment by eazy2x** [comment]
Basicly used the "on_tap" page in examples, using that and set all zoom levels to 14.7 should do the trick.

**Comment by ibrierley** [comment]
Have you tried 0.9.0 ?

**Comment by eazy2x** [comment]
did some testings:

it is worst at 14.5 getting better slowly until 15 is fine. Then 15.0 - 15.49 has no problem at all

so just the .5  to .99 range is causing the problem

**Comment by eazy2x** [comment]
> Have you tried 0.9.0 ?
> […](#)

sure, before i used "any" so should have been, going back to 0.8.2 was my quick way to test the package before your pull (checked dates) as i have no clue how to change it manually.

**Comment by ibrierley** [comment]
Works fine for me at that zoom level 14.7, but may be you need to be more
specific with the code changes (latlngs and if it's just the flutter_map
zoom to 14.7 or whatever) to replicate.

**Comment by eazy2x** [comment]
oh and i think it depends on the latitude you are on, swapped to Singapore (near 0) and at 14.5 i have barely an issue (just a tiny bit), so issue seems to come with the stretch factor of the map, going nort/south 

the very problem i am working on right now (to show fixed size window with same meters) 
working formulas i foud here: 
https://gis.stackexchange.com/questions/110730/mercator-scale-factor-is-changed-along-the-meridians-as-a-function-of-latitude

**Comment by eazy2x** [comment]
//  static LatLng startPoint = LatLng(71.167802, 25.782208); //Nordkap
//  static LatLng startPoint = LatLng(64.137125, -21.902071); // Island
//  static LatLng startPoint = LatLng(34.031037, -5.002876); // Marokko
  static LatLng startPoint = LatLng( 1.329646, 103.840275); // Singapur

center: startPoint,
          zoom: fixedZoom,
          maxZoom: fixedZoom,
          minZoom: fixedZoom,

and fixed zoom i just set by hand to test some samples, now i want to compute it, using the formulas in that stack link and break it down to mapzoom using log2

**Comment by eazy2x** [comment]
to compare: singapore at 14.5 lvl (thats the worst i can get it to by slowly moving map)
![image](https://user-images.githubusercontent.com/63650733/80468776-f4ba0c80-893f-11ea-95bd-f992fd8289ec.png)

vs cape north, again worst case by slowly moving map 

![image](https://user-images.githubusercontent.com/63650733/80469045-50849580-8940-11ea-94c3-ff7c53724378.png)

**Comment by eazy2x** [comment]
from math aspect, i guess the error is no counting in the stretch of the map projection, to dig/dive into the code of package i am not able at this point, even struggle to understand basic stuff, but hope my observations my help you guys, probably not many testing uneven zoom levels up north lol

**Comment by ibrierley** [comment]
As mentioned, I can't replicate the problem, but maybe someone else can
spot it.

But it would be useful to have a specific example people can add to check
to see if they get the same problem.

Ian

**Comment by eazy2x** [comment]
i will try to put an example together, tried OSM now as provider, tiles are smaller compared to mapbox, issue still there but not that obvious as the width of possible missing tiles is cut by / 2

**Comment by eazy2x** [comment]
Now i am confused, trying to rebuild, all works fine, removed paddings, column/flex/deleted app bar, also hide status bar, all works in this sample app as usual. 

also did remove that "drawer: ..." as i only use 1 screen (but i dont really know what this is doing) could it be the issue? sorry for wasting your time :/ 

could send you my //spaghetti// code i am not to proud of

**Comment by maRci002** [comment]
Unreproducible, tested with this code:
```dart
class OnTapPage extends StatelessWidget {
  static const String route = 'on_tap';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar(title: Text('OnTap')),
      drawer: buildDrawer(context, OnTapPage.route),
      body: FlutterMap(
        options: MapOptions(
          center: LatLng(51.5, -0.09),
          zoom: 2.7,
          maxZoom: 15.0,
          minZoom: 3.0,
          onTap: print,
        ),
        layers: [
          TileLayerOptions(
            urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            subdomains: ['a', 'b', 'c'],
          ),
        ],
      ),
    );
  }
}
```
