### ISSUE TITLE
MBTilesImageProvider.fromFile out of bound error not catch

### ISSUE THREAD

**Issue by shunnokw** [fleaflet/flutter_map#617]
I imported a mbtile by ```MBTilesImageProvider.fromAssets``` and everythings work fine.
If the user scroll out of bound, error will be caught and shown.
But when I try to import the same map by ```MBTilesImageProvider.fromFile```, 
when I scroll out of bound, the app freeze as the error not being caught.
After I look around the sources code, I found that when transfering from assets to file,
one more line is executed:
``` dart
 file.writeAsBytesSync(
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
        flush: true);
```

Is there any reason not executed when user import from file?
Or it is a bug? If it is, I can help create a PR since I have fixed on my own version.

Thanks

**Comment by kengu** [comment]
MBTilesProvider was removed from flutter_map in version [0.11.0](https://pub.dev/packages/flutter_map/changelog#0110---10292020).
