### ISSUE TITLE
Error: Method not found: 'LatLng'.  

### ISSUE THREAD

**Issue by Zaboy15** [fleaflet/flutter_map#625]
Hello , I Have error this Error: Method not found: 'LatLng'.  

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';

class DataMaps extends StatefulWidget {
  @override
  _DataMapsState createState() => _DataMapsState();
}

class _DataMapsState extends State<DataMaps> {

  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body:  new FlutterMap(
    options: new MapOptions(
      center: LatLng(51.5, -0.09),
      zoom: 13.0,
    ),
    layers: [
      new TileLayerOptions(
        urlTemplate: "https://api.tiles.mapbox.com/v4/"
            "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
        additionalOptions: {
          'accessToken': 'Key',
          'id': 'mapbox.streets',
        },
      ),
      new MarkerLayerOptions(
        markers: [
          new Marker(
            width: 80.0,
            height: 80.0,
            point:  LatLng(51.5, -0.09),
            builder: (ctx) =>
            new Container(
              child: new FlutterLogo(),
            ),
          ),
        ],
      ),
    ],
      )
      
    );
  }
}
```

**Comment by PatrykGala** [comment]
You need import:
`import 'package:latlong/latlong.dart';`

**Comment by SaileshVerma** [comment]
after importing the import 'package:latlong/latlong.dart';    still i m  unable to use Latlng pls help its shows Latlng not defined

**Comment by Swepilot** [comment]
And you have added it to your pubspec.yaml?

[https://pub.dev/packages/latlong/install](https://pub.dev/packages/latlong/install)

**Comment by SunnyMittal** [comment]
this issue still exists :(
created a flutterMap widget as suggested on this link, but i see squiggly red line below the LatLng method name.

![image](https://user-images.githubusercontent.com/8129184/123538138-64679980-d787-11eb-9f1b-3d4231b10f3b.png)

https://pub.dev/packages/flutter_map 
Widget build(BuildContext context) {
  return FlutterMap(
    options: MapOptions(
      center: LatLng(51.5, -0.09),
      zoom: 13.0,
    ),
    layers: [
      MarkerLayerOptions(
        markers: [
          Marker(
            width: 80.0,
            height: 80.0,
            point: LatLng(51.5, -0.09),
            builder: (ctx) =>
            Container(
              child: FlutterLogo(),
            ),
          ),
        ],
      ),
    ],
    children: <Widget>[
      TileLayerWidget(options: TileLayerOptions(
        urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        subdomains: ['a', 'b', 'c']
      )),
      MarkerLayerWidget(options: MarkerLayerOptions(
        markers: [
          Marker(
            width: 80.0,
            height: 80.0,
            point: LatLng(51.5, -0.09),
            builder: (ctx) =>
            Container(
              child: FlutterLogo(),
            ),
          ),
        ],
      )),
    ],
  );
}

**Comment by ibrierley** [comment]
You need to import latlong2 0.8.0 not latlong. If you have problems still, do a "flutter pub deps" and it will probably highlight it's using an old latlng somewhere.

**Comment by abdulsamad110** [comment]
First Import This to pubspec.yaml
![av](https://user-images.githubusercontent.com/69845934/133738626-dfef0b1d-6f96-4190-b193-663a5396fe90.PNG)
Then Import this
![bv](https://user-images.githubusercontent.com/69845934/133738753-0e215880-a1cb-4489-8e3d-d5f9b8c03e2a.PNG)
Then Error will be resolved
![cv](https://user-images.githubusercontent.com/69845934/133738796-89edb976-ca53-4baa-952b-85738078354e.PNG)
