### ISSUE TITLE
Get an error "Undefined class 'Proj4Crs'."

### ISSUE THREAD

**Issue by kvbogdanov** [fleaflet/flutter_map#628]
> import 'package:flutter/material.dart';
> import 'package:flutter/foundation.dart';
> import 'package:flutter_map/flutter_map.dart';
> import 'package:flutter_map/plugin_api.dart';
> import 'package:flutter_map_marker_cluster/flutter_map_marker_cluster.dart';
> import 'package:latlong/latlong.dart';
> import 'package:shared_preferences/shared_preferences.dart';
> import 'package:countree/widgets/drawer.dart';
> import 'package:countree/data/cities.dart';
> import 'package:countree/data/colors.dart';
> import 'package:countree/pages/treeform.dart';
> import 'package:uuid/uuid.dart';
> import 'dart:async';
> import 'dart:convert';
> import 'package:dio/dio.dart';
> import 'package:proj4dart/proj4dart.dart' as proj4;
> 
> class HomePage extends StatefulWidget {
>   static const String route = '/';
> 
>   @override
>   HomePageState createState() {
>     return HomePageState();
>   }
> }
> 
> class HomePageState extends State<HomePage>{
>   final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
>   Proj4Crs epsg3413CRS; // <--- ERROR "Undefined class 'Proj4Crs'."
>

**Comment by maRci002** [comment]
Make sure you are using latest flutter_map and run `flutter pub get`
