### ISSUE TITLE
How to draw a polygon crossing the -180/180° lon bound

### ISSUE THREAD

**Issue by S-Man42** [fleaflet/flutter_map#630]
Hi,

I want to draw a line or a polygon from 179° to -179°. Currently the resulting line is a line crossing the whole map. This is not expected. Is there a way to draw the line one degree at the left and one degree at the right or something similar?

Kind regards!

**Comment by quai20** [comment]
@S-Man42 Did you manage to solve this ?

**Comment by S-Man42** [comment]
Unfortunately not yet. Most wanted solution in this library for me...

**Comment by geweald** [comment]
I'm facing the same issue, any chances to fix it? @johnpryan

**Comment by ibrierley** [comment]
It may be worth taking a look at the Leaflet.js code to see how they get around this.

**Comment by quai20** [comment]
I did manage to get around my problem by plotting the marker at longitude -182° instead of longitude 178° for example. It ugly but it works, I just needed to tweak the latlong package because it checks that longitude is indeed between -180/180. I just removed that check.

**Comment by Huanxin1997** [comment]
> I did manage to get around my problem by plotting the marker at longitude -182° instead of longitude 178° for example. It ugly but it works, I just needed to tweak the latlong package because it checks that longitude is indeed between -180/180. I just removed that check.

Hi quai20，I tried this method drawing the route line. But outside the bound, I can't change the zoom in the map. Did you face this problem.

**Comment by quai20** [comment]
Hi @Huanxin1997 ,
No I don't have any zoom problem. Here's how is defined my map : 
```
FlutterMap(
              options: new MapOptions(
                center: new LatLng(latitude, longitude),
                zoom: 6.0,
                interactiveFlags:
                    InteractiveFlag.pinchZoom | InteractiveFlag.drag,
                maxZoom: 10.0,
                minZoom: 3.0,
              )
```

**Comment by Huanxin1997** [comment]
> Hi @Huanxin1997 , No I don't have any zoom problem. Here's how is defined my map :
> 
> ```
> FlutterMap(
>               options: new MapOptions(
>                 center: new LatLng(latitude, longitude),
>                 zoom: 6.0,
>                 interactiveFlags:
>                     InteractiveFlag.pinchZoom | InteractiveFlag.drag,
>                 maxZoom: 10.0,
>                 minZoom: 3.0,
>               )
> ```

<img width="388" alt="image" src="https://user-images.githubusercontent.com/42678103/161921031-26139cde-8f46-4e31-a632-2757b8c347fc.png">
Hello.
In the left section, the longitude is smaller than -180. The right section is the normal case. When I zoom in right section, it's OK. But when I zoom in the left section, It seems limited. As shown in the figure below, I can not zoom in to see the left end point.
<img width="213" alt="image" src="https://user-images.githubusercontent.com/42678103/161924651-df2d0de1-e754-485a-86a6-a882038257be.png">

**Comment by quai20** [comment]
Sorry, I don't know where this could come from. 
If you want to share some code so I can try on my side, we can talk on gitter.

**Comment by S-Man42** [comment]
Is there any news on longitude "overflowing" polygones without doing some hacky stuff?

**Comment by JaffaKetchup** [comment]
Hi @S-Man42, this is supported natively in v8.

**Comment by S-Man42** [comment]
Haha, great to hear! And after all these years I found a workaround! Damn :D Well I try and mayby my workaround never needs to be used!
