### ISSUE TITLE
请问flutter_map的版本和flutter的版本有什么要求吗？

### ISSUE THREAD

**Issue by bubinyang** [fleaflet/flutter_map#635]
我的flutter版本是1.12.16和flutter_map: ^0.6.1+2，一直报错

“
Compiler message:
/C:/Users/Administrator/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/flutter_map-0.6.1+2/lib/src/layer/mbtiles/mbtiles_image_provider.dart:88:24: Error: The method 'MBTileImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(MBTileImage key) {
                       ^
/C:/Users/Administrator/Downloads/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
/C:/Users/Administrator/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/flutter_image-2.0.0/lib/network.dart:73:24: Error: The method 'NetworkImageWithRetry.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(NetworkImageWithRetry key) {
                       ^
/C:/Users/Administrator/Downloads/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
”

**Comment by ruizalexandre** [comment]
Try with a higher version please
```
dependencies:
  flutter_map: ^0.9.0
```
Follow right instruction here
https://pub.dev/packages/flutter_map#-installing-tab-
