### ISSUE TITLE
Tiles are not shown if used in another instance of FlutterMap

### ISSUE THREAD

**Issue by guenth39** [fleaflet/flutter_map#636]
For details look at the screen record from current version of example app.
To reproduce just start the example app and switch between 'MapController' and 'AnimatedMapController'. Unfortunately it’s blocking the app in my use case of FlutterMap because I push multiple instances of FlutterMap with `ineractive: false` to the navigation stack and you can just remove the 'grayscreen' by zooming in or out. Would be awesome to have a solution for that.

![video-2020-05-28-16-56-41](https://user-images.githubusercontent.com/29251617/83158875-a0a07480-a105-11ea-97d4-86c1e92f0358.gif)

Best Regards

**Comment by guenth39** [comment]
I think it has something to do with the `CachingNetworkTileProvider` because the issue does not appear on the `ZoomButtonPlugins` Page and there the `NonCachingNetworkTileProvider` is used.

**Comment by ibrierley** [comment]
You may be able to fake it by adding a move or slightly changing the zoom to something and back again, which will force a refresh ?

**Comment by guenth39** [comment]
Thanks for that hint. Thought about that earlier but didn't came back to it. Tried it now and works fine :) added the following code:
```
@override
  void didUpdateWidget(SimpleMapView oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.position != oldWidget.position || widget.zoom != oldWidget.zoom)
      _mapController?.move(widget.position, 18);
    Future.delayed(Duration(milliseconds: 200)).then(
      (value) => _mapController?.move(widget.position, widget.zoom),
    );
  }
```

**Comment by ruizalexandre** [comment]
With flutter_map version 8, tiles are correctly displayed. 
Seems that a commit from version 9 break something. 
Need to explore git history and find the issue

**Comment by ruizalexandre** [comment]
@johnpryan PR available
Fix the race condition

**Comment by ruizalexandre** [comment]
⚠️ After many tests, rotation is broken too since the commit **d4aefaecc44d0c0b431375fd7bc97b2ef1a214e7**

I'm working also to fix that

**Comment by maRci002** [comment]
PR #715 is an easy applicable fix, try it out.
