### ISSUE TITLE
Marker Anchor Error

### ISSUE THREAD

**Issue by 244226077** [fleaflet/flutter_map#640]
I want to put a location_on icon marker with it's pin at a point, try AnchorAlign.center,AnchorAlign.top and AnchorAlign.bottom,but the pin of the icon don't anchor on the point I want
marker = new Marker(
    point: pos,
    builder: (_) =>
 Icon(Icons.location_on,
    color: Color.fromRGBO(0, 0, 255, 1),
    size: MapPge.markerSize),
    anchorPos: AnchorPos.align(AnchorAlign.center),//AnchorAlign.top,AnchorAlign.bottom
);
![bottom](https://user-images.githubusercontent.com/33371469/83401559-9d73f400-a437-11ea-81e4-835a5a5a8bc9.png)
![center](https://user-images.githubusercontent.com/33371469/83401561-9ea52100-a437-11ea-8677-9e0dcc468aec.png)
![top](https://user-images.githubusercontent.com/33371469/83401562-9ea52100-a437-11ea-8b4b-ec577494cb8e.png)

**Comment by Swepilot** [comment]
Not sure if this helps but I had to play around with the `height` of the `Marker` to get it to work for me

**Comment by 244226077** [comment]
> Not sure if this helps but I had to play around with the `height` of the `Marker` to get it to work for me
Will it works for all scale？

**Comment by MooNag** [comment]
What I do to make the bottom of the marker line up perfectly on the point is this, make sure the size of the icon matches the height. This will work for all scales and zoom levels:

```
MarkerLayerOptions(
  markers: [
    Marker(
      width: 12.0,
      height: 24.0,
      anchorPos: AnchorPos.exactly(Anchor(0, 0)),
      point: new LatLng( YOUR LATITUDE , YOUR LONGITUDE ),
      builder: (ctx) => Container(
        child: Icon(Icons.location_on, color: Colors.red, size: 24),
      ),
    ),
  ],
),
```
