### ISSUE TITLE
Location lat-lng getting wrong when using Yandex Map

### ISSUE THREAD

**Issue by savasadar** [fleaflet/flutter_map#642]
I am using flutter_map with yandex map like below. When I mark a location, Getting location lat and lon are wrong. So If I draw a polygon on the map, It drawn on wrong location. How to fix this?

```dart
FlutterMap(
  options: MapOptions(
    center: LatLng(41.334554,36.269617),
    zoom: 11.0,
    maxZoom: 18,
    minZoom: 5,
    plugins: [
      DragMarkerPlugin(),
    ],
    onTap: (value){
      print(value.toString());
      markLocation(value);
    },
  ),
  layers: [
    TileLayerOptions(
        urlTemplate: 'https://core-sat.maps.yandex.net/tiles?l=sat&v=3.569.0&x={x}&y={y}&z={z}&lang=tr_TR'
    ),
    TileLayerOptions(
        urlTemplate: 'http://vec{s}.maps.yandex.net/tiles?l=skl&v=20.06.03&z={z}&x={x}&y={y}&scale=1&lang=tr_TR',
        subdomains: ['01', '02', '03', '04'],
        backgroundColor: Colors.transparent
    ),
    CircleLayerOptions(
        circles: _circles
    ),
    PolygonLayerOptions(
      polygons: getPolygons()
    ),
    DragMarkerPluginOptions(
      markers: _markers
    )
  ],
  mapController: _mapController,
)
```

Actual position of polygon:
![Screen Shot 2020-06-03 at 17 34 38](https://user-images.githubusercontent.com/1931570/83650162-b360f080-a5c0-11ea-84f1-2c70edf64d44.png)

And How to looks on device?
![Screenshot_20200603-173706](https://user-images.githubusercontent.com/1931570/83650567-29655780-a5c1-11ea-94c7-f6ab529eafdd.png)

**Comment by ruizalexandre** [comment]
Projection issue ? Using 4326 can fix this ?

**Comment by savasadar** [comment]
> Projection issue ? Using 4326 can fix this ?

I have no idea what is 4326. Could you describe what is the 4326 and how can I use it?

**Comment by savasadar** [comment]
> L.CRS.EPSG3395 | Rarely used by some commercial tile providers. Uses Elliptical Mercator projection.
> -- | --
> L.CRS.EPSG3857 | The most common CRS for online maps, used by almost all free and commercial tile providers. Uses Spherical Mercator projection. Set in by default in Map's crs option.



I guess yandex map use EPSG3395 ellipsoid projection.

> https://tech.yandex.com/maps/jsapi/doc/2.1/ref/reference/projection.wgs84Mercator-docpage/

flutter_map support EPSG3857 and EPSG4326 but not EPSG3395. How can I implement EPSG3395 as a custom csr?

**Comment by moovida** [comment]
Yes, look at this part for how to do it: https://github.com/johnpryan/flutter_map#custom-crs

**Comment by savasadar** [comment]
I am trying to work with custom csr and There are some problems about it. I defined custom csr for 3395 like below.

```dart
epsg3395 = proj4.Projection('EPSG:3395') ??
        proj4.Projection.add('EPSG:3395', '+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');

    final epsg3395Bounds = Bounds<double>(
      CustomPoint<double>(-180.0, -80.0),
      CustomPoint<double>(180.0, 84.0),
    );

    final resolutions = <double>[
      32768,
      16384,
      8192,
      4096,
      2048,
      1024,
      512,
      256,
      128,
    ];

    // Define CRS
    epsg3395CRS = Proj4Crs.fromFactory(
      // CRS code
      code: 'EPSG:3395',
      // your proj4 delegate
      proj4Projection: epsg3395,
      // Resolution factors (projection units per pixel, for example meters/pixel)
      // for zoom levels; specify either scales or resolutions, not both
      resolutions: resolutions,
      // Bounds of the CRS, in projected coordinates
      // (if not specified, the layer's which uses this CRS will be infinite)
      bounds: epsg3395Bounds,
      // Tile origin, in projected coordinates, if set, this overrides the transformation option
      // Some goeserver changes origin based on zoom level
      // and some are not at all (use explicit/implicit null or use [CustomPoint(0, 0)])
      // @see https://github.com/kartena/Proj4Leaflet/pull/171
      origins: [CustomPoint(0,0)],
      // Scale factors (pixels per projection unit, for example pixels/meter) for zoom levels;
      // specify either scales or resolutions, not both
      scales: null,
      // The transformation to use when transforming projected coordinates into pixel coordinates
      transformation: null,
    );
```
I got definion from https://epsg.io/3395

When I set custom csr to map with MapOptions, Tiles not loading.

![Screen Shot 2020-06-04 at 14 43 40](https://user-images.githubusercontent.com/1931570/83752946-1199dc00-a672-11ea-8e39-19b08bbc23ee.png)

![Screen Shot 2020-06-04 at 14 46 09](https://user-images.githubusercontent.com/1931570/83752991-26766f80-a672-11ea-9477-4f62fdec5147.png)

**Comment by savasadar** [comment]
When I manipulate location latitude polygon come to true location. But I know this is not right way for solve the issue, I am still research how to use custom csr.

`LatLng(item.latitude*0.99538824, item.longitude)`

Result:
![Screen Shot 2020-06-04 at 15 42 40](https://user-images.githubusercontent.com/1931570/83758028-0d71bc80-a67a-11ea-90b4-e752dcb8eea6.png)

**Comment by maRci002** [comment]
Try change resolutions based on [this](https://github.com/maRci002/proj4dart/issues/2#issuecomment-612389717).

Or maybe [hardcoded resolutions](https://www.arcgis.com/sharing/rest/content/items/a96dda2971cd4ece92553a5ab0b56b1b/data) works.
```dart
    final resolutions = <double>[
      156543.03390625003,
      78271.51695312501,
      39135.75847656251,
      19567.879238281253,
      9783.939619140627,
... so on
    ];
```

**Comment by dmitrienkop** [comment]
@savasadar 

I wrote custom CSR and for me everything working just fine with Yandex tiles:

`
import 'dart:math' as math;
import 'package:flutter_map/plugin_api.dart';
import 'package:latlong/latlong.dart';

class Epsg3395 extends Earth {
  @override
  final String code = 'EPSG:3395';

  @override
  final Projection projection = const Mercator();

  @override
  final Transformation transformation = const Transformation(_scale, 0.5, -_scale, 0.5);

  static const num _scale = 0.5 / (math.pi * Mercator.r);

  const Epsg3395() : super();
}

class Mercator extends Projection {
  static const int r = 6378137;
  static const double rMinor = 6356752.314245179;
  static final Bounds<double> _bounds = Bounds<double>(
    CustomPoint<double>(-20037508.34279, -15496570.73972),
    CustomPoint<double>(20037508.34279, 18764656.23138),
  );

  const Mercator() : super();

  @override
  Bounds<double> get bounds => _bounds;

  @override
  CustomPoint project(LatLng latlng) {
    var d = math.pi / 180;
    var y = latlng.latitude * d;
    var tmp = rMinor / r;
    var e = math.sqrt(1 - tmp * tmp);
    var con = e * math.sin(y);

    var ts = math.tan(math.pi / 4 - y / 2) / math.pow((1 - con) / (1 + con), e / 2);
    y = -r * math.log(math.max(ts, 1E-10));

    return CustomPoint(latlng.longitude * d * r, y);
  }

  @override
  LatLng unproject(CustomPoint point) {
    var d = 180 / math.pi;
    var tmp = rMinor / r;
    var e = math.sqrt(1 - tmp * tmp);
    var ts = math.exp(-point.y / r);
    var phi = math.pi / 2 - 2 * math.atan(ts);

    for (var i = 0, dphi = 0.1, con; i < 15 && dphi.abs() > 1e-7; i++) {
			con = e * math.sin(phi);
			con = math.pow((1 - con) / (1 + con), e / 2);
			dphi = math.pi / 2 - 2 * math.atan(ts * con) - phi;
			phi += dphi;
		}

    return LatLng(phi * d, point.x * d / r);
  }
}
`

Hope, it helps.

**Comment by savasadar** [comment]
@dmitrienkop Thank you. This is working.

**Comment by zappaz00** [comment]
Unfortunately, in v7 version the Transformation and CrsWithStaticTransformation (replacing the old Earth class) classes were hidden. After migration I had to copy these classes to myself...

**Comment by mukhtorov712** [comment]
I implemented it as follows. For versions higher than v7

`
import 'dart:math' as math;
import 'dart:math';

import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class _WorldMercator extends Projection {
  static const int _r = 6378137;
  static const _d = math.pi / 180;
  static const double _rMinor = 6356752.314245179;
  static const _tmp = _rMinor / _r;
  static final _e = math.sqrt(1 - _tmp * _tmp);

  static const Bounds<double> boundList = Bounds.unsafe(
    Point(-20037508.34279, -15496570.73972),
    Point(20037508.34279, 18764656.23138),
  );

  const _WorldMercator() : super(boundList);

  /// Project latitude using World Mercator formula
  static double _projectLat(double latitude) {
    var y = latitude * _d;
    var con = _e * math.sin(y);
    var ts = math.tan(math.pi / 4 - y / 2) / math.pow((1 - con) / (1 + con), _e / 2);
    return -_r * math.log(math.max(ts, 1E-10));
  }

  /// Project longitude using World Mercator formula
  static double _projectLng(double longitude) {
    return _r * math.pi / 180 * longitude;
  }

  @override
  (double, double) projectXY(LatLng latlng) {
    return (
      _projectLng(latlng.longitude),
      _projectLat(latlng.latitude),
    );
  }

  @override
  LatLng unprojectXY(double x, double y) {
    var ts = math.exp(-y / _r);
    var phi = math.pi / 2 - 2 * math.atan(ts);

    for (num i = 0, dPhi = 0.1, con = 0; i < 15 && dPhi.abs() > 1e-7; i++) {
      con = _e * math.sin(phi);
      con = math.pow((1 - con) / (1 + con), _e / 2);
      dPhi = math.pi / 2 - 2 * math.atan(ts * con) - phi;
      phi += dPhi;
    }
    return LatLng(phi * _d, x * _d / _r);
  }
}

class Epsg3395 extends Crs {
  static const double _scale = 0.5 / (math.pi * _WorldMercator._r);
  static const Projection _proj = _WorldMercator();
  static const Bounds<double> _projBounds = _WorldMercator.boundList;

  const Epsg3395()
      : super(
          code: 'EPSG:3395',
          infinite: false,
          wrapLng: (-180, 180),
        );

  @override
  Projection get projection => _proj;

  @override
  (double, double) transform(double x, double y, double scale) =>
      (scale * (_scale * x + 0.5), scale * (-_scale * y + 0.5));

  @override
  (double, double) untransform(num x, num y, double scale) => (
        (x / scale - 0.5) / _scale,
        (-y / scale + 0.5) / _scale,
      );

  @override
  (double, double) latLngToXY(LatLng latlng, double scale) {
    final (x, y) = _proj.projectXY(latlng);
    return transform(x, y, scale);
  }

  @override
  LatLng pointToLatLng(math.Point point, double zoom) {
    final (x, y) = untransform(point.x, point.y, scale(zoom));
    return _proj.unprojectXY(x, y);
  }

  @override
  double scale(double zoom) => 256.0 * math.pow(2, zoom);

  @override
  Bounds<double>? getProjectedBounds(double zoom) {
    final s = scale(zoom);
    return Bounds(
      math.Point(_projBounds.min.x * s, _projBounds.min.y * s),
      math.Point(_projBounds.max.x * s, _projBounds.max.y * s),
    );
  }
}
`

**Comment by mukhtorov712** [comment]
I implemented it as follows. For versions higher than v7.

```
import 'dart:math' as math;
import 'dart:math';

import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class _WorldMercator extends Projection {
  static const int _r = 6378137;
  static const _d = math.pi / 180;
  static const double _rMinor = 6356752.314245179;
  static const _tmp = _rMinor / _r;
  static final _e = math.sqrt(1 - _tmp * _tmp);

  static const Bounds<double> boundList = Bounds.unsafe(
    Point(-20037508.34279, -15496570.73972),
    Point(20037508.34279, 18764656.23138),
  );

  const _WorldMercator() : super(boundList);

  /// Project latitude using World Mercator formula
  static double _projectLat(double latitude) {
    var y = latitude * _d;
    var con = _e * math.sin(y);
    var ts = math.tan(math.pi / 4 - y / 2) / math.pow((1 - con) / (1 + con), _e / 2);
    return -_r * math.log(math.max(ts, 1E-10));
  }

  /// Project longitude using World Mercator formula
  static double _projectLng(double longitude) {
    return _r * math.pi / 180 * longitude;
  }

  @override
  (double, double) projectXY(LatLng latlng) {
    return (
      _projectLng(latlng.longitude),
      _projectLat(latlng.latitude),
    );
  }

  @override
  LatLng unprojectXY(double x, double y) {
    var ts = math.exp(-y / _r);
    var phi = math.pi / 2 - 2 * math.atan(ts);

    for (num i = 0, dPhi = 0.1, con = 0; i < 15 && dPhi.abs() > 1e-7; i++) {
      con = _e * math.sin(phi);
      con = math.pow((1 - con) / (1 + con), _e / 2);
      dPhi = math.pi / 2 - 2 * math.atan(ts * con) - phi;
      phi += dPhi;
    }
    return LatLng(phi * _d, x * _d / _r);
  }
}

class Epsg3395 extends Crs {
  static const double _scale = 0.5 / (math.pi * _WorldMercator._r);
  static const Projection _proj = _WorldMercator();
  static const Bounds<double> _projBounds = _WorldMercator.boundList;

  const Epsg3395()
      : super(
          code: 'EPSG:3395',
          infinite: false,
          wrapLng: (-180, 180),
        );

  @override
  Projection get projection => _proj;

  @override
  (double, double) transform(double x, double y, double scale) =>
      (scale * (_scale * x + 0.5), scale * (-_scale * y + 0.5));

  @override
  (double, double) untransform(num x, num y, double scale) => (
        (x / scale - 0.5) / _scale,
        (-y / scale + 0.5) / _scale,
      );

  @override
  (double, double) latLngToXY(LatLng latlng, double scale) {
    final (x, y) = _proj.projectXY(latlng);
    return transform(x, y, scale);
  }

  @override
  LatLng pointToLatLng(math.Point point, double zoom) {
    final (x, y) = untransform(point.x, point.y, scale(zoom));
    return _proj.unprojectXY(x, y);
  }

  @override
  double scale(double zoom) => 256.0 * math.pow(2, zoom);

  @override
  Bounds<double>? getProjectedBounds(double zoom) {
    final s = scale(zoom);
    return Bounds(
      math.Point(_projBounds.min.x * s, _projBounds.min.y * s),
      math.Point(_projBounds.max.x * s, _projBounds.max.y * s),
    );
  }
}
```

**Comment by psijikk** [comment]
@zappaz00 Hi. Can you show me the implementation of the CRS 3395 class itself? Thanks!
