### ISSUE TITLE
MapBox Style

### ISSUE THREAD

**Issue by Jack74r** [fleaflet/flutter_map#645]
Hello ,
Mapbox no longer allows you to add layers as explained in the documentation.
Instead we have to use this id: mapbox.mapbox-streets-v8
But I'm getting a black card with a lot of text.
![image](https://user-images.githubusercontent.com/25966996/83950056-2cae4c80-a828-11ea-8a45-af634dd48841.png)

How can I get the map back just as it was before?

Is it possible to use the Style of MapBox Studio?
urlTemplate : https://api.mapbox.com/styles/v1/name/token
I get an error:  "Could not instantiate image codec."

Thank

**Comment by kalimuthu123** [comment]
Hi me also getting the same error  as  in my case

**Comment by GeoffGodwin** [comment]
I have the same issue. The API Docs at MapBox specify you can append a style= attribute to the call, which seems to be completely ignored. When I add the style attribute the tile still returns via HTTPS but with no style applied.

**Comment by ibrierley** [comment]
Where are you looking in the mapbox docs ?

**Comment by GeoffGodwin** [comment]
I found the error in my URL. I had updated my old URL from the classic tiles to the new and left in the wrong file extension. For anyone else who stumbles across this, my working URL ended up like this:

https://api.mapbox.com/styles/v1/{user}/{style}/tiles/256/{z}/{x}/{y}@2x?access_token={accessToken}

Where the user is my own user account and the style is the alphanumeric style code. Without a style I get the above black map with overly messy text. Turning off retinaMode and using the above URL pattern (with my own custom style) got everything working as expected.
