### ISSUE TITLE
Holes in polygon

### ISSUE THREAD

**Issue by adnanefouam** [fleaflet/flutter_map#648]
polygon without holes, when i tested in geojson.io  my data works fine but here it seems not supported , any sug or idea how to fix this ? Thanks
<img width="1053" alt="Screen Shot 2020-06-08 at 06 14 10" src="https://user-images.githubusercontent.com/59290932/83994881-9e34ea80-a94f-11ea-9306-28d29b705355.png">

**Comment by maRci002** [comment]
#526 ?

**Comment by adnanefouam** [comment]
i'm sorry the problem is not in the flutter map package but in the  Geojson package , the problem located in this part  points: geoSerie.toLatLng(ignoreErrors: true), there is no code for holePointsList

**Comment by zjyhll** [comment]
maybe like this
![84db134597d0cddd0f29bc9aa614fc7](https://user-images.githubusercontent.com/8895877/163138220-9f6a14d9-563c-49d6-a61f-93122504a7c9.jpg)
