### ISSUE TITLE
Periodically clear the images from cache

### ISSUE THREAD

**Issue by Swepilot** [fleaflet/flutter_map#649]
I understand the purpose of using the `CachedNetworkTileProvider` is to have the tiles, well, cached. But what if I want to get fresh tiles from the server? After how long does the cache expire (if at all) and is it possible to expel the tiles manually?

My case is that I have a layer of weather data (not WMS) that I want to update periodically, but I don't want to use a non-caching provider.

I know the cached images are in the libCachedImageData directory but there is no way of telling which images belong to the layer in question. I rather not delete the whole cache. 

Is there a way of doing this already or what would the best practice be?

**Comment by MooNag** [comment]
#577 and #564 both relate to this. 564 has to do with customizing the caching behavior.
