### ISSUE TITLE
A lot of pull requests with fixes available

### ISSUE THREAD

**Issue by fryette** [fleaflet/flutter_map#652]
It would be nice to merge fixes and produce new version

**Comment by HugoHeneault** [comment]
Sure! It would be great. Maintaining a repo is also time-expensive. We should definitively support/sponsor @johnpryan for his work. 

@johnpryan What can we do to help?

**Comment by X-SLAYER** [comment]
agree! I hope he merged it soon

**Comment by estevez-dev** [comment]
Apparently that is how we can help: #680

**Comment by johnpryan** [comment]
0.10.0 is now available on Pub - please give it a try and file any new issues.

**Comment by JaffaKetchup** [comment]
Hello,
Can we reopen this, as there's now 23 open PRs and 191 issues?

Thanks
Luka S
