### ISSUE TITLE
Map quality is poor

### ISSUE THREAD

**Issue by A1Gard** [fleaflet/flutter_map#656]
I used flutter map and openstreet map, but the map **quality is to low.** I used other services, but the problem still not solved.

```
FlutterMap(
  mapController: _mapcontroller,
  options: MapOptions(
	onTap: (ps) {
	 // di some thing
	},
	center: LatLng(_pos.latitude, _pos.longitude),
	zoom: 15.0,
	maxZoom: 18,
  ),
  layers: [
	TileLayerOptions(
		tileProvider: NetworkTileProvider(),
//                    urlTemplate: 'http://tile.memomaps.de/tilegen/{z}/{x}/{y}.png',
		urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
//                    urlTemplate: 'https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}',
		subdomains: ['a', 'b', 'c']),
	MarkerLayerOptions(
	  markers: markers,
	)
  ],
),
```
![image](https://user-images.githubusercontent.com/9222481/84953961-beac3400-b109-11ea-9618-3a1d383b7c4b.png)
Look at result the **Curved lines**!!!
Any idea to improve map quality ?

**Comment by farzady** [comment]
I have same problem too, And I use the latest version.

**Comment by moovida** [comment]
Hi @A1Gard , @farzady , is it possible that this occurs because you are zooming between the zoomlevels for which the tiles are defined (think of the zoomlevel you push when you have buttons against when pinching with the fingers). I think the interpolation methods used for the intermediate levels are simple chosen for speed and not for proper antialiasing.

It would be nice to have control over that (if it is that), since also image layers suffer from lower quality than the original. Had no time to investigate yet, though.

**Comment by ibrierley** [comment]
It will certainly be sharper if only having a zoom level that's an integer, and I guess something you can control. The other thing that springs to mind is retina displays, maybe see https://github.com/johnpryan/flutter_map/pull/585

**Comment by mat8854** [comment]
Maybe someone can also try this modified version with [FilterQuality](https://api.flutter.dev/flutter/dart-ui/FilterQuality-class.html) set to `FilterQuality.high` in the `RawImage` in `tile_layer.dart`:

```
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: widget.tile.opacity,
      child: (widget.tile.loadError && widget.errorImage != null)
          ? Image(
              image: widget.errorImage,
              fit: BoxFit.fill,
            )
          : RawImage(
              image: widget.tile.imageInfo?.image,
              filterQuality: FilterQuality.high,
              fit: BoxFit.fill,
            ),
    );
  }
```

I can see no effect on my device (?).

**Comment by A1Gard** [comment]
@moovida Thanks bro. I'm sure, it depends on zoom between  the zoom levels, Cuz when the map rendered by 18.0 zoom, the problem exist .

@ibrierley the pull request blocked. :(
@ibrierley  and @mat8854 thanks for your kindness, there is no official solution? If not. How can I use library with your solutions without use the main package.

**Comment by ibrierley** [comment]
I think you can still link to a pull request in your pubspec.yaml if needed, but it's a while since I tried that, so I may be out of touch a bit.

**Comment by mat8854** [comment]
You can reference open PRs from your pubspec like said [here](https://github.com/johnpryan/flutter_map/issues/613#issuecomment-628472496)

Where `ref` is the id of the latest commit.

**Comment by szybki8562** [comment]
use 
retinaMode: true

**Comment by pinzon** [comment]
@szybki8562 where do you set that option? There is no mention of the retinaMode in the documentation.

**Comment by szybki8562** [comment]
`layers: [
        new TileLayerOptions(
            urlTemplate:
            'https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png',
            maxZoom: 22.0,
            subdomains: ['a', 'b', 'c'],
            tileProvider: CachedNetworkTileProvider(),
            retinaMode: true),
        MarkerLayerOptions(
          markers: widget.markers,
        ),
      ],`

flutter_map: ^0.10.1

**Comment by mat8854** [comment]
> use
> retinaMode: true

@szybki8562  I tried it today. It still looks worse than other map implementations (osmdroid for example).

**Comment by szybki8562** [comment]
mat8854 You can change tileLayer
[http://leaflet-extras.github.io/leaflet-providers/preview/index.html](url)

**Comment by mat8854** [comment]
@szybki8562 I think both `osmdroid` and `flutter_map` use Mapnik as default source.

![image](https://user-images.githubusercontent.com/2643309/87462675-97fdf200-c610-11ea-8718-dc09989d5d7a.png)

**Comment by szybki8562** [comment]
This is how it looks on my device
![image](https://user-images.githubusercontent.com/12680909/87463644-0abb9d00-c612-11ea-9be0-d9f38cb0ee9b.png)

**Comment by A1Gard** [comment]
I found the problem and fix it with `retinaMode`.

The code:
```

FlutterMap(
  mapController: _mapcontroller,
  options: MapOptions(
	onTap: (ps) {
	 // di some thing
	},
	center: LatLng(_pos.latitude, _pos.longitude),
	zoom: 17,
	maxZoom: 21,
  ),
  layers: [
	TileLayerOptions(
		tileProvider: NetworkTileProvider(),
                urlTemplate: 'http://mt{s}.google.com/vt/lyrs=m@221097413,parking,traffic,lyrs=m&x={x}&y={y}&z={z}',
                subdomains: ['0', '1', '2', '3'],
                retinaMode: true,
                maxZoom: 22,
),
	MarkerLayerOptions(
	  markers: markers,
	)
  ],
),
```
Note 1: opensteet support only until 19 zoom level, so google map is better for `retinaMode`
Note 2: we have to maxZoom we should use by this pattern to best result.

Thank for all helps, Spatially  @mat8854

**Comment by chester755** [comment]
Hi

> I found the problem and fix it with `retinaMode`.
> 
> The code:
> 
> ```
> 
> FlutterMap(
>   mapController: _mapcontroller,
>   options: MapOptions(
> 	onTap: (ps) {
> 	 // di some thing
> 	},
> 	center: LatLng(_pos.latitude, _pos.longitude),
> 	zoom: 17,
> 	maxZoom: 21,
>   ),
>   layers: [
> 	TileLayerOptions(
> 		tileProvider: NetworkTileProvider(),
>                 urlTemplate: 'http://mt{s}.google.com/vt/lyrs=m@221097413,parking,traffic,lyrs=m&x={x}&y={y}&z={z}',
>                 subdomains: ['0', '1', '2', '3'],
>                 retinaMode: true,
>                 maxZoom: 22,
> ),
> 	MarkerLayerOptions(
> 	  markers: markers,
> 	)
>   ],
> ),
> ```
> 
> Note 1: opensteet support only until 19 zoom level, so google map is better for `retinaMode`
> Note 2: we have to maxZoom we should use by this pattern to best result.
> 
> Thank for all helps, Spatially @mat8854

That is definitely a better map.
But, I have done some checks, and realise that the tile_map only support up to 18 zoom. I don't think setting to 22 actually do anything.
Maybe we should consider increasing the max zoom to allow more zoom for finer maps rather than cap it at 18?

**Comment by A1Gard** [comment]
@chester755 
It's working on zoom 22, I check it, don't worry :)
