### ISSUE TITLE
How to move marker

### ISSUE THREAD

**Issue by XieXiaoSa** [fleaflet/flutter_map#657]
I want to move marker in flutter_map to achieve my goal, but the current version does not seem to have such a function. Is there any other way?

**Comment by XieXiaoSa** [comment]
By the way, I'm trying to use my fingers to move marker, is there a way around that？

**Comment by ibrierley** [comment]
If trying to drag the marker you mean, maybe my plugin could be of help

https://github.com/ibrierley/flutter_map_dragmarker
