### ISSUE TITLE
Tiles not loading correctly with slow tiles provider and multiple zooms/pans

### ISSUE THREAD

**Issue by HugoHeneault** [fleaflet/flutter_map#659]
Hello 👋 

We love `flutter_map` 0.9.0 with the new zoom/pan behavior from #572. Well done @maRci002 !
But we have an issue when using a slow tiles provider. 

Using fast tiles provider works great. When it takes a few sec to fetch the tiles, things get weird. 
If a tile didn't finish loading and a zoom is triggered, the new one seems to be extremely slow to load, as if it awaits the first one to load before loading the latest zoom. Sometimes it even seems to never load at all.

Do you have any idea?

Thanks!

**Comment by louyanqi** [comment]
This will lead to a bad experience, can there be a parameter to control whether the old tiles needs to be displayed?

**Comment by maRci002** [comment]
https://github.com/johnpryan/flutter_map/issues/580#issuecomment-611639876

> then _abortLoading() should handle it and ask TileProvider to drop connections if a Tile is still in loading phase and when dispose is called, however there no way to ask CachedNetworkImageProvider / NetworkImage to abort downloading this may be the second issue to flutter team

**Comment by tuarrep** [comment]
Something interesting is coming around here https://github.com/dart-lang/sdk/issues/41904 abort aborting requests.

**Comment by tuarrep** [comment]
I've forked flutter_image package and made request cancelable :  https://github.com/OwnWeb/flutter_image.

I've tried to implement this by adding `tile.imageProvider.cancel('')` in `TileLayer` `_abortLoading` method (l 527) but it doesn't seems to fix the described issue. 
When intensively zooming (in / out) some tiles never fetches but other goes well.

Here is the snippet:

```dart
if (tile.imageProvider is NetworkImageWithRetry) {
  NetworkImageWithRetry imageProvider = tile.imageProvider;
  imageProvider.abort('');
}
```

As an example of "slow tiles provider" you can use `"https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"`

**Comment by tuarrep** [comment]
I've searched a lit bit more.

I feel the canceled tiles are not removed from the tiles list, so they aren't refreshed when zooming back to the level which requires them.

Perhaps #667 can help to discard canceled tiles.

Not tested anything yet.

**Comment by maRci002** [comment]
It's not about canceled tiles, onTileReady won't find the incoming tile in  _tiles because purne or update / abort removed it from _tiles map. It only preserves the old tiles (removes them if new ones ready from new zoom) if they are already loaded or if they are in loading phase they will removed from _tiles immediately.
I think this is leaflet's algorithm I can check behavior next week.
