### ISSUE TITLE
How to run method after map is mounted and ready

### ISSUE THREAD

**Issue by giohappy** [fleaflet/flutter_map#665]
I want to call MapController.fitToBounds(...) right after the map is mounted and visible.
I've digged into MapController and MapState, but I can only see the MapState.move stream getter as a way to be notified of map changes. On the other side I don't see if and how it's possible to set a custom onReady callback.
What's the best approach to get this?

**Comment by tprebs** [comment]
Assuming that you are creating your map controller within a StatefulWidget, you can set a custom callback onto the onReady future in `initState()`

```
@override
  void initState() {
    _mapController.onReady?.then((value) {
       ....do some work after map is ready
    });
    super.initState();
  }
```

**Comment by giohappy** [comment]
Yes, thx. I'm new to Flutter so I didn't notice onReady was a getter with a Future. 

BTW I'm doing this inside the build method of a stateless scaffold. Do you see problems with creating an instance of mapController (and seeting the onReady callback) inside the build method?

```
@override
  Widget build(BuildContext context) {
    MapController mapController = MapController();
    mapController.onReady.then((value) => print("loaded"));
   ....
```

My application builds mutliple maps (with different layers), so I'm not sure if creating a Stateful widget is the right approach here. In that case I asusme I would have to use a distinct key for each of them....
