### ISSUE TITLE
Clearing loaded _tiles in TileLayer.

### ISSUE THREAD

**Issue by tprebs** [fleaflet/flutter_map#666]
While writing a heat map plugin for flutter_map, I came across the need to reset the tiles held in memory within TileLayerState (`_tiles`). When the data for the heat map changes, the heat map tiles should be rebuilt. currently this only happens zooming in/out or moving outside of the `keepBuffer` limit.

This also applies to working with WMS servers with server side filtering. When the filter changes, the tiles are the same. 

I initially looked into using the rebuild stream to manually trigger the rebuild but this doesn't support unloading the current _tiles.

**Comment by moovida** [comment]
Hi @tprebs , some time ago I also started a heat map plugin, but using a CustomPainter instead of a tiled layer approach, so that it would properly repaint on data change. 

On a sidenote I was blocked by the impossibility to get the current pixel value from the canvas and had to put the work aside due to other job issues. I was porting leaflet's heatmap plugin. May I ask what approach you chose?

**Comment by tprebs** [comment]
I have done something similar regarding the CustomPainter. I have created an untiled version which doesn't work as well with larger (5000 + points) as there is no easy way to distinguish between an on map move start and on map move finish event which means it redraws and recalculates the heatmap data at a very high frequency. The tiled approach works much better for larger datasets as the individual tiles are cached (both in TileLayer and in a custom TileProvider). 

I faced a similar issue with the attempting to get the current pixel value. I went down a similar route to the leaftlet heatmap plugin.

1. Create a canvas 1 pixel by 256 and apply the colour gradient to a rectangle 1x256. Capture the image with picture recorder and cache it (this is how I got the pixel values). This ByteData becomes the colour palette to apply colour to the grayscale heatmap image
2. Create a canvas to create a template image used to replace each LatLng (similar approach to above)
3. Generate the heatmap layer/tile by applying the template image at each point
4. process the heatmap layer pixel by pixel replacing the 255 grayscale value with the value on the colour ramp.

Steps 1 and 2 can be done on initialisation, only requiring step 3 and 4 to be run for each layer rebuild.

**Comment by moovida** [comment]
@tprebs , any chance that code goes public or is it a private project? I would be happy to contribute or test. 
The issue that blocked me was that picture recorder only works async and I couldn't plug it into my rendering cycle :-)
But I will have to go back on that eventually.

**Comment by mpierog** [comment]
This used to work properly, but now the cache looks like it not clearing. I just want to let the user switch back and forth between map types. It used to redraw right away, but now the user has to pan or zoom to get things going.

**Comment by tprebs** [comment]
@moovida 
This will go into a public repo once I have a bit more time to make it more generic. I will be happy collaborate with you on this. 
I moved the heatmap generation outside of the render cycle to get around this. I have a heatmap generator which asynchronously generates bitmap images. once the image is rendered the imagedata can be painted on the canvas synchronously

**Comment by moovida** [comment]
@tprebs , clearly you did. Actually that is the perfect way to go, not sure why I didn't think of it :-D 
Well, I have time to work on this later, I am leaving for 2 weeks. After that I can happily contribute with documentation you were to bored to write and review the code (I took the exact same approach on the heatmap side). 
Ping me when you want me to dig in. Or I ping you if I come prior to the point in which I would like to have it implemented. Thanks!
