### ISSUE TITLE
How to get Lat/Lon value from screen position

### ISSUE THREAD

**Issue by nimazareian** [fleaflet/flutter_map#672]
I want the user of my app to be able to select a location by dragging their map to the desired area. How can this be done? Similar to the **Pick address** function of the flutter_map_picker package:
https://pub.dev/packages/flutter_map_picker#-readme-tab-

Or how can I get the latitude/longitude of the middle of my screen?

**Comment by HugoHeneault** [comment]
This might interest you: https://github.com/fleaflet/flutter_map/pull/505
