### ISSUE TITLE
How to move the map center

### ISSUE THREAD

**Issue by spinachomes** [fleaflet/flutter_map#673]
setState(() {
     _location = LatLng(info.lat, info.lng); // the center
     print("location:$_location}");
});
I changed the center like upon,but map not move the new center.

**Comment by maRci002** [comment]
[map_controller.dart](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/map_controller.dart)

[animated_map_controller.dart](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart)

**Comment by spinachomes** [comment]
> [map_controller.dart](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/map_controller.dart)
> 
> [animated_map_controller.dart](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart)

thanks,but i get other problem. mapController.move several times in a row,the map is stack then app quit.
