### ISSUE TITLE
onpositionchanged called multiple times

### ISSUE THREAD

**Issue by uchihasharukh** [fleaflet/flutter_map#674]
Hi. Good day to you all!
The onPositionChanged option works but it gets called every time the map changes. But I want to get the position where I lift my finger (stop touching screen). Then I want to call an API to get list of markers near that location. 
So the problem with onPositionChanged is that it gets called a lot of times and I can not call the API that many times! So it would be great if I was able to call it when the user stops touching screen, like the onTapUp option in gestureDetector.
Is there any way to implement this?

_Originally posted by @arashAndroid in https://github.com/johnpryan/flutter_map/issues/554#issuecomment-644674483_

**Comment by mat8854** [comment]
@uchihasharukh @arashAndroid

Right now this is not supported if you look at the `MapOptions` class.

```dart
  MapOptions({
   ...
    this.onTap,
    this.onLongPress,
    this.onPositionChanged,
 ...
  })
```

There is a [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) in the widget tree and it has all the callbacks. They are just not implemented.
```dart
GestureDetector(
            onScaleStart: handleScaleStart,
            onScaleUpdate: handleScaleUpdate,
            onScaleEnd: handleScaleEnd,
            onTap: _positionedTapController.onTap,
            onLongPress: _positionedTapController.onLongPress,
            onTapDown: _positionedTapController.onTapDown,
            onTapUp: handleOnTapUp,
            child: layerStack,
...
```

Other Android map libraries I worked with had the option to register to a classic Android [View.OnTouchListener](https://developer.android.com/reference/android/view/View.OnTouchListener) / `MapListener`. The user could filter out the wanted `MotionsEvents` from all events.

Related to that:
I was also wondering how often these position updates are sent under Flutter (?).

In osmdroid for instance they introduced a [DelayMapListener](https://github.com/osmdroid/osmdroid/blob/19053d1435e8fa4e58b04960b23b0769e99adb66/osmdroid-android/src/main/java/org/osmdroid/events/DelayedMapListener.java) to improve performance.
```
* A MapListener that aggregates multiple events called in quick succession.
 * After an event arrives, if another event arrives within <code>delay</code> milliseconds,
 * the original event is discarded.  Otherwise, the event is propagated to the wrapped
 * MapListener.  Note: This class is not thread-safe.
```

**Comment by uchihasharukh** [comment]
https://stackoverflow.com/tags/gesturedetector/hot?filter=all

Maybe you can try hittestbehaviour from gesture detector

**Comment by uchihasharukh** [comment]
Also if i initiate geolocator plugin for current location.. the hasgesture sets to false

**Comment by mat8854** [comment]
> https://stackoverflow.com/tags/gesturedetector/hot?filter=all
> 
> Maybe you can try hittestbehaviour from gesture detector
@uchihasharukh 
I thought just passing the **DragCallbacks** for **Start/End/Cancel** and up to the user:
```
GestureDragStartCallback onPanStart
GestureDragEndCallback onPanEnd
GestureDragCancelCallback onPanCancel
```

**Comment by uchihasharukh** [comment]
Is there a autocomplete search option in this plugin? If no, is there any alternative that u know?
