### ISSUE TITLE
Add flyTo method

### ISSUE THREAD

**Issue by komape** [fleaflet/flutter_map#675]
Leaflet has a [`flyTo`](https://leafletjs.com/reference-1.6.0.html#map-flyto) method. Flutter Map has currently only the `move` method. `flyTo` offers a smooth animation to the given location (as the method name says). Would be really nice to have this feature.

**Comment by HugoHeneault** [comment]
@komape You can check the [animated_map_controller](https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart) example :)

**Comment by b3nni97** [comment]
However, the FlyTo method animates completely differently than in the AnimatedMapController example. Is it not possible to implement the FlyTo method?

**Comment by QTree-app** [comment]
reopen?

**Comment by JaffaKetchup** [comment]
See #1263.
