### ISSUE TITLE
Gray band with load OpenStreetMap

### ISSUE THREAD

**Issue by jamontes79** [fleaflet/flutter_map#676]
When I load a map using OpenStreetMap I have a gray band always in the same position until I make zoom in or zoom out.

I'm using the version 0.9.0.

I attach a screenshot, any suggestion?

![Simulator Screen Shot - iPhone 8 - 2020-07-06 at 14 50 32](https://user-images.githubusercontent.com/11333270/86595019-604fd400-bf98-11ea-89db-f5e2e484e0bf.png)

Thanks
Regards

**Comment by ibrierley** [comment]
Do you get any tile load errors in the console or anything ?

**Comment by jamontes79** [comment]
No, I don't have anything in the console, neither in Android neither in iOS.

**Comment by gmhz** [comment]
Download plugin and place it locally, add local dependency in pubspec.yaml file like this:
  flutter_map:
    path: ./plugins/flutter_map-0.9.0

edit file ./plugins/flutter_map-0.9.0/lib/src/layer/tile_layer.dart


change method _handleMove
from :
`  void _handleMove() {
    var tileZoom = _clampZoom(map.zoom.roundToDouble());

    if (_tileZoom == null) {
      // if there is no _tileZoom available it means we are out within zoom level
      // we will restory fully via _setView call if we are back on trail
      if ((options.maxZoom != null && tileZoom <= options.maxZoom) &&
          (options.minZoom != null && tileZoom >= options.minZoom)) {
        _tileZoom = tileZoom;
        setState(() {
          _setView(map.center, tileZoom);
        });
      }
    } else {
      setState(() {
        if ((tileZoom - _tileZoom).abs() >= 1) {
          // It was a zoom lvl change
          _setView(map.center, tileZoom);
        } else {
          if (null == _throttleUpdate) {
            _update(null);
          } else {
            _throttleUpdate.add(null);
          }

          _setZoomTransforms(map.center, map.zoom);
        }
      });
    }
  }
`
to :
`  void _handleMove() {
    var tileZoom = _clampZoom(map.zoom.roundToDouble());

    if (_tileZoom == null) {
      // if there is no _tileZoom available it means we are out within zoom level
      // we will restory fully via _setView call if we are back on trail
      if ((options.maxZoom != null && tileZoom <= options.maxZoom) &&
          (options.minZoom != null && tileZoom >= options.minZoom)) {
        _tileZoom = tileZoom;
        _setView(map.center, tileZoom);
      }
    } else {
      if ((tileZoom - _tileZoom).abs() >= 1) {
        // It was a zoom lvl change
        _setView(map.center, tileZoom);
      } else {
        if (null == _throttleUpdate) {
          _update(null);
        } else {
          _throttleUpdate.add(null);
        }

        _setZoomTransforms(map.center, map.zoom);
      }
    }
    setState(() {});
  }
`

It helped me fixing the gray areas on the map.

**Comment by gmhz** [comment]
> Download plugin and place it locally, add local dependency in pubspec.yaml file like this:
> flutter_map:
> path: ./plugins/flutter_map-0.9.0
> 
> edit file ./plugins/flutter_map-0.9.0/lib/src/layer/tile_layer.dart
> 
> change method _handleMove
> from :
> 
> ```
> void _handleMove() {
>     var tileZoom = _clampZoom(map.zoom.roundToDouble());
> 
>     if (_tileZoom == null) {
>       // if there is no _tileZoom available it means we are out within zoom level
>       // we will restory fully via _setView call if we are back on trail
>       if ((options.maxZoom != null && tileZoom <= options.maxZoom) &&
>           (options.minZoom != null && tileZoom >= options.minZoom)) {
>         _tileZoom = tileZoom;
>         setState(() {
>           _setView(map.center, tileZoom);
>         });
>       }
>     } else {
>       setState(() {
>         if ((tileZoom - _tileZoom).abs() >= 1) {
>           // It was a zoom lvl change
>           _setView(map.center, tileZoom);
>         } else {
>           if (null == _throttleUpdate) {
>             _update(null);
>           } else {
>             _throttleUpdate.add(null);
>           }
> 
>           _setZoomTransforms(map.center, map.zoom);
>         }
>       });
>     }
>   }
> ```
> 
> to :
> 
> ```
> void _handleMove() {
>     var tileZoom = _clampZoom(map.zoom.roundToDouble());
> 
>     if (_tileZoom == null) {
>       // if there is no _tileZoom available it means we are out within zoom level
>       // we will restory fully via _setView call if we are back on trail
>       if ((options.maxZoom != null && tileZoom <= options.maxZoom) &&
>           (options.minZoom != null && tileZoom >= options.minZoom)) {
>         _tileZoom = tileZoom;
>         _setView(map.center, tileZoom);
>       }
>     } else {
>       if ((tileZoom - _tileZoom).abs() >= 1) {
>         // It was a zoom lvl change
>         _setView(map.center, tileZoom);
>       } else {
>         if (null == _throttleUpdate) {
>           _update(null);
>         } else {
>           _throttleUpdate.add(null);
>         }
> 
>         _setZoomTransforms(map.center, map.zoom);
>       }
>     }
>     setState(() {});
>   }
> ```
> 
> It helped me fixing the gray areas on the map.

Actually it looked like it helped at first me but it didn't.



The real solution for me for this issue changing tile url:

TileLayerOptions(
              urlTemplate:
                  "https://tile{s}.maps.2gis.com/tiles?z={z}&x={x}&y={y}&v=1.3&r=g&ts=online_hd&itr=${Helper.mapIteration()}",
              subdomains: ['0', '1', '2', '3', '4'],
              tileProvider: CachedNetworkTileProvider(),
)

class Helper {
  static int iteration = 0;

  static int mapIteration() {
    return iteration;
  }

  static int increaseMapIteration() {
    return iteration++;
  }
}

you just increase map iteration in case you change screen orientation or width-height of the map widget or map containing widgets.
