### ISSUE TITLE
Call for maintainers!

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#680]
First off, I'm very grateful for the amazing contributions from everyone. This is currently a side-project for me, and I'm not able to give it enough time and attention to meet everyone's needs. I'll continue to help maintain this project, but would like some help with handling all the incoming issues and pull requests.

As a maintainer, you would be responsible for triaging issues, reviewing PRs, updating the changelog, and publishing new versions.

To be considered, please fill out this form: https://docs.google.com/forms/d/e/1FAIpQLSe9oe7pYO293NNY2Po6YIFaF-lbmmfXk2UjernGn5LKryQJDw/viewform?usp=sf_link

Thanks everyone!

**Comment by JakeAlmer** [comment]
Fyi Looks like your form isn't public

**Comment by johnpryan** [comment]
Fixed, thanks.

**Comment by nickoe** [comment]
Hello @johnpryan, any update on finding a couple of new maintainers?

**Comment by johnpryan** [comment]
Yes, the responses need to be looked at. Also need to figure out what criteria to use.

**Comment by arsamme** [comment]
Hi @johnpryan, Any updates on this?

**Comment by johnpryan** [comment]
Thanks for the submissions everyone - we have two contributors who are maintainers now. I'll keep reviewing submissions and add more as we need.
