### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt with use padding

### ISSUE THREAD

**Issue by juanlabrador** [fleaflet/flutter_map#687]
Hi, this error happen when use padding in FitBoundsOptions with different values in top, bottom, left and right, I try ways to fix but I couldn't, thanks.

**Comment by Miksier** [comment]
@juanlabrador 
I'd be best if you provided more data for a bug report. 
Like version of plugin or, i'd be best, a sample project. I tried to reproduce it but "for me it works", so a sample would be great

**Comment by umutonat** [comment]
/lib/src/map/flutter_map_state.dart
```
line 96  else {
line 97        mapState.size =
line 98            CustomPoint<double>(constraints.maxWidth, constraints.maxHeight);
line 99      }
```
@Miksier this else runs and maxHeight is infinity, that causes problems :)

**Comment by NoamDev** [comment]
@Miksier why was that issue closed?
It's still relevant on latest version (0.13.1)
