### ISSUE TITLE
How to show multi tile layer? 

### ISSUE THREAD

**Issue by NeonX** [fleaflet/flutter_map#689]
I would like to show  more than one layer.
base layer is template map like openstreetmap.org and overlay with wms layer.
But when I place two TileLayerOptions, it will display only the last layer.

Thanks

![2020-07-16_13-33-07](https://user-images.githubusercontent.com/1585675/87635286-fc33c980-c768-11ea-9f58-c9620533712e.jpg)
![109406873_719759218864646_2348667360521473003_n](https://user-images.githubusercontent.com/1585675/87635381-25545a00-c769-11ea-8cde-7b29e18312a4.jpg)

**Comment by Rashesh-Bosamiya** [comment]
I am facing same issue as yours.

If you find any solutions please post it here.

Thank you.

**Comment by Rashesh-Bosamiya** [comment]
I am also facing one issue when I zoom in the map, at certain level map disappears. And when I again zoom out map appears again.

Are you facing the same issue while zooming?

**Comment by Rashesh-Bosamiya** [comment]
please set `transparent: true` & `backgroundColor: Colors.transparent` in TileLayerOptions

This may work for you.

**Comment by NeonX** [comment]
@Rashesh-Bosamiya  Wow It's work for me!  Thank you very much. 

and I am also facing zooming problem, too.
If you find any solutions please help me. ^_^

**Comment by Rashesh-Bosamiya** [comment]
Please try to set `maxZoom` property of `MapOptions`.

If this doesn't work, then you have create custom `CRS` for your map.

You can find more information about CRS from blow reference URL.

https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/custom_crs/custom_crs.dart

**Comment by jiazeh** [comment]
I have same issue on new version 0.10.x
But, in old version. It work! please help, thanks a lot !!
