### ISSUE TITLE
"Failed host lookup: 'a.tile.openstreetmap.org'" when run in --release

### ISSUE THREAD

**Issue by TheLastGimbus** [fleaflet/flutter_map#690]
When I use this lib with OpenStreetMap normally, in debug, it works fine.
When i use it in release mode, suddently I can't reach OSM address:
`I/flutter ( 3092): SocketException: Failed host lookup: 'c.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)`

**Comment by joaotomaspinheiro** [comment]
It does the same for me. When I run in debug mode, it works perfectly. But in release mode, the map appears blank, with than same exception.

**Comment by ibrierley** [comment]
You need to check your androidmanifest XML file in the release folder. You
will prob find you don't have internet enabled there. Compare it to the
debug folder. (Sorry on mobile so can't dig out exact text to add in)

**Comment by TheLastGimbus** [comment]
Thanks, this worked :ok_hand: 
Shouldn't this be already declared by the package itself? (Or not, if someone wants to use only offline version and not have internet permission)
?
