### ISSUE TITLE
transform polygons and polylines to custompaint

### ISSUE THREAD

**Issue by X-SLAYER** [fleaflet/flutter_map#693]
is there any way to transform a polygon to a path or custom paint and draw it inside any widget 
something like that 

 ![image](https://i.imgur.com/dYfh0DU.png)

**Comment by ibrierley** [comment]
Just pondering, what's the use case ? It should be possible, but often the devil is in the detail.

**Comment by X-SLAYER** [comment]
just let's say that I want to show all my polygons in another listview or something like that, I want to show each polygon in a custom widget lets say something like this 
![image](https://static.dribbble.com/users/128446/screenshots/3322987/object.png)

**Comment by ibrierley** [comment]
Assuming you have the original poly that you passed to flutter_map, could you project the latlongs with options.crs.latLngToPoint(latlng, zoom); (may need to dig out the code in map.dart) divide by 2^zoom and then adjust with the min/max bounds of that, to fit in whatever canvas you are creating ?
Just thinking off the top of my head how I would look to approach it.

**Comment by X-SLAYER** [comment]
i already tried this one but its showing blank i used this method
[#385 ](https://github.com/fleaflet/flutter_map/issues/385#issuecomment-526301828)

**Comment by ibrierley** [comment]
ok, so start with a test list of Offsets, can you show the code you are trying to get it displayed, that may give some clues?

**Comment by X-SLAYER** [comment]
sorry, I already deleted my code for that but it's based on the same method u had told me
