### ISSUE TITLE
Not loading .Mbtiles file in tileProvider

### ISSUE THREAD

**Issue by blackvitriol** [fleaflet/flutter_map#694]
Hey, I got my own .mbtiles file and I am trying to use it, but I get no errors and the map doesn't show up.

I used:
`tileProvider: FileTileProvider("mymap.mbtiles"),`

**Comment by kesaribharat** [comment]
did you figure out how could be done. because we are having the same issue.

**Comment by Swepilot** [comment]
Use `MBTilesImageProvider.fromFile("yourMBTilesfile")`

if the file is part of your assets, use `.fromAsset`
