### ISSUE TITLE
Complete documentation about implementation

### ISSUE THREAD

**Issue by mabesi** [fleaflet/flutter_map#696]
Is there a complete documentation about flutter_map and its functionalities, like markers, lines, routes, zoom, wich explain in details how to implement each one?

**Comment by ibrierley** [comment]
I think for the moment, I would look in the test directory for examples on most common functionalities.

**Comment by 4F2E4A2E** [comment]
E.g.: what does the Boolean flag 'slideOnBoundaries' [1] practically mean?


1: https://github.com/fleaflet/flutter_map/blob/85558c9194f0f0b7b1f7b20e6d487d8fdfe523fb/example/lib/pages/sliding_map.dart#L33
