### ISSUE TITLE
How could we bake/support you?

### ISSUE THREAD

**Issue by HugoHeneault** [fleaflet/flutter_map#699]
Hi there!

As `flutter_map` is providing high value to our apps, we would like to support your work. 
Is it possible to enable a funding system on your package? Like on https://opencollective.com/ ?

Thanks a lot for all your work 🙏

**Comment by 4F2E4A2E** [comment]
I can only agree with @HugoHeneault. I have done many "Map-Solutions" in the last 10 years and this is one of the very few projects which works. We are very thankful for that.
