### ISSUE TITLE
onMoveStart onMoveEnd

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#701]
Is there any listener, when moving started and ended?

**Comment by sm2017** [comment]
@johnpryan @maRci002 I want to create an animation effect on markers when users start/end moving map , So I need `onMoveStart` and `onMoveEnd` callback

**Comment by maRci002** [comment]
Okay, I'll see what I can do.

**Comment by mat8854** [comment]
@sm2017 @maRci002
I think most users need the start and end events from manual dragging. We had this topic also in #674.

**Comment by maRci002** [comment]
@mat8854 
Yes it's a good start point.

**Comment by maRci002** [comment]
Can you try PR #719 ?

> There are a lot of issues which ask for `onMoveStart` / `onMoveEnd callbacks`, just listen to `mapEventStream` and filter these events (`MapEventMoveStart` / `MapEventMoveEnd`), however take care because `Map may use fling animation` if the velocity is high enough so the final location will be different from `MapEventMoveEnd`'s targetLocation, so there are two options:
>  - disable fling animation
>  - filter `MapEventFlingEnd` and `MapEventFlingNotStarted`
