### ISSUE TITLE
Extra data in markers

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#703]
I am using `flutter_map_marker_cluster` 

In cluster widget , https://github.com/lpongetti/flutter_map_marker_cluster/blob/master/example/lib/main.dart#L157
We only can show length of markers , No additional data in available

I want to reduce list and show sum of a property

`Marker` has no option for this https://github.com/fleaflet/flutter_map/blob/master/lib/src/layer/marker_layer.dart#L75-L79
It is good to have an `id` field or a `dynamic extra` field

**Comment by 4F2E4A2E** [comment]
@sm2017 how did you solve this? By using the plugin flutter_map_marker_cluster ?

**Comment by sm2017** [comment]
Yes, simply extends Marker class

**Comment by aytunch** [comment]
I got rid of the field warnings by this. Now only `LatLng` warning exist. If anyone know how to get rid of it, please tell
```
import 'package:flutter/material.dart';

import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class EventMarker extends Marker {
  final int eventsCount;

  EventMarker({
    Key? key,
    required LatLng point,
    required WidgetBuilder builder,
    double width = 30.0,
    double height = 30.0,
    bool? rotate,
    Offset? rotateOrigin,
    AlignmentGeometry? rotateAlignment,
    AnchorPos? anchorPos,
    required this.eventsCount,
  }) : super(
          key: key,
          point: point,
          builder: builder,
          width: width,
          height: height,
          anchorPos: anchorPos,
          rotate: rotate,
          rotateOrigin: rotateOrigin,
          rotateAlignment: rotateAlignment,
        );
}
```

**Comment by ibrierley** [comment]
I don't know the Cluster Plugin, but do you really need to do all of that ? Eg can't you use the Marker builder, could you do...

```
Text textBuilder(val) {
    return Text("${val + DateTime.now().second}");
}
```
and in build...

```
var r = Random();
    for (var x = 0; x < maxMarkersCount; x++) {
      allMarkers.add(
        Marker(
          point: LatLng(
            doubleInRange(r, 37, 55),
            doubleInRange(r, -9, 30),
          ),
          builder: (context) => textBuilder(x),
        ),
      );
    }
```

**Comment by aytunch** [comment]
If you want to pass extra info in to `builder(context, markers)` then the only way is to extend `Marker` class and do casting.
With the above Marker class, I implement my cluster builder as follows;
```
                    MarkerClusterLayerOptions(
                      builder: (context, markers) {
                        if (markers.isEmpty) {
                          return const SizedBox.shrink();
                        }
                        List<EventMarker> eventMarkers =
                            markers.map((e) => e as EventMarker).toList();
                        return EventsClusterWidget(
                          markers: eventMarkers,
                          zoom: widget.mapController.zoom,
                        );
                      },
```

**Comment by ibrierley** [comment]
Ah I see, for the Cluster to have access to. Makes sense, apologies!
