### ISSUE TITLE
WFS support?

### ISSUE THREAD

**Issue by rktvsiim** [fleaflet/flutter_map#706]
I was very glad to discover that flutter_map added WMS support since 0.9.0 (already using it!)

Are there any plans to implement support for WFS as well?

**Comment by 4F2E4A2E** [comment]
What is WMS and WFS?

**Comment by rktvsiim** [comment]
@4F2E4A2E 
> What is WMS and WFS?

https://www.ogc.org/standards/wfs

An oversimplified **generalization**:
1) **WMS** map services (the ones that I usually work with) mostly return PNG (or jpeg) raster tiles. The flutter_map's WMSTileLayerOptions has quite nice support for that.
2) **WFS** services usually return a bunch of JSON (usually FeatureCollections containing all sorts of information (geometry, properties) about polygons/lines etc... which can then be plotted onto the map.

WMS/WFS queries are quite similar in terms of passed in parameters.

For leaflet there are a few plugins which behave a bit differently:
- https://github.com/Flexberry/Leaflet-WFST
- https://github.com/azgs/azgs-leaflet

**Comment by 4F2E4A2E** [comment]
Thank you for your kind explanation. Do I understand it correctly that **WFS** would be superior in terms of efficiency on display and data transport?

**Comment by rktvsiim** [comment]
@4F2E4A2E - WMS and WFS are just different ways to show information on the map. I wouldn't say WFS is superior to WMS but it allows a bit more different control and is better suited to show various **vector** elements on the map (especially when they need to be interactive or manipulated- clicked/tapped/style changes/etc...). 

**WMS sample query:** 
`map?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=my_wms_layer_name&STYLES=default&some_extra_param=123&CRS=my_projection&WIDTH=X&HEIGHT=Y&BBOX=x,y,x,y`
And this basically returns a large PNG file (heatmaps, baselayers). Depending on your client-app WMS can be a good thing - you might run into real performance issues (but it is a rare case with high volumes) when rendering a huge amount of vector features onto the map via WFS (the exact amount depends on the viewport, device, library being used (openlayers/leaflet etc..), how you are rendering the element, how you are styling the element while rendering. But there are things you cannot do by just using a WMS service.

**WFS sample query**
`&SERVICE=WFS&SRS=projection&FORMAT=image/png&LAYERS=my_wfs_layer&TRANSPARENT=TRUE&VERSION=1.0.0&REQUEST=getfeature&STYLES=&TYPENAME=my_type_name&MAXFEATURES=10&outputFormat=geojson&BBOX=x,y,x,y` 
The query itself is quite similar but instead of a PNG you would get JSON something like this:
```
crs: {...some props...}
features: [
   {
       geometry: {type: 'Polygon', coordinates: [...] }
       properties: {id: 123, name: 'My park', address: 'Some street 26', city: 'Dolor', number_of_trees_in_park: 321, dogs_allowed: false}
   }
   ...
]
type: "FeatureCollection"
```
The trick here with a WFS now is that depending on the library/plugin being used you can immediately style or plot the vector elements (polygons, lines etc...) onto the map and interact with them (highlight the vector shape, style it, animate it, add listeners).
Depending on the WFS service you usually also pass several custom properties which then can be read by the client-app.

In the _dummy_ example above: the WMS layer might show a raster layer with park boundaries (marked with a different color so that they can be easily distinguished at various zoom levels. The WFS layer is used to draw a vector polygon when a user clicks on a park (and now we can use the custom properties from the WFS service response to show a modal/popup or do all kinds of magic with the vector element).

---

Again an oversimplified generalization:
- You usually use WMS for static baselayers, heatmaps, cadastral units, object borders etc...
- You usually (but it is definitely not a rule) accompany the WMS layer with a WFS layer to have more interactivity and data.

UX wise: WMS usually works better in low zoom levels (country/county/city view), WFS works better with higher zoom levels (a certain smaller area).

Technically most WFS plugins construct the necessary query (like the current wmsTileOptions does), sets a bounding box and has some sort of  support or documentation on how to easily plot and style the received geoJSON as vector elements onto the map. And of-course usually it makes sure that everything unnecessary outside the viewport gets destroyed.

**Comment by 4F2E4A2E** [comment]
Thank you so much for taking your time for explaining it. I love it and understand it much better now.

**Comment by mblataric** [comment]
Another example for WFS is situation where you want to display names over map. 
If I use WMS, I am stuck with colors defined on geoserver which rarely works well and there is nothing you can do about it. 
With WFS, I can get vector information and provide information how to draw it on the map layer.

**Comment by barbalex** [comment]
Being able to add WFS is a fairly basic feature. I'd love to see it implemented.

**Comment by ibrierley** [comment]
If it's a fairly basic feature, I'm guessing it should be easy to create a pull request for it ;). Don't underestimate your own abilities, others would help if they can. 

I'm saying the first bit slightly tongue in cheek, as often these are more complex than we think. But, if you can break it down into steps...i.e
1) here is a wfs server working to look at and query...
2) here are the requests we would want it to be able to handle
3) this is what the data looks like every time, and a spec (maybe a bit of test data the server sends)
4) this is what we would want to be able to do with it....

And then break it down from there further if necessary. It sounds quite interesting, but I don't think someone will just pick it up because there is a git issue open for it, but it may overlap with some other projects people are playing with including myself.

**Comment by barbalex** [comment]
@ibrierley  With _basic_ I meant a basic need rather than it being simple to implement. But thanks for the great input.

**Comment by haikun-li** [comment]
https://github.com/haikun-li/flutter_map_wfs

**Comment by FireAndIceFrog** [comment]
Was there any progress on this?
