### ISSUE TITLE
Tiles not appearing when using FlutterMap on multiple screens

### ISSUE THREAD

**Issue by maro242** [fleaflet/flutter_map#707]
Steps to reproduce:

1. Create two screens with FlutterMap (both maps should have identical center and zoom). Alternatively, you can run [this](https://bitbucket.org/maro24/tile_bug_example/src/master/) example.
2. Navigate from the first screen to the other.
3. Tiles displayed on the first screen never appear on the second one.
4. Panning in any direction will show tiles but the original area will remain unloaded.

This used to work on 0.8.2 but does not work since the changes to tile management on 0.9.0.

Removing the indicated line (965) from the _tileReady method in tile_layer.dart solves the issue. 

    var key = _tileCoordsToKey(coords);
    tile = _tiles[key]; //Removing this solves the issue
    if (null == tile) {
      return;
    }

I do not understand the package enough to know what purpose does keeping tiles in the _tiles hash map serve but so far I have not noticed any issues since deleting it so am quite curious about this.

**Comment by maRci002** [comment]
```dart
var key = _tileCoordsToKey(coords);
tile = _tiles[key];
if (null == tile) {
  return;
}
```

Makes sure the `loaded tile` is still in `_tiles` `HashMap` which is maintained mainly by `void _update(LatLng center) {` and `void _pruneTiles() {` and `void _abortLoading() {` methods. Imagine a situation where you start loading 4 tiles forexample the center of a country, then you move the map to the country's boundary then the center tiles finished with loading so we are no more intersted of center tiles anymore. Anyway in #572 I implemented this behaviour [from Leafet](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L854-L855).

You are right about the problem so I'll investigate it.

**Comment by maRci002** [comment]
Try PR #715 it should fix your issue.
