### ISSUE TITLE
Is there an option to pick the location? If so can it geo code the lat and long?

### ISSUE THREAD

**Issue by arjungprs** [fleaflet/flutter_map#710]
Is there an option to pick the location? If so can it geo code the lat and long?

**Comment by ibrierley** [comment]
Not quite sure of your question. What do you mean by 'pick the location' ? You can tie flutter_map in with a geolocation package, and use a map controller to move the map. There are also packages for geocoding, but I'm not quite sure that's what you are specifically asking.

Maybe if you can explain with the use case a bit more, it could be easier to answer a bit more specifically.

**Comment by arjungprs** [comment]
Hi @ibrierley , 
Lets say user wants to select a place on the map, Instead adding markers. There will be a marker already (initially gps location) and user moves the map to select the desired location. There is a google map plugin in pub. I am trying to explain the same plugin. There is a gif animation that they have give in this link : https://pub.dev/packages/google_map_location_picker

**Comment by ibrierley** [comment]
Ah in that case, no there isn't. but sounds like it could be a good plugin for someone to add ;).
