### ISSUE TITLE
TileLayerOptions repeat the image

### ISSUE THREAD

**Issue by Pinkal7600** [fleaflet/flutter_map#712]
I have set one image URL in '**urlTemplate**' inside '**TileLayerOptions**'. Once we run the app. It repeats the image multiple times even if we zoom in or zoom out it keeps repeating the image. 

Question: How we can stop to repeat images and show only one image which we have provided?

<img src="https://user-images.githubusercontent.com/22210038/89272878-68189c00-d65c-11ea-86b1-535ed4024af9.png" height="700" />

**Comment by maRci002** [comment]
You can use overlayimage layer

**Comment by Pinkal7600** [comment]
@maRci002 Thank you.

Can you help me with this issue: https://github.com/fleaflet/flutter_map/issues/725
