### ISSUE TITLE
How can I solve this issue?

### ISSUE THREAD

**Issue by fluttercid** [fleaflet/flutter_map#718]
Hello all,

I followed the sample 'live_location.dart'.

However, when I open a screen, this message continually came up in debug console.

Did I miss something?

Thank you for your help in advance.

Console log =========================================================
D/skia    (26036): Shader compilation error
D/skia    (26036): ------------------------
D/skia    (26036):    1	#version 300 es
D/skia    (26036):    2
D/skia    (26036):    3	#extension GL_EXT_shader_framebuffer_fetch : require
D/skia    (26036):    4	precision mediump float;
D/skia    (26036):    5	precision mediump sampler2D;
D/skia    (26036):    6	inout mediump vec4 sk_FragColor;
D/skia    (26036):    7	uniform mediump vec4 uleftBorderColor_Stage1_c0_c0;
D/skia    (26036):    8	uniform mediump vec4 urightBorderColor_Stage1_c0_c0;
D/skia    (26036):    9	uniform sampler2D uTextureSampler_0_Stage1;
D/skia    (26036):   10	in mediump vec4 vQuadEdge_Stage0;
D/skia    (26036):   11	in mediump vec4 vinColor_Stage0;
D/skia    (26036):   12	in highp vec2 vTransformedCoords_0_Stage0;
D/skia    (26036):   13	mediump vec4 stage_Stage1_c0_c0_c0_c0(mediump vec4 _input) {
D/skia    (26036):   14	    mediump vec4 _output;
D/skia    (26036):   15	    mediump float t = vTransformedCoords_0_Stage0.x + 9.9999997473787516e-06;
D/skia    (26036):   16	    _output = vec4(t, 1.0, 0.0, 0.0);
D/skia    (26036):   17	    return _output;
D/skia    (26036):   18	}
D/skia    (26036):   19	mediump vec4 stage_Stage1_c0_c0_c1_c0(mediump vec4 _input) {
D/skia    (26036):   20	    mediump vec4 _output;
D/skia    (26036):   21	    mediump vec2 coord = vec2(_input.x, 0.5);
D/skia    (26036):   22	    _output = texture(uTextureSampler_0_Stage1, coord);
D/skia    (26036):   23	    return _output;
D/skia    (26036):   24	}
D/skia    (26036):   25	mediump vec4 stage_Stage1_c0_c0(mediump vec4 _input) {
D/skia    (26036):   26	    mediump vec4 _output;
D/skia    (26036):   27	    mediump vec4 t = stage_Stage1_c0_c0_c0_c0(vec4(1.0));
D/skia    (26036):   28	    if (t.x < 0.0) {
D/skia    (26036):   29	        _output = uleftBorderColor_Stage1_c0_c0;
D/skia    (26036):   30	    } else if (t.x > 1.0) {
D/skia    (26036):   31	        _output = urightBorderColor_Stage1_c0_c0;
D/skia    (26036):   32	    } else {
D/skia    (26036):   33	        _output = stage_Stage1_c0_c0_c1_c0(t);
D/skia    (26036):   34	    }
D/skia    (26036):   35	    {
D/skia    (26036):   36	        _output.xyz *= _output.w;
D/skia    (26036):   37	    }
D/skia    (26036):   38	    return _output;
D/skia    (26036):   39	}
D/skia    (26036):   40	mediump vec4 blend_multiply(mediump vec4 src, mediump vec4 dst) {
D/skia    (26036):   41	    return vec4(((1.0 - src.w) * dst.xyz + (1.0 - dst.w) * src.xyz) + src.xyz * dst.xyz, src.w + (1.0 - src.w) * dst.w);
D/skia    (26036):   42	}
D/skia    (26036):   43	void main() {
D/skia    (26036):   44	    mediump vec4 outputCoverage_Stage0;
D/skia    (26036):   45	    {
D/skia    (26036):   46	        mediump float edgeAlpha;
D/skia    (26036):   47	        mediump vec2 duvdx = dFdx(vQuadEdge_Stage0.xy);
D/skia    (26036):   48	        mediump vec2 duvdy = -dFdy(vQuadEdge_Stage0.xy);
D/skia    (26036):   49	        if (vQuadEdge_Stage0.z > 0.0 && vQuadEdge_Stage0.w > 0.0) {
D/skia    (26036):   50	            edgeAlpha = min(min(vQuadEdge_Stage0.z, vQuadEdge_Stage0.w) + 0.5, 1.0);
D/skia    (26036):   51	        } else {
D/skia    (26036):   52	            mediump vec2 gF = vec2((2.0 * vQuadEdge_Stage0.x) * duvdx.x - duvdx.y, (2.0 * vQuadEdge_Stage0.x) * duvdy.x - duvdy.y);
D/skia    (26036):   53	            edgeAlpha = vQuadEdge_Stage0.x * vQuadEdge_Stage0.x - vQuadEdge_Stage0.y;
D/skia    (26036):   54	            edgeAlpha = clamp(0.5 - edgeAlpha / length(gF), 0.0, 1.0);
D/skia    (26036):   55	        }
D/skia    (26036):   56	        outputCoverage_Stage0 = vec4(edgeAlpha);
D/skia    (26036):   57	    }
D/skia    (26036):   58	    mediump vec4 output_Stage1;
D/skia    (26036):   59	    {
D/skia    (26036):   60	        output_Stage1 = stage_Stage1_c0_c0(vec4(1.0, 1.0, 1.0, 1.0));
D/skia    (26036):   61	    }
D/skia    (26036):   62	    {
D/skia    (26036):   63	        mediump vec4 _dstColor = sk_FragColor;
D/skia    (26036):   64	        sk_FragColor = blend_multiply(output_Stage1, _dstColor);
D/skia    (26036):   65	        sk_FragColor = outputCoverage_Stage0 * sk_FragColor + (vec4(1.0) - outputCoverage_Stage0) * _dstColor;
D/skia    (26036):   66	    }
D/skia    (26036):   67	}
D/skia    (26036):   68
D/skia    (26036): Errors:
D/skia    (26036): ERROR: 0:3: 'GL_EXT_shader_framebuffer_fetch' : extension is not supported
D/skia    (26036): ERROR: 0:6: 'inout' : syntax error

**Comment by ibrierley** [comment]
Try flutter clean, see if that helps. Also if not, try restarting your emulator or create a new one, see if it still happens.

**Comment by fluttercid** [comment]
@ibrierley Thank you for your advice; however, I tried
- flutter clean
- device data delete and cold boot
- create another device
All of them did not work.

Is there another suggetion?
Thanks.

Also I downloaded example and tried it. It also has same result.
I think when it draw a map, it happen.

**Comment by ibrierley** [comment]
Is this in the emulator ? Do you get it on a live device as well out of interest ?

**Comment by fluttercid** [comment]
@ibrierley When I tested with a real device, it is OK.
Can I ignore this message when I tested with a emulator?
Thank you for your good answers.
Thanks.

**Comment by ibrierley** [comment]
My vague understanding is that it maybe a problem with the emulator opening a gl/graphics library context or something. I think there's an option when creating a virtual device to enable that, but I can't see anything like that myself.

Maybe there is some limitation with your PC or you're emulating an old device or something ? I'm purely guessing here though, just trying to give some ideas of where to look.

I suspect  if you ignore it, you may get oddities when running flutter_map in the emulator..so just be aware of that.

**Comment by fluttercid** [comment]
I replaced build's child in marker from 'FlutterLogo' to just 'Container' and it is gone now.

remove below:
          child: FlutterLogo(
            colors: Colors.blue,
            key: ObjectKey(Colors.blue),
          ),

Thanks.

**Comment by ibrierley** [comment]
ok sure, but just be aware it may come back with certain circumstances if nothing else has changed. At least you're aware of it now!

**Comment by fluttercid** [comment]
There is no more concern about it.
