### ISSUE TITLE
Unable to zoom beyond 18.0

### ISSUE THREAD

**Issue by kwg105** [fleaflet/flutter_map#720]
If I attempt to zoom in further than 18.0, the map is replaced with a gray screen.  Recreated using the sample app.

**Comment by ibrierley** [comment]
Try setting minZoom and maxZoom in your MapOptions.

**Comment by kwg105** [comment]
@ibrierley - I have a minZoom of 10.0, maxZoom of 25.0, and a starting zoom of 15.0.  Once I go beyond 18.0, gray screen and no errors.

**Comment by ibrierley** [comment]
Does your tile provider provide tiles at zoom 19+ ? Most don't I think, which one are you using ?

**Comment by kwg105** [comment]
The provider I was using goes to 24.0.  
But, I reverted back to openstreetmap.org which supports up to 20.0.  https://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by ibrierley** [comment]
What's the URL with the z/x/y format in it, you include out of interest ?

**Comment by kwg105** [comment]
I'm using the example:
                      "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",

**Comment by moovida** [comment]
@kwg105 , the OSM sources usually do not go over 18. After that they often block or don't even serve.

**Comment by maRci002** [comment]
`MapOptions` has `maxZoom` which is the `maxZoom for all layers` and `TileLayerOptions` has a `maxZoom` too. Imagine a situation you have multiple layers and the `base layer` which uses `0 - 25 zoom` and you have also a `wms layer` which uses `0-18 zoom` then if map's zoom goes beyond 18.0 zoom then wms layer is not fetching any image (which would anyway fail) moreover hides old ones.

**Comment by kwg105** [comment]
That was it @maRci002 !  I needed to set maxZoom in both TileLayerOption as well as MapOptions. Thank you!
