### ISSUE TITLE
OnTap click delay problem

### ISSUE THREAD

**Issue by princebb** [fleaflet/flutter_map#724]
Can you provide a configuration to advoid adding the **onDoubleTap** event? Because I am using fluttermap's **onTap** click event to draw points, found that there is a delay until the drawing is completed.I want to improve the user experience, and I don’t need the onDoubleTap zoom event.
```
FlutterMap(
                  mapController: widget.mapController,
                  options: MapOptions(
                      center: state?.center,
                      zoom: state?.zoom,
                      onTap: _mapClickEvent,
                      plugins: mapPlugins)
```
Thanks.

**Comment by maRci002** [comment]
In PR #719 you are able to disable certain interactions. There are `move`, `fling`, `pinchZoom`, `doubleTapZoom`, `rotate` interactions.

You need to provide your own `interactiveFlags` to `MapOptions` like this:
`interactiveFlags: InteractiveFlag.rotate | InteractiveFlag.pinchZoom  | InteractiveFlag.fling | InteractiveFlag.move
`

**Comment by princebb** [comment]
Thanks, let me take a look
