### ISSUE TITLE
OverlayImage tap detector

### ISSUE THREAD

**Issue by renantheodoro** [fleaflet/flutter_map#733]
How can I detect what OverlayImage the user is touching and how can I get the informations of this asset (its bounds and image name)? It is possible to do?

**Comment by X-SLAYER** [comment]
for me, I put overlay images on top of polygons and detect click of polygons like that :
use this package to detect if the selected Geopoint when u tap in polygon or no 
[geodesy](https://pub.dev/packages/geodesy)
```dart
var detectedPolygon = polygons.firstWhere(
      (polygon) {
        return geodesy.isGeoPointInPolygon(cordinate, polygon.points);
      },
      orElse: () => null,
    );
```

**Comment by renantheodoro** [comment]
> for me, I put overlay images on top of polygons and detect click of polygons like that :
> use this package to detect if the selected Geopoint when u tap in polygon or no
> [geodesy](https://pub.dev/packages/geodesy)
> 
> ```dart
> var detectedPolygon = polygons.firstWhere(
>       (polygon) {
>         return geodesy.isGeoPointInPolygon(cordinate, polygon.points);
>       },
>       orElse: () => null,
>     );
> ```

What would be `cordinate` and `polygon.points`?

**Comment by renantheodoro** [comment]
@X-SLAYER Thank you very much!!! It resolved!
