### ISSUE TITLE
How to draw widget with specified width/height in meters?

### ISSUE THREAD

**Issue by vladd11** [fleaflet/flutter_map#734]
I need to draw circle match location accuracy. Are there any ways to do this?

**Comment by maRci002** [comment]
https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/circle.dart#L13-L19

```dart
          useRadiusInMeter: true,
          radius: 2000 // 2000 meters | 2 km
```

**Comment by vladd11** [comment]
Thanks for help. Full solution.
`layers: [
              ...
              CircleLayerOptions(circles: [
                CircleMarker(
                    point: LatLng(0, 0),
                    useRadiusInMeter: true,
                    radius: 1000)
              ])
            ]`
