### ISSUE TITLE
Question: Why drawer is disabled on live_location example ?

### ISSUE THREAD

**Issue by Frezyx** [fleaflet/flutter_map#735]
![image 6 (2)](https://user-images.githubusercontent.com/40857927/91554501-eef92580-e937-11ea-9ec8-d61b0f16972d.jpg)

**Comment by maRci002** [comment]
Idk, but one of my PR I [fixed it](https://github.com/fleaflet/flutter_map/pull/719/files#diff-4374c37354ec707de41b3b45a21e54f7R118-R120)

**Comment by Frezyx** [comment]
@maRci002 Are you going to finish this pr?  It's really a very useful and important functionality.

Maybe you need some help with it?

**Comment by maRci002** [comment]
I think it's ready I'm going to add some documentation about events and retest multifinger gesture race.

**Comment by Frezyx** [comment]
It is very cool 👍 
Looking forward to these updates 😊
