### ISSUE TITLE
How to implement DynamicMapServiceLayer 

### ISSUE THREAD

**Issue by ishivamkapoor** [fleaflet/flutter_map#739]

**Comment by ishivamkapoor** [comment]
I want to add a dynamic map service layer over the Base Map Tile Layer but I am unable to do so. I was able to do it using ArcGISDynamicMapServiceLayer in javascript.

**Comment by ibrierley** [comment]
I'm not very familiar with that, but if the service returns a raster tile via a url, it should be possible. If it returns a datastructure to decode client side, I don't think that's currently possible. If not sure, find an example in js, open the dev console goto networking, and look at the requests coming back, and if the URLs are in a format that you can click on and it returns an image.

If so, you should be able to provide that url to your tilelayeroptions urlTemplate.

**Comment by ishivamkapoor** [comment]
I am unable to do so, if I add another TileLayerOption  with urltemplate in the array of layers  , the first layer disappears as well.

**Comment by ibrierley** [comment]
What about setting an opacity ? I guess it depends if there are any
transparent sections as well, or what exactly the image is, and how exactly
you would want it to work...

**Comment by ishivamkapoor** [comment]
![WhatsApp Image 2020-09-05 at 9 55 35 PM](https://user-images.githubusercontent.com/34067250/92309377-a76f3b00-efc2-11ea-925d-7dc42d68155e.jpeg)
I want like this as in the image. It has been implemented in javascript using ( Tilelayer as basemap and ArcGISDynamicMapServiceLayer for the red lines)

**Comment by ibrierley** [comment]
The only way I can see it being achieved, is if its a png or something and has some transparency, if it does, you should be able to add it as a tilelayer, if not, I'm not sure how you expect it to work ?

**Comment by ishivamkapoor** [comment]
Sir I am searching for alternative to L.esri.dynamicmaplayer (in js) for flutter_map

**Comment by ibrierley** [comment]
I suspect you will have to roll your own.

**Comment by kengu** [comment]
Closing as stale
