### ISSUE TITLE
The method 'LatLng' isn't defined for the type 'CompanyMap'.

### ISSUE THREAD

**Issue by AhmedAbogameel** [fleaflet/flutter_map#744]
LatLng is not defined in my flutter project

**Comment by AhmedAbogameel** [comment]
Resolved by importing it:

import 'package:latlong/latlong.dart';

**Comment by SaileshVerma** [comment]
still even after importing  'package:latlong/latlong.dart'; I m unable to use Latlng pls help

**Comment by daraul** [comment]
`import 'package:latlong2/latlong.dart';`

Would have been nice if that was in the docs.
