### ISSUE TITLE
Polyline projection on a globe

### ISSUE THREAD

**Issue by goranskular** [fleaflet/flutter_map#746]
Hi, it would be great if polylines were projected on the globe. Now polyline is a straight line from one latlng to a second one. It is ok for greater zoom levels, but very inaccurate when zoomed out. 

Is it possible that we get projected polylines?

**Comment by ibrierley** [comment]
Do you mean the points are out, or you want the line to be a curve to account for it, screenshot may be useful.

**Comment by goranskular** [comment]
Yes, I mean curved line like this:
![image](https://user-images.githubusercontent.com/5990380/93318107-93bba400-f80e-11ea-9d65-337bca89b06f.png)

**Comment by goranskular** [comment]
this geodesic: true would be perfect (snippet from google_maps_flutter):

```
Polyline(
          polylineId: PolylineId(
              'uniqueid'),
          **geodesic: true,**
          points: [originLatLng, destinationLatLng],
          width: 3,
          color: Theme.of(context).primaryColor,
        )
```

**Comment by maRci002** [comment]
Can u upload flutter_map image version which is now incorrect?

**Comment by maRci002** [comment]
Nice workaround.

**Comment by goranskular** [comment]
I encountered a new problem, but I already saw some issues about it :) So, this approach is not so simple.

![image](https://user-images.githubusercontent.com/5990380/93660758-63fcde00-fa52-11ea-9b7d-67db9321df24.png)

**Comment by S-Man42** [comment]
I am using a similar solution in my app for nearly a year right now:

Drawing Geodetic Polyline.:
https://github.com/S-Man42/GCWizard/blob/master/lib/widgets/tools/coords/base/gcw_map_geometries.dart#L39

I am splitting the real way into several substeps, project from start to all substeps and then I draw a polyline. The same thing can be done drawing better circles keeping their radius on the projected map:

Drawing "Geodetic" Circles :
https://github.com/S-Man42/GCWizard/blob/master/lib/widgets/tools/coords/base/gcw_map_geometries.dart#L81

![grafik](https://user-images.githubusercontent.com/16626063/94408031-87bbd480-0174-11eb-9214-5cd0a6d16eb0.png)

Surely, it's not the most efficient way to do this, espessially for more general purposes. But if you like, feel free to use the code.

The problem with the... I call it overflow..., I reported this already some months ago. I would be glad to see this problem solved!
https://github.com/fleaflet/flutter_map/issues/630

Maybe this could be a solution? 
https://github.com/fleaflet/flutter_map/issues/468
