### ISSUE TITLE
IOS memory leak, when adding points outside the bounds of the map

### ISSUE THREAD

**Issue by fre391** [fleaflet/flutter_map#747]
I recently noticed that a memory leak occurs when you add points to a polyline which is far out of the visible range of the map. In my case the origin was in Germany, but I added points to a polyline, which is located in the US by using the debug location options of the IOS simulator. When doing so, the app frontend is freezed, while internally >20GB of data will be allocated. After a few seconds (in my case approx. 20sec), it gets released again and the frontend is getting updated again.

It would be great to supress any calculations, when outside the visible area of the map. Do you have any suggestions? Thank you so much.

**Comment by goranskular** [comment]
The same thing on Android.
When having polyline far away and not on screen, it becomes unusable.

It can be reproduced really easily, just put some polylines far away from the on screen map. And zoom on that far away location.

**Comment by goranskular** [comment]
Adding polylineCulling: true worked for me.

**Comment by radomir9720** [comment]
@goranskular Thanks a lot! It helped.
