### ISSUE TITLE
Don't catching on errorTileCallback

### ISSUE THREAD

**Issue by Adrek** [fleaflet/flutter_map#748]
Hi, 
I would appreciate if you can give me a help.
I have a "hello world" app and I copied all the code from the following template to my app project for test errors. The only thing I commented was the drawer:
https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/tile_loading_error_handle.dart

Steps I did: 
1- I enter the page of the tile_loading_error_handle template.
2- I entered airplane mode
3- Zoom on the map
4- The app crashes and the vscode shows:
> SocketException (SocketException: Failed host lookup: 'a.tile.openstreetmap.org' (OS Error: No address associated with hostname, errno = 7)

The error ocurred in _network_image_io.dart
https://i.imgur.com/qme2uwn.png
It should be noted that the app does not reach errorTileCallback, but rather stays in the network_image catch

I made a video:
https://youtu.be/zMzoznvhJMk

Thanks for your help

More date:
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
...
flutter_map: ^0.10.1+1

Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (6 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**Comment by maRci002** [comment]
What if you press F5 (continue)?

![image](https://user-images.githubusercontent.com/8436039/93750571-f8ef0b00-fbfb-11ea-9d9c-1f99d1321b89.png)
Untick All exceptions / Uncaught exceptions which should solve your problem permanently. [Dart sometimes has hard time with uncaught exceptions](https://github.com/flutter/flutter/issues/33427) I mean it cannot search for catcher in stack trace if code is async.
