### ISSUE TITLE
Drawing route (Direction, not Skyway line)

### ISSUE THREAD

**Issue by pqtrong17** [fleaflet/flutter_map#749]
![image](https://user-images.githubusercontent.com/45705060/93747479-f521af80-fc20-11ea-8a43-8236b959c97e.png)
Sorry my englist is not good. I hope you understand.

I want something like this. PolylineLayerOptions draw a line from start point to end point. It's skyway, not route. Help me, please.

**Comment by maRci002** [comment]
Raster Tiles are just images we don't have any information about routes.

**Comment by pqtrong17** [comment]
> Raster Tiles are just images we don't have any information about routes.

Example: Depart point is Paris, France and arrive point is Rennes, France. I want draw a route from depart to arrive, not a skyway.

**Comment by maRci002** [comment]
I know what you mean, however we don't know about any routes in the app itself. Even if we would know the all routes on the earth then there are plenty of algorithms, I mean use highways / fields / shortest route etc. I assume you think we have information about current traffic too, forexample there is a traffic jam?
