### ISSUE TITLE
flutter build web no longer working with example app

### ISSUE THREAD

**Issue by jferas** [fleaflet/flutter_map#751]
This may be related to a recent flutter or dart release.. pretty sure this was working last week...

cd example
flutter build web
(lots of errors similar to below)
`Target dart2js failed: Exception: ../../../../.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.3/lib/path_provider_windows.dart:7:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../../../.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:6:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../../../.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart:6:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../../../.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:5:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/callbacks.dart:7:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';`

and these....

`../../../../.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:28:30:
Error: Type 'Pointer' not found.
typedef WinHeapAllocNative = Pointer Function(Pointer, Uint32, IntPtr);
                             ^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:28:47:
Error: Type 'Pointer' not found.
typedef WinHeapAllocNative = Pointer Function(Pointer, Uint32, IntPtr);
                                              ^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:28:56:
Error: Type 'Uint32' not found.
typedef WinHeapAllocNative = Pointer Function(Pointer, Uint32, IntPtr);
                                                       ^^^^^^
`

My Flutter environment.. since my most recent upgrade....

`flutter doctor -v
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-12.1.pre at /Users/jferas/flutter_dev/flutter
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jferas/Library/android-sdk-mac
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jferas/Library/android-sdk-mac
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!`

Pretty sure I could pull a plain vanilla FlutterMap into a Flutter app and do a 'flutter build web' with my previous versions of Flutter/Dart..

Is anyone else seeing this issue with the example app from the repo?

**Comment by maRci002** [comment]
Maybe #697 causes the problem.

Try to use commit 265e2935f7c794c62cd3300d332905dda30486ea or under that. Or just use `0.10.0` version for testing.

Don't forget to run `flutter pub get`

**Comment by jferas** [comment]
Hmmm... beginning to think it is related to my Flutter version or my Dart version.

In pubspec.yaml, I took the flutter_map version all the way back to 0.8.0 for a very simple test app that makes use of flutter_map.. did a "flutter clean" and a "flutter pub get"... still got the build issues described above when I did a "flutter build web"

Completely flushed my pubspec caches (hosted and git) and did the same steps above.. still got the error.

I haven't moved back to any older Flutter or Dart version.. I guess that's the next thing I should try.

**Comment by jferas** [comment]
Used "flutter downgrade" to take me back to flutter version "1.21.0-9.2.pre" on the beta channel (down from "1.22.0-12.1.pre" above).  Still getting the web build error after "flutter clean" and flushing the pub cache.

The "flutter downgrade" didn't change my Dart version... that remains at "2.10.0" and since these compiler errors are all coming from "dartjs" I'm still suspicious of the Dart version.

I don't see this "flutter build web" problem for apps that don't include the flutter_map plugin.

Before I go about figuring out how to downgrade my Dart to an earlier version.. Is anyone else seeing this problem with "flutter build web" and the flutter_map plugin?

**Comment by jferas** [comment]
Just went through a 'flutter upgrade' that move my 'dart' version up to 2.10.1 but still seeing this problem.

Curious if I am the only one seeing this and it is unique to my build environment.

Is anyone else successfully using this plugin with "flutter build web" ?

**Comment by bharathiselvan** [comment]
I am getting the same error while running the app on chrome.. Does anyone have the solution for this issue?..

**Comment by troyanskiy** [comment]
Same here (`v1.24.0-10.2.pre`):
```
% flutter build web --release

Running "flutter pub get" in brt_sales...                        1,155ms
Target dart2js failed: Exception: ../../../.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/material_with_modal_page_route.dart:21:16:
Error: Getter not found: 'opaque'.
        assert(opaque),
               ^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheets/cupertino_bottom_sheet.dart:339:46:
Error: No named parameter with the name 'shadowThemeOnly'.
    final isCupertinoApp = Theme.of(context, shadowThemeOnly: true) == null;
                                             ^^^^^^^^^^^^^^^
../../../Sites/sdks/flutter/packages/flutter/lib/src/material/theme.dart:119:20:
Info: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
../../../.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheets/material_bottom_sheet.dart:40:32:
Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(context, shadowThemeOnly: true),
                               ^^^^^^^^^^^^^^^
../../../Sites/sdks/flutter/packages/flutter/lib/src/material/theme.dart:119:20:
Info: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
../../../.pub-cache/hosted/pub.dartlang.org/extended_image-1.5.0/lib/src/extended_image.dart:785:44:
Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
../../../Sites/sdks/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25:
Info: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                             13.8s
Exception: Failed to compile application for the Web.

```

Version `1.23.0-18.1.pre` is OK

**Comment by troyanskiy** [comment]
Latest release (`1.25.0-8.1.pre`) of beta still have build web problem, exactly same as described above.
