### ISSUE TITLE
pinning the map

### ISSUE THREAD

**Issue by nickiw38** [fleaflet/flutter_map#753]
isn't there anyway for the user to pin the map and when she does it i get pin's long and latitude?

**Comment by Swepilot** [comment]
Use onTap or onLongPress in MapOptions to register a function to create a Marker. Those callbacks will give you the LatLng from where the user taps or presses.

**Comment by maRci002** [comment]
[Example code](https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/tap_to_add.dart)

**Comment by kengu** [comment]
Closing as stale.
