### ISSUE TITLE
Is it possible to drag markers on the map?

### ISSUE THREAD

**Issue by S-Man42** [fleaflet/flutter_map#758]
Hi,

I created some markers on the map. Now I want to drag/move it to another position of the map. Is that possible?

**Comment by ibrierley** [comment]
I don't think it's possible currently with the default flutter_map. I did do a plugin at https://github.com/ibrierley/flutter_map_dragmarker which you may want to play with an see if it works for you.

**Comment by Ahmed-gubara** [comment]
This code worked for me by using **GestureDetector**

 ```
  final _controller = MapController();
  final _points = <LatLng>[];

  @override
  Widget build(BuildContext context) {
    List<Marker> markers = List.generate(
      _points.length,
      (index) => Marker(
        width: 20,
        height: 20,
        point: _points[index],
        builder: (context) => GestureDetector(
          onPanUpdate: (details) {
            CustomPoint position = Epsg3857().latLngToPoint(_points[index], _controller.zoom);
            Offset delta = details.delta;
            LatLng pointToLatLng = Epsg3857().pointToLatLng(position + CustomPoint(delta.dx, delta.dy), _controller.zoom);

            _points[index] = pointToLatLng;

            setState(() {});
          },
          child: Container(...),
        ),
      ),
    );
  ......
  }
```

**Comment by S-Man42** [comment]
@Ahmed-gubara Great this works for me! :)

**Comment by Mike-3** [comment]
Unfortunately, this code no longer works in version flutter_map 0.14.0. Up to version 0.13.1 it worked fine. From version 0.14.0 onPanUpdate is no longer called to move the markers.
Is there an approach to solve the problem?
