### ISSUE TITLE
add onCameraIdle method like google map

### ISSUE THREAD

**Issue by masoudpaidar** [fleaflet/flutter_map#759]
There is onPositionChanged option in flutter_map but it gets called every time the position is changing, which is a lot. As soon as the user touched the screen, the onPositionChanged gets called until the user stops touching the screen,
but there is no option to call a method when camera movement has ended like a  onCameraIdle in the google map

**Comment by maRci002** [comment]
In #719 you can listen to events

```dart
  StreamSubscription<MapEvent> subscription;

  @override
  void initState() {
    super.initState();
    mapController = MapController();

    subscription = mapController.mapEventStream.listen(onMapEvent);
  }

  void onMapEvent(MapEvent mapEvent) {
    if (mapEvent is MapEventMoveEnd) {
      // do something
    }
  }

  @override
  void dispose() {
    subscription?.cancel();
    super.dispose();
  }
```

**Comment by masoudpaidar** [comment]
HI @maRci002 
but for this problem i don not know what is the MapEvent and when i use it i have a error can you explanation more pls?

**Comment by jiazeh** [comment]
You can check MapEvent on [here](https://github.com/fleaflet/flutter_map/tree/a6b5c6f6722e66462b022e49f01f730d68b0d12d/lib/src/gestures) and [here](https://github.com/fleaflet/flutter_map/tree/a6b5c6f6722e66462b022e49f01f730d68b0d12d)

Hope it helps..

**Comment by maRci002** [comment]
@jiazeh is right.

I'll soon finish that PR (little docs + fix when no event triggered when mapController.fitBounds called), I was a little busy :)
