### ISSUE TITLE
Implement different url

### ISSUE THREAD

**Issue by hamid3d** [fleaflet/flutter_map#760]
hi
I want to use a map based on this url

`https://api.neshan.org/v2/static?key=service.w3EcEiZSVBzP7VQdxMitkIRWWB0cVuShn4Xo9f9z&type=dreamy&zoom={z}&center={x},{y}&width=256&height=256`

but for x and y it accepts something like

`center=35.700538,51.337907 `

but Fluttermap generate this format x=4908 y=2707

how to change default format to that format?

**Comment by govorilka** [comment]
Try this: https://github.com/fleaflet/flutter_map/pull/805
