### ISSUE TITLE
New markers map not updated

### ISSUE THREAD

**Issue by JohnnyBeGood70** [fleaflet/flutter_map#761]
Hi,

I try to add a list of markers to the map (with a button click), after the map is shown, by adding a new MarkerLayerOptions layer populated with the list of markers. The layer is added in a setState encapsulation. Unfortunately the markers are not displayed until I manually move or zoom the map. Doing this via a mapcontroller doesn't work.

I know others had similar issues in the past but the solutions suggested there didn't help me.

Can you please give me any hints and/or examples how to overcome this problem?

Thanks in advance!

**Comment by maRci002** [comment]
This shouldn't happen any code to reproduce?

If there is any then you can still do some workaround, maintain a `int key = 0;` property and when you click on Button do your stuff and `key++;` and provide this `key` to `MarkerLayerOptions(key: Key(key.toString()), ...)` which should force Flutter to rebuild.
