### ISSUE TITLE
list of markers

### ISSUE THREAD

**Issue by grungy01** [fleaflet/flutter_map#762]
hi ! is it possible to add multiple markers ?
I'm trying to loop on Markers but with no success :
![Capture d'écran Deepin_zone de sélection _20201015164843](https://user-images.githubusercontent.com/72883291/96146208-5712c380-0f06-11eb-85ab-4c750311d01a.png)

**Comment by ibrierley** [comment]
Yes, you can add multiple markers, just make sure your list has them inside. You can create your list before the return statement, so you can check what's in there (it's hard to tell from your code the way it's formatted here, there's no need to include the for loop inside the list).

**Comment by grungy01** [comment]
Before i tried to put my loop in a  function being called by MarkerLayerOptions but i couldn't initialize my list with choosenisland (it's a list of object containing a sublist with xyBeach ~ latlong coord).  Do you have an example of code  ?

**Comment by ibrierley** [comment]
First I think you need to define what 'doesn't work' is...any error ? Does just one marker display ? etc
The reason I suggested something like (not tested, no near a flutter pc atm)...is that you can firstly debug what's in your list. Once you can output to the console your list etc and verify that is all good and latlngs correct etc, you can then move on...
I also note you don't have any width/height for your marker. Can't remember if that could be an issue or not...
```
...near start of build method...
List<Marker> markers = [];
for( var i=0; i <= choosenisland.length; i++ ) {
  var m = Marker( marker stuff in here )
  markers.push(m);
}
...later
MarkerLayerOptions( markers: markers );
```

**Comment by grungy01** [comment]
yeah my fault ^^, i had previously a red screen saying that it was out of list (2 and there is only 2 value for the moment)  so the problem come probably how i call my object. Unstead of testing **<=** choosenisland.length" i put  ** <**. I got my map back but without any marker but i think the loop is okay but the probleme come the way i call my data.

when i ran   setStat()  =>  print(choosenisland.xyBeach[0]); it show nothing unstead of giving me latitude

**Comment by ibrierley** [comment]
First try with some test data and expand from there. If you create a minimal example, with a couple of points and it fails, post the example here so someone can test it. It's quite hard to have any idea without seeing the source data and rest of code. But try and keep examples minimal.

**Comment by grungy01** [comment]
@ibrierley  thank you ! the problem was actually not the variables neither , my icons where so small that i couldn't see them ^^
