### ISSUE TITLE
Wrong bounds at first time

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#764]
First time the bounds is wrong and in console prints
```
{
 north: 85.05113935741468, 
 south: 85.04219535127464,
 east: -179.92949622017997,
 west: -180.0
}
```

```dart
Widget build(BuildContext context) {
    return new FlutterMap(
      options: new MapOptions(
        center: new LatLng(51.5, -0.09),
        zoom: 13.0,
        onPositionChanged: (MapPosition position, bool hasGesture) {
          print({
            'north': position.bounds.north,
            'south': position.bounds.south,
            'east': position.bounds.east,
            'west': position.bounds.west,
          });
        },
      ),
      layers: [
        new TileLayerOptions(
            urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            subdomains: ['a', 'b', 'c']
        ),
        new MarkerLayerOptions(
          markers: [
            new Marker(
              width: 80.0,
              height: 80.0,
              point: new LatLng(51.5, -0.09),
              builder: (ctx) =>
              new Container(
                child: new FlutterLogo(),
              ),
            ),
          ],
        ),
      ],
    );
}
```

**Comment by sm2017** [comment]
@johnpryan Can you please take a look?

**Comment by sm2017** [comment]
@johnpryan @maRci002 Can you please take a look?

**Comment by mtardal** [comment]
I encountered the same issue and I am using this workaround for now as my use case doesn't require values around this.
`if (position.bounds.west == -180.0) return;
`
But obviously, this is a band-aid fix.

**Comment by sm2017** [comment]
@johnpryan can you please reply?

**Comment by sm2017** [comment]
Re-opened

**Comment by sm2017** [comment]
No stale

**Comment by sm2017** [comment]
@johnpryan @maRci002 Please, Please reply after 6 month! @github-actions not stale again!

**Comment by sm2017** [comment]
@johnpryan thanks for your response, just run it and see the output of first `print` in the console, the first time bounds are wrong

**Comment by sm2017** [comment]
Not stale

**Comment by ibrierley** [comment]
Just tested this. For what it's worth it works ok for me, on both real device and emulator. I get 

{north: 51.533709749589526, south: 51.46644042394476, east: -0.05922317504882813, west: -0.12102127075195314}
, on master and nullsafety git branches.

So the obvious question is why isn't it working for you. Have you tried with a fresh flutter project ? It would be good to isolate what the difference is. Can you expand a bit on what setup you are trying (just in case there is some timing issue with things getting initiliased).

Can you dump out "flutter pub deps" ?
