### ISSUE TITLE
Not work with gradle 4.0.0 in release mode

### ISSUE THREAD

**Issue by Miko2x** [fleaflet/flutter_map#771]
Not work with gradle 4.0.0 in release mode, working after downgrade to 3.5.0

in `android/build.gradle`
~~`classpath 'com.android.tools.build:gradle:4.0.0'`~~ ❌
`classpath 'com.android.tools.build:gradle:3.5.0'` ✔

**Comment by kengu** [comment]
Android in example app is upgraded to gradle 4.1.0. Closing.
