### ISSUE TITLE
FIxing example!!!

### ISSUE THREAD

**Issue by joselbr2099** [fleaflet/flutter_map#774]
when i try build example i get multiple errors;

`lib/pages/animated_map_controller.dart:93:13: Error: No named parameter with the name 'colors'.
            colors: Colors.green, `

the code is in multiple files with FlutterLogo witget, to fix them:
replace only **colors** parameter with **textColor**  in every FlutterLogo widget, such like this:

`FlutterLogo(
    key: Key('green'),
    textColor: Colors.green,
 ),`

**Comment by GGLabCenter** [comment]
+1. I wanted to try the example..
but I get multiple errors on the AnimationController, also: 
_The named parameter 'vsync' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'vsync'._

Moreover a dependency library seems deprecated: latlong.
