### ISSUE TITLE
Routes between two points

### ISSUE THREAD

**Issue by Maurycio-Kemesson** [fleaflet/flutter_map#775]
Someone can help or say if can make a route between two points for example from point A to point B, I did it using the polyline but it does a path but not with route.

**Comment by ibrierley** [comment]
I think you need to explain a bit further what you mean, maybe with some example. It's not really clear to me what you are meaning with   >>it does a path but not with route<<.

If you have a route, i.e a list of latlongs, you should be able to create a polyline from them. Maybe I am misunderstanding your problem though.

**Comment by Maurycio-Kemesson** [comment]
![image](https://user-images.githubusercontent.com/53949129/99410633-7a4bdc80-28d1-11eb-9e69-2a8da6a7d7e1.png)

**Comment by ibrierley** [comment]
Ok, so I'm guessing you don't have a list of latlngs from a directions API yet ?

**Comment by Maurycio-Kemesson** [comment]
it's like this, I wanted you to make a route from point A to B, passing through the streets, and not in the way you are, maybe I'm doing it the wrong way.

**Comment by Maurycio-Kemesson** [comment]
As it is, he draws a line without respecting the direction of the streets, and what I need is for him to actually make a route from point A to B without being fluctuating but rather going through the streets, can you understand?@ibrierley

**Comment by ibrierley** [comment]
Ok, it's not clear if you have any directions from anywhere. Here's what I would do (NOT complete code)...

You need to grab a Mapbox Directions API key, and test you can query them. Once you have the code, you can make a call. 

Example snippets of code. THIS WILL NOT WORK AS IS. It's just some bits to try and give a process.

Get your start & end LatLngs, convert to a string, and then insert where start/endLatLngString are below

INCOMPLETE CODE.

```
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';
import 'dart:async';
import 'dart:convert';
//other imports

/// your stuff...below probably in a method & class somewhere

var res;
var polyline;

try {
    String url = 'https://api.mapbox.com/directions/v5/mapbox/walking/' + startLatLngString + ';' + endLatLngString + '?steps=true&geometries=geojson&access_token=<INSERT YOUR MAPBOX API TOKEN HERE!!!!!!!!!!>
    res = await http.get( url );
    polyline = jsonToPolyline( res.body )
    
} catch (e) {
        print("FAILED!!");
        print(e);
}

return polyline;

/// Have a sub that converts from json to a polyline. Old example...

static Polyline jsonToPolyLine( String jsonString ) {

    Polyline polyline;
    List<LatLng> geometryList = [];
    List<LatLng> intersectionList = [];
    LatLng thisll;
    var myJson = json.decode( jsonString );

    List<dynamic> routes = myJson['routes'];
    List<dynamic> legs = routes[0]['legs'];
    List<dynamic> steps = legs[0]['steps'];

    steps.forEach(( el ) {

      el['geometry']['coordinates'].forEach( ( arrEl ) {
        thisll = new LatLng( arrEl[1], arrEl[0]);
        geometryList.add( thisll );
      });


    });
    polyline = new Polyline( points: geometryList, color: Colors.indigoAccent, strokeWidth: 3.0, isDotted: true );
    return polyline;
  }

```

If I get time some day, I'll try and make a plugin or something which works.

**Comment by Maurycio-Kemesson** [comment]
![image](https://user-images.githubusercontent.com/53949129/99413785-e5e37900-28d4-11eb-9c69-b36f52ad255d.png)


The problem is here, instead of deflecting it, it passes over the objects in front, and I need it to trace from one point to the next, respecting the direction of the streets etc. @ibrierley

**Comment by ibrierley** [comment]
See the earlier reply r.e mapbox api and code.

**Comment by ibrierley** [comment]
Out of interest, I spotted this today, which could be useful for some.

https://pub.dev/packages/mapbox_api

**Comment by JaffaKetchup** [comment]
Please still http://project-osrm.org/ if you still care about this. It should path find for you for free and you just need to draw the line.

**Comment by ibrierley** [comment]
Oo thanks for that, I wasn't aware of it. Had used Mapbox with it. Maybe I'll cobble together a plugin at some point in the future for it, as it may be quite handy.

**Comment by JaffaKetchup** [comment]
Hah, I'm beating you to it as I started it yesterday! Sorry!

**Comment by ibrierley** [comment]
Np and thanks for letting me know ! I'm not looking for plugins to write :D (altho I need to test a few I've done again and add to readme). Happy for you to do it, and I'll very likely use it if you let me know when you want someone to test.

**Comment by JaffaKetchup** [comment]
Thanks! I'm planning to make it a standalone for osrm, but through the magic of tree shaking, it will also be a plugin for flutter_map if you have it installed. And maybe, I'll link it to my offline plugin, so you can download all the map tiles along a route!
