### ISSUE TITLE
Offset the center of the map

### ISSUE THREAD

**Issue by ixsans** [fleaflet/flutter_map#777]
It is possible to offset the center of a location bounds with certain amount of pixel in flutter_map?
For example i multiple points and did calculation to get center of all points. Then i wanted to move map to some pixels and get it position in lat lng.

After get the lat lng, i want to move map position to it? is it possible?

Any answer will be appreciated. 
Thanks

**Comment by kanhaic** [comment]
I don't think there is a method in flutter_map to do that, I have achieved this by using the move method and subtracting 0.001 from latitude to move it up

options: MapOptions(
          interactive: true,
          maxZoom: 19,
          center: LatLng(
            (_currentLocation?.latitude ?? 0) - 0.001,
            _currentLocation?.longitude ?? 0,
          ),
          zoom: 17,
        ),

**Comment by JaffaKetchup** [comment]
Replaced by #1460. This will be added for v5 by #1532 (2764747)!
