### ISSUE TITLE
Zoom 18+

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#788]
My tile server support maxZoom=20, My leafletjs map works with zoom 19 and 20

In flutter application, I set `maxZoom:20` in `MapOptions` , in zoom<=18 everything is OK, but in zoom 19 and 20 no tile is requested

**Comment by ibrierley** [comment]
Note, I think tilelayer takes a min/maxzoom as well, so make sure you set it on the tilelayeroptions. Also note, there's a mi/maxnativezoom as well, if it applies. There's a few comments on the params at https://github.com/fleaflet/flutter_map/blob/master/lib/src/layer/tile_layer.dart so worth having a read.

**Comment by Informateur** [comment]
maxNativeZoom
