### ISSUE TITLE
flutter-pi offline maps support

### ISSUE THREAD

**Issue by matzesoft** [fleaflet/flutter_map#791]
I want to use flutter map in my [flutter-pi](https://github.com/ardera/flutter-pi) project. But it seems like there is a issue using offline maps.

1. Install flutter-pi
2. Import the offline maps example
3. Check the output of the flutter-pi app

**Output:**
```
$ flutter: Observatory listening on http://127.0.0.1:41449/dtyhCxUW25k=/
$ flutter: Unable to load asset: assets/map/anholt_osmbright/12/2182/1259.png
$ flutter: Unable to load asset: assets/map/anholt_osmbright/12/2182/1260.png
$ flutter: Unable to load asset: assets/map/anholt_osmbright/12/2182/1261.png
```

As you look into the provided assets theses requested images are out of range. However the rest of the map is loading fine. Here is a [screenshot](https://github.com/matzesoft/kart-project/blob/master/screenshots/2020_07_23.jpeg) of my own project showing the example.
Another issue I run into is that the zoom of the map is randomly resetting. I also run into the zoom issue using my own map data, the `Unable to load asset` error in this case did not appear.

**Comment by matzesoft** [comment]
I also created two [videos](https://github.com/fleaflet/flutter_map/files/5701003/Archiv.zip) showing the issues. One shows the example, the other one my own project.

**Comment by moovida** [comment]
Did you try to compiling the app for web? I wonder if the pi touchscreen has a different "feeling" than usual devices screens. Possibly the web compiled version might respond better due to better browser support?

**Comment by matzesoft** [comment]
Would be a good idea to try but I am using the lite version of RaspberryPi OS which comes with no desktop interface. flutter-pi is just running from the command line interface.

**Comment by moovida** [comment]
I am not sure I understand. You run it and somewhere you see it on the screen right? As per your videos. So the same way you could run a ligthweight http server and run that and access the screen. Sorry, I seem to miss some bits about the flutter-pi project, which anyways does fascinate me a lot :-)

**Comment by matzesoft** [comment]
Well, I am also just a flutter-pi user so I can't tell you much about the details 😅. But here is a quote of the readme:

> A light-weight Flutter Engine Embedder for Raspberry Pi. Inspired by https://github.com/chinmaygarde/flutter_from_scratch. Flutter-pi also runs without X11, so you don't need to boot into Raspbian Desktop & have X11 and LXDE load up; just boot into the command-line.

Thats why I had choosen Raspbian lite (which only comes with a command-line) so running a http server would be a good idea but opening a website in the command-line seems hard to do.

However as @ardera has mentioned in this [issue](https://github.com/ardera/flutter-pi/issues/138) zooming in `flutter_gallery` works fine. So the issue is probably part of `flutter_map`. Support for `flutter-pi` would be awesome to get but I understand that there is the question if the work would be worth it.

**Comment by ibrierley** [comment]
It's not very clear to me if there's one problem or several in here, and what's Pi related...

the assets error in the original post...if they don't exist (or do they?) then I'm not sure what fix is desired (other than making sure they are there?)

Then there's the touchscreen problem, is that simply not enough grunt on the Pi, or something with the screen ?

**Comment by matzesoft** [comment]
Yeah that the problem. The issue could go in so many directions so its hard to find out what causes it.

### Touch input issue
As I mentioned above, ardera has tested zoom with the `flutter_gallery` widget:

> Additionally, flutter_gallery has a widget for testing zoom. I tested there and it works fine

I also tested this [`zoom_widget` package](https://pub.dev/packages/zoom_widget) and it worked completely fine aswell.
Which leads me to say that the issue is not caused because of touch input.

### Unable to load asset issue
No, the required assets aren't included in the map data but everything of the map is still shown correctly. I also tested the offline maps example on my iPhone and I didn't got any error of missing assets. So `flutter_map` in `flutter-pi` is trying to access map data which is out of the given reach.

**Comment by matzesoft** [comment]
Cause it doesn't seem after any solution here I now switched to a different map package which worked for me.
But still thanks for the interest.
