### ISSUE TITLE
Show text under marker icon

### ISSUE THREAD

**Issue by S-Man42** [fleaflet/flutter_map#796]
Hi,

I want to display some text, like "Marker 1" below my marker. Currently my marker icon is centered on the related coordinate.

Is there a way to keep the marker icon position on the coordinate while adding some text below?

I could replace my marker Icon with a `Column` which includes the `Icon` and the `Text`, but then the entire `Column` center points to the coordinate, not only the icon:
The entire widget will be aligned: Before the entire widget was only the icon which worked fine, now it is the icon and the text. This yield another center point for aligning. 

So I am struggling with this issue for a long time. Can anybody help me?

Kind regards,
Mark

**Comment by robertpiosik** [comment]
![image](https://user-images.githubusercontent.com/7120725/110826242-29536000-8295-11eb-9af3-0d1ccce02303.png)

Look at marker's params, you can set something like anchorPos

**Comment by QTree-app** [comment]
> Is there a way to keep the marker icon position on the coordinate while adding some text below?

did you find a solution mate?

**Comment by S-Man42** [comment]
No, not yet, sorry.

**Comment by ibrierley** [comment]
Can you not add something like a Stack with 2 Positioned Widgets ?

**Comment by S-Man42** [comment]
Several approaches I had, positioned the center of the entire Stack on the coordinate. We need something to keep the icon centered and just put the label below... If you have an idea, please let us know :)
