### ISSUE TITLE
Markers draggable and dynamically loaded

### ISSUE THREAD

**Issue by rafaelsimonassi** [fleaflet/flutter_map#802]
Hello,

I would like to know if flutter_map supports the following:

1) Is it possible to have draggable markers? 
2) Is it possible to load the markers based when moving the map position? For example, if I move the map initial position, I want to load more markers from an external database.
3) Is it possible to create route lines between two points?

Regards

**Comment by ibrierley** [comment]
I did these 2 plugins if any use...
dragmarker https://github.com/ibrierley/flutter_map_dragmarker/
lineeditor (uses plugin above) https://github.com/ibrierley/flutter_map_line_editor 

I think that will work for 1&3, but maybe you'd have to combine for your 2nd question with some custom code.

**Comment by rafaelsimonassi** [comment]
Hello Ian,

Thank you very much for the suggestions, I will try those plugins.

As resgard question #2, I already tried a solution using a StreamBuilder approach, but the problem is that it consumes lots of CPU, since I need to always update the UI. I pasted a snippet of code below.



class _MapState extends DefaultState<MapPage> {
  final StreamController _mapController = StreamController.broadcast();
  List<MyMarkeer> mymarkers = List();
  Stream get onVariableChanged => _mapController.stream;
  void updateCurrentMapUI() => _mapController.sink.add(mymarkers);
  @override
  void dispose() {
    _mapController.close();
    super.dispose();
  }
  Widget build(BuildContext context) {
       return Scaffold(
            key: super.scaffoldKey,
            floatingActionButton: FloatingActionButton(
              onPressed: () =>
                  Navigator.push(context, PageTransition(type: PageTransitionType.bottomToTop, child: MarkeerCreationPageFirst(point: point, myUser: widget.myUser,))),     
             child: Icon(Icons.add_location),
            ),
            body:
return Container(
                        child: StreamBuilder(
                      stream: mapProvider.fetchMyMarkeersNearByAsStream(mymarkeers', latitude, longitude, distance),
                      builder: (context, snapshot) {
                        switch (snapshot.connectionState) {
                          case ConnectionState.none:
                          case ConnectionState.waiting:
                            updateCurrentMapUI();
                            return Center(child: CircularProgressIndicator());
                          default:
                            {
                              mymarkers.clear();
                              snapshot.data.docs.forEach((marker) {
                                mymarkers.add(MyMarkeer.fromMap(
                                    user: widget.myUser,
                                    snapshot: marker.data(),
                                    id: marker.id,
                                    myMarkeerDoc: marker));
                              });
                              double lat1= latitude;
                              double long1 = longitude;
                              return StreamBuilder(
                                stream: onVariableChanged,
                                builder: (context, snapshot) {
                                  switch (snapshot.connectionState) {
                                    case ConnectionState.none:
                                    case ConnectionState.waiting:
                                      updateCurrentMapUI();
                                      return Center(
                                          child: CircularProgressIndicator());
                                    default:
                                      updateCurrentMapUI();
                                      return new FlutterMap(
                                        options: new MapOptions(
                                          onPositionChanged:
                                              (position, hasGesture) {
                                            if (checkBoundaries(
                                                    LatLng(lat1, long1),
                                                    distance,
                                                    position.bounds.northEast)
                                                ) {
                                              lat1 = position.bounds.northEast.latitude;
                                              long1 = position.bounds.northEast.longitude;
                                              mapProvider
                                                  .fetchMyMarkeersNearByAsStream(
                                                      'mymarkeers',
                                                      lat1,
                                                      long1,
                                                      distance)
                                                  .forEach((markers) {
                                                markers.docs.forEach((marker) {
                                                  mymarkers.add(
                                                      MyMarkeer.fromMap(
                                                          user: widget.myUser,
                                                          snapshot:
                                                              marker.data(),
                                                          id: marker.id,
                                                          myMarkeerDoc:
                                                              marker));
                                                  updateCurrentMapUI();
                                                });
                                              });
                                            }
                                          },
                                          maxZoom: 16.5,
                                          minZoom: 10.5,
                                          bounds: LatLngBounds(
                                              LatLng(latitude, longitude),
                                              LatLng(latitude, longitude)),
                                          zoom: 16.5,
                                        ),
                                        layers: [
                                          new TileLayerOptions(
                                              urlTemplate:
                                                  "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                                              subdomains: ['a', 'b', 'c']),
                                          new MarkerLayerOptions(
                                            markers: mymarkers,
                                          ),
                                        ],
                                      );
                                  }
                                },
                              );
                            }
                        }
                      },
                    ));
......
    );
}
....
}
