### ISSUE TITLE
Because every version of user_location from git depends on flutter_map ^0.10.1 and Application_Name depends on flutter_map ^0.11.0, user_location from git is forbidden. So, because Application_Name depends on user_location from git, version solving failed.

### ISSUE THREAD

**Issue by pravinbhole1** [fleaflet/flutter_map#807]
Because every version of user_location from git depends on flutter_map ^0.10.1 and Application_Name depends on flutter_map ^0.11.0, user_location from git is forbidden. So, because Application_Name depends on user_location from git, version solving failed.

Not getting proper solution for this

**Comment by loonyfawn** [comment]
Hello. May be I am late, but could you try  to change versions like **flutter_map: any**. It works for me.

**Comment by TesteurManiak** [comment]
> Hello. May be I am late, but could you try to change versions like **flutter_map: any**. It works for me.

This is not a solution if he wants to use the latest version of flutter_map.

The only solution that you could apply is to fork the package `user_location` and upgrade its `flutter_map` dependency to the latest and waiting for the maintainer of `user_location` to upgrade the dependency himself to use the original package again.

You should probably also open an issue on the package `user_location` for an upgrade of the lastest dependencies if it was not already asked.
