### ISSUE TITLE
Disable Snap when dragging?

### ISSUE THREAD

**Issue by cliffordh** [fleaflet/flutter_map#809]
I've implemented a basic map, but when dragging around the map the map view "snaps to grid". I don't know what to enable to allow smooth panning and dragging. Here is my implementation:
`
The code

      return FlutterMap(
       mapController: _mapController,
       options: MapOptions(
        center: LatLng(currentLatLng.latitude, currentLatLng.longitude),
        zoom: 7.0,
        interactiveFlags: interActiveFlags,
      ),
      layers: [
        TileLayerOptions(
          urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          subdomains: ['a', 'b', 'c'],
          retinaMode: false,
          backgroundColor: const Color(0x00000000),
          // For example purposes. It is recommended to use
          // TileProvider with a caching and retry strategy, like
          // NetworkTileProvider or CachedNetworkTileProvider
          tileProvider: NetworkTileProvider(),
        ),
        MarkerLayerOptions(markers: markers)
      ],
    );
`

**Comment by daniel-stoneuk** [comment]
The closest thing I've been able to get to disabling the panning is by removing `flingAnimation` from the interactiveFlags, like so:

```
interactiveFlags: InteractiveFlag.all &
                  ~InteractiveFlag.flingAnimation &
                  ~InteractiveFlag.rotate,
```

The problem with this is that there's no fling or velocity at all anymore. Were you able to solve this?

**Comment by daniel-stoneuk** [comment]
After checking again on my device it seems like the map isn't actually snapping - it just feels like it due to the fling animation. Can you confirm this? There doesn't seem to be a particular grid it snaps to.

This is probably an issue that stems from #271.
