### ISSUE TITLE
Disable map rotation

### ISSUE THREAD

**Issue by joao10martins** [fleaflet/flutter_map#811]
Is it possible to disable roation of the map? I do not want the map to rotate.

**Comment by ibrierley** [comment]
Not tried it, but I note the latest version of FlutterMap has both "layers" and "nonRotatedLayers"...have you tried using that instead of layers in your FlutterMap creation (and nonRotatedChildren rather than children) ?

**Comment by joao10martins** [comment]
I tried using the "nonRotatedLayers" and indeed, the rotation was disabled. But that introduced wrong behavior of pinch actions and even dragging. To give you an example: when I tried to drag the screen down in order to scroll upwards on the map I instead went downwards.

**Comment by merxim** [comment]
Hey, I noticed the map was rotating for the first time today (which i didnt have on another device last week) and I came to ask the EXACT same question. I don't know if you 've solved it in the meantime, but in case you haven't:

Digging through the code led me to the _interactive_flag_ class which you can use in your **MapOptions** .  The following code works for me to disable rotation:

    MapOptions options = MapOptions(interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate,
      );
    return FlutterMap(
      mapController: _mapController,
      options: options,
      layers: [.... etc
      ]
      );

**Comment by joao10martins** [comment]
Yeah I could fix that later. By doing the same thing.

**Comment by Apollo108** [comment]
Jesus Christ, even deliberately I couldn't have come up with more harder way than that...

**Comment by kengu** [comment]
@Apollo108 This is a community driven spear-time effort. Feel free to contribute to make it better. I agree that things can be better, it always can, but please keep the comments constructive.

**Comment by hey-riki-here** [comment]
> Hey, I noticed the map was rotating for the first time today (which i didnt have on another device last week) and I came to ask the EXACT same question. I don't know if you 've solved it in the meantime, but in case you haven't:
> 
> Digging through the code led me to the _interactive_flag_ class which you can use in your **MapOptions** . The following code works for me to disable rotation:
> 
> ```
> MapOptions options = MapOptions(interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate,
>   );
> return FlutterMap(
>   mapController: _mapController,
>   options: options,
>   layers: [.... etc
>   ]
>   );
> ```

Great! It worked for me. Thanks! 😄

**Comment by Tarek-higazi** [comment]
Old thread but i noticed that its impossible to block map-rotation on Web.  Using the latest Fluttermaps version & disabling rotation in MapOptions, i can still rotate using by pressing the Ctrl button, clicking the mouse & moving it. 
(on mobile works as expected)

**Comment by josxha** [comment]
@Tarek-higazi the rotate flag is implemented as a two finger rotate gesture only, the Ctrl+drag gesture can be disabled like described here: https://docs.fleaflet.dev/usage/options/interaction-options#cursor-keyboard-rotation
I agree that splitting this appart is not the right approach and confusing. https://github.com/fleaflet/flutter_map/pull/1809 tries to solve that.
