### ISSUE TITLE
How to know when map is fully loaded?

### ISSUE THREAD

**Issue by gsimko** [fleaflet/flutter_map#812]
I would like to trigger a function when the map with the current bounds is fully loaded/finalized. Is this doable today?

Looks like we could add listeners to the layers and for example in TileLayer's case notify them from TileLayerState's _onAnimateEnd() function. Would that work?

**Comment by robertpiosik** [comment]
You can use MapController's `onReady` callback.

**Comment by Apollo108** [comment]
I use the FutureBuilder, where I pass mapController.onReady, but it never resolves... What am I doing wrong?
