### ISSUE TITLE
type 'LatLng' is not a subtype of type 'LocVeh' in type cast. how can i solve it properly? 

### ISSUE THREAD

**Issue by loonyfawn** [fleaflet/flutter_map#814]
Hello. 

I am writing an application that monitors the movement of cars (several cars) and I have an API that contains the latitude and longitude values. I want to put all these cars on the map simultaneously and watch them move in real time on the map. Is it possible? I'm trying to use **live_location.dart** from the **example**, but nothing seems to work. Only map loads, but FAB isn't working and it dosen't show not my, nor cars locations. 
Or is this package not meant for that? And I need to look for another ways more carefully? 

Thanks.

**Comment by ibrierley** [comment]
I don't see why not. You probably need to expand on "nothing seems to work". Maybe include a basic minimal example of code to look at.

**Comment by loonyfawn** [comment]
I am trying to get all moving cars on my map from API so i decided to fetch all markers using FutureBuilder, But when I do it, markers are static and they don't  move on the map smoothly. 

```
 FutureBuilder<List<LocVeh>>(
              future: futureLoc,
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  listDir = snapshot.data;
                  listDir.forEach((element) {
                    _markers = listDir.map((e) =>
                        Marker(
                            point: latLng.LatLng(e.uLong, e.uLat),
                            width: 5,
                            height: 5,
                            builder: (ctx) =>
                                Icon(Icons.directions_train_outlined)
                        )).toList(growable: true);
                  });
                  return Flexible(
                    child: FlutterMap(
                      mapController: _mapController,
                      options: MapOptions(
                        center: latLng.LatLng(48.707103, 44.516939),
                        zoom: 5.0,
                      ),
                      layers: [
                        TileLayerOptions(
                          urlTemplate:
                          'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                          subdomains: ['a', 'b', 'c'],
                    
                          tileProvider: NonCachingNetworkTileProvider(),
                        ),
                        MarkerLayerOptions(markers: _markers
                        ),
                      ],),
                  );
                } else if (snapshot.hasError) {
                  return Text("${snapshot.error}");
                }
                return Center(
                  child: CircularProgressIndicator(
                    backgroundColor: Colors.green,
                    strokeWidth: 2,
                  ),
                );
              }),
```

also I am trying to understand how I  can get the transport realtime location.  Ss I andrestood I need to use location package to call lat and long from API. May be I am the dumbest man on the Earth and miss something and I shouldn't do something like this.  I have read a lot of articles and example code, and everybody said that I should use location_package to get current transport location on the map. And after days of seraching and learning there are 2 options appear: 1)markers are static (so how can I make them move in real time not by hardcoded animation?); 2) they don't show on map but map loads perfectly. 

Now the full code is: 

```
class _LiveLocationPageState extends State<LiveLocationPage> {

\\in _currentlocation I put my LocVeh class which is from API
  LocVeh _currentLocation;

  MapController _mapController;

//here I call myAPI and list of Markers
  List<LocVeh> listDir; 
  List<Marker> _markers;
  Future<List<LocVeh>> futureLoc;


  bool _liveUpdate = true;
  bool _permission = true;

  String _serviceError = '';


  final loc.Location _locationService = loc.Location();
  var interActiveFlags = InteractiveFlag.all;



  @override
  void initState() {
    super.initState();
    futureLoc = fetchLoc();
    _mapController = MapController();
    initLocationService();
  }

  void initLocationService() async {
    await _locationService.changeSettings(
      accuracy: loc.LocationAccuracy.high,
      interval: 1000,
    );

    LocVeh location;
    bool serviceEnabled;
    bool serviceRequestResult;

    try {
      serviceEnabled = await _locationService.serviceEnabled();

      if (serviceEnabled) {
        var permission = await _locationService.requestPermission();
        _permission = permission == PermissionStatus.granted;

        if (_permission) {
          location = (await _locationService.getLocation()) as LocVeh;
          _currentLocation = location;
          _locationService.onLocationChanged.listen((loc.LocationData result) async {
            if (mounted) {
              setState(() {
                _currentLocation = result as LocVeh;

                // If Live Update is enabled, move map center
                if (_liveUpdate) {
                  _mapController.move(
                      latLng.LatLng(_currentLocation.uLong,
                          _currentLocation.uLat),
                      _mapController.zoom);
                }
              });
            }
          });
        }
      } else {
        serviceRequestResult = await _locationService.requestService();
        if (serviceRequestResult) {
          initLocationService();
          return;
        }
      }
    } on PlatformException catch (e) {
      print(e);
      if (e.code == 'PERMISSION_DENIED') {
        _serviceError = e.message;
      } else if (e.code == 'SERVICE_STATUS_ERROR') {
        _serviceError = e.message;
      }
      location = null;
    }
  }

  @override
  Widget build(BuildContext context) {
    latLng.LatLng currentLatLng;

    if (_currentLocation != null) {
      currentLatLng =
          latLng.LatLng(_currentLocation.uLong, _currentLocation.uLat);
    }
```
My API

```
class LocVeh {
  LocVeh({
    this.uLat,
    this.uLong,
    this.uSpeed,
  });

  int ttId;
  double uLat;
  double uLong;
  int uSpeed;

```


I think I don't notice something obvious. Or using this example absolutly wrong. 

Thank you for replying.

**Comment by ibrierley** [comment]
Hopefully someone else can help a bit more, as I'm busy at work, but one thing that's making me scratch my chin a bit (i.e it may be perfectly fine, but I'd have to spend a bit of time checking, it may also be totally unrelated :D)...

I note you have your FlutterMap inside your location FutureBuilder (intuitively this _may_ feel odd, but it depends and may be fine). In your case though, you seem to have a fixed center and zoom (eg latLng.LatLng(48.707103, 44.516939))...

So is the map being moved, a location update comes in, and then resets fluttermap back to it's initial state. Normally I would expect to see the center and zoom be variables, eg from _currentLocation ?

It may just be the layout of the code which is confusing me though, as it's split up a bit and harder to follow.

Either way, I would add some console debug outputs into your build methods, futurebuilder etc. See if things are happening in the order that you think they are, and your latlongs etc are what you think. Remember, build methods can be called any time even when you don't expect it.

**Comment by kengu** [comment]
@loonyfawn It seems like you are forcing a type cast on `LatLng` to `LocVeh` in multiple places. This will only work if `LocVeh` is a subtype of `LatLng` which dart it telling you is not the case. 

Example
```
1   // Until currentLocation is initially updated, Widget can locate to 0, 0
2   // by default or store previous location value to show.
4   if (_currentLocation != null) {
5     _currentLocation = LatLng(_currentLocation.uLat, _currentLocation.uLong) as LocVeh;
6   } else {
7    _currentLocation = LatLng(0, 0) as LocVeh;
8   }
```
where line 5 and 7 above will throw `type 'LatLng' is not a subtype of type 'LocVeh' in type cast`.
