### ISSUE TITLE
Is it possible to display Markerks selected/unselected state?

### ISSUE THREAD

**Issue by joao10martins** [fleaflet/flutter_map#815]
Is it possible to display Markers selected/unselected state?

What I mean is if it's possible to make a marker black color when selected and blue/some other color when it has not been selected.

So if I have 10 markers and I select one, it turns black whiles all the others are blue for example. And if I selected a different one, it should be automatically deselected and change back to blue.

Is this possible?

**Comment by ibrierley** [comment]
I think it's possible, but I'm not sure of anything in flutter_map to help with that, so it would be down to your own holding marker states and updating etc.

**Comment by joao10martins** [comment]
For example, can this be done with the help on `rebuild:` inside `MarkerLayerOptions`?
Because I am creating a `List<Marker>` and adding to the layer.

**Comment by ibrierley** [comment]
If you are updating the list of markers with the correct colours etc on a press already, then the rest should update whenever you do a setState, ie fluttermap will rebuild and the markers will get rebuilt as well.

**Comment by joao10martins** [comment]
`List<Marker> _buildMarkers() {
    var markers = List<Marker>.empty(growable: true);
    widget.hotelResults.forEach((hotel) {
      markers.add(
        Marker(
          width: 60.0,
          height: 35.0,
          anchorPos: AnchorPos.align(AnchorAlign.top),
          point: new LatLng(hotel.geo.latitude, hotel.geo.longitude),
          builder: (ctx) => LodgingMapMarker(
              currency: hotel.currency.symbol,
              price: _getCheapestRoom(hotel.roomData),
          ),
        ),
      );
    });
    return markers;
  }`

Here's the code that creates the markers. I really am confused as to how to do something so simple.

**Comment by joao10martins** [comment]
This implementation also doesn't work.

```
List<Marker> _buildMarkers() {
    if(markers.isNotEmpty) markers.clear();
    for(int i=0; i<widget.hotelResults.length; i++) {
      markers.add(
        Marker(
          width: 60.0,
          height: 35.0,
          anchorPos: AnchorPos.align(AnchorAlign.top),
          point: new LatLng(widget.hotelResults[i].geo.latitude, widget.hotelResults[i].geo.longitude),
          builder: (ctx) => GestureDetector(
            child: LodgingMapMarker(
              currency: widget.hotelResults[i].currency.symbol,
              price: _getCheapestRoom(widget.hotelResults[i].roomData),
            ),
            onTap: () {
              setState(() {
                if(previousMarker != null) {
                  markers.removeAt(previousMarkerIndex);
                  markers.insert(previousMarkerIndex, _buildMarker(previousMarker, primaryColor));
                }
                var selectedMarker = widget.hotelResults[i];
                previousMarker = selectedMarker;
                previousMarkerIndex = i;
                markers.removeAt(i);
                markers.insert(i, _buildMarker(selectedMarker, Colors.black));
              });
            },
          ),
        ),
      );
    }
    return markers;
  }
```

**Comment by ibrierley** [comment]
print out the value of "i" each tap, see if it is what you think it is each tap. Hard to tell at a glance, but you may need a closure to preserve the value in your onTap functions.

**Comment by TesteurManiak** [comment]
You can easily do this by using the package [map_controller](https://pub.dev/packages/map_controller) in complement which provides `StatefulMarker`.
