### ISSUE TITLE
How to correctly configure the PanBoundaries on an offline map correctly

### ISSUE THREAD

**Issue by DiMiTriFrog** [fleaflet/flutter_map#816]
After doing the whole process and getting the map in .mbtiles and converting all this into {z} {x} {y} directories, when I start the project I get the error of. Ex:  Unable to load asset: assets/map/and/13/4357/2520.png

The problem is that the code is trying to find coordinates on images that do not exist. I think that the limits and the center of the map are well delimited, I have extracted the points from OpenStreetMaap, but there are failures looking for the variable {y}.

Do you know where the problem could be?

```
FlutterMap(
                options: MapOptions(
                  center: LatLng(56.704173, 11.543808),
                  minZoom: 12.0,
                  maxZoom: 14.0,
                  zoom: 13.0,
                  swPanBoundary: LatLng(56.6877, 11.5089),
                  nePanBoundary: LatLng(56.7378, 11.6644),
                ),
                layers: [
                  TileLayerOptions(
                    tileProvider: AssetTileProvider(),
                    maxZoom: 14.0,
                    urlTemplate: 'assets/map/anholt_osmbright/{z}/{x}/{y}.png',
                  ),
                ],
              )
```

**Comment by Swepilot** [comment]
Have you correctly added the map folder to the pubspec.yaml file?

**Comment by DiMiTriFrog** [comment]
> Have you correctly added the map folder to the pubspec.yaml file?

Yes. The problem occurs because the code tries to search for images that do not exist

**Comment by ibrierley** [comment]
Why is it looking for the directory "and" in the url there ?

eg assets/map/and/13/4357/2520.png and not assets/map/anholt_osmbright/
13/4357/2520.png

I may be misunderstanding something there tho...

**Comment by Swepilot** [comment]
> > Have you correctly added the map folder to the pubspec.yaml file?
> 
> Yes. The problem occurs because the code tries to search for images that do not exist

OK so what you are saying is that when you created the directory structure and files from Mbtiles no ./13/4357/2520.png was created?

**Comment by DiMiTriFrog** [comment]
> Why is it looking for the directory "and" in the url there ? eg assets/map/and/13/4357/2520.png and not assets/map/anholt_osmbright/ 13/4357/2520.png I may be misunderstanding something there tho...
> […](#)

Because the name of my map is "and"

**Comment by DiMiTriFrog** [comment]
> > > Have you correctly added the map folder to the pubspec.yaml file?
> > 
> > 
> > Yes. The problem occurs because the code tries to search for images that do not exist
> 
> OK so what you are saying is that when you created the directory structure and files from Mbtiles no ./13/4357/2520.png was created?

Yes, but I think that image is not part of the exported map.

**Comment by DiMiTriFrog** [comment]
I fixed using the -tsm when I exported the .mbtiles to .png. All right!

**Comment by KaliFuckers** [comment]
I'm using qgis to export to png but i have this. Somebody help me please
![Captura de pantalla (1)](https://user-images.githubusercontent.com/26528044/111671388-476a1480-87ef-11eb-93dd-26153a2d0558.png)
