### ISSUE TITLE
Flutter Map is not changing the map image

### ISSUE THREAD

**Issue by rafaelcb21** [fleaflet/flutter_map#817]
I am using the flutter_map and when updating the latitude and longitude of the map, Marker changes however the map image does not change.

    import 'package:flutter/material.dart';
    import 'package:flutter_map/flutter_map.dart';
    import 'package:latlong/latlong.dart';

    void main() {
      runApp(MyApp());
    }

    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Flutter Map',
          home: MyHomePage(title: 'Flutter Demo Map Page'),
        );
      }
    }

    class MyHomePage extends StatefulWidget {
      MyHomePage({Key key, this.title}) : super(key: key);

      final String title;

      @override
      _MyHomePageState createState() => _MyHomePageState();
    }

    class _MyHomePageState extends State<MyHomePage> {
     
      double lat;
      double long;

      @override
      void initState() {
        super.initState();
        lat = 25.7751;
        long = -80.2105;
      }

      @override
      void dispose() {
        super.dispose();
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: Stack(
            children: <Widget> [
              new FlutterMap(
                options: new MapOptions(
                  minZoom: 10.0,
                  center:  new LatLng(
                    lat,
                    long,
                  )
                ),
                layers: [
                  new TileLayerOptions(
                    urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    subdomains: ['a','b','c']
                  ),
                  new MarkerLayerOptions(
                    markers: [
                      new Marker(
                        width: 45.0,
                        height: 45.0,
                        point: new LatLng(
                          lat,
                          long,
                        ),
                        builder: (context)=> new Container(
                          child: IconButton(
                            icon: Icon(Icons.add_location),
                            onPressed: () {
                              print('Marker tapped!');
                            }
                          )
                        )
                      )
                    ]
                  )
                ]
              ),
            ],
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () {
              setState(() {
                lat = 34.0898373;
                long = -118.5010028;
              });
            },
            tooltip: 'Increment',
            child: Icon(Icons.add),
          ),
        );
      }
    }

**Comment by Swepilot** [comment]
If you want to change the position (and/or zoom) of the map you can use a `MapController` and reference that in the `FlutterMap`. Then you use the mapController object's methods to control the map.
https://pub.dev/packages/map_controller

**Comment by rafaelcb21** [comment]
In fact, it was necessary to use `MapController` to insert new markers and change the center.

Follow the code working:

    import 'package:flutter_map/flutter_map.dart';
    import 'package:flutter_map/plugin_api.dart';
    import 'package:flutter/material.dart';
    import 'package:latlong/latlong.dart';

    void main() {
      runApp(MyApp());
    }

    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Flutter Map',
          home: MyHomePage(title: 'Flutter Demo Map Page'),
        );
      }
    }

    class MyHomePage extends StatefulWidget {
      MyHomePage({Key key, this.title}) : super(key: key);
      MapController mapController;

      final String title;

      @override
      _MyHomePageState createState() => _MyHomePageState();
    }

    class _MyHomePageState extends State<MyHomePage> {
     
      static LatLng london = LatLng(51.5, -0.09);
      static LatLng los_angeles = LatLng(34.0522342, -118.2436849);

      MapController mapController;

      var _markers = <Marker>[];

      @override
      void initState() {
        super.initState();
        mapController = MapController();
        _markers.add(createMarker(london));
      }

      @override
      void dispose() {
        super.dispose();
      }

      Marker createMarker(LatLng latLng) {
        return Marker(
          width: 80.0,
          height: 80.0,
          point: latLng,
          builder: (ctx) => Container(
            child: IconButton(
              icon: Icon(Icons.add_location),
              onPressed: () {
                
              }
            ),
          ),
        );
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: Stack(
            children: <Widget> [
              new FlutterMap(
                mapController: mapController,
                options: new MapOptions(
                  minZoom: 0.0,
                  center:  london,
                ),
                layers: [
                  new TileLayerOptions(
                    urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    subdomains: ['a','b','c']
                  ),
                  new MarkerLayerOptions(markers: _markers)
                ]
              ),
            ],
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () {
              setState(() {
                _markers.clear();
                _markers.add(createMarker(los_angeles));
                mapController.move(los_angeles, 9.0);
              });
            },
            tooltip: 'Increment',
            child: Icon(Icons.add),
          ),
        );
      }
    }
