### ISSUE TITLE
get bounding box onTap

### ISSUE THREAD

**Issue by icangku** [fleaflet/flutter_map#822]
how to get bounding box onTap on a WMSTileLayer? or how to get bounding box from onTap of the map, I've been figuring out returning bounding box from LatLng but it seems to need a list of LatLng,

**Comment by robertpiosik** [comment]
Have you tried getting bounds from your map controller?

**Comment by icangku** [comment]
i dont know how to do it. can u give me an example please?

**Comment by robertpiosik** [comment]
When you instantiate FlutterMap widget, you're assigning MapController to it. This is an object that stores current map state such as bounding box.
