### ISSUE TITLE
Map gets super laggy when there are a lot of Markers

### ISSUE THREAD

**Issue by TheLastGimbus** [fleaflet/flutter_map#824]
Hi there!

I am currently making an app which will have *a lot of* markers - around 4000 spread across whole country. After some testing, it got obvious that all of this gets super laggy

When I use all 3.5k markers and zoom on area with *no markers at all*, and start dragging the map, I get ~12 fps, on *phisical Android tablet in `profile` mode*

### After some debugging, `print()`ing and `Stopwatch()`ing, I traced which parts use the most time:

In `lib/src/layer/marker_layer.dart` -> `MarkerLayer` -> `build()`, there is a `for-loop` that iterates over all given `Markerks`:
https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/layer/marker_layer.dart#L130

#### The whole thing was taking ~25ms, and with `Stopwatch()`, I traced which parts of loop use the most time:
```dart
// I did it like this:
int sumStep = 0;
for(var i in list){
  var w = Stopwatch()..start();
  i.someStep();
  sumStep += w.elapsedMicroseconds();
  w.reset();
  // Of course, some precision is lost, because some steps take 1.something microsecond
}
print('Step: $sumStep');  // Summed microseconds
```
This was taking around 7500 us:
https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/layer/marker_layer.dart#L131

This 3600:
https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/layer/marker_layer.dart#L132-L133

And the rest around 0:
https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/layer/marker_layer.dart#L140-L152

### So I started to dig into `.project()`:
https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/map/map.dart#L417-L420

https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/geo/crs/crs.dart#L26-L34

`this.scale()` and `transformation.transform()` don't seem to be expensive - they are only some basic calculations...

So, `projection.project`:
https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/geo/crs/crs.dart#L450-L456

https://github.com/maRci002/proj4dart/blob/7eb11da840ce21c78c017e0a89ee0332ba5a60e3/lib/src/classes/projection.dart#L152

Okay... this ^ is *big*, and not even a part of this repo, so I don't think we can do anything about it...

# Conclusions
While re-building `MarkerLayer` (which happens constantly while dragging the map), we are doing some expensive calculations, which slow down the whole map - that is, calculating some `position` from `LatLng`

// I didn't dig into `pos.multiply` (step which was taking 3600us), and I don't really know what it's doing...

I'm fresh into this project and I don't know much about mapping, but it seems like we could somehow cache just the `projection`, and apply only `scale` and `transformations` - since only them *really change* when you drag the map

(This generally seems related #768, but discussion there got kinda chaotic, not knowing what issue actually was, so I'm making this separate)

**Comment by robertpiosik** [comment]
My workaround to this issue was filtering markers based on current map boundaries.

**Comment by TheLastGimbus** [comment]
Wait, how couldn't I see this before:

In whole loop we:

https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/layer/marker_layer.dart#L131-L142

1. Calculate some `.project`
2. Then some `.multiplyBy`
3. Then `pixelPos - something` // This one should be light
/// Which, from my measurements, all of this can take even 30ms at 5000 makrers
AND THEN
4. `!_boundsContainsMarker`:
https://github.com/fleaflet/flutter_map/blob/f09b193505ad31eb496b99a379346d99ec944cc7/lib/src/layer/marker_layer.dart#L113-L114

Same `.project` that took us so long before - just to dismiss previous calculations if markers is not visible

@robertpiosik this diservers much more than a workaround :flushed:

**Comment by ibrierley** [comment]
Yes, that's possibly a good optimisation. Thinking out loud, I'm actually wondering if that could be cached for each zoom level, as we're possibly doing the same map project for each point/zoom each frame ? (would need to verify and test that)

**Comment by TheLastGimbus** [comment]
@ibrierley a zoom level is a double, soooooo I don't know how this would go...

But, even caching it until zoom changes would be better than nothing...

**Comment by ibrierley** [comment]
Just thinking out loud a bit more on other optimisations (unfortunately I'm not near a PC I can test on flutter_map for a while), if bounds checking is optimally being done the wrong way around...currently we project every marker point, take the width/height, and do a basic boundary check. The slow bit being the project ?

Could we do the boundary checking on latlongs, not on screenprojected points. So unproject the map boundary corners (they may actually be already available as map.bounds?) to latlongs (so only has to be done once per frame). Figure out the marker delta latlongs to account for width/height for the marker, and calculate (if all the markers are the same, as an optional param that width/height latlong delta could be cached). Then you don't need to do any marker projections at all ?

Not entirely sure if I'm making sense and there's no flaws :D.

**Comment by ibrierley** [comment]
hmm maybe there's an issue with the calculation of the marker widths and height not taking into account the curvature or something, so maybe a good reason it's not done like that, but maybe it could be a useful custom pre-culling of points by someone when creating their marker lists.

**Comment by rorystephenson** [comment]
It's not an answer to your question directly but an alternative solution is to use marker clustering (see the clustering plugin listed in the README).

I have less markers (~1300) but it is very fast.

**Comment by TheLastGimbus** [comment]
The problem is that, even with markers clustering, map lags even when there are no markers visible at all

I currently fixed it in my fork and I'm temporary using it unitl it gets merged

**Comment by robertpiosik** [comment]
Indeed, clustering doesn't make any difference to perf.

@TheLastGimbus maybe providing a 60fps comparison gif might help gaining some attention

From my experience, original leaflet js deals with thousands of markers very well in the browser, though `flutter_map` lacks in this area significantly.

**Comment by TheLastGimbus** [comment]
> 60fps comparison gif 

SEE? THIS IS HOW BAD THIS IS!!! MERGE THIS TO STOP THIS CIRCUS :clown_face: 

I love this :heart_eyes: :laughing: 

> original leaflet js deals with thousands of markers very well

This keeps scratching my head. How do some web devs have their maps filled with markers, running 60fps in browser on my shitty phone, meanwhile "super native optimized Flutter cool framework" can't do >100 displayed at once :confounded: 

Maybe doing some "direct Canvas painting magic" would help, but I have 0 motivation to try this now - maybe some day as extra plugin for this

**Comment by Mondonno** [comment]
Was it actually gotten fixed?

**Comment by TesteurManiak** [comment]
Hi @Mondonno, performances of the package have improved a lot since the last comment, we even have a ["Many Markers" example](https://demo.fleaflet.dev/many_markers) that showcases that event with thousands of markers the map is running quite smoothly.
