### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by AyushBherwani1998** [fleaflet/flutter_map#829]
One of our side project uses this library, would be happy to help to migrate to null safety @johnpryan

**Comment by AyushBherwani1998** [comment]
There are few blockers 

flutter_image  is deprecated and no longer maintained under Flutter org.                
latlong is archived and is no longer maintained.                              
positioned_tap_detector has been discontinued                
proj4dart is not yet migrated to sound null safety.

**Comment by andreystavitsky** [comment]
For latlong here is active pull request
https://github.com/fleaflet/flutter_map/pull/750

**Comment by aytunch** [comment]
in order for migrating to Flutter 2.0 we will need this library to be null safe. This is a one of a kind package which lets Flutter community to use their beloved widgets as markers. @johnpryan do you have any strategy for this? @AyushBherwani1998 thanks for listing the deprecated dependencies. It might be a good starting point before nnbd migration. I think flutter_image and latlong are not going to be hard to replace. I don't know what proj4dart is for and if there is a replacement for positioned_tap_detector.

**Comment by kevin-lot** [comment]
For "latlong".
What about "latlng" package already null safety compatible ?

nb: I didn't check the code https://github.com/xclud/flutter_latlng.

**Comment by JAICHANGPARK** [comment]
```

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_map
 - package:latlong
 - package:logging
 - package:validate
 - package:proj4dart
 - package:tuple
 - package:positioned_tap_detector
 - package:flutter_image
 - package:quiver
 - package:mgrs_dart
 - package:wkt_parser
 - package:unicode
 - package:lists


```

**Comment by jpeiffer** [comment]
It looks like `latlong` was abandoned but someone has forked that and added Null Safety:
https://pub.dev/packages/latlong2

**Comment by attex** [comment]
logging has been updated to null-safety 
tuple has a prerelease for null-safety
quiver has been updated to null-safety
unicode has been updated to null-safety

**Comment by arsamme** [comment]
I think this repo is archived and I gonna fork and publish NS version of flutter_map.

**Comment by aytunch** [comment]
@arsamme thanks. But I do hope it is not the case for flutter_map. I see the owner @johnpryan active from time to time. I would love to hear his opinion about the future of this great package

**Comment by arsamme** [comment]
@aytunch I hope too. But he didn't respond to any issue for a long time.

**Comment by o1dnik** [comment]
@arsamme @aytunch there's a call for maintainers on the top of the issues list on this repo. I assume someone else has to join as an active maintainer so that the package get's timel yupdates. Is there another package available out there or downgrading to pre-null-safety version is one of the ways you manage the production-ready apps ?

**Comment by aytunch** [comment]
@o1dnik I have missed the call for maintainers issue, thanks for pointing it out. I have been using this library from the very early days. And lately @maRci002 and @lpongetti  have done very useful and successful contributions among other developers. As now understanding that @johnpryan is busy with other stuff, I would like to know from you  two friends if you have an agenda on this libraries null safety upgrade, maintenance and new features? Thanks.

Lastly, I would like to remind to the developers and marketers of several Map provider companies which are supported by this package that if this package is not maintained anymore, we would most likely change to another provider which offer similar functionality using their official packages. So it would be great to get some help from your side too:)

**Comment by arsamme** [comment]
@aytunch I've submitted call for maintainers form and no answers yet (after about two weeks)

**Comment by maRci002** [comment]
I am going to migrate proj4dart to nullsafety including mgrs_dart / wkt_parser packages.

**Comment by aytunch** [comment]
Great to hear from you @maRci002 

I am just gathering the info scattered throughout this issue so we know where we are in terms of Bull Safety status of Flutter_map's dependencies. Thanks everyone who shared info here (I haven't checked the packages just collected the info in the issue so if there are new info, please copy paste the table and reply accordingly):



- [ ]  ❓package:latlong (https://pub.dev/packages/latlong2 someone has forked that and added Null Safety) There is an alternative package called latlng which has null safety also.
- [ ]  ✅ package:logging
- [ ]  ❌ package:validate
- [ ]  ⚠️ package:proj4dart
- [ ]  ♻️ package:tuple (prerelease null safety)
- [ ]  ❌ package:positioned_tap_detector (discontinued)
- [ ]  ❌ package:flutter_image (deprecated and no longer maintained under Flutter org)
- [ ]  ✅ package:quiver
- [ ]  ⚠️ package:mgrs_dart
- [ ]  ⚠️ package:wkt_parser
- [ ]  ✅ package:unicode
- [ ]  ❌ package:lists

**Comment by arsamme** [comment]
> Great to hear from you @maRci002
> 
> I am just gathering the info scattered throughout this issue so we know where we are in terms of Null Safety status of Flutter_map's dependencies. Thanks everyone who shared info here (I haven't checked the packages, just collected the info in the issue so if there are new updates, please copy paste the table and reply accordingly):
> 
> * [ ]   ✅ package:logging
> * [ ]   ✅ package:quiver
> * [ ]   ✅ package:unicode
> * [ ]   ♻️ package:tuple (prerelease null safety)
> * [ ]   ⚠️ package:proj4dart (on maRci002's radar)
> * [ ]   ⚠️ package:mgrs_dart (on maRci002's radar)
> * [ ]   ⚠️ package:wkt_parser (on maRci002's radar)
> * [ ]   ❓package:latlong (https://pub.dev/packages/latlong2 someone has forked that and added Null Safety) There is an alternative package called latlng which has null safety also.
> * [ ]   ❌ package:lists
> * [ ]   ❌ package:validate
> * [ ]   ❌ package:positioned_tap_detector (discontinued)
> * [ ]   ❌ package:flutter_image (deprecated and no longer maintained under Flutter org)

lists is migrated

**Comment by JaffaKetchup** [comment]
Hi all,
Another thing that may need to be migrated are the multiple plugins (not sure if this is out of scope, however). Also, before publishing a new version as @arsamme [suggested](https://github.com/fleaflet/flutter_map/issues/829#issuecomment-797865380) (good idea), it may also be a good idea to merge some pull requests (again this might be out of scope), such as #564, #810, #582 & #577. This would immediately boost the new package and make it even better than before.

Thanks for all your hard efforts, I really appreciate it, even though I am still in full time education, I program/code as much as possible in my spare time :).

**Comment by arsamme** [comment]
@JaffaKetchup Unfortunately author of package is nit responding and I think there is no way for merging PRs. In my opinion best solution for now is forking this repo and publishing migrated package, then adding other features.

**Comment by JaffaKetchup** [comment]
@arsamme Yeah, sorry should have clarified. I meant after creating the new GitHub repo but before publishing on pub.dev.

**Comment by arsamme** [comment]
@JaffaKetchup Great. So I'll notify you here on updates.

**Comment by erickhaendel** [comment]
Great, awaiting for updates.

**Comment by johnpryan** [comment]
I have added some additional maintainers to help with maintenance.

**Comment by arsamme** [comment]
@johnpryan nice. Is there any eta on when we will get nnbd version?

**Comment by johnpryan** [comment]
@arsamme no, we need to wait for other packages to upgrade first.

**Comment by kengu** [comment]
@johnpryan / @maRci002 - what do you think of replacing lat_long with maps_toolkit, ref #750? The change looks simple enough, so does the new dependency. The question is do we need a dependency for modelling LatLng when there is no commonly used library for LatLng in dart/flutter community afaics?

**Comment by maRci002** [comment]
@kengu that package doesn't support nullsafe yet, however it has a much safer hashCode than the current one.
You are right we could just create our own LatLng class since we don't use any of it's utility functions.

**Comment by johnpryan** [comment]
The ideal solution is to use a popular, well maintained package so users don't have to convert the types too often. I'm not opposed to including a `LatLng` type either. Switching to a new package or type will be a breaking change, either way.  There is also a fork of `package:latlong` called `latlong2` that has been upgraded to null safety: https://pub.dev/packages/latlong2

**Comment by arsamme** [comment]
I've migrated positioned_tap_detector.
Author of proj4dart said he will migrate the package in this week. Check [here](https://github.com/maRci002/proj4dart/issues/5).
`lat_long` and `flutter_image` are the only not migrated packages.

**Comment by kengu** [comment]
@arsamme thanks for the the contribution, #843 is merged to master.

**Comment by aytunch** [comment]
@arsamme Thanks for positioned_tap_detector2. I think next to `lat_long` and `flutter_image`, there is validate before all dependencies are null safe. We are very close to upgrade to Flutter 2.0 :) Do anyone know if there are any work started for `flutter_image`?

**Comment by arsamme** [comment]
@aytunch There is active PR for flutter_image and I've asked for validate if they have any plans for migrating. Check [here](https://github.com/MikeMitterer/dart-validate/issues/6)

**Comment by kengu** [comment]
I've reviewed [latlng2](https://pub.dev/packages/latlong2) and I think this is all things considered the right way forward.

**Comment by rubber-duck** [comment]
Considering how core latlong type is to this library and fleaflet is already an organisation - wouldn't it make more sense to fork latlong2 under fleaflet and publish it under flutter_map namespace (ie. flutter_map_latlong) ?  

Sounds like (relatively) the least work while avoiding the same problem down the line.

**Comment by aytunch** [comment]
@rubber-duck it can be maintained inside of flutter_map in the future. The maintainers can decide on it. 
However I think our priority should be to make flutter_map null-safety complaint as soon as possible. A lot of developers can not migrate to Flutter 2.0 because of flutter_map not supporting null-safety. So the quickest way is the right way for now:)

**Comment by rubber-duck** [comment]
I'm using Flutter 2.0 with flutter_map without any issues, I'm just not using null-safety yet. Using latlong2 and then forking and changing again just for the sake of having a release a few days sooner seems hacky to me - forking and republishing doesn't sound like that much work to justify such hacks.

**Comment by josxha** [comment]
I think it really depends if @jifalops has planned to do a long time support for latlong2.  There isn't really the need for two published versions of his null-safety version of the package. 
I agree with @rubber-duck, that it would be best to focus on providing the developers, with a null-safety version of this package.

**Comment by escamoteur** [comment]
Hi,

because I need this library in a null safe version I migrated it today ignoring the currently not migrated packages:

    package:proj4dart
    package:mgrs_dart
    package:wkt_parser
    package:unicode
    package:lists

This is a migration to unsound null safety. So far I couldn't see problems, so I expect as soon as the missing packages are available that should be fine.
At some places I wasn't sure if previous nullable values should still be nullable, I left the null checks despite having changed the types to nonnullables and added a TODO comment.

I hope this is in your sense and you can use it, it was a whole day work :-)

**Comment by attex** [comment]
@escamoteur is it possible to get your Null-safety-version somehow?

**Comment by josxha** [comment]
@attex Change the `flutter_map` dependency in your `pubspec.yaml` with the following lines:

```yaml
flutter_map:
    git:
      url: git://github.com/escamoteur/flutter_map.git
      ref: nullsafety
```

There might be an warning. It so, just add `publish_to: none` below the app description.

**Comment by attex** [comment]
@josxha  thank you!

**Comment by tazik561** [comment]
> @attex Change the `flutter_map` dependency in your `pubspec.yaml` with the following lines:
> 
> ```yaml
> flutter_map:
>     git:
>       url: git://github.com/escamoteur/flutter_map.git
>       ref: nullsafety
> ```
> 
> There might be an warning. If so, just add `publish_to: none` below the app description.

I used but I got this error :

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building RawGestureDetector(state: RawGestureDetectorState#23abb(gestures: [tap, long press, scale])):
type '_ControllerStream<LatLng?>' is not a subtype of type 'Stream<LatLng>' of 'stream'

The relevant error-causing widget was
FlutterMap
lib/…/main_map/main_map_view.dart:28
When the exception was thrown, this was the stack
#2      _TileLayerState._initThrottleUpdate
package:flutter_map/…/layer/tile_layer.dart:515
#3      _TileLayerState.initState
package:flutter_map/…/layer/tile_layer.dart:446
#4      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:4632
#5      ComponentElement.mount
package:flutter/…/widgets/framework.dart:4469
#6      Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
```

**Comment by maRci002** [comment]
`proj4dart` has been [migrated to nullsafety](https://pub.dev/packages/proj4dart).

And following dependencies are no longer problem
```
package:mgrs_dart
package:wkt_parser
package:unicode
package:lists
```

**Comment by josxha** [comment]
@tazik561 Thanks for you investigation. I haven't used the version by @escamoteur myself yet. There is an active pull request for this https://github.com/fleaflet/flutter_map/pull/851. Maybe you can fix the error there directly?

**Comment by escamoteur** [comment]
will update this

**Comment by tazik561** [comment]
> will update this

I adde pull request https://github.com/escamoteur/flutter_map/pulls

**Comment by aytunch** [comment]
> `proj4dart` has been [migrated to nullsafety](https://pub.dev/packages/proj4dart).
> 
> And following dependencies are no longer problem
> 
> ```
> package:mgrs_dart
> package:wkt_parser
> package:unicode
> package:lists
> ```

@maRci002 thanks for the conversions. So at this moment do flutter_map have any un-migrated dependencies?

**Comment by arsamme** [comment]
@aytunch I think flutter_image is left.

**Comment by aytunch** [comment]
@arsamme I just looked at `flutter_image`s repo and there is an active PR which seems to be under your radar. After it is migrated, what do we do for `flutter_map`?

**Comment by arsamme** [comment]
@aytunch 
Thanks @Ascenio, The PR for `flutter_image` is ready to merge and we are waiting for flutter team to review and merge.

**Comment by JaffaKetchup** [comment]
Hi, any news on this?

**Comment by escamoteur** [comment]
you currently can use my fork

**Comment by tazik561** [comment]
I don't know what is happening. I was working on my project about one month. I am using flutter map and almost my project is done, But I don't know, know why I got this error? 

```
Launching lib/main.dart on sdk gphone x86 in debug mode...
lib/main.dart:1
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:flutter_image

For solutions, see https://dart.dev/go/unsound-null-safety
```
I was working about one month !! and map worked but now I can't run project ?

**Comment by kengu** [comment]
> I don't know what is happening. I was working on my project about one month. I am using flutter map and almost my project is done, But I don't know, know why I got this error?
> 
> ```
> Launching lib/main.dart on sdk gphone x86 in debug mode...
> lib/main.dart:1
> Error: Cannot run with sound null safety, because the following dependencies
> don't support null safety:
> 
> - package:flutter_image
> 
> For solutions, see https://dart.dev/go/unsound-null-safety
> ```
> 
> I was working about one month !! and map worked but now I can't run project ?
> 
> How can I do with flutter_image?

I don't know for sure, but probably because you have upgraded to Flutter >= 2.0 and therefore is running with dart >=2.12, which requires all packages being null-safe. You can run you application with unsound null-safety by adding the commend 
```
// @dart=2.11
```
to `main.dart`

**Comment by tazik561** [comment]
> > I don't know what is happening. I was working on my project about one month. I am using flutter map and almost my project is done, But I don't know, know why I got this error?
> > ```
> > Launching lib/main.dart on sdk gphone x86 in debug mode...
> > lib/main.dart:1
> > Error: Cannot run with sound null safety, because the following dependencies
> > don't support null safety:
> > 
> > - package:flutter_image
> > 
> > For solutions, see https://dart.dev/go/unsound-null-safety
> > ```
> > 
> > 
> > I was working about one month !! and map worked but now I can't run project ?
> > How can I do with flutter_image?
> 
> I don't know for sure, but probably because you have upgraded to Flutter >= 2.0 and therefore is running with dart >=2.12, which requires all packages being null-safe. You can run you application with unsound null-safety by adding the commend
> 
> ```
> // @dart=2.11
> ```
> 
> to `main.dart`

My project was null safety and now it is null safety

**Comment by kengu** [comment]
@tazik561 Sorry, I can not say why without more information. Have you performed a flutter pub upgrade lately? This would force an upgrade of git://github.com/escamoteur/flutter_map.git which was updated 11h ago. Maybe @escamoteur have some insight here? The error indicates that package:flutter_image is not null-safe, which it should be.

**Comment by tazik561** [comment]
> @tazik561 Sorry, I can not say why without more information. Have you performed a flutter pub upgrade lately? This would force an upgrade of git://github.com/escamoteur/flutter_map.git which was updated 11h ago. Maybe @escamoteur have some insight here? The error indicates that package:flutter_image is not null-safe, which it should be.

I swear , I just increased `local_auth 1.1.3` from 1.1.0 and then run pub get. I have a question ? Now It is possible to use flutter-map with null safety? If your answer is no, Then how it is possible that I use for 13 days .On top I had a pull request https://github.com/fleaflet/flutter_map/issues/829#issuecomment-807003555 . After that I was using it.

**Comment by escamoteur** [comment]
My fault! When changing the flutter_image import to `dependency_overrides` I made a typo

**Comment by tazik561** [comment]
> My fault! When changing the flutter_image import to `dependency_overrides` I made a typo

Now, is OK ? Because I cloned flutter map null safety and flutter image null safety as a local package , Now I can run my application.

**Comment by aytunch** [comment]
@escamoteur Thanks for the null-safe fork. It saves the day:) However for future, when there are new features in the repo, this fork won't cut it. I would like to know if null-safe migration will be finished soon? This package is the last one in our project.

**Comment by escamoteur** [comment]
Oh, I thought it would have already merged into https://github.com/fleaflet/flutter_map/tree/issues-829-nullsafety

so that you no longer need my fork and that new feaures can be directly pushed there

**Comment by kengu** [comment]
@aytunch I've just finished moving @escamoteur's branch to [issues/829-nullsafety](https://github.com/fleaflet/flutter_map/tree/issues-829-nullsafety). See PR #870 which merges sound null-safety when [flutter_image is migrated](https://github.com/flutter/flutter_image/pull/22). 

If you can not wait for this to land on master, use the following dependency override

```
dependency_overrides:
  flutter_map:
    git:
      url: git://github.com/fleaflet/flutter_map.git
      ref: issues/829-nullsafety
```

**Comment by bramvbilsen** [comment]
> @aytunch I've just finished moving @escamoteur's branch to [issues/829-nullsafety](https://github.com/fleaflet/flutter_map/tree/issues-829-nullsafety). See PR #870 which merges sound null-safety when [flutter_image is migrated](https://github.com/flutter/flutter_image/pull/22).
> 
> If you can not wait for this to land on master, use the following dependency override
> 
> ```
> dependency_overrides:
>   flutter_map:
>     git:
>       url: https://github.com/fleaflet/flutter_map
>       ref: issues/829-nullsafety
> ```

Using the dependency override, I get the following build error:
```

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\bramv\DevTools\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\bramv\DevTools\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
Do you have the same result?

**Comment by josxha** [comment]
@bramvbilsen I think flutter_map isn't the problem here. There is a problem with gradle. Open the /android directory with e.g. Android Studio and try to build gradle there.

**Comment by barbalex** [comment]
> If you can not wait for this to land on master, use the following dependency override

This unfortunately does not work yet, as flutter_image is not null safe yet:

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:flutter_image

For solutions, see https://dart.dev/go/unsound-null-safety
3

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\alexa\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\alexa\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

I guess it will start working after flutter_image got updated 🙏

**Comment by josxha** [comment]
@barbalex Have a look into the provided link in the error message. 
Even though flutter_map has no complete sound null safety support yet because of the flutter_image dependency, you can run your app with **unsound null safety**: ```flutter run --no-sound-null-safety```
See: https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs

**Option 2** (if you don't want to run you're app with unsound null safety):
There is an open pull request that removes the flutter_image decendency. You can use it with:
```yaml
dependency_overrides:
  flutter_map:
    git:
      url: git://github.com/josxha/flutter_map.git
      ref: issues/829-nullsafety
```

**Comment by aytunch** [comment]
`flutter_image` null safety just got merged fyi everyone. Is there any other dependencies left for `flutter_map` to be sound null safe?

**Comment by josxha** [comment]
@aytunch Unfortunately not quite, flutter_image has been merged and moved to a new repository, but the version has not been released on pub.dev yet.
The new repository is: https://github.com/flutter/packages/tree/master/packages/flutter_image

However, I would like to point out my PR replacing flutter_image with http. This would make all packages with support for sound null safety. See: https://github.com/fleaflet/flutter_map/pull/894

**Comment by aytunch** [comment]
@josxha Thank you for https://github.com/fleaflet/flutter_map/pull/894 In the long run I think relying on http will be much safer and robust. Do you have any idea when your `http` PR be merged? And after it is merged, do we have any obstacles for sound null safety?

**Comment by MooNag** [comment]
@aytunch http is going to be a more robust solution. I made some noise in a new issue about releasing a new version but sometimes @johnpryan and the new maintainers are a bit slow on the catch-up to PRs. My guess is that null-safety and the http merge will be in the next week. I just checked the master branch and all other dependencies are null safe so there are no more blockers (assuming we remove flutter_image)

**Comment by kengu** [comment]
See my comment on #894. I think we should wait for flutter_image 4.0.1, which is now part of [flutter packages](https://github.com/flutter/packages). The [829-nullsafety](https://github.com/fleaflet/flutter_map/tree/issues/829-nullsafety) is now pointing to the [new location](https://github.com/flutter/packages/tree/master/packages/flutter_image) in flutter packages.

**Comment by JaffaKetchup** [comment]
This is great news, and I'm glad to see some progress 👍 .

Should the new release be 1.0.0 (or 2.0.0) however? This is because this is a potentially breaking change with huge code refactoring, and it kind of seems time for a major release.

**Comment by MooNag** [comment]
Caching should not be handled by the image provider like that. Check my post in #984 for info.

@JaffaKetchup it would likely be version 1.0.0. Any increase of the first number is indicating a significant breaking change.

**Comment by rorystephenson** [comment]
FWIW I opened an issue to ask for flutter_image to be published: https://github.com/flutter/flutter/issues/82900

**Comment by barbalex** [comment]
And flutter_image v4.0.1 was published: https://github.com/flutter/flutter/issues/82900#issuecomment-844000279

**Comment by kengu** [comment]
I'll update the branch tonight @barbalex 

 @johnpryan We are ready to merge shortly. Can you do the review soon?

**Comment by kengu** [comment]
flutter_image is now upgraded to latest version 4.0.1 in PR #870

**Comment by kamleshwebtech** [comment]
Still looking forward for Null Safety solution :)
