### ISSUE TITLE
Zooming and pannig is freezing when load GeoJson

### ISSUE THREAD

**Issue by raycastsant** [fleaflet/flutter_map#830]
Hello

I'm developing an application to load some shapes in geojson format Right now I'm just loading 1000 polygons. Everything is fine when the user zooms in, zoom out on android , but on the web when trying to pan the map (panning behavior) or zoom, it doesn't seem to move until 8 or 9 seconds ago.

Any helps? Thanks.

**Comment by maRci002** [comment]
`PolygonLayerOptions` has a porperty `polygonCulling` set it to `true` it may help. Anyway has your polygon holes?

**Comment by raycastsant** [comment]
Hi, thanks for your response. The polygons are fine, they do not have holes. The polygonCulling property is useful when zooming in close, but when zooming out and trying to move the map then it freezes. The strange thing is that I have tried it on android and it doesn't happen like that.
I'm thinking of using some geometry simplification method when the zoom is lower.

**Comment by kengu** [comment]
@raycastsant Could you try to make a simplified implementation that reproduces the problem and share it with us?

**Comment by raycastsant** [comment]
Yes of course. This my widget´s code:

`import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pedantic/pedantic.dart';
import 'package:geopoint/geopoint.dart'; 
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';
import 'package:geojson/geojson.dart';
import 'layersDisplayControl.dart';

class _BuildingsPageState extends State<BuildingsPage> {
    var _shapes = <Polygon>[];
    var infoLoaded = false;
    MapController controller;

    @override
    void initState() {
        controller = new MapController();

        _loadCityShapes().then( (_) => setInfoUpdated());

        super.initState();
    }

    void setInfoUpdated() {
        infoLoaded = true;
    }

    Future<void> _loadCityShapes() async {
        final data = await rootBundle.loadString('assets/city.json');
        final geojson = GeoJson();  
        
        Color c = Color.fromRGBO(253, 252, 195, 0.60);
        Color c2 = Color.fromRGBO(145, 62, 17, 0.60);
        geojson.processedPolygons.listen((GeoJsonPolygon poly) {
            final geoSerie = GeoSerie(
                type: GeoSerieType.polygon,
                geoPoints: <GeoPoint>[]
            );

            for (final serie in poly.geoSeries) {
                geoSerie.geoPoints.addAll(serie.geoPoints);
            }
             setState(() => {
                _shapes.add(Polygon(borderStrokeWidth: 0.8, color: c, borderColor: c2, points: geoSerie.toLatLng(ignoreErrors: true)))
            });
        });

        geojson.endSignal.listen((_) => geojson.dispose());
        unawaited(geojson.parseInMainThread(data));
    }

    @override
    Widget build(BuildContext context) {
        
        return Scaffold(
            body: FlutterMap(
                mapController: controller,
                options: MapOptions(
                    center: LatLng(51.9828176452276, 5.87265058785708),  
                    zoom: 15.5,
                    plugins: [
                        LayersDisplayControlPlugin(),
                    ],
                ),
                
                layers: [
                     TileLayerOptions(
                        urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                        subdomains: ['a', 'b', 'c']
                    ),
                    PolygonLayerOptions(
                        polygons: _shapes,
                    ),
                ],
                nonRotatedLayers: [
                    LayersDisplayControl(
                        minZoom: 15,
                        maxZoom: 26,
                        mini: true,
                        padding: 10,
                        alignment: Alignment.topLeft,
                    ),
                ],
            )
        );
    }
}

class BuildingsPage extends StatefulWidget {
  @override
  _BuildingsPageState createState() => _BuildingsPageState();
}
`

and **layersDisplayControl.dart** code:

`import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map/plugin_api.dart';


class LayersDisplayControl extends LayerOptions {
    final double minZoom;
    final double maxZoom;
    final bool mini;
    final double padding;
    final Alignment alignment;
    final Color zoomInColor;
    final Color zoomOutColor;
    final IconData zoomInIcon;
    final IconData zoomOutIcon;
    final IconData refreshIcon;
    static double currentZoom = 15.5;

    LayersDisplayControl({
        Key key,
        this.minZoom = 10,
        this.maxZoom = 25,
        this.mini = true,
        this.padding = 10,
        this.alignment = Alignment.topLeft,
        this.zoomInColor,
        this.zoomInIcon = Icons.zoom_in,
        this.zoomOutColor,
        this.zoomOutIcon = Icons.zoom_out,
        this.refreshIcon = Icons.sync_rounded,
    }) : super(key: key);
}

class LayersDisplayControlPlugin implements MapPlugin {
    LayersDisplayControlWidget control;

  @override
  Widget createLayer(LayerOptions options, MapState mapState, Stream<Null> stream) {
        if (options is LayersDisplayControl) {
            control = LayersDisplayControlWidget(options, mapState, stream);
            return control; 
        }
        throw Exception('Unknown options type for LayersDisplayControlPlugin: $options');
  }

  @override
  bool supportsLayer(LayerOptions options) {
    return options is LayersDisplayControl;
  }
}

class LayersDisplayControlState extends State<LayersDisplayControlWidget> {
    final LayersDisplayControl layerControlOpts;
    final MapState map;
    final Stream<Null> stream;
    final FitBoundsOptions options = const FitBoundsOptions(padding: EdgeInsets.all(8.0));
    bool showRooms;
   
    LayersDisplayControlState(this.layerControlOpts, this.map, this.stream);

    @override
    void initState() {
        super.initState();
        showRooms = true;
    }

    void zoomIn() {
        var bounds = map.getBounds();
        
        LayersDisplayControl.currentZoom = LayersDisplayControl.currentZoom + 0.3;

        if (LayersDisplayControl.currentZoom > layerControlOpts.maxZoom) {
            LayersDisplayControl.currentZoom = layerControlOpts.maxZoom;
        } 
        else {
            var centerZoom = map.getBoundsCenterZoom(bounds, options);
            map.move(centerZoom.center, LayersDisplayControl.currentZoom);
        }
    }

    void zoomOut() {
        var bounds = map.getBounds();
        LayersDisplayControl.currentZoom = LayersDisplayControl.currentZoom - 0.3;

        if (LayersDisplayControl.currentZoom < layerControlOpts.minZoom) {
            LayersDisplayControl.currentZoom = layerControlOpts.minZoom;
        } 
        else {
            var centerZoom = map.getBoundsCenterZoom(bounds, options);
            map.move(centerZoom.center, LayersDisplayControl.currentZoom);
        }
    }

    @override
     Widget build(BuildContext context) {
        return Align(
            alignment: layerControlOpts.alignment,
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                    Padding(
                        padding: EdgeInsets.only(
                            left: layerControlOpts.padding,
                            top: layerControlOpts.padding,
                            right: layerControlOpts.padding),
                        child: FloatingActionButton(
                            heroTag: 'zoomInButton',
                            mini: layerControlOpts.mini,
                            backgroundColor:
                                layerControlOpts.zoomInColor ?? Theme.of(context).primaryColor,
                            onPressed: () {
                                zoomIn();
                                setState(() {
                                    print('zoomIn'+LayersDisplayControl.currentZoom.toString());
                                });
                            },
                            child: Icon(layerControlOpts.zoomInIcon),
                        ),
                    ),
                    Padding(
                        padding: EdgeInsets.only(
                            left: layerControlOpts.padding,
                            top: layerControlOpts.padding,
                            right: layerControlOpts.padding),
                        child: FloatingActionButton(
                            heroTag: 'zoomOutButton',
                            mini: layerControlOpts.mini,
                            backgroundColor: layerControlOpts.zoomOutColor ??
                                Theme.of(context).primaryColor,
                            onPressed: () {
                                zoomOut();
                                setState(() {
                                    print('zoomOut '+LayersDisplayControl.currentZoom.toString());
                                });
                            },
                            child: Icon(layerControlOpts.zoomOutIcon),
                        ),
                    ),
                ],
            ),
        );
    }
}

class LayersDisplayControlWidget extends StatefulWidget {
    final LayersDisplayControl layerControlOpts;
    final MapState map;
    final Stream<Null> stream;

    LayersDisplayControlWidget(this.layerControlOpts, this.map, this.stream);

    @override
    LayersDisplayControlState createState() => LayersDisplayControlState(this.layerControlOpts, this.map, this.stream);
}
`

The **city.json** have 1050 polygons. I'm just making a test, becouse I need to load much more information.
On android results are fine, but not on the web platform.
Thanks in advance for your answer.

**Comment by kengu** [comment]
@raycastsant A bit hard to evaluate the code properly this way. I would be more efficient for us if you use [dartpad.dev](https://dartpad.dev/?null_safety=true) and share the city.json file also
