### ISSUE TITLE
Remove background above and below

### ISSUE THREAD

**Issue by PaoloP98** [fleaflet/flutter_map#831]
Hi there is a way to prevent vertical scroll outside of the map?
I don't want to see the grey background above and below of the map
<img src="https://user-images.githubusercontent.com/25118257/109399860-a0a7fc00-7945-11eb-89e5-8df4a02a8660.png" height="350px"/>

**Comment by roderikpeeters** [comment]
Also looking for a solution for this.

**Comment by maRci002** [comment]
`TileLayerOptions` has a `backgroundColor` property change it to `Colors.transparent`

**Comment by PaoloP98** [comment]
> `TileLayerOptions` has a `backgroundColor` property change it to `Colors.transparent`

I would like to remove that space not make it transparent

**Comment by kengu** [comment]
@PaoloP98 Are you trying to keep the map within its outer bounds? If so, this example should do it 

* https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/sliding_map.dart

> This is a map that can be panned smoothly when the boundaries are reached.

**Comment by PaoloP98** [comment]
> @PaoloP98 Are you trying to keep the map within its outer bounds? If so, this example should do it
> 
> * https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/sliding_map.dart
> 
> > This is a map that can be panned smoothly when the boundaries are reached.

Thanks, I tried, it looked fine but there is still a problem when I zoom in and out. When I zoom in, the edges reappear
