### ISSUE TITLE
Changing marker position onTap and getting the latitude and longitude.

### ISSUE THREAD

**Issue by ChiragKr04** [fleaflet/flutter_map#833]
I am implementing the flutter_map where I want to add a marker on tap and get the location where the marker is placed. 
I've seen examples but all the markers are with hardcoded values.
Is there a possible way to get the location of the placed marker?

  

    class MapScreen extends StatefulWidget {
       final PlaceLocation initialLocation;
       final bool isSelecting;
        MapScreen({
            this.initialLocation = const PlaceLocation(
              latitude: 37.422,
              longitude: -122.084,
            ),
            this.isSelecting = false,
          });
        
          @override
          _MapScreenState createState() => _MapScreenState();
     }  
    class _MapScreenState extends State<MapScreen> {
      lg.LatLng _pickedLocation;
  
    void _selectLocation(lg.LatLng position) {
      setState(() {
        _pickedLocation = position;
      });
    }
  
    @override
    Widget build(BuildContext context) {
      return Scaffold(
        appBar: AppBar(
          title: Text("Map"),
        ),
        body: FlutterMap(
          options: MapOptions(
            center: lg.LatLng(
              widget.initialLocation.latitude,
              widget.initialLocation.longitude,
            ),
            zoom: 5,
          ),
          layers: [
            TileLayerOptions(
              urlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
            ),
            MarkerLayerOptions(
              markers: _pickedLocation == null
                  ? null
                  : [
                      Marker(
                        width: 45,
                        height: 25,
                        point: _pickedLocation,
                        builder: (ctx) => Container(
                          child: IconButton(
                            onPressed: () {
                              print("marker tapped");
                            },
                            icon: Icon(
                              Icons.location_on,
                              color: Colors.red,
                              size: 45,
                            ),
                          ),
                        ),
                      ),
                    ],
            ),
          ],
        ),
      );
    }
    }

**Comment by ibrierley** [comment]
You can probably do something like...
```
new MapOptions(
    onTap: (LatLng location) {
        // update your stuff
    }
)
```
If it's any use, I also added a dragMarker plugin at https://github.com/ibrierley/flutter_map_dragmarker but I think this won't be necessary, if you only want to move it instantly.

**Comment by ChiragKr04** [comment]
Thanks for the help <3 
But I want to add that dragMarker as well, will look into your repo.
