### ISSUE TITLE
Map Freezes after opening, say.. a Filter/Sorting screen and going back to the Map

### ISSUE THREAD

**Issue by joao10martins** [fleaflet/flutter_map#834]
I'm facing an issue which is pretty annoying and only throws:
`Bad state: Cannot add new events after calling close`

So what happens is that when I am on the Map I am able to move the map around and moving to a marker is also possible BUT if I open a new screen and change some filtering/sorting option(doesn't really matter what exactly happens here) and "submit" it and go back to the Map the Map is now frozen and won't move unless I re-open the screen from the beginning.

Any ideas why the Map freezes?

**Comment by ibrierley** [comment]
Sounds a bit like more screen/page Navigaton state being lost than flutter_map maybe ?

**Comment by joao10martins** [comment]
Hmm.. and how exactly does that affect the map? I can still see the map and interact with other widgets I have. everything except the map

**Comment by ibrierley** [comment]
It's a while since I've dealt with that, so I may be out of date. But in the past if you navigated away from a widget with certain solutions, state of previous widgets was lost, maybe streams closed. So that could be things like the mapController state may be lost ? 

I'm just guessing here, but probably some stream has been closed and needs to be reopened looking at the error. Personally with the nav I used, I just set the widgets to be Offstage, so nothing was ever lost or closed on them, but there's various ways to implement navigation (if that's what the issue is). I think you'll probably have to add a bit of debugging to try and figure what bits are in what state when you return from the new screen.

**Comment by rorystephenson** [comment]
This sounds like an error in your code. You should share a reproducible case of you'd like help.

Make sure you are closing any streams in the dispose method and reopening them in the initstate.

**Comment by andreystavitsky** [comment]
after 0.11 update map destroys MapController when dispose. Move your MapController to same State that your map contained in.

**Comment by joao10martins** [comment]
> after 0.11 update map destroys MapController when dispose. Move your MapController to same State that your map contained in to ensure that MapController will be created with map.

Yeah I forcefully fixed my issue by re-initializing the MapController but I don't think that disposing the MapController automatically is a good thing to do, in my opinion I should decide when I want to dispose of a given controller myself.

**Comment by ibrierley** [comment]
Feels kind of clunky to have to deal with any of that if using a menu or something. As mentioned, if you use an offstage widget I don't think you will have any of those problems unless something has changed since I last used it. It just means the none active widgets are still there, just not displayed.

So I typically have say 3 widgets in a container list type widget. Only one can be active, so I put 3 Offstage widgets inside, eg flutter_map, a_menu_widget, an_options_widget, and then just toggle which one is active via the offstage param.

**Comment by tranice** [comment]
I met the same problem that Map freezes ,when touch map , will throw Bad state: Cannot add new events after calling close ,but it happens occasionally ,I met some times, I even can't  reproduce it .

**Comment by ibrierley** [comment]
It's probably down to not looking after state and streams correctly.

**Comment by juanlabrador** [comment]
I have the problem, I start when migrating to flutter 2.0, and in my case I have an app where I must show a flow of states with the map, for this I must be changing widgets, on top of the same map, like saying that it will change the screen. When starting it moves, when it changes state, the error already appears.

**Comment by ibrierley** [comment]
I think you need to include more information for others to have an idea of what may be wrong, and include some example code.

**Comment by fryette** [comment]
Same happens to me
In log I see: thread #30, name = 'DartWorker', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY

**Comment by ibrierley** [comment]
I think you need to include more information and some example. Showing how you are handling navigation, how are you preserving state etc.

**Comment by andreystavitsky** [comment]
It can be reproduced by putting map controller into bloc

**Comment by ibrierley** [comment]
Someone needs to show a minimal example highlighting the problem, as has been said numerous times.

**Comment by fryette** [comment]
My case was:
I added post frame callback with setState after navigation. I have quite a lot of layer and in 99% app crashed because of out of memory.
After removing it, navigation working like a charm

**Comment by TheMcSebi** [comment]
I've created a "minimal" example. It appears this only occurs when setState is called while the FlutterMap widget is not currently displayed.
I've modified the example map_controller.dart from version 0.11.0 to show this effect.

Steps to reproduce: Open the page for MapController, Click "Dublin" to check if it is still working, Click "London" to hide the map and call setState, click Dublin or anything else again, un-hide the map by clicking London, try clicking Dublin again. Resulting error is "Bad state: Cannot add new events after calling close".

I modified lines 85-55 and 162-164 in this example code.

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';
import 'package:location/location.dart';

import '../widgets/drawer.dart';

class MapControllerPage extends StatefulWidget {
  static const String route = 'map_controller';

  @override
  MapControllerPageState createState() {
    return MapControllerPageState();
  }
}

class MapControllerPageState extends State<MapControllerPage> {
  static LatLng london = LatLng(51.5, -0.09);
  static LatLng paris = LatLng(48.8566, 2.3522);
  static LatLng dublin = LatLng(53.3498, -6.2603);

  bool notdisplaying;

  MapController mapController;
  double rotation = 0.0;

  @override
  void initState() {
    super.initState();
    mapController = MapController();
    notdisplaying = false;
  }

  @override
  Widget build(BuildContext context) {
    var markers = <Marker>[
      Marker(
        width: 80.0,
        height: 80.0,
        point: london,
        builder: (ctx) => Container(
          key: Key('blue'),
          child: FlutterLogo(),
        ),
      ),
      Marker(
        width: 80.0,
        height: 80.0,
        point: dublin,
        builder: (ctx) => Container(
          child: FlutterLogo(
            key: Key('green'),
            textColor: Colors.green,
          ),
        ),
      ),
      Marker(
        width: 80.0,
        height: 80.0,
        point: paris,
        builder: (ctx) => Container(
          key: Key('purple'),
          child: FlutterLogo(textColor: Colors.purple),
        ),
      ),
    ];

    return Scaffold(
      appBar: AppBar(title: Text('MapController')),
      drawer: buildDrawer(context, MapControllerPage.route),
      body: Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
              child: Row(
                children: <Widget>[
                  MaterialButton(
                    child: Text('London'),
                    onPressed: () {
                      mapController.move(london, 18.0);
                      notdisplaying = !notdisplaying;
                      setState(() {
                        print(notdisplaying);
                      });
                    },
                  ),
                  MaterialButton(
                    child: Text('Paris'),
                    onPressed: () {
                      mapController.move(paris, 5.0);
                    },
                  ),
                  MaterialButton(
                    child: Text('Dublin'),
                    onPressed: () {
                      mapController.move(dublin, 5.0);
                    },
                  ),
                  CurrentLocation(mapController: mapController),
                ],
              ),
            ),
            Padding(
              padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
              child: Row(
                children: <Widget>[
                  MaterialButton(
                    child: Text('Fit Bounds'),
                    onPressed: () {
                      var bounds = LatLngBounds();
                      bounds.extend(dublin);
                      bounds.extend(paris);
                      bounds.extend(london);
                      mapController.fitBounds(
                        bounds,
                        options: FitBoundsOptions(
                          padding: EdgeInsets.only(left: 15.0, right: 15.0),
                        ),
                      );
                    },
                  ),
                  Builder(builder: (BuildContext context) {
                    return MaterialButton(
                      child: Text('Get Bounds'),
                      onPressed: () {
                        final bounds = mapController.bounds;

                        Scaffold.of(context).showSnackBar(SnackBar(
                          content: Text(
                            'Map bounds: \n'
                            'E: ${bounds.east} \n'
                            'N: ${bounds.north} \n'
                            'W: ${bounds.west} \n'
                            'S: ${bounds.south}',
                          ),
                        ));
                      },
                    );
                  }),
                  Text('Rotation:'),
                  Expanded(
                    child: Slider(
                      value: rotation,
                      min: 0.0,
                      max: 360,
                      onChanged: (degree) {
                        setState(() {
                          rotation = degree;
                        });
                        mapController.rotate(degree);
                      },
                    ),
                  )
                ],
              ),
            ),
            Flexible(
              child: notdisplaying
                  ? Container()
                  : FlutterMap(
                      mapController: mapController,
                      options: MapOptions(
                        center: LatLng(51.5, -0.09),
                        zoom: 5.0,
                        maxZoom: 5.0,
                        minZoom: 3.0,
                      ),
                      layers: [
                        TileLayerOptions(
                            urlTemplate:
                                'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                            subdomains: ['a', 'b', 'c']),
                        MarkerLayerOptions(markers: markers)
                      ],
                    ),
            ),
          ],
        ),
      ),
    );
  }
}

class CurrentLocation extends StatefulWidget {
  const CurrentLocation({
    Key key,
    @required this.mapController,
  }) : super(key: key);

  final MapController mapController;

  @override
  _CurrentLocationState createState() => _CurrentLocationState();
}

class _CurrentLocationState extends State<CurrentLocation> {
  int _eventKey = 0;

  var icon = Icons.gps_not_fixed;
  StreamSubscription<MapEvent> mapEventSubscription;

  @override
  void initState() {
    super.initState();

    mapEventSubscription =
        widget.mapController.mapEventStream.listen(onMapEvent);
  }

  @override
  void dispose() {
    mapEventSubscription.cancel();
    super.dispose();
  }

  void setIcon(IconData newIcon) {
    if (newIcon != icon && mounted) {
      setState(() {
        icon = newIcon;
      });
    }
  }

  void onMapEvent(MapEvent mapEvent) {
    if (mapEvent is MapEventMove && mapEvent.id == _eventKey.toString()) {
      setIcon(Icons.gps_not_fixed);
    }
  }

  void _moveToCurrent() async {
    _eventKey++;
    var location = Location();

    try {
      var currentLocation = await location.getLocation();
      var moved = widget.mapController.move(
        LatLng(currentLocation.latitude, currentLocation.longitude),
        18,
        id: _eventKey.toString(),
      );

      if (moved) {
        setIcon(Icons.gps_fixed);
      } else {
        setIcon(Icons.gps_not_fixed);
      }
    } catch (e) {
      setIcon(Icons.gps_off);
    }
  }

  @override
  Widget build(BuildContext context) {
    return IconButton(
      icon: Icon(icon),
      onPressed: _moveToCurrent,
    );
  }
}
```

**Comment by ibrierley** [comment]
Not quite sure on this one (I can't easily run as its not null safe). It
feels like you should handle the mapController stream cancel, when you are
removing flutter_map from the widget tree, and leaving CurrentLocation with
the mapeventstream still active ? I may well be wrong though! But the fact
it's not clear what should happen there, makes me think there's something
amiss.

I'm not an expert on the mapController stuff though, so maybe someone
better than me can clarify how this type of thing can be handled.

**Comment by TheMcSebi** [comment]
How would I go about handling the mapController steam cancel? I'm relatively new to flutter and still trying to grasp some of the concepts involved.
In my use-case I'm simply trying to display a map for a second time after showing different content and move the map once the user has clicked a button. Re-initializing the MapController when the map is shown for the second time doesn't work either, because 
```
The method 'move' was called on null. 
Receiver: null
Tried calling: move(Instance of 'LatLng', 2.0, id: null, source: Instance of 'MapEventSource')
``` 
Using the debugger I can see that my newly created mapController is not null, but it's not "ready" either. Initializing the mapController seems to only work in the initState() method.

To easily reproduce this error, the git repo at the commit of 0.11.0 release can be used for testing. This can be found here: https://github.com/fleaflet/flutter_map/tree/c99a14ece7fc70dcf3f524da24ce51f9f2e2e717 
Just download as zip, replace map_controller.dart with the one I modified and run it.

**Comment by ibrierley** [comment]
I guess it's the same principle though with the null error, that should be handled by the code. Btw I'm not saying that flutter_map isn't at fault, just it's not clear what should happen anyway.

For what it's worth, I've always handled this issue by using an Offstage() Widget, and just mark the widget offstage=true (eg by checking the value of notDisplaying). That way, flutter_map is always in the widget tree, and when you return to that page, the state is exactly as it was left prior to navigating away.

**Comment by TheMcSebi** [comment]
Thank you! I wasn't aware of that widgets existence. I'll try to implement that and report back.

**Comment by ibrierley** [comment]
It's a very handy one for menus. Just be aware that things like animation still happen if a widget is offstage, so may want to handle prevent some actions if there's something happening and may be inactive for a long time.

Would also be interesting to know how others handle things like menu navigation and flutter_map and mapController etc.

**Comment by TheMcSebi** [comment]
It solves my issue. Thank you so much for pointing out the Offstage widget to me, I've been trying to solve this issue for hours in so many different ways.
At least performance shouldn't be impacted too much, as I only need a single map widget at any time.
