### ISSUE TITLE
Loading tiles outside min/maxZoom when changing BaseMap

### ISSUE THREAD

**Issue by Anders55** [fleaflet/flutter_map#836]
STR:
1. Set up a BaseMap with maxZoom = 20
2. Set up a BaseMap with maxZoom = 19 (OpenStreetMap)
3. Load the BaseMap from step 1
4. Zoom to zoom=20. 
5. Change BaseMap to the map in step 2

Problem: flutter_map will now in it's didUpdateWidget method of the _TileLayerState class  iterate through the old tiles (from the Basemap in step 1) and try to replace them with new corresponding tiles (from the BaseMap in step 2). This causes an error as the new BaseMap does not have tiles for the same coords and zoom-level (zoom=20) as the BaseMap in step 1.

**Comment by Anders55** [comment]
PR here: https://github.com/fleaflet/flutter_map/pull/837

**Comment by kengu** [comment]
Closed by #837.
