### ISSUE TITLE
Will MBTilesImageProvider come back?

### ISSUE THREAD

**Issue by DonWasyl** [fleaflet/flutter_map#839]
Hello :)
I've been confused because I was trying to add an offline map based on mbtiles format. I noticed that MBTilesImageProvider has been deleted since 0.11.0, so I'm using https://pub.dev/packages/flutter_mbtiles_extractor/ for now to extrude raster tiles.
Are you planning to revert mbtiles support? I'm asking because I'm wondering if my work with extruding have sense if MBTiles provider will back ;)

**Comment by DonWasyl** [comment]
I used removed code from this repository and I've created a separate package:

https://github.com/DonWasyl/flutter_map_mbtiles_provider

**Comment by NemanjaLugi** [comment]
Hi, 

I also have this issue with the 0.11.0 version. Is there any new way how to load mbtiles offline maps?

**Comment by kengu** [comment]
@DonWasyl You can use [flutter_map_mbtiles_provider](https://github.com/DonWasyl/flutter_map_mbtiles_provider) to load mbtiles offline from assets or local file.

**Dependency**
Since flutter_map_mbtiles_provider is not available on [pub.dev](https://pub.dev), you need to use the following dependency definition in `pubspec.yaml`:
```
flutter_map_mbtiles_provider:
    git:
      url: git://github.com/DonWasyl/flutter_map_mbtiles_provider
      ref: master
```
**Import package**
`import 'package:flutter_map_mbtiles_provider/flutter_map_mbtiles_provider.dart';`

**From asset**
```
TileLayerOptions(
  tileProvider: MBTilesImageProvider.fromAsset('assets/berlin.mbtiles'),
  maxZoom: 14.0,
  backgroundColor: Colors.white,
  tms: true,
),
```
**From local file**
```
TileLayerOptions(
  tileProvider: MBTilesImageProvider. fromFile(File('path/to/file.mbtiles'),
  maxZoom: 14.0,
  backgroundColor: Colors.white,
  tms: true,
),
```
For full example, see [example/lib/main.dart](https://github.com/DonWasyl/flutter_map_mbtiles_provider/blob/master/example/lib/main.dart)

**Comment by DonWasyl** [comment]
@kengu thanks, I know, this is my repository 😂

**Comment by kengu** [comment]
Haha, I see that now. Wrong mention

**Comment by kengu** [comment]
@DonWasyl Are you planning to publish the package to [pub.dev](https://pub.dev)?

**Comment by kengu** [comment]
@DonWasyl The short answer to your question is that it it is unlikely that MBTilesImageProvider will return as core component in flutter_map. Closing.

**Comment by eveetc** [comment]
> @DonWasyl The short answer to your question is that it it is unlikely that MBTilesImageProvider will return as core component in flutter_map. Closing.

What is the exact reason for it ?

**Comment by HugoHeneault** [comment]
> > @DonWasyl The short answer to your question is that it it is unlikely that MBTilesImageProvider will return as core component in flutter_map. Closing.
> 
> What is the exact reason for it ?

From changelog : 

> This version removes various tile providers that depend on plugins. **This helps simplify the flutter_map release process.** Tile providers can be implemented in your app or in a separate package.

This plugin should be in the Readme, but it might require to publish it first on pub.dev?
