### ISSUE TITLE
latLngToPoint() gives wrong Point on Epsg3006, but not on Epsg3857

### ISSUE THREAD

**Issue by magnuswikhog** [fleaflet/flutter_map#840]
Not sure if this is a bug or just a drawback of using `Epsg3006` as the Coordinate Reference System, but when I try to get the screen offset of a longpress from a coordinate, it gives me the wrong point. It works perfectly if I instead use `Epsg3857` (but of course my tiles get screwed up). 

I use the following code to get the screen point:

      CustomPoint<num> northWestPoint = Epsg3006().latLngToPoint(mapController.bounds.northWest, mapController.zoom);
      CustomPoint<num> markerPoint = Epsg3006().latLngToPoint(latLng, mapController.zoom);
      o = Offset(markerPoint.x - northWestPoint.x, markerPoint.y - northWestPoint.y);

For example, when the map is at `LatLng(latitude:55.706972, longitude:13.187099)`) and I press near the top left corner, I get ~ `(-15.4,12.2)` instead of the expected ~ `(0,0)`.

**Comment by magnuswikhog** [comment]
Any suggestions on this issue?

**Comment by kengu** [comment]
If you need screen point in pixels, this is the correct way of doing so

```
final pointInLatLng = ...
final pointInPixels = map.project(pointInLatLng);
```

This will always use the `Crs` defined in `MapOptions` to project to pixels in a `CustomPoint` instance at current zoom level.

**Comment by magnuswikhog** [comment]
@kengu I can't get this to work at all. 

Not sure what you mean by `map.project()`? There's no `project()` method on the `FlutterMap` widget or the `MapController`. Perhaps you meant `crs.projection.project()`? I tried that, but it doesn't give anything near pixel coordinates.

I'm able to get the same results as my original code by doing this:

```
  CustomPoint<num> northWestPoint = _crs.projection.project(mapController.bounds.northWest);
  CustomPoint<num> markerPoint = _crs.projection.project(ll);
  Offset o = Offset(markerPoint.x - northWestPoint.x, northWestPoint.y - markerPoint.y);
  o = o.scale(2, 2);
```

Not sure why I need to multiply by 2, but it doesn't really matter - I get the same results as the original code. ~ (-16,12) instead of (0,0).

**Comment by kengu** [comment]
@magnuswikhog I don't know what you want to accomplish or where you are trying to accomplish it at, but is seems like you are working outside the control scope of flutter_map's plugin api? The reference was to `MapState` which is available when extending `MapPlugin`. Do you have a complete example to share that shows me what you want to accomplish? You could e.g. use [dart.pad](https://dartpad.dev) to share it.
