### ISSUE TITLE
Flutter Maps Offline with AssetTileProvider send Error: Unable to load asset 

### ISSUE THREAD

**Issue by KaliFuckers** [fleaflet/flutter_map#846]
I'm usin QGIS to generate the assets with TMS tile convention. Wanna know if i can use other program than QGIS or if it's a flutter_map error
![Captura de pantalla (1)](https://user-images.githubusercontent.com/26528044/111710524-38e82100-8820-11eb-9b15-5d2ec35f46be.png)

**Comment by kengu** [comment]
Did you remember to add these assets to `pubspec.yaml` under assets section? This is from the example app
![image](https://user-images.githubusercontent.com/866528/111762947-e0f1fe80-88a1-11eb-8daf-bec9f2639811.png)

**Comment by KaliFuckers** [comment]
Of course i did it and i tried with theses assets in the example and still the same. The fact is, look for some assets that doesn't exist

**Comment by KaliFuckers** [comment]
I use QGIS with QMetaTiles

**Comment by Swepilot** [comment]
Have you tried `TileLayerOptions.tms = true`

**Comment by kengu** [comment]
If `tms: true`does not work, you could try to use [flutter_mbtiles_extractor](https://pub.dev/packages/flutter_mbtiles_extractor) as a reference.

**Comment by LamaAgent** [comment]
@shammael Were you able to fix it?
