### ISSUE TITLE
Placing widgets over map (stack)

### ISSUE THREAD

**Issue by CJSZ01** [fleaflet/flutter_map#849]
Is there any way to overlay a widget in front of the map, something like a button?
Tried using a stack, tried using an indexed stack, tried multiple things but it just doesn't seem to work, either the map is rendered, or the widget in front of it. Anyone has an idea? Thanks for the help!

**Comment by Swepilot** [comment]
I'm placing positioned buttons on top of the map using `Stack` so I don't know why it's not working for you.

**Comment by CJSZ01** [comment]
Darn it. It is good to know the problem is with my code then, I'll rethink the implementation. Thank you!
