### ISSUE TITLE
Incompatible with camera >=0.8.0

### ISSUE THREAD

**Issue by tercnem** [fleaflet/flutter_map#853]
Updating my project's libraries, I found the following incompatibility.
```
Because flutter_map >=0.5.0+1 depends on tuple ^1.0.2 which depends on quiver >=0.22.0 <3.0.0, flutter_map >=0.5.0+1 requires quiver >=0.22.0 <3.0.0.

And because camera >=0.8.0 depends on quiver ^3.0.0, flutter_map >=0.5.0+1 is incompatible with camera >=0.8.0.

So, because sidak_mobile depends on both camera ^0.8.1 and flutter_map ^0.12.0, version solving failed.
```

**Comment by kengu** [comment]
It seems like you have old dependencies that require different (older og newer) incompatible versions. It is highly unlikely that any of these stems from flutter_map. If you are not able to upgrade all dependencies to versions of tuple that are compatible with each other, you are probably left with one of the following options

* Downgrade flutter_map to a version of tuple that works with other dependencies in you app
* use dependency_override to force a downgrade to tuple ^1.0.2

None of these solutions are optimal though, but it should works as a temporary solution until all of your dependencies are compatible with same version of tuple.
