### ISSUE TITLE
OSM Change Theme style

### ISSUE THREAD

**Issue by tazik561** [fleaflet/flutter_map#855]
On my application I am using osm like this:

    FlutterMap(
                        options: MapOptions(
                            controller: controller,
                            center: model!.userLocation,
                            zoom: 16.0,
                            onTap: (point) {
                              model.setSelectedLatLngMarker(point);
                            },
                            plugins: [
                              DragMarkerPlugin(),
                            ]),
                        layers: [
                          TileLayerOptions(
                            urlTemplate:
                                'https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png',
                            subdomains: ['a', 'b', 'c'],
                            tileProvider: NonCachingNetworkTileProvider(),
                          )

I want to use dark map but `https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png`, is very dark : https://pasteboard.co/JUque4J.png

Is it possible to change street line and title colors ?

After googleing I found This [guide][1] . Now with **maputnik** I made my custom style. After exporting json style how can I use this style ?

  [1]: https://openmaptiles.org/docs/style/maputnik/

**Comment by kengu** [comment]
I don't think this question belongs here, it should be raised in https://forum.openstreetmap.org. TileLayer fetches images (tiles) from any source supporting slippy or tms tile formats.
