### ISSUE TITLE
Polyline filled with borderColor

### ISSUE THREAD

**Issue by Ahmed-gubara** [fleaflet/flutter_map#856]
Starting with version 0.11.0 with PR #766
Using **Polyline** to draw path creates shapes (with **borderColor**), unless you pass **Colors.transparent** as **borderColor**.

![flutter_map](https://user-images.githubusercontent.com/29988012/112743352-e254b280-8f96-11eb-8936-e0e785f723b8.JPG)

Going through the source code i found this part 
https://github.com/fleaflet/flutter_map/blob/e8389e13083839a9f854bba2239d91f475940eaa/lib/src/layer/polyline_layer.dart#L153-L161

and 
https://github.com/fleaflet/flutter_map/blob/e8389e13083839a9f854bba2239d91f475940eaa/lib/src/layer/polyline_layer.dart#L188-L195

Swapping **filterPaint** with **borderPaint** in the function call **_paintLine(...)** makes **Polyline** works normally

Should i make PR for that, or is this intentional?

**Comment by kengu** [comment]
@escamoteur - I guess the intention was not to change default behaviour of polyline filling?

**Comment by escamoteur** [comment]
nope, that wasn't intended

**Comment by escamoteur** [comment]
yeah, PR would be nice

**Comment by kengu** [comment]
@Ahmed-gubara A PR is much appreciated. Add me as reviewer and I will look at it asap.

**Comment by escamoteur** [comment]
could you check if this is still the case in my null safety branch?

**Comment by Ahmed-gubara** [comment]
@escamoteur  It's still present in your null safety branch.
I've made a PR with just placing the line `borderPaint.style = PaintingStyle.stroke;` before the paint statement.

**Comment by escamoteur** [comment]
could you make a PR on https://github.com/escamoteur/flutter_map/tree/nullsafety?

**Comment by Ahmed-gubara** [comment]
@escamoteur I've made the PR, but getting `All checks have failed` with issues related to files I've not changed.
