### ISSUE TITLE
LatLng not found

### ISSUE THREAD

**Issue by mbdax034** [fleaflet/flutter_map#857]
Hello,
Thanks for this work
I don't know why but i can't found LatLng class.
I'm using Visual Studio Code .
I think  it's not exported from plugin package

**Comment by kengu** [comment]
Yes, you are right @mbdax034 . It is not exported by flutter_map, you need to add latlng to pubspec.yaml.

**Comment by mbdax034** [comment]
Thanks for your response,
I have done it, but i have this issue:
```
LatLng is defined in snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/latlng-0.1.0/lib/src/latlng.dart`
LatLng.dart(35, 25): LatLng is defined in snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/latlong-0.6.1/lib/latlong/LatLng.dart
```

**Comment by josxha** [comment]
@mbdax034 I assume that the error occurs when running `pub get`?
The version of latlong inside your pubspec.yaml don't match with the version required by flutter_map. You can't use two different versions of the same package in your project.
Change the line in your `pubspec.yaml` to:
```yaml
latlong: ^0.6.1
```
