### ISSUE TITLE
Flutter2 Migration

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#858]
Do you have plan to migrate to flutter 2
I have problem with [latlong: ^0.6.1](https://github.com/lpongetti/flutter_map_marker_cluster/blob/master/pubspec.yaml#L17) and `quiver`

**Comment by stingrayx** [comment]
Same question and problem on my side with flutter_map + google_sign_in and quiver

**Comment by danilocubos** [comment]
There is an open pull request #854 for replacing latlong to latlong2.

**Comment by sm2017** [comment]
What about quiver

**Comment by Mariluk** [comment]
quiver: ^3.0.0-nullsafety.3

**Comment by Tahaan** [comment]
Not a stale issue
