### ISSUE TITLE
Marker rotation

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#861]
I upgraded flutter map from **0.10.1+1** to **0.12.0**

The `MarkerLayerOptions` rotates with map in new version, How can I stop rotation of marker layer?

```dart
Widget build(BuildContext context) {
  return FlutterMap(
    options: MapOptions(
      center: LatLng(51.5, -0.09),
      zoom: 13.0,
    ),
    layers: [
      TileLayerOptions(
        urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        subdomains: ['a', 'b', 'c']
      ),
      MarkerLayerOptions(
        markers: [
          Marker(
            width: 80.0,
            height: 80.0,
            point: LatLng(51.5, -0.09),
            builder: (ctx) =>
            Container(
              child: FlutterLogo(),
            ),
          ),
        ],
      ),
    ],
  );
}
```

**Comment by tlueder** [comment]
https://github.com/fleaflet/flutter_map/issues/823#issuecomment-779939088

**Comment by sm2017** [comment]
@tlueder What is use use case of marker location? Why it is the default behavior in the latest version?
It's be better to have a Boolean `rotateMarkers` options

**Comment by tlueder** [comment]
I can think of a simple use case where you would want the marker be rotated relative to the map and not the screen. Just think of directional marker, like pointing to an exit.

But you are right, having a setting in the map options to switch between rotate markers or not by default would be helpful.

I didn't implement the rotation feature, so I can't say something about the why the default behaviour is as it is.

I just wanted to answer you question on how you can make them stop rotating.

So maybe to get this fixed, you could open a feature request or implement this yourself and make a pull request?

**Comment by sm2017** [comment]
I open https://github.com/fleaflet/flutter_map/issues/863
