### ISSUE TITLE
How to get feature info from geoserver 

### ISSUE THREAD

**Issue by saufister** [fleaflet/flutter_map#862]
Hi, i am successfull add my geoserver tile wms into flutter_maps like this
![Screenshot_2021-04-03-17-57-52-805_me jpryan flutter_map_example](https://user-images.githubusercontent.com/7332738/113475823-405b2b80-94aa-11eb-8096-8793c31e1dde.jpg)

I want to show dialog about info of feature when tap on the feature, how i can achieve that ?
In leaflet web i can do that with following this :
https://gist.github.com/rclark/6908938

Appreciate it for the help. Thanks

**Comment by dipesh1993** [comment]
Hey have u got any solution?

**Comment by FernandoChulde** [comment]
someone found something?

**Comment by ibrierley** [comment]
Can you show a live running leaflet.js example somewhere ? It's difficult to know quite what's being sought. 

I'm guessing there's the disconnect of where the feature info is. Is the provided within a tile that is decoded or something else ?

**Comment by dipesh1993** [comment]
Consider above screenshot in flutter where we need getfeatureinfo at the selected area.
The flutter_maps provide getmap to display the tile but does not have getfeatureinfo yet.

**Comment by ibrierley** [comment]
Yes, I get that :D, but you have to do a little work to explain where that info physically comes from, or a spec for it or something.

**Comment by ibrierley** [comment]
Just looking a bit more at it. My guess is that you are using flutter_map wms tile layer or something, which is set to load in a raster image which is a png. Hence it will have no feature information with it. You could possibly download another format, but that will need decoding, and then as well something written to figure out a tap location to the information downloaded. 
Nothing is impossible, but I suspect it's not something you can achieve without a lot of work (unless someone provides an external lat/lng to feature api, then it would be easier, but I'm assuming that's not possible).

If you can find an example that works out there online, it can probably be reverse engineered, but someone has to show an example, not just an image.
