### ISSUE TITLE
[Feature request] Marker rotation

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#863]
In newer version of flutter map, marker is rotated when the map rotates, But in previous it is not rotate , see https://github.com/fleaflet/flutter_map/issues/861

It's be better to have a Boolean `rotateMarkers` options in the `MapOptions` or `MarkerLayerOptions`   to switch between rotate markers or not by default

**Comment by tlueder** [comment]
I like the idea of having this option build in.
So I added it to the marker options

If you want to check it out edit your pubspec.yaml like this

  flutter_map:
    git:
      url: https://github.com/tlueder/flutter_map.git
      ref: rotate-marker

**Comment by sm2017** [comment]
@tlueder Thanks for your PR, As I have `flutter_map_marker_cluster` as my dependencies, I cannot test it, I get error

> Error: The argument type 'LatLng/*1*/' can't be assigned to the parameter type 'LatLng/*2*/'.

I think we need to have some PR in the `flutter_map_marker_cluster` too I requested feature here https://github.com/lpongetti/flutter_map_marker_cluster/issues/68
