### ISSUE TITLE
Support for offline map

### ISSUE THREAD

**Issue by youknowbaron** [fleaflet/flutter_map#878]
Dear Developers, 

I am trying to make an offline map. I downloaded assets from zoom levels 5 to 10.
If I zoom the map to level 10, everything will be alright. But if I zoom the map to level 11, the map disappears, and all I see are the gray background.
How do I do if I want to keep the images at zoom level 10, and just zoom in it at zoom level 11?

Best regards.

**Comment by Swepilot** [comment]
Set `maxNativeZoom` in the layer to 10

**Comment by youknowbaron** [comment]
> Set `maxNativeZoom` in the layer to 10

Thank you very much, it works.
