### ISSUE TITLE
Problem with ChangeNotifierProvider: Could not find the correct Provider<BackendService> above this MainWidget Widget

### ISSUE THREAD

**Issue by SeCo89** [fleaflet/flutter_map#880]
Hi to everyone,

I've got a Problem using flutter_map package in combination with a bottom navigation bar and a ChangeNotifierProvider.
The app consists of a MapScreen and other screens inside a BottomNavigationBar. 
I cannot access the Provider in the MapScreen where the FlutterMap is rendered. Every other screen of the BottomNavigationBar is able to access the Provider.
Although I pass the parent context to the MapScreen I always get the following error:

_The following ProviderNotFoundException was thrown building NotificationListener<KeepAliveNotification>:
Error: Could not find the correct Provider<BackendService> above this MainWidget Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that MainWidget is under your MultiProvider/Provider<BackendService>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
  ```

I tried every solution I got suggested by the error message. Nothing worked.
When I print the passed parent context inside the MapScreen I can see that the context is depending on the correct Provider (MainWidget(dependencies: [MediaQuery, _InheritedProviderScope<BackendService>], state: _MainWidgetState#09b2d)).
I also tried to delete everything that has to do with the KeepAliveMixin. That doesn't work neither.
Could it be a problem of this package?

I would love to solve this problem.
Greetings and thanks in advance!

The relevant code:

**main.dart**

`void main() {
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => BackendService(),),
      ],
      //child: MyApp(),
      builder: (context, child) {
        return MyApp();
      },
    ),
  );
}

class MyApp extends StatelessWidget {
  static const String _title = 'ab&c';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: _title,
      theme: ThemeData(
        primarySwatch: AppConstants.mainColor,
      ),
      home: MainWidget(),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MainWidget extends StatefulWidget {
  MainWidget({Key key}) : super(key: key);

  @override
  _MainWidgetState createState() => _MainWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MainWidgetState extends State<MainWidget> {
  int _selectedIndex;
  List<Widget> _widgetOptions;
  PageController _pageController;

  @override
  void initState() {
    super.initState();
    _selectedIndex = 0;
    _widgetOptions = <Widget>[
      MapWidget(parentContext: context,),
      HotelHomeScreen(),
      HomeScreen(),
      TicketsPage(),
      SettingsPage(),
    ];
    _pageController = PageController(initialPage: _selectedIndex);
    Provider.of<BackendService>(context, listen: false).init();
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
      _pageController.jumpToPage(index);
    });
  }

  @override
  Widget build(BuildContext context) {
    final backendService = Provider.of<BackendService>(context);
    return Scaffold(
      body: backendService.loading
          ? Center(
              child: Container(
                child: CircularProgressIndicator(),
              ),
            )
          : Stack(children: [
              PageView(
                controller: _pageController,
                physics: NeverScrollableScrollPhysics(),
                children: _widgetOptions,
              ),
              _selectedIndex == 0
                  ? Positioned(
                      child: AppBar(
                        title: RichText(
                          text: TextSpan(
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: AppConstants.textColor,
                                fontSize: 20),
                            children: <TextSpan>[
                              TextSpan(
                                  text: 'a',
                                  style:
                                      TextStyle(color: AppConstants.mainColor)),
                              TextSpan(
                                  text: 'b',
                                  style: TextStyle(color: Colors.white)),
                              TextSpan(
                                  text: '&',
                                  style: TextStyle(color: Colors.white)),
                              TextSpan(
                                  text: 'c',
                                  style: TextStyle(color: Colors.white)),
                            ],
                          ),
                        ),
                        backgroundColor: Colors.transparent,
                        elevation: 0,
                        actions: <Widget>[
                          IconButton(
                            icon: Icon(Icons.share),
                            onPressed: () {
                              print('Page: ' + _pageController.page.toString());
                            },
                            tooltip: 'Share',
                            color: AppConstants.textColor,
                          ),
                        ],
                      ),
                      width: MediaQuery.of(context).size.width,
                      height: 80,
                    )
                  : Container(
                      height: 0,
                      width: 0,
                    ),
              (_selectedIndex == 0 || _selectedIndex == 1)
                  ? Positioned(
                      child: SearchBar(),
                      top: 80,
                    )
                  : Container(
                      height: 0,
                      width: 0,
                    ),
            ]),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.map),
            label: 'Map',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.message),
            label: 'Messages',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.local_parking),
            label: 'My Tickets',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: AppConstants.mainColor,
        unselectedItemColor: AppConstants.secondaryColor.shade600,
        selectedLabelStyle: TextStyle(fontWeight: FontWeight.w600),
        unselectedLabelStyle: TextStyle(fontWeight: FontWeight.w600),
        type: BottomNavigationBarType.fixed,
        onTap: _onItemTapped,
      ),
    );
  }
}
`

**MapWidget**

`class MapWidget extends StatefulWidget {
  final BuildContext parentContext;

  MapWidget({Key key, @required this.parentContext}): super(key: key);

  @override
  _MapWidgetState createState() => _MapWidgetState();
}

class _MapWidgetState extends State<MapWidget> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  static const mapHeight = 16.0;
  static const _markerSize = 40.0;
  static const Icon _markerIcon = Icon(Icons.location_on_rounded, color: AppConstants.mainColor);
  static MapController _mapController = MapController();
  static PopupController _popupController = PopupController();
  static List<Marker> userLocationMarkers;
  static List<Marker> markers;

  @override
  void initState() {
    print(Provider.of<BackendService>(widget.parentContext, listen: false)); <---- DOESN'T WORK!
    print(widget.parentContext); <---- PRINTS: MainWidget(dependencies: [MediaQuery, _InheritedProviderScope<BackendService>], state: _MainWidgetState#09b2d)
    super.initState();
    userLocationMarkers = [];
    markers = [
      Marker(
        anchorPos: AnchorPos.align(AnchorAlign.center),
        height: _markerSize,
        width: _markerSize,
        point: LatLng(53.994877, 10.81613444),
        builder: (ctx) => _markerIcon,
      ),
      Marker(
        anchorPos: AnchorPos.align(AnchorAlign.center),
        height: _markerSize,
        width: _markerSize,
        point: LatLng(53.99402858962992, 10.816128234829838),
        builder: (ctx) => _markerIcon,
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    //print(Provider.of<BackendService>(context, listen: false)); <---- DOESN'T WORK!
    return FlutterMap(
          mapController: _mapController,
          options: MapOptions(
            // center: new LatLng(53.99402858962992, 10.816128234829838),
            minZoom: 5.0,
            maxZoom: 18.0,
            plugins: <MapPlugin>[
              // USAGE NOTE 2: Add the plugin
              MarkerClusterPlugin(),
              LocationPlugin(),
            ],
            interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate,
            onTap: (_) => _popupController.hidePopup(),
            // Hide popup when the map is tapped.
            controller: _mapController, 
          ),
          layers: <LayerOptions>[
            TileLayerOptions(
                urlTemplate: AppConstants.MAP_URL, additionalOptions: {
              'accessToken': AppConstants.MAPBOX_API_KEY,
              'id': 'mapbox.mapbox-streets-v7'
            }),
            // USAGE NOTE 3: Add the layer for the marker
            MarkerClusterLayerOptions(
              maxClusterRadius: 120,
              disableClusteringAtZoom: 20,
              size: Size(40, 40),
              anchor: AnchorPos.align(AnchorAlign.center),
              fitBoundsOptions: FitBoundsOptions(
                padding: EdgeInsets.all(50),
              ),
              markers: markers,
              polygonOptions: PolygonOptions(
                  borderColor: Colors.blueAccent,
                  color: Colors.black12,
                  borderStrokeWidth: 3),
              popupOptions: PopupOptions(
                popupSnap: PopupSnap.markerTop,
                popupController: _popupController,
                popupBuilder: (_, marker) =>
                    Container(
                      decoration: BoxDecoration(
                          border: Border.all(
                            color: Colors.red[500],
                          ),
                          borderRadius: BorderRadius.all(Radius.circular(20))
                      ),
                      width: 200,
                      height: 100,
                      //color: Colors.white,
                      child: GestureDetector(
                        onTap: () => debugPrint("Popup tap!"),
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Text(
                            "Container popup for marker at ${marker.point}",
                          ),
                        ),
                      ),
                    ),),
              builder: (context, markers) {
                return FloatingActionButton(
                  child: Text(markers.length.toString()),
                  onPressed: null,
                );
              },
            ),
            MarkerLayerOptions(markers: userLocationMarkers),
            LocationOptions(
              markers: userLocationMarkers,
              onLocationUpdate: (LatLngData ld) {
                //print('Location updated: ${ld?.location}');
              },
              onLocationRequested: (LatLngData ld) {
                if (ld == null || ld.location == null) {
                  return;
                }
                _mapController?.move(ld.location, mapHeight);
              },
              buttonBuilder: (BuildContext context,
                  ValueNotifier<LocationServiceStatus> status,
                  Function onPressed) {
                return Align(
                  alignment: Alignment.bottomRight,
                  child: Padding(
                    padding: const EdgeInsets.only(bottom: 16.0, right: 16.0),
                    child: FloatingActionButton(
                        child: ValueListenableBuilder<LocationServiceStatus>(
                            valueListenable: status,
                            builder: (BuildContext context,
                                LocationServiceStatus value, Widget child) {
                              switch (value) {
                                case LocationServiceStatus.disabled:
                                case LocationServiceStatus.permissionDenied:
                                case LocationServiceStatus.unsubscribed:
                                  return const Icon(
                                    Icons.location_disabled,
                                    color: Colors.white,
                                  );
                                  break;
                                default:
                                  return const Icon(
                                    Icons.location_searching,
                                    color: Colors.white,
                                  );
                                  break;
                              }
                            }),
                        onPressed: () => onPressed()),
                  ),
                );
              },
            ),
          ],
        );
  }

}`

**Comment by kengu** [comment]
I don't think flutter_map is at fault here. this seems like a problem with the context not belonging to the correct navigator or some other common problem with providers. you need to ensure that the provider is injected above MapWidget and within same navigator. I believe this the problem is that BottomNavigationBar creates a new navigator for each tab pressed.

**Comment by SeCo89** [comment]
Hey,
I solved the problem, which wasn't related to this library. 
Thanks for helping

**Comment by L200170152** [comment]
> Hey,
> I solved the problem, which wasn't related to this library.
> Thanks for helping

hello..can you help me about this case? i got error like you today, but i can't
