### ISSUE TITLE
Error with latlong2 library

### ISSUE THREAD

**Issue by allesan** [fleaflet/flutter_map#883]
I have a problem with example on the pub.dev page.
This is the error that I get

`Error: The argument type 'LatLng/*1*/' can't be assigned to the parameter type 'LatLng/*2*/'.`

**Comment by ibrierley** [comment]
This is what I had yesterday. I think the key is to make sure you also have the latlong2 package import 'package:latlong2/latlong.dart'; in your own package where you interface with flutter_map. (I thought flutter_map would be enough, but it seems to cause issues without it).
Someone please correct me if I'm wrong!

**Comment by allesan** [comment]
This is what I have as imports

import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

**Comment by aodbee** [comment]
use this 
import 'package:latlong/latlong.dart';
It work for  flutter_map: any

**Comment by marcoautiero** [comment]
Same error here

**Comment by ibrierley** [comment]
Try in your pubspec.yaml

flutter_map:
latlong2: ^0.8.0

and make sure its latlong2 in your imports, not latlong.

If you still get an error, paste the output of "flutter pub deps" (make sure it says latlon2 0.8.0 and not latlong 0.6.1 or something.

**Comment by kaiorferraz** [comment]
it seems that there is no solution for this unless you use "as suffix" whenever is necessary. 

```dart
import 'package:latlong2/latlong.dart' as latLng
```

and then:

```dart
latLng.LatLng(....)
```

**Comment by kaiorferraz** [comment]
Rye solution is to merge whatever LatLng class with latlong2

**Comment by JaffaKetchup** [comment]
@kaiorferraz This shouldn't be necessary. Please post your pubspec.

**Comment by kaiorferraz** [comment]
The issue was solved.

worked for me because LatLng is used extensively across multiple pages. Having to cast (eg: as latLong) was getting overwhelming and inconsistent.
