### ISSUE TITLE
CircleLayerWidget prevents tap on other layers

### ISSUE THREAD

**Issue by arndt-s** [fleaflet/flutter_map#891]
Hi there,

just experienced this weird behavior that a CircleLayerWidget as a last child prevents all taps on other layers (e.g one with markers containing GestureDetectors).

```
FlutterMap(
  children: [
       TileLayerWidget(),
       MarkerLayerWidgetWithGestureDetectors(),
       CircleLayerWidget()
  ]
);
```

```
return CircleLayerWidget(
  options: CircleLayerOptions(
  circles: [
    CircleMarker(
        point: LatLng(location.latitude, location.longitude),
        color: Colors.blue.withOpacity(1),
        borderStrokeWidth: 3.0,
        borderColor: Colors.white,
        radius: 8 
    )
  ],
));
```

Not sure but the CustomPaint used in the CircleLayer might not delegate hits to other widgets beneath.
Ended up using a MarkerLayer that draws a circle.

**Comment by kengu** [comment]
Duplicate of #253?

**Comment by geisterfurz007** [comment]
And #135 although it was declared as "just works this way" in that one. I proposed a solution there (wrapping in IgnorePointer if a boolean field is true), and I am still open to doing that if it is something that would fit it.

**Comment by arndt-s** [comment]
#253 is an issue in which the map is embedded into a list view. In this issue the error occurs in the map itself.
#135 seems to be the same though.
