### ISSUE TITLE
Using with Provider (or BLoC)

### ISSUE THREAD

**Issue by promistrio** [fleaflet/flutter_map#896]
Hello! I've got the same problem like it https://stackoverflow.com/questions/61155942/flutter-map-move-camera-with-map-controller-through-bloc. Is there a more elegant solution?

**Comment by ibrierley** [comment]
Kind of hard to figure a more elegant solution without seeing the code. Every case is different.

**Comment by ibrierley** [comment]
Something "feels" a little off with your logic, but I don't know the aim. It looks a bit like every time you addWaypoint, you add a new onReady function, which looks wrong firstly. I would typically expect and onReady func to be setup in an initState method (alongside the same widget as flutter_map).

But that may all be a redherring as we can't see when addWaypoint and MissingPlanning get called.

**Comment by promistrio** [comment]
> Something "feels" a little off with your logic, but I don't know the aim. It looks a bit like every time you addWaypoint, you add a new onReady function, which looks wrong firstly. I would typically expect and onReady func to be setup in an initState method (alongside the same widget as flutter_map).
> 
> But that may all be a redherring as we can't see when addWaypoint and MissingPlanning get called.

For example, you can't use it with a provider. It only supports stateless widgets. I tried to find an example with something architectural, but I couldn't:(

**Comment by Tahaan** [comment]
Example :  Another widget somewhere wants to use a Bloc or Provider to control the map.

So, from the other widget, you want to do

onTap: () {
  myProvider.setPosition(newLatLongValue);
  }
  
  This provider needs a callback to the Map's controller's method.
  
  Currently I wrap my map in a stateful widget.  in the initState I add the state's "controller" to the provider.  But it feels wrong.
  
  The alternative is to send callback functions down the tree, which can not not work if the Widget changing the location, or zoom, etc, is not a child.
