### ISSUE TITLE
[BUG] maxNativeZoom ignored when map has custom CRS

### ISSUE THREAD

**Issue by 1075dn** [fleaflet/flutter_map#898]
**Describe The Bug/Expected Behavior**

`TileLayerOptions`' `maxNativeZoom` is ignored when using a custom CRS in `MapOptions`.
As such, when zoom level is greater than `maxNativeZoom`, a `RangeError` on the zoom level (index) occurs.

**Screenshot**
![Screenshot showing error](https://user-images.githubusercontent.com/66363175/164287929-005c46f3-3a5c-4707-a973-a155848b23e2.png)

**Additional Information**
May be related to issue #1223.

---

**Doctors Report**
(The issue is irrelevant since I'm not developing for Windows ATM.)
```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.1)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 4.1)
[√] VS Code (version 1.66.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**To Reproduce**
Add the following widget to any Flutter app:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:proj4dart/proj4dart.dart' as proj4;

final _epsg2039 = Proj4Crs.fromFactory(
  code: 'EPSG:2039',
  proj4Projection: proj4.Projection.add('EPSG:2039',
      '+proj=tmerc +lat_0=31.73439361111111 +lon_0=35.20451694444445 +k=1.0000067 +x_0=219529.584 +y_0=626907.39 +ellps=GRS80 +towgs84=-48,55,52,0,0,0,0 +units=m +no_defs'),
  resolutions: <double>[
    793.751587503175,
    264.583862501058,
    132.291931250529,
    66.1459656252646,
    26.4583862501058,
    13.2291931250529,
    6.61459656252646,
    2.64583862501058,
    1.32291931250529,
    0.661459656252646,
    0.330729828126323
  ],
  origins: [CustomPoint(-5403700, 7116700)],
);

class MapTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      options: MapOptions(
        crs: _epsg2039,
        center: LatLng(31.698019, 34.934762),
        minZoom: 0,
        maxZoom: 18,
        zoom: 11,
      ),
      layers: [
        TileLayerOptions(
          maxNativeZoom: 10,
          templateFunction: (str, data) {
            String hexify(String rowOrCol) =>
                int.parse(rowOrCol).toRadixString(16).padLeft(8, '0');
            return 'https://mapcdn.govmap.gov.il/N23A09GARY4/L${data['z'].padLeft(2, '0')}/R${hexify(data['y'])}/C${hexify(data['x'])}.jpg';
          },
        ),
      ],
    );
  }
}
```

---

**Severity**
- [x] Non-Fatal
- [ ] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android _(emulator)_
- [ ] iOS _(not tested)_
- [ ] Web _(not tested)_
- [ ] Windows _(not tested)_
- [ ] Others (beta platforms) _(not tested)_

**Comment by 1075dn** [comment]
@fegyi001

**Comment by ibrierley** [comment]
maxNativeZoom to me seems to work ok, as long as maxZoom is within the crs resolutions range.

Ie maxZoom of 18 and maxNativeZoom won't work, as the map can't deal with a zoom of 11 in this example, so it never gets to try maxNativeZoom.

If maxZoom is 10 and maxNativeZoom is 8 for example, this seems to work (i.e for a zoom of 10, it will try and load zoom 8 tiles and scale, which is what it's purpose is afaik).

However, I don't know much on the crs side of the code in flutter_map, and also it not being null safe makes it harder to debug.

**Comment by 1075dn** [comment]
Okay, for the rest of this discussion, see issue 1223 from [this comment](https://github.com/fleaflet/flutter_map/issues/1223#issuecomment-1110302533) onward.
