### ISSUE TITLE
scroll-wheel zoom support for Flutter desktop and web

### ISSUE THREAD

**Issue by lucavinci** [fleaflet/flutter_map#904]
When using the package in Flutter Web I realized that the zoom with the scroll-wheel is not yet implemented.

I managed to implement a small implementation that zooms but keeps the center unchanged. 
A zoom implementation like the google maps website would be amazing, but I do not know how they do it. I think they change the center relative to the mouse position.

My basic Implementation:

```dart
  /// Handle scroll event for zoom on desktops
  void _onScroll(final PointerSignalEvent pointerSignal) {
    if (pointerSignal is PointerScrollEvent) {
      // Check whether the mouse is scrolled down and change the zoom level
      final delta = pointerSignal.scrollDelta.dy > 0 ? -1 : 1;
      final zoom = this._mapController.zoom + delta;
      // Check whether the zoom level is available and apply zoom level
      if (zoom >= 1 && zoom <= 19) {
        this._mapController.move(this._mapController.center, zoom);
      }
    }
  }
```

```dart
Listener(
        onPointerSignal: this._onScroll,
        child: FlutterMap(
            /* custom code here */
        )
)
```

**Comment by teddichiiwa** [comment]
Wonderful, it works great on macOS

**Comment by lucavinci** [comment]
Thank you. If this is something that is wantee by the community, I could create a PR soon.

**Comment by sethdeegan** [comment]
If this is implemented, is the package considered compatible for web (and gets the label on pub.dev)?

**Comment by gucci-quoci** [comment]
Any updates?
