### ISSUE TITLE
how to import offline image tiles in batch

### ISSUE THREAD

**Issue by CKT90** [fleaflet/flutter_map#905]
example for offline map at zoom 18, there will be several folders of PNG tiles. for a big area, importing each PNG file will take up many lines in pubspec.yaml. is there a better way to import them, or as a whole within a folder directory, instead of individual PNG file import?

**Comment by Swepilot** [comment]
Yes you can import the whole folder instead by referencing that in pubspec.yaml instead of the individual files. Remember to add the forward slash after the directory name.
