### ISSUE TITLE
having multiple TileLayerOptions under FlutterMap.layers

### ISSUE THREAD

**Issue by Zzerr0r** [fleaflet/flutter_map#906]
I need two different TileLayerOptions as layers, because I need to send different "otherParameters" to the server, depending on which layer I'm requesting. However, if I try to include both under FlutterMap.layers, Only the later one will be rendered. Is this intentional and if yes, is there another way to send different parameters for different layers?

**Comment by ibrierley** [comment]
What exactly are you wanting to happen ?

**Comment by Zzerr0r** [comment]
I want both Layers to be rendered. Currently only one of them is getting rendered.
Code under Layers:
layers: [
        TileLayerOptions(
          tileProvider: const CachedTileProvider(),
          wmsOptions: WMSTileLayerOptions(
            baseUrl: "http://10.0.2.2:8080/MapService/wms.axd/testview?",
            layers: ["TileLayer0"],
          ),
        ),
        TileLayerOptions(
          wmsOptions: WMSTileLayerOptions(
            baseUrl: "http://10.0.2.2:8080/MapService/wms.axd/testview?",
            layers: ["MarkerLayer"],
            otherParameters: markerPosMap(),
          ),
        )
]
If I leave the second one out, it shows only "TileLayer0" 
<img src="https://user-images.githubusercontent.com/43878904/118678255-24fb7400-b7fd-11eb-80f4-fabd9e4c31d2.png" width="200" height="400"/>
if i run it like above, it shows only "MarkerLayer"
<img src="https://user-images.githubusercontent.com/43878904/118678321-347abd00-b7fd-11eb-8510-9ff03e46d180.png" width="200" height="400" />

sorry that the code looks like this, i don't know how to format it properly

**Comment by ibrierley** [comment]
Can you change the backgroundColor of the layer to be transparent, not sure the best way, maybe Color(0x00000000) ?

**Comment by Zzerr0r** [comment]
Okay, that fixed it, my bad. Thanks for the help!

**Comment by ibrierley** [comment]
You're welcome, don't worry, it wasn't obvious to me either at first! I had incorrectly assumed the background was transparent by default.
