### ISSUE TITLE
Odd GitHub Dependency Blowing Up

### ISSUE THREAD

**Issue by ibcoleman** [fleaflet/flutter_map#907]
When I set `pubspec.yaml` entry to `0.12.0`, which is the latest reported version on pub.dev, my build blows up because it depends on latlong 0.6.1 which has a very old logging dependency:

`Because no versions of flutter_map match >0.12.0 <0.13.0 and flutter_map 0.12.0 depends on latlong ^0.6.1, flutter_map ^0.12.0 requires latlong ^0.6.1.
Because latlong 0.6.1 depends on logging >=0.11.3 <1.0.0 and no versions of latlong match >0.6.1 <0.7.0, latlong ^0.6.1 requires logging >=0.11.3 <1.0.0.
Thus, flutter_map ^0.12.0 requires logging >=0.11.3 <1.0.0.
So, because asset_management_mobile depends on both logging ^1.0.0 and flutter_map ^0.12.0, version solving failed.
pub get failed (1; So, because asset_management_mobile depends on both logging ^1.0.0 and flutter_map ^0.12.0, version solving failed.)`

When I change `pubspec.yaml` to `flutter_map: any` as specified on pub.dev, I get the following error on `pub get`:
`
Git error. Command: 'git clone --mirror git://github.com/johnpryan/dart-latlong.git /Users/ian/.pub-cache/git/cache/dart-latlong-1a6938abd0ba0d042ff87d2d4ef789c31de62a56'
stdout: 
stderr: Cloning into bare repository '/Users/ian/.pub-cache/git/cache/dart-latlong-1a6938abd0ba0d042ff87d2d4ef789c31de62a56'...
fatal: remote error: 
  Repository not found.
exit code: 128`

From what I can see, flutter_map is trying to clone a repo that doesn't exist. (i.e. git://github.com/johnpryan/dart-latlong.git)

Any idea what's going on? Thanks!

**Comment by dan1229** [comment]
I'm experiencing the same. I believe it's because of this package https://pub.dev/packages/latlong

**Comment by kengu** [comment]
See issue #888
