### ISSUE TITLE
Making a Layer plugin that needs to put GestureDetector on whole screen - double tap doesn't work (and more!)

### ISSUE THREAD

**Issue by TheLastGimbus** [fleaflet/flutter_map#908]
Hi there!
I'm currently creating a plugin that will draw Markers with `canvas` to make it faster! I started to implement `onMakrerTap` functionality, and wouldn't you guess, there are **problems**

After 30 minutes of reaserch I still have no idea how to use multiple `GestureDetector`s, but for now, I've put mine like this:
```dart
@override
Widget build(BuildContext context) {
  return Container(
    width: double.infinity,
    height: double.infinity,
    child: StreamBuilder<int>(
      stream: widget.stream,
      builder: (BuildContext context, snapshot) {
        return GestureDetector(
          onTapUp: (TapUpDetails d) => print('SOME LOGIC HERE'),
          behavior: HitTestBehavior.opaque,  // I have no idea how this works
          child: CustomPaint( ... ),
        );
      },
    ),
  );
}
```

It seems to block `FlutterMap(onTap: (){ })`, and more important, double-tap-to-zoom :confused: 

I tried with custom `class CustomTap extends TapGestureRecognizer` without much success, but would love to see what did I do wrong

When I just set `GestureDetector` with `onTap`, it detects the tap immediately and doesn't care about dobule taps. When I do add some function to `onDoubleTap`, it does have a dealy, and gives me feedback, but still `flutter_map` doesn't receive this

Soooo... does anyone have idea how can I do this? Maybe I should manually add multpiple `Positioned(GestureDetector())`s? 

Maybe this requires some intervention inside `flutter_map` itself - digging into the widget tree, I found this beauty:

https://github.com/fleaflet/flutter_map/blob/9b73456842c4db82daf6fe57807bf32c980a28a2/lib/src/map/flutter_map_state.dart#L89-L94

Maybe we could expose its `controller` so I can pass `onDoubleTap` onto it?

**Comment by ibrierley** [comment]
I suspect you don't want behaviour set to opaque. use translucent (or remove entirely), see if that makes any difference.

**Comment by TheLastGimbus** [comment]
Nope. `translucent`, `deferToChild`, nor "none" don't work either...

**Comment by TheLastGimbus** [comment]
I ended up adding a workaround `onTapRaw` to `MapState` in my fork - https://github.com/KanarekApp/flutter_map/commit/440e2205c562aa689b5db33d23d22d139254e1a2

I don't know if a solution to this issue could be anyhow similar, but works for me for now

**Comment by TheLastGimbus** [comment]
Hey @johnpryan could you take a look? My `fast_markers` library now works pretty well and allows quantity of markers that was previously completely crashing the app - it would be awesome if I could officially publish it on pub

I made a `onTapRaw` function that returns a boolean that indicates if map's `onTap` should be called or skipped - so I can skip it when marker was hit 👌

**Comment by TheLastGimbus** [comment]
No, I still need this :pleading_face:

**Comment by TheLastGimbus** [comment]
Wait stop it's still important!
