### ISSUE TITLE
Marker ID

### ISSUE THREAD

**Issue by RedHappyLlama** [fleaflet/flutter_map#909]
Hello,

As per Google Maps package, please could an int ID property be added for a marker. 

I don't believe it's currently possible. Would be great to be able then reference that ID for that Marker in the popupBuilder.

Thanks!

**Comment by BenBitDesign** [comment]
Hi @RedHappyLlama 

I haven't used the popupBuilder myself, but wouldn't it be possible to put in the builder of the marker a GestureDetector which would call a function with the ID?

Example:
```
      markers.add(
        Marker(
          point: LatLng(data.startLat, data.startLng),
          builder: (ctx) => Container(
            child: GestureDetector(
              onLongPress: () => _changeShownData(data.id),
              child: Icon(
                Icons.location_on,
              ),
            ),
          ),
        ),
      );
```

**Comment by RedHappyLlama** [comment]
Hi @BenBitDesign,

Yes I have considered that, effectively making a custom popup from the Marker, and it's what I'll probably end up doing. I just thought it wouldn't take too much to change the package to accept an int to achieve that. 

Thanks for your comment!
Ben

**Comment by kengu** [comment]
I agree with @BenBitDesign. Ids are use-case specific and therefore left for the user to decide how to implement. We do support keys for each marker now in the constructor, which ensures that flutter will reuse them as long as the position of flutter map does not change in the widget tree.

**Comment by RedHappyLlama** [comment]
Hello,

Is someone able to help me implement this (I'm fairly new to coding) as I'm getting an error? 

Error:
The following ArgumentError was thrown building Builder-[#878fb](dirty):
Invalid argument(s)


I think the issue is that the popup is being built before _changeShownData method is completing?

```
 buildPins() {
    for (AudioGuideDetails audioGuideDetails in widget.audioGuideDetails) {
      pinList.add(
        Marker(
          width: 80.0,
          height: 80.0,
          point: LatLng(audioGuideDetails.latitude, audioGuideDetails.longitude),
          builder: (context) => MapPin(
            pinCallback: () {
              setState(() {
                selectedGuide = widget.audioGuideDetails.indexOf(audioGuideDetails);
              });
              print('selected guide is: $selectedGuide');
            },
            cardNo: audioGuideDetails.id.toString(),
            textColor: myBrownColour,
          ),
        ),
      );
    }
  }
```

                MarkerClusterLayerOptions(
                  popupOptions: PopupOptions(
                    popupSnap: widget.popupSnap,
                    popupController: _popupLayerController,
                    popupBuilder: (BuildContext context, Marker marker) {
                      return AudioGuideCard(
                        audioGuideDetails: widget.audioGuideDetails[selectedGuide],
                        downloaded: widget.audioGuideDetails[selectedGuide].downloaded,
                        popCallback: null,
                      );
                    },
                  ),

**Comment by ibrierley** [comment]
It's hard to debug code like that without running it....maybe you can check if the argument is null or whatever first, and provide a replacement widget (or none) until its ready.
