### ISSUE TITLE
flutter 2 null safety

### ISSUE THREAD

**Issue by mghase** [fleaflet/flutter_map#917]
Please update this library to support flutter 2

**Comment by Marthijs-Berfelo** [comment]
@mghase The upgrade to null-safety is already in progress. Actually several issues already exist for the upgrade. 

See:
#902 
#829 
#870 
#858

**Comment by comatory** [comment]
I know there's a `null-safety` branch, could you please point to it? I'm really dying to migrate my codebase to null safety.

**Comment by andreandersson** [comment]
@comatory there is a null-safety branch at `issues/829-nullsafety`

**Comment by ibcoleman** [comment]
@Marthijs-Berfelo Any estimate when a new release is going to get pushed to pub.dev?

**Comment by statsss** [comment]
need

**Comment by ibrierley** [comment]
As others have said, you can point to the null safety branch in the
meantime, I have done.

**Comment by ibcoleman** [comment]
@ibrierley This is a good workaround short-term, but folks are probably reluctant to rely on hacks around dependency management as a policy in production code.

**Comment by Marthijs-Berfelo** [comment]
> @Marthijs-Berfelo Any estimate when a new release is going to get pushed to pub.dev?

AFAIK merging of the #870 branch and releasing a new version can only be done by @johnpryan

**Comment by JaffaKetchup** [comment]
Close as duplicate? There are already 2(unnecessary) + 1(main) + 1(PR) on this topic?

**Comment by johnpryan** [comment]
Version 0.13.0 has been released, closing.
