### ISSUE TITLE
ScaleLayerPlugin does not refresh on zoom events

### ISSUE THREAD

**Issue by barbalex** [fleaflet/flutter_map#920]
I implemented the ScaleLayerPlugin according to the [example](https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/plugin_scalebar.dart).

Unfortunately when the map is zoomed, the scalebar does not refresh. This is also visible in the example itself (double-click to zoom and watch the scalebar not changing).

How can I get the scalebar to refresh on zoom events?
As this seems expected behavior I suggest to update the example to include it.

**Comment by kimlet** [comment]
fixed at [this PR](https://github.com/fleaflet/flutter_map/pull/930)

**Comment by spyke555** [comment]
Are you issuing a setState on zoom to repaint the widgets? That fixed it for my application.

**Comment by barbalex** [comment]
Would it not be an overkill to repaint all layers instead of just the scale layer?

**Comment by ibrierley** [comment]
Well, I think it's fixed in PR #930 anyway ?

**Comment by kimlet** [comment]
> Well, I think it's fixed in PR #930 anyway ?

Yep, waiting for review @johnpryan

**Comment by barbalex** [comment]
For a different reason I implemented a `setState` call onPositionChanged. This seems to have the side effect of solving this issue. But at the price of this call being dangerous (https://github.com/fleaflet/flutter_map/issues/374) and pricey as it repaints all layers.

**Comment by kimlet** [comment]
> For a different reason I implemented a `setState` call onPositionChanged. This seems to have the side effect of solving this issue. But at the price of this call being dangerous (#374) and pricey as it repaints all layers.

yes, please be careful to use `setState`
