### ISSUE TITLE
Gesture error: LateInitializationError _mapZoomStart and _lastRotation

### ISSUE THREAD

**Issue by c4xp** [fleaflet/flutter_map#922]
Hi, I wanted to migrate to null-safety for flutter_map also but I get theese errors when I move the map (single gesture)
The map just scrolls to mountains of madness ..
In the meanwhile I will keep using 0.12.0

I/flutter (13018): Another exception was thrown: LateInitializationError: Field '_mapZoomStart@750256441' has already been initialized.
I/flutter (13018): Another exception was thrown: LateInitializationError: Field '_lastRotation@750256441' has already been initialized.
...
I/flutter (13018): Another exception was thrown: LateInitializationError: Field '_lastRotation@750256441' has already been initialized.
...
I/flutter (13018): Another exception was thrown: LateInitializationError: Field '_mapZoomStart@750256441' has already been initialized.
I/flutter (13018): Another exception was thrown: LateInitializationError: Field '_lastRotation@750256441' has already been initialized.
...
I/flutter (13018): Another exception was thrown: LateInitializationError: Field '_lastRotation@750256441' has already been initialized.

I think it's related to the null-safety migration in: lib/src/gestures/gestures.dart
flutter 2.2.1
flutter_map 0.13.0
latlong2 0.8.0
environment:  sdk: ">=2.12.0 <3.0.0"
Virtual device - release R - API level 30

I can provide any other info..

**Comment by danielocampo2** [comment]
I am experiencing the same as well

**Comment by JaffaKetchup** [comment]
I think it was probably commit 3ea0500d291cb9b653f3eccf004d4ebdea309a34, which happened just before merge, so @danielocampo2 is correct.

**Comment by andreandersson** [comment]
I removed final from none-final fields, see #923

**Comment by kengu** [comment]
Version 0.13.1 is released to pub.dev with hotfix #923
