### ISSUE TITLE
lastrotation lateinitialization error

### ISSUE THREAD

**Issue by MichalNemec** [fleaflet/flutter_map#924]
Hello,
fresh flutter 2.2.1
included map as a simple stateless widget which is used in homepage.
When i click and drag it goes all over the place and showing just
`
════════ Exception caught by gesture ═══════════════════════════════════════════
LateInitializationError: Field '_lastRotation@627256441' has already been initialized.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
LateInitializationError: Field '_lastRotation@627256441' has already been initialized.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════

`

**Comment by kengu** [comment]
Duplicate of #922

**Comment by kengu** [comment]
Fix is merged to master, @johnpryan will hopefully release 0.14.0 to pub.dev soon.

**Comment by kengu** [comment]
Version 0.13.1 is released to pub.dev with hotfix #923
