### ISSUE TITLE
Order of layer and widget displays not clear.

### ISSUE THREAD

**Issue by ibrierley** [fleaflet/flutter_map#925]
I'm not sure if this is an issue or not currently. I was just debugging a problem with some markers not displaying when I was using Widgets (rather than layers only).

One thing to note I think (from looking at flutter_map_state.dart), is the order that will be displayed seems to go...
widget.childen
widget.layers
widget.nonRotatedChildren
widget.nonRotatedLayers

The problem in my case, and may trip others up, is typically I suspect most people use layers for the tile layer/widget, which means if you do this, any widget children will be hidden.

Maybe most people will either use all widgets or all layers, so it's not a problem (but I note the example in the readme has layers, and widgets...so erm is the 2nd set of markers in the readme example actually hidden ?) ? I'm not really sure it can be changed, as it may break it for others though. Maybe it just needs some note in the readme and examples clarified (if I'm understanding it right)?

**Comment by JaffaKetchup** [comment]
Hi,
It does say in the README that children appear over layers, but that it is recommended to put all layers in children and all children in children.

**Comment by ibrierley** [comment]
Ok, I'm probably missing something then, could you let me know where in the readme, am I looking at the wrong one maybe ? And I think children would be below layers (but as I said, maybe I'm confused, it's entirely possible :D)

**Comment by JaffaKetchup** [comment]
Oh sorry! It doesn't actually say in README, I misremembered. But it does say it in the code itself:

```
/// A set of layers' options to used to create the layers on the map.
///
/// Usually a list of [TileLayerOptions], [MarkerLayerOptions] and
/// [PolylineLayerOptions].
///
/// These layers will render above [children]
final List<LayerOptions> layers;
```

In that case maybe you're right. We do need to raise awareness about this.
