### ISSUE TITLE
Hosting flutter_map plugins in fleaflet GitHub organization

### ISSUE THREAD

**Issue by Xennis** [fleaflet/flutter_map#932]
Dear flutter_map maintainers,

I liked flutter_map and its extensibility via plugins. A drawback is that most plugins are spread across a lot of private GitHub accounts and are often maintained by just one person. A lot of forking happens to patch plugins for example to make them compatible to the latest flutter_map version or to each other. Further on it sometimes take quite some time before merge requests are merged because of the few maintainers.

I'm the maintainer of https://github.com/Xennis/flutter_map_location . I'm getting more and more issues and pull requests and would like to work together with others on the plugin; including giving some people more permissions.

I think it would boost flutter_map if plugins are maintained within the same GitHub organization (of course on voluntary basis). An great example is https://github.com/fluttercommunity that maintainers a lot of high quality plugins and where each plugin has a clear maintainer but other people can easily make adjustments as well.

I would be open to transfer my repo to [fleaflet](https://github.com/fleaflet/) and continue there my work there with together others.

What do you think about that?

Regards
Xennis

**Comment by TheOneWithTheBraid** [comment]
As a contributor of `flutter_map_location`, I definitely like the idea of having a unified `flutter_map` community.

**Comment by ibrierley** [comment]
I agree something would be useful. I've written 4 plugins and not bothered
making a PR for the main Readme, but I know others may find some useful.

The examples mentioned feel a bit "listy" (but that's probably my
ignorance), although maybe the community side is interesting, but I'm not
quite sure what actual community is there or how that works ?

For what it's worth I find this useful for Leaflet
https://leafletjs.com/plugins.html and have referred to it quite a bit when
searching, and if nothing else a layout like that would be beneficial...is
there something that would meet several criteria, allowing easy edit via
multiple changing users (no single owner), useful layout, and maybe
community ?

Ian

**Comment by JaffaKetchup** [comment]
Yeah, that sounds good @Xennis, especially as this project has it's own user space anyway!

**Comment by JaffaKetchup** [comment]
@ibrierley Wow, you totally should make a PR if this doesn't happen, because I just found two of your plugins to do with dragging extremely useful! Thanks 👍

**Comment by ibrierley** [comment]
No problem! Btw on most there's null safety branches there, just I haven't properly tested them yet.

Is there any overlap with documentation i.e https://github.com/fleaflet/flutter_map/discussions/927 ? Can't make my mind up, just like things not too fragmented.

What exactly is fleaflet ? Hadn't even pondered this too much :D.

Just another thought, what about the flutter_map wiki. If it was enabled I think you can allow public editing (as long as they have a git account). It's mentioned in the docs discussion. Could it be a way to go, or does it need a more community aspect and repos under one umbrella (and would people want to do that?)

**Comment by JaffaKetchup** [comment]
Yeah I found them eventually!
Also about the wiki, the issue is you can't make a PR for a wiki, so an external wiki or Pages would be better.

**Comment by ibrierley** [comment]
Do you need PRs when anyone can edit it though ? i.e https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis assuming Jon or whoever would be ok with that...

The fleaflet question, I think I was more meaning who owns it etc, rather than what it stands for. Is it a github organisation that's been set up. If you transfer one of your repos to it, and then something happens to them, what happens ? I'd probably be very hesitant to transfer a repo to it

**Comment by JaffaKetchup** [comment]
Yeah I'm not sure what would happen, we'd have to double check. I guess of 'Jon' could start the wiki, then we can all contribute without PR, but he will need to start it. 
Maybe we could setup a test repo to see what happens?
