### ISSUE TITLE
Propositon to add OverlayWidget

### ISSUE THREAD

**Issue by zeykafx** [fleaflet/flutter_map#940]
Hello,

I'm currently working on a project that required me to place widgets on the map (not like markers because I needed them to stay within certain boundaries).
I quickly copied the OverlayImage file and modified the OverlayImage references to be OverlayWidget (as well as the Layers and options). You can pass a widget to the OverlayWidget and it will take the place of the image from the OverlayImage, it looks like this: 
```dart
OverlayWidget(
    bounds: LatLngBounds(LatLng(35.70466131,-121.1498058), LatLng(34.75734059,-120.3941829)),
    child: Container(
      decoration: BoxDecoration(color: Colors.blue),
      child: Center(child: Text('Hello from the map')),
    )
),
```

<img src="https://user-images.githubusercontent.com/37271973/122444805-358c3f00-cfa1-11eb-9a3c-e0df4f0e5458.jpg" width="350">

[(here is my implementation)](https://github.com/zeykafx/flutter_map/commit/5ada650b0721ce9f9bd754877e0548fb4f43ee1f)
I would do a PR but I have no idea if it was done properly, I just tried something and it ended up working for my use case.

I think this could be useful to have by default.

Thanks for the awesome library!

**Comment by ibrierley** [comment]
It probably would make sense to have this rather than the image overlay if I understand it right, but I guess would break some existing uses if that were to happen...

Just as I'm a bit wary of the flutter_map base getting too large for all options that come along like this, could it be done as a plugin instead I wonder ?

**Comment by zeykafx** [comment]
I suppose it could be done as a plugin but I think that it would be too small to be a standalone plugin.
If having too many options is a problem, I guess you could just add a way to display a widget instead of an image in with the OverlayImage.

**Comment by ibrierley** [comment]
Just a ponder, probably a bad idea, but could it do both and detect what's being passed (so there is just one overlaywidget that doesn't break backwards compatibility), as 90% of the code is probably duplicated ?

**Comment by zeykafx** [comment]
Yes my implementation is literally just an overlay image that does not have an image widget but instead has the widget that you pass into it. I think it would be nice to have one thing that does both (widgets and images) but then it would be a bit weird passing a Widget into an OverlayImage...
