### ISSUE TITLE
Pan boundaries depending on zoom level  and coordenates positive

### ISSUE THREAD

**Issue by amed901107** [fleaflet/flutter_map#943]
But I face a problem with grey area displayed while tapping and zooming when map "ends".It has to do with nePanBoundary and swPanBoundary that don't change depending on zoom level. With negative coordinates it doesn't work well either.
Example:
swPanBoundary: LatLng(18.896,-85.594),
        nePanBoundary: LatLng(24.427, -73.696),

**Comment by mchesnokov** [comment]
> But I face a problem with grey area displayed while tapping and zooming when map "ends".It has to do with nePanBoundary and swPanBoundary that don't change depending on zoom level. With negative coordinates it doesn't work well either.
> Example:
> swPanBoundary: LatLng(18.896,-85.594),
> nePanBoundary: LatLng(24.427, -73.696),

Have you found a solution?

**Comment by amed901107** [comment]
Hi, I have not found a solution so far
