### ISSUE TITLE
Support forum

### ISSUE THREAD

**Issue by Swepilot** [fleaflet/flutter_map#945]
Is there any active support forum for flutter_map, perhaps on Stackexchange/overflow or similar? A lot of issues here aren't really issues but more general "how to" questions. I myself would sometimes like to ask more "how to" questions but don't feel this is the most appropriate forum for it.

Thoughts?

**Comment by ibrierley** [comment]
I suspect currently this is the best place, but maybe that's not ideal. At least with the github bot, things get tidied up a bit. 

I think if it's a general question that just happens to involve flutter_map though, then S.O is be the best. 

There has been a question about a community page though, and sharing solutions etc, and I quite like that idea also IF enough others were happy to join it (and also for more collaboration). I think the danger is just one or two people end up there answering the questions though, and they move on etc.

There's also https://github.com/fleaflet/flutter_map/discussions although I could swear I've not had notifications of some of those!
