### ISSUE TITLE
Fling animation prevents MapController.move

### ISSUE THREAD

**Issue by b3nni97** [fleaflet/flutter_map#946]
If you change the position during the fling animation with move etc. then the map jumps back to the fling animation and the position was not changed.

**Comment by b3nni97** [comment]
No one?

**Comment by JaffaKetchup** [comment]
I agree it's an issue, but I have no idea how to fix it.

**Comment by b3nni97** [comment]
One option is to make the AnimationFlingController accessible from outside, then you can stop the animation yourself
