### ISSUE TITLE
Using hosted Mapbox tile sets (styles)

### ISSUE THREAD

**Issue by comatory** [fleaflet/flutter_map#949]
I have looked at this issue https://github.com/fleaflet/flutter_map/issues/645 that is now closed. The approach there works but it requires me to create my own style via Mapbox studio. I would like to use just the basic style that is hosted by Mapbox (for example `streets-v*-light`).

Also the issue above is using `v1` API, would it be possible to use newer one with this plugin?

**Comment by comatory** [comment]
Bump, anyone has any tips?

**Comment by comatory** [comment]
Does anyone know how to correctly use Mapbox-hosted tiles?

**Comment by JaffaKetchup** [comment]
I think so. In the share map or export map (I haven't personally used it, but I've seen it done), choose the 'Carto' option. It gives a URL (for `urlTemplate`) and a private key that needs to go into the `additionalOptions`.
Let me know how it goes!

**Comment by comatory** [comment]
I had to resort to using this value when passing `urlTemplate` parameter to `TileLayerOptions` object:

`https://api.mapbox.com/styles/v1/myAccount/abcd1234/tiles/256/{z}/{x}/{y}@2x`

I would like to instead use public tiles such as `streets-v8-light` (documented [here](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/)) but when I tried using something like:

`https://api.mapbox.com/styles/mapbox/light-v10`

It does not work and I'm not sure what the format should be.

**Comment by comatory** [comment]
Still haven't figured out how to do this for hosted tiles.
Also, the solution above works but if you cross certain zoom level, tiles disappear.

**Comment by comatory** [comment]
Closing in favor of https://github.com/fleaflet/flutter_map/issues/1029
