### ISSUE TITLE
The method 'of' isn't defined for the type 'MapState'

### ISSUE THREAD

**Issue by sm2017** [fleaflet/flutter_map#950]
```dart
final mapState = MapState.of(context);
```

I upgraded `flutter_map` from `0.12.0` to `0.13.1` and I have `The method 'of' isn't defined for the type 'MapState'` error

Why it's removed? there is nothing in [changelog](https://pub.dev/packages/flutter_map/changelog) and how can I fix it?

**Comment by ibrierley** [comment]
Just wondering, because of nullsafety,  has "of" become "maybeOf" and could that be used ?
