### ISSUE TITLE
[FEATURE] Add screen-based offset capability to `MapController.move`

### ISSUE THREAD

**Issue by comatory** [fleaflet/flutter_map#952]
I want to actually reopen this issue https://github.com/fleaflet/flutter_map/issues/777

I think it would be super useful to have. I have used Mapbox Javascript SDK in the past and would take advantage of their ability to calculate offset via pixels.

My use case is that I have map that takes up the whole screen. Then I have bottom sheet that covers the bottom of the map. Now I want to center / move map to programmatically via `MapController`, the problem is the bottom sheet could cover the point where I want to move. The bottom sheet is also expandable, you can pull it up and down so you never know it's size.

I could get the height of the sheet in pixels before I center or move the map but at the moment, I can't easily do this since the `move` and `moveAndRotate` method does take any parameter. It seems like `fitBounds` uses padding which I'm not sure if it's the same.

I might resort to zooming out a bit to make sure it's not completely covered but it'd be really nice to have this feature.

**Comment by comatory** [comment]
Could someone point me how to implement this? I believe the plugin has to do this internally anyway since `fitBounds` takes padding. Could you point me to relevant code?

Would be great to expose some utilities that do this calculation as well.

**Comment by 1075dn** [comment]
I had to do this too, and ended up having to copy most of the relevant code in [src/map/map.dart](https://github.com/fleaflet/flutter_map/blob/f19cce5c3a2a3d0d9691547fd3bd9e7d8c1d7823/lib/src/map/map.dart#L374) 😞. Hope this helps!

**Comment by heebj** [comment]
I had the same problem and was able to do it with the following lines:
`  LatLng _moveByBottomPadding(LatLng coordinates, double zoomLevel, double bottomOffset) {
    // the following code is copied from unreachable flutter map internas
    final crs = const Epsg3857();
    final oldCenterPt = crs.latLngToPoint(coordinates, zoomLevel);
    final offset = CustomPoint(0, bottomOffset);

    final newCenterPt = oldCenterPt + offset;
    final newCenter = crs.pointToLatLng(newCenterPt, zoomLevel);
    
    return newCenter;
  }`

Would be nice if this is directly provided by the API :-)

**Comment by pawelsa** [comment]
@comatory how do you obtain the size/offset of bottom sheet ?

**Comment by comatory** [comment]
> @comatory how do you obtain the size/offset of bottom sheet ?

There is a way to obtain widget sizes in Flutter, can't tell you from head right now but you use widget's key `currentContext` property: https://stackoverflow.com/questions/49307677/how-to-get-height-of-a-widget

**Comment by comatory** [comment]
Bump. I tried using @heebj but that did not work for me. Could we get this functionality built-in?

**Comment by JaffaKetchup** [comment]
Replaced by #1460. This will be added for v5 by #1532 (2764747)!
