### ISSUE TITLE
Flutter Web support?

### ISSUE THREAD

**Issue by raegtime** [fleaflet/flutter_map#954]
Is there a release for flutter web planed?

**Comment by daraul** [comment]
Has web support been dropped? I've been using it on web for a few days, but I haven't updated.

**Comment by mrtdeh** [comment]
I use flutter web , can be support for web?

**Comment by mauriceraguseinit** [comment]
no reactions here?

**Comment by ibrierley** [comment]
Have you tried it ? It would be useful if someone could actually say what doesn't work, what error they get.

**Comment by daraul** [comment]
It works on web. My initial comment was out of confusion, thinking web support was dropped.

**Comment by luxomansilla** [comment]
It works on web, but we need to zoomin to pointer when scrollin.

**Comment by klaasdannen** [comment]
> It works on web, but we need to zoomin to the pointer when scrollin.

was fixed yesterday.. scroll now works

**Comment by fairlycasual** [comment]
I'm having massive difficulties with the web compilation on mobile browsers. Works like a charm on a normal browser, but even after compiling with canvaskit, my map more often than not does not render, or appears grey. Does anyone have any suggestions here? This is a major sticking point at the moment...
