### ISSUE TITLE
Flutter_Map Zoom issue 

### ISSUE THREAD

**Issue by kapilkiwi** [fleaflet/flutter_map#955]
Flutter_Map perform weird ,when we Zoom  and scroll the map with finger.
when we scroll the map to left it move to another direction or sometimes circular.
Code I am using 
FlutterMap(
                    mapController: _mapController,
                    layers: [
                      TileLayerOptions(
                        urlTemplate:
                            'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                        subdomains: ['a', 'b', 'c'],
                      ),
                      MarkerLayerOptions(markers: _markers),
                    ],
                    options: MapOptions(
                        center: LatLng(40.455051, -98.616661),
                        maxZoom: 18.0,
                        minZoom: 1.0,
                        zoom: 4.0,
                        onPositionChanged: (_, __) {
                          _onMove();
                        }),
                  )

**Comment by JaffaKetchup** [comment]
Please make sure you are using the latest version
