### ISSUE TITLE
Cycled polylines

### ISSUE THREAD

**Issue by mchesnokov** [fleaflet/flutter_map#956]
I have a blue polyline broken since the next point after the one with longitude 179 has longitude -179. 
Is there any option to have a polyline drawn on each world-cycle (-180..180) continuously? 
Thank you.

![polyline](https://user-images.githubusercontent.com/84324375/123790651-3d27de00-d8e7-11eb-8173-9bd5d3b876db.jpg)

**Comment by S-Man42** [comment]
Still waiting for support. Already asked in

#630
#746
