### ISSUE TITLE
Fixing markers to map center

### ISSUE THREAD

**Issue by fedus** [fleaflet/flutter_map#959]
I'd like to implement a way for the user to select a location on the map by showing a cross-hair marker in the center of the map, and then letting the user move the map (with the marker being fixed at the center) so that they can move the desired location under the cross-hair.

This is useful to pick exact locations on the map, where tapping is just not precise enough (because fingers are too thick).

However, there seems to be no "efficient" way to do this. The way I've implemented it right now is to update the marker position on every map move (basically recentering it all the time). An obvious drawback is, is that there is a noticeable and visible lag, ie one can see the marker moving around before it is recentered.

Is there a better way to achieve this or is this a feature that is missing?

Thanks!

**Comment by ibrierley** [comment]
Just thinking out loud...If the marker isn't going to move from the centre, couldn't it just be swapped to some fixed widget or overlay image or something ?

**Comment by fedus** [comment]
> Just thinking out loud...If the marker isn't going to move from the centre, couldn't it just be swapped to some fixed widget or overlay image or something ?

In general that would be one option, however in my case I need the marker (or to be precise, a circle) to grow and shrink together with the map zoom. If I just draw an overlay, I lose this link (unless I'm missing something).

**Comment by ibrierley** [comment]
In that case, can you not base your marker parameters on the state of the mapController zoom & center ? (difficult to understand if you are detecting a change from the mapcontroller or something, then resetting the marker and calling setState()...rather than just having the marker 'point' be the mapController.center within the build method ?). Maybe a bit of code or pseudocode would be useful to clarify how its currently being attempted.

**Comment by fedus** [comment]
I have tried setting the marker's point to the map controller's center at first, but unfortunately that fails.

This is basically my setup:

```
class CrossingMap extends StatefulWidget {
  final LatLng crossingPosition;
  final MapImagery mapImagery;

  CrossingMap({ this.crossingPosition, this.mapImagery });

  @override
  _CrossingMapState createState() => _CrossingMapState();
}

class _CrossingMapState extends State<CrossingMap> {

  MapController mapController;

  @override
  void initState() {
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      mapController: mapController,
      options: MapOptions(
        center: widget.crossingPosition,
        zoom: 20.0,
      ),
      layers: [
        TileLayerOptions(
            urlTemplate: widget.mapImagery.getUrlTemplate,
            maxNativeZoom: 20,
            maxZoom: 22
        ),
        MarkerLayerOptions(
          markers: [
            Marker(
              width: 50.0,
              height: 50.0,
              point: widget.crossingPosition,
              anchorPos: AnchorPos.align(AnchorAlign.center),
              builder: (ctx) => Container(
                child: Icon(Icons.add, size: 50),
              ),
            ),
            Marker(
              width: 10.0,
              height: 10.0,
              point: mapController.center,
              anchorPos: AnchorPos.align(AnchorAlign.center),
              builder: (ctx) => Container(
                child: Icon(Icons.circle, size: 10, color: Colors.blueAccent,),
              ),
            ),
          ],
        ),
        CircleLayerOptions(circles: [
          CircleMarker(
              point: mapController.center,
              color: Colors.blue.withOpacity(0.25),
              borderColor: Colors.blue,
              borderStrokeWidth: 2,
              useRadiusInMeter: true,
              radius: 5 // 2000 meters | 2 km
          ),
        ]),
      ],
    );
  }
}
```

However, this fails with the following:

```
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building CrossingMap(dirty, state: _CrossingMapState#0bf2b):
The getter 'center' was called on null.
Receiver: null
Tried calling: center

The relevant error-causing widget was: 
  CrossingMap file:///home/.../AndroidStudioProjects/.../lib/pages/swipe_screen.dart:274:44
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _CrossingMapState.build (package:.../widgets/crossing_map.dart:69:36)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
```

The exception(s) is/are the lines where I set the markers to mapController.center

I know there are similar issues open with that error. I have tried different ways of initialising the map controller, but without any success.

I'm using flutter_map 0.13.1

Any help would be greatly appreciated. Thank you all for the great work.

**Comment by fedus** [comment]
I should add that when I initialise the map controller like so: 

`MapController mapController = MapController()`

or in the init method:
`
mapController = MapController()`

I also get an exception, but a different one:

```
======== Exception caught by widgets library =======================================================
The following LateError was thrown building CrossingMap(dirty, state: _CrossingMapState#b4b73):
LateInitializationError: Field '_state@403051772' has not been initialized.

The relevant error-causing widget was: 
  CrossingMap file:///home/.../AndroidStudioProjects/.../lib/pages/swipe_screen.dart:274:44
When the exception was thrown, this was the stack: 
#0      MapControllerImpl._state (package:flutter_map/src/map/map.dart)
#1      MapControllerImpl.center (package:flutter_map/src/map/map.dart:55:24)
#2      _CrossingMapState.build (package:.../widgets/crossing_map.dart:66:36)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
```
The origin is again where I assign mapController.center to the marker's point.

**Comment by ibrierley** [comment]
I think there's probably two different issues intermingled there (maybe).

I think for the earlier one, maybe something like listen to the mapController.onReady, and when it changes set some new var like mapControllerReady to true (or possibly simpler, just check if mapController != null)

```
point: mapController != null ? mapController.center : someStartingVal
```
or add CircleMarker(...) if mapController != null to your circles list if you don't want anything there at all until the mapController is ready. I'm assuming the bit mentioned is the CircleMarker, but adjust to elsewhere if not.

For the second issues (late initialisation), it's not clear where mapController is getting initialised. I note that you have a file called "swipe_screen.dart". Does this happen when returning from some other navigation ? If so, I've got around that issue in the past by having the flutter_map (and any parent relevant widgets to that nav screen) in an Offstage widget. Then it never gets removed from the Widget Tree.

**Comment by fedus** [comment]
So, I got it to work based on your suggestions, even though it's very similar to my starting point (I've managed to eliminate the step where I would "copy" the center of the map into its own property, to which the `point` of the marker is set).

However, a couple of notes:
1) I had to use a boolean flag in combination with `onReady`. Just using a ternary for `point` did not work since the widget would not rebuild when mapController is not null anymore. Thus I had to set the boolean flag in `onReady` using `setState` explicitly to make it work.
2) I also had to add:
```
        onPositionChanged: (position, hasGesture) {
          setState(() {});
        }
```
in the map options to make it work, the logic is the same as for for point 1.

It seems much more fluent now than my first implementation. Would you say this is as efficient as it gets?

Thanks again for your help and fast response time!

**Comment by fedus** [comment]
So, another issue popped up.

The above solution works during hot reload, but actually on the first real rebuild of the app, the following exception is thrown:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building LayoutBuilder:
setState() or markNeedsBuild() called during build.
```

Which makes sense - I just don't know how to work around it. In fact, this is why I wound up with my first solution actually (setting a dedicated LatLng property to the map controller's center in the next frame in a setState()) ...

**Comment by ibrierley** [comment]
Instead of setState(), try 
```
 WidgetsBinding.instance.addPostFrameCallback((_) {
  // executes after build
})
```

**Comment by ibrierley** [comment]
I'm surprised you need to use that at all tbh (same with setState), apart from maybe the first time after the mapController onReady is called maybe ?

**Comment by fedus** [comment]
Using WidgetsBinding... results in a small but noticeable lag: the marker moves away from the center on map drag, and in the next frame "corrects" this by moving back to the center (as expected by the code).

> I'm surprised you need to use that at all tbh (same with setState), apart from maybe the first time after the mapController onReady is called maybe ?

Yes it's very cumbersome, but if I don't call setState(), the marker doesn't update to the changed map controller's center. The whole snippet is pasted above - I can't see any obvious mistakes though ...

**Comment by ibrierley** [comment]
Oh I see I think, the outer widget setState isn't called automatically, so that value will never get checked doh.. Maybe you could create a markerWidget that has a builder listening to the mapController stream or something, which would just reposition the marker, rather than refresh the whole map, but possibly starts to feel a bit convoluted then, and may just look the same in fact as there's possibly a slight delay again. hmm

**Comment by fedus** [comment]
I think your analysis is right, about the outer widget's setState not being called. So for now, I got it working as follows (a bit clunky and cumbersome, but does the job):

```
class _CrossingMapState extends State<CrossingMap> {

  MapController mapController;
  bool controllerReady = false;
  bool buildFinished = false;

  @override
  void initState() {
    super.initState();
    mapController = MapController();
    mapController.onReady.then((value) {
      setState(() {
        controllerReady = true;
      });
    });
    WidgetsBinding.instance
        .addPostFrameCallback((_) => buildFinished = true);
  }

  void _handleMove(position, hasGesture) {
    if (buildFinished) setState(() {});
  }


  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      mapController: mapController,
      options: MapOptions(
        //interactiveFlags: InteractiveFlag.none,
        center: widget.crossingPosition,
        zoom: 20.0,
        onPositionChanged: _handleMove
      ),
      layers: [
        TileLayerOptions(
            urlTemplate: widget.mapImagery.getUrlTemplate,
            maxNativeZoom: 20,
            maxZoom: 22
        ),
        MarkerLayerOptions(
          markers: [
            Marker(
              width: 50.0,
              height: 50.0,
              point: widget.crossingPosition,
              anchorPos: AnchorPos.align(AnchorAlign.center),
              builder: (ctx) => Container(
                child: Icon(Icons.add, size: 50),
              ),
            ),
            Marker(
              width: 10.0,
              height: 10.0,
              point: controllerReady ? mapController.center : widget.crossingPosition,
              anchorPos: AnchorPos.align(AnchorAlign.center),
              builder: (ctx) => Container(
                child: Icon(Icons.circle, size: 10, color: Colors.blueAccent,),
              ),
            ),
          ],
        ),
        CircleLayerOptions(circles: [
          CircleMarker(
              point: controllerReady ? mapController.center : widget.crossingPosition,
              color: Colors.blue.withOpacity(0.25),
              borderColor: Colors.blue,
              borderStrokeWidth: 2,
              useRadiusInMeter: true,
              radius: 5 // 2000 meters | 2 km
          ),
        ]),
      ],
    );
  }
}
```

I need `controllerReady` because if I just use `mapController != null` in the ternary for the marker's `position`, the state change is not detected and therefore, the position is not updated to the center.

I need `buildFinished`, because `_handleMove` is also triggered when the outer widget first builds, and in that case calling setState() triggers an exception (can't trigger a rebuild while widget is building).

Compared to my initial solution, this one is faster (you can still detect a very slight jitter in the widgets that are supposed to stay fixed to the center, but it's negligeable now).

There's room for improvement, but I'm closing this ticket with this comment.

Thanks for your help!

**Comment by ibrierley** [comment]
Super, thanks for the update.
