### ISSUE TITLE
Robust polygon drawing functionality

### ISSUE THREAD

**Issue by prl900** [fleaflet/flutter_map#961]
The #790 approach to draw polygons works well. I have managed to implement polygon drawing functionality using the `onTap`. Users can create polygons interactively by clicking on the screen. This gets visualised using `PolylineLayerOptions`. When users close the polygon by clicking on the first point the result gets visualised using `PolygonLayerOptions`.

However, I'm having trouble determining when the first point of the polygon gets clicked for closing it. I have implemented an approach in which every tapped LatLon position gets compared to the initial one using a threshold. The problem is that this threshold should be dependent on the zoom level, to allow users drawing polygons of any size. Ideally, this should be done using screen pixel positions rather than LatLon values, although I'm not sure if this is possible.

I reckon I could use the zoom level information to work out the relative distance between tapped points in the screen, although I'm not sure what is the best approach here.

I'd appreciate it if anyone has a suggestion or code samples for coding a robust polygon drawing functionality that works at any scale.

**Comment by ibrierley** [comment]
Do they need to click on the last bit, can it be assumed to automatically close if its a Poly ? Just wondering if my line_editor is any use there... i.e   https://github.com/ibrierley/flutter_map_line_editor/tree/nullsafety (has a gif showing it in effect at the bottom).

**Comment by JaffaKetchup** [comment]
Not sure if this would be useful:
https://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by prl900** [comment]
Thank you @ibrierley and @JaffaKetchup! I like the suggestion of assuming the shapes are closed polygons. It's much easier than having to deal with relative zoom levels. I also like the option of editing by bisecting the segments, really neat!

I will give the line_editor a go in my app. Cheers

**Comment by ibrierley** [comment]
Just note there's a null safety branch

**Comment by killerm250m** [comment]
> #790

Hi, can you please share the polygon/polyline drawing code?
