### ISSUE TITLE
Style from .Json - similar GoogleMapController.setMapStyle(_MyJsonStyle);

### ISSUE THREAD

**Issue by MateusONunes** [fleaflet/flutter_map#967]
Loading Style from .Json similar Google_maps_flutter does with GoogleMapController.setMapStyle(_MyJsonStyle);

Is it possible in Flutter_Map? If not, is it too difficult to implement this in Flutter_Map?

We are in need of this solution and we are considering the possibility of developing it.

thanks

**Comment by ibrierley** [comment]
If I understand it correctly, it's not currently possible with flutter_map as it currently uses raster tiles. There's a couple of attempts at getting vector tiles working, but they aren't production ready imo (I'm doing one of them, and I know mine isn't ;D), but are ok to explore. There's a number of canvas performance issues there which makes it quite hard (we can convert vectors to raster on the fly, but it still takes a bit of grunt).

Depending on your needs, probably the best bet is to try and get some raster tiles that are close to the style you want (or even provide them yourself I guess). Some providers have a few theme variations that can be used.

You could also take a look at flutter mapbox gl and as you know google maps flutter which you've mentioned.
