### ISSUE TITLE
example for polygon/polyline drawing

### ISSUE THREAD

**Issue by killerm250m** [fleaflet/flutter_map#969]
Hi, anyone can provide an example for shape drawing like polygon, polyline.

**Comment by ibrierley** [comment]
There should be a polyline example in the examples folder.

**Comment by killerm250m** [comment]
> There should be a polyline example in the examples folder.

Yeah I checked it but I need an example for polygon drawing

**Comment by killerm250m** [comment]
Nevermind I find a great plugin here: https://github.com/ibrierley/flutter_map_line_editor
