### ISSUE TITLE
Fill closed Polyline with different color than border

### ISSUE THREAD

**Issue by S-Man42** [fleaflet/flutter_map#972]
In `Polyline` options you can insert both, `color` and `borderColor`. So, I guess, it should be possible to enter different colors for the outline and the filling, correct? However, this seems not work:

1. When entering both: `color` is taken as outline color. No filling, `borderColor` is ignored.

Is it possible to

1. Fill the closed polyline
2. Make the color different to its border?

**Comment by JaffaKetchup** [comment]
Can you just use a `PolygonLayerOptions`? That fill and border can be different colours.

**Comment by S-Man42** [comment]
Hi,

I cannot see, that the `PolygonLayerOptions` itself has a color attribute, but `Polygon` of course.

Unfortunately I have no polygons, but polylines (some of them are closed, which, of course, makes them a polygon: These are the ones I want to fill).

Moreover, as far as I can see, `Polygon` and `Polyline` have the same set of options when it comes to colors:

  final Color color;
  final double borderStrokeWidth;
  final Color? borderColor;
  
Why should Polygons act differently here?

I need the Polylines, because I need them tappable (adding a Tap Listener), which is done but the plugin `flutter_map_tappable_polyline`. So I am trying to achive this for Polylines, and it's not clear to me, why there are different color options, but they do not work as I expect it.

**Comment by JaffaKetchup** [comment]
I'm not sure. Try increasing the stroke width of your polyline? It could be that color is actually a fill color of the line, and border color is a color of the line's border?

**Comment by S-Man42** [comment]
Hm this might be, actually. However, that wouldn't solve my probleme anyway. I need to fill closed area created by a polyline.

**Comment by JaffaKetchup** [comment]
In that case you'll need to use Polygon. I'm not sure how you can get a tap listener, however.

**Comment by JaffaKetchup** [comment]
Please see #968 for an issue of adding tap handlers to polygons.

**Comment by Birdy2404** [comment]
We would still be interessted in this topic.

**Comment by S-Man42** [comment]
Still requested

**Comment by S-Man42** [comment]
Still required

**Comment by Birdy2404** [comment]
This topic is still interesting for US.

**Comment by S-Man42** [comment]
still interested

**Comment by S-Man42** [comment]
still interested

**Comment by JaffaKetchup** [comment]
I'm going to close this now. For this use-case, a polygon with tap detection would be more appropriate. Please see #385 for the latest discussions on this - hopefully something can be done sooner rather than later.
Thanks for raising. Let me know if you think this shouldn't be closed in favour of that issue, and I will reconsider.
