### ISSUE TITLE
LateInitializationError with polygonCulling in PolygonLayerOptions

### ISSUE THREAD

**Issue by Kacper1263** [fleaflet/flutter_map#974]
Hi, after updating Flutter Map to 0.13.1 when I set polygonCulling to true in PolygonLayerOptions I'm receiving `LateInitializationError: Field 'boundingBox' has already been initialized`, everything is working fine with polygonCulling set to false

**Comment by mchesnokov** [comment]
It is because it is trying to set boundingBox, which is final. You may try to make it not final. But in case of polylines culling doesn't seem to work after doing so.
