### ISSUE TITLE
Maps not loading on Netlify

### ISSUE THREAD

**Issue by MihailDundukov** [fleaflet/flutter_map#976]
Can you say me please how to fix this ploblem? I use urlTemplate: 'http://tiles.maps.sputnik.ru/{z}/{x}/{y}.png'. In debug mode its ok, but on Netlify maps not showing me

**Comment by ibrierley** [comment]
Need more info really. Check you have internet enabled in your android release directory AndroidManifest.xml though if nothing works in release mode. But not sure with netlify if you are using web only or something, I've never used that so can't help there.
