### ISSUE TITLE
Drawing huge number of polygons

### ISSUE THREAD

**Issue by killerm250m** [fleaflet/flutter_map#984]
Hello,
I am trying to draw a large number of polygons (over 500 for defining houses and properties)  in the polygon layer, but it affects performance badly when I want to zoom in/out, or moving the map, Is there any workaround to optimize the drawing?

**Comment by JaffaKetchup** [comment]
Hi,
This is, unfortunately, normal, as seen in a previous issue/PR tying to optimize marker calculations. Its computationally expensive, so it's going to be slow.

**Comment by killerm250m** [comment]
> Hi,
> This is, unfortunately, normal: #826 is the PR to optimize marker calculations, but it didn't touch anything else.
> Its computationally expensive, so it's going to be slow. It's possible it could be done faster, as seen in the aforementioned PR, but this would be a PR (which takes time here in flutter_map 😅).

Can I do the same thing on the polygons?

**Comment by JaffaKetchup** [comment]
As I said, maybe (I haven't really looked), but you'll have to submit a PR and wait for it to get merged, which takes a while.

**Comment by killerm250m** [comment]
> As I said, maybe (I haven't really looked), but you'll have to submit a PR and wait for it to get merged, which takes a while.

Can you give me some tips on how I can optimize the polygon drawing?

**Comment by JaffaKetchup** [comment]
No, as I've already said, I have no idea how those internals work.

**Comment by killerm250m** [comment]
> No, as I've already said, I have no idea how those internals work, sorry.

Okay, Thanks man.
