### ISSUE TITLE
[help] how can I custom the bbox

### ISSUE THREAD

**Issue by xiaoao** [fleaflet/flutter_map#995]
my bbox is 102.232112,0.74775  104.011123,2.154979, not 180,-90

**Comment by JaffaKetchup** [comment]
Can you give some more information please?

**Comment by xiaoao** [comment]
const resolutions = <double>[32768, 16384, 8192, 4096, 2048, 1024, 512, 256, 128];
var maxZoom = (resolutions.length - 1).toDouble();
var epsg4326 = Proj4Crs.fromFactory(
    code: 'EPSG:4326',
    proj4Projection:  proj4.Projection.get('EPSG:4326')!,
    resolutions: resolutions,
    bounds: Bounds(CustomPoint(102.232112,0.74775), CustomPoint(104.011123,2.154979)),
  );
TileLayerWidget(options: TileLayerOptions(
          wmsOptions: WMSTileLayerOptions(
            baseUrl: 'https://*****/wms?',
            layers: ['mylayer'],
            crs: epsg4326,
            version: "1.1.1",
          ),
        ),),
